[How to guides] Creating a Room
wechaty/docusaurus pull request #1011
Opened 2021-07-04 08:47 UTC by vasvi-sood

![manage-room1](https://user-images.githubusercontent.com/76619050/124379087-9078a280-dcd2-11eb-9218-7836c8d29124.png)
![manage-room2](https://user-images.githubusercontent.com/76619050/124379089-92dafc80-dcd2-11eb-85ee-4dc8485bef16.png)
![mange-room3](https://user-images.githubusercontent.com/76619050/124379090-953d5680-dcd2-11eb-9427-245950cc0f9c.png)
![mange-room4](https://user-images.githubusercontent.com/76619050/124379092-979fb080-dcd2-11eb-88e3-f578f098dad9.png)

2021-07-04 09:38 UTC, abhishek-iiit commented
Linked to issue #896

2021-07-08 15:55 UTC, proudofsimin approved these changes, later dismissed

2021-07-11 12:44 UTC, Rohitesh-Kumar-Jain approved these changes, later dismissed
PR looks good, but not sure that we need to put the output image there as well?

2021-07-14 05:02 UTC, vasvi-sood commented
> PR looks good, but not sure that we need to put the output image there as well?

I thought, maybe that would be more intuitive. Should I remove it?

2021-07-18 10:27 UTC, Rohitesh-Kumar-Jain commented
> > PR looks good, but not sure that we need to put the output image there as well?
> 
> I thought, maybe that would be more intuitive. Should I remove it?

I leave that to you

2021-07-22 09:06 UTC, abhishek-iiit submitted a review, later dismissed
Rohitesh is correct, I guess we don't need all of those output images for these similar sections. Can we drop these Output image, if it grants ?

2021-09-07 19:00 UTC, huan requested changes
I saw you remove all the source codes from the `room.md`, could you please let me know what's the reason behind doing that?

I believe the most important part of the howto guides is the polyglot howto guides, which should demonstrate how to achieve a series of room related tasks.

And for our howto guides, all polyglot languages are needed, which should includes TypeScript, Python, Go, Java, etc...

2021-09-10 10:34 UTC, vasvi-sood commented
> I saw you remove all the source codes from the `room.md`, could you please let me know what's the reason behind doing that?
> 
> I believe the most important part of the howto guides is the polyglot howto guides, which should demonstrate how to achieve a series of room related tasks.
> 
> And for our howto guides, all polyglot languages are needed, which should includes TypeScript, Python, Go, Java, etc...

The  code snippets provided were giving an error, when I tried to run them. So using the introduction and reference section, I created new code snippets in the JavaScript language (which were actually working). And since I am not familiar with the code for wechaty  in other languages, I have left it blank. Please provide me with he code snippets in other languages for the function I have written, I would be happy to make the necessary changes.

2021-09-17 17:20 UTC, vasvi-sood commented
Please review it @huan, so that

> > I saw you remove all the source codes from the `room.md`, could you please let me know what's the reason behind doing that?
> > I believe the most important part of the howto guides is the polyglot howto guides, which should demonstrate how to achieve a series of room related tasks.
> > And for our howto guides, all polyglot languages are needed, which should includes TypeScript, Python, Go, Java, etc...
> 
> The code snippets provided were giving an error, when I tried to run them. So using the introduction and reference section, I created new code snippets in the JavaScript language (which were actually working). And since I am not familiar with the code for wechaty in other languages, I have left it blank. Please provide me with he code snippets in other languages for the function I have written, I would be happy to make the necessary changes.

Kindly review it @huan, so that I may proceed to merging it.

2021-09-18 18:14 UTC, lijiarui requested changes
Hi @abhishek-iiit 

I suggest:

1. Use an mdx file, then you can add a tab in the markdown
2. Refer to the latest example and add an example link to the blog. The latest example is: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/room-bot.js

2021-09-18 18:14 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +1. [Node.js](https://nodejs.org/en/download) v12+
v12+ ---> v16

2021-09-24 17:55 UTC, vasvi-sood commented
changes done as suggested @lijiarui

2021-09-28 16:43 UTC, lijiarui commented
Hi @vasvi-sood Please resolve the conflict first.

2021-10-02 07:56 UTC, vasvi-sood commented
> Hi @vasvi-sood Please resolve the conflict first.

done

2021-10-16 16:15 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood pls help turn the CI turn green :)

2021-10-16 19:23 UTC, huan commented
> The code snippets provided were giving an error, when I tried to run them. So using the introduction and reference section, I created new code snippets in the JavaScript language (which were actually working). And since I am not familiar with the code for wechaty in other languages, I have left it blank. Please provide me with he code snippets in other languages for the function I have written, I would be happy to make the necessary changes.

Could you please restore all the other languages' code?

You can leave them blank for now, and we will fill them in the future.

2021-10-17 09:01 UTC, lijiarui requested changes

2021-10-17 09:01 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +}           = require('wechaty')
We should use import instead of require here, see : https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/room-bot.js#L50

2021-10-17 09:01 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +const contactList=[];
In the js part, you should make it same as typescript, but now, some important part seems to be cut.

2021-10-17 09:01 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +### Linux/macOS
We should use a tab as we did in polyglop wechaty to show Linux and windows code.

2021-10-28 11:40 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit and @vasvi-sood pls address the requested changes

2021-10-28 11:59 UTC, abhishek-iiit commented
Sorry for the delay. We are in a talk to resolve this as soon as possible within 2 days, as Vasvi was facing health issue 😅

2022-03-30 12:07 UTC, huan commented
Close this PR in favor of 

- wechaty/wechaty.js.org#1

2022-03-30 12:07 UTC, closed without merging