Week-7 Wechaty Polyglot
wechaty/docusaurus pull request #1013
Opened 2021-07-04 11:46 UTC by shraddhavp

This PR has the updated documented Wechaty polyglot section and it links #890 .

2021-07-04 15:49 UTC, shraddhavp commented
@Rohitesh-Kumar-Jain  and @proudofsimin please have a look at the PR and do give your feedbacks ,thanks

2021-07-05 18:58 UTC, iamrajiv requested changes

2021-07-05 18:58 UTC, iamrajiv commented on docusaurus/docs/polyglot/overview.mdx
> +If you are a total beginner to Wechaty, this project is the best starting point for you. You can run it on a Cloud IDE in a couple of steps or on a locally on your machine.
```suggestion
If you are a total beginner to Wechaty, this project is the best starting point for you. You can run it on a Cloud IDE in a couple of steps or locally on your machine.
```

2021-07-05 18:58 UTC, iamrajiv commented on docusaurus/docs/polyglot/overview.mdx
> +* It works in all operating systems like on Linux, Mac or Windows.
```suggestion
* It works in all operating systems like Linux, Mac, or Windows.
```

2021-07-05 18:58 UTC, iamrajiv commented on docusaurus/docs/polyglot/overview.mdx
> +### Running Wechaty Getting Started Project on a cloud based IDE
```suggestion
### Running Wechaty Getting Started Project on a cloud-based IDE
```

2021-07-05 18:58 UTC, iamrajiv commented on docusaurus/docs/polyglot/overview.mdx
> +If you are a total beginner, then we recommed Gitpod.
```suggestion
The fastest way to get started with Wechaty is to use a Cloud-based IDE for running the Wechaty Getting Started Project. You can either use Gitpod or Google Cloud Shell.
If you are a total beginner, then we recommend Gitpod.
```

2021-07-05 18:58 UTC, iamrajiv commented on docusaurus/docs/polyglot/overview.mdx
> +You can learn more about Gitpod  Wechaty from our blog: [Getting Started Without Leaving Your Browser: Wechaty Gitpod, @huan, Feb 06, 2021](https://wechaty.js.org/2021/02/06/wechaty-getting-started-w
```suggestion
Gitpod is an online and open-source platform for automated and ready-to-code development environments. If you have never used Gitpod before, you will be required to log in using your GitHub account.
You can learn more about Gitpod  Wechaty from our blog: [Getting Started Without Leaving Your Browser: Wechaty Gitpod, @huan, Feb 06, 2021](https://wechaty.js.org/2021/02/06/wechaty-getting-started-without-leave-your-browser/)
```

2021-07-05 18:58 UTC, iamrajiv commented on docusaurus/docs/polyglot/overview.mdx
> +After opening the Google Cloud Shell editor, there  it should open  a tutorial in the right panel which you can follow to learn more about Wechaty.
```suggestion
After opening the Google Cloud Shell editor, there should open a tutorial in the right panel which you can follow to learn more about Wechaty.
```

2021-07-08 16:18 UTC, proudofsimin reviewed
Hi, could you mention and link these two from the tutorials? #922 and #923 (I guess they will be merged soon).Thank you.

2021-07-09 03:07 UTC, shraddhavp commented
> Hi, could you mention and link these two from the tutorials? #922 and #923 (I guess they will be merged soon).Thank you.

yes will add them once both are merged

2021-07-12 14:11 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-19 16:05 UTC, shraddhavp commented
@proudofsimin  have updated the docs with the new links,please do check out the PR and let me  know if any feedbacks 
Thanks

2021-08-01 09:04 UTC, proudofsimin approved these changes

2021-09-07 19:05 UTC, huan requested changes

2021-09-07 19:05 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -<ShortestChatbots />
I'd like to keep this code example in this overview docs.

Or could you please let me know why you believe it should be removed?

2021-09-07 19:05 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -## Getting Started Templates {#getting-started-templates}
The `polyglot` docs are under the **references** section, which means that they are technical descriptions of the machinery and how to operate it.

they should be information-oriented, austere, and to the point. <https://documentation.divio.com/reference/>

So I believe the `getting started` part in this docs is not necessary.

Please feel free to let me know if you have any questions.

2021-09-07 19:05 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -- [Python the Wechaty Way wechaty/python-wechaty#13](https://github.com/wechaty/python-wechaty/issues/13)
Please keep those links because they are very informative and helpful.

2021-09-08 11:28 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> -## Getting Started Templates {#getting-started-templates}
yes @huan as the current polyglot version started a bit abruptly hence just gave a bit of intro and gave links to tutorials page for info

2021-09-08 16:28 UTC, shraddhavp commented
@huan  have done the requested changes please check if any changes

2021-09-09 09:48 UTC, huan requested changes

2021-09-09 09:48 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -<GettingStartedTemplates />
Why do we remove the `<GettingStartedTemplates />`? 

Could you please share your thoughts about this change, because I think it's an important part for the readers?

2021-09-09 09:48 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> +#### Using Google Cloud Shell
The `polyglot/` docs are under **References**, which means that it should be straightforward, information-oriented, austere, and to the point.

> Reference guides are technical descriptions of the machinery and how to operate it. --- [Documentation System](https://documentation.divio.com/reference/)

I think we can remove all the getting-started related information in this docs, hence the "Using Google Cloud Shell" is not necessary.

2021-09-09 09:48 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -- [Multi Language Wechaty Beta Release Announcement!](https://wechaty.js.org/2020/06/19/multi-language-wechaty-beta-release/)
The release announcement is import for this docs, please keep it.

2021-09-09 09:50 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -Wechaty in all programming languages have the same API, as the TypeScript documented version.
This sentence is import, please keep it.

2021-09-09 09:52 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> -Wechaty in all programming languages have the same API, as the TypeScript documented version.
@huan  yes it is mentioned in all the different languages docs , only here it is removed to avoid repetition

2021-09-09 09:52 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> +#### Using Google Cloud Shell
ok will do so

2021-09-09 09:54 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> -- [Multi Language Wechaty Beta Release Announcement!](https://wechaty.js.org/2020/06/19/multi-language-wechaty-beta-release/)
yes it is kept

2021-09-09 09:56 UTC, shraddhavp commented
@huan  have done the requested changes ,please do let me know if any more changes ,Thank you

2021-09-09 10:02 UTC, iamrajiv approved these changes

2021-09-09 11:26 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -<ShortestChatbots />
Could we keep this?

2021-09-09 11:26 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -- [Python the Wechaty Way wechaty/python-wechaty#13](https://github.com/wechaty/python-wechaty/issues/13)
Could we keep this?

2021-09-09 11:29 UTC, huan commented
Please read my reviews carefully and follow my comments before you request my review next time.

Thank you very much.

2021-09-09 11:30 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -<GettingStartedTemplates />
Could we keep this?

2021-09-09 11:30 UTC, huan commented on docusaurus/docs/polyglot/overview.mdx
> -- [Python the Wechaty Way wechaty/python-wechaty#13](https://github.com/wechaty/python-wechaty/issues/13)
Could we keep this???

2021-09-10 12:00 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> -<GettingStartedTemplates />
@huan  yes have added it

2021-09-10 12:01 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> +#### Using Google Cloud Shell
@huan  have removed all the "Using Google Cloud Shell" part from the doc as suggested

2021-09-10 17:07 UTC, Soumi7 approved these changes
LGTM

2021-09-10 18:02 UTC, huan requested changes
I'd like to keep this code (<ShortestChatbots />) example in this overview docs.

Could we keep this?

2021-09-11 04:53 UTC, shraddhavp commented on docusaurus/docs/polyglot/overview.mdx
> -<ShortestChatbots />
@huan  done

2021-09-11 05:31 UTC, huan approved these changes
LGTM

2021-09-11 06:15 UTC, merged