Deployment with Docker
wechaty/docusaurus pull request #1028
Opened 2021-07-08 05:47 UTC by abhishek-iiit

# Added Deployment with Docker
![Screenshot from 2021-07-08 11-02-34](https://user-images.githubusercontent.com/69477761/124868026-c7a1c900-dfdc-11eb-9286-d8f2a5770996.png)
![Screenshot from 2021-07-08 11-02-46](https://user-images.githubusercontent.com/69477761/124868030-c96b8c80-dfdc-11eb-8894-96aa79a69997.png)
![Screenshot from 2021-07-08 11-02-58](https://user-images.githubusercontent.com/69477761/124868034-ca042300-dfdc-11eb-8f01-72858caab283.png)
![Screenshot from 2021-07-08 11-03-34](https://user-images.githubusercontent.com/69477761/124868039-cb355000-dfdc-11eb-8566-a6e3882f2e13.png)

2021-07-08 05:59 UTC, abhishek-iiit commented
Linked to issue #896

2021-07-10 09:31 UTC, proudofsimin approved these changes
Please correct some minor issues and this one is great.

2021-07-10 09:31 UTC, proudofsimin commented on docusaurus/docs/howto/howto_docker.md
> +10. `mybot.js` : File contains code wrote by you, should be placed in current directory `./`
It would be better if we change to bulleted list as it's not related to step sequence.

2021-07-10 09:31 UTC, proudofsimin commented on docusaurus/docs/howto/howto_docker.md
> +* See Also: [Dockerize Wechaty for easy start #66](https://github.com/wechaty/wechaty/issues/66)
remove the bulleted point.

2021-07-10 09:31 UTC, proudofsimin commented on docusaurus/docs/howto/howto_docker.md
> +* Uninstall any older versions of Docker such as `docker`, `docker.io`, or `docker-engine`, if installed.
* If you have installed any older versions of Docker, including `docker`, `docker.io`, or `docker-engine`, uninstall it.
(Conditional clause goes first)

2021-07-10 09:31 UTC, proudofsimin commented on docusaurus/docs/howto/howto_docker.md
> +To get familiar with the Docker Environment ,you can try [Runing hello-world under 3 minutes with Docker](https://docs.docker.com/get-started/)
space should be after the comma, and you missed a period at the end.

2021-07-11 12:37 UTC, Rohitesh-Kumar-Jain approved these changes
Checked for content, grammar, and spellings, and the PR is properly based.

2021-07-14 05:12 UTC, vasvi-sood approved these changes
This PR looks Great!

2021-07-14 05:12 UTC, vasvi-sood commented on docusaurus/docs/howto/howto_docker.md
> +The best practice of using Wechaty Docker is like the following:
The best practice of using Wechaty Docker is as follows:

2021-07-18 21:44 UTC, lijiarui requested changes

2021-07-18 21:44 UTC, lijiarui commented on docusaurus/docs/howto/howto_docker.md
> +wechaty media-file-bot.ts
It seems wired using `wechaty media-file-bot.ts` Maybe we should run ding-dong bot here?

2021-07-18 21:44 UTC, lijiarui commented on docusaurus/docs/howto/howto_docker.md
> +```
It would be better if you could add how to install docker under Linux,Mac,and Windows, and use mdx files like this: http://wechaty.js.org/docs/getting-started/running-locally

2021-07-19 18:40 UTC, abhishek-iiit commented on docusaurus/docs/howto/howto_docker.md
> +wechaty media-file-bot.ts
Yaa sure!, it actually becomes easy when using ding-dong bot. Ok will change the recommended changes

2021-07-29 15:36 UTC, lijiarui requested changes
I cannot find this in the left nav bar

![image](https://user-images.githubusercontent.com/6419514/127521815-ecdbfbb6-02ba-421e-b5ba-734421fe9668.png)

2021-08-23 16:52 UTC, lijiarui requested changes, later dismissed

2021-08-23 16:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Deploy with Docker](howto/howto_docker.mdx)
Please change to `docker` here, making the link more beautiful

2021-08-23 16:52 UTC, lijiarui commented on docusaurus/sidebars.ts
> +    'howto/howto_docker',
Please change to docker here.

2021-08-24 05:39 UTC, Rohitesh-Kumar-Jain approved these changes

2021-08-24 06:17 UTC, abhishek-iiit commented on docusaurus/sidebars.ts
> +    'howto/howto_docker',
Thankyou Iijiarui, changes done as suggested :)

2021-09-07 19:10 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-13 22:39 UTC, abhishek-iiit commented
Merging PR with no conflicts and 4 approvals :)

2021-09-13 22:42 UTC, merged