Create 2018-08-26-Thoughts-About-AI-Bot-WeChaty
wechaty/docusaurus pull request #105
Opened 2018-08-28 08:36 UTC by lirobin1998

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2018-08-28 15:22 UTC, lijiarui requested changes
Thanks for your pull request.
1 . Please change the filename from `2018-08-26-Thoughts-About-AI-Bot-WeChaty` to `2018-08-26-thoughts-about-ai-bot-wechaty.md`
2. Please use markdown form instead of the raw text form.
3. See more guidline in [CONTRIBUTE GUIDELINE](https://github.com/chatie/blog#contribute-guideline)

2018-08-30 09:42 UTC, lijiarui requested changes
Please change as I request, and:

Change the filename from `2018-08-26-Thoughts-About-AI-Bot-WeChaty` to `2018-08-26-thoughts-about-ai-bot-wechaty.md`

2018-08-30 09:42 UTC, lijiarui commented on _posts/2018-08-26-Thoughts-About-AI-Bot-WeChaty
> +# AI、Bot、WeChaty相关思考
Please add the header at the top of this blog:

```
---
 layout: post
 title: "AI、Bot、WeChaty相关思考"
 date: 2018-08-30 09:00 +0800
 author: lirobin1998
 ---
 
 > Author: [@李彬](https://github.com/lirobin1998) ，清华大学博士。硅谷智慧科技公司创始人，贵州博士科技有限公司CEO。聚焦智慧AI创新创业，从AI科普教育切入，开展人机智慧智能开发教育，打造全民AI教育开放平台。30年前在清华大学电子工程系开始研究机器翻译，20年前到硅谷开始学习探索智慧智能科技，10年硅谷与国内高科技创业经历。

```

2018-08-30 09:42 UTC, lijiarui commented on _posts/2018-08-26-Thoughts-About-AI-Bot-WeChaty
> +
add `<!--more-->` here

2018-08-30 09:42 UTC, lijiarui commented on _posts/2018-08-26-Thoughts-About-AI-Bot-WeChaty
> +> 李彬，清华大学博士。硅谷智慧科技公司创始人，贵州博士科技有限公司CEO。聚焦智慧AI创新创业，从AI科普教育切入，开展人机智慧智能开发教育，打造全民AI教育开放平台。30年前在清华大学电子工程系开始研究机器翻译，20年前到硅谷开始学习探索智慧智能科技，10年硅谷与国内高科技创业经历。
move this to the top of the blog as I showed.

2018-08-31 00:59 UTC, lirobin1998 commented
created a new pull request. I am closing this pull request.

2018-08-31 00:59 UTC, closed without merging