Updated polyglot Go
wechaty/docusaurus pull request #1050
Opened 2021-07-11 14:00 UTC by shraddhavp

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-07-12 14:09 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for adding the beautiful image

2021-07-15 15:21 UTC, proudofsimin approved these changes
Fantastic! Thank you.

2021-07-15 16:22 UTC, Rohitesh-Kumar-Jain commented
@Soumi7 I would be glad if you like to go through the PR once, and would like to suggest some changes, or approve the PR if it's looking good.

2021-07-17 06:06 UTC, Soumi7 requested changes
Apart from the minor requested changes, this looks good to me.

2021-07-17 06:06 UTC, Soumi7 commented on docusaurus/docs/polyglot/go/overview.md
> +More details on  Go Wecahty And WeChat Web Protocol can be [check here](https://wechaty.js.org/2021/04/16/go-wechaty-use-web/).
Go Wechaty (spelling)

2021-07-17 06:06 UTC, Soumi7 commented on docusaurus/docs/polyglot/go/overview.md
> +More details on  Go Wecahty And WeChat Web Protocol can be [check here](https://wechaty.js.org/2021/04/16/go-wechaty-use-web/).
Also spaces after full stops.

2021-07-17 07:36 UTC, Soumi7 approved these changes
LGTM

2021-07-18 21:49 UTC, lijiarui requested changes

2021-07-18 21:49 UTC, lijiarui commented on docusaurus/docs/polyglot/go/overview.md
> -Template Repo: <https://github.com/wechaty/go-wechaty-getting-started>
I suggest we change back the template repo because go repo is important for new developers. Even though you have git clone repo in the command line, but it seems not that obvious.

2021-07-19 14:32 UTC, shraddhavp commented
@lijiarui  mam have added the changes you mentioned

2021-07-29 15:51 UTC, lijiarui requested changes, later dismissed

2021-07-29 15:51 UTC, lijiarui commented on docusaurus/docs/polyglot/go/overview.md
> -- Getting Started Template Repo <https://github.com/wechaty/go-wechaty>
I suggest we keep these 3 links back.

2021-07-29 15:51 UTC, lijiarui commented on docusaurus/docs/polyglot/go/overview.md
> +* [go-wecahty and web protocol to develop robots, @dchaofei, Apr 16, 2021](https://wechaty.js.org/2021/04/16/go-wechaty-use-web/)
go-wecahty --> go-wechaty

2021-07-30 12:55 UTC, shraddhavp commented on docusaurus/docs/polyglot/go/overview.md
> -- Getting Started Template Repo <https://github.com/wechaty/go-wechaty>
yes mam have added it one in intro section and other in getting started section

2021-07-30 12:57 UTC, shraddhavp commented
@lijiarui  mam have done the changes suggested

2021-09-07 19:13 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-11 05:22 UTC, shraddhavp commented
@lijiarui  mam can you please review the PR all the changes requested have been completed

2021-09-11 17:05 UTC, iamrajiv approved these changes

2021-09-14 05:56 UTC, merged