Naivebird update: OSPP 2021: QQ puppet for Wechaty
wechaty/docusaurus pull request #1051
Opened 2021-07-11 16:30 UTC by anaivebird

- update personal info and project plan blog

2021-07-11 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1051) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1051) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1051) it.</sub>

2021-07-12 13:03 UTC, lijiarui requested changes
Please change as I request.

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  - kuaishou
Please change this to `qq`, since this project is related to qq instead of `kuaishou `

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +- 导师：李佳芮
Please add `李卓桓` as well

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +categories: project
Please add `ospp` category as well

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +## [开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块]具体计划
Please change `## [开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块]具体计划` to `## 项目介绍`

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +- 详细方案
Please change `- 详细方案` to `## 详细方案`

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +- 项目开发时间计划
Please change `- 项目开发时间计划` to `## 项目开发时间计划`

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  - 第一阶段（7月-8月）
Please change `- 第一阶段（7月-8月）` to `### 第一阶段（7月-8月）`

2021-07-12 13:03 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  - 第二阶段（8月-10月）
Please change `- 第一阶段（7月-8月）` to `### 第二阶段（8月-10月）`

2021-07-12 14:35 UTC, lijiarui requested changes
Pls change as I request to make the blog more beautiful, thanks!

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +
Please remove the blank line here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  使用 [wechaty-puppet-mock](https://github.com/wechaty/wechaty-puppet-mock) 项目作为模版，参考社区其他的 Wechaty Puppet Provider 代码模块，对 QQ 进行规划、RPA选型、原型测试，和最终的代码封装。
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +    在初期开发中，能够实现文本消息的接收和发送，即可完成原型验证 POC 。
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +
Please remove the blank line here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  通过对Wechaty Puppet Provider和wechaty-puppet-mock项目等进行了解和学习，并对已有项目进行梳理，多和导师进行沟通，实现通过 Wechaty 加载 wechaty-puppet-qq模块，并包装[oicq](https://github.com/takayama-lily/oicq)项目，实现文本消息的收发功能，提供一个 examples/ding-do
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  先和导师沟通，并观看Wechaty Puppet Provider 的 workshop 视频，熟悉Wechaty Puppet Provider的业务流程，并对自己目前还没有掌握的nodejs、npm、typescript等内容进行快速的了解和学习，对时间安排做好具体的规划
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +
Please remove the blank line here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +
Please remove the blank line here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  开始正式进行代码的prototyping，先完成基础的功能，完成通过 Wechaty 加载 wechaty-puppet-5g-qq 模块，并通过oicq项目实现的qq协议，实现文本消息的收发功能。每周协同导师进行功能的开发和完善
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  在现有基础上，滑动验证码登陆、设备锁、qq登陆风控等问题进行调研和排查
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +
Please remove the blank line here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +
Please remove the blank line here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  如果还有功能模块未完成则继续优化代码，梳理项目，如果时间充足，可以尝试完成一下配置 GitHub Actions 实现自动化测试的任务。
Please remove blank space here.

2021-07-12 14:35 UTC, lijiarui commented on jekyll/_posts/2021-07-11-summer-wechaty-qq-puppet.md
> +  继续完善功能，完成“接收到文字消息ding时，自动回复消息dong"的功能，不断总结和完善功能列表。
Please remove blank space here.

2021-07-12 14:52 UTC, merged

2021-07-12 14:52 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited chatrbot to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

2021-07-12 14:52 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited chatrbot to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

2022-04-11 00:15 UTC, huan commented
@anaivebird please complete the above steps required by the community, and join out contributor WeChat room for discussing your new wechaty-huggingface-pipeline idea with other contributors!

2022-04-11 00:19 UTC, anaivebird commented
Thanks, Great!