Update the Python-Wechaty
wechaty/docusaurus pull request #1057
Opened 2021-07-12 14:24 UTC by shraddhavp

This PR links to #890 and this Pr contains the updated document of the Python-Wechaty.

2021-07-12 14:37 UTC, Rohitesh-Kumar-Jain approved these changes
Pass the CI and we are good to go ig

2021-07-15 16:13 UTC, proudofsimin requested changes

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +* This has a  powerful sample code library for robots.
When we use bulleted list, the sentence structures should be paralleled, so maybe consider changing to "Provide powerful sample code library for robots."

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +* Creation of room, member invitation.
When we use bulleted list, the sentence structures should be paralleled, so maybe " Create rooms and invite members."

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +* Can also use the Wechaty-plugin system.
Support Wechaty-plugin system.

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +* It is very easy to implement.
Easy to implement

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +As the basic ecosystem of wechaty is in TypeScript we only need to translate it to Python .There is a hundred (100) lines of code in  class named `Image` in charge of downloading the WeChat image to
Be careful of the spaces:
As the basic ecosystem of Wechaty is in TypeScript, we only need to translate it to Python. There is a hundred (100) lines of code in class named `Image` in charge of downloading the WeChat image to different sizes.

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +For more information on the Python-Wechaty releases and its history the below link can be visited.
For more information on the Python-Wechaty releases and history, visit the link below:

2021-07-15 16:13 UTC, proudofsimin commented on docusaurus/docs/polyglot/python/overview.md
> +You can find more information on Python-Wechaty [here](https://github.com/wechaty/python-wechaty-getting-started).The [General Architecture Diagram](https://wechaty.js.org/docs/polyglot/diy/) illustr
You can find more information on [python-wechaty-getting-started](https://github.com/wechaty/python-wechaty-getting-started). The [General Architecture Diagram](https://wechaty.js.org/docs/polyglot/diy/) illustrates on how the Python-Wechaty can be implemented on the ~already~ existing TypeScript Wechaty ecosystem.

2021-07-17 17:09 UTC, proudofsimin approved these changes
Thanks :)

2021-09-07 19:14 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 02:57 UTC, wj-Mcat approved these changes
LGTM

2021-09-08 03:54 UTC, merged