Add Starter Bot under Examples: Basic
wechaty/docusaurus pull request #1076
Opened 2021-07-14 02:39 UTC by sbis04

Have added the **Starter Bot** page under `Tutorials > Examples > Basic` section. 

Also, added the link to the Starter Bot in the **Event Logger plugin** (fixes #1047), **QR Code Terminal plugin** (refer #1032) **Heartbeat plugin** (fixes #1046) page.

Updated sidebar:

<img width="278" alt="sidebar-examples-basic" src="https://user-images.githubusercontent.com/43280874/125552109-abcf2441-9369-4b33-8c71-16c873a4460d.png">

The Starter Bot page looks like this:

![Starter Bot page](https://user-images.githubusercontent.com/43280874/125551742-0828450c-633d-4185-99e2-31e1cb11960d.png)

Tag #891

2021-07-15 16:37 UTC, proudofsimin approved these changes
Love this so much! This idea is fantastic that I have to repeat it again :)

2021-07-15 17:23 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +1. If you want to use **WhatsApp**, you can install `wechaty-puppet-whatsapp`:
It's a necessary step, change `you can install` to `install`

2021-07-15 17:23 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +2. If you want to use **WeChat**, you can install `wechaty-puppet-wechat`:
same as above

2021-07-15 17:23 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +3. If you want to use **WeCom**, you can install `wechaty-puppet-wxwork`:
here as well

2021-07-15 17:50 UTC, sbis04 commented
@Rohitesh-Kumar-Jain I have done the changes.

2021-07-17 06:46 UTC, shwetalsoni approved these changes

2021-07-20 13:39 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing the changes

2021-07-25 18:01 UTC, lijiarui requested changes

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +npm install wechaty ts-node
I think maybe we change to the following to make it easy to understand.

```
npm install wechaty
npm install ts-node
```

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +  npm install wechaty-puppet-wxwork
wxwork is using wechaty-puppet-service, so you should change this to the following:

If you want to use **[WeCom](https://work.weixin.qq.com/)**, you can install `wechaty-puppet-service`, and get a token like `puppet_wxwork_XXXXX`, 

see more [puppet-service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

```
npm install wechaty-puppet-service
```

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +2. If you want to use **WeChat**, install `wechaty-puppet-wechat`:
There is a lot of puppets can use for WeChat, here is some information for you, you can change this in your way into the doc:

If you want to use **[WeChat](https://www.wechat.com/)**, you can try the following puppet:
- Web Protocol： `wechaty-puppet-wechat`
- iPad Protocol:
  -  padlocal: `wechaty-puppet-padlocal`: `npm install wechaty-puppet-padlocal` and get a token like `puppet_padlocal_XXX`, see more [puppet service padlocal](http://wechaty.js.org/docs/puppet-services/padlocal)
  - paimon: `wechaty-puppet-service`: `npm install wechaty-puppet-service` and get a token like `puppet_paimon_XXX`, see more [puppet service paimon](http://wechaty.js.org/docs/puppet-services/paimon)

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +  npm install wechaty-puppet-wxwork
Also, I found there is error here: http://wechaty.js.org/docs/getting-started/running-locally#2-install-dependencies

No need to install wechaty-puppet-wxwork, it should install wechaty-puppet-service.

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +```
Please add the following after bot.start(), or you cannot get anything at the terminal:

```ts
bot
.on('scan', (qrcode, status) => console.log(`Scan QR Code to login: ${status}\nhttps://wechaty.js.org/qrcode/${encodeURIComponent(qrcode)}`))
.on('login',            user => console.log(`User ${user} logged in`))
.on('message',       message => console.log(`Message: ${message}`))
.start()
```

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +
1. It seems it shouldn't in src file?
2. How about we use it in command line instead of put it in package json file?

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Should change to

```
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN="puppet_wxwork_XXXXX"
```

Get token from [puppet service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Should change to

```
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN="puppet_wxwork_XXXXX"
```

Get token from [puppet service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-07-25 18:01 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Should change to

```
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN="puppet_wxwork_XXXXX"
```

Get token from [puppet service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-07-29 12:29 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +npm install wechaty ts-node
Have updated this.

2021-07-29 12:29 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +  npm install wechaty-puppet-wxwork
Have updated this, and opened issue #1147

2021-07-29 12:30 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +2. If you want to use **WeChat**, install `wechaty-puppet-wechat`:
Have made the changes

2021-07-29 12:30 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +```
Added this.

2021-07-29 12:30 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +
Have removed this part, and directly added the command to run the bot.

2021-07-29 12:30 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Updated this.

2021-07-29 12:30 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Updated this.

2021-07-29 12:30 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Updated this.

2021-07-29 12:31 UTC, sbis04 commented
@lijiarui I have made the suggested changes.

2021-07-29 13:22 UTC, lijiarui requested changes
Just one more tips and I will merge this PR.

Thanks!

2021-07-29 13:22 UTC, lijiarui commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +1. If you want to use **WhatsApp**, install `wechaty-puppet-whatsapp`:
How about we add WhatsApp link as well?

2021-07-29 13:40 UTC, sbis04 commented on docusaurus/docs/examples/basic/starter-bot.mdx
> +1. If you want to use **WhatsApp**, install `wechaty-puppet-whatsapp`:
Have added the link.

2021-07-29 18:24 UTC, sbis04 commented
@lijiarui I have added the link.

2021-07-31 15:52 UTC, lijiarui approved these changes

2021-07-31 15:52 UTC, merged