基于开放 API 封装 Wechaty 接口下的飞书聊天机器人:期初具体计划
wechaty/docusaurus pull request #1085
Opened 2021-07-14 08:53 UTC by remember00000

我已按照格式完成，麻烦您审核！

2021-07-14 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1085) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1085) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1085) it.</sub>

2021-07-14 15:47 UTC, lijiarui approved these changes
Thanks for the post!

Please:
1. Make GitHub action green. You can run `npm run test` locally to make it pass the test.
2. You can ask your mentor help you to review the blog first. When your mentor approve the blog, I will review your blog.

2021-07-15 13:05 UTC, Roxanne718 commented on jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md
> +    - 使用wecharty
'Wechaty' here, not 'wecharty'

2021-07-15 13:14 UTC, remember00000 commented on jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md
> +    - 使用wecharty
done~

2021-07-15 13:21 UTC, Roxanne718 commented
LGTM

2021-07-15 17:55 UTC, lijiarui commented
Hi @remember00000 Please make Github action green, then I will review this PR.

You can run `npm run test` locally to make it pass the test. 

@Roxanne718 Could you help @remember00000 to make GitHub action green? thanks!

2021-07-16 01:19 UTC, remember00000 commented
> Hi @remember00000 Please make Github action green, then I will review this PR.
> 
> You can run `npm run test` locally to make it pass the test.
> 
> @Roxanne718 Could you help @remember00000 to make GitHub action green? t

2021-07-16 01:23 UTC, remember00000 commented
> Hi @remember00000 Please make Github action green, then I will review this PR.
> 
> You can run `npm run test` locally to make it pass the test.
> 
> @Roxanne718 Could you help @remember00000 to make GitHub action green? thanks!

I try this,but I met something and I can solve that by google;So I ask in Issues,and I hope to run npm run test locally successfully.thanks

2021-07-16 19:19 UTC, lijiarui commented
Hi @remember00000 As [Github Action shown](https://github.com/wechaty/wechaty.js.org/pull/1085/checks?check_run_id=3089103272) Your error is related to the image issues, you can read the error info and change as the error required.

```
ok 18 total 197 files checked.
# developer project avatar should be put under assets/contributors/ folder
not ok 19 jekyll/assets/contributors/remember00000/avatar.jpg should exist
  ---
    operator: fail
    at: Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/contributor-profile.spec.ts:91:11)
    stack: |-
      Error: jekyll/assets/contributors/remember00000/avatar.jpg should exist
          at Test.assert [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/contributor-profile.spec.ts:91:11)
  ...
ok 20 total 197 files checked
# developer profile name must be GitHub username
.......
ok 21 7 contributors profile names checked
# misplaced files
ok 22 should no miss placed files. 
# folder _contributors/, _posts/, and assets/ has been moved to `jekyll/` (e.g. _posts/ => jekyll/_posts/)
ok 23 7 deprecated folders checked.
# filename only allow [a-z0-9-_.]
ok 24 total 2252 files checked.
# front matter key `image` must has a value to define the teaser image
ok 25 total 328 files checked
# {% include iframe.html src=... %} should exist in assets/ folder
ok 26 total 328 files checked.
# all remote images linked from the post should be exist.
.
ok 27 total 1 remote image urls checked
# all local images linked from the post should be exist.
not ok 28 "/assets/2021/07-wechaty-puppet-lark-plan-blog/wechaty-lark.png" should exist
  ---
    operator: fail
    at: Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/image-existance.spec.ts:104:11)
    stack: |-
      Error: "/assets/2021/07-wechaty-puppet-lark-plan-blog/wechaty-lark.png" should exist
          at Test.assert [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/image-existance.spec.ts:104:11)
  ...
not ok 29 "/assets/contributors/remember00000/avatar.jpg" should exist
  ---
    operator: fail
    at: Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/image-existance.spec.ts:104:11)
    stack: |-
      Error: "/assets/contributors/remember00000/avatar.jpg" should exist
          at Test.assert [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/image-existance.spec.ts:104:11)
  ...
```

As you mention in #1093 It seems this error is totally different from the issue you report, if you can give reproduce code, I would like to help.

2021-07-18 12:38 UTC, lijiarui requested changes
Thanks for making Github Action green!

Please change as I request, and it would be better if you can refer   https://github.com/wechaty/wechaty.js.org/pull/1078/files to make the blog more beautiful/

2021-07-18 12:38 UTC, lijiarui commented on jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md
> + categories: project
Please change to the following as [OSPP Guide](https://wechaty.js.org/2021/06/24/summer-wechaty-guide/) required.
```
categories:
  - project
  - ospp
```

2021-07-18 12:38 UTC, lijiarui commented on jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md
> +  - ecosystem
Please add the following tag as [OSPP Guide](https://wechaty.js.org/2021/06/24/summer-wechaty-guide/) required:

`ospp`,`ospp-2021`,`plan`

2021-07-18 12:38 UTC, lijiarui commented on jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md
> +
Please add the project link here: https://github.com/wechaty/summer-of-wechaty/issues/38

2021-07-18 15:50 UTC, lijiarui requested changes
Please change as I request. 

Also, please change the file name from `jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md` to `2021-07-14-ospp-plan-XX`as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ required.

2021-07-18 15:50 UTC, lijiarui commented on jekyll/_posts/2021-07-14-wechaty-puppet-lark-plan-blog.md
> + title: "基于开放 API 封装 Wechaty 接口下的飞书聊天机器人:期初具体计划"
Please change title to `OSPP 2021-期初报告-你的标题` as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ required.

2021-07-19 14:10 UTC, lijiarui commented
@remember00000 Please make Github action green.

2021-07-27 07:44 UTC, merged

2021-07-27 07:45 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited  remember00000 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _ruirui_0914_ and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!