Scala-Wechaty
wechaty/docusaurus pull request #1096
Opened 2021-07-15 11:57 UTC by shraddhavp

this PR links to #890 and this PR contains the updated section of Scala-Wechaty.

2021-07-15 12:20 UTC, iamrajiv requested changes

2021-07-15 12:20 UTC, iamrajiv commented on docusaurus/docs/polyglot/scala/overview.md
> +Scala Wechaty is a Scala programming client derived from the Wechaty ecosystem.Scala's static types help avoid bugs in complex applications,hence Scala wechaty is very easy to use,implement and is al
```suggestion
Scala Wechaty is a Scala programming client derived from the Wechaty ecosystem. Scala's static types help avoid bugs in complex applications, hence Scala wechaty is very easy to use, implement and is also very efficient. You can find more information on Scala-Wechaty [here](https://github.com/wechaty/scala-wechaty-getting-started). The [General Architecture Diagram](https://wechaty.js.org/docs/polyglot/diy/) illustrates how the Scala-Wechaty can be implemented on the already existing TypeScript Wechaty ecosystem.
```

2021-07-15 12:20 UTC, iamrajiv commented on docusaurus/docs/polyglot/scala/overview.md
> +There are a hundred (100) lines class named `Image` in charge of downloading the WeChat image to different sizes.Below are the links to Image class for both TypeScript and Scala for better understand
```suggestion
There is a hundred (100) lines class named `Image` in charge of downloading the WeChat image to different sizes. Below are the links to the Image class for both TypeScript and Scala for a better understanding of the code and the translation.
```

2021-07-15 16:31 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/polyglot/scala/overview.md
> +* Stable interaction with back-end GRPC, continuous and stable operation for many days.
after reading this it seems like, Scala-Wechaty becomes unstable after some period of time 🤔 

Also, a nitpicking suggestion is to change GRPC to gRPC 😅

2021-07-15 16:35 UTC, Rohitesh-Kumar-Jain commented
@shraddhavp can we expect a lesser number of typos and punctuation errors in the upcoming PRs : )
Thanks for @iamrajiv for spotting them

2021-07-15 17:05 UTC, shraddhavp commented
> @shraddhavp can we expect a lesser number of typos and punctuation errors in the upcoming PRs : )
> Thanks for @iamrajiv for spotting them

yes sure I am trying it this type typos were less but punctuation was a bit problem but thanks to you @proudofsimin and @iamrajiv  for correcting me next PR's you will not see typos or punctuation  errors much

2021-07-15 17:14 UTC, Rohitesh-Kumar-Jain commented
> next PR's you will not see typos or punctuation errors much

It's okay if there are typos or punctuation errors, we are here to correct them.

But proofread yourself once before pushing.

2021-07-17 15:34 UTC, proudofsimin approved these changes
Thank you.

2021-07-20 14:07 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-24 10:05 UTC, Soumi7 approved these changes

2021-09-07 19:15 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 06:28 UTC, Rohitesh-Kumar-Jain commented
@iamrajiv

2021-09-09 22:26 UTC, iamrajiv approved these changes

2021-09-11 05:43 UTC, merged