2021-07-15-summer-2021-5g-chatbot-puppet
wechaty/docusaurus pull request #1097
Opened 2021-07-15 15:08 UTC by sqcn

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-07-15 15:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1097) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1097) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1097) it.</sub>

2021-07-15 17:59 UTC, lijiarui commented
Thanks for the blog！

Please make GitHub action green. You can run the `npm run test` locally to make this commit pass all of the tests first.

2021-07-16 18:40 UTC, lijiarui commented
@sqcn Please make GitHub action green. You can run the npm run test locally to make this commit pass all of the tests first.

2021-07-17 18:32 UTC, sqcn commented
@lijiarui Hi, we already fixed the last picture bug that CI Action mentioned. We just submitted but still yellow.

2021-07-17 18:32 UTC, sqcn commented
@lijiarui  Hi, we have already fixed the last picture bug that CI Action mentioned. We just submitted but still yellow.

2021-07-18 12:22 UTC, lijiarui requested changes
Please change as I request.

And it could be better if you can refer https://github.com/wechaty/wechaty.js.org/pull/1078/files to make the blog look better.

2021-07-18 12:22 UTC, lijiarui commented on jekyll/_posts/2021-07-15-ospp-plan-5g-chatbot-puppet.md
> +- 导师：李佳芮,康嘉
Please add `李卓桓` here as well

2021-07-18 12:22 UTC, lijiarui commented on jekyll/_posts/2021-07-15-ospp-plan-5g-chatbot-puppet.md
> +    - 无
What do you mean `无` here, I suggest deleting unrelated intro in the blog.

2021-07-18 12:22 UTC, lijiarui commented on jekyll/_posts/2021-07-15-ospp-plan-5g-chatbot-puppet.md
> +
Please add `项目介绍：https://github.com/wechaty/summer-of-wechaty/issues/74` here

2021-07-19 14:11 UTC, merged

2021-07-19 14:12 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited sqcn to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _ruirui_0914_ and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!