Deploy with WeChat
wechaty/docusaurus pull request #1098
Opened 2021-07-16 08:36 UTC by abhishek-iiit

# Deploy with WeChat
![Screenshot from 2021-07-16 13-40-30](https://user-images.githubusercontent.com/69477761/125918550-27d76a14-e201-41cd-a886-558209163672.png)
![Screenshot from 2021-07-16 13-40-39](https://user-images.githubusercontent.com/69477761/125918560-44e87798-5b53-458e-9b7d-4180a9c1db06.png)
![Screenshot from 2021-07-16 13-40-48](https://user-images.githubusercontent.com/69477761/125918568-cac31e56-e46f-4ce3-a4fc-a05b5d1c327b.png)

2021-07-16 08:39 UTC, abhishek-iiit commented
Linked to issue #896

2021-07-17 17:02 UTC, proudofsimin requested changes
Just wondering if there are going to be guides for WhatsApp or others.

2021-07-17 17:02 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-wechat.md
> +With all-in-one system and massive audience base, deploying WeChaty in WeChat can prove to be a good choice.In this how to guide, you will learn how to deploy the bot in WeChat locally.
The introduction is good. You added the benefit of following this guide and what the users would learn, but it's better if you could explain more, which I meant to mention that we will use starter template as an example in here.

2021-07-17 17:02 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-wechat.md
> +
Run `wechaty-puppet-wechat`:

2021-07-17 17:02 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-wechat.md
> +<ol><li> Initialise the project by creating a new folder `my-bot`.</li>
Initialize <- use the American spelling instead.

2021-07-17 17:02 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-wechat.md
> +Let's take up an example on how to integrate bot from [starter templete](https://github.com/wechaty/wechaty-getting-started) to WeChat.The steps are similar for all other bots as well.
Add a step between two sentences.

2021-07-17 17:02 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-wechat.md
> +## Example
I'm not sure for this title. How do you feel if we use "integrate a bot from starter template to WeChat" ? I'll let you decide for this one. I can't find a great example.

2021-07-22 11:47 UTC, abhishek-iiit commented
Changes done as suggested :)

2021-07-22 12:35 UTC, abhishek-iiit commented
Changes done as suggested :)

2021-07-23 16:32 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-wechat.md
> +
Why don't you add this sentence in?

2021-07-23 16:50 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-25 02:05 UTC, abhishek-iiit commented on docusaurus/docs/howto/deploy-wechat.md
> +
Added

2021-07-26 16:45 UTC, proudofsimin approved these changes

2021-07-27 07:12 UTC, vasvi-sood approved these changes
This PR is great. LGTM

2021-07-29 15:34 UTC, lijiarui requested changes, later dismissed
![image](https://user-images.githubusercontent.com/6419514/127521411-dc9b0ab8-8d40-48cd-9caf-7338865dbfdd.png)

It seems you didn't put this in the nav bar. Please add this to nav bar and then I will review.

2021-09-07 19:15 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-13 21:41 UTC, abhishek-iiit commented
merging PR with no conflicts and 4 approvals :)

2021-09-13 21:41 UTC, merged