Improve the Contact Bot page
wechaty/docusaurus pull request #1099
Opened 2021-07-16 12:23 UTC by sbis04

Have made some improvements to the **Contact Bot** page under `Tutorials > Examples > Basic`.

The page looks like this:

![Contact Bot page](https://user-images.githubusercontent.com/43280874/125946542-1a692b60-dea6-4788-8516-0851200c2997.png)

Tag #891

2021-07-16 17:42 UTC, shwetalsoni approved these changes

2021-07-20 16:29 UTC, proudofsimin approved these changes

2021-07-23 16:43 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-24 04:39 UTC, sbis04 commented
@Rohitesh-Kumar-Jain I guess this qualifies to be added to #1056

2021-07-24 04:52 UTC, Rohitesh-Kumar-Jain commented
> @Rohitesh-Kumar-Jain I guess this qualifies to be added to #1056

Yes I will add it there : )

2021-07-25 18:12 UTC, lijiarui requested changes

2021-07-25 18:12 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +cd contact-bot
It looks a little bit strange that you already create ` wechaty-getting-started` before, and now create another folder `contact-bot` here, but they are the same code.

```
git clone https://github.com/wechaty/wechaty-getting-started.git
cd wechaty-getting-started
```

2021-07-25 18:12 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +  npm install wechaty-puppet-wechat
There is a lot of puppets can use for WeChat, here is some information for you, you can change this in your way into the doc:

If you want to use **[WeChat](https://www.wechat.com/)**, you can try the following puppet:
- Web Protocol： `wechaty-puppet-wechat`
- iPad Protocol:
  -  padlocal: `wechaty-puppet-padlocal`: `npm install wechaty-puppet-padlocal` and get a token like `puppet_padlocal_XXX`, see more [puppet service padlocal](http://wechaty.js.org/docs/puppet-services/padlocal)
  - paimon: `wechaty-puppet-service`: `npm install wechaty-puppet-service` and get a token like `puppet_paimon_XXX`, see more [puppet service paimon](http://wechaty.js.org/docs/puppet-services/paimon)

2021-07-25 18:12 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +  npm install wechaty-puppet-wxwork
wxwork is using wechaty-puppet-service, so you should change this to the following:

If you want to use **[WeCom](https://work.weixin.qq.com/)**, you can install `wechaty-puppet-service`, and get a token like `puppet_wxwork_XXXXX`, 

see more [puppet-service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

```
npm install wechaty-puppet-service
```

2021-07-25 18:12 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Should change to

```
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN="puppet_wxwork_XXXXX"
```

Get token from [puppet service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-07-25 18:12 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Should change to

```
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN="puppet_wxwork_XXXXX"
```

Get token from [puppet service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-07-25 18:12 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Should change to

```
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN="puppet_wxwork_XXXXX"
```

Get token from [puppet service wxwork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-07-29 13:14 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +cd contact-bot
Actually, those are two separate sections.

In **Getting started** section, it guides the user to clone an pre-made bot and run it locally on their system.

In **Building the bot** section, it guides the user step-by-step how to build the bot from scratch.

If you see the bot building tutorials, we have followed a similar pattern in most of them.

2021-07-29 13:15 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +  npm install wechaty-puppet-wechat
Have made these changes.

2021-07-29 13:15 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +  npm install wechaty-puppet-wxwork
Have made these changes.

2021-07-29 13:15 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Have made the changes.

2021-07-29 13:15 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Have made the changes.

2021-07-29 13:15 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Have made the changes.

2021-07-29 13:16 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +# export WECHATY_PUPPET=wechaty-puppet-wxwork
Have made the changes.

2021-07-29 13:17 UTC, sbis04 commented
@lijiarui I have made the suggested changes.

2021-07-29 13:28 UTC, lijiarui approved these changes
Just one more change, then I will merge this PR!

2021-07-29 13:28 UTC, lijiarui commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +
I thinks we should install wechaty first.

```
npm install wechaty
```

2021-07-29 13:42 UTC, sbis04 commented on docusaurus/docs/examples/basic/contact-bot.mdx
> +
Have made the change.

2021-07-29 18:25 UTC, sbis04 commented
@lijiarui I have made the change.

2021-07-31 15:53 UTC, lijiarui approved these changes

2021-07-31 15:53 UTC, merged