Deploy in Lark
wechaty/docusaurus pull request #1101
Opened 2021-07-16 15:00 UTC by abhishek-iiit

# Deploy in Lark
![Screenshot from 2021-07-16 20-25-04](https://user-images.githubusercontent.com/69477761/125967951-8f15d8f9-b1a1-4817-bc33-9ad9e19dee30.png)
![Screenshot from 2021-07-16 20-25-13](https://user-images.githubusercontent.com/69477761/125967959-058246e3-1308-43fa-bb7a-500d1d0d3921.png)
![Screenshot from 2021-07-16 20-25-26](https://user-images.githubusercontent.com/69477761/125967966-5c8b0a2c-afab-4252-a850-71ef57203186.png)

2021-07-16 15:00 UTC, abhishek-iiit commented
Linked to issue #896

2021-07-20 16:51 UTC, proudofsimin requested changes
Could you modify this PR according to the comments in #1098 ? Thank you.

2021-07-22 12:25 UTC, abhishek-iiit commented
Changes made as suggested :)

2021-07-26 16:47 UTC, proudofsimin approved these changes
Great! Thank you, but don't forget to add this one.
![image](https://user-images.githubusercontent.com/19759195/127027360-4442b622-71f3-48ef-b425-0c271724502a.png)

2021-07-27 07:35 UTC, vasvi-sood approved these changes
This PR looks perfect to me!

2021-08-01 14:45 UTC, Rohitesh-Kumar-Jain approved these changes
proofread

2021-09-07 19:17 UTC, huan requested changes, later dismissed
```diff
- docusaurus/static/img/docs/howto/IM_platform/deploy-lark.webp
+ docusaurus/static/img/docs/howto/deploy-lark/deploy-lark.webp

2021-09-13 08:49 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood and @abhishek-iiit pls make the required changes so that we can proceed towards the merge

2021-09-13 21:07 UTC, abhishek-iiit commented
> ```diff
> - docusaurus/static/img/docs/howto/IM_platform/deploy-lark.webp
> + docusaurus/static/img/docs/howto/deploy-lark/deploy-lark.webp
> ```

Thank you for the feedback. Changes made as suggested :)

2021-09-18 18:27 UTC, lijiarui requested changes

2021-09-18 18:27 UTC, lijiarui commented on docusaurus/docs/howto/deploy-lark.mdx
> +1. Your system must have [Node.js](https://nodejs.org/en/download/package-manager/) installed (version >= 12).
(version >= 12). --> (version >= 16).

Since wechaty only support  >= 16 NodeJS now.

2021-09-18 18:27 UTC, lijiarui commented on docusaurus/docs/howto/deploy-lark.mdx
> +* [Encapsulation of Feishu chat robot under Wechaty interface based on open API: end of term](https://wechaty.js.org/2020/09/30/wechaty-puppet-lark-final-blog/).
Please add the following related blogs too:

- https://wechaty.js.org/2020/08/19/wechaty-puppet-lark-mid-term-blog/
- https://wechaty.js.org/2021/07/14/ospp-plan-wechaty-puppet-lark/

2021-09-18 19:04 UTC, huan requested changes
Please rename `docusaurus/static/img/docs/howto/IM_platform/deploy-lark.webp` to `docusaurus/static/img/docs/howto/deploy-lark/deploy-lark.webp`

2021-09-21 20:06 UTC, abhishek-iiit commented
> Please rename `docusaurus/static/img/docs/howto/IM_platform/deploy-lark.webp` to `docusaurus/static/img/docs/howto/deploy-lark/deploy-lark.webp`

I added the changes as suggested previously. will delete the `IM_platform` folder at the end of the merging of all PR :)

2021-10-13 12:50 UTC, huan approved these changes
LGTM

2021-10-16 16:15 UTC, Rohitesh-Kumar-Jain commented
ping @lijiarui

2021-10-17 08:48 UTC, lijiarui submitted a review, later dismissed
When I preview the doc, I found I cannot find the content in the sidebar, I think we should fix this first.

![image](https://user-images.githubusercontent.com/6419514/137619444-037509ad-0f8c-4843-9f8a-fca1f26bd8e1.png)

2021-10-28 11:39 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit I don't see the requested changes addresses.

2021-10-28 11:47 UTC, abhishek-iiit commented
> @abhishek-iiit I don't see the requested changes addresses.

Sorry, I forgot to mention that I did the changes as addressed here in this #1139 PR

2021-10-28 11:54 UTC, Rohitesh-Kumar-Jain approved these changes
Yes you are right, I wasn't aware that you changed that there 😅

2021-10-28 11:55 UTC, abhishek-iiit commented
> Yes you are right, I wasn't aware that you changed that there 😅

Actually I forgot to mention it here :( Sorry 😅

2021-11-03 11:21 UTC, Rohitesh-Kumar-Jain commented
ping @lijiarui

2021-11-25 13:26 UTC, merged