Fix Running locally CodeSandbox
wechaty/docusaurus pull request #1102
Opened 2021-07-16 17:53 UTC by sbis04

Have fixed the CodeSandbox of the **Running locally** page. You can check it out using [this link](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?file=/ding-dong-bot.ts).

![Screenshot 2021-07-16 at 11 13 36 PM](https://user-images.githubusercontent.com/43280874/125988766-d423955b-fe1c-47e8-8dd9-785dd29479c1.png)

Refer #1032

2021-07-20 13:37 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
I guess, the repository wechaty-ding-dong should be hosted on Wechaty ?

2021-07-20 16:53 UTC, proudofsimin approved these changes

2021-07-24 04:57 UTC, sbis04 commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
@Rohitesh-Kumar-Jain I am not sure about that, previously the pages like **Vorpal bot**, **Contact bot**, **Room bot**, **Busy bot**, **Friend bot** also has the CodeSandbox stored on a personal account. We may consult mentors once I guess.

2021-07-24 05:08 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
Yes we should ask @lijiarui and @huan about this

2021-08-24 05:33 UTC, Rohitesh-Kumar-Jain commented
Adding this in the merge list, because it's a mere formality for Shwetal Soni to review and I will approve it once approved by mentors (see my comment).

2021-08-25 18:29 UTC, lijiarui requested changes

2021-08-25 18:29 UTC, lijiarui commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
We should never have the CodeSandbox stored on a personal account since it would be hard to maintain if hosted in the personal account in the future. If previously the pages are hosted in the personal account, we should change back to wechaty(If I merge some of them, I think maybe I ignored by mistake).

How do you think about this? @huan

2021-08-25 20:11 UTC, sbis04 commented
@lijiarui I had done a PR to the `wechaty-getting-started` repo for fixing this error: https://github.com/wechaty/wechaty-getting-started/pull/192

If you can accept that, I will use the official repo link here.

2021-09-07 19:19 UTC, huan commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
I agree we should always use the example code from our official example directory, which is living at https://github.com/wechaty/wechaty-getting-started/tree/main/examples

2021-09-07 19:20 UTC, huan requested changes
Please use our official example directory, which is living at https://github.com/wechaty/wechaty-getting-started/tree/main/examples

2021-09-07 19:59 UTC, sbis04 commented
@huan but this was a fix for an issue with the official Code Sandbox of the Ding Dong bot which is in the root directory here: https://github.com/wechaty/wechaty-getting-started (because the `sandbox.config.json` file is present in the root dir)

2021-09-09 10:49 UTC, huan commented
> @huan but this was a fix for an issue with the official Code Sandbox of the Ding Dong bot which is in the root directory here: https://github.com/wechaty/wechaty-getting-started (because the sandbox.config.json file is present in the root dir)

What do you mean "the sandbox.config.json file is present in the root dir"?

In our official example directory, the sandbox example is at <https://github.com/wechaty/wechaty-getting-started/tree/main/examples/third-parties/codesandbox>, please change the CodeSandbox link to here.

My understanding is, If there's any improvement/changes that should be made, we should send a PR and fix our official example.

2021-09-12 07:57 UTC, sbis04 commented
Sorry I made a mistake, I have created a new PR. @huan can you please take a look at this: https://github.com/wechaty/wechaty-getting-started/pull/206

2021-09-14 09:44 UTC, huan commented
Related to #1296

2021-09-14 10:48 UTC, huan commented
Fixed by https://github.com/wechaty/wechaty.js.org/issues/1296

2021-09-14 10:48 UTC, closed without merging