[How to guides] Whatsapp section
wechaty/docusaurus pull request #1106
Opened 2021-07-17 09:13 UTC by vasvi-sood

![deploy-whatsapp1](https://user-images.githubusercontent.com/76619050/126032287-c152168d-6fb3-4693-b6a2-369daceed36a.png)
![deploy-whatsapp2](https://user-images.githubusercontent.com/76619050/126032290-f7232b05-8ddb-4d34-a1ed-43bbad6dc434.png)
![deploy-whatsapp3](https://user-images.githubusercontent.com/76619050/126032292-e140b805-05ed-4103-a863-7a3a6279641f.png)

2021-07-22 08:49 UTC, abhishek-iiit approved these changes
Approved PR with suggested changes. If you could have a little more explanation to the header section, it can become prefect PR, rest everything is perfect :)

2021-07-22 09:47 UTC, proudofsimin requested changes
Could you modify according to the advice I gave in #1098 ? Thank you.

2021-07-22 09:47 UTC, proudofsimin commented on docusaurus/docs/howto/deploy-whatsapp.md
> +Whatsapp  is the most popular IM platform, so this how to guide focusses to deploy the bot in Whatsapp locally.
typo: focuses on deploying

2021-07-27 07:13 UTC, vasvi-sood commented
> Could you modify according to the advice I gave in #1098 ? Thank you.

Sure

2021-07-27 07:34 UTC, vasvi-sood commented
All changes have been made. Kindly review it @proudofsimin  and @abhishek-iiit

2021-07-28 14:47 UTC, proudofsimin approved these changes
Thanks

2021-08-01 14:47 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-07 19:21 UTC, huan requested changes
```diff
- docusaurus/static/img/docs/howto/IM_platform/deploy-whatsapp.webp 
+ docusaurus/static/img/docs/howto/deploy-whatsapp/deploy-whatsapp.webp 
```

2021-09-10 10:54 UTC, vasvi-sood commented
> ```diff
> - docusaurus/static/img/docs/howto/IM_platform/deploy-whatsapp.webp 
> + docusaurus/static/img/docs/howto/deploy-whatsapp/deploy-whatsapp.webp 
> ```

All necessary changes have been made. Kindly review it @huan

2021-09-10 15:43 UTC, huan approved these changes
Thank you very much for adding this whatsapp how-to guide!

Please follow my reviews and resolve the conflicts, then I believe it's ready to go.

2021-09-10 15:43 UTC, huan commented on docusaurus/docs/howto/deploy-whatsapp.md
> +```bash
Here should be `ts` instead of `bash`

2021-09-10 15:43 UTC, huan commented on docusaurus/docs/howto/deploy-whatsapp.md
> +const {
Please change them from CommonJS `require` to ESM `import`.

See: #1275

2021-09-13 08:49 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood and @abhishek-iiit pls solve the merging conflict, and help yourself in merging the PR

2021-09-13 18:05 UTC, merged