Update Puppet Providers - Gitter
wechaty/docusaurus pull request #1110
Opened 2021-07-18 06:51 UTC by Soumi7

Updates Puppet Providers -  Gitter section in references.
 
References issue #890

ScreenShots :

![Screenshot from 2021-07-18 12-16-55](https://user-images.githubusercontent.com/51290447/126058381-dba16b07-da96-472f-a7f0-33601e5ec14f.png)

![Screenshot from 2021-07-18 12-17-03](https://user-images.githubusercontent.com/51290447/126058384-41f88849-076a-47b5-8c4c-a78fc853c4c6.png)

![Screenshot from 2021-07-18 12-17-16](https://user-images.githubusercontent.com/51290447/126058387-8f66df63-91b4-45a1-bfb8-4317dde77adf.png)

![Screenshot from 2021-07-18 12-17-19](https://user-images.githubusercontent.com/51290447/126058391-2aa8e44e-00c5-40dc-b614-eca19e64634a.png)

![Screenshot from 2021-07-18 12-17-22](https://user-images.githubusercontent.com/51290447/126058392-4179fb1b-a2e6-4b5d-9fb3-e1ce53016a97.png)

2021-07-18 08:45 UTC, shraddhavp commented
@Soumi7  make the CLI green

2021-07-20 13:51 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-23 14:46 UTC, proudofsimin approved these changes
Thank you.

2021-07-23 16:34 UTC, Rohitesh-Kumar-Jain commented
@Soumi7

2021-07-23 16:35 UTC, Rohitesh-Kumar-Jain commented
@shraddhavp

2021-07-23 16:36 UTC, Soumi7 commented
Have updated. Once the CLI turns green, its ready to merge

2021-07-23 16:36 UTC, Soumi7 commented
@Rohitesh-Kumar-Jain

2021-07-23 16:44 UTC, iamrajiv requested changes

2021-07-23 16:44 UTC, iamrajiv commented on docusaurus/docs/puppet-providers/gitter.md
> +```sh
replace `sh` to `ts`

2021-07-24 09:56 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/gitter.md
> +```sh
Done.

2021-09-07 19:24 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 05:46 UTC, Soumi7 commented
@iamrajiv as you requested changes, we will need your approval to merge this PR. Can you please approve this?

2021-09-11 11:36 UTC, shraddhavp approved these changes
LGTM

2021-09-11 11:39 UTC, iamrajiv approved these changes

2021-09-11 11:47 UTC, merged