Wechaty 实现 Milvus 社区群消息同步
wechaty/docusaurus pull request #1115
Opened 2021-07-20 04:29 UTC by shiyu22

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-07-24 03:43 UTC, huan requested changes
Thanks for sharing the Wechaty practice experiences from the Milvus community!

Please make the CI green by following the error messages from https://github.com/wechaty/wechaty.js.org/pull/1115/checks?check_run_id=3117089428 before we can continue reviewing this great blog post.

2021-08-03 00:14 UTC, huan requested changes
Please convet all PNG files to WEBP format in favor to #1035

2021-08-24 04:08 UTC, lijiarui commented
Hi @shiyu22  Please make GitHub action green then we could continue to review this PR.

2021-08-24 06:59 UTC, lijiarui commented
Hi, @shiyu22  The most efficient way to make your post PR turns green is to run the npm test locally before push because it will greatly reduce the time that you spend to pass this CI test.

2021-09-01 14:36 UTC, lijiarui commented
ping @shiyu22

2021-09-07 17:56 UTC, lijiarui requested changes

2021-09-07 17:56 UTC, lijiarui commented on jekyll/_posts/2021-07-20-milvus-sync-bot.md
> +
Please remove the useless blank here.

2021-09-07 17:56 UTC, lijiarui commented on jekyll/_posts/2021-07-20-milvus-sync-bot.md
> +
Please remove the useless blank here.

2021-09-07 17:56 UTC, lijiarui commented on jekyll/_posts/2021-07-20-milvus-sync-bot.md
> +
Please remove the useless blank here. See:   https://docs.google.com/presentation/d/1rWd7aLozgPFyPiSbyxqw1GeGV2-NCGRKvDOUcq9VYcw/edit#slide=id.gec336ad374_1_357

2021-09-07 17:56 UTC, lijiarui commented on jekyll/_posts/2021-07-20-milvus-sync-bot.md
> +<img src="/assets/2021/07-milvus-sync-bot/syncbot1.webp" width = "300" height = "500" alt="图片名称" align=center />
Please change to the following:

```
![效果展示](/assets/2021/07-milvus-sync-bot/syncbot1.webp)
```

2021-09-07 19:25 UTC, huan commented
Thanks for the update, and I'm looking forward to seeing this blog post online soon!

2021-09-09 10:44 UTC, huan requested changes
You are very close to passing the CI!

Please see https://github.com/wechaty/wechaty.js.org/runs/3540785907#step:7:24 and I believe we can see a green CI after fixed all of them.

2021-09-18 10:54 UTC, lijiarui commented
ping @shiyu22

2021-09-22 08:23 UTC, huan commented
You are very close to passing the CI!

Please see 
 https://github.com/wechaty/wechaty.js.org/pull/1115/checks?check_run_id=3670813600#step:7:24

and I believe we can see a green CI after fixed all of them.

2021-09-22 09:51 UTC, huan commented
@shiyu22 It seems that you have only fixed a tiny subset of the linting problems.

I'd like to suggest that you should run the following commands locally (Node.js required):

```sh
npm install
npm test
```

And you will get the linting report before pushing them.

2021-09-28 15:55 UTC, lijiarui commented
ping @shiyu22

2021-10-06 10:58 UTC, lijiarui commented
Thanks for your update, @shiyu22

In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-11-07 14:31 UTC, huan approved these changes
LGTM

Congratulations on having fixed all the **linting requirements**!

2021-11-08 10:14 UTC, merged

2021-11-08 10:15 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited shiyu22 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!