Add Redux: Ducks proposal style docs
wechaty/docusaurus pull request #1126
Opened 2021-07-20 09:17 UTC by sbis04

I have added the Wechaty Redux **Ducks Proposal Style** tutorial under `Tutorials > Using Redux with Wechaty > Ducks Proposal Style`.

The page looks like this:

![Ducks Proposal Style](https://user-images.githubusercontent.com/43280874/126295383-79c6ed23-105b-4410-b904-963a91ecac97.png)

Tag #891

2021-07-23 14:59 UTC, proudofsimin approved these changes
You're really a great writer :)

2021-07-24 04:58 UTC, Rohitesh-Kumar-Jain approved these changes
wow, the quality of your documentation has improved exponentially, your last few PRs have been exceptional. I wasn't able to find a single typo or improvement in the way you should be writing documentation. Great work, I will suggest you to look back at your initial PRs and then look this PR 🔥

2021-07-24 05:01 UTC, Rohitesh-Kumar-Jain commented
Your initial documentation I feel used to be a bit verbose, and used to contain too many screenshots.

2021-07-24 05:06 UTC, sbis04 commented
Okay, thanks @Rohitesh-Kumar-Jain & @proudofsimin 😊

2021-07-25 07:51 UTC, shwetalsoni commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +1. If you want to use **WhatsApp**, you can install `wechaty-puppet-whatsapp`:
` If you want to use **WhatsApp**, you can install `wechaty-puppet-whatsapp`:`
I think this can be formatted in a better way like this:
`. If you want to use **WhatsApp**, install `wechaty-puppet-whatsapp`:`

2021-07-25 08:51 UTC, sbis04 commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +1. If you want to use **WhatsApp**, you can install `wechaty-puppet-whatsapp`:
I forgot to update this, thanks for noticing. Have updated now.

2021-07-29 11:08 UTC, shwetalsoni approved these changes

2021-07-29 13:21 UTC, sbis04 commented
@Rohitesh-Kumar-Jain I think this PR can be added to #1056

2021-07-29 15:27 UTC, lijiarui requested changes

2021-07-29 15:27 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +  ```bash
I think you should change as @sbis04 request: https://github.com/wechaty/wechaty.js.org/pull/1099#discussion_r676183033

2021-07-29 15:27 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +  npm install wechaty-puppet-wxwork
This should refer: https://github.com/wechaty/wechaty.js.org/pull/1099#discussion_r676183045

2021-07-29 15:27 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +Start by creating a new folder called `src`, and add a file `redux-bot.ts`. We will be writing the code here.
It seems you already create a folder `redux-bot`, so there is no need to create a new one `src` here.

2021-07-29 15:27 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +npx ts-node src/redux-bot.ts
change to `ts-node redux-bot.ts`

2021-07-29 19:18 UTC, sbis04 commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +  ```bash
Have made the changes.

2021-07-29 19:18 UTC, sbis04 commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +  npm install wechaty-puppet-wxwork
Have made the changes.

2021-07-29 19:18 UTC, sbis04 commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +Start by creating a new folder called `src`, and add a file `redux-bot.ts`. We will be writing the code here.
Corrected it.

2021-07-29 19:18 UTC, sbis04 commented on docusaurus/docs/using-redux-with-wechaty/ducks-proposal.mdx
> +npx ts-node src/redux-bot.ts
Have made the change.

2021-07-29 19:19 UTC, sbis04 commented
@lijiarui I have made the suggested changes

2021-07-31 16:57 UTC, lijiarui approved these changes
LGTM

2021-08-02 16:17 UTC, merged