2021gsod
wechaty/docusaurus pull request #1129
Opened 2021-07-20 10:32 UTC by gangena

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-07-20 13:21 UTC, Rohitesh-Kumar-Jain commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +   7月18日：进行了GSoD第六次会议，同样，每个参与者都进行了一周总结与下一周的计划，志愿者和技术作者进行了讨论，并进行了问答环节，讨论和解决了大家存在的问题。
We also announced mid & final blog posts and new PR merging rules, so you may or may not add that as well : )

2021-07-20 15:41 UTC, lijiarui requested changes
This is a news release.

You can refer to this: https://www.oschina.net/news/147090/apijson-4-7-0-released

2021-07-20 15:41 UTC, lijiarui commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +title: 2021GSoD&Wechaty
Please change a more attractive title for this blog.

2021-07-20 15:41 UTC, lijiarui commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +- GSOD是[Google Season of Docs](https://developers.google.com/season-of-docs)的简称，是由谷歌组织的年度活动，目的是将技术作家和开源组织聚集到一块，在开源这个空间中共同促进和改善开源的发展。
GSOD --> GSod

技术作家 --> 技术文档撰写工程师

2021-07-20 15:41 UTC, lijiarui commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +### 一个好消息
Delete this since this is a press release.

2021-07-22 09:44 UTC, proudofsimin commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +1. [Souvik Biswas](https://docs.google.com/document/d/1MD9CwO6BoB664J67ozfygBJUaawazay7dDpcXB3jJcY/edit)
Just wondering if we should include all the names since some of them did not participate in GSoD at last and Rajiv joined as a separate project but his name is not on it.

2021-07-22 09:44 UTC, proudofsimin commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +   7月4日：进行了GSoD第五周会议，首先，每个参与者都进行了一周总结计划了下一周的工作，志愿者和技术作者们进行了讨论。Simin分享了一些关于Wechaty后续活动的信息，最后我们合影留念。
Could you remove this sentence "Simin分享了一些关于Wechaty后续活动的信息"? I made a some modifications of the checking list instead of sharing some upcoming events. Thank you.

2021-07-22 09:50 UTC, closed without merging

2021-07-22 09:55 UTC, gangena commented
Sorry，this is the new blog<https://github.com/wechaty/wechaty.js.org/pull/1132&gt;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Simin Liao"; 
Date: 2021年7月22日(星期四) 下午5:45
To: "wechaty/wechaty.js.org"; 
Cc: "gangena"; "Author"; 
Subject: Re: [wechaty/wechaty.js.org] 2021gsod (#1129)

&nbsp;



@proudofsimin commented on this pull request.我对这个拉动请求发表了评论。


In 在jekyll/_posts/2021-07-16-gsod-2021-publish-article.mdjekyll/_posts/2021-07-16-gsod-2021-publish-article.md:
&gt; +1. [Abhishek Jaiswal](https://06412355400643469324.googlegroups.com/attach/2696b2e901464/GSoD%202021%20Project%20Proposal(Abhishek%20Jaiswal).pdf?part=0.1&amp;view=1&amp;vt=ANaJVrH3pZ3BlMcLvPB0Hkmb5a0UOwzTxgIx35I_eiVuC-derjfLADp6bOkSNSplVMvJjxPvaSkAPmq-uhcbTI4yJfGY6tKzbegUoN3mwGlnY-7X-cuZUCU) +1. [Ahmed Essam](https://docs.google.com/document/d/1GLxVZSUNDq_jf_OvZc82ZwjVK1ECB1srkBf2IyRYtGc/edit#heading=h.wu5oliio4h1o) +1. [Anirudh TPVS](https://groups.google.com/group/wechaty/attach/1f2bde59e72d6/Wechaty%20GSOD%202021.docx?part=0.1&amp;view=1) +1. [Chris Estepa](https://docs.google.com/document/d/1KQHHFqXrxadsfELzYREjANdW4bgLq1v81OxJX7ujv3s/edit) +1. [David Atanda](https://www.dropbox.com/scl/fi/99bghzgaxa6lr138s262w/GSoD-2021-Proposal_-Creating-Easy-to-learn-Tutorials-for-beginner-users-of-Wechaty.paper?dl=0&amp;rlkey=idczdeprj5fz3padp7ttzg4g7) +1. [Jaya Gupta](https://docs.google.com/document/d/1idLYEoqKcYoeID2jY-xufh3gRlDJhbmyy7MRhka38Q0/edit) +1. [Mukosa Joseph Mawa](https://docs.google.com/document/d/1WizCc8Tg047ZTnYX0wMA8tp213HVDKbCozgeLdbaeI8/edit#) +1. [Rohitesh Kumar Jain](https://docs.google.com/document/d/1YnUrU2-7gxn2e3t4HevDQbUYg3CqKRvMp_l2HFOioug/edit#) +1. [Rufai Mustapha](https://docs.google.com/document/d/1y_Gig1RTSKCAmzxiU-RHxLrDmtswLKn_ZdsEbPWm3Fg/edit) +1. [Sajen Sarvajith k](https://docs.google.com/document/d/1szNLbHT8k6ty7xYE9aRvFW2QGrOeTKea5lfcUHLyPic/edit) +1. [Shraddha Prasad](https://groups.google.com/g/wechaty/c/gN3gFp1ZKsU/m/Y32JBGYbAQAJ) +1. [Shwetal Soni](https://06412355400643469324.googlegroups.com/attach/1c45ede8c394c/shwetalsoni_gsod'21%20proposal_wechaty.pdf?part=0.1&amp;view=1&amp;vt=ANaJVrElF4m8VB99nbeqkqyqAljZNanks-RZwoh0kjtccYfVMzN9gQx54qseGHPw1adpo0qgrubdpE0C0LRokO9Ypjk6rRc-lJ9AqhFLotuKDmrGuMLvux4) +1. [Simin Liao (廖思閔)](https://groups.google.com/group/wechaty/attach/138b8c1c79a04/Season%20of%20Docs%20Application-Simin%20Liao.pdf?part=0.1&amp;view=1) +1. [Soumi Bardhan](https://docs.google.com/document/d/1q2_m0gqn7_cPLVPeMmIIzP_IEeGuQxEc_cztooOhLhc/edit) +1. [Souvik Biswas](https://docs.google.com/document/d/1MD9CwO6BoB664J67ozfygBJUaawazay7dDpcXB3jJcY/edit) &gt;+1.[阿比谢克Jaiswal](https://06412355400643469324.googlegroups.com/attach/2696b2e901464/GSoD%202021%20Project%20Proposal(Abhishek%20Jaiswal)。pdf？part=0.1&amp;view=1&amp;vt=ANaJVrH3pZ3BlMcLvPB0Hkmb5a0UOwzTxgIx35I_eiVuC-derjfLADp6bOkSNSplVMvJjxPvaSkAPmq-uhcbTI4yJfGY6tKzbegUoN3mwGlnY-7X-cuZUCU)+1.[AhmedEssam](https://docs.google.com/document/d/1GLxVZSUNDq_jf_OvZc82ZwjVK1ECB1srkBf2IyRYtGc/edit#heading=h.wu5oliio4h1o)+1.[阿尼鲁德·TPVS](https://groups.google.com/group/wechaty/attach/1f2bde59e72d6/Wechaty%20GSOD%202021.docx？part=0.1&amp;view=1)+1.[克里斯·Estepa](https://docs.google.com/document/d/1KQHHFqXrxadsfELzYREjANdW4bgLq1v81OxJX7ujv3s/edit)+1.[DavidAtanda](https://www.dropbox.com/scl/fi/99bghzgaxa6lr138s262w/GSoD-2021-Proposal_-Creating-Easy-to-learn-Tutorials-for-beginner-users-of-Wechaty.paper？dl=0&amp;rlkey=idczdeprj5fz3padp7ttzg4g7)+1.[JayaGupta](https://docs.google.com/document/d/1idLYEoqKcYoeID2jY-xufh3gRlDJhbmyy7MRhka38Q0/edit)+1.[穆科萨·约瑟夫·Mawa](https://docs.google.com/document/d/1WizCc8Tg047ZTnYX0wMA8tp213HVDKbCozgeLdbaeI8/edit#)+1.[罗库马尔Jain](https://docs.google.com/document/d/1YnUrU2-7gxn2e3t4HevDQbUYg3CqKRvMp_l2HFOioug/edit#)+1.[RufaiMustapha](https://docs.google.com/document/d/1y_Gig1RTSKCAmzxiU-RHxLrDmtswLKn_ZdsEbPWm3Fg/edit)+1.[萨文吉k](https://docs.google.com/document/d/1szNLbHT8k6ty7xYE9aRvFW2QGrOeTKea5lfcUHLyPic/edit)+1.[沙拉达Prasad](https://groups.google.com/g/wechaty/c/gN3gFp1ZKsU/m/Y32JBGYbAQAJ)+1.[瑞士的Soni](https://06412355400643469324.googlegroups.com/attach/1c45ede8c394c/shwetalsoni_gsod‘21%20proposal_wechaty.pdf？part=0.1&amp;view=1&amp;vt=ANaJVrElF4m8VB99nbeqkqyqAljZNanks-RZwoh0kjtccYfVMzN9gQx54qseGHPw1adpo0qgrubdpE0C0LRokO9Ypjk6rRc-lJ9AqhFLotuKDmrGuMLvux4)+1.[思敏廖（廖思閔）](https://groups.google.com/group/wechaty/attach/138b8c1c79a04/Season%20of%20Docs%20Application-Simin%20Liao.pdf？part=0.1&amp;view=1)+1.[苏米Bardhan](https://docs.google.com/document/d/1q2_m0gqn7_cPLVPeMmIIzP_IEeGuQxEc_cztooOhLhc/edit)+1.[南方的Biswas](https://docs.google.com/document/d/1MD9CwO6BoB664J67ozfygBJUaawazay7dDpcXB3jJcY/edit)
Just wondering if we should include all the names since some of them did not participate in GSoD at last and Rajiv joined as a separate project but his name is not on it.只是想知道，如果我们应该包括所有的名字，因为他们中的一些人没有参加&nbsp;GSoD&nbsp;的最后和拉吉夫加入了一个单独的项目，但他的名字没有在它。


In 在jekyll/_posts/2021-07-16-gsod-2021-publish-article.mdjekyll/_posts/2021-07-16-gsod-2021-publish-article.md:
&gt; +     你也可以了解[相关博客](https://wechaty.js.org/2021/05/16/gsod-2021-week1-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.o69fqys8gbda) +     ![1st](/assets/2021/07-gsod-2021-publish-article/1st.webp) + +   5月23日：进行了GSoD第二周会议，在本次会议上，每位与会者首先给出了自己的一周总结，并向社区报告了他们下一周的计划。一起讨论了一下Wechaty的未来愿景，Simin就PRs中经常出现的错误进行了讨论，接下来她向我们介绍了一个后续检查清单。最后我们进行了一个问答环节，下面是我们的合影。 +     你也可以了解[相关博客](https://wechaty.js.org/2021/05/23/gsod-2021-second-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.3ly9biu8mtyy) +     ![2nd](/assets/2021/07-gsod-2021-publish-article/2nd.webp) + +   6月6日：进行了GSoD第三周会议，在本次会议上，每位与会者首先做了一周的总结，并向社区汇报了他们下一周的计划，提出了对大型PRs的关注，讨论了PRs的范围和规模，对于缺乏每周跟进的团队解释了各自的原因。Simin说明了需要注意的相关事项并向大家进行了演示。最后我们进行了一个问答环节，并合影留念。 +     你也可以了解[相关博客](https://wechaty.js.org/2021/06/06/gsod-2021-third-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.lmf3j0zgmymr) +     ![3rd](/assets/2021/07-gsod-2021-publish-article/3rd.webp) + +   6月20日：进行了GSoD第四周会议，在本次会议上，首先每位参与者都做了一周的总结，并向社区汇报了他们下一周的计划，志愿者和技术作家们在进行一周总结的同时进行了讨论。最后大家进行了问答环节，并拍了一张可爱的合影。 +     你也可以了解[相关博客](https://wechaty.js.org/2021/06/22/gsod-2021-fourth-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.3am6kd2l4v24) +     ![4th](/assets/2021/07-gsod-2021-publish-article/4th.webp) + +   7月4日：进行了GSoD第五周会议，首先，每个参与者都进行了一周总结计划了下一周的工作，志愿者和技术作者们进行了讨论。Simin分享了一些关于Wechaty后续活动的信息，最后我们合影留念。 
Could you remove this sentence "Simin分享了一些关于Wechaty后续活动的信息"? I made a some modifications of the checking list instead of sharing some upcoming events. Thank you.你能把这句话删掉吗？“思敏分享了一些关于微信后续活动的信息”?我做了一些修改的检查列表，而不是分享一些即将发生的事件。谢谢你

—
You are receiving this because you authored the thread.您正在接收此消息，因为您创建了该线程。
Reply to this email directly, 直接回复此邮件，view it on GitHub在&nbsp;GitHub&nbsp;上查看, or 或unsubscribe取消订阅.

2021-07-23 06:09 UTC, huan commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +   7月18日：进行了GSoD第六次会议，同样，每个参与者都进行了一周总结与下一周的计划，志愿者和技术作者进行了讨论，并进行了问答环节，讨论和解决了大家存在的问题。
I'd like to suggest that we definitely should add them. Thanks to @Rohitesh-Kumar-Jain for the suggestion!

2021-07-23 06:11 UTC, huan commented
Hi @gangena , where did this PR go? Please leave comments for explanation when you close a PR.

2021-07-23 06:22 UTC, gangena commented
> Hi @gangena , where did this PR go? Please leave comments for explanation when you close a PR.

sorry，I I set up a new branch and wrote a new blog at <https://github.com/wechaty/wechaty.js.org/pull/1132>

2021-07-23 06:34 UTC, gangena commented
OK, I'll add it
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Huan (李卓桓)"; 
Date: 2021年7月23日(星期五) 下午2:09
To: "wechaty/wechaty.js.org"; 
Cc: "gangena"; "State change"; 
Subject: Re: [wechaty/wechaty.js.org] 2021gsod (#1129)

&nbsp;


 
@huan评论了这个拉取请求。
 
 
在jekyll/_posts/2021-07-16-gsod-2021-publish-article.md 中：
 &gt; +     你也可以了解[相关博客](https://wechaty.js.org/2021/05/23/gsod-2021-second-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.3ly9biu8mtyy) + ![2nd](/assets/2021/07-gsod-2021-publish-article/2nd.webp) + +   6月6日：进行了GSoD第三周会议，在本次会议上，每位与会者首先做了一周的总结，并向社区汇报了他们下一周的计划，提出了对大型PRs的关注，讨论了PRs的范围和规模，对于缺乏每周跟进的团队解释了各自的原因。Simin说明了需要注意的相关事项并向大家进行了演示。最后我们进行了一个问答环节，并合影留念。 +     你也可以了解[相关博客](https://wechaty.js.org/2021/06/06/gsod-2021-third-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.lmf3j0zgmymr) + ![3rd](/assets/2021/07-gsod-2021-publish-article/3rd.webp) + +   6月20日：进行了GSoD第四周会议，在本次会议上，首先每位参与者都做了一周的总结，并向社区汇报了他们下一周的计划，志愿者和技术作家们在进行一周总结的同时进行了讨论。最后大家进行了问答环节，并拍了一张可爱的合影。 +     你也可以了解[相关博客](https://wechaty.js.org/2021/06/22/gsod-2021-fourth-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.3am6kd2l4v24) + ![4th](/assets/2021/07-gsod-2021-publish-article/4th.webp) + +   7月4日：进行了GSoD第五周会议，首先，每个参与者都进行了一周总结计划了下一周的工作，志愿者和技术作者们进行了讨论。Simin分享了一些关于Wechaty后续活动的信息，最后我们合影留念。 +     你也可以了解[相关博客](https://wechaty.js.org/2021/07/06/gsod-2021-fifth-meeting/)和[会议详情](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.s6s37xc2auay) + ![5th](/assets/2021/07-gsod-2021-publish-article/5th.webp) + +   7月18日：进行了GSoD第六次会议，同样，每个参与者都进行了一周总结与下一周的计划，志愿者和技术作者进行了讨论，并进行了问答环节，讨论和解决了大家存在的问题。  
我想建议我们绝对应该添加它们。感谢@Rohitesh-Kumar-Jain的建议！
 
—
您收到此消息是因为您修改了打开/关闭状态。
直接回复此邮件，在 GitHub 上查看，或取消订阅。

2021-07-29 04:04 UTC, TommyLemon commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +### 一个好消息
interesting lol