Gsod
wechaty/docusaurus pull request #1132
Opened 2021-07-21 10:08 UTC by gangena

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-07-21 15:22 UTC, lijiarui approved these changes
LGTM！

2021-07-21 18:17 UTC, huan requested changes
The blog post is great!

However, cloud you please confirm that is your account represent the juzi? If not, please change your avatar from juzi logo to any other picture as you like.

Thank you very much.

2021-07-23 08:24 UTC, lijiarui commented
Hi @proudofsimin @Rohitesh-Kumar-Jain 

Pls help us review this blog, if you two approve this blog, then you can merge this.

2021-07-23 13:34 UTC, Rohitesh-Kumar-Jain commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +  今年，Wechaty已经与GSoD达成合作，请求的预算9500美元也已经被批准。
I believe it might be a good idea to mention full : Google Season of Docs, as outsiders might not be aware of what GSoD is, plus they mention themselves as [SoD](https://developers.google.com/season-of-docs), you can check that on their website and the emails they sent us. But using GSoD is fine as most participants abbreviate this to GSoD. It's just GSoD is more popular but the correct abbreviation is SoD, but we can go with GSoD I guess.

So at the end what I am suggesting is that to change `GSoD` to Google Season of Docs

2021-07-23 13:46 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-23 13:46 UTC, Rohitesh-Kumar-Jain commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +     ![6th](/assets/2021/07-gsod-2021-publish-article/6th.webp)
[Here's](https://github.com/wechaty/wechaty.js.org/pull/1130) the draft for the sixth meeting, you can refer to that as I have no more commits to push to that PR (from my side)

Also, I am reviewing on the English translation of the commit, so really don't know what exactly is written 

Like the title got translated like this, just to give you an idea, on what I have reviewed upon : )

<img width="516" alt="Screenshot 2021-07-23 at 7 14 25 PM" src="https://user-images.githubusercontent.com/62026125/126790775-bbe91383-f0b6-4312-b362-10a476bcb770.png">

2021-07-23 15:35 UTC, proudofsimin approved these changes
Should we add the participant list? If not, this PR looks great to me. Thank you.

2021-07-26 03:19 UTC, lijiarui commented
@proudofsimin @Rohitesh-Kumar-Jain Thanks for the great suggestion!

@gangena How do you think about this.

2021-07-26 03:53 UTC, gangena commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +  今年，Wechaty已经与GSoD达成合作，请求的预算9500美元也已经被批准。
OK, I've changed it. Please review again.

2021-07-26 03:54 UTC, gangena commented on jekyll/_posts/2021-07-16-gsod-2021-publish-article.md
> +     ![6th](/assets/2021/07-gsod-2021-publish-article/6th.webp)
I have edited this paragraph again.

2021-07-27 07:48 UTC, lijiarui requested changes

2021-07-27 07:48 UTC, lijiarui commented on .gitignore
> +*.png
Please remove this from this commit.

2021-08-03 08:23 UTC, gangena commented on .gitignore
> +*.png
It has been corrected.

2021-08-05 06:39 UTC, lijiarui commented
Hi @Rohitesh-Kumar-Jain and  @proudofsimin 

If you feel this blog is good for you, you can merge this PR and we will publish this to a Chinese press!

2021-08-05 06:40 UTC, lijiarui approved these changes
LGTM!

Looking forward to @Rohitesh-Kumar-Jain and  @proudofsimin to merge this PR!

2021-08-21 05:28 UTC, merged