Tutorial for examples/advanced/busy-bot
wechaty/docusaurus pull request #1134
Opened 2021-07-21 18:56 UTC by shwetalsoni

![Screenshot from 2021-07-22 00-19-51](https://user-images.githubusercontent.com/57187745/126544120-8deae077-0cdd-4308-a2f7-e93f5bfc5864.png)
![Screenshot from 2021-07-22 00-20-09](https://user-images.githubusercontent.com/57187745/126544128-90b3b04e-7750-4009-97b5-5f98b8a7b6de.png)
![Screenshot from 2021-07-22 00-20-24](https://user-images.githubusercontent.com/57187745/126544131-d48097a3-d8ac-44ae-9abe-2b609e67188b.png)
![Screenshot from 2021-07-22 00-20-35](https://user-images.githubusercontent.com/57187745/126544134-31f94d6a-d7e6-4ac6-be73-c8765399a3b0.png)
![Screenshot from 2021-07-22 00-20-48](https://user-images.githubusercontent.com/57187745/126544138-6c555a27-1604-4ade-bbad-1425fa05a751.png)
![Screenshot from 2021-07-22 00-21-05](https://user-images.githubusercontent.com/57187745/126544141-c81d0811-e4db-4bdc-9a32-9b82d1b07576.png)
![Screenshot from 2021-07-22 00-21-22](https://user-images.githubusercontent.com/57187745/126544145-47c5bbbb-4f14-4cef-8395-17149b4be489.png)
![Screenshot from 2021-07-22 00-21-36](https://user-images.githubusercontent.com/57187745/126544149-b7ddcd09-4018-4acf-b45d-51fb5c7e9956.png)
![Screenshot from 2021-07-22 00-21-50](https://user-images.githubusercontent.com/57187745/126544151-dfd9ed6d-7b78-43f9-b9bc-01f6c2022ebc.png)
![Screenshot from 2021-07-22 00-22-03](https://user-images.githubusercontent.com/57187745/126544155-f27426da-6a0b-4a91-8b21-c22cb98e24ac.png)
![Screenshot from 2021-07-22 00-22-15](https://user-images.githubusercontent.com/57187745/126544158-515b3c67-0b77-4151-b06f-e562e2621091.png)

2021-07-21 18:57 UTC, shwetalsoni commented
Tag #891

2021-07-23 15:43 UTC, proudofsimin approved these changes

2021-07-23 15:43 UTC, proudofsimin commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +### 1. Initialise project
initialize

2021-07-23 15:43 UTC, proudofsimin commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +Use the following command to initialise an npm project
initialize

2021-07-23 15:43 UTC, proudofsimin commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +Let's import required packages in `busy-bot.js` and initialise the bot by providing it a name and puppet to be used.
initialize

2021-07-24 05:04 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +Busy bot sends auto response message for you when you are busy.
it should be message, messages, or maybe message(s) ?

I am leaving upon you to select this

2021-07-24 05:17 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +Use the following command to initialise an npm project
Well this is intersting

Actually @proudofsimin, In India we follow British English in schools and offices. Anyways what English does Wechaty follows?

I think we should go with the type of English followed in China, and I wasn't able to find on the internet what type of English is being followed thier 😅 I saw conflicting anserws on quora https://www.quora.com/Which-is-preferred-in-mainland-China-American-English-or-British-English

2021-07-24 05:20 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +Busy bot sends auto response message for you when you are busy.
anyways is should be a message, if a single message is being sent

2021-07-24 06:16 UTC, shwetalsoni commented
@Rohitesh-Kumar-Jain and @proudofsimin I have applied the suggested fixes.

2021-07-24 07:56 UTC, Rohitesh-Kumar-Jain commented
> @Rohitesh-Kumar-Jain and @proudofsimin I have applied the suggested fixes.

you haven't applied my suggested change : message to a message or depending on the context messages if applicable

2021-07-24 07:57 UTC, Rohitesh-Kumar-Jain commented
And We were actually yet to decide which English variant we are following, because as per the English (UK one) taught in our schools, you were actually correct

2021-07-24 08:17 UTC, shwetalsoni commented
> > @Rohitesh-Kumar-Jain and @proudofsimin I have applied the suggested fixes.
> 
> you haven't applied my suggested change : message to a message or depending on the context messages if applicable

I thought you agreed upon keeping it `message` and to me even it sounds good. 
Actually what is happening here is:

either we can keep it as **Busy bot sends auto-response message for you when you are busy.** or
**Busy bot sends a message for you when you are busy**. or
but we can't change it to `messages` because only one message is being sent.

2021-07-24 08:20 UTC, shwetalsoni commented
> And We were actually yet to decide which English variant we are following, because as per the English (UK one) taught in our schools, you were actually correct

Yeah, that is true but I think since from the beginning in this documentation we have been following English(American one), so to maintain the consistency, its better to use it.

2021-07-24 08:30 UTC, sbis04 commented
Yes @shwetalsoni,  @Rohitesh-Kumar-Jain I believe we are trying to follow **English (US)** for the Wechaty documentation because previously also we have tried to keep that consistency of English (US), so it would be better to stick to it.

2021-07-24 08:46 UTC, sbis04 requested changes

2021-07-24 08:46 UTC, sbis04 commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +
I think this part can be formatted in a better way, like this (passing on some suggestions that @Rohitesh-Kumar-Jain had given me once 😅):

1. If you want to use **WhatsApp**, install `wechaty-puppet-whatsapp`:

  ```bash
  npm install wechaty-puppet-whatsapp
  ```
2. If you want to use **WeChat**, install `wechaty-puppet-wechat`:

  ```bash
  npm install wechaty-puppet-wechat
  ```

3. If you want to use **Wecom**, install `wechaty-puppet-wxwork`:

  ```bash
  npm install wechaty-puppet-wxwork
  ```

> You can find more information about the puppets [here](https://wechaty.js.org/docs/puppet-providers/).

2021-07-24 08:46 UTC, sbis04 commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +set WECHATY_PUPPET=wechaty-puppet-wechat
In these, you are setting the puppet but earlier in the code the bot is initialized like this:

```
const bot = new Wechaty({
  name: "busy-bot",
  puppet: "wechaty-puppet-wechat4u"
});
```

So, I guess this overrides the exported puppets and use `wechaty-puppet-wechat4u` by default, then exporting the puppets doesn't make sense. Let me know if I am wrong.

2021-07-24 09:42 UTC, shwetalsoni commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +set WECHATY_PUPPET=wechaty-puppet-wechat
@sbis04 yeah I think you are right, what do you think I should do. I mean, now we don't know if busy bot works with other puppets or not. No one has responded to issue #1119. 
So is it better to remove it during initializing bot or while exporting?

2021-07-24 09:47 UTC, shwetalsoni commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +
Thanks @sbis04 for suggesting this.

2021-07-24 10:03 UTC, Rohitesh-Kumar-Jain commented
> Yes @shwetalsoni, @Rohitesh-Kumar-Jain I believe we are trying to follow **English (US)** for the Wechaty documentation because previously also we have tried to keep that consistency of English (US), so it would be better to stick to it.

Yes let's stick to the US variant, thanks to @proudofsimin for pointing that

2021-07-24 10:05 UTC, Rohitesh-Kumar-Jain commented
> > > @Rohitesh-Kumar-Jain and @proudofsimin I have applied the suggested fixes.
> > 
> > 
> > you haven't applied my suggested change : message to a message or depending on the context messages if applicable
> 
> I thought you agreed upon keeping it `message` and to me even it sounds good.
> Actually what is happening here is:
> 
> either we can keep it as **Busy bot sends auto-response message for you when you are busy.** or
> **Busy bot sends a message for you when you are busy**. or
> but we can't change it to `messages` because only one message is being sent.

Well let's change it to Busy bot sends _**an**_ auto-response message for you when you are busy 😅

2021-07-24 10:07 UTC, Rohitesh-Kumar-Jain reviewed
I saw that Simin pointed out 3 initialize changes, and you have changed only 2

I Will give my approval once all comments gets resoved

2021-07-24 10:15 UTC, shwetalsoni commented
> I saw that Simin pointed out 3 initialize changes, and you have changed only 2
> 
> I Will give my approval once all comments gets resoved

Sorry, I missed it. Now it's done.

2021-07-24 10:25 UTC, sbis04 commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +set WECHATY_PUPPET=wechaty-puppet-wechat
Yeah, I think you can just remove the puppet from the initialization of the bot for now.

2021-07-24 10:27 UTC, shwetalsoni commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +set WECHATY_PUPPET=wechaty-puppet-wechat
ok thanks @sbis04

2021-07-24 12:47 UTC, sbis04 approved these changes

2021-07-24 15:31 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-25 02:46 UTC, sbis04 commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +[![TypeScript](https://img.shields.io/badge/%3C%2F%3E-TypeScript-blue.svg)](https://www.typescriptlang.org/)
This is using `JavaScript`, so you should update this tag to:
```
[![JavaScript](https://img.shields.io/badge/%3C%2F%3E-JavaScript-blue.svg)](https://www.javascript.com/)
```

2021-07-28 08:08 UTC, shwetalsoni commented
@Rohitesh-Kumar-Jain and @proudofsimin since this PR has got 3 approvals, I request you to add it to merging list.
Thank you ;)

2021-07-29 13:37 UTC, lijiarui requested changes

2021-07-29 13:37 UTC, lijiarui commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +
I think you should change as @sbis04 request: https://github.com/wechaty/wechaty.js.org/pull/1099#discussion_r676183033

2021-07-29 13:37 UTC, lijiarui commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +3. If you want to use wecom, install wechaty-puppet-wxwork
This should refer: https://github.com/wechaty/wechaty.js.org/pull/1099#discussion_r676183045

2021-07-29 13:37 UTC, lijiarui commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +Create a new folder called `src` and add a file `busy-bot.js`. You will be writing code here.
It seems you already create a folder `busy-bot`, so there is no need to create a new one `src` here.

2021-07-29 13:37 UTC, lijiarui commented on docusaurus/docs/examples/advanced/busy-bot.mdx
> +npx ts-node src/busy-bot.js
maybe we should change to `ts-node busy-bot.js` here.

2021-07-29 14:33 UTC, shwetalsoni commented
@lijiarui I have changed to requested changes.

2021-07-29 15:15 UTC, lijiarui approved these changes
Thanks for the contribution!

2021-07-30 12:53 UTC, merged