Left Nav bar Menu
wechaty/docusaurus pull request #1139
Opened 2021-07-25 10:08 UTC by abhishek-iiit

## Redefined left-sidebar
![Screenshot from 2021-07-24 16-36-14](https://user-images.githubusercontent.com/69477761/126866618-a1757f9e-0fc9-4edd-9075-164eccef79a8.png)

2021-07-25 10:09 UTC, abhishek-iiit commented
Reopen of PR #946 & linked to issue #896

2021-07-28 14:05 UTC, proudofsimin approved these changes
Thank you. This is great.

2021-07-28 14:47 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-29 15:29 UTC, lijiarui requested changes

2021-07-29 15:29 UTC, lijiarui commented on docusaurus/docs/howto/event.mdx
> +title: 'Add events and customise a bot'
I think `Listening Events` is better, how do you think of this @huan

2021-07-29 15:36 UTC, huan commented on docusaurus/docs/howto/event.mdx
> +title: 'Add events and customise a bot'
Thanks for loop me in.

I think both of the names are ok, and the differences between them are minor.

2021-07-29 16:58 UTC, abhishek-iiit commented on docusaurus/docs/howto/event.mdx
> +title: 'Add events and customise a bot'
Since, the differences is minor. I feel making it short can make better experience for the user :)

2021-08-23 16:36 UTC, lijiarui approved these changes
LGTM

2021-08-23 16:44 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit pls remove the merge conflict and then ping for merge

2021-08-23 16:54 UTC, lijiarui requested changes

2021-08-23 16:54 UTC, lijiarui commented on docusaurus/docs/howto/howto_docker.mdx
> +---
Please change the name to `docker`, instead of `howto_docker`, to make URL more beautiful.

2021-08-23 16:54 UTC, lijiarui commented on docusaurus/sidebars.ts
> +    'howto/howto_docker',
Please change this to docker here.

2021-08-23 20:12 UTC, abhishek-iiit commented on docusaurus/sidebars.ts
> +    'howto/howto_docker',
Thankyou lijiarui, got the changes done :)

2021-08-23 20:13 UTC, abhishek-iiit commented
> @abhishek-iiit pls remove the merge conflict and then ping for merge

@Rohitesh-Kumar-Jain changes done as suggested :)

2021-08-24 13:31 UTC, vasvi-sood approved these changes

2021-09-02 06:49 UTC, Rohitesh-Kumar-Jain commented
pls remove the conflicting files

2021-09-07 19:28 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-13 08:48 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood and @abhishek-iiit pls solve the merging conflict, and help yourself in merging the PR

2021-09-18 18:52 UTC, lijiarui requested changes

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/deploy-whatsapp.mdx
> +title: 'Deploy in Whatsapp'
Whatsapp --> WhatsApp

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/deploy-padlocal.mdx
> +title: Deploy in PadLocal
It looks strange saying deploy in padlocal,  we should say use padlocal in WeChat.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/deploy-wechat4u.mdx
> +title: Deploy in WeChat4U
It looks strange saying deploy in WeChat4U,  we should say use WeChat4U in WeChat

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Listening events](howto/event.mdx)
It seems you change to `Listen to events`, I think these two parts should be unified.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Managing contacts](howto/contact.mdx)
It seems you change to `Manage contacts`, I think these two parts should be unified.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Dealing with messages](howto/message.mdx)
It seems you change to `Deal with messages`, I think these two parts should be unified.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Making friends](howto/friendship.mdx)
It seems you change to `Send and accept friend requests`, I think these two parts should be unified.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Processing files](howto/file-box.mdx)
It seems you change to `Send and receive files`, I think these two parts should be unified.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Processing files](howto/file-box.mdx)
Btw, if there have more other parts, please add them as well.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Managing rooms](howto/room.mdx)
It seems you change to `Manage rooms`, I think these two parts should be unified.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/sidebars.ts
> +    'howto/deploy-padlocal',
padlocal is not a IM platform, it is a puppet used for WeChat.

2021-09-18 18:52 UTC, lijiarui commented on docusaurus/sidebars.ts
> +    'howto/deploy-wechat4u',
wechat4u is not an IM platform, it is a puppet used for WeChat.

2021-10-10 09:17 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood @abhishek-iiit

2021-10-16 16:16 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood @abhishek-iiit pls help us proceed towards the merge :)

2021-10-18 15:33 UTC, lijiarui submitted a review, later dismissed

2021-10-18 15:33 UTC, lijiarui commented on docusaurus/docs/howto/deploy-whatsapp.mdx
> +Whatsapp  is the most popular IM platform, so this how to guide focuses on deploying the bot in Whatsapp locally. You will learn how to deploy the bot in Whatsapp locally and integrate bot from the l
Change Whasapp to WhatsApp

2021-10-18 15:33 UTC, lijiarui commented on docusaurus/docs/howto/deploy-whatsapp.mdx
> +3. You must be familiar with [Wechaty Plugins](https://www.npmjs.com/package/wechaty-plugin-contrib).
I don't think knowing how to deploy WhatsApp needs the Wechaty Plugins knowledge.

2021-10-18 15:33 UTC, lijiarui commented on docusaurus/docs/howto/deploy-whatsapp.mdx
> +const {
Please change to import, as https://github.com/wechaty/getting-started/blob/main/examples/ding-dong-bot.js showed.

2021-10-18 15:33 UTC, lijiarui commented on docusaurus/docs/howto/deploy-whatsapp.mdx
> +* Get the starter template from [wechaty-getting-started](https://github.com/wechaty/wechaty-getting-started).
Please add WhatsApp official repo here: https://github.com/wechaty/wechaty-puppet-whatsapp

2021-10-18 15:33 UTC, lijiarui commented on docusaurus/docs/howto/heroku.mdx
> +<img src="../../static/img/howto/heroku/heroku1.webp"></img>
I think we should use markdown grammar instead of HTML here.

2021-10-18 15:33 UTC, lijiarui commented on docusaurus/docs/howto/heroku.mdx
> +<li>Push the feature branch of your local repository to the main branch of heroku using the following command:
I think we should use markdown grammar instead of HTML here.

2021-10-20 18:58 UTC, abhishek-iiit commented on docusaurus/docs/howto/deploy-whatsapp.mdx
> +* Get the starter template from [wechaty-getting-started](https://github.com/wechaty/wechaty-getting-started).
Added

2021-10-28 11:38 UTC, Rohitesh-Kumar-Jain commented
ping @lijiarui

2021-11-17 03:36 UTC, shraddhavp commented
@abhishek-iiit  please resolve the merge conflict ,then we are good to merge

2021-11-25 13:11 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit pls resolve the conflicts

2021-11-25 19:36 UTC, abhishek-iiit commented
> @abhishek-iiit pls resolve the conflicts

@Rohitesh-Kumar-Jain conflict resolved, thankyou :)

2021-11-26 01:59 UTC, merged