add doc for add-contact-into-room, change roomTopic
wechaty/docusaurus pull request #1143
Opened 2021-07-28 14:46 UTC by YipZong

add doc for add-contact-into-room, change roomTopic

- [v] Create your contributor profile (if you are a first time contributor)

2021-07-30 13:01 UTC, lijiarui requested changes
Thanks so much for the contribution!

Could you refer to https://github.com/wechaty/wechaty-getting-started to give more general docs for this?

Thanks!

2021-07-31 15:41 UTC, YipZong commented
@lijiarui Thanks for the comment. Added some general doc. Please take a look again. Thank you!

2021-08-24 09:27 UTC, lijiarui requested changes
Thanks for imporving wechaty docs.

Please refer: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/room-bot.js

And change according to wechaty official example. Then we would merge this!

Thanks again!

2021-08-24 09:27 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +Managing room is one of the important features in WeChaty. The word "room" here refers to Wechat rooms (also called groups).
WeChaty --> wechaty

2021-08-24 09:27 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +async function putPersonIntoRoom(person: Contact, room: Room) {
According https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/room-bot.js 

Maybe we change to `putInRoom()` is better.

2021-08-24 09:27 UTC, lijiarui commented on docusaurus/docs/howto/room.md
> +if (msg.text() === 'ZhiMaKaiMen') {
Wechaty always using ding as the test message. So I suggesting changing to ding in official docs.

2021-08-25 12:59 UTC, YipZong commented on docusaurus/docs/howto/room.md
> +Managing room is one of the important features in WeChaty. The word "room" here refers to Wechat rooms (also called groups).
changed to lower case in the latest commit. Please take a look!

2021-08-25 13:00 UTC, YipZong commented on docusaurus/docs/howto/room.md
> +async function putPersonIntoRoom(person: Contact, room: Room) {
Method name changed to `putInRoom` in the latest commit. Please take a look! Thank you！

2021-08-25 13:00 UTC, YipZong commented on docusaurus/docs/howto/room.md
> +if (msg.text() === 'ZhiMaKaiMen') {
Noted. Changed the secret to ding. Please take a look!

2021-09-01 15:19 UTC, huan approved these changes
LGTM

2021-09-01 15:20 UTC, lijiarui approved these changes

2021-09-01 15:21 UTC, merged

2021-09-01 15:21 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited YipZong to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _**ruirui_0914**_  and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!