Improve tutorials running locally page
wechaty/docusaurus pull request #1148
Opened 2021-07-30 03:20 UTC by sbis04

## Changes

* Have made the changes suggested by @lijiarui in [#1076 (comment)](https://github.com/wechaty/wechaty.js.org/pull/1076#discussion_r676181074).

* Added the missing Wechaty and TypeScript badges and properly formatted the reference link.
* Converted the images to `.webp` format

The updated page looks like this:

![Running locally page](https://user-images.githubusercontent.com/43280874/127594541-ec4401f7-ac8c-4d35-a828-9431a6f94f22.png)

Fixes #1147 
Tag #891

2021-07-30 05:42 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-30 10:27 UTC, shwetalsoni approved these changes

2021-07-30 14:37 UTC, proudofsimin approved these changes

2021-07-30 19:40 UTC, lijiarui requested changes

2021-07-30 19:40 UTC, lijiarui commented on docusaurus/docs/getting-started/running-locally.mdx
> +  src="https://codesandbox.io/embed/github/sbis04/wechaty-ding-dong/tree/main?fontsize=12&hidenavigation=1&module=%2Fding-dong-bot.ts&theme=dark"
Please change to wechaty official repo.

2021-08-01 02:50 UTC, sbis04 commented on docusaurus/docs/getting-started/running-locally.mdx
> +  src="https://codesandbox.io/embed/github/sbis04/wechaty-ding-dong/tree/main?fontsize=12&hidenavigation=1&module=%2Fding-dong-bot.ts&theme=dark"
@lijiarui I have a PR to the `wechaty-getting-started` repo for fixing this error: https://github.com/wechaty/wechaty-getting-started/pull/192

If you can accept that, I will use the official repo link here.

2021-08-11 13:53 UTC, sbis04 commented
@lijiarui Please have a look at the PR in the `wechaty-getting-started` repo: https://github.com/wechaty/wechaty-getting-started/pull/192

2021-08-11 14:42 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/getting-started/running-locally.mdx
> +  src="https://codesandbox.io/embed/github/sbis04/wechaty-ding-dong/tree/main?fontsize=12&hidenavigation=1&module=%2Fding-dong-bot.ts&theme=dark"
> If you can accept that, I will use the official repo link here.

It's failing test, pls make sure that your PR is passing automated tests

2021-08-11 15:44 UTC, sbis04 commented on docusaurus/docs/getting-started/running-locally.mdx
> +  src="https://codesandbox.io/embed/github/sbis04/wechaty-ding-dong/tree/main?fontsize=12&hidenavigation=1&module=%2Fding-dong-bot.ts&theme=dark"
@Rohitesh-Kumar-Jain the automated tests are not specific to that PR, it's because of some unit tests which requires some secret to be present as mentioned by Huan [here](https://github.com/wechaty/wechaty-getting-started/pull/193#issuecomment-890607316).

2021-09-03 19:20 UTC, sbis04 commented
ping @lijiarui

2021-09-07 19:38 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 03:12 UTC, sbis04 commented
@huan this PR needs to be approved by @lijiarui as well for it to be eligible for merging

2021-09-08 04:40 UTC, huan commented
@sbis04 understand.

@lijiarui please help to review this PR so that we can either improve it or merge it.

Thank you very much!

2021-09-09 10:32 UTC, huan commented
ping @lijiarui

2021-09-13 14:18 UTC, lijiarui requested changes
I think we should keep the wechaty official repo here.

We may change the official repo link then we can merge this PR.

2021-09-13 14:18 UTC, lijiarui commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
We should always use wechaty official repo here, or it would make it hard to maintain in the future, please change as following:

- Maybe we should change back `sbis04` repo to `wechaty` official repo here.
- We should keep using wechaty-getting-started

2021-09-13 14:18 UTC, lijiarui commented on docusaurus/docs/getting-started/running-locally.mdx
> +  src="https://codesandbox.io/embed/github/sbis04/wechaty-ding-dong/tree/main?fontsize=12&hidenavigation=1&module=%2Fding-dong-bot.ts&theme=dark"
I think we should use official link here, and then fix the wechaty-getting-started repo.

It seems https://github.com/wechaty/wechaty-getting-started/pull/192 didn't pass Github action, please make GitHub action green there.

2021-09-14 11:10 UTC, sbis04 commented on docusaurus/docs/getting-started/running-locally.mdx
> +[![Edit wechaty-getting-started](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/sbis04/wechaty-ding-dong/tree/main/?fontsize=14&hidenavigation=1&theme=dark)
@lijiarui I have restored the link to the wechaty official repo now

2021-09-14 12:12 UTC, sbis04 commented
@lijiarui I have restored the link to the wechaty official repo now

2021-09-15 14:43 UTC, lijiarui approved these changes
LGTM

2021-09-15 15:14 UTC, merged