Update puppet providers lark
wechaty/docusaurus pull request #1152
Opened 2021-07-31 13:53 UTC by Soumi7

Updates Puppet Providers - Lark section in references

References issue #890

## Screenshots 

![Screenshot from 2021-07-31 18-22-36](https://user-images.githubusercontent.com/51290447/127742007-9781b6fb-47f4-4a75-9e6c-13ee902f4d99.png)

![Screenshot from 2021-07-31 18-22-46](https://user-images.githubusercontent.com/51290447/127742010-86d09383-0b15-4306-beae-91a99ab119c4.png)

![Screenshot from 2021-07-31 18-22-50](https://user-images.githubusercontent.com/51290447/127742012-a4b74c1e-7de7-4cd6-b0bc-02f47d44fd88.png)

![Screenshot from 2021-07-31 18-22-53](https://user-images.githubusercontent.com/51290447/127742016-e1dae97a-0ac8-4040-bc4a-39eede678d5e.png)

![Screenshot from 2021-07-31 18-22-57](https://user-images.githubusercontent.com/51290447/127742019-c014ae6d-21a1-425d-9447-22a872c0cf7d.png)

![Screenshot from 2021-07-31 18-23-01](https://user-images.githubusercontent.com/51290447/127742021-823962fb-1788-493a-8c82-8c55bd4d0de8.png)

![Screenshot from 2021-07-31 18-23-04](https://user-images.githubusercontent.com/51290447/127742023-86f89448-0eef-4383-86f0-34bde430451c.png)

2021-08-01 09:45 UTC, proudofsimin requested changes
Please remove the code snippet and add #1101 in the usage section after it is merged. Thank you.

2021-09-07 19:38 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-09 07:08 UTC, Soumi7 commented
Waiting on #1101 to get merged.

2021-09-11 12:19 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-12 08:54 UTC, Soumi7 commented
@proudofsimin could you please approve this?

2021-09-12 13:04 UTC, shraddhavp approved these changes

2021-09-13 08:38 UTC, Rohitesh-Kumar-Jain commented
ping @proudofsimin

2021-09-15 17:03 UTC, proudofsimin commented
> @proudofsimin could you please approve this?

Did you add the reference page of how-to guides yet?

2021-09-17 07:11 UTC, Soumi7 commented
> > @proudofsimin could you please approve this?
> 
> Did you add the reference page of how-to guides yet?

That PR has not been merged yet. @proudofsimin Should I still add the contents anyway?

2021-09-18 16:32 UTC, proudofsimin commented
> > > @proudofsimin could you please approve this?
> > 
> > 
> > Did you add the reference page of how-to guides yet?
> 
> That PR (#1101) has not been merged yet. @proudofsimin Should I still add the contents anyway?

Hi @huan,
Could you review #1101 first since we are awaiting it to refer to in this PR?  Or if you have other concerns or feel not necessary of the reference, please do let us know. Thank you.

2021-09-18 19:00 UTC, lijiarui commented
> Hi @huan,
Could you review #1101 first since we are awaiting it to refer to in this PR? Or if you have other concerns or feel not necessary of the reference, please do let us know. Thank you.

Hi @proudofsimin I have some comments in the lark part in #1101

2021-09-18 19:07 UTC, huan commented
@proudofsimin Thanks for ping me Simin!

The #1101 is good to be merged after all the request changes have been fulfilled.

And I believe it should be referred from this page because they are highly related.

2021-09-19 13:51 UTC, Soumi7 commented
@proudofsimin I have updated this PR with the changes in #1101, taking @lijiarui 's comments in mind. Can you please check this? Thanks.

2021-09-19 18:26 UTC, proudofsimin approved these changes
Hi I guess you misunderstand a bit. I was only asking you to add the URL of that PR so if the users would like to learn more about how to use in WhatsApp, they could quickly allocate themselves to the correct positions. same issue with #1153

2021-09-21 11:42 UTC, lijiarui requested changes
It seems this puppet support the following features as [project introduction](https://github.com/wechaty/wechaty-puppet-lark#%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D) introduced.

1. Send & Receive Messages (Text, Image, Video, File)
2. Get Contact List

2021-09-21 11:43 UTC, lijiarui commented
I would like to invite @Roxanne718 to review this issue if she has time since she is the creator of this puppet. ：）

2021-09-21 11:56 UTC, lijiarui requested changes

2021-09-21 11:56 UTC, lijiarui commented on docusaurus/docs/puppet-providers/lark.md
> +### Live Coding
Please change `Live Coding` to `Presentation`

2021-09-21 11:56 UTC, lijiarui commented on docusaurus/docs/puppet-providers/lark.md
> +### Video Demo
Please change `Video Demo` to `Live Coding`

2021-09-21 11:56 UTC, lijiarui commented on docusaurus/docs/puppet-providers/lark.md
>  ## History
I think we should remove the `History` part here, because novice developers don't need to care more about history, they should pay more attention to how to use it.

I suggest we add [How to run](https://github.com/wechaty/wechaty-puppet-lark) as the wechaty-puppet-lark repo showed.

2021-09-21 11:56 UTC, lijiarui commented on docusaurus/docs/puppet-providers/lark.md
> +1. [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人, 范蕊, Sep 30, 2020](https://wechaty.js.org/2020/09/30/wechaty-puppet-lark-final-blog/)
Please add all of this related blog to this part:

- https://wechaty.js.org/2020/07/29/wechaty-puppet-lark-plan-blog/
- https://wechaty.js.org/2020/08/19/wechaty-puppet-lark-mid-term-blog/
- https://wechaty.js.org/2020/09/30/wechaty-puppet-lark-final-blog/
- https://wechaty.js.org/2021/07/14/ospp-plan-wechaty-puppet-lark/

2021-09-21 17:32 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/lark.md
> +### Video Demo
Done.

2021-09-21 17:33 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/lark.md
>  ## History
Added.

2021-09-21 17:33 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/lark.md
> +1. [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人, 范蕊, Sep 30, 2020](https://wechaty.js.org/2020/09/30/wechaty-puppet-lark-final-blog/)
Added.

2021-09-22 08:08 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/lark.md
> +### Live Coding
Done.

2021-09-23 06:22 UTC, Rohitesh-Kumar-Jain approved these changes
I think @Soumi7 you have implemented the requested changes, always re-request review, and comment that you have implemented the suggested changes, so that others can know, when they are ready to review : )

And one other thing, pls use meaningful commit messages next time 😅

2021-09-23 06:42 UTC, Soumi7 commented
> I think @Soumi7 you have implemented the requested changes, always re-request review, and comment that you have implemented the suggested changes, so that others can know, when they are ready to review : )
> 
> And one other thing, pls use meaningful commit messages next time 😅

Yeah actually I was trying to fix an error which was occurring repeatedly, hence those commit messages. Will keep in mind.

2021-09-27 11:26 UTC, Soumi7 commented
@lijiarui ping

2021-10-13 12:47 UTC, huan commented
@lijiarui ping

2021-10-16 16:18 UTC, Rohitesh-Kumar-Jain commented
ping @lijiarui

2021-10-16 18:18 UTC, lijiarui approved these changes
LGTM

2021-10-16 18:18 UTC, merged