Update Puppet Providers Whatsapp
wechaty/docusaurus pull request #1153
Opened 2021-07-31 14:36 UTC by Soumi7

Updates Puppet Providers - Whatsapp section in references

References issue #890

![Screenshot from 2021-07-31 20-01-19](https://user-images.githubusercontent.com/51290447/127743224-06f8429d-e38b-4c0b-a180-cbefdfcf0fa0.png)

![Screenshot from 2021-07-31 20-01-24](https://user-images.githubusercontent.com/51290447/127743226-43da8708-0bc3-43fe-b109-aa04fc675872.png)

![Screenshot from 2021-07-31 20-01-28](https://user-images.githubusercontent.com/51290447/127743241-24e143d3-43d7-4859-a9cb-446cc321b170.png)

![Screenshot from 2021-07-31 20-01-33](https://user-images.githubusercontent.com/51290447/127743244-c518b319-16c4-4e4b-a8a6-132d39a9f46a.png)

![Screenshot from 2021-07-31 20-01-36](https://user-images.githubusercontent.com/51290447/127743248-cd87124c-4ecd-4def-8652-1f89061a6b7c.png)

![Screenshot from 2021-07-31 20-01-39](https://user-images.githubusercontent.com/51290447/127743252-1f04cd3a-5c56-4485-b445-7fd8e84254e6.png)

2021-08-01 09:56 UTC, proudofsimin requested changes
Please add #1106 after it is merged.

2021-08-15 08:54 UTC, shraddhavp commented
LGTM

2021-09-07 19:39 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-11 11:38 UTC, shraddhavp approved these changes
LGTM

2021-09-12 13:03 UTC, shraddhavp commented
@Rohitesh-Kumar-Jain

2021-09-12 13:03 UTC, shraddhavp commented
@proudofsimin

2021-09-13 08:37 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-13 08:38 UTC, Rohitesh-Kumar-Jain commented
@proudofsimin could pls review once more ?

2021-09-15 16:03 UTC, proudofsimin commented
> @proudofsimin

Did you add the reference to the page I asked before? Where is the link?

2021-09-18 18:38 UTC, lijiarui requested changes

2021-09-18 18:38 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Wechaty Puppet Whatsapp is built on top of whatsapp-web.js, which is A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app, created by Pedro S. Lopez, @pedroslopez
Please add the two link for reference:

- `[whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js)`
- `[@pedroslopez](https://github.com/pedroslopez)`

2021-09-18 18:38 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +  .on('message', message => log.info(`Message: ${message}`))
Please change the code follow the latest example: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/ding-dong-bot.js or https://github.com/wechaty/wechaty-puppet-whatsapp#puppet-whatsapp

2021-09-18 18:38 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
>  - [@univerone](https://wechaty.js.org/contributors/univerone)
Please add Huan as well: @huan Huan LI <zixia@zixia.net>

See: https://github.com/wechaty/wechaty-puppet-whatsapp

2021-09-19 06:59 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Wechaty Puppet Whatsapp is built on top of whatsapp-web.js, which is A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app, created by Pedro S. Lopez, @pedroslopez
Updated, thanks.

2021-09-19 06:59 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
>  - [@univerone](https://wechaty.js.org/contributors/univerone)
Updated, thanks.

2021-09-19 12:34 UTC, Soumi7 commented
@proudofsimin Have added contents from #1106 . Please let me know if this is okay.

2021-09-19 13:54 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +  .on('message', message => log.info(`Message: ${message}`))
Updated, thanks.

2021-09-19 18:25 UTC, proudofsimin approved these changes
Hi I guess you misunderstand a bit. I was only asking you to add the URL of that PR so if the users would like to learn more about how to use in WhatsApp, they could quickly allocate themselves to the correct positions. similar issue with #1152

2021-09-20 04:45 UTC, Soumi7 commented
@lijiarui @proudofsimin Have made the changes you suggested.

2021-09-21 11:05 UTC, lijiarui requested changes
Please change the title and sidebar_label from `Whatsapp` to `WhatsApp`

2021-09-21 11:23 UTC, lijiarui requested changes

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +- [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js)
I think maybe we change to the following:

```
- Build on top of(A WhatsApp client library for NodeJS): [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js)
```

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +- [@pedroslopez](https://github.com/pedroslopez)
I think maybe we change to the following:

```
- [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) Creator: [@pedroslopez](https://github.com/pedroslopez)
```

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Wechaty Puppet Whatsapp is built on top of whatsapp-web.js, which is A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app, created by Pedro S. Lopez, @pedroslopez
Actually, I think the way you updated looked wired, what I mean the change is: 

```
Wechaty Puppet Whatsapp is built on top of [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js), which is A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app, created by Pedro S. Lopez, [@pedroslopez](https://github.com/pedroslopez)
```

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +const { Wechaty, log} = require("wechaty");
Please refer to： https://github.com/wechaty/wechaty-getting-started/blob/main/examples/basic/ding-dong-bot.js

Use ESM import instead or require.

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
>  - [Wechaty Puppet Whatsapp Has been Published, Shan, Feb 15, 2021](https://wechaty.js.org/2021/02/15/publishment-of-wechaty-whatapp-puppet/)
Your link is a deadlink, please change to :

https://wechaty.js.org/2021/02/15/publishment-of-wechaty-whatsapp-puppet/

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +wechaty-puppet-whatsapp is an open-source project. If you’re interested in contributing to this project, check out the contribution guidelines to learn more, and welcome to join the Wechaty Developer
It would be better to add a link like the following:

```
or our [Gitter network](https://gitter.im/wechaty/wechaty) to join our community.
```

2021-09-21 11:23 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
>  - [@univerone](https://wechaty.js.org/contributors/univerone)
You updated in a really wired way... Please do a preview before you ask mentors for review:

![image](https://user-images.githubusercontent.com/6419514/134161875-77b17580-d74f-4f11-b0bc-cea57593e5b4.png)

Change as following:

```
[@huan](https://github.com/huan) [Huan LI](http://linkedin.com/in/zixia) \<zixia@zixia.net\>
```

2021-09-21 11:44 UTC, lijiarui commented
I would like to invite @univerone to review this issue if she has time since she is the creator of this puppet. ：）

2021-09-21 16:04 UTC, lijiarui commented
> Please change the title and sidebar_label from `Whatsapp` to `WhatsApp`

It seems your commit didn't fix this.

2021-09-21 16:06 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Wechaty Puppet Whatsapp is built on top of whatsapp-web.js, which is A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app, created by Pedro S. Lopez, @pedroslopez
@Soumi7 No, you didn't update as request, so please don't resolve this request.

2021-09-21 16:08 UTC, lijiarui requested changes

2021-09-21 16:08 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +- [@huan](https://github.com/huan) [Huan LI](http://linkedin.com/in/zixia) \<zixia@zixia.net\>
Maybe we should remove `\` for the email here.

2021-09-22 08:27 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Wechaty Puppet Whatsapp is built on top of whatsapp-web.js, which is A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app, created by Pedro S. Lopez, @pedroslopez
I have updated it again.

2021-09-22 08:27 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
>  - [@univerone](https://wechaty.js.org/contributors/univerone)
Updated it again.

2021-09-22 08:28 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +- [@huan](https://github.com/huan) [Huan LI](http://linkedin.com/in/zixia) \<zixia@zixia.net\>
Done

2021-09-22 09:37 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
>  - [@univerone](https://wechaty.js.org/contributors/univerone)
Updated again

2021-09-22 09:37 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +- [@pedroslopez](https://github.com/pedroslopez)
Updated again

2021-10-12 06:48 UTC, Soumi7 commented
@lijiarui ping

2021-10-16 16:18 UTC, Rohitesh-Kumar-Jain commented
ping @lijiarui

2021-10-16 18:14 UTC, lijiarui requested changes
Please change as I request, thanks!

2021-10-16 18:14 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +}= require('wechaty')
We should use import here, see: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/ding-dong-bot.js

2021-10-16 18:14 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +const qrTerm = require('qrcode-terminal')
We should use import here, see: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/ding-dong-bot.js

2021-10-16 18:14 UTC, lijiarui commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Scan it using your Whatsapp and you are ready to play with the bot! You can read more about deploying a whatsapp puppet [here](https://github.com/wechaty/wechaty.js.org/pull/1106).
Please change the link: https://github.com/wechaty/wechaty.js.org/pull/1106 Since this link is already merged.

2021-10-17 10:37 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +Scan it using your Whatsapp and you are ready to play with the bot! You can read more about deploying a whatsapp puppet [here](https://github.com/wechaty/wechaty.js.org/pull/1106).
Replaced link @lijiarui

2021-10-17 10:38 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +const qrTerm = require('qrcode-terminal')
Replaced.

2021-10-17 10:38 UTC, Soumi7 commented on docusaurus/docs/puppet-providers/whatsapp.md
> +}= require('wechaty')
Changed.

2021-10-17 15:11 UTC, lijiarui approved these changes
Good job！ Cheers！

2021-10-17 15:23 UTC, merged