Gitter section
wechaty/docusaurus pull request #1154
Opened 2021-07-31 18:45 UTC by vasvi-sood

![gitter1](https://user-images.githubusercontent.com/76619050/127749638-da586e66-1637-4587-8eb9-fdd51903d249.png)
![gitter2](https://user-images.githubusercontent.com/76619050/127749641-7e1b5601-a980-4240-a759-1d73505e3fd1.png)
![gitter3](https://user-images.githubusercontent.com/76619050/127749643-42e05654-6ea3-4cc2-94f0-e20a4dd6678b.png)

2021-08-01 04:44 UTC, abhishek-iiit commented
Linked to issue #896

2021-08-01 04:51 UTC, abhishek-iiit requested changes
It would be nice for the user, if they find the `Blogs` section at the end. Could you please add as suggested. Thank you:)

2021-08-04 14:37 UTC, Rohitesh-Kumar-Jain approved these changes

2021-08-04 16:21 UTC, proudofsimin approved these changes

2021-08-15 09:41 UTC, vasvi-sood commented
> It would be nice for the user, if they find the `Blogs` section at the end. Could you please add as suggested and same for #1106 too Thank you:)

Changes done as suggested. Thankyou!

2021-09-07 19:40 UTC, huan approved these changes
LGTM.

```diff
- docusaurus/static/img/docs/howto/IM_platform/wechaty-puppet-gitter.webp 
+ docusaurus/static/img/docs/howto/deploy-gitter/wechaty-puppet-gitter.webp 
```

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 05:13 UTC, abhishek-iiit approved these changes
LGTM

2021-09-10 15:44 UTC, huan approved these changes
Thanks for adding this gitter howto!

2021-09-10 15:44 UTC, huan commented on docusaurus/docs/howto/deploy-gitter.mdx
> +```bash
`bash` -> `ts`

2021-09-13 08:48 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood and @abhishek-iiit pls solve the merging conflict, and help yourself in merging the PR

2021-09-13 19:43 UTC, abhishek-iiit commented on docusaurus/docs/howto/deploy-gitter.mdx
> +```bash
Thankyou for your feedback, changes done as suggested :)

2021-09-13 19:44 UTC, abhishek-iiit commented
Merging PR with no conflicts and 4 approvals :)

2021-09-13 19:44 UTC, merged