Buildwechaty
wechaty/docusaurus pull request #1158
Opened 2021-08-03 08:59 UTC by gangena

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-09 09:50 UTC, gangena commented
Corresponding blog here<https://github.com/wechaty/wechaty.js.org/issues/909>

2021-08-24 02:34 UTC, lijiarui requested changes

2021-08-24 02:34 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +author: juzibot
Please change this to `lijiarui`

2021-08-24 02:34 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +  - summer-2020
Please remove the useless tag.

Add some useful tag for this, eg: chatbot, global AI.

2021-08-24 02:34 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +句子互动的创始人，GitHub上开源项目Wechaty上面的联合作者，Wechaty在github上面有超过1万star，并搭建了一个覆盖全球的微信平台开发者社区，微软的AIWP，出版书：《Chatbot从0到1》，已经在京东上架，欢迎大家阅读，本次分享里面会简单介绍书中的内容，如何从0到1搭建一个聊天机器人，
AIWP--> AI MVP

2021-08-24 02:34 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![intro](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/04.webp)
It seems strange the image name you use. Please change to a more meaningful image name.

2021-08-24 06:39 UTC, gangena commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![intro](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/04.webp)
new blog at <https://github.com/wechaty/wechaty.js.org/pull/1221>

2021-08-24 08:59 UTC, lijiarui commented
duplicate with  #1221

2022-03-30 12:06 UTC, huan commented
Close because it's duplicated with an already published blog.

I hope the PR creator can take more responsibility for managing the PRs that they created in the future. @lijiarui

2022-03-30 12:06 UTC, closed without merging