Mid Term Blog: Tutorials
wechaty/docusaurus pull request #1160
Opened 2021-08-03 10:52 UTC by shwetalsoni

![Screenshot from 2021-08-03 16-10-43](https://user-images.githubusercontent.com/57187745/128003509-f9143ba9-573f-4502-8c3a-0f604765e30f.png)
![Screenshot from 2021-08-03 16-11-11](https://user-images.githubusercontent.com/57187745/128003513-befea864-4795-4757-a957-f9fca4175b3c.png)
![Screenshot from 2021-08-03 16-12-10](https://user-images.githubusercontent.com/57187745/128003551-9c0c3392-a3ed-4738-846b-3f23b80e176b.png)
![Screenshot from 2021-08-03 16-12-19](https://user-images.githubusercontent.com/57187745/128003561-5fcf3c6c-c310-4488-9436-28d9306b7abd.png)
![Screenshot from 2021-08-03 16-12-38](https://user-images.githubusercontent.com/57187745/128003562-1c7d8f1d-0ab5-4b22-a2d2-eabdbc59f623.png)
![Screenshot from 2021-08-03 16-12-55](https://user-images.githubusercontent.com/57187745/128003564-e83ca1a2-5c8a-489a-87a5-11e79e35881a.png)
![Screenshot from 2021-08-03 16-13-04](https://user-images.githubusercontent.com/57187745/128003570-9907213a-70fb-404b-80af-353adfc649f6.png)
![Screenshot from 2021-08-03 16-13-14](https://user-images.githubusercontent.com/57187745/128003572-7b71b89b-6a6a-41ae-afbd-75ec3aa88ab4.png)
![Screenshot from 2021-08-03 16-13-28](https://user-images.githubusercontent.com/57187745/128003574-c1458b92-796f-467c-9d5e-527059722140.png)
![Screenshot from 2021-08-03 16-13-37](https://user-images.githubusercontent.com/57187745/128003575-99e8001a-9eca-4006-a189-f72572dcef20.png)
![Screenshot from 2021-08-03 16-13-45](https://user-images.githubusercontent.com/57187745/128003576-9fb4a42b-efba-48fb-810d-24026205c7b3.png)
![Screenshot from 2021-08-03 16-13-56](https://user-images.githubusercontent.com/57187745/128003578-aa5a5aaf-c69e-4429-92c2-f461315305bb.png)
![Screenshot from 2021-08-03 16-14-10](https://user-images.githubusercontent.com/57187745/128003582-7ba36399-b95c-46dc-9483-c1ea0677e1f1.png)

2021-08-04 14:31 UTC, Rohitesh-Kumar-Jain approved these changes
I feel it's not a good idea to put your email in the main heading along with your name, but anyways as this not a documentation for Wechaty, you can keep that any way you wish to keep it.

2021-08-04 14:38 UTC, shwetalsoni commented
> I feel it's not a good idea to put your email in the main heading along with your name, but anyways as this not a documentation for Wechaty, you can keep that any way you wish to keep it.

Ok, I'll keep that in mind from next time :)

2021-08-05 11:54 UTC, proudofsimin approved these changes
Thank you.

2021-08-10 14:50 UTC, sbis04 approved these changes

2021-08-12 07:23 UTC, shwetalsoni commented
@Rohitesh-Kumar-Jain and @proudofsimin please add this PR to the merging list

Thank you :)

2021-08-20 17:33 UTC, lijiarui requested changes
Pls change as I request, thanks!

2021-08-20 17:33 UTC, lijiarui commented on jekyll/_posts/2021-08-03-gsod-2021-mid-term-blog-tutorials.md
> +categories: tutorial
Please change the categories to `gsod` here.

2021-08-20 19:24 UTC, shwetalsoni commented on jekyll/_posts/2021-08-03-gsod-2021-mid-term-blog-tutorials.md
> +categories: tutorial
@lijiarui I have applied the requested changes.

2021-08-23 12:53 UTC, lijiarui approved these changes
LGTM

2021-08-23 13:16 UTC, merged