Open-source Wechaty in Python, Go, and Java
wechaty/docusaurus pull request #1166
Opened 2021-08-04 09:13 UTC by gangena

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-06 19:12 UTC, lijiarui requested changes
LGTM

2021-08-06 19:12 UTC, lijiarui commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +文档：<https://wechaty.js.org/v/zh/>
Please change this to http://wechaty.js.org/

2021-08-09 09:45 UTC, gangena commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +文档：<https://wechaty.js.org/v/zh/>
It has been changed.

2021-08-09 09:47 UTC, gangena commented
Corresponding blog herehttps://github.com/wechaty/wechaty.js.org/issues/909

2021-08-09 09:48 UTC, gangena commented
Corresponding blog here<https://github.com/wechaty/wechaty.js.org/issues/909>

2021-08-24 02:36 UTC, lijiarui requested changes

2021-08-24 02:36 UTC, lijiarui commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +  - summer-2021
Please remove the useless tag here.

And add more meaningful tag, such as python, go, java

2021-08-24 02:36 UTC, lijiarui commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +
Please remove redundant lines here.

2021-08-24 06:45 UTC, gangena commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +
It's all changed.

2021-08-24 06:57 UTC, lijiarui commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +  - summer-2021
How about this? @gangena

2021-08-24 07:01 UTC, gangena commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +  - summer-2021
It's also changed.

2021-08-24 08:25 UTC, lijiarui requested changes

2021-08-24 08:25 UTC, lijiarui commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +  - summer-2021
It didn't change, please check for this more carefully

2021-08-24 08:25 UTC, lijiarui commented on jekyll/_posts/2020-04-20-open-source-wechaty-in-python-go-and-java.md
> +
No, you haven't change yet.

2022-03-30 12:04 UTC, huan commented
Close because the post has already been published.

2022-03-30 12:04 UTC, closed without merging