Create 2021-08-11-living_bot-paddleXwechaty.md
wechaty/docusaurus pull request #1190
Opened 2021-08-11 05:35 UTC by thomas-yanxin

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-11 05:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1190) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1190) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1190) it.</sub>

2021-08-16 12:03 UTC, huan requested changes
Thanks for sharing your experiences with the Paddle + Wechaty event!

Please read the GitHub Actions CI messages and fix testing problems then we can continue reviewing this great PR.

2021-08-24 06:57 UTC, lijiarui commented
@thomas-yanxin  Please sign the CLA first.

Looking forward to your reply.

2021-08-26 09:21 UTC, lijiarui commented
Hi @thomas-yanxin Please 
- Add author info as well.
- Make Github action green.

Thanks

2021-09-01 14:35 UTC, lijiarui commented
ping @thomas-yanxin 

Please always keep working on one PR and keep improving it, instead of closing one and opening another, because we should always keep the conversation and the improvements linked together, which can be achieved by keeping improving one PR.

I think you can commit https://github.com/wechaty/wechaty.js.org/pull/1191  to this PR.

2021-09-07 19:42 UTC, huan requested changes
Please make the CI green before we can continue reviewing this great blog post!

2021-09-07 19:42 UTC, huan commented on jekyll/_posts/2021-08-11-living_bot-paddleXwechaty.md
> +<div class="video-container" style="
Use `{% include iframe.html src="https://www.bilibili.com/video/BV1pf4y1V7G8/" %}` instead.

2021-09-08 17:27 UTC, thomas-yanxin commented
I feel very sorry for some inappropriate operations before, because I just learned about Git related operations, and I am not familiar with it. I'm still learning how to do it. I'm so sorry for that! For the above reasons, can you take a look at this PR #1270.

2021-09-08 17:30 UTC, thomas-yanxin commented
Maybe I push my contributor profile and the blog together into this pr #1270.

2021-09-09 08:35 UTC, huan commented
No problem. Please keep one PR which you are working on, and closed others to help us to be focus. 

Thank you very much.

2021-09-09 08:37 UTC, closed without merging