添加两篇wechaty相关文章
wechaty/docusaurus pull request #120
Opened 2019-04-02 09:11 UTC by gengchen528

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

已经按照要求书写，@huan邀请

2019-04-02 16:15 UTC, huan approved these changes
Thank you very much for sharing your great blog articles to the Chatie community!

2019-04-02 16:15 UTC, huan commented
@lijiarui Please review and help @gengchen528 to merge his PR for publishing, thank you very much!

2019-04-02 22:21 UTC, lijiarui requested changes
请按照我的review 进行修改，之后我会merge 他，感谢！

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
前言内容会被引入到博客中，读者打开博客看到两个相同的段落，所以建议删除其中一个。

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加：```js 表示代码模块

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ``` 结束代码模块

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```js

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```js

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```sh

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```sh

2019-04-02 22:21 UTC, lijiarui commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```js

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```js

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```shell

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +    npm config set puppeteer_download_host https://npm.taobao.org/mirrors
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加```sh

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +    yarn config set puppeteer_download_host https://npm.taobao.org/mirrors
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```sh

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```js

2019-04-02 22:21 UTC, lijiarui commented on _posts/2020-04-02-node-wechaty-spider.md
> +
增加 ```

2019-04-03 01:44 UTC, gengchen528 commented on _posts/2019-04-02-koa-wechaty-assistant.md
> +
好的

2019-04-03 07:48 UTC, lijiarui commented
Thanks！

2019-04-03 07:48 UTC, merged