<x世纪星际终端>基于wechaty的AR+LBS漂流瓶轻社交游戏
wechaty/docusaurus pull request #1217
Opened 2021-08-22 00:20 UTC by kevinfu1717

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-22 06:15 UTC, kevinfu1717 commented
check MD with hint

2021-08-22 08:06 UTC, huan requested changes
Please follow the error messages from CI and fix them as well.

See: https://github.com/wechaty/wechaty.js.org/pull/1217/checks?check_run_id=3392604010#step:8:24

2021-08-22 17:51 UTC, huan requested changes
Please follow https://github.com/wechaty/wechaty.js.org/pull/1217/checks?check_run_id=3394419204#step:8:24 and fix those errors.

The most efficient way to make your post PR turns green is to run the `npm test` locally before push because it will greatly reduce the time that you spend to pass this CI test.

2021-08-24 06:55 UTC, lijiarui commented
The most efficient way to make your post PR turns green is to run the npm test locally before push because it will greatly reduce the time that you spend to pass this CI test.

2021-08-24 11:03 UTC, lijiarui requested changes

2021-08-24 11:03 UTC, lijiarui commented on jekyll/_posts/2021-08-21-super-interstellar-terminal.md
> +  >
You can change to:

```
{% include iframe.html src="https://player.bilibili.com/player.html?bvid=BV1hL411E79M" %}
```

2021-08-24 11:03 UTC, lijiarui commented on jekyll/_posts/2021-08-21-super-interstellar-terminal.md
> +| -------- | -------- | -------- |
It would be better if you change the table to ordered Lists since our blog cannot support table well here.

You will get a preview like this:

![image](https://user-images.githubusercontent.com/6419514/130605693-5e6d9874-b5cf-4132-982a-d3b0409afe7a.png)

2021-08-25 06:19 UTC, lijiarui approved these changes
Good job！

2021-08-25 06:19 UTC, merged

2021-08-25 06:20 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited kevinfu1717 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _ruirui_0914_ and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!