Usage Puppet Providers Mock
wechaty/docusaurus pull request #1220
Opened 2021-08-24 05:54 UTC by Soumi7

Updates Puppet Providers - Mock section in Puppet Providers

References issue #890

Screenshots :

![image](https://user-images.githubusercontent.com/51290447/130563068-d75abb94-e581-46be-80bc-44d18832b329.png)

![image](https://user-images.githubusercontent.com/51290447/130563117-66e2b13a-4d08-4fe7-a000-95a73c7d3a4a.png)

![image](https://user-images.githubusercontent.com/51290447/130563180-10c96056-3d13-43cf-87f8-17f360341b23.png)

![image](https://user-images.githubusercontent.com/51290447/130563232-f112fcec-555d-4f07-8396-b82b2113c476.png)

![image](https://user-images.githubusercontent.com/51290447/130563281-3855d74c-7844-4be4-be35-f4406d446a24.png)

![image](https://user-images.githubusercontent.com/51290447/130563352-c6b6a559-b044-4fe0-90a1-bd24e00e9c00.png)

![image](https://user-images.githubusercontent.com/51290447/130563561-0986f298-6ebd-4a9f-9e20-0fe4b05e6367.png)

![image](https://user-images.githubusercontent.com/51290447/130563605-09f45b41-577a-4b82-943d-8bc2a0a775ed.png)

2021-08-25 03:37 UTC, shraddhavp approved these changes
LGTM

2021-08-27 15:12 UTC, proudofsimin requested changes
Always remember that you should never leave code snippet alone without explanations. Please describe what you are doing in the codes. Examples could see [documents](https://github.com/wechaty/wechaty.js.org/pull/981) from How-to guides team, or from [Javascript](https://javascript.info/date).

2021-08-27 15:12 UTC, proudofsimin commented on docusaurus/docs/puppet-providers/mock.md
> +1. Helps to test Wechaty framework with a mock puppet.
```suggestion
1. Help to test Wechaty framework with a mock puppet.
```
* imperative sentence

2021-08-27 15:12 UTC, proudofsimin commented on docusaurus/docs/puppet-providers/mock.md
Run `wechaty-puppet-mock`.

2021-08-27 15:12 UTC, proudofsimin commented on docusaurus/docs/puppet-providers/mock.md
Please add explanation of the code snippet here.

2021-08-27 15:12 UTC, proudofsimin commented on docusaurus/docs/puppet-providers/mock.md
>  ```
(not sure why I can't insert in between the title "Mocker and environment" and the code snippet) <-Please change the title to this format as well.

Please add explanation of the code snippet.

2021-08-27 16:25 UTC, Soumi7 commented
Updated screenshots :

![image](https://user-images.githubusercontent.com/51290447/131158464-5310b09c-7436-41ee-bdb3-06ee5aab93a8.png)

![image](https://user-images.githubusercontent.com/51290447/131158498-8611957b-46e3-44b9-8577-21a0cf91cc22.png)

![image](https://user-images.githubusercontent.com/51290447/131158781-023531c1-0005-4d24-866a-5082cd4644ff.png)

2021-08-28 16:45 UTC, Soumi7 commented
@proudofsimin No more information other than the titles in mentioned anywhere, hence I think we will have to request the mentors for more info about the code snippets. @shraddhavp  what do you think?

2021-09-02 06:46 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-07 19:47 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-13 08:37 UTC, Rohitesh-Kumar-Jain commented
@proudofsimin I would be glad if you review changes once again : )

2021-09-15 16:00 UTC, Soumi7 commented
@proudofsimin as Huan has already approved this, could you please approve this too? There is nothing more I can add in this.

2021-09-15 17:03 UTC, proudofsimin approved these changes

2021-09-15 17:56 UTC, merged