How to build a chatbot from zero to one on WeChat
wechaty/docusaurus pull request #1221
Opened 2021-08-24 06:38 UTC by gangena

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-24 08:41 UTC, lijiarui requested changes

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +句子互动的创始人，GitHub上开源项目Wechaty上面的联合作者，Wechaty在github上面有超过1万star，并搭建了一个覆盖全球的微信平台开发者社区，微软的 AI MVP，出版书：《Chatbot从0到1》，已经在京东上架，欢迎大家阅读，本次分享里面会简单介绍书中的内容，如何从0到1搭建一个聊天机器人，
Please add link https://item.jd.com/12630213.html for 《Chatbot从0到1》

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +> 作者: [lijiarui](https://github.com/lijiarui/)
Please remove author here.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +句子互动的创始人，GitHub上开源项目Wechaty上面的联合作者，Wechaty在github上面有超过1万star，并搭建了一个覆盖全球的微信平台开发者社区，微软的 AI MVP，出版书：《Chatbot从0到1》，已经在京东上架，欢迎大家阅读，本次分享里面会简单介绍书中的内容，如何从0到1搭建一个聊天机器人，
"句子互动的创始人，GitHub上开源项目Wechaty上面的联合作者，Wechaty在github上面有超过1万star，并搭建了一个覆盖全球的微信平台开发者社区，微软的 AI MVP，出版书：《Chatbot从0到1》，已经在京东上架，欢迎大家阅读，本次分享里面会简单介绍书中的内容，如何从0到1搭建一个聊天机器人，"  This looks like a sick sentence

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +image: /assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/homepage.webp
Please change the teaser to global ai teaser.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +
Please remove the useless line here.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +
Please remove the useless line here.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![lifecycles](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/lifecycles.webp)
Please add a line here. It should have a wrap here.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 在过去，我们公司一直在为企业做chatbot，也和很多企业聊过，他们以为搭建chatbot的方式一定是机器学习做的，这个需要掌握非常强的数学能力，概率论能力，也需要了解所有的相关算法，要有很强的软件能力，很强的工程能力，还要去读大量的论文，了解什么是神经元，最后从入门到放弃。
Please remove `-` here.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 下面主要围绕微软的luis来讲怎样去搭建一个多轮的对话系统，我刚刚给大家介绍的chatbot从0到1，理论也是非常相似的，把搭建chatbot拆分成了8大生命周期，其实搭建一个chatbot和过去我们搭建一个网站或者app有很多相似的地方，但也有一些不一样的地方，某些东西我们是可以拿来借鉴直接使用的，有些东西也是chatbot独有的，如今我们不会再去说搭建一个应用技术，其实还有许多其他的产品
Please remove `-` here.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 需求分析
Please change to `#### 1. 需求分析` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 流程设计
Please change to `#### 2. 流程设计` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 数据处理
Please change to `#### 3. 数据处理` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 对话脚本撰写
Please change to `#### 4. 对话脚本撰写` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 对话系统搭建
Please change to `#### 5. 对话系统搭建` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 对话任务测评
Please change to `#### 6. 对话任务测评` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 平台渠道集成
Please change to `#### 7. 平台渠道集成` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 运营反馈
Please change to `#### 8. 运营反馈` here

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![wechaty](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/wechaty.webp)
It looks strange you put an image in the middle of a sentence.

Please add the image in a new line.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +在GitHub上面已经有8k的star，是一个基于微信个人号的WeChat RPA框架，能够帮助你去搭建你的微信机器人，开发者遍布全球，美国欧洲澳洲，
8k--> 11k

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![global](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/global.webp)
It looks strange you put an image in the middle of a sentence.

Please add the image in a new line.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![luis](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/luis.webp)
It looks strange you put an image in the middle of a sentence.

Please add the image in a new line.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 任务1：发布LUIS版本
change to `### 任务1：发布LUIS版本`

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 任务2 - 将LUIS RESTFUL API 接入wechaty
change to `### 任务2： 将LUIS RESTFUL API 接入wechaty`

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 任务3：运行代码
change to `### 任务3：运行代码`

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +- 任务4：运行代码
change to `### 任务4：运行代码`

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![sand](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/sand.webp)
It looks strange you put an image in the middle of a sentence.

Please add the image in a new line.

2021-08-24 08:41 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +![welcome](/assets/2020/04-how-to-build-a-chatbot-from-zero-to-one-on-wechaty/welcome.webp)
It looks strange you put an image in the middle of a sentence.

Please add the image in a new line.

2021-08-24 08:58 UTC, lijiarui requested changes

2021-08-24 08:58 UTC, lijiarui commented on jekyll/_posts/2020-04-09-how-to-build-a-chatbot-from-zero-to-one-on-wechaty.md
> +  - talk
Please add `microsoft tag here.

2021-09-01 14:35 UTC, lijiarui commented
@gangena Please make GitHub action green.

2022-03-30 11:56 UTC, huan commented
Merge for preparing 

- #1501

2022-03-30 11:56 UTC, merged