Mid Term blog of OSPP 2021: Wechaty Piggy Bro
wechaty/docusaurus pull request #1226
Opened 2021-08-26 05:47 UTC by ReiKohaku

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  
- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

2021-08-26 08:33 UTC, lijiarui requested changes
Please get your mentor approve first.

2021-08-26 08:33 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-piggy-bro.md
> +> Author: [@ReiKohaku](https://github.com/ReiKohaku)
Please remove Author's description here.

2021-08-28 01:18 UTC, ReiKohaku commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-piggy-bro.md
> +> Author: [@ReiKohaku](https://github.com/ReiKohaku)
I removed this line in 5a0463a

2021-08-28 11:03 UTC, Valerieeeee approved these changes
LGTM

2021-08-28 12:49 UTC, ninetailskim approved these changes
LGTM

2021-08-29 03:06 UTC, merged