OSPP 2021: mid-term report of wechaty-cli
wechaty/docusaurus pull request #1228
Opened 2021-08-26 11:52 UTC by chinggg

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-29 03:05 UTC, lijiarui approved these changes
LGTM!

Please get your mentor's approvement then I will merge this PR.

2021-09-07 07:40 UTC, huan approved these changes
LGTM

Thank you very much for sharing the CLI project for the community!

2021-09-07 17:14 UTC, lijiarui requested changes

2021-09-07 17:14 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-cli.md
> +
Please add Chinese version video as https://github.com/wechaty/summer/issues/80#issuecomment-914480564 request, and add it to the blog: 


```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-07 17:14 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-cli.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=1U0ONeHV7z8" %}
Please add Chinese version video as https://github.com/wechaty/summer/issues/80#issuecomment-914480564 request, and add it to the blog: 


```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-08 15:42 UTC, chinggg commented on jekyll/_posts/2021-08-26-ospp-mid-term-cli.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=1U0ONeHV7z8" %}
Will add Chinese version video tomorrow

2021-09-09 07:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1228) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: huan<br/>:white_check_mark: chinggg<br/>:x: liu.jing<br/><hr/>**liu.jing** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1228) it.</sub>

2021-09-18 06:46 UTC, lijiarui commented
@chinggg Please make GitHub action green.

2021-09-18 06:49 UTC, chinggg commented
> Please add Chinese version video as wechaty/summer#80 (comment) request, and add it to the blog:

> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
@lijiarui The style of bare url is not allowed by the CI rule.

2021-09-18 08:59 UTC, lijiarui commented
@chinggg You can follow other students did: https://github.com/wechaty/wechaty.js.org/pull/1236/files

2021-09-18 09:56 UTC, huan commented
Link to https://github.com/wechaty/summer/issues/80

2021-09-18 10:22 UTC, lijiarui approved these changes
LGTM!

2021-09-18 10:22 UTC, merged