about me #251
wechaty/docusaurus pull request #1229
Opened 2021-08-28 05:58 UTC by jiaqianjing

2021-08-28 06:19 UTC, lijiarui requested changes

2021-08-28 06:19 UTC, lijiarui commented on jekyll/_contributors/jiaqianjing.md
> +仙友你好!
Please link your PR content here, thanks!

2021-08-28 06:28 UTC, jiaqianjing commented on jekyll/_contributors/jiaqianjing.md
> +仙友你好!
ok

2021-08-28 16:53 UTC, lijiarui commented
Please make github adction green.

2021-08-28 16:56 UTC, lijiarui commented
Btw, please accept the invitation as  https://github.com/wechaty/python-wechaty/pull/251 requested, then Github action will run automatically for you.

2021-08-30 05:49 UTC, lijiarui commented
@jiaqianjing 

Please accept the invitation as  https://github.com/wechaty/python-wechaty/pull/251#issuecomment-907056950 requested, then Github action will run automatically for you.

> You'are invited jiaqianjing to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

2021-08-30 06:08 UTC, jiaqianjing commented
> > You'are invited jiaqianjing to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

Please tell me what I have not finished.

2021-08-30 07:48 UTC, lijiarui commented
Please visit https://github.com/wechaty to accept the invitation.

2021-08-30 07:49 UTC, lijiarui approved these changes

2021-08-30 07:56 UTC, jiaqianjing commented
> Please visit https://github.com/wechaty to accept the invitation.

Done

2021-08-30 07:56 UTC, merged