Add contributor profile for pig208.
wechaty/docusaurus pull request #1230
Opened 2021-08-28 15:40 UTC by PIG208

This is a follow-up for the merged PR wechaty@python-wechaty#253.

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-28 16:44 UTC, lijiarui commented
Hi @PIG208 thanks for adding the profile, please:

1. make Github action green
2. add more info on the profile page
3. add your PR content to the profile page

2021-08-29 15:31 UTC, lijiarui requested changes

2021-08-29 15:31 UTC, lijiarui commented on jekyll/_contributors/pig208.md
> +
Please add your PR link here.

2021-08-29 15:35 UTC, PIG208 commented on jekyll/_contributors/pig208.md
> +
Updated accordingly.

2021-08-29 16:11 UTC, lijiarui requested changes

2021-08-29 16:11 UTC, lijiarui commented on jekyll/_contributors/pig208.md
> +
[为python-wechaty贡献代码](https://github.com/wechaty/python-wechaty/pull/253) --->

为python-wechaty贡献代码, 贡献内容:
- [Implement mention_text, contact-bot, and improve typing configuration](https://github.com/wechaty/python-wechaty/pull/253)。

2021-08-29 17:40 UTC, lijiarui commented
Please make Github action green, thanks!

2021-08-30 08:20 UTC, PIG208 commented
Sorry for the delay, I was on a flight. This PR should be all-set now.

2021-08-30 08:46 UTC, merged