initial OSPP 2021 Mid-Term Itchat Puppet
wechaty/docusaurus pull request #1234
Opened 2021-08-30 01:42 UTC by lyleshaw

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-30 02:11 UTC, lyleshaw commented
If it is convenient, I would like to ask you to check if there are any problems with my mid-term report
@wj-Mcat

2021-09-01 01:48 UTC, wj-Mcat approved these changes
LGTM

2021-09-01 14:14 UTC, lijiarui requested changes
It would be better if you add a Chinese link as well! Thanks!

2021-09-01 14:14 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +{% include iframe.html src="https://youtu.be/hce3c4WZylo" %}
Please add Chinese version as well：

```
> 国内链接：https://www.bilibili.com/video/BV1Ef4y1G7hE/
```

2021-09-01 14:14 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +{% include iframe.html src="https://youtu.be/gjg1EW30pOw" %}
Please add Chinese version as well：

```
> 国内链接：https://www.bilibili.com/video/BV15P4y1p7JN/
```

2021-09-02 14:53 UTC, lyleshaw commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +{% include iframe.html src="https://youtu.be/gjg1EW30pOw" %}
@lijiarui Done~

2021-09-03 03:47 UTC, lijiarui requested changes

2021-09-03 03:47 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +{% include iframe.html src="https://github.com/wechaty/summer/files/7072385/itchat.pdf" %}
Please localize this file in wechaty.js.org repo.

2021-09-03 03:47 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/lyleshaw/python-wechaty-puppet-itchat>
I think we should move this to https://github.com/wechaty/python-wechaty-puppet-itchat

How do you think of this and how do you think of the repo name? @wj-Mcat @huan

2021-09-05 18:08 UTC, huan commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/lyleshaw/python-wechaty-puppet-itchat>
For repos from summer 2021, if one has passed the midterm check, and the quality is good (confirmed by the mentor and org admin), then we should accept the project to the wechaty org on GitHub. 

@wj-Mcat do you think this repo is good for transferring? If so, we should get it done.

2021-09-07 02:13 UTC, wj-Mcat commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/lyleshaw/python-wechaty-puppet-itchat>
If it has passed the CICD testing, I think it's good for transfering.

There should exist strict CICD testing in wechaty project, so does python-wechaty-puppet-itchat, I believe @lyleshaw can do it as soon as possible.

2021-09-07 06:16 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/lyleshaw/python-wechaty-puppet-itchat>
Good, @wj-Mcat  please help @lyleshaw  move https://github.com/lyleshaw/python-wechaty-puppet-itchat to https://github.com/wechaty/python-wechaty-puppet-itchat , then change the blog repo name, and I will merge this PR.

2021-09-18 09:12 UTC, lijiarui commented
ping @lyleshaw

2021-09-18 12:21 UTC, wj-Mcat commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/lyleshaw/python-wechaty-puppet-itchat>
I have maintained some communications with @lyleshaw these days, and have fixed the core problem in [`python-wechaty-puppet-itchat`](https://github.com/lyleshaw/python-wechaty-puppet-itchat). I believe it will have a great progress in next few days. Do you think so? @lyleshaw 

I suggest that we can merge the blog first, and I will help @lyleshaw  transfer the `python-wechaty-puppet-itchat` repo to `wechaty` community. @huan @lijiarui  How do you think about ?

2021-09-18 13:33 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/lyleshaw/python-wechaty-puppet-itchat>
I suggest change the blog repo name first, because, in the future, developers read this blog, the blog can give a correct link.

BTW, I think transfer the repo is just a 1 minutes work, it should not be blocked in such a long time.

2021-09-19 15:53 UTC, lijiarui commented
ping @wj-Mcat

2021-09-20 09:43 UTC, lyleshaw commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +{% include iframe.html src="https://github.com/wechaty/summer/files/7072385/itchat.pdf" %}
Done

2021-09-20 09:48 UTC, lyleshaw commented
> ping @lyleshaw

@lijiarui 

Thanks to the help of @wj-Mcat , I solved a big problem and transferred the ownership to Wechaty.
Please check this PR again when you have time.
Waiting for your reply~

2021-09-21 03:55 UTC, huan requested changes
Please compress your PDF from 18MB to less than 3MB by using some service like https://www.ilovepdf.com/compress_pdf

2021-09-21 03:58 UTC, lyleshaw commented
> Please compress your PDF from 18MB to less than 3MB by using some service like https://www.ilovepdf.com/compress_pdf

Done

2021-09-21 09:34 UTC, lijiarui requested changes

2021-09-21 09:34 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +  - project
Please add `ospp` category as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ requested.

2021-09-21 09:37 UTC, lyleshaw commented on jekyll/_posts/2021-08-29-ospp-mid-term-wechaty-itchat-puppet.md
> +  - project
Done

2021-09-21 09:53 UTC, lijiarui approved these changes
LGTM! Cheers!

2021-09-21 09:53 UTC, merged