Mid Term blog of OSPP 2021: Wechaty Puppet Official Account
wechaty/docusaurus pull request #1235
Opened 2021-08-30 11:39 UTC by zzzyer

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-30 16:11 UTC, lijiarui commented
Please get your mentors approval first.

2021-09-01 01:48 UTC, wj-Mcat approved these changes
LGTM

2021-09-01 14:08 UTC, lijiarui requested changes

2021-09-01 14:08 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +  - midterm
Please change the tag to `mid-term` as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ requsted.

2021-09-01 14:08 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +{% include iframe.html src="../assets/2021/08-ospp-mid-term-wechaty-puppet-oa/wechaty-puppet-oa-midterm-ppt.pdf" %}
Please remove `..` here，or the pdf cannot shown in the blog.

2021-09-02 02:26 UTC, zzzyer commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +  - midterm
I have fixed it.

2021-09-02 09:16 UTC, lijiarui requested changes

2021-09-02 09:16 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +项目仓库: <https://github.com/zzzyer/wechaty-puppet-official-account>
Maybe we should change to https://github.com/wechaty/wechaty-puppet-official-account , since we should merge the two project into one.

@wj-Mcat How do you think about this?

2021-09-05 17:30 UTC, lijiarui requested changes
Good job！

Please change as I request, then I will merge this PR.

2021-09-05 17:30 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +{% include iframe.html src="https://youtu.be/acEAgTdApQc" %}
Please add Chinese version as well：

```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-05 17:30 UTC, lijiarui commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +{% include iframe.html src="https://youtu.be/iazpyB54PwU" %}
Please add Chinese version as well：

```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-10 06:43 UTC, huan commented on jekyll/_posts/2021-08-26-ospp-mid-term-wechaty-puppet-oa.md
> +{% include iframe.html src="https://www.bilibili.com/video/BV1zv411w7w6/" %}
We do not need to embed the backup video link.

You can just put the backup video link like the following:

```md
> Bilibili link: <https://www.bilibili.com/video/BV1zv411w7w6/>
```

2021-09-17 13:15 UTC, lijiarui commented
ping @zzzyer

2021-09-19 10:20 UTC, zzzyer commented
> 
> 
> ping @zzzyer

2021-09-19 10:20 UTC, zzzyer commented
@lijiarui 
I have fixed my blog.

2021-09-19 15:51 UTC, lijiarui approved these changes
LGTM

2021-09-19 15:51 UTC, merged