Ospp interim report matrix appservice wechaty
wechaty/docusaurus pull request #1236
Opened 2021-08-30 12:23 UTC by lprintf

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-30 15:51 UTC, lprintf commented
https://github.com/wechaty/summer/issues/59 @lijiarui

2021-08-30 16:08 UTC, lijiarui requested changes

2021-08-30 16:08 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +title: "OSPP 2021-中初报告-基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善"
中初报告 --> 期中报告

2021-08-30 16:08 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +  - matrix
Please add `mid-term` tag here.

2021-08-30 16:08 UTC, lijiarui commented
@lprintf Please get your mentor approvement first.

2021-08-30 22:54 UTC, lprintf commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +title: "OSPP 2021-中初报告-基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善"
@huan

2021-09-01 01:35 UTC, lprintf commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +title: "OSPP 2021-中初报告-基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善"
Oh, sorry, I didn’t notice the change request before.

2021-09-07 07:42 UTC, huan approved these changes
LGTM

Thank you for sharing the matrix project with the community!

And it would be great if you can use YouTube video-sharing service next time.

2021-09-07 17:09 UTC, lijiarui requested changes

2021-09-07 17:09 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +---
Please change the file name to `2021-XX-XX-ospp-mid-term-XX` as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ requested.

2021-09-07 17:09 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +  - 设计实现一套可以[快速部署Matrix和Matrix-Wechaty的方案](https://github.com/lprintf/easy-matrix-wechaty)，并发布到github上
@huan I think maybe it should moved to wechaty org: https://github.com/wechaty/easy-matrix-wechaty

2021-09-07 17:09 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +{% include iframe.html src="https://www.bilibili.com/video/BV12A411c7Nz/" %}
Please change to the youtube video and also add bibili video like this: 

```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-07 17:09 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-interim-report-matrix-wechaty.md
> +
Please change to the youtube video and also add bibili video like this: 

```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-17 12:41 UTC, lprintf reviewed
@lijiarui Please review it. Thank you!

2021-09-17 13:14 UTC, lijiarui requested changes

2021-09-17 13:14 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-matrix-wechaty.md
> +{% include iframe.html src="/assets/2021/08-ospp-interim-report-matrix-wechaty/report-ppt.pdf" %}
Please change to  `08-ospp-mid-term-matrix-wechaty` here, or it may cause a pdf break in the blog.

2021-09-17 14:08 UTC, lprintf commented on jekyll/_posts/2021-08-30-ospp-mid-term-matrix-wechaty.md
> +{% include iframe.html src="/assets/2021/08-ospp-interim-report-matrix-wechaty/report-ppt.pdf" %}
!!! I'm sorry for making this mistake.

2021-09-18 09:20 UTC, lijiarui approved these changes
LGTM！

2021-09-18 09:20 UTC, merged