submit mid term 5g chatbot
wechaty/docusaurus pull request #1237
Opened 2021-08-30 13:34 UTC by zrn-fight

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-30 16:11 UTC, lijiarui requested changes
Please follow this guide here: https://wechaty.js.org/2021/06/24/summer-wechaty-guide/

2021-08-30 16:11 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-5g-chatbot-puppet.md
> +title: "Mid Term blog of OSPP 2021: 5gChatbot"
Please change the title to `OSPP 2021-期中报告-你的标题`

2021-08-30 16:11 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-5g-chatbot-puppet.md
> +  - plan
Please add `mid-term` tag here.

2021-08-30 16:11 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-5g-chatbot-puppet.md
> +{% include iframe.html src="https://maiimg.com/free/?e=dwYyE0y.U6nYo6" %}
Please upload your ppt instead of using an online version.

2021-08-31 07:49 UTC, lijiarui requested changes

2021-08-31 07:49 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-5g-chatbot-puppet.md
> +- 项目介绍：[https://github.com/wechaty/summer/issues/74]
Please change to <https://github.com/wechaty/summer/issues/74> Or it could not be clicked.

2021-08-31 07:49 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-5g-chatbot-puppet.md
> +- 项目链接：[https://github.com/wechaty/summer/issues/74]
Please change to <https://github.com/wechaty/summer/issues/74> Or it could not be clicked.

2021-08-31 07:49 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-5g-chatbot-puppet.md
> +{% include iframe.html src="../assets/2021/08-ospp-mid-term-5g-chatbot-puppet/5g-chatbot-ppt.pdf" %}
Please remove `..` here, or we cannot view the pdf in the blog.

2021-08-31 10:31 UTC, zrn-fight commented
Thank you for your suggestions. I have made some changes. Could you please check it again?

2021-08-31 10:32 UTC, zrn-fight commented
Thank you for your suggestions. I have made some changes. Could you please check it again?
@lijiarui

2021-08-31 10:53 UTC, lijiarui approved these changes
LGTM

2021-08-31 10:54 UTC, merged