midreport
wechaty/docusaurus pull request #1241
Opened 2021-08-31 08:26 UTC by remember00000

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-08-31 08:40 UTC, lijiarui commented
Thanks for the post, please:

1. Make Github action green
2. Get your mentor's approval

2021-09-18 09:07 UTC, lijiarui commented
@remember00000 Please get your mentors approval ASAP.

2021-09-21 07:13 UTC, Roxanne718 approved these changes
LGTM

2021-09-21 09:18 UTC, lijiarui requested changes
Please change the file name to `2021-XX-XX-ospp-mid-term-XX` as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ requested.

2021-09-21 09:22 UTC, lijiarui requested changes

2021-09-21 09:22 UTC, lijiarui commented on jekyll/_posts/2021-08-30-wechaty-larkpuppet-ospp-mid-term-blog.md
> +> Author: [@remember00000](https://github.com/remember00000)
Please remove `> Author: [@remember00000](https://github.com/remember00000)` here, since you already put name at the head of the blog.

2021-09-21 09:22 UTC, lijiarui commented on jekyll/_posts/2021-08-30-wechaty-larkpuppet-ospp-mid-term-blog.md
> +> Code: [wechaty-puppet-lark](https://github.com/remember00000/wechaty-puppet-lark)
Please change `remember00000` to `wechaty`

2021-09-21 09:22 UTC, lijiarui commented on jekyll/_posts/2021-08-30-wechaty-larkpuppet-ospp-mid-term-blog.md
> +项目仓库: [https://github.com/remember00000/wechaty-puppet-lark](https://github.com/remember00000/wechaty-puppet-lark)
Please change remember00000 to wechaty official repo.

2021-09-21 09:22 UTC, lijiarui commented on jekyll/_posts/2021-08-30-wechaty-larkpuppet-ospp-mid-term-blog.md
> +{% include iframe.html src="https://youtu.be/fAIZS9lgxjo" %}
Please add Chinese video like this: 

```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-21 09:22 UTC, lijiarui commented on jekyll/_posts/2021-08-30-wechaty-larkpuppet-ospp-mid-term-blog.md
> +{% include iframe.html src="https://youtu.be/IwMA8VJZZqE" %}
Please add Chinese video like this: 

```
> 国内链接：https://www.bilibili.com/XXXXXXXXXXXXXXXXXXXXXXX
```

2021-09-21 09:22 UTC, lijiarui commented on jekyll/_posts/2021-08-30-wechaty-larkpuppet-ospp-mid-term-blog.md
> +- 项目链接：[https://github.com/remember00000/wechaty-puppet-lark](https://github.com/remember00000/wechaty-puppet-lark)
Please change remember00000 to wechaty

2021-09-21 12:05 UTC, lijiarui requested changes
Please pay more attention to the details and following https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ requested.

2021-09-21 12:05 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-wechaty-puppet-lark.md
> +项目仓库: [https://github.com/remember00000/wechaty-puppet-lark](https://github.com/wechaty/wechaty-puppet-lark)
Please change remember00000 to wechaty ...

2021-09-21 12:05 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-wechaty-puppet-lark.md
> +{% include iframe.html src="https://youtu.be/IwMA8VJZZqE" %}
Where is the Chinese version video?

2021-09-21 12:05 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-wechaty-puppet-lark.md
> +- 项目链接：[https://github.com/remember00000/wechaty-puppet-lark](https://github.com/remember00000/wechaty-puppet-lark)
Please change remember00000 to wechaty

2021-09-21 15:10 UTC, lijiarui requested changes
Please be careful with all of the details...

2021-09-21 15:10 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-wechaty-puppet-lark.md
> +本项目 [项目名称] 系 暑期2021 支持的开源项目。
Please add your project name instead of put `[项目名称]` here.

2021-09-21 15:10 UTC, lijiarui commented on jekyll/_posts/2021-08-30-ospp-mid-term-wechaty-puppet-lark.md
> +{% include iframe.html src="/assets/2021/08-wechaty-larkpuppet-ospp-mid-term-blog/mid-term-ppt.pdf" %}
Your pdf path is wrong, so we cannot preview your pdf. Please check the path and modify it to the correct version.

2021-09-21 16:21 UTC, lijiarui approved these changes

2021-09-21 16:21 UTC, merged