OSPP 2021-期中报告-开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块
wechaty/docusaurus pull request #1242
Opened 2021-08-31 12:44 UTC by anaivebird

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-09-01 14:04 UTC, lijiarui requested changes

2021-09-01 14:04 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +  - plan
Please remove plan tag here, because this is a mid-term blog.

2021-09-01 14:04 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +        开始正式进行代码的prototyping，先完成基础的功能，完成通过 Wechaty 加载 wechaty-puppet-5g-qq 模块，并通过oicq项目实现的qq协议，实现文本消息的收发功能。每周协同导师进行功能的开发和完善
What is `wechaty-puppet-5g-qq` here ?

2021-09-01 14:04 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +        将CI（持续集成）的测试跑通，如果时间充足，可以尝试完成一下配置 GitHub Actions 实现自动化测试的任务。
Please add more message types instead of adding CI and GitHub actions here.

2021-09-01 14:10 UTC, lijiarui requested changes

2021-09-01 14:10 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +    通过途径弄到了一些QQ小号方便测试。
Please add the following as requested: https://wechaty.js.org/2021/06/24/summer-wechaty-guide/

```
### live coding视频:
 
{% include iframe.html src="视频链接" %}

### PPT展示视频:

{% include iframe.html src="视频链接" %}

### 项目PPT:

{% include iframe.html src="pdf链接" %}
```

2021-09-02 07:10 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +        开始正式进行代码的prototyping，先完成基础的功能，完成通过 Wechaty 加载 wechaty-puppet-5g-qq 模块，并通过oicq项目实现的qq协议，实现文本消息的收发功能。每周协同导师进行功能的开发和完善
fixed

2021-09-02 09:58 UTC, lijiarui requested changes
Please follow the blog template as request: https://github.com/wechaty/summer/issues/79#issuecomment-899086777

2021-09-02 09:58 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +  - other
Please add `puppet` and `qq` tag for this blog

2021-09-02 09:58 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +{% include iframe.html src="https://youtu.be/FY4U2JPZjxE" %}
Please add the Chinese version here：

```
> 国内版： http://www.iqiyi.com/v_gqyz7g94fw.html
```

2021-09-02 09:58 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Please add the Chinese version here：

```
> 国内版： http://www.iqiyi.com/v_1ixjchyr7yw.html
```

2021-09-02 09:58 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +        开始正式进行代码的prototyping，先完成基础的功能，完成通过 Wechaty 加载 wechaty-puppet-oicq 模块，并通过oicq项目实现的qq协议，实现文本消息的收发功能。每周协同导师进行功能的开发和完善
![image](https://user-images.githubusercontent.com/6419514/131823531-096c72f5-28c4-48fe-a45e-94225ea54f20.png)

It looks strange when I preview the blog. Please remove the useless blank here as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ request

2021-09-02 09:58 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +    按照原计划继续进行，并且尽可能对图片消息、语音消息等增加支持，使wechaty-puppet-oicq成为事件和API支持非常详细的机器人协议提供端。",
![image](https://user-images.githubusercontent.com/6419514/131823774-2e8988d8-829d-40ac-8a02-a239543997ca.png)


It looks strange when I preview the blog. Please remove the useless blank here as https://wechaty.js.org/2021/06/24/summer-wechaty-guide/ request

2021-09-02 09:58 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Please add the following information as well

```
## 项目成果

项目仓库: <https://github.com/XX/XX>  
```

2021-09-18 09:06 UTC, lijiarui commented
ping @anaivebird

2021-09-18 10:50 UTC, lijiarui requested changes

2021-09-18 10:50 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +>
Please add youtube link as this:  `{% include iframe.html src="视频链接" %}` 

Since the blog should preview the video.

2021-09-18 10:50 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +> 国际版： <https://youtu.be/pT16CnFhTPQ>
Please add youtube link as this:  `{% include iframe.html src="视频链接" %}` 

Since the blog should preview the video.

2021-09-18 10:50 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/anaivebird/wechaty-puppet-oicq>
Please remove this repo to wechaty official org.

2021-09-18 11:00 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/anaivebird/wechaty-puppet-oicq>
So just remove it now, since moving to  wechaty official org is not finished yet?

2021-09-18 11:06 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/anaivebird/wechaty-puppet-oicq>
move to wechaty official org, sorry for the typo.

2021-09-18 11:06 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/anaivebird/wechaty-puppet-oicq>
Please change to https://github.com/wechaty/wechaty-puppet-oicq here.

2021-09-18 11:11 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/anaivebird/wechaty-puppet-oicq>
changed to https://github.com/wechaty/wechaty-puppet-oicq

2021-09-18 17:48 UTC, lijiarui requested changes

2021-09-18 17:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +    按照原计划继续进行，并且尽可能对图片消息、语音消息等增加支持，使wechaty-puppet-oicq成为事件和API支持非常详细的机器人协议提供端。",
Please change all of the strange preview styles.

2021-09-18 17:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Please change all of the strange preview styles. You can follow other students' markdown style, it will make the blog easy to read.

![image](https://user-images.githubusercontent.com/6419514/133897742-61be8722-1b9a-41c4-93a5-01eaa52369f9.png)

2021-09-18 17:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Please add the missing part for the blog:

## [项目名称]信息

- 导师：[导师名称]  
- 学生：[学生名称]  
- 项目介绍：[Github Issue 链接，如 https://github.com/wechaty/summer/issues/74]  

## 项目成果

项目仓库: <https://github.com/XX/XX>

2021-09-19 03:52 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Sorry, 后续工作安排's style is neglected by me, but other styles has been changed yesterday. In order to preview these styles, I spent considerable time to install ruby 2.4 and Jekyll in my CentOS 7 server.

To prevent invalid pull requests again and again, I will send the rendered version into QQ group for check.

2021-09-19 03:56 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
added

2021-09-19 04:00 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
For block styling, it is referring to https://wechaty.js.org/2021/08/26/ospp-mid-term-wechaty-piggy-bro/, and spacing between title and block seem impossible to eliminate.
## my styling
![image](https://user-images.githubusercontent.com/29398611/133914955-bdc1a2ac-8fb3-4fdf-b5fe-7afc45829278.png)

## the styling I'm [refering to](https://wechaty.js.org/2021/08/26/ospp-mid-term-wechaty-piggy-bro/)
![image](https://user-images.githubusercontent.com/29398611/133914950-031da9c1-565d-4799-b83c-e4bc2e4d9b60.png)

2021-09-19 15:48 UTC, lijiarui requested changes
You should change as request, don't resolve the conversation unless you **really** resolve the problem I request.

And, please keep discussing the blog only on GitHub instead of in WeChat Group.

2021-09-19 15:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
@anaivebird you have added repo but you didn't added the following information: 

```
## [项目名称]信息

- 导师：[导师名称]  
- 学生：[学生名称]  
- 项目介绍：[Github Issue 链接，如 https://github.com/wechaty/summer/issues/74]  
```

And, you should move https://github.com/anaivebird/wechaty-puppet-oicq to https://github.com/wechaty/wechaty-puppet-oicq Then change the repo name in the blog.

2021-09-19 15:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Please keep discussing on GitHub, thanks.

And you should keep improving on this PR.

2021-09-19 15:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +>
You didn't change as request, so pls don't resolve the conversation.

2021-09-19 15:48 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +> 国际版： <https://youtu.be/pT16CnFhTPQ>
You didn't change as request, so pls don't resolve the conversation.

2021-09-21 03:46 UTC, huan commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的
Please add 1-2 paragraphs for introducing the wechaty-puppet-oicq project at the beginning of this blog post, because the first sentence will be used as the brief of thforis post, and it should be introducing our project instead of the ospp2021.

The introduction of the OSPP2021 can be moved at the end of this post.


Thank you very much.

2021-09-21 03:48 UTC, huan requested changes

2021-09-21 03:48 UTC, huan commented on package.json
> +  "version": "0.9.15",
This version change is an unrelated change and it is TERRIBLE because you are downgrading the version, which will cause lots of problems.

Please be careful when submitting a PR to our system.

2021-09-21 03:55 UTC, anaivebird commented on package.json
> +  "version": "0.9.15",
I find committing everytime will automatically add version number locally, which will make the version I upload several version ahead of the master of this repo. Any suggestion on it?

2021-09-21 09:27 UTC, lijiarui requested changes

2021-09-21 09:27 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +{% include iframe.html src="https://youtu.be/FY4U2JPZjxE" %}
Please add a Chinese version as I request: 

```
> 国内版：http://www.iqiyi.com/v_gqyz7g94fw.html

If you use the `{%include iframe.html` tag, it will preview the video, which is not as expected. We should just add a Chinese version link instead of a preview of the Chinese version video.

2021-09-21 09:27 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +
Please add a Chinese version as I request: 

```
> 国内版：http://www.iqiyi.com/v_1ixjchyr7yw.html
```

If you use the `{%include iframe.html` tag, it will preview the video, which is not as expected. We should just add a Chinese version link instead of a preview of the Chinese version video.

2021-09-21 12:28 UTC, lijiarui requested changes

2021-09-21 12:28 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +希望可以实现对 QQ Chatbot 的支持。通过 Wechaty Puppet 的接口，可以将 QQ 进行 RPA 封装，使其成为 wechaty-puppet-qq 供 Wechaty 开发者方便接入 QQ 平台，使其成
wechaty-puppet-qq ---> wechaty-puppet-oicq

2021-09-21 12:28 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +本项目通过 Wechaty Puppet 的接口，可以将 QQ 进行 RPA 封装，使其成为 wechaty-puppet-qq 供 Wechaty 开发者方便接入 QQ 平台，使其成为 Wechaty 可以使用的社区生态模块。
wechaty-puppet-qq ---> wechaty-puppet-oicq

2021-09-21 12:28 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-oicq>
Please move https://github.com/anaivebird/wechaty-puppet-oicq to wechaty official org first. 

Now, https://github.com/wechaty/wechaty-puppet-oicq is a deadlink.

2021-09-21 12:28 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +- 导师：李佳芮: Wechaty co-creator, Founder & CEO of Juzi.BOT (rui@chatie.io)
Please add @huan as a mentor as well.

2021-09-21 12:41 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-oicq>
It need to make puppet support ESM mode first which takes several days.

2021-09-21 12:45 UTC, huan commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-oicq>
It's OK to move the project to wechaty org first, then make it to support ESM second.

2021-09-21 12:49 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-oicq>
Any document for moving repo to Wechaty official?

2021-09-21 15:30 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-oicq>
You can google for it: [github transfer ownership](https://www.google.com/search?q=github+transfer+ownership&oq=github+transfer&aqs=chrome.1.69i57j0i512l9.8989j0j1&sourceid=chrome&ie=UTF-8)

2021-09-22 07:51 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-oicq>
Has moved to https://github.com/wechaty/wechaty-puppet-oicq

2021-09-22 08:13 UTC, huan commented on package.json
> +  "version": "0.9.15",
Just pay attention for your changes: it's never right to change the version v0.10 to v0.9

2021-09-22 08:15 UTC, huan approved these changes
LGTM

Thank you very much for following the reviews and keeping improving the PR!

2021-09-23 05:18 UTC, lijiarui requested changes

2021-09-23 05:18 UTC, lijiarui commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +    通过咨询项目导师和wechaty飞书机器人负责人等途径，观看社区livecoding视频，对消息处理进行快速学习，并通过编码实践，最终成功将oicq的事件和消息格式转换为了wechaty的messageRawPay，也加深了对框架架构设计的理解。
messageRawPay or messageRawPayload?

2021-09-23 05:28 UTC, anaivebird commented on jekyll/_posts/2021-08-31-ospp-mid-term-qq-puppet.md
> +    通过咨询项目导师和wechaty飞书机器人负责人等途径，观看社区livecoding视频，对消息处理进行快速学习，并通过编码实践，最终成功将oicq的事件和消息格式转换为了wechaty的messageRawPay，也加深了对框架架构设计的理解。
Sorry, it's a typo.

2021-09-23 05:32 UTC, lijiarui approved these changes
LGTM

2021-09-23 05:32 UTC, merged