First Section of the Wechaty landing page
wechaty/docusaurus pull request #1258
Opened 2021-09-07 19:42 UTC by encodeArnab

Issue Number ( #912 )
This commit comprises of an atomic PR of first section (Hero Section with CSS and Images) for the Wechaty landing page. Its a test PR for review.

Images of hero section running locally

(Desktop Version)
<img width="1440" alt="HeroSection" src="https://user-images.githubusercontent.com/77114532/132401195-e9f95c03-eed8-4eab-8c16-862b7767e849.png">

(Mobile Version)
<img width="347" alt="HeroSectionMobile" src="https://user-images.githubusercontent.com/77114532/132401183-72e793f7-73f1-4b6b-8ac2-91375dfbf3d5.png">

2021-09-07 19:52 UTC, encodeArnab commented
Hello @Huan, 
I adjusted the PR as advised, and it now only contains the first section, as well as the CSS and images that go with it. 
We attempted to make CSS inline with the content (in a single file), but CSS has over 200 lines of code (just for the first part), making the code a bit messy, so we separated it in another file for the reviewers' convenience.

2021-09-07 20:06 UTC, huan requested changes
Thanks for creating this react component to make this PR clear!

I have the following comments:

1. please create a directory `docusaurus/src/pages/header-section/`, and put all the files (.css, .png, .jsx) of `HeaderSection` component inside it, to make it well encapsulated.
2. please rename `headerSection.jsx` to `header-section.tsx`, to follow two rules: 1) all file names are in lowercase, with `-` separated, and 2) we should always use TypeScript.
3. rename `heroChatbotImage.png` to `header-section/hero-chatbot-image.png`, and so on.

Please follow the above comments and then we can continue to review this great PR.

2021-09-08 07:33 UTC, encodeArnab commented
Hello @huan ,
Thank you for your comments. 
I've made the necessary modifications; please evaluate.

2021-09-08 07:50 UTC, huan requested changes
Thanks for the update!

Please make the CI turns green before we can contribute reviewing this PR.

P.S. I believe we should rename PNG to WEBP to make the image type to be consistent.

2021-09-08 13:49 UTC, encodeArnab commented
Hello @huan 
We've made the necessary adjustments, and CI is now green.

2021-09-09 09:57 UTC, huan commented on docusaurus/src/pages/header-section/hero-section.tsx
> +    <div className={styles.body}>
Cloud we apply all the CSS at once in our code, instead of specifying the `className` everywhere?

2021-09-09 09:57 UTC, huan requested changes
Cloud we apply all the CSS at once in our code, instead of specifying the className everywhere?

2021-09-09 15:01 UTC, encodeArnab commented
Hello @huan 

> Cloud we apply all the CSS at once in our code, instead of specifying the className everywhere?

If I understand your question well, you're recommending that the appropriate CSS be written in the html tag itself, rather than using classname everywhere.

The main purpose of using classname for individual styles was to make the code cleaner and more efficient, as making a separate CSS file from the react component is usually the best practise. Because each CSS specifier for each classname is quite long, combining the css with each tag will be tough and chaotic for us. 
Could you provide us some advice on how we should go about making this change?
Thank You

2021-09-10 02:43 UTC, huan commented
> If I understand your question well, you're recommending that the appropriate CSS be written in the html tag itself, rather than using classname everywhere.

No, I'm not recommending writing CSS in the HTML tag itself.

My suggestion is, when inside our react HTML component, we can just use the exact class name instead of the `{style.xxx}`, which makes the code clearer.

```diff
- className={styles.heroImageMobile}
- className="heroImageMobile"
```

And to be better, I think we can use the shadow dom to make the CSS better by using just the semantic HTML tag with the `.semanticHtmlTag` css selector, or using a `id` for the selectors:

```html
<div id="hero">
  <img src="...">
</div>
```

For example, we can take a look at [react-shadow-root](https://apearce.github.io/react-shadow-root/)

2021-09-10 15:55 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/header-section/hero-section.tsx
> +        <headline id="heroTagLine">
I am not sure that \<headline> is valid semantic

I hope I am not missing something

<img width="970" alt="Screenshot 2021-09-10 at 9 25 09 PM" src="https://user-images.githubusercontent.com/62026125/132882311-bcb0e40f-c5c9-40ab-b8a6-89ca097896d4.png">

2021-09-10 15:59 UTC, encodeArnab commented
hello @Rohitesh-Kumar-Jain 
I apologise for the error; I will correct it right away.

2021-09-10 16:07 UTC, encodeArnab commented
hello @huan 
We've updated the suggested adjustments, eliminated classnames and other style elements, and provided contrast as per the proposed designs to distinguish between different sections of the landing page.

2021-09-10 18:16 UTC, huan requested changes

2021-09-10 18:16 UTC, huan commented on docusaurus/src/pages/header-section/hero-section.tsx
> +          src="https://user-images.githubusercontent.com/31739964/132517171-4eb33791-30ea-4f17-91ee-e3b170e8ef19.png"
We should store all images locally, instead of using an external URL link.

2021-09-10 18:16 UTC, huan commented on docusaurus/src/pages/header-section/hero-section.tsx
> +          src="https://user-images.githubusercontent.com/31739964/132517179-5802f6c3-1209-41d7-b993-3f2b197adc2d.png"
To be honest, I'm not like this bot avatar much.

Could we prepare some more bot avatar to be as the candidate of our website bot image, with a stronger style of the conversational user interface, text dialog?

2021-09-11 08:15 UTC, Rohitesh-Kumar-Jain commented
> hello @Rohitesh-Kumar-Jain
> I apologise for the error; I will correct it right away.

Thanks for correcting it, no need to apologize for it. a pr is at least a two-person job, one contributor and one reviewer : )

2021-09-11 08:25 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing my suggestions, great work :P

2021-09-11 14:08 UTC, encodeArnab commented on docusaurus/src/pages/header-section/hero-section.tsx
> +          src="https://user-images.githubusercontent.com/31739964/132517171-4eb33791-30ea-4f17-91ee-e3b170e8ef19.png"
hello @huan ,
Okay, we'll work on it.

2021-09-11 14:11 UTC, encodeArnab commented
> Thanks for implementing my suggestions, great work :P
Hi @Rohitesh-Kumar-Jain ,
Thank You for the review. :)

2021-09-11 17:08 UTC, encodeArnab commented on docusaurus/src/pages/header-section/hero-section.tsx
> +          src="https://user-images.githubusercontent.com/31739964/132517179-5802f6c3-1209-41d7-b993-3f2b197adc2d.png"
Hello @huan ,
We fixed the bot avatar during the review period of the design document and went ahead with the current image after approval from all the team members. That said, we don't have any backup avatar image and the video team has also used the same avatar as a part of their introductory video. @sajenjeshan1222 and I will discuss if we can get some more bot candidates.

2021-09-12 10:05 UTC, proudofsimin approved these changes

2021-09-17 15:28 UTC, sajenjeshan1222 approved these changes
LGTM

2021-09-22 03:00 UTC, lijiarui commented
Hi @encodeArnab  How can I preview the landing page? I tried to run docusaurus, but the landing page keep the old one.

![image](https://user-images.githubusercontent.com/6419514/134276680-d199b250-b1f7-4a49-acc0-7319c8f89723.png)

2021-09-23 06:11 UTC, encodeArnab commented
> Hi @encodeArnab How can I preview the landing page? I tried to run docusaurus, but the landing page keep the old one.
Hello @lijiarui 
In order for the new website to appear, we must first import all of the components and make a few changes to index.tsx. 
Other minor adjustments have been made to the footer. 
So, for the time being, we're waiting for all of the PRs to be merged before making those modifications in the next PR. 
Thank you very much.

2021-09-23 07:22 UTC, lijiarui commented
How about you create a PR change to index.tsx first? Then I think we can preview and then review.

2021-09-23 07:55 UTC, encodeArnab commented
> Thanks for your reply @encodeArnab
> 
> How about you create a PR change to index.tsx first? Then I think we can preview and then review.

Hello @lijiarui 
Yes, we can create a PR for that, but CI will fail because the components aren't merged, thus it won't discover all of the files. But we can push a draft PR for review.
So, should we create a draft PR?

2021-09-23 08:27 UTC, lijiarui commented
Could you find a way to commit to this PR, just change this PR-related part in index.tsx ?

2021-09-23 10:56 UTC, encodeArnab commented
Hello @lijiarui 
I've made changes to the index.tsx file, and you can now preview this section.
I also moved the images associated with this section to the static folder, as recommended by the docusaurus documentation, to avoid any errors.
Thank you

2021-10-14 12:18 UTC, arnabiscreating commented
Hello @huan, @lijiarui, @Rohitesh-Kumar-Jain, @proudofsimin
I'd like to know when the PRs for the first four sections will be able to merge and what the next step will be for those PRs, as those four PRs have three authorised reviews and have completed all of the requested changes to the first four sections.
Or will they be integrated once all the sections has been approved? 
And I'd like to know when we should start working on the end-term blog, when we've merged the majority of the PRs in accordance with the [GSoD'21 Guide Blog](https://wechaty.js.org/2021/07/10/google-season-of-docs-guide/), or if we should start writing and making a demo video right away.
Thank you.

2021-10-14 13:33 UTC, proudofsimin commented
> Hello @huan, @lijiarui, @Rohitesh-Kumar-Jain, @proudofsimin I'd like to know when the PRs for the first four sections will be able to merge and what the next step will be for those PRs, as those four PRs have three authorised reviews and have completed all of the requested changes to the first four sections. Or will they be integrated once all the sections has been approved? And I'd like to know when we should start working on the end-term blog, when we've merged the majority of the PRs in accordance with the [GSoD'21 Guide Blog](https://wechaty.js.org/2021/07/10/google-season-of-docs-guide/), or if we should start writing and making a demo video right away. Thank you.

We could merge it once we receive approvals from everyone. I would suggest that you send emails if you have been waiting for someone's review for quite a long time. For the second question, since you have finished your work, you could start working on your final report.

2021-10-14 14:13 UTC, huan approved these changes
Thanks for the updates!

I have no time to check all of our landing pages PRs for now, but I believe it the time to merge them once they are good to go by receiving enough PR approvals as well as you have high confidence of this PR is good to be merged.

I believe those React components are highly encapsulated and can be revised after it has been published.

Please feel free to help yourself to merge the PR and please do double check our website is deployed as you expected by checking our landing page after the GitHub Action has been finished.

Thank you very much!

2021-10-15 04:44 UTC, merged

2021-10-15 07:01 UTC, encodeArnab commented
> We could merge it once we receive approvals from everyone. I would suggest that you send emails if you have been waiting for someone's review for quite a long time. For the second question, since you have finished your work, you could start working on your final report.

Hello @proudofsimin,
Thank you for informing me; we will begin working on the end-of-term blog right away.

2021-10-15 07:10 UTC, encodeArnab commented
> Thanks for the updates!
> 
> I have no time to check all of our landing pages PRs for now, but I believe it the time to merge them once they are good to go by receiving enough PR approvals as well as you have high confidence of this PR is good to be merged.
> 
> I believe those React components are highly encapsulated and can be revised after it has been published.
> 
> Please feel free to help yourself to merge the PR and please do double check our website is deployed as you expected by checking our landing page after the GitHub Action has been finished.
> 
> Thank you very much!

Hello @huan, 
Thank you for your approval. 
The merge process has started, however there are three sections that still need your permission before they can be merged.
(Those are #1262, #1269, #1272)
And, absolutely, we will make every effort to ensure that the site is bug-free and that everything functions properly.
Thank you