Updated the  sidebars.ts  for references section
wechaty/docusaurus pull request #1260
Opened 2021-09-08 10:42 UTC by shraddhavp

this pr links to #890 and it is a PR that fixes the side bar issue

2021-09-08 12:48 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-08 16:47 UTC, proudofsimin approved these changes

2021-09-09 04:46 UTC, huan commented on docusaurus/sidebars.ts
> -    'specs/token',
Why do we remove the `token` entry from sidebar menu?

2021-09-09 04:51 UTC, shraddhavp commented on docusaurus/sidebars.ts
> -    'specs/token',
@huan removing the token section because https://github.com/wechaty/wechaty.js.org/pull/919 is the newer version of the token section itself

2021-09-09 04:57 UTC, huan commented on docusaurus/sidebars.ts
> -    'specs/token',
I think 919 is only added a new spec for gateway, instead of replacing the existing token ?

Please confirm. Thank you very much.

2021-09-09 05:01 UTC, shraddhavp commented on docusaurus/sidebars.ts
> -    'specs/token',
yes I got it @huan  will add the token section back ,there is another PR for token ,that has been merged yet so will be re-adding the tokens section ,sorry for the bit of a confusion

2021-09-09 05:04 UTC, huan commented on docusaurus/sidebars.ts
> +    'api/wechaty-class',
I also have question about this part: why do we replacing the `wechaty` by another name, does that necessary?

2021-09-09 05:09 UTC, shraddhavp commented on docusaurus/sidebars.ts
> +    'api/wechaty-class',
well I have created a new section for Wechaty classes as per PR #865 and hence changing the file name to wechaty class as in PR #913

2021-09-09 08:18 UTC, huan commented on docusaurus/sidebars.ts
> +    'api/wechaty-class',
I saw the new files are added via #865 and #913, however, the old file has been neither renamed nor deleted (please correct me if I missed anything).

And I have just checked our repo, the https://github.com/wechaty/wechaty.js.org/blob/master/docusaurus/docs/api/wechaty.md still exists.

So my comments will be:

1. If we decided to replace the `wechaty.md` by `wechaty-class.md`, then we should include them in one PR so that the git system can know it's a **rename** operation, and so that we can track changes/diffs.
2. If we change our docs to use a new file, we need to deal with the old file properly, in one Pull Request, so that we can track all of them together.
3. If we only add new files and replace the sidebar to the new file, but do not deal with the old files, we will not only lose track of the old docs (which we should always track the change of them!), but also we will have a file leak, left trash files in our repo.

I hope I have made myself clear, and please feel free to let me know if you have any questions.

Also, I want to CC @proudofsimin about my above comments because you have approved this change.

Thank you very much.

2021-09-09 08:19 UTC, huan requested changes
Please follow my comments at https://github.com/wechaty/wechaty.js.org/pull/1260/files#r705098954

2021-09-12 04:49 UTC, closed without merging