Features Section of the Wechaty landing page
wechaty/docusaurus pull request #1262
Opened 2021-09-08 14:20 UTC by encodeArnab

Issue Number ( #912 )
This commit comprises of an atomic PR of Second section (Features Section with CSS) for the Wechaty landing page.

Images of hero section running locally

(Desktop Version)
<img width="618" alt="Screenshot 2021-09-08 at 1 16 16 PM" src="https://user-images.githubusercontent.com/77114532/132526500-4ad182cc-8a43-45f1-a43b-4e20963199fa.png">

(Mobile Version)
<img width="346" alt="Screenshot 2021-09-08 at 1 15 14 PM" src="https://user-images.githubusercontent.com/77114532/132526562-1c84398d-1b7b-49fd-81e5-cd0060954f08.png">
<img width="347" alt="Screenshot 2021-09-08 at 1 15 27 PM" src="https://user-images.githubusercontent.com/77114532/132526573-e6961fe6-7843-44bc-9e79-ffd112a6d527.png">

2021-09-09 05:52 UTC, Rohitesh-Kumar-Jain reviewed
Check my comment on #1267 : )

2021-09-10 16:27 UTC, encodeArnab commented
Hello @Rohitesh-Kumar-Jain 
I've applied contrast to identify between distinct elements of the landing page, as per the recommended designs. The contrast is a little mild to match the overall UI, but each section is easily distinguishable. 
In addition, I updated the proposed changes and removed classnames and other style elements.

2021-09-10 18:18 UTC, huan requested changes, later dismissed

2021-09-10 18:18 UTC, huan commented on docusaurus/src/pages/features-section/features-section.tsx
> +                src="https://static.overlay-tech.com/assets/a633a787-7bc5-4b36-abe7-fbc1a8a48f1f.svg"
We need to save those images to local

2021-09-12 10:07 UTC, proudofsimin approved these changes

2021-09-13 06:36 UTC, Rohitesh-Kumar-Jain requested changes

2021-09-13 06:36 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/features-section/features-section.css
> +#number100 {
if you may add some decription about this number100 that would be great

2021-09-13 06:36 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/features-section/features-section.css
> +#number100Two {
same as above

2021-09-13 06:36 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/features-section/features-section.css
> +#number10000 {
same as above

2021-09-13 06:36 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/features-section/features-section.tsx
> +              <img alt="Check Circle Vector" id="vector" src="tick-mark.webp" />
Thanks for automatically implementing suggestion across the PRs : )
Great work 🎉

2021-09-14 10:30 UTC, encodeArnab commented on docusaurus/src/pages/features-section/features-section.css
> +#number10000 {
Hello @Rohitesh-Kumar-Jain 
Okay, to make them more descriptive, I'll write a comment.

2021-09-14 10:31 UTC, encodeArnab commented on docusaurus/src/pages/features-section/features-section.tsx
> +              <img alt="Check Circle Vector" id="vector" src="tick-mark.webp" />
Thank You : )

2021-09-15 12:48 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for using more descriptive name, when the names aren't descriptive enough add comments

2021-09-17 15:28 UTC, sajenjeshan1222 approved these changes
LGTM

2021-10-15 08:29 UTC, merged