Added Lets Get Started Section of the new Wechaty landing page (Section 3)
wechaty/docusaurus pull request #1266
Opened 2021-09-08 15:41 UTC by encodeArnab

Issue Number ( #912 )
This commit comprises of an atomic PR of third section (Lets Get Started Section with CSS) for the Wechaty landing page.

Images of Lets Get Started Section running locally

(Desktop Version)
<img width="1440" alt="Screenshot 2021-09-08 at 9 02 06 PM" src="https://user-images.githubusercontent.com/77114532/132540712-0141ddcc-a3f6-4786-9992-8401f0cda016.png">

(Mobile Version)
<img width="347" alt="Screenshot 2021-09-08 at 9 02 39 PM" src="https://user-images.githubusercontent.com/77114532/132540803-13934da1-a2b6-42a8-a65d-6eb2d1c1477e.png">
<img width="349" alt="Screenshot 2021-09-08 at 9 03 10 PM" src="https://user-images.githubusercontent.com/77114532/132540826-88a3c5ba-f2f1-4c49-bba5-375ef98eda70.png">
<img width="348" alt="Screenshot 2021-09-08 at 9 02 53 PM" src="https://user-images.githubusercontent.com/77114532/132540834-5dec54be-64d0-4711-96b0-43532db997a7.png">

2021-09-09 05:56 UTC, Rohitesh-Kumar-Jain reviewed
See my comment on #1267.

I have seen all of your 7 PRs and I don't see proper semantics being followed, as you have used the <div> tag everywhere.

Another thing, we agreed upon was to have contrast in the landing page, but after viewing 7 sections I don't think that's being worked upon? Do you plan to add contrast later to the landing page?

2021-09-09 15:11 UTC, encodeArnab commented
Hello @Rohitesh-Kumar-Jain 
Thank you for taking the time to write a review. 
Yes, we considered doing that in the next commit because it was already in the design, and we'll also do semantics in the next commit.

2021-09-10 16:43 UTC, encodeArnab commented
Hello @Rohitesh-Kumar-Jain,
For the landing page components, I modified all possible semantics, and for section contrast, please read my second section comment [here](https://github.com/wechaty/wechaty.js.org/pull/1262#issuecomment-917038472)

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain requested changes

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +#takeMeThereLinkButtonTwo {
Can you add some comments above this so, one can know later which takeMeThereLink you are talking about, and where it will be taking a user

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +#takeMeThereLinkButtonThree {
same as above

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +#takeMeThereLink {
same

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +#contentWrapperThree {
pls add some comments

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +  #contentWrapperTwo {
one-liner comment will be sufficient here

2021-09-13 06:33 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +  #takeMeThereLinkButtonTwo {
same

2021-09-14 10:33 UTC, encodeArnab commented on docusaurus/src/pages/lets-get-started/lets-get-started-section.css
> +  #takeMeThereLinkButtonTwo {
Hello @Rohitesh-Kumar-Jain 
Ya I will work on it.

2021-09-14 14:54 UTC, proudofsimin approved these changes

2021-09-16 06:23 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-17 15:29 UTC, sajenjeshan1222 approved these changes
LGTM

2021-10-15 06:21 UTC, merged