Honors and Awards section of the new wechaty landing page (Section 5)
wechaty/docusaurus pull request #1269
Opened 2021-09-08 16:41 UTC by sajenjeshan1222

Issue Number: #912  

This PR comprises of an atomic PR of fifth section (Honors and Awards) for the new wechaty landing page.

Below are the images of Honors and Awards Section running locally

Desktop Version:
<img width="1171" alt="Screenshot 2021-09-08 at 9 04 36 PM" src="https://user-images.githubusercontent.com/31739964/132549413-cd1f201c-34dd-4cdc-93b6-bf93a962e941.png">

Mobile Version:
<img width="346" alt="Screenshot 2021-09-08 at 9 05 43 PM" src="https://user-images.githubusercontent.com/31739964/132549476-8333a0cf-1d2c-4bad-8f76-f4880e8258f9.png">
<img width="347" alt="Screenshot 2021-09-08 at 9 05 53 PM" src="https://user-images.githubusercontent.com/31739964/132549481-37869397-efab-476f-a4e5-dfd356a6d7ce.png">

2021-09-09 08:37 UTC, huan requested changes

2021-09-09 08:37 UTC, huan commented on docusaurus/src/pages/honors-and-awards-section/honors-and-awards-section.tsx
> +        <div className={styles.body}>
I saw you add custom css on every line of the HTML code, which is very verbose.

Can we apply CSS once for the whole react html5 component?

2021-09-11 10:22 UTC, sajenjeshan1222 commented on docusaurus/src/pages/honors-and-awards-section/honors-and-awards-section.tsx
> +        <div className={styles.body}>
Done, I have made changes in all the PRs as you said

2021-09-11 15:03 UTC, huan requested changes, later dismissed
I saw all CSS are using `id` (`#id`), and every HTML section has different `id`s.

I think we should use a more general class to specify this?

For example, `honorsAndAwardsFirstWrapper` and `honorsAndAwardsSecondWrapper` seems not necessary to be different?

2021-09-12 14:21 UTC, sajenjeshan1222 commented
> I saw all CSS are using `id` (`#id`), and every HTML section has different `id`s.
> 
> I think we should use a more general class to specify this?
> 
> For example, `honorsAndAwardsFirstWrapper` and `honorsAndAwardsSecondWrapper` seems not necessary to be different?

@huan ok I will change it accordingly.

2021-09-13 06:27 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-14 14:59 UTC, proudofsimin approved these changes

2021-09-16 08:21 UTC, encodeArnab approved these changes

2021-10-15 07:42 UTC, merged