voice of developers section of the new wechaty landing page (Section 6)
wechaty/docusaurus pull request #1271
Opened 2021-09-08 17:38 UTC by sajenjeshan1222

Issue Number: #912

This PR comprises of an atomic PR of sixth section (Voice of Developers) for the new wechaty landing page.

Below are the images of Honors and Awards Section running locally

Desktop Version:
<img width="1171" alt="Screenshot 2021-09-08 at 9 04 47 PM" src="https://user-images.githubusercontent.com/31739964/132557355-ff56982b-f2a3-44fd-8120-ea9771acbca0.png">

Mobile Version:
<img width="347" alt="Screenshot 2021-09-08 at 9 06 01 PM" src="https://user-images.githubusercontent.com/31739964/132557382-cdff7c75-e8fb-4955-82d0-a2635ae7f9c1.png">

@huan we need the voice of developers quote and their avatar to replace it with the example one in this section PR.

2021-09-09 06:23 UTC, Rohitesh-Kumar-Jain reviewed
This comment is probably net-picking, but I feel that the contrast in the voice of developers section can be made better by using a bit darker black color 😅 

Or some other combination, there are many online resources for checking contrast like this one https://webaim.org/resources/contrastchecker/

2021-09-11 10:31 UTC, sajenjeshan1222 commented
> This comment is probably net-picking, but I feel that the contrast in the voice of developers section can be made better by using a bit darker black color 😅
> 
> Or some other combination, there are many online resources for checking contrast like this one https://webaim.org/resources/contrastchecker/

@Rohitesh-Kumar-Jain I can understand and we added the contrast in voice of developers section and other sections in which the contrast was necessary and also we have made the changes that was said by @huan and the changes that was said by you in here

2021-09-13 06:23 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
Shouldn't we fill this text now as well. I feel we shouldn't have this merged on master with dummy text : )

2021-09-13 12:38 UTC, sajenjeshan1222 commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
@Rohitesh-Kumar-Jain yes we should as I said you in one of our meeting I have the developers voice(quotes) that was said by various developers but we don't have their avatar to put in that place.

You can look at the voice of developers [here](https://github.com/Wechaty/wechaty/wiki/Voice%20Of%20Developer) but we are missing their avatar/image to put in that place

2021-09-13 12:56 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
I will suggest not to place dummy quote in master, rather search pics online for them, google about the person or maybe add an image related to them, if thier isn't available. I mean if they are CEO of a particular company, add pic of thier company's logo.

Or maybe we can add random related images from Splash temporaritly, like these?

<img width="1366" alt="Screenshot 2021-09-13 at 6 22 16 PM" src="https://user-images.githubusercontent.com/62026125/133086784-5c8349d2-2ca0-4ee9-b730-c8d2cf2e8848.png">

@proudofsimin @huan @lijiarui what do you think?

2021-09-13 13:13 UTC, sajenjeshan1222 commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
ok thank you and  I will look into it and do the necessary changes.

2021-09-13 17:09 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
Hey wait for other's view on this as well 😅

2021-09-13 17:10 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
I am not requesting a change, I just felt it might feel weird to have dummy text in the master branch itself, where visitors might be reading that.

2021-09-14 12:49 UTC, sajenjeshan1222 commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
ok lets wait for others no issues

2021-09-14 15:08 UTC, proudofsimin commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
I would personally prefer not to put this on as publishing drafts is a bit unprofessional.

2021-09-15 17:01 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
@proudofsimin so should we consider putting genuine text with dummy pics?

2021-09-16 12:58 UTC, sajenjeshan1222 commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
So what are we do? I have the voice of developers and their avatars are missing. we can include 3 voice of developers.

2021-09-19 11:28 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
1 image done : https://github.com/hailiang-wang

2021-09-19 11:34 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
2nd image take it from here https://wechaty.js.org/contributors/lijiarui/

"Wechaty让运营人员更多的时间思考如何进行活动策划、留存用户，商业变现"
-- @lijiarui, Orange Interactive CEO.

2021-09-19 11:41 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
for the third image try requesting him (via his email id gcaufy@gmail.com)

Wechaty is a great solution, I believe there would be much more users recognize it." link
-- @Gcaufy, Tencent Engineer, Author of WePY

2021-09-20 03:15 UTC, sajenjeshan1222 commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
Thank you for the information and for the third image I will try reaching him and let you know what is the response.

2021-09-27 09:12 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
Any update on the same?

2021-09-27 09:14 UTC, Rohitesh-Kumar-Jain requested changes
Pls remove dummy images and dummy text from the voice of the developers and replace them with the ones that I provided.

2021-09-27 14:49 UTC, sajenjeshan1222 commented on docusaurus/src/pages/voice-of-developers-section/voice-of-developers-section.tsx
> +            "This is an example text, voice of developers comes here"
I contacted the developer with the mail that you provided but no response yet.

2021-09-27 16:00 UTC, sajenjeshan1222 commented
> Pls remove dummy images and dummy text from the voice of the developers and replace them with the ones that I provided.

@Rohitesh-Kumar-Jain Ok I will replace those and for the last developer image I will use that developer GitHub avatar as temporary, is that fine?

2021-09-27 16:28 UTC, Rohitesh-Kumar-Jain commented
> > Pls remove dummy images and dummy text from the voice of the developers and replace them with the ones that I provided.
> 
> @Rohitesh-Kumar-Jain Ok I will replace those and for the last developer image I will use that developer GitHub avatar as temporary, is that fine?

yeah, that's fine, btw you got any reply to your email?

2021-10-07 11:42 UTC, sajen-k commented
> > > Pls remove dummy images and dummy text from the voice of the developers and replace them with the ones that I provided.
> > 
> > 
> > @Rohitesh-Kumar-Jain Ok I will replace those and for the last developer image I will use that developer GitHub avatar as temporary, is that fine?
> 
> yeah, that's fine, btw you got any reply to your email?

@Rohitesh-Kumar-Jain No I haven't got any reply for that mail yet

2021-10-15 05:32 UTC, Rohitesh-Kumar-Jain commented
@sajenjeshan1222 and @encodeArnab pls work upon resolving my requested change. So that we can proceed with the merge.

2021-10-15 05:32 UTC, Rohitesh-Kumar-Jain commented
@encodeArnab and @proudofsimin pls add your suggestions as well.

2021-10-15 05:34 UTC, sajenjeshan1222 commented
@Rohitesh-Kumar-Jain I have implemented the changes now, please take a look.

2021-10-15 05:36 UTC, Rohitesh-Kumar-Jain commented
What image are you using for the third voice?

2021-10-15 05:42 UTC, sajenjeshan1222 commented
> What image are you using for the third voice?

@Rohitesh-Kumar-Jain As I said before I reached the person via the mail but there was no response till now, so for the third image I am using GitHub avatar of the person. There was a delay to implement this changes because I was waiting for the response for the mail regarding the third person image. Thank you.

2021-10-15 05:46 UTC, Rohitesh-Kumar-Jain commented
Maybe we can use the image in https://github.com/Gcaufy, I have been unable to find his real image, and we can't use somebody else's face for him, neither we can leave that without a photo.

So I see 3 choices : 

1) we use some objects as images like the ones I shared above.

2) Let's drop the third voice of the developer altogether.

3) This section is the voice of the developer section, and we haven't asked the main developer of Wechaty i.e @huan for his voice yet 😅

2021-10-15 05:48 UTC, sajen-k commented
> Maybe we can use the image in https://github.com/Gcaufy, I have been unable to find his real image, and we can't use somebody else's face for him, neither we can leave that without a photo.

I am using that image only

2021-10-15 08:17 UTC, Rohitesh-Kumar-Jain approved these changes
I think the voice of the developers section is satisfactory enough to merge :)

2021-10-15 08:46 UTC, arnabiscreating approved these changes
Looks good

2021-10-15 08:47 UTC, sajen-k commented
@Rohitesh-Kumar-Jain we need 3 approval to merge this PR so I would like to ask @proudofsimin to review and approve it.

2021-10-15 08:53 UTC, iamrajiv approved these changes

2021-10-15 08:53 UTC, merged