Sponsors section of the new wecahty landing page (Section 7)
wechaty/docusaurus pull request #1272
Opened 2021-09-08 18:08 UTC by sajenjeshan1222

Issue Number: #912

This PR comprises of an atomic PR of seventh section (Sponsors) for the new wechaty landing page.

Below are the images of Sponsors Section running locally

Desktop Version:
<img width="1170" alt="Screenshot 2021-09-08 at 9 04 58 PM" src="https://user-images.githubusercontent.com/31739964/132561669-67eb6f87-49c6-4788-8294-639901daeae7.png">

Mobile Version:
<img width="346" alt="Screenshot 2021-09-08 at 9 06 23 PM" src="https://user-images.githubusercontent.com/31739964/132561703-716a2dbb-0db3-4260-8771-f7d53e555b15.png">

2021-09-09 05:59 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.tsx
> +      <img
pls add alt text to all images, it helps improve accessibility : )

2021-09-09 06:00 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.tsx
> +      <img
And pls add that to all PRs, that's something I am confident you should be adding, and I am a requesting change.

2021-09-09 06:05 UTC, Rohitesh-Kumar-Jain requested changes
Pls, add alt text to all images, in all PRs.

2021-09-11 10:41 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.tsx
> +      <img
Done!

2021-09-11 10:42 UTC, sajenjeshan1222 commented
@Rohitesh-Kumar-Jain All the changes was made in all the corresponding PRs

2021-09-11 15:55 UTC, huan requested changes, later dismissed
1. Please use `.webp` format instead of others.
1. Please name the image file with meaningful name, for example: `sponsorOne.png` -> `tencent.webp`

2021-09-12 17:28 UTC, sajenjeshan1222 commented
> 1. Please use `.webp` format instead of others.
> 2. Please name the image file with meaningful name, for example: `sponsorOne.png` -> `tencent.webp`

@huan Done

2021-09-13 06:11 UTC, Rohitesh-Kumar-Jain requested changes

2021-09-13 06:11 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsOne {
Pls do change this from sponsoring to sponsor's name, 

In general, if you have to named your variables like string1, string2, you should consider renaming them.

2021-09-13 06:11 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsFirstSection {
here also can you come up with a more descriptive name?

2021-09-13 06:11 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsTwo {
same as above

2021-09-13 06:11 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsOneImage {
here as well

2021-09-13 06:11 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +  #sponsorsFive {
same as above

2021-09-13 13:02 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsOne {
Done, Thank you for the comments.

2021-09-13 13:02 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsTwo {
done

2021-09-13 13:02 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsOneImage {
done

2021-09-13 13:02 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +  #sponsorsFive {
done

2021-09-13 13:10 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsFirstSection {
ok I will look into it and we have divided the sponsors to 2 section where one contains few sponsors logo and 2nd section contains others and each of these wrapped into 2 `<div>` tags that's the reason we have given it as firstsection and secondsection.

2021-09-13 17:06 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsFirstSection {
If you aren't able to come up with a meaningful name, at least add comments on top of that giving some details about it

2021-09-14 13:02 UTC, sajenjeshan1222 commented on docusaurus/src/pages/sponsors-section/sponsors-section.css
> +#sponsorsFirstSection {
Done, thank you.

2021-09-16 03:37 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing both my and @huan's suggested changes.

2021-09-16 08:19 UTC, encodeArnab approved these changes
Looks good to me.

2021-09-16 15:26 UTC, proudofsimin approved these changes

2021-10-15 13:12 UTC, merged