[GSoD 2021] Improved contributing guidelines
wechaty/docusaurus pull request #1276
Opened 2021-09-09 19:02 UTC by iamrajiv

Fixes: #1111
Related: #1012 wechaty/grpc#140 wechaty/openapi#16

![Screenshot 2021-09-10 at 12 29 18 AM](https://user-images.githubusercontent.com/42106787/132746908-c1b4228c-5053-4f25-9996-fb739391bb7c.jpg)

![Screenshot 2021-09-10 at 12 29 28 AM](https://user-images.githubusercontent.com/42106787/132746922-2cf7f0fd-0e42-4d43-bbf0-4b411fa86a7c.jpg)

2021-09-09 22:26 UTC, iamrajiv commented
@huan @Rohitesh-Kumar-Jain @proudofsimin Please review

2021-09-10 02:57 UTC, huan commented on docusaurus/docs/contributing/documentation.md
> +To get started contributing, you'll want to read the :ref:`reStructuredText reference <sphinx:rst-index>`.
Please remove the RST related information because we are using Markdown.

2021-09-10 03:04 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/contributing/overview.md
> +### Not sure where to start?
Apart from contributing code/documentation, there are many subtle ways via which one can contribute.

Like reporting bugs, suggesting enhancements, attending open wechaty meetings.
And some more subtle as following Wechaty across social media, and sharing its post

2021-09-10 03:05 UTC, Rohitesh-Kumar-Jain commented
You haven't attached all the ss

2021-09-10 03:08 UTC, Rohitesh-Kumar-Jain reviewed
We probably should also add some guidelines about adding relevant labels regarding the PRs and Issues.

2021-09-10 03:14 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/contributing/overview.md
> +We built wechaty with pleasure because it can help others. Help from you for wechaty will be very much appreciated by the community.
`Help from you` -> your contributions (or something else).

I feel that you have used a single word `help` quite often.

2021-09-10 03:16 UTC, Rohitesh-Kumar-Jain commented
We probably can also add the `Code of Conduct` and `Getting Help` sections in which include a link to the Wechaty Gitter channel as well.

2021-09-11 00:27 UTC, iamrajiv commented
hi, @huan @Rohitesh-Kumar-Jain thanks for the suggestions I have implemented the requested changes. Also, I have added only those page screenshots that I had heavily edited or created.

2021-09-11 03:57 UTC, huan commented on docusaurus/docs/contributing/overview.md
> +What's documentation is one of its key strengths? It's informative
I feel it's strange in this sentence.

2021-09-11 06:11 UTC, iamrajiv commented on docusaurus/docs/contributing/overview.md
> +What's documentation is one of its key strengths? It's informative
@huan thanks for pointing out I have fixed it.

2021-09-12 08:54 UTC, proudofsimin requested changes
We could talk about the style more, but as in my previous experience and Google standards, we are actually trying to eliminate using "_you_" in documents to make the tone soften and formal. I understand that each document has its own writing style and those Django used don't necessarily apply to Wechaty's.

2021-09-12 08:54 UTC, proudofsimin commented on docusaurus/docs/contributing/documentation.md
> +  repeat the same material.
In how-to guides, users are expected to take the initiative and look for the information they need themselves. Contents in this section are organized as recipes to a cookbook. Each topic is independent and is named after the result that users will achieve after they follow the steps inside. With that said, the target audience for this section are those equipped with at least basic knowledge in Wechaty.

2021-09-12 08:54 UTC, proudofsimin commented on docusaurus/docs/contributing/documentation.md
> +is implied to be.
If you are documenting this part, suggest either to rewrite the whole content or remove this. It does not reflect the documents we were trying to do in GSoD. Besides, in technical documents, pronouns are actually not encouraged since it might cause some confusions. 
For the modifier, your statement is correct but this is not the main issue. The main focus should be formats, writing tones, and sentence structure. Minor issues such as use of punctuations, spellings...etc.

Last but not least, we are not creating documentation standards ourselves. We follow Google's standards which are very comprehensive in technical writing. As we cannot listed all the rules here, we ought to suggest contributors to check out the rules in Google. Also alternatives are Microsoft's style guide, Red Hat's or Apple's which are very renowned in technical documentation.

2021-09-12 08:54 UTC, proudofsimin commented on docusaurus/docs/contributing/documentation.md
> +## Commonly used terms
I would suggest to merge this part with the styling as Google provides a complete dictionary about whether the words are appropriate and how to format them, but it's thoughtful that you listed down some words.
How do you think rather than listed down in words, we list them down in rules? For example,
1. Use American spellings: "_realize_" instead of "_realise_", "_color_" instead of "_colour_"
2. Use the full product/language names and don't change the letter cases: "_Wechaty_" instead of "_wechaty_", "_JavaScript_" instead of "_javascript_"
...

2021-09-12 08:54 UTC, proudofsimin commented on docusaurus/docs/contributing/documentation.md
> +- **TOKEN** &mdash; it's all capitalized.
Could refer to [Main concepts in Wechaty](https://wechaty.js.org/docs/main-concepts-in-wechaty).

2021-09-12 08:54 UTC, proudofsimin commented on docusaurus/docs/contributing/documentation.md
> +
should also provide the link to official Markdown guides.

2021-09-13 08:41 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing my suggestion : )

2021-09-15 23:30 UTC, iamrajiv commented
@proudofsimin @huan I have done the requested changes.

2021-09-18 16:24 UTC, proudofsimin approved these changes

2021-09-18 16:28 UTC, iamrajiv commented
@huan I am done with the changes can you approve and merge 😀

2021-09-18 16:44 UTC, shraddhavp approved these changes

2021-09-18 17:43 UTC, merged