Puppet services overview
wechaty/docusaurus pull request #1277
Opened 2021-09-10 17:02 UTC by Soumi7

# Update Puppet services overview

TBD

2021-09-10 18:21 UTC, huan commented on docusaurus/docs/puppet-services/overview.mdx
> -## FAQ
Where has this part been moved to?

2021-09-11 05:11 UTC, Soumi7 commented on docusaurus/docs/puppet-services/overview.mdx
> -## FAQ
A new file, tokens.md

2021-09-11 05:33 UTC, huan commented on docusaurus/docs/puppet-services/overview.mdx
> -## FAQ
Ok. If we move part of the docs to a new file, please remember to always keep all the modifications into one PR, so that we can track and know what happens exactly.

If you separate them, then I'll be very nervous about the information lost problem.

Please make the above a requirement in the future, Thank you very much.

2021-09-11 05:34 UTC, huan requested changes
Please link to the new file `tokens.md` Pull Request to this one, because they are strongly related.

2021-09-11 05:50 UTC, Soumi7 commented
tokens file : #1282

2021-09-11 06:00 UTC, shraddhavp requested changes
please make the CLI green

2021-09-11 07:28 UTC, Soumi7 commented on docusaurus/docs/puppet-services/overview.mdx
> -## FAQ
Thanks, will keep this in mind from the next time!

2021-09-11 17:11 UTC, shraddhavp approved these changes

2021-09-12 06:58 UTC, Soumi7 commented
As suggested by @huan , I have merged #1282 tokens.md into this PR.

Add tokens.md file

## Screenshots

![Screenshot from 2021-09-11 11-54-42](https://user-images.githubusercontent.com/51290447/132938659-22e0e1ad-dda9-4c55-bae5-770157ecc7b6.png)

![Screenshot from 2021-09-11 11-54-47](https://user-images.githubusercontent.com/51290447/132938665-62bd710a-9f2c-4797-b1ae-08aee794f63d.png)

![Screenshot from 2021-09-11 11-54-51](https://user-images.githubusercontent.com/51290447/132938668-3aec6e03-53a2-4325-a509-91bc39ecb454.png)

![Screenshot from 2021-09-11 11-54-55](https://user-images.githubusercontent.com/51290447/132938669-087963f3-ac62-4702-a0ed-9762a5b8152a.png)

2021-09-13 05:07 UTC, shraddhavp approved these changes

2021-09-13 08:36 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/puppet-services/tokens.md
> +Long-term TOKEN is for those developers who has joined our [Wechaty Contributor Program](contributing/contributor-program.md).
has -> have ?

2021-09-13 08:36 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-14 15:11 UTC, proudofsimin approved these changes

2021-09-17 06:30 UTC, Soumi7 commented on docusaurus/docs/puppet-services/tokens.md
> +Long-term TOKEN is for those developers who has joined our [Wechaty Contributor Program](contributing/contributor-program.md).
Changed, thanks!

2021-09-18 10:29 UTC, huan approved these changes
Please follow my review and fix the problem, then this PR will LGTM.

2021-09-18 10:29 UTC, huan commented on docusaurus/docs/puppet-services/overview.mdx
> +export WECHATY_PUPPET_SERVICE_TOKEN="__TOKEN__"
Please use `${TOKEN}` instead of `__TOKEN__`.

Because the `_` has special meaning in our ecosystem since `wechaty@0.69`

2021-09-18 10:47 UTC, Soumi7 commented on docusaurus/docs/puppet-services/overview.mdx
> +export WECHATY_PUPPET_SERVICE_TOKEN="__TOKEN__"
Changed, thanks.

2021-09-18 11:07 UTC, merged