updated the Polyglot Do it yourself section
wechaty/docusaurus pull request #1283
Opened 2021-09-11 07:31 UTC by shraddhavp

this PR updated the Polyglot DIY section ,here have deleted sections that already present in Python wechaty section https://wechaty.js.org/docs/polyglot/python/ and also added the new polyglot architecture image

2021-09-13 06:50 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-13 09:22 UTC, Soumi7 approved these changes
LGTM

2021-09-15 17:30 UTC, proudofsimin approved these changes

2021-09-18 13:59 UTC, huan requested changes, later dismissed
Thanks for the update!

Please follow my reviews and I believe this PR will be ready to go after we have finished them!

2021-09-18 13:59 UTC, huan commented on docusaurus/docs/polyglot/diy/overview.md
> -  | wechaty-puppet-padlocal  | |  (wechaty-puppet-wechat) |
Please keep the asciiart image, which is easier to be maintained.

2021-09-18 13:59 UTC, huan commented on docusaurus/docs/polyglot/diy/overview.md
> -As we have already an ecosystem of Wechaty in TypeScript, so we will not have to implement everything in other languages, especially, in Feb 2020, we have finished the [wechaty_grpc](https://github.c
rename `wechaty_grpc` to `wechaty-grpc`, which is our correct NPM name.

2021-09-18 13:59 UTC, huan commented on docusaurus/docs/polyglot/diy/overview.md
> -  |  (wechaty-puppet-frida)  | |   (wechaty-puppet-mac)   |
Please help us to update the diagram by the following changes:

1. `Friday Protocol` -> `Windows Protocol`
1. `wechaty-puppet-frida` -> `wechaty-puppet-xp`
2. `Mac Protocol` -> `Whatsapp Protocol`
3. `wechaty-puppet-mac` -> `wechaty-puppet-whatsapp`

2021-09-18 16:10 UTC, shraddhavp commented on docusaurus/docs/polyglot/diy/overview.md
> -As we have already an ecosystem of Wechaty in TypeScript, so we will not have to implement everything in other languages, especially, in Feb 2020, we have finished the [wechaty_grpc](https://github.c
@huan done

2021-09-18 16:11 UTC, shraddhavp commented on docusaurus/docs/polyglot/diy/overview.md
> -  | wechaty-puppet-padlocal  | |  (wechaty-puppet-wechat) |
done

2021-09-18 16:11 UTC, shraddhavp commented on docusaurus/docs/polyglot/diy/overview.md
> -  |  (wechaty-puppet-frida)  | |   (wechaty-puppet-mac)   |
done @huan

2021-09-18 16:23 UTC, shraddhavp commented
> Thanks for the update!
> 
> Please follow my reviews and I believe this PR will be ready to go after we have finished them!

@huan done with the changes as suggested ,thanks for the suggestion

2021-09-18 16:42 UTC, merged