Update overview.mdx
wechaty/docusaurus pull request #1286
Opened 2021-09-11 14:51 UTC by shraddhavp

this PR contains the references section overview.

2021-09-13 06:49 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-13 06:49 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/references/overview.mdx
> +The reference guide contains are a technical description of the machinery. They are code determined, information oriented. The references guides contain clear descriptions of Classes, API, Functions,
aims -> aim ?

2021-09-13 09:19 UTC, shraddhavp commented on docusaurus/docs/references/overview.mdx
> +The reference guide contains are a technical description of the machinery. They are code determined, information oriented. The references guides contain clear descriptions of Classes, API, Functions,
done @Rohitesh-Kumar-Jain  thanks

2021-09-16 09:24 UTC, shraddhavp commented
@Soumi7

2021-09-16 14:59 UTC, proudofsimin approved these changes

2021-09-18 18:30 UTC, lijiarui requested changes, later dismissed

2021-09-18 18:30 UTC, lijiarui commented on docusaurus/docs/references/overview.mdx
> +title: WECHATY REFERENCES
I think `Wechaty References Overview` will be better.

2021-09-18 18:30 UTC, lijiarui commented on docusaurus/docs/references/overview.mdx
> +sidebar_label: 'References'
I think we should change to `Overview` as the other part is written.

2021-09-19 06:54 UTC, Soumi7 approved these changes

2021-09-19 07:13 UTC, shraddhavp commented on docusaurus/docs/references/overview.mdx
> +title: WECHATY REFERENCES
@lijiarui done

2021-09-19 07:13 UTC, shraddhavp commented on docusaurus/docs/references/overview.mdx
> +sidebar_label: 'References'
@lijiarui done

2021-09-19 12:58 UTC, merged

2021-09-21 04:53 UTC, huan commented on docusaurus/docs/references/overview.mdx
> +title: WECHATY REFERENCES OVERVIEW
I believe it is not a good title with all UPPER CAP?

2021-09-21 11:39 UTC, shraddhavp commented on docusaurus/docs/references/overview.mdx
> +title: WECHATY REFERENCES OVERVIEW
ok @huan

2021-09-23 16:59 UTC, huan commented on docusaurus/docs/references/overview.mdx
> +title: WECHATY REFERENCES OVERVIEW
You have read my comment and reply OK, but without changing it before merging it.

I think next time I will put a "Request changes" on your PR before everything is really good to go.

Please fix this problem by submitting another PR.

2021-09-23 18:18 UTC, shraddhavp commented on docusaurus/docs/references/overview.mdx
> +title: WECHATY REFERENCES OVERVIEW
@huan actually i had merged the PR before the comments from you,the next day I got the change request comment from you, will be doing by creating a new PR was busy this week so could not work on the issue. Will do it soon .