Update the friendship class section
wechaty/docusaurus pull request #1289
Opened 2021-09-12 12:53 UTC by shraddhavp

this PR updates the friendship class in API references section.

2021-09-12 12:55 UTC, shraddhavp commented
@proudofsimin  @Rohitesh-Kumar-Jain  @huan  @Soumi7

2021-09-13 06:48 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-13 09:28 UTC, Soumi7 requested changes

2021-09-13 09:28 UTC, Soumi7 commented on docusaurus/docs/api/friendship.md
Fuctionalities -> functionalities

2021-09-13 09:34 UTC, shraddhavp commented on docusaurus/docs/api/friendship.md
done

2021-09-16 09:10 UTC, Soumi7 approved these changes
Lgtm

2021-09-16 15:12 UTC, proudofsimin approved these changes

2021-09-18 12:16 UTC, merged