Update contacts in API references
wechaty/docusaurus pull request #1290
Opened 2021-09-12 14:21 UTC by shraddhavp

The PR updates the contacts section int he API refrences.

2021-09-13 06:05 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-13 09:27 UTC, Soumi7 requested changes

2021-09-13 09:27 UTC, Soumi7 commented on docusaurus/docs/api/contact.md
> +The method gets the region 'city' from a contact.Check the below example for implementation.
The -> this?

2021-09-13 09:27 UTC, Soumi7 commented on docusaurus/docs/api/contact.md
> +the method gets the region 'province' from a contact.Check the below example for implementation.
The -> this

2021-09-13 09:27 UTC, Soumi7 commented on docusaurus/docs/api/contact.md
> +The method finds contact by `name` or `alias`.If  you use Contact.findAll\(\) get the contact list of the bot. Include the contacts from bot's rooms.
The -> this

2021-09-13 09:33 UTC, shraddhavp commented on docusaurus/docs/api/contact.md
> +The method finds contact by `name` or `alias`.If  you use Contact.findAll\(\) get the contact list of the bot. Include the contacts from bot's rooms.
done

2021-09-14 05:14 UTC, shraddhavp commented
@huan

2021-09-16 09:10 UTC, Soumi7 approved these changes
LGTM

2021-09-16 15:22 UTC, proudofsimin approved these changes

2021-09-18 12:37 UTC, merged