Footer section of the new wecahty landing page (Section 8)
wechaty/docusaurus pull request #1292
Opened 2021-09-12 17:09 UTC by sajenjeshan1222

Issue Number: #912

This PR comprises of an atomic PR of eight section (Footer) for the new wechaty landing page.

I have added this Footer component under `src/theme/Footer.tsx`, this is because then only the docusaurus can identify this new footer and apply this new footer to other parts of the webpage. So footer should be added under the `src/theme` to make it visible to the whole website.

Below are the images of Footer Section running locally

Desktop Version:

<img width="1000" alt="Screenshot 2021-09-08 at 9 05 27 PM" src="https://user-images.githubusercontent.com/31739964/132996167-139da69b-d740-4b60-bb39-0080d9a3c855.png">

Mobile Version:

<img width="346" alt="Screenshot 2021-09-08 at 9 06 32 PM" src="https://user-images.githubusercontent.com/31739964/132996180-e680f8f3-01fb-4ffc-8a81-e5d19351e5ed.png">
<img width="348" alt="Screenshot 2021-09-08 at 9 06 40 PM" src="https://user-images.githubusercontent.com/31739964/132996182-da6a7802-2c03-4ed8-b0ef-12c9b67367ea.png">

2021-09-13 06:16 UTC, Rohitesh-Kumar-Jain requested changes

2021-09-13 06:16 UTC, Rohitesh-Kumar-Jain commented on docusaurus/src/theme/footer-section.css
> +  #footerColumnOne {
Hey pls add some comments in the CSS, file so that another person working on the future is able to know that is this for footer column one from left or right.

2021-09-13 13:26 UTC, sajenjeshan1222 commented on docusaurus/src/theme/footer-section.css
> +  #footerColumnOne {
Done

2021-09-13 17:08 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-16 08:17 UTC, encodeArnab approved these changes

2021-09-16 15:49 UTC, proudofsimin approved these changes

2021-10-15 06:05 UTC, merged