如何使用python-wechaty来搭建一个自动转发消息的微信机器人
wechaty/docusaurus pull request #1304
Opened 2021-09-21 14:34 UTC by Gan-lang

2021-09-21 14:47 UTC, lijiarui commented
Please always keep working on one PR and keep improving it, instead of closing one and opening another, because we should always keep the conversation and the improvements linked together, which can be achieved by keeping improving one PR.

This PR seemed duplicated with https://github.com/wechaty/wechaty.js.org/pull/1302 https://github.com/wechaty/wechaty.js.org/pull/1303. I suggest you close this PR and keep commit in https://github.com/wechaty/wechaty.js.org/pull/1302

2021-09-21 14:52 UTC, Gan-lang commented
#1302 #1303 这两个已经被我删除了，之前拉取的仓库已经删除无法恢复

2021-09-21 14:56 UTC, Gan-lang commented
> 请始终在一个 PR 上继续工作并不断改进它，而不是关闭一个然后打开另一个，因为我们应该始终将对话和改进联系在一起，这可以通过不断改进一个 PR 来实现。
> 
> 这个 PR 似乎与[#1302 ](https://github.com/wechaty/wechaty.js.org/pull/1302) #1303重复。我建议你关闭这个 PR 并继续提交#1302

[#1302 ](https://github.com/wechaty/wechaty.js.org/pull/1302) #1303这两个已经被我删除了，之前拉取的仓库已经删除无法恢复

2021-09-21 15:20 UTC, lijiarui commented
Sure, then please keep working on this PR, don't create any other new PR unless it is a new feature or a new blog.

2021-09-21 15:21 UTC, lijiarui commented
In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-09-21 15:30 UTC, Gan-lang commented
修改文件名为小写字母，并且改变图片为 .webp 格式
无法理解 npm test 中错误
(jekyll/_contributors/__AUTHOR__.md) 文件名必须匹配 /[a-z0-9_-.]+/

2021-09-21 15:32 UTC, lijiarui commented
It means this filename: `jekyll/_contributors/Gan-lang.md` must match /[a-z0-9-.]+/

2021-09-21 15:33 UTC, Gan-lang commented
谢谢，已经做出改变

2021-09-21 15:34 UTC, lijiarui commented
Good, looking forward to your GitHub action green as soon as possible!

2021-09-21 15:42 UTC, Gan-lang commented
提交中已经修改大小写问题，但是因为重名
File renamed without changes.
无法覆盖之前的提交

2021-09-21 15:45 UTC, lijiarui commented
You have committed two files, you should delete this one: jekyll/_contributors/Gan-lang.md

![image](https://user-images.githubusercontent.com/6419514/134203075-d5ee1419-fb05-4c4e-bb4f-8b97ae5dac6c.png)

2021-09-22 10:28 UTC, Gan-lang commented
提交已绿，请审核。
加入Wechaty Contributor Program
希望获得一个长久的token

2021-09-22 20:03 UTC, huan commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
I believe this will not work at all?

2021-09-23 00:27 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
这是可行的，我已经有现成的实例可供参考

2021-09-23 00:28 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
This is feasible, I already have ready-made examples for reference

2021-09-23 00:30 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
This is feasible, I already have ready-made examples for reference

2021-09-23 00:35 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
This allows environment variables to be permanently modified, that is, they can be modified remotely.
Code example:
`vi /root/.bashrc`
`export WECHATY_LOG="verbose"
export WECHATY_PUPPET="wechaty-puppet-padlocal"
export WECHATY_PUPPET_PADLOCAL_TOKEN="puppet_padlocal_"
export WECHATY_PUPPET_SERVER_PORT="8086"
export WECHATY_TOKEN=""`
`source ~/.bashrc`

2021-09-23 15:05 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
export WECHATY_PUPPET="wechaty-puppet-padlocal"

2021-09-23 16:28 UTC, huan commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
> export WECHATY_PUPPET="wechaty-puppet-padlocal"

That's correct.

2021-09-24 04:36 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
> > export WECHATY_PUPPET="wechaty-puppet-padlocal"
> 
> That's correct.

So can I pass

2021-09-24 07:55 UTC, lijiarui requested changes

2021-09-24 07:55 UTC, lijiarui commented on jekyll/_contributors/gan-lang.md
> +a student
It would be better adding more information of you here, instead of just saying `a student`

2021-09-24 07:55 UTC, lijiarui commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +  - blog
Please remove blog tag here, since all of the articles are blog.

2021-09-24 07:55 UTC, lijiarui commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +先前在本社区看到一篇关于怎么使用 `python`-`wechaty`+`paddlehub`+阿里云白嫖一个智能微信机器人，
It would be better to add a link for `python`-`wechaty`+`paddlehub`+阿里云白嫖一个智能微信机器人

2021-09-24 07:55 UTC, lijiarui commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
It seems you didn't modify `WECHATY_PUPPET`：这里填 `Ipad` 协议 here

2021-09-24 07:55 UTC, lijiarui commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +- 输入网址: <https://api.chatie.io/v0/hosties/your_token_at_here>，例如我输入的地址就是这个: <https://api.chatie.io/v0/hosties/puppet_padlocal_210c112ddf9b49fdaa8242b87b83b0eb>
I think you should change `puppet_padlocal_210c112ddf9b49fdaa8242b87b83b0eb` to `puppet_padlocal_XXXX`, or you token will be leaked to all of the developers.

2021-09-24 11:15 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +`WECHATY_PUPPET`：这里填 `Ipad` 协议
已修改

2021-09-24 11:15 UTC, Gan-lang commented on jekyll/_contributors/gan-lang.md
> +a student
已修改

2021-09-24 11:15 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +  - blog
已修改

2021-09-24 11:15 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +先前在本社区看到一篇关于怎么使用 `python`-`wechaty`+`paddlehub`+阿里云白嫖一个智能微信机器人，
已修改

2021-09-24 11:15 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +- 输入网址: <https://api.chatie.io/v0/hosties/your_token_at_here>，例如我输入的地址就是这个: <https://api.chatie.io/v0/hosties/puppet_padlocal_210c112ddf9b49fdaa8242b87b83b0eb>
已修改

2021-09-26 11:16 UTC, lijiarui requested changes

2021-09-26 11:16 UTC, lijiarui commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +先前在本社区看到一篇关于怎么使用 `python`-`wechaty`+`paddlehub`+阿里云白嫖一个智能微信机器人，出自[https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun]
Change to:

```
[用python-wechaty+paddlehub+阿里云白嫖一个智能微信机器人](https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun/)
```

2021-09-26 11:16 UTC, lijiarui commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +- [https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun]
Change to the following:

```
- [PaddleHub官网](https://www.paddlepaddle.org.cn/hub)
- [python-wechaty](https://github.com/wechaty/python-wechaty)
- [python-wechaty-getting-started](https://github.com/wechaty/python-wechaty-getting-started)
- [手把手教你用python-wechaty+paddlehub+阿里云白嫖一个智能微信机器人](https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun)
```

2021-09-26 11:39 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +- [https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun]
已修改

2021-09-26 11:39 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +先前在本社区看到一篇关于怎么使用 `python`-`wechaty`+`paddlehub`+阿里云白嫖一个智能微信机器人，出自[https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun]
已修改

2021-09-26 12:21 UTC, merged

2021-09-26 13:58 UTC, Gan-lang commented on jekyll/_posts/2021-09-21-how-to-get-an-automatic-message-forwarding-weixin-chatbot-with-python-wechaty-aliyun.md
> +- [https://wechaty.js.org/2021/06/08/how-to-get-a-weixin-chatbot-with-python-wechaty-and-paddlehub-and-aliyun]
I expect I can get a Long-term TOKEN to learn.

2021-09-26 14:11 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited Gan-lang to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _**ruirui_0914**_  and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!