OSPP 2021-期中报告-开发基于微信实现微信会员&活动管理的微信小程序
wechaty/docusaurus pull request #1308
Opened 2021-09-23 07:01 UTC by mangguo188

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-09-23 07:18 UTC, lijiarui commented
You should keep commit here: https://github.com/wechaty/wechaty.js.org/pull/1240

2021-09-23 07:22 UTC, mangguo188 commented
> @mangguo188 你应该在这里继续提交：#1240

我已经将#1240关闭了

2021-09-23 08:31 UTC, lijiarui commented
Please get your mentor's approval first.

2021-09-23 09:26 UTC, atorber approved these changes

2021-09-23 16:35 UTC, atorber commented
@mangguo188 Some checks were not successful，please check carefully before submitting.

2021-09-23 16:40 UTC, atorber commented
> @mangguo188 Some checks were not successful，please check carefully before submitting.

# Subtest: tags for project category
        not ok 1 - "jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md" has category "project":    it's tags should contain one of "automotive,devops,ecommerce,ecosystem,education,entertainment,finance,game,healthcare,hospitality,insurance,media,other,productivity,real-estate,social,travel,utility"     Learn more from Issue #710: Enforce blog posts with category "project" to contain one of the tags      Url: https://github.com/wechaty/wechaty.js.org/issues/710
          ---
          at:
            line: 168
            column: 15
            file: file:///home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/tag.spec.ts
            type: Test
          stack: |
            Test.<anonymous> (file://tests/jekyll/tag.spec.ts:168:15)
          ...

2021-09-24 04:13 UTC, atorber approved these changes

2021-09-24 04:13 UTC, atorber approved these changes

2021-09-24 07:34 UTC, lijiarui requested changes

2021-09-24 07:34 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +  - other
What is `other` tag here mean?

2021-09-24 07:34 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +项目仓库: <https://github.com/wechaty/wechaty.js.org/pull/1090>
I don't think this is a project repo link. Please change the correct project repo.

2021-09-24 07:34 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +{% include iframe.html src="https://youtu.be/MoNLKnT2rJ8" %}
Please add a Chinese version video as other students did.

2021-09-24 07:34 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +{% include iframe.html src="https://youtu.be/oYcoOLfbgdE" %}
Please add a Chinese version video as other students did.

2021-09-24 08:15 UTC, atorber commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +{% include iframe.html src="https://youtu.be/oYcoOLfbgdE" %}
Hi， @lijiarui jiarui,I'm very sorry, because of the personal time arrangement, did not give a good review and guidance as mentor. I will try to improve in the remaining time.
 At the same time, @mangguo188 ChenJing to carefully modify according to the comments.

2021-09-24 09:01 UTC, lijiarui requested changes

2021-09-24 09:01 UTC, lijiarui commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +- 项目链接：<https://github.com/wechaty/summer/issues/1090>
This link is a dead link...

2021-09-25 03:09 UTC, atorber commented on jekyll/_posts/2021-08-29-ospp-mid-term-club-managment.md
> +- 项目链接：<https://github.com/wechaty/summer/issues/1090>
@mangguo188  <https://github.com/wechaty/summer/issues/1090>

2021-09-26 06:23 UTC, lijiarui approved these changes

2021-09-26 06:24 UTC, merged