Update faq.md
wechaty/docusaurus pull request #1321
Opened 2021-09-29 13:01 UTC by chris-4444

Edited and formatted.

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-09-29 13:32 UTC, Rohitesh-Kumar-Jain approved these changes

2021-09-30 11:54 UTC, proudofsimin approved these changes

2021-10-16 18:05 UTC, lijiarui approved these changes

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +  - [Cannot log in using WeChat account](#11-i-can-not-login-with-my-wechat-account)
It seems the link can not go to the correct place.

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +- Wechaty also supports protocols other than Web APIs, such as **PadChat**. Learn more about it [here](https://github.com/wechaty/wechaty/issues/1296).
Please change 
```
- Wechaty also supports protocols other than Web APIs, such as **PadChat**. Learn more about it [here](https://github.com/wechaty/wechaty/issues/1296). 
```

to the following

```
In order to fix this problem, Wechaty also support protocols other than Web APIs, such as:
- [Ipad protocol: PadLocal](http://wechaty.js.org/docs/puppet-services/padlocal)
- [Windows protocol: xp](https://github.com/wechaty/wechaty-puppet-xp)
```

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +- **@ someone in the room**: We plan to support this in the future and provide solutions other than Web API.
We already support mention (**@ someone in the room**) in [Ipad protocol: PadLocal](http://wechaty.js.org/docs/puppet-services/padlocal) and [WeCom Solution: WxWork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +- **Send Share Card**: We plan to support this in the future and provide solutions other than Web API.
We already support Send Share Card in [Ipad protocol: PadLocal](http://wechaty.js.org/docs/puppet-services/padlocal) and [WeCom Solution: WxWork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +- **Send Voice**: We plan to support this in the future and provide solutions other than Web API.
We already support Send Voice in [Ipad protocol: PadLocal](http://wechaty.js.org/docs/puppet-services/padlocal)

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +- **At the moment**: We haven't decided yet whether to support such functions.
Please change to 

```
- **At the moment**: We are planning to support this, see: https://github.com/wechaty/wechaty/issues/1880
```

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +Not at the moment but we plan to provide support in the future.
We already support this in [Ipad protocol: PadLocal](http://wechaty.js.org/docs/puppet-services/padlocal) and [WeCom Solution: WxWork](http://wechaty.js.org/docs/puppet-services/wxwork)

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +Currently, Wechaty only supports personal account created in Wechaty.
Please change `Currently, Wechaty only supports personal account created in Wechaty.`  to the following:

```
Yes, Wechaty already supports WeChat Official Account, see: 
- GitHub Repo: https://github.com/wechaty/wechaty-puppet-official-account
- Intro: http://wechaty.js.org/docs/puppet-providers/official-account
```

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +The plugins are named `XXXPuppet`; like `PuppetPuppeteer` is using the Chrome puppeteer to control the WeChat Web API via the Chrome browser; `PuppetPadchat` is using the WebSocket protocol to connec
PuppetPuppeteer --> PuppetWechat

PuppetPadchat --> PuppetPadLocal

2021-10-16 18:05 UTC, lijiarui commented on docusaurus/docs/explanations/faq.md
> +In order **not** to be blocked by wechat, we add a queue in Wechaty. For more information, refer to [rx-queue](https://github.com/zixia/rx-queue).
Please change the link to https://github.com/huan/rx-queue

2021-10-16 18:05 UTC, lijiarui requested changes
Please change as I request.

2021-10-28 17:58 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +- Wechaty also supports protocols other than Web APIs, such as **PadChat**. Learn more about it [here](https://github.com/wechaty/wechaty/issues/1296).
Changed

2021-10-28 18:02 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +- **@ someone in the room**: We plan to support this in the future and provide solutions other than Web API.
Edited bullet point

2021-10-28 18:03 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +- **Send Share Card**: We plan to support this in the future and provide solutions other than Web API.
Edited bullet point.

2021-10-28 18:03 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +- **Send Voice**: We plan to support this in the future and provide solutions other than Web API.
Edited bullet point.

2021-10-28 18:17 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +- **At the moment**: We haven't decided yet whether to support such functions.
Edited bullet point

2021-10-28 18:21 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +Not at the moment but we plan to provide support in the future.
Edited statement.

2021-10-28 18:27 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +Currently, Wechaty only supports personal account created in Wechaty.
Changed as requested

2021-10-28 18:28 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +In order **not** to be blocked by wechat, we add a queue in Wechaty. For more information, refer to [rx-queue](https://github.com/zixia/rx-queue).
Changed link

2021-10-28 18:31 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +The plugins are named `XXXPuppet`; like `PuppetPuppeteer` is using the Chrome puppeteer to control the WeChat Web API via the Chrome browser; `PuppetPadchat` is using the WebSocket protocol to connec
Changed names as requested

2021-10-28 19:21 UTC, nibble0101 commented on docusaurus/docs/explanations/faq.md
> +  - [Cannot log in using WeChat account](#11-i-can-not-login-with-my-wechat-account)
Added correct links.

2021-10-28 19:22 UTC, nibble0101 approved these changes
LGTM

2021-11-07 12:48 UTC, nibble0101 commented
> Please change as I request.

@lijiarui  Can you please have a look at this again?

2021-11-17 02:47 UTC, shraddhavp approved these changes
LGTM

2022-03-30 11:49 UTC, huan commented
Close this PR because it has not no any activities for months.

2022-03-30 11:49 UTC, closed without merging