OSPP 2021: final report of wechaty-cli
wechaty/docusaurus pull request #1322
Opened 2021-09-30 01:00 UTC by chinggg

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-10-05 13:35 UTC, lijiarui commented
Thanks for the post!

In order to make sure your changes have not broken anything, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-10-06 20:26 UTC, huan requested changes
Looking forward to watch your video presentation with live coding!

2021-10-06 20:26 UTC, huan commented on jekyll/_posts/2021-09-30-ospp-final-cli.md
> +“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的
Please:

1. Add the project introduction at the beginning of this blog post
2. Move the OSPP 2021 introduction to the end of this blog post.

2021-10-07 15:04 UTC, chinggg commented on jekyll/_posts/2021-09-30-ospp-final-cli.md
> +“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的
Sorry for the late response, I have been back to university today. You can believe that the final report will be improved as expected and requested since I have done the same things twice this summer 🤣  
Are you and @lijiarui in agreement with the format? I put OSPP 2021 introduction at the beginning just as the [template of midterm  report offered by SoW guide](https://wechaty.js.org/2021/06/24/summer-wechaty-guide/) requests. There is no template for final report in that post, but many others' final reports in this year and last year put OSPP 2021 introduction at the beginning. 
For the purpose of clear summary, I agree with you on the adjustment. @lijiarui What is your opinion?

2021-10-08 06:52 UTC, lijiarui commented on jekyll/_posts/2021-09-30-ospp-final-cli.md
> +“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的
@chinggg You can follow the latest requirement here:  [OSPP 学生开发者工作指导](https://github.com/wechaty/summer#ospp-%E5%AD%A6%E7%94%9F%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E4%BD%9C%E6%8C%87%E5%AF%BC)

The latest template is here: https://github.com/wechaty/summer/blob/master/iscas-open-source-promotion-plan/template/final-term-template.md

2021-10-08 09:04 UTC, lijiarui requested changes

2021-10-08 09:04 UTC, lijiarui commented on jekyll/_posts/2021-09-30-ospp-final-cli.md
> +
Please:

1. Add a live coding demo for the blog
2. Add Chinese version video link as template request.

2021-10-09 09:48 UTC, lijiarui commented
Please get your mentor approval first @huan

2021-10-10 17:52 UTC, lijiarui commented
ping @huan

2021-10-12 07:15 UTC, chinggg commented
ping @huan @lijiarui. I hope OssChat will send a message to Wechat groups to remind him of this PR.

2021-10-12 08:44 UTC, lijiarui commented
@chinggg Maybe you can message him via WeChat.

2021-10-13 05:58 UTC, huan approved these changes
LGTM

Thank your very much for sharing this great blog post!

2021-10-13 08:29 UTC, lijiarui approved these changes

2021-10-13 08:29 UTC, merged

2021-10-13 09:32 UTC, huan commented
link to

- https://github.com/wechaty/summer/issues/80