人类的本质是复读机 - 可能是世界上最无聊的机器人
wechaty/docusaurus pull request #1329
Opened 2021-10-02 18:56 UTC by BurgerBurglar

Hello @huan,  the previous PR #1316 was closed because I couldn't figure out how to solve the CLA bug. 

I've fixed the formatting issues and updated the asset file extensions to `.webp`. Thank you for your time and happy National Day.

2021-10-03 19:54 UTC, huan commented
Happy National Day to you too!

2021-10-04 04:22 UTC, BurgerBurglar commented
well this is kinda annoying. the tests cannot be done locally as on Windows machines, path separators are "\" and will fail the CI directly. I have to push and wait for someone else to trigger the CI, and new errors just pop up every time :/

2021-10-04 04:30 UTC, huan commented
Yes, our filename linter is not compatible with the Windows system.

If there's anyone who can fix it, a PR will be welcome.

BTW: you can use https://github.com/wechaty/PMC/issues/13 after you join our Wechaty org.

2021-10-04 05:16 UTC, huan commented
I'd like to suggest that you can just push new commits to this PR because force push is not a good practice and we can not see the history changes.

2021-10-04 05:47 UTC, huan requested changes
Congratulations on passing the CI!

Please follow my reviews, after you get them done then this PR will be ready to be merged.

2021-10-04 05:47 UTC, huan commented on jekyll/_contributors/shuo.md
> +avatar: /assets/contributors/shuo/avatar.webp
Please change your contributor name to be as same as your GitHub username: `burgerburglar` because we will enforce it in the future.

2021-10-04 05:47 UTC, huan commented on jekyll/_posts/2021-09-28-the-stupidest-bot-ever-created.md
> +categories: article
change categories to: `project`

2021-10-04 05:47 UTC, huan commented on jekyll/_posts/2021-09-28-the-stupidest-bot-ever-created.md
> +  - 娱乐
1. Remove Chinese tag names.
2. Add a tag: `entertainment`

2021-10-04 05:47 UTC, huan commented on jekyll/_posts/2021-09-28-the-stupidest-bot-ever-created.md
> +<img src="/assets/2021/09-the-stupidest-bot-ever-created/135126765-5be9bbac-6e08-4f0a-975a-cb4b2eeeb14c.webp" width="500"/>
Never use HTML tag in markdown.

use Markdown syntax to include your image.

2021-10-04 05:47 UTC, huan commented on jekyll/_posts/2021-09-28-the-stupidest-bot-ever-created.md
> +<img src="/assets/2021/09-the-stupidest-bot-ever-created/135121653-34fcaa7d-7212-41a5-95df-da48095a095b.webp" width="500"/>
Change the image filename to be a meaningful name, instead of a UUID.

2021-10-04 13:57 UTC, BurgerBurglar commented on jekyll/_posts/2021-09-28-the-stupidest-bot-ever-created.md
> +<img src="/assets/2021/09-the-stupidest-bot-ever-created/135126765-5be9bbac-6e08-4f0a-975a-cb4b2eeeb14c.webp" width="500"/>
The picture is too big and doesn't look good without applying some CSS on it.

2021-10-04 14:02 UTC, huan commented on jekyll/_posts/2021-09-28-the-stupidest-bot-ever-created.md
> +<img src="/assets/2021/09-the-stupidest-bot-ever-created/135126765-5be9bbac-6e08-4f0a-975a-cb4b2eeeb14c.webp" width="500"/>
That's the point.

We always enforce checking the image file size, by parsing the markdown.

2021-10-04 16:16 UTC, huan commented on jekyll/_contributors/shuo.md
> +avatar: /assets/contributors/shuo/avatar.webp
What we enforced is not the name property, but the filename: 

```diff
- jekyll/_contributors/shuo.md 
+ jekyll/_contributors/burgerburglar.md 
```

2021-10-04 16:18 UTC, huan requested changes
Thanks for following my reviews and change requests!

I believe this PR is good to be merged after renaming the contributor file name to be the same as your GitHub username.

2021-10-05 03:42 UTC, BurgerBurglar commented
@huan thank you for your comment. I've just added the latest commits from `main` - please trigger the CI again and we shall be able to merge it soon.

2021-10-05 06:28 UTC, merged

2021-10-05 06:29 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited 田鼠 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!