OSPP 2021：the report of final term
wechaty/docusaurus pull request #1331
Opened 2021-10-03 06:14 UTC by zzzyer

2021-10-05 13:42 UTC, lijiarui commented
Please get your mentor's approval first.

@Roxanne718

2021-10-05 13:57 UTC, zzzyer commented
项目地址：https://github.com/wechaty/summer/issues/82

2021-10-05 14:03 UTC, lijiarui commented
Please get your mentor's approval first.

2021-10-05 15:11 UTC, wj-Mcat approved these changes
LGTM

2021-10-06 10:29 UTC, lijiarui requested changes
It looks strange about your blog file name, please remove `_20211003134518` in the file name.

2021-10-06 16:25 UTC, huan requested changes
There are two working in process PR in your project:

- https://github.com/wechaty/wechaty-puppet-official-account/pull/27
- https://github.com/wechaty/wechaty-puppet-official-account/pull/24

Please make sure to pass the CI and get approval from your mentor, by working on them continuously.

2021-10-06 16:27 UTC, huan commented
@wj-Mcat I don't think this PR can be approved because it contains 3 different files under the `_posts/` folder, which is obviously a mistake.

And also, please help our students to get to know how to make their PRs to be merged in the project repo: there's also left lots of problems in her PR, which makes that PR useless.

2021-10-08 01:50 UTC, zzzyer commented
> 
> 
> It looks strange about your blog file name, please remove `_20211003134518` in the file name.

Sorry，i have deleted these files.

2021-10-08 03:20 UTC, lijiarui commented
> @wj-Mcat I don't think this PR can be approved because it contains 3 different files under the `_posts/` folder, which is obviously a mistake.
> 
> And also, please help our students to get to know how to make their PRs to be merged in the project repo: there's also left lots of problems in her PR, which makes that PR useless.

As @huan said, only when @wj-Mcat re-approves this PR by the comment `approved`, then I will keep review this PR.

2021-10-08 07:27 UTC, zzzyer commented
> 
> 
> There are two working in process PR in your project:
> 
>     * [wechaty/wechaty-puppet-official-account#27](https://github.com/wechaty/wechaty-puppet-official-account/pull/27)
> 
>     * [wechaty/wechaty-puppet-official-account#24](https://github.com/wechaty/wechaty-puppet-official-account/pull/24)
> 
> 
> Please make sure to pass the CI and get approval from your mentor, by working on them continuously, before you can submit your final project report.

I have committed a new  PR and passed npm test

2021-10-09 10:00 UTC, lijiarui commented
Please get your mentor @wj-Mcat approval as soon as possible.

2021-10-10 05:42 UTC, wj-Mcat approved these changes
LGTM

2021-10-10 17:49 UTC, lijiarui commented
@huan How do you think of this PR?

2021-10-10 17:51 UTC, lijiarui requested changes

2021-10-10 17:51 UTC, lijiarui commented on jekyll/_posts/2021-10-03-ospp-final-term-wechaty-puppet-oa.md
> +{% include iframe.html src="/assets/2021/10-ospp-final-term-wechaty-puppet-oa/final-term-ppt.pdf" %}
I think you should add contact info here as template requested: https://github.com/wechaty/summer/blob/master/iscas-open-source-promotion-plan/template/final-term-template.md

2021-10-11 01:17 UTC, zzzyer commented on jekyll/_posts/2021-10-03-ospp-final-term-wechaty-puppet-oa.md
> +{% include iframe.html src="/assets/2021/10-ospp-final-term-wechaty-puppet-oa/final-term-ppt.pdf" %}
Done

2021-10-11 03:35 UTC, lijiarui commented on jekyll/_posts/2021-10-03-ospp-final-term-wechaty-puppet-oa.md
> +{% include iframe.html src="/assets/2021/10-ospp-final-term-wechaty-puppet-oa/final-term-ppt.pdf" %}
Are you sure it is done?

Where is the content info?

2021-10-11 07:13 UTC, zzzyer commented on jekyll/_posts/2021-10-03-ospp-final-term-wechaty-puppet-oa.md
> +{% include iframe.html src="/assets/2021/10-ospp-final-term-wechaty-puppet-oa/final-term-ppt.pdf" %}
I'm sorry, , I had a mistake in understanding before, and now I have added contact info.Is it right？

2021-10-11 12:21 UTC, lijiarui commented
@zzzyer Thanks for the update, please get @huan approval, then I will review this PR.

2021-10-13 08:34 UTC, lijiarui commented
ping @zzzyer How is this project going on?

2021-10-13 08:47 UTC, wj-Mcat commented
ping @huan 

> @zzzyer Thanks for the update, please get @huan approval, then I will review this PR.

2021-10-13 09:08 UTC, zzzyer commented
> 
> 
> ping @zzzyer How is this project going on?

I have made some changes and I am waiting for @huan reply

2021-10-13 12:23 UTC, huan commented
@zzzyer The two PRs that I have mentioned before were all closed (instead of being merged).

Please update your PR and let me know your updates.

2021-10-14 02:35 UTC, wj-Mcat approved these changes
LGTM

2021-10-14 02:38 UTC, huan approved these changes
LGTM


Could you please link the PR link with your weekly report with a brief introduction?

It will make the report more detail.

Thank you very much for participating in OSPP summer 2021 project, I hope you enjoy it.

Cheers!

2021-10-14 03:04 UTC, wj-Mcat commented
ping @zzzyer

2021-10-14 08:33 UTC, zzzyer commented
> 
> 
> ping @zzzyer


Thank you for helping me link the issue link.

2021-10-14 09:05 UTC, wj-Mcat commented
@lijiarui All changes, including your request changes, have been done, so this pr is ready to be merged. Please help us to merge it.

2021-10-14 11:39 UTC, zzzyer reviewed
review changes

2021-10-14 11:57 UTC, zzzyer reviewed
delete irrelevant files

2021-10-14 12:39 UTC, lijiarui approved these changes

2021-10-14 12:39 UTC, merged