OSPP 2021-结项报告-基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet
wechaty/docusaurus pull request #1336
Opened 2021-10-05 14:31 UTC by lyleshaw

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-10-05 14:32 UTC, ly1ex commented
明日上传视频后更新视频链接～

2021-10-05 15:12 UTC, wj-Mcat approved these changes
LGTM

2021-10-05 15:16 UTC, lyleshaw commented
项目地址：wechaty/summer#75

2021-10-06 10:21 UTC, lijiarui requested changes
Good job! Looking forward to  [wechaty-puppet-cq](https://github.com/lyleshaw/wechaty-puppet-cq)! Cheers!

Please:
1. Change as I request
2. Add Chinese version video link as soon as possible.

2021-10-06 10:21 UTC, lijiarui commented on jekyll/_posts/2021-10-05-ospp-final-term-wechaty-itchat-puppet.md
> +  - 产出2：PyPi 包：[https://pypi.org/project/wechaty-puppet-itchat/](https://pypi.org/project/wechaty-puppet-itchat/)，已可以正常使用
Please add your mentor (@wj-Mcat and @huan  ) as Maintainers to https://pypi.org/project/wechaty-puppet-itchat

2021-10-06 10:29 UTC, lyleshaw commented on jekyll/_posts/2021-10-05-ospp-final-term-wechaty-itchat-puppet.md
> +  - 产出2：PyPi 包：[https://pypi.org/project/wechaty-puppet-itchat/](https://pypi.org/project/wechaty-puppet-itchat/)，已可以正常使用
> Please add your mentor (@wj-Mcat and @huan ) as Maintainers to https://pypi.org/project/wechaty-puppet-itchat

Done~

2021-10-06 10:33 UTC, lijiarui commented on jekyll/_posts/2021-10-05-ospp-final-term-wechaty-itchat-puppet.md
> +  - 产出2：PyPi 包：[https://pypi.org/project/wechaty-puppet-itchat/](https://pypi.org/project/wechaty-puppet-itchat/)，已可以正常使用
Good job! When will you add the Chinese version video link? 

Only when you add a Chinese version link, then I would merge this PR.

2021-10-06 10:36 UTC, lyleshaw commented on jekyll/_posts/2021-10-05-ospp-final-term-wechaty-itchat-puppet.md
> +  - 产出2：PyPi 包：[https://pypi.org/project/wechaty-puppet-itchat/](https://pypi.org/project/wechaty-puppet-itchat/)，已可以正常使用
> Good job! When will you add the Chinese version video link?
> 
> Only when you add a Chinese version link, then I would merge this PR.

I'll try my best to complete the video release tonight (due to my PyCharm license expired and internet speed problems, there may be a delay)

2021-10-06 10:47 UTC, lijiarui commented
It seems your PR failed the test, please make GitHub action green first.

2021-10-06 10:55 UTC, ly1ex commented
> It seems your PR failed the test, please make GitHub action green first.

I'll update PDF file to pass CI soon

2021-10-07 09:32 UTC, ly1ex commented
> It seems your PR failed the test, please make GitHub action green first.

@lijiarui 

I have some questions about `assets-pdf-size.spec.ts`.

It requires `PDF size should be fit for the web (no more than 3MB)`, but at the same time it says `the maximum limitation: size<=1048576`.

I have tried my best to compress my PDF to 2.4MB, it seems that I have no way to compress it to 1MB.

2021-10-08 03:10 UTC, lijiarui commented
Hey @lyleshaw 

I guess there is a typo here about 3MB, it should be less than 1MB. We will appreciate if you can create a PR for us:

```
It requires PDF size should be fit for the web (no more than 3MB), but at the same time, it says the maximum limitation: size<=1048576.
```

You can try one of these suggestions:

1. Use https://www.ilovepdf.com/compress_pdf to compress to less than 1MB.
2. Upload to [Google Slides](https://docs.google.com/presentation/u/0/) and use Google Slides to embed your pdf here.

2021-10-08 15:32 UTC, ly1ex commented
> Hey @lyleshaw
> 
> I guess there is a typo here about 3MB, it should be less than 1MB. We will appreciate if you can create a PR for us:
> 
> ```
> It requires PDF size should be fit for the web (no more than 3MB), but at the same time, it says the maximum limitation: size<=1048576.
> ```
> 
> You can try one of these suggestions:
> 
> 1. Use https://www.ilovepdf.com/compress_pdf to compress to less than 1MB.
> 2. Upload to [Google Slides](https://docs.google.com/presentation/u/0/) and use Google Slides to embed your pdf here.

Done

2021-10-09 09:34 UTC, lijiarui requested changes

2021-10-09 09:34 UTC, lijiarui commented on jekyll/_posts/2021-10-05-ospp-final-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/wechaty/python-wechaty-puppet-itchat>
You can add the pip package link here as well.

2021-10-10 14:05 UTC, ly1ex commented on jekyll/_posts/2021-10-05-ospp-final-term-wechaty-itchat-puppet.md
> +项目仓库: <https://github.com/wechaty/python-wechaty-puppet-itchat>
Done

2021-10-10 17:47 UTC, lijiarui approved these changes
Good job!

2021-10-10 17:47 UTC, merged