OSPP 2021-结项报告-基于 Wechaty 开发开源的二师兄社群逗乐机器人
wechaty/docusaurus pull request #1340
Opened 2021-10-06 14:57 UTC by ReiKohaku

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  
- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

2021-10-06 16:12 UTC, Valerieeeee approved these changes
LGTM

2021-10-08 02:42 UTC, lijiarui requested changes
Please change as I request.

2021-10-08 02:42 UTC, lijiarui commented on jekyll/_posts/2021-10-06-ospp-final-wechaty-piggy-bro.md
> +> Author: [@ReiKohaku](https://github.com/ReiKohaku)
Please remove this part as Mid-Term Demo Day requested.

See: https://docs.google.com/presentation/d/1rWd7aLozgPFyPiSbyxqw1GeGV2-NCGRKvDOUcq9VYcw/edit#slide=id.gec336ad374_1_327

2021-10-08 02:42 UTC, lijiarui commented on jekyll/_posts/2021-10-06-ospp-final-wechaty-piggy-bro.md
> +{% include iframe.html src="https://www.youtube.com/embed/51EwCNB_Y90" %}
Please add a Chinese version video link:

```
> 国内链接：<国内视频的链接>
```

2021-10-08 02:42 UTC, lijiarui commented on jekyll/_posts/2021-10-06-ospp-final-wechaty-piggy-bro.md
> +{% include iframe.html src="https://www.youtube.com/embed/Na9pGdf_6oY" %}
Please add a Chinese version video link:

```
> 国内链接：<国内视频的链接>
```

2021-10-09 09:54 UTC, lijiarui approved these changes
LGTM

2021-10-09 09:54 UTC, merged