OSPP Summer 2021:final term 5gChatbot
wechaty/docusaurus pull request #1343
Opened 2021-10-08 14:55 UTC by zrn-fight

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-10-08 15:35 UTC, zrn-fight commented
I'm so sorry that I didn't submit my blog within the specified time.

2021-10-09 09:31 UTC, lijiarui requested changes

2021-10-09 09:31 UTC, lijiarui commented on jekyll/_posts/2021-10-07-ospp-final-term-5g-chatbot-puppet.md
> +  - plan
Please remove plan tag here, since it is final-term now.

2021-10-09 09:31 UTC, lijiarui commented on jekyll/_posts/2021-10-07-ospp-final-term-5g-chatbot-puppet.md
> +项目仓库: <https://github.com/zrn-fight/wechaty-puppet-walnut>
Please move this repo to wechaty org as I requested at mid-term.

2021-10-10 13:58 UTC, zrn-fight commented
I have moved the repo to wechaty and modified the blog according to your suggestions. Would you please see what else needs to be modified?

2021-10-10 17:46 UTC, lijiarui requested changes
Also, please get @huan approval first

2021-10-10 17:46 UTC, lijiarui commented on jekyll/_posts/2021-10-07-ospp-final-term-5g-chatbot-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-walnut>
It seems you didn't pass GitHub action in the repo, please fix the CI first.

2021-10-20 00:36 UTC, zrn-fight commented
@huan Could you please review this pr?Thank you.

2021-10-20 09:59 UTC, lijiarui requested changes

2021-10-20 09:59 UTC, lijiarui commented on jekyll/_posts/2021-10-07-ospp-final-term-5g-chatbot-puppet.md
> +项目仓库: <https://github.com/wechaty/wechaty-puppet-walnut>
Please add the npm package link as well, and add @huan  and me as npm maintainers.

2021-10-20 11:30 UTC, zrn-fight commented
Done

2021-10-23 01:26 UTC, zrn-fight commented
@huan Could you please review this pr?Thank you.

2021-10-23 03:44 UTC, huan approved these changes
@zrn-fight Sorry for missing this PR

This PR is related your walnut project with two primary mentors: @lijiarui and @IronConrad , which I believe all you need is to get their approval and then I believe this PR is good to be merged.

**One should not put others as required/blocker without any good reason.**

However, your PR is LGTM. Thank you very much for your effort in participating OSPP'21!

2021-10-24 09:44 UTC, lijiarui approved these changes
LGTM

2021-10-24 09:44 UTC, merged