Update contributing2.md
wechaty/docusaurus pull request #1344
Opened 2021-10-10 10:21 UTC by chris-4444

Edited and formatted.

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-10-10 13:13 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/contributing/overview.md
> +The work on Wechaty itself falls into three (3) major areas:
Maybe we can add another one

```report bugs, suggest enhancements, requests features as Github issues.```

A subtle way of contributing can be by following and sharing  Wechaty content across social platforms like YT, gitter, etc.

2021-10-10 13:13 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/contributing/overview.md
> +The work on Wechaty itself falls into three (3) major areas:
What say?

2021-10-14 13:15 UTC, proudofsimin commented on docusaurus/docs/contributing/overview.md
> +Wechaty is a community that lives on its volunteers. As it keeps growing, we always need more people to help the users and the community. You can contribute in many ways, either to the framework itse
Wechaty is an open source software which is highly relied on volunteers to maintain. As we keep growing, we always welcome more people to join us. Please read through and abide by [Wechaty Community Code of Conduct](code-of-conduct.md).

2021-10-14 13:15 UTC, proudofsimin commented on docusaurus/docs/contributing/overview.md
> +relevant from time to time.
Documentation is one of the most important things that introduce Wechaty to general users. If you like teaching and sharing knowledge with other people, you are more than welcome to join our documentation project. Below are some ways you could contribute:

2021-10-15 12:48 UTC, chris-4444 reviewed
Included all suggestions, ty @Rohitesh-Kumar-Jain @proudofsimin. 😎

2021-10-16 06:09 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing my suggestions :)

2021-10-16 16:19 UTC, Rohitesh-Kumar-Jain commented
ping @nibble0101 and @proudofsimin

2021-10-16 17:35 UTC, lijiarui requested changes

2021-10-16 17:35 UTC, lijiarui commented on docusaurus/docs/contributing/overview.md
> +For more information, you may contact rui@Wechaty.io.
Please change the email from `rui@Wechaty.io` to `wechaty@googlegroups.com`

2021-10-16 17:35 UTC, lijiarui commented on docusaurus/docs/contributing/overview.md
> +For more information, you may contact rui@Wechaty.io.
Please change the email from `rui@Wechaty.io` to `wechaty@googlegroups.com`

2021-10-16 17:35 UTC, lijiarui commented on docusaurus/docs/contributing/overview.md
Add mailing list:

```
- Join Wechaty Mailing List: Send an email to wechaty@googlegroups.com, then you are in!

- Join Wechaty WeChat Room: If you want to talk with other developers via WeChat, just scan the [QR Code](https://github.com/wechaty/wechaty#join-us) in WeChat with secret code wechaty, join our Wechaty Developers' Home.


```

2021-10-16 17:35 UTC, lijiarui commented on docusaurus/docs/contributing/overview.md
Please add the following information:

```
## Know more about Wechaty

- [Wechaty Blog](https://wechaty.js.org/blog/)
- [Wechaty Contributors List](https://wechaty.js.org/contributors/): Get all of Wechaty contributor profiles/
- [Meeting Notes](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.64c95c3y2l4v)： We use meeting notes to record all of the meetings
- [Branding Guides](https://wechaty.js.org/docs/marketing/branding/)： How to use Wechaty logo and other materials
- [YouTube](https://www.youtube.com/playlist?list=PL8hd9KDTdarDXf_Rxtr8meKhxtgcXMInh)： Wechaty video playlist.
- [Open Collective](https://opencollective.com/wechaty)： The only way to donate to Wechaty
- [Google Drive](https://drive.google.com/drive/folders/1KTnB3EOZo3nFRFSWoFc2-7LM7MgKQLzM)： Wechaty files
- [Photo Album](https://photos.google.com/share/AF1QipOWKUfUkjw-VzE0skrjmCwbwIWwuBiI7Li4UCbdXH62n8iH2ITnvDbPTsx4eBl8dw?key=cy1NdWFoUGpXanVmczVHSm84TVg1LXJWeW5HTDhR)： Wechaty photos
- [Hall of Fame](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.64c95c3y2l4v): Know people in Wechaty
```

2021-10-17 09:01 UTC, chris-4444 reviewed
Included all your suggestions. Thanks @lijiarui 😊

2021-10-17 15:17 UTC, lijiarui approved these changes
Good job！ Cheers！

2021-10-17 15:17 UTC, lijiarui commented
Please make GitHub action green then ：）

2021-10-20 15:12 UTC, proudofsimin approved these changes

2021-10-28 17:18 UTC, nibble0101 approved these changes
LGTM

2021-10-28 17:28 UTC, merged