Wechaty OSPP(开源之夏) Final Demo Day
wechaty/docusaurus pull request #1352
Opened 2021-10-13 11:58 UTC by socialok

---
title: "Wechaty OSPP(开源之夏) Final Demo Day"
author: juzibot
categories: announcement
tags:
  - summer-of-wechaty
  - summer-2021
  - talk
  - news
  - meetup
  - featured
image: /assets/2021/10-wechaty-soc-final-demo-day/final-demo-day.webp
---

“[开源软件供应链点亮计划-暑期2021](https://summer.iscas.ac.cn)”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。 学生可自主选择感兴趣的项目进行申请，并在中选后获得该软件资深维护者（社区导师）亲自指导的机会。 

Wechaty 作为中国最大的聊天机器人开源项目，合计发布了10个项目，共收到来自上海大学、华东理工大学、长沙理工大学、中国科学技术大学、电子科技大学等高校的几十份申请。 

此次的10个项目的学生开发者，均录制了一份路演视频，向社区介绍具体的项目进展和后续规划。
了按顺序播放视频，还会邀请社区导师和开发者进行评价和指导，并给出切实有效的建议。

此外，开发者们可以在路演日中找到自己感兴趣的项目，并在路演日结束后，与对应的开发者取得联系并在后续共同开发

开发者和项目地址：

- [Wechaty Open Source Promotion Plan 2021 Kickoff Meeting](https://wechaty.js.org/2021/06/24/wechaty-soc-kick-off-meeting/ )

- [项目地址](https://github.com/wechaty/summer/issues/79) 

## 结项汇报（Final-Term Demo Day）会议纪实

{% include iframe.html src="https://www.youtube.com/watch?v=xqJN3NmGukg"%}

### Agendas议程

- [0:08:30](https://youtu.be/xqJN3NmGukg?t=510) 1.介绍会议议程
- [0:10:30](https://youtu.be/xqJN3NmGukg?t=630) 2.陈婧：开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序
- [0:29:40](https://youtu.be/xqJN3NmGukg?t=1780) 3.肖良玉:基于 Itchat为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet    
- [0:46:50](https://youtu.be/xqJN3NmGukg?t=2810) 4.张瑞宁,邵琦:开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块
- [1:05:00](https://youtu.be/xqJN3NmGukg?t=3900) 5.马田慧:基于开放 API 封装 Wechaty 接口下的飞书聊天机器人
- [1:19:30](https://youtu.be/xqJN3NmGukg?t=4770) 6.刘靖:基于 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC）
- [1:34:00](https://youtu.be/xqJN3NmGukg?t=5640) 7.林宇靖，张瑞宁:基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善
- [1:51:00](https://youtu.be/xqJN3NmGukg?t=6660) 8.anaivebird:开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块
- [2:21:30](https://youtu.be/xqJN3NmGukg?t=8490) 9.zzzyer:基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善 
- [2:42:40](https://youtu.be/xqJN3NmGukg?t=9760) 10.井维嘉: 基于Wechaty 开发开源的二师兄社群逗乐机器人
- [3:09:56](https://youtu.be/xqJN3NmGukg?t=11396) 11.总结

You can learn more from our [meeting_notes](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#)

## Wechaty 期末项目列表

Wechaty 在多平台、多功能多个维度上，共发布了 10 项任务，并通过 issue 的方式进行每周的更新。
如果你有看到感兴趣的项目，可以直接在对应 issue 下面找到负责对应任务的开发者。

你可以在查看[首次KickOff博客](https://wechaty.js.org/2021/06/24/wechaty-soc-kick-off-meeting/)了解更多信息。

### 基于开放API封装 Wechaty 接口下的飞书聊天机器人 

- 导师： 范蕊 飞书Puppet作者 （froxanne1024@gmail.com）
- 学生开发者：梁浩彬，华南农业大学本科生（xilou31@gmail.com）；马田慧（tianhuima01@gmail.com）；许欣瑜（3378374880@qq.com）；张凯（840854995@qq.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/38>

{% include iframe.html src="https://youtu.be/-HOF0LV1d54" %}

### 基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善 

- 导师：yswtrue Wechaty contributor （yswtrue@gmail.com），李卓桓 Creator of Wechaty，Tencent TVP of Chatbot （zixia@zixia.net）
- 学生开发者：林宇靖, 上海海洋大学本科生（545641826@qq.com）；张瑞宁, 长沙理工大学本科生（3134191406@qq.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/59>

{% include iframe.html src="https://www.youtube.com/watch?v=3j3BGRnoVtE" %}

### 开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块 

- 导师：康嘉 硬核桃社区PM （sj-kangj@dimpt.com）；李佳芮 Wechaty co-creator，Founder & CEO of Juzi.BOT （rui@chatie.io）
- 学生开发者：张瑞宁，长沙理工大学本科生（3134191406@qq.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/74>

{% include iframe.html src="https://www.youtube.com/watch?v=cQydTnaym7Y" %}

### 基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet 

- 导师：吴京京 Python Wechaty creator，Wechaty committer （wjmcater@gmail.com）；李卓桓 Wechaty creator，Python Wechaty maintainer，Tencent TVP of Chatbot （zixia@zixia.net）
- 学生开发者：肖良玉，杭州电子科技大学本科生（x@lyleshaw.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/75>

{% include iframe.html src="https://www.youtube.com/watch?v=SKhgnRaljzk" %}

### 开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 

- 导师：鲁玉超 物联网行业产品经、微信小程序群组大师开发者 （atorber@163.com）
- 学生开发者：陈婧，华东理工大学本科生（1017137803@qq.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/78>

{% include iframe.html src="https://www.youtube.com/watch?v=eSgaD32njVw" %}

### 基与 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC） 

- 导师：李卓桓 Creator of Wechaty，Tencent TVP of Chatbot （zixia@zixia.net）
- 学生开发者：刘靖，上海大学本科生（liuchinggg@gmail.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/80>

{% include iframe.html src="https://youtu.be/PssH9epe0tU" %}

### 开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块 

- 导师：李佳芮 Wechaty co-creator，Founder & CEO of Juzi.BOT （rui@chatie.io）；李卓桓 Creator of Wechaty，Tencent TVP of Chatbot （zixia@zixia.net）
- 学生开发者：胡星武（huxingwu@gmail.com）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/81>

{% include iframe.html src="https://www.youtube.com/watch?v=Z2IIPe0FLA4" %}

### 基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善 

- 导师：吴京京 Python Wechaty creator，Wechaty committer （wjmcater@gmail.com）
- 学生开发者：左雁茹，中国科学技术大学研究生（zuoyanru@mail.ustc.edu.cn）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/82>

{% include iframe.html src="https://www.youtube.com/watch?v=ySxpkKjv018" %}

### 基于Wechaty 开发开源的二师兄社群逗乐机器人 

- 导师：王玉丹 Wechaty Contributor，AI Chatbot Wechaty x PaddleHub UP主，Wechaty社区大使 （huangaszaq@gmail.com）；鲁玉超 物联网行业产品经、微信小程序群组大师开发者 （atorber@163.com）；韩磊 百度飞桨PPDE，飞桨上海领航团团长 （iregisteru@163.com）
- 学生开发者：肖诗诗，电子科技大学本科生（me@mrxiao.net）
- 项目介绍：<https://github.com/wechaty/summer-of-wechaty/issues/83>

{% include iframe.html src="https://youtu.be/Na9pGdf_6oY" %}

## 欢迎正在阅读的你参与其中

虽然“暑期2021”的报名已经结束，但Wechaty社区依然欢迎正在阅读本篇内容的你参与到暑期2021的工作中来。
以下是几种可能的参与方式：

- 时刻跟进Wechaty SoC项目的每周例行更新Issue，并直接与相关负责导师和学生开发者取得联系，和他们交流相关进展。
- 在 Wechaty 开发者群内，为学生开发者们的Plan Blog、POC Blog和Finished Blog点赞和提出想法。
- 直接参与已经完成部分工作的项目开发，为学生开发者们负责的复杂项目添砖加瓦。

> 作者: [juzibot](https://github.com/juzibot/)

2021-10-13 11:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1352) <br/>All committers have signed the CLA.

2021-10-13 21:53 UTC, lijiarui commented
Thanks for your post!

In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-10-13 21:57 UTC, lijiarui requested changes

2021-10-13 21:57 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +### 基于开放API封装 Wechaty 接口下的飞书聊天机器人
All of the information is the wrong one, please correct the result as meeting notes showed: 
https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.xdrnd37ekiek


- [陈婧] 开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序	
- [肖良玉] 基于 Itchat 为 Python Wechaty 实现社区首个 Python 语言的本地 Puppet	
- [张瑞宁,邵琦] 开发支持电信运营商 5G Chatbot / RCS 的 Wechaty 接入 Puppet 模块 
- [马田慧] 基于开放 API 封装 Wechaty 接口下的飞书聊天机器人
- [刘靖] 基于 Blessed 的 Wechaty 命令行文本客户端软件（仿IRC）
- [林宇靖，张瑞宁] 基于 Matrix AppService Wechaty 项目的用户、群与消息等基础功能的完善（视频可开启字幕）
- [anaivebird] 开发支持 QQ 聊天软件的 Wechaty Puppet Provider 模块
- [左雁茹] 基于 Wechaty Puppet Official Account 项目的用户与消息等基础功能的完善 
- [井维嘉] 基于Wechaty 开发开源的二师兄社群逗乐机器人

2021-10-14 02:24 UTC, Valerieeeee requested changes
Please make the changes as mentioned.

2021-10-14 02:24 UTC, Valerieeeee commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +- 导师：王玉丹 Wechaty Contributor，AI Chatbot Wechaty x PaddleHub UP主，Wechaty社区大使 （huangaszaq@gmail.com）；鲁玉超 物联网行业产品经、微信小程序群组大师开发者 （atorber@163.com）；韩磊 百度飞桨PPDE，飞桨上海领航团团长 （iregisteru@163.com）
王玉丹 email：（valeriewyd@gmail.com)

2021-10-14 02:24 UTC, Valerieeeee commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +- 学生开发者：肖诗诗，电子科技大学本科生（me@mrxiao.net）
学生need to be changed to：井维嘉，海南大学，[@ReiKohaku](https://github.com/ReiKohaku)

2021-10-14 02:36 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +### 基于开放API封装 Wechaty 接口下的飞书聊天机器人
OK，thanks for checking.

2021-10-14 03:00 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +- 导师：王玉丹 Wechaty Contributor，AI Chatbot Wechaty x PaddleHub UP主，Wechaty社区大使 （huangaszaq@gmail.com）；鲁玉超 物联网行业产品经、微信小程序群组大师开发者 （atorber@163.com）；韩磊 百度飞桨PPDE，飞桨上海领航团团长 （iregisteru@163.com）
OK，thanks for checking.

2021-10-14 03:01 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +- 学生开发者：肖诗诗，电子科技大学本科生（me@mrxiao.net）
OK，thanks for checking.

2021-10-14 03:56 UTC, socialok reviewed
已修改部分错误

2021-10-14 08:22 UTC, lijiarui requested changes

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +  - featured
Please add the `ospp-admin` tag here as https://github.com/wechaty/summer#%E5%B7%A5%E5%85%B7%E5%8C%85 requested.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +Wechaty 作为中国最大的聊天机器人开源项目，合计发布了10个项目，共收到来自上海大学、华东理工大学、长沙理工大学、中国科学技术大学、电子科技大学等高校的几十份申请。
10个项目 --> 9 个项目

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +此次的10个项目的学生开发者，均录制了一份路演视频，向社区介绍具体的项目进展和后续规划。
10个项目 --> 9 个项目

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=xqJN3NmGukg"%}
Please add video chapters at [Youtube link](https://www.youtube.com/watch?v=xqJN3NmGukg) as [Wechaty Way](https://wechaty.js.org/2021/06/23/the-wechaty-way/) requested, see more: [To add your own video chapters:](https://support.google.com/youtube/answer/9884579?hl=en):

![image](https://user-images.githubusercontent.com/6419514/137277058-85982ec7-1bc9-4711-b345-383a0d96c174.png)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +Wechaty 在多平台、多功能多个维度上，共发布了 10 项任务，并通过 issue 的方式进行每周的更新。
10 项任务 --> 9 项

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=eSgaD32njVw" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=SKhgnRaljzk" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=cQydTnaym7Y" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://youtu.be/-HOF0LV1d54" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://youtu.be/PssH9epe0tU" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=3j3BGRnoVtE" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=Z2IIPe0FLA4" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=ySxpkKjv018" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://youtu.be/Na9pGdf_6oY" %}
Please add a video topic for the video.

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +
Please add the student's final term blog as well. Here is the blog list: [期末报告](https://github.com/wechaty/summer/issues/79#issuecomment-934160505)

2021-10-14 08:22 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +> 作者: [juzibot](https://github.com/juzibot/)
Please remove the author here, because you have already added the author at the head of the blog.

2021-10-15 06:36 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +  - featured
👌

2021-10-15 06:36 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +Wechaty 作为中国最大的聊天机器人开源项目，合计发布了10个项目，共收到来自上海大学、华东理工大学、长沙理工大学、中国科学技术大学、电子科技大学等高校的几十份申请。
👌

2021-10-15 06:37 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +此次的10个项目的学生开发者，均录制了一份路演视频，向社区介绍具体的项目进展和后续规划。
👌

2021-10-15 08:46 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +Wechaty 在多平台、多功能多个维度上，共发布了 10 项任务，并通过 issue 的方式进行每周的更新。
OK

2021-10-15 09:10 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=eSgaD32njVw" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=SKhgnRaljzk" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=cQydTnaym7Y" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://youtu.be/-HOF0LV1d54" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://youtu.be/PssH9epe0tU" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=Z2IIPe0FLA4" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=ySxpkKjv018" %}
OK

2021-10-15 09:12 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://youtu.be/Na9pGdf_6oY" %}
OK

2021-10-15 09:20 UTC, socialok commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +> 作者: [juzibot](https://github.com/juzibot/)
OK

2021-10-16 17:13 UTC, lijiarui requested changes

2021-10-16 17:13 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +Wechaty 作为中国最大的聊天机器人开源项目，合计发布了10个项目，共收到来自上海大学、华东理工大学、长沙理工大学、中国科学技术大学、电子科技大学等高校的几十份申请。
You should change as I request instead of just reply 👌 here.

2021-10-16 17:13 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +此次的10个项目的学生开发者，均录制了一份路演视频，向社区介绍具体的项目进展和后续规划。
You should change as I request instead of just reply 👌 here.

2021-10-25 07:56 UTC, socialok commented
已修改完之前提到的问题

2021-10-26 16:08 UTC, lijiarui requested changes
Please change as I requested.

And, it would be better you can add some tips from https://github.com/wechaty/summer in this blog since we will publish this blog to ospp official as well!

2021-10-26 16:08 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=eSgaD32njVw" %}
Have you change as requested?

2021-10-26 16:08 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +- 期末报告：<https://wechaty.js.org/2021/09/29/final-term-club-managment/>
Please add the report title for the report, instead just put link on it.

eg: 

```
[OSPP 2021-结项报告-开发基于Wechaty实现微俱乐部会员&活动管理的微信小程序](https://wechaty.js.org/2021/09/29/final-term-club-managment)
```

2021-10-26 16:08 UTC, lijiarui commented on jekyll/_posts/2021-10-09-summer-2021-wechaty-soc-final-demo-day.md
> +- 期末报告：<https://wechaty.js.org/2021/10/05/ospp-final-term-wechaty-itchat-puppet/>
Please add the report title for the report, instead just put link on it.

2021-10-27 08:08 UTC, socialok commented
done

2021-10-28 06:06 UTC, lijiarui commented
@socialok Please add a live coding video as well.

2021-10-28 12:53 UTC, socialok commented
Done

2021-10-31 13:01 UTC, lijiarui approved these changes
LGTM

2021-10-31 13:01 UTC, merged

2021-12-04 11:41 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited socialok to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _**ruirui_0914**_  and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!