added a maodou blog
wechaty/docusaurus pull request #138
Opened 2019-07-19 07:18 UTC by limingth

- [*] Add Blog Header, including title, author, date.
e.g.
```
---
layout: post
title: "如何用PadPro实现发送微信小程序"
author: limingth, zhaoic
date: '2019-07-18 09:00:00 +0800'
---

> 作者: [limingth](https://github.com/limingth)，[zhaoic](https://github.com/zhaoic) 毛豆网

**内容纲要**  
* 毛豆课堂项目背景介绍  
* 如何用PadPro实现发送微信小程序  
* 进一步需要完成的工作  

```

[See more](https://github.com/Chatie/blog#contribute-guideline)

2019-07-19 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Chatie/blog?pullRequest=138) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Chatie/blog?pullRequest=138) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Chatie/blog?pullRequest=138) it.</sub>

2019-07-19 17:18 UTC, huan commented
Thank you very much for the great blog post article!

However, we need to fix some minor issue before we can merge it:

1. Please save all the images to the `/download/2019` directory, so that we will make sure that we can load the image from our own server in the future.
1. Please sign the CLA.

I'll be able to merge it after all the above had been done.

Have a nice weekend!

2019-07-19 17:19 UTC, huan requested changes
Please follow my comments.

2019-07-20 01:03 UTC, limingth commented
@huan  those 2 requests are done!

2019-07-20 03:27 UTC, huan requested changes
Please change the url link from hardcoded to generated by jekyll because we are going to change the site configuration today.

2019-07-20 03:27 UTC, huan commented on _posts/2019-07-18-send-miniprogram-using-padpro.md
> +![毛豆课堂演示](../download/2019/maodou-ketang-demo.png)
The download-able file URLs might be changed according to different configurations.

For example, your blog post url might be:

1. `https://blog.chatie.io/send-miniprogram-using-padpro/`, or
1. `https://blog.chatie.io/blog/send-miniprogram-using-padpro/`

Like the above, two URLs demonstrated that the blog post url might at the first or the second depth of url, but the `download` directory will always at `https://blog.chatie.io/download`.

So please change your file address like the following diff shows:

Please change this line:

```diff
- [毛豆课堂演示](../download/2019/maodou-ketang-demo.png)
+ [毛豆课堂演示]({{ '/download/2019/maodou-ketang-demo.png' | relative_url }})
```

2019-07-20 06:30 UTC, merged

2019-07-20 06:31 UTC, huan commented
I prepare to start working on the blog right now, so I will do the fix for you later.