彩虹屁机器人 开心每一天
wechaty/docusaurus pull request #1385
Opened 2021-11-03 15:17 UTC by livingbody

```
title: 彩虹屁机器人     开心每一天
author: Livingbody
categories: article
```

2021-11-03 15:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1385) it.</sub>

2021-11-04 05:15 UTC, huan commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +  - rainbow-fart
Please add a `python` tag to your post so that it can be searched by tag `python`

2021-11-04 05:16 UTC, huan commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +categories: article
The category of this post will be better to use `project` because it's introducing your open source project.

2021-11-04 05:41 UTC, lijiarui requested changes

2021-11-04 05:41 UTC, lijiarui commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +![](https://ai-studio-static-online.cdn.bcebos.com/df042d8661e2466ab923b30a224c4c6888443c9f600a451a964ddc8d28011428)
Please localize all of the images in case of a future 404 error.

2021-11-04 05:41 UTC, lijiarui commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +![](https://ai-studio-static-online.cdn.bcebos.com/6433c5be0f8a4a888fb792712e62abd0194fa91fd958473e9398697aa7c1ccaf)
Please localize all of the images in case of a future 404 error.

2021-11-04 13:42 UTC, livingbody commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +  - rainbow-fart
OK

2021-11-05 05:10 UTC, livingbody commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +categories: article
project added

2021-11-08 02:50 UTC, livingbody commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +![](https://ai-studio-static-online.cdn.bcebos.com/df042d8661e2466ab923b30a224c4c6888443c9f600a451a964ddc8d28011428)
done

2021-11-08 02:50 UTC, livingbody commented on jekyll/_posts/2021-11-03-Rainbow-fart-wechaty-robot.md
> +![](https://ai-studio-static-online.cdn.bcebos.com/6433c5be0f8a4a888fb792712e62abd0194fa91fd958473e9398697aa7c1ccaf)
done

2021-11-13 05:32 UTC, huan requested changes

2021-11-13 05:32 UTC, huan commented on jekyll/_posts/2021-11-03-rainbow-fart-wechaty-robot-project.md
> +<iframe width='1000', height='800' src="//player.bilibili.com/player.html?aid=291932794&bvid=BV19f4y157NL&cid=377824174&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullsc
Please use `{% include iframe.html src="" %}` instead of HTML.

2021-11-13 05:32 UTC, huan commented on jekyll/_posts/2021-11-03-rainbow-fart-wechaty-robot-project.md
> +![img](/assets/2021/11-rainbow-fart-wechaty-robot-project/a7cc431a0f2244aea6e24213b238a15adbfbb5c0da204080b765b708bbf7987c.webp)
Please rename the images file name to some meaningful words instead of a random string.

2021-11-16 11:48 UTC, huan commented on jekyll/_posts/2021-11-03-rainbow-fart-wechaty-robot-project.md
> +![img](/assets/2021/11-rainbow-fart-wechaty-robot-project/a7cc431a0f2244aea6e24213b238a15adbfbb5c0da204080b765b708bbf7987c.webp)
thanks for the renaming

2021-11-22 05:04 UTC, huan commented
@wj-Mcat could you please take a look at this PR and see if you can help @livingbody to pass our CI test? Because it's based on Python Wechaty and seems that the CI is very close to being able to turn green.

2022-03-30 11:47 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> [](https://github.com/wechaty)You've invited livingbody to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

2022-03-30 11:47 UTC, merged

2022-03-30 11:47 UTC, huan commented
Merge  this PR for preparint

- #1501