juzibot-期初报告-信息管理机器人-机器人与部分算法实现
wechaty/docusaurus pull request #1404
Opened 2021-11-22 06:42 UTC by AquaIndigo

juzibot信息管理机器人，包括信息收集、管理、搜索、标签分析全文搜索等功能。

独立项目，基于wechaty，会兼容wechaty支持的各种平台，实现多平台信息管理。

2021-11-22 06:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1404) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1404) it.</sub>

2021-11-24 03:04 UTC, hcfw007 reviewed
I think you should add a link to your project in the contributor bio, and add some contact info (at least github homepage).

2021-11-24 04:42 UTC, hcfw007 commented on jekyll/_contributors/aquaindigo.md
> +
add a link to your project here

2021-11-24 07:54 UTC, AquaIndigo commented on jekyll/_contributors/aquaindigo.md
> +
But it's private actually.

2021-11-24 09:33 UTC, hcfw007 commented on jekyll/_contributors/aquaindigo.md
> +
OK, then maybe add a link to your new blog

2021-11-24 17:17 UTC, hcfw007 approved these changes

2021-11-24 17:17 UTC, hcfw007 approved these changes

2021-11-26 06:32 UTC, lijiarui commented
Thanks for your post!

In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-11-26 06:57 UTC, AquaIndigo commented
> 

Thank you! And I tried that and passed all the tests yesterday.

2021-11-26 06:58 UTC, AquaIndigo commented
> Thanks for your post!
> 
> In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.
> 
> ```shell
> npm install
> npm test
> ```
> 
> See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

Thank you! And I tried that and passed all the tests yesterday.

2021-11-26 07:11 UTC, lijiarui commented
Thanks for making CI green, could you add a proposal video to demonstrate the project and your plan?

You can refer to this blog: https://wechaty.js.org/2021/05/12/gsod-2021-volunteering-proposal/

2021-11-30 01:25 UTC, AquaIndigo commented
> Thanks for making CI green, could you add a proposal video to demonstrate the project and your plan?
> 
> You can refer to this blog: https://wechaty.js.org/2021/05/12/gsod-2021-volunteering-proposal/

Hi, I've done that.

2021-11-30 02:20 UTC, huan commented on jekyll/_contributors/aquaindigo.md
> +
Please notice that at the Wechaty community, we are only accepting blog posts for **open-source** projects.

2021-11-30 10:09 UTC, AquaIndigo commented on jekyll/_contributors/aquaindigo.md
> +
> 

OK, and I've made the critical codes public.

2021-11-30 11:27 UTC, lijiarui requested changes

2021-11-30 11:27 UTC, lijiarui commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +  - other
Please remove `other` tag here.

2021-11-30 11:29 UTC, lijiarui requested changes

2021-11-30 11:29 UTC, lijiarui commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +{% include iframe.html src="https://www.youtube.com/watch?v=jX9B4IW1xbo" %}
Thanks for the video, could you add the video slides in the blog as well?

You can insert like this:
{% include iframe.html src="pdf链接" %}

2021-11-30 14:43 UTC, lijiarui requested changes

2021-11-30 14:43 UTC, lijiarui commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +{% include iframe.html src="https://github.com/juzibot/intern/files/7625693/proposal.pdf" %}
Please localize this file instead of putting it outside the site, in case of a future 404 error.

2021-11-30 15:25 UTC, AquaIndigo commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +{% include iframe.html src="https://github.com/juzibot/intern/files/7625693/proposal.pdf" %}
The file is too large to upload because of the size limitation.

2021-12-01 10:46 UTC, lijiarui requested changes

2021-12-01 10:46 UTC, lijiarui commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +  - 提供了OCR、keyword extraction、object detection等功能的web api [OCR](https://github.com/deepdialog/docker-ocr-api)、[keyword extraction](https://github.com/deepdialog/docker-keywords-api)、[object detection
We should not put private repo in the blog, because others only get a 404 error when they click this link.

2021-12-02 01:35 UTC, lijiarui requested changes

2021-12-02 01:35 UTC, lijiarui commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +- 项目地址: <https://github.com/deepdialog/JuziBot>
Please link the intern issue link as well, thanks.

2021-12-02 01:48 UTC, lijiarui requested changes

2021-12-02 01:48 UTC, lijiarui commented on jekyll/_posts/2021-11-21-juzi-ai-lab-plan-algo.md
> +- 工作进度详见 <https://github.com/juzibot/intern/issues/5>
工作进度详见 --> 任务描述

2021-12-02 09:50 UTC, lijiarui approved these changes
LGTM

2021-12-02 10:11 UTC, lijiarui approved these changes
Good job! Cheers！

2021-12-02 12:16 UTC, huan approved these changes
LGTM

I hope we can read more code from you in the future!

2021-12-04 10:35 UTC, merged

2021-12-04 10:42 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited AquaIndigo to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _**ruirui_0914**_  and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!