基于5G消息的Wechaty Puppet模块的设计于实现
wechaty/docusaurus pull request #1406
Opened 2021-11-23 15:42 UTC by Bibabo-BUPT

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-11-23 15:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1406) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1406) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1406) it.</sub>

2021-11-26 06:33 UTC, lijiarui commented
Thanks for your post!

In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-11-30 11:23 UTC, lijiarui requested changes
Could you add a proposal video to demonstrate the project and your plan?

You can refer to this blog: https://wechaty.js.org/2021/05/12/gsod-2021-volunteering-proposal/

2021-11-30 11:23 UTC, lijiarui commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +
Please add `puppet-walnut` tag as well.

2021-11-30 11:23 UTC, lijiarui commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +  - 5g_message
change `5g_message ` to `5G`

2021-11-30 11:59 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +  - 5g_message
Upper case is not allowed in tags.

2021-12-01 01:54 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +- 学生：张嘉璐
It's better to up your name before mine.

2021-12-01 01:57 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +- 阶段列表
It's better to use `###` replace `-` for sub-title.

2021-12-01 01:57 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +- 计划安排:
ditto

2021-12-01 02:00 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +
Please add puppet-walnut Github link here.

2021-12-01 02:02 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +- 项目名称：基于5g消息的Wechaty Puppet模块的设计于实现
Please change all `5g` by `5G`, not includes `tags`.

2021-12-01 08:12 UTC, su-chang commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +- 项目名称：基于5G消息的Wechaty Puppet模块的设计于实现
Please fix the typo

2021-12-01 09:05 UTC, su-chang approved these changes, later dismissed
@lijiarui  LGTM

2021-12-01 10:52 UTC, lijiarui requested changes

2021-12-01 10:52 UTC, lijiarui commented on jekyll/_posts/2021-11-23-wechaty-puppet-based-on-5g-message.md
> +{% include iframe.html src="https://www.bilibili.com/video/BV1nq4y1z7AK/" %}
I suggest we use the youtube link as the primary link here, you can add bilibili link as an option here. Since wechaty is an international open-source project.

2021-12-01 12:20 UTC, Bibabo-BUPT reviewed
ok

2021-12-01 12:59 UTC, huan requested changes
1. Your audio quality is too low in your video, need to be fixed
2. The presentation needs slides/deck to make your points clear. need to be added.
3. The front camera needs to be open so that you can appear in your presentation. From all our GSoD and Summer 2020/2021 practice, we are always requiring the presentation video to keep the front camera open so that the presenter can show themselves in the video.

2021-12-05 12:23 UTC, su-chang commented
> The presentation needs slides/deck to make your points clear. need to be added.

@Bibabo-BUPT please make sure you have changed as @huan request.

BTW,  these is a lot of background noise in your video.

2021-12-07 09:58 UTC, su-chang commented
@Bibabo-BUPT ping

2021-12-16 14:50 UTC, su-chang commented
@Bibabo-BUPT ping

2022-01-05 10:58 UTC, lijiarui commented
Close this PR since @Bibabo-BUPT long time no reply.

Feel free to open this PR at any time.

2022-01-05 10:58 UTC, closed without merging