KevinTung patch 1
wechaty/docusaurus pull request #1407
Opened 2021-11-24 01:46 UTC by KevinTung

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-11-24 01:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1407) it.</sub>

2021-11-30 11:20 UTC, lijiarui requested changes
Please:

1. resolve the conflict and make CI green
2. add video intro in this blog

2021-11-30 11:20 UTC, lijiarui commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +
Please use markdown to insert images into the blog.

2021-12-14 06:38 UTC, KevinTung commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +
Fixed

2021-12-14 06:39 UTC, KevinTung commented
> Please:
> 
> 1. resolve the conflict and make CI green
> 2. add video intro in this blog

1. I resolved the conflict
2. Can I post this initial blog first?  I will then add my video intro to my mid-term blog.

2021-12-14 15:19 UTC, huan commented on package.json
> +    "file-name-linter": "^1.1.0"
I don't think this modification is necessary?

2021-12-16 08:32 UTC, KevinTung commented on package.json
> +    "file-name-linter": "^1.1.0"
yes, I should delete this

2021-12-16 08:40 UTC, KevinTung reviewed
resolved conflicts

2021-12-16 09:13 UTC, qhduan requested changes

2021-12-16 09:13 UTC, qhduan commented on jekyll/_contributors/kevintung.md
> +bio: hi~
这里还是改认真一点

2021-12-16 09:13 UTC, qhduan commented on jekyll/_posts/2021-11-11-sales-assistant.md
> +<!-- ![01](/assets/2021/11-sales-assistant/01.webp)
已经不需要的注释删一下

2021-12-16 09:27 UTC, KevinTung commented on jekyll/_contributors/kevintung.md
> +bio: hi~
fixed

2021-12-16 09:27 UTC, KevinTung commented on jekyll/_posts/2021-11-11-sales-assistant.md
> +<!-- ![01](/assets/2021/11-sales-assistant/01.webp)
fixed

2021-12-16 15:16 UTC, KevinTung commented
I found that I mistakenly merged the main repo into my repo.  After a hard reset, I found that I could only create a new branch , sales-mid-term, and created a new PR.

2021-12-16 15:16 UTC, closed without merging