Wechaty puppet 5g report
wechaty/docusaurus pull request #1408
Opened 2021-11-25 05:51 UTC by fabian4

post my report about puppet 5g

2021-11-25 05:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1408) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1408) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1408) it.</sub>

2021-11-25 06:03 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +- 联系方式：
duplicate content in contributor.

2021-11-25 06:04 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +  - 5g
lets change all `5g` to `5G`

2021-11-25 06:07 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +- 目标计划
Duplicate with `计划安排`, please simplify your aim.

2021-11-26 06:32 UTC, lijiarui commented
Thanks for your post!

In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-11-28 03:07 UTC, su-chang approved these changes

2021-11-28 11:39 UTC, lijiarui commented
Could you add a proposal video to demonstrate the project and your plan?

You can refer to this blog: https://wechaty.js.org/2021/05/12/gsod-2021-volunteering-proposal/

2021-11-30 11:16 UTC, lijiarui requested changes
Please add a video introduction as soon as possible, or you may fail to this report.

2021-11-30 11:16 UTC, lijiarui commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +  - 5g
@su-chang Please make sure your student change as your request, then you can approve the PR.

2021-11-30 11:16 UTC, lijiarui commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +  - ecosystem
Please add `puppet-walnut` tag as well

2021-11-30 11:16 UTC, lijiarui commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +- 代码地址：<https://github.com/fabian4/puppet-5G>
Please change to the official code link here.

2021-11-30 11:40 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +  - 5g
Upper case is not allowed in `tags`, so revert `5G` to `5g`.

2021-11-30 11:43 UTC, fabian4 commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +  - 5g
@lijiarui  `5g` may fail the test because the Upper case word is not allowed in the tag as the rule says

2021-11-30 11:45 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +  - 目前已经基本调试了所有的api接口，实现基本功能。
Please make all punctuation marks be consistent.

2021-11-30 11:49 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +- 学生：鲍耀龙
It's better to up your name before mine.

2021-11-30 12:23 UTC, su-chang approved these changes

2021-11-30 12:24 UTC, su-chang commented
@lijiarui LGTM

2021-11-30 12:43 UTC, su-chang commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +{% include iframe.html src="https://youtu.be/aPiqVq7e-VU" %}
The video is not sharp enough.

2021-11-30 12:55 UTC, fabian4 commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +{% include iframe.html src="https://youtu.be/aPiqVq7e-VU" %}
It seems fine on my side

2021-11-30 14:39 UTC, lijiarui submitted a review, later dismissed
LGTM

2021-12-01 12:41 UTC, huan requested changes
It's great to see your 5G Puppet blog post!

I believe everything is good except that the presentation is lacking the front camera video.

From all our GSoD and Summer 2020/2021 practice, we are always requiring the presentation video to keep the front camera open so that the presenter can show themselves in the video.

Please update your presentation video and then we will be able to merge your great PR.

Thank you very much.

2021-12-02 12:31 UTC, huan commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +{% include iframe.html src="https://youtu.be/O9wj-7aXh7s" %}
Please turn off "This action is turned off for content made for kids" on YouTube for this video, so that we can add it to our Wechaty play list.

2021-12-02 13:58 UTC, fabian4 commented on jekyll/_posts/2021-11-24-begin-term-wechaty-puppet-5g-report.md
> +{% include iframe.html src="https://youtu.be/O9wj-7aXh7s" %}
Sorry for that, I have changed it to your wish.
Now it is good to go.

2021-12-02 14:11 UTC, huan approved these changes
LGTM

I hope we can have a useable Puppet Walnut soon!

2021-12-04 11:54 UTC, lijiarui approved these changes

2021-12-04 11:55 UTC, merged

2021-12-04 12:01 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited fabian4 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _**ruirui_0914**_  and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!