Wechaty-puppet module based on Tiktok
wechaty/docusaurus pull request #1409
Opened 2021-11-25 09:29 UTC by YuSihe88

Wechaty-puppet module based on Tiktok   
   

 **title: Design and implementation of wechaty puppet module based on Tiktok**
    Subtitle: Yu Sihe - opening/Mid term report
    author: [YuSihe88](https://github.com/YuSihe88)
    mentor：[NickWang](https://github.com/hcfw007)
    Time: 27 / 09 / 2021 - 20 / 11 / 2021
    categories: project
    **tags:**
      - Typescript
      - TIKTOK
      - Wechaty
   

**Context**
We hope that our product can have more ability to access IM, Therefore, the first thing to bear the brunt is to enable wechaty to stably access more IM.

Tiktok is a popular short video software all over the world, but in addition to short video, it also has strong social attributes and provides social functions including single chat and group chat.
In order to enable wechaty users to send and receive messages using tiktok, it is necessary to develop the corresponding puppet access module.

**Goal**
During the internship, we hope to achieve the following objectives:
The messaging function needs to implement the most basic dingdong BOT, that is, the robot will automatically reply to Dong after receiving Ding
Need to support contact list and group list
The code needs to be hosted on GitHub

**Bot Basic information**
intelligent tiktok robot based on the platform of shaking table, providing an intelligent robot customer service system with sales, marketing and after-sale services. It helps the enterprise to get customers quickly, enhance user stickiness and improve transformation through intelligent dialogue, customer service system and data analysis. It covers education, retail, insurance and other industries.
* Application Name: chatbot
* Application type: Website application
* Application category: Social communication

**Project steps**
1, implement dingdong based on tiktok development platform.
2. Encapsulate the logic flow into a puppet
3. Add our newly encapsulated puppet to wechaty

**Current progress**
1. Achieve DingDong bot with TikTok Api

PS：For more detailed work progress and process, please refer to the following address：
https://github.com/juzibot/intern/issues/3
(Learn more about how to embed file/url in the post by reading this []
(https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)

**Plans**
* **Recent plan**
1. Read Puppet-Mock code and try to integrate DingDong into it.
2. (optional) base on that, implements room (group) control and message. (There is no room api in TikTok doc. I tried to consult the custom service but no result so far)

* **Long term plan**
1. Encapsulate the logic flow into a puppet
2. Add our newly encapsulated puppet to wechaty

2021-11-25 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=1409) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=1409) it.</sub>

2021-11-25 10:43 UTC, hcfw007 reviewed
Your blog is fine but not great. In my opinion, blog is more about self-expression. You should say more like why Tiktok-puppet is important, and how you work to achieve your goals so far. ( I saw ding-dong bot cost you lots of time, maybe something about that can make new comers an easier start). For now it's too much of a report than a blog.
However if it would take too much of your time, the current blog is good enough for me to pass.

2021-11-25 10:43 UTC, hcfw007 commented on jekyll/_contributors/yusihe88.md
> +
```suggestion
---
```
use another line to mark the end of info section.
Also please say something about yourself and mention how you contributed to wechaty.

2021-11-25 10:43 UTC, hcfw007 commented
One more thing, you should sign CLA before we can move on.

2021-11-26 06:32 UTC, lijiarui commented
Thanks for your post!

In order to make sure your changes have not broken anything and no need to wait for us to click `approve and run`, you can run the following commands before pushing your changes to GitHub.

```shell
npm install
npm test
```

See https://github.com/wechaty/wechaty.js.org#how-to-run-tests

2021-11-29 09:15 UTC, hcfw007 approved these changes
LGTM. @lijiarui

2021-11-30 11:12 UTC, lijiarui commented
@hcfw007 You should help your student to make CI green first, eg, resolve the conflict first.

2021-11-30 13:09 UTC, lijiarui requested changes
Thanks for your post, please change as I request.

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +Time: 27 / 09 / 2021 - 20 / 11 / 2021
This looks strange, please follow the blog template, thanks.

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +  - typescript
Please remove typescript tag here, since all of wechaty is typescript by default.

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +  - tiktok
Please add `puppet-tiktok` tag as well

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +image: /assets/2021/11-try-to-build-a-wechaty-tiktok-puppet/yusihe88-avatar.webp
Why are your trying adding your avatar as the blog teaser?

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +1, implement dingdong based on tiktok development platform.
1，--> 1.

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://youtu.be/N-Yswi7BnG4]
Please add video link as template required, instead of just adding a link like this.

2021-11-30 13:09 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://youtu.be/N-Yswi7BnG4]
Also, you can add your slides in the blog.

2021-12-01 07:21 UTC, hcfw007 approved these changes

2021-12-01 08:28 UTC, hcfw007 approved these changes

2021-12-01 10:25 UTC, lijiarui requested changes
Please change as I request, thanks!

2021-12-01 10:25 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +image: /assets/2021/11-try-to-build-a-wechaty-tiktok-puppet/ywechaty-tiktok-puppet.webp
You have a wrong image here, `ywechaty-tiktok-puppet.webp` please be more careful to this blog, or it will cause a 404 error.

2021-12-01 10:25 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +## video
As I suggested before, it would be be better to refer to this our GSoD Tech Writer blog: https://wechaty.js.org/2021/05/12/gsod-2021-volunteering-proposal/

So please change to `Proposal Video Presentation` as the title here.

2021-12-01 10:25 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +## Slides
Slides--> Proposal Slides

2021-12-01 10:25 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +  1. implement dingdong based on tiktok development platform.
I suggest you use the standard markdown, so please remove the useless blank before `1. `

You can change all of the markdowns writing styles in this blog.

2021-12-01 10:25 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +
Please link to the project issue, add your mentor and your name to the blog.

2021-12-01 10:28 UTC, YuSihe88 commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +image: /assets/2021/11-try-to-build-a-wechaty-tiktok-puppet/ywechaty-tiktok-puppet.webp
Sorry,I fixed it already

2021-12-01 10:30 UTC, YuSihe88 commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +
OK, I'll do it as fast as possible

2021-12-01 10:52 UTC, YuSihe88 commented
All problems found so far have been fixed

2021-12-01 11:40 UTC, lijiarui requested changes

2021-12-01 11:40 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://github.com/juzibot/intern/issues/]
Please  add the specified issue link instead of just add a general issue link.

2021-12-01 11:40 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://github.com/juzibot/intern/issues/]
Please  add the specified issue link instead of just add a general issue link.

2021-12-01 11:50 UTC, YuSihe88 commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://github.com/juzibot/intern/issues/]
OK~add already

2021-12-01 11:55 UTC, lijiarui requested changes

2021-12-01 11:55 UTC, lijiarui commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://github.com/juzibot/intern/issues/3]
I think you can change to:

`[基于TIKTOK的 Wechaty puppet 模块设计与实现](https://github.com/juzibot/intern/issues/3)`

2021-12-01 11:59 UTC, YuSihe88 commented on jekyll/_posts/2021-11-29-try-to-build-a-wechaty-tiktok-puppet.md
> +[https://github.com/juzibot/intern/issues/3]
Ok~change already

2021-12-01 12:26 UTC, lijiarui approved these changes
LGTM

2021-12-01 13:05 UTC, huan approved these changes
LGTM & Good job!

From your blog post, we can know that you have a very clear goal with plan steps, as well as your presentation is detailed enough which I can know that you do understand the puppet and have great progress on your work!

Please keep moving forward and I hope you will enjoy the Puppet development in the following weeks.

2021-12-01 13:06 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited YuSihe88 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

2021-12-02 01:37 UTC, merged