the first blog
wechaty/docusaurus pull request #1417
Opened 2021-11-30 15:35 UTC by IronConrad

the first blog ，to be a contributor

2021-12-03 07:31 UTC, IronConrad commented
fix something

2021-12-03 08:32 UTC, IronConrad reviewed
finish

2021-12-03 08:56 UTC, huan approved these changes, later dismissed
LGTM

Congratulations!

Thank you very much for the great effort in pushing 5G RCS (Chatbot) with the Wechaty ecosystem moving forward, it's a great way to help more and more chatbot developers move from Internet IM to Telecom SMS!

2021-12-03 14:16 UTC, lijiarui requested changes
Thanks for the post!

But I would like to request some changes to make the blog easier to find in the future.

2021-12-03 14:16 UTC, lijiarui commented on jekyll/_contributors/ironconrad.md
> +avatar: /assets/contributors/ironconrad/avatar.webp
It would be better if you could add your github link here.

2021-12-03 14:16 UTC, lijiarui commented on jekyll/_posts/2021-11-30-report-for-summer-2021.md
> +  - wechaty-puppet-walnut
Please add `5g`, `ospp`, `ospp-2021`,`summer-of-wechaty`,`summer-2021` tags as well.

2021-12-04 01:26 UTC, IronConrad reviewed
add something as jiarui wish

2021-12-04 01:26 UTC, IronConrad commented on jekyll/_posts/2021-11-30-report-for-summer-2021.md
> +  - wechaty-puppet-walnut
ok

2021-12-04 10:39 UTC, lijiarui approved these changes
Thanks！ Cheers！

2021-12-04 10:39 UTC, merged

2021-12-04 10:40 UTC, lijiarui commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited IronConrad to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _**ruirui_0914**_  and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!