wechaty-puppet-padlocal 实现初探
wechaty/docusaurus pull request #1438
Opened 2021-12-15 11:52 UTC by kkdev163

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-12-15 13:20 UTC, huan requested changes
Thank you very much for sharing these great analytics for the PadLocal with gRPC steps!

Please use the `permalink` as I commented, and then this PR will be able to be merged.

2021-12-15 13:20 UTC, huan commented on jekyll/_posts/2021-12-15-inner-glance-of-padlocal.md
> +- [PadLocalClientApi.login](https://github.com/padlocal/padlocal-client-ts/blob/master/src/PadLocalClientApi.ts#L24-L54)
I'd like to use the `Copy permalink` instead of `Copy lines` because the `permalink` will not be changed if the code base has been changed in the future.

For example, the permalink of the https://github.com/padlocal/padlocal-client-ts/blob/master/src/PadLocalClientApi.ts#L24-L54 is:

https://github.com/padlocal/padlocal-client-ts/blob/7ba679d78d13aeacb67969f0d817dbabf64f9c36/src/PadLocalClientApi.ts#L24-L54

![image](https://user-images.githubusercontent.com/1361891/146193433-0d16f0f5-6442-475b-bf7c-dc063cc9fcb5.png)

2021-12-15 23:18 UTC, kkdev163 commented on jekyll/_posts/2021-12-15-inner-glance-of-padlocal.md
> +- [PadLocalClientApi.login](https://github.com/padlocal/padlocal-client-ts/blob/master/src/PadLocalClientApi.ts#L24-L54)
Thanks for your advice, I' have replaced all previous link with permalink.

2021-12-16 12:19 UTC, kkdev163 commented
Hi @huan,  I have resolved all issue,  could this MR to be merged ?

2021-12-16 16:18 UTC, huan approved these changes
LGTM

Thank you very much for sharing your great insight!

2021-12-16 16:18 UTC, merged