Sales mid term blog
wechaty/docusaurus pull request #1439
Opened 2021-12-16 14:51 UTC by KevinTung

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-12-16 15:13 UTC, qhduan approved these changes
LGTM

2021-12-16 15:13 UTC, qhduan submitted a review, later dismissed
LGTM

2021-12-18 07:49 UTC, qhduan submitted a review, later dismissed

2021-12-18 11:58 UTC, lijiarui requested changes
Thanks for the post, please add a video and recording pdf for the blog.

2021-12-18 11:58 UTC, lijiarui commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +  <img src="/assets/2021/11-sales-assistant-bot/01.webp" style="zoom: 21%;" />
We should use markdown style here, instead of HTML code.

2021-12-18 11:58 UTC, lijiarui commented on jekyll/_posts/2021-12-14-sales-assistant-mid-term-progress.md
> +<center class="half">
We should use markdown style here, instead of HTML code.

2021-12-19 16:23 UTC, KevinTung commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +  <img src="/assets/2021/11-sales-assistant-bot/01.webp" style="zoom: 21%;" />
I used an HTML style for resizing images, which is hard to achieve in pure markdown style.  Besides, the HTML style seems to be pretty safe.

2021-12-19 16:23 UTC, KevinTung commented on jekyll/_posts/2021-12-14-sales-assistant-mid-term-progress.md
> +<center class="half">
I used an HTML style for resizing images, which is hard to achieve in pure markdown style. Besides, the HTML style seems to be pretty safe.

2021-12-22 07:29 UTC, KevinTung commented
> Thanks for the post, please add a video and recording pdf for the blog.
@lijiarui 
OK, I've added my video in the initial blog.  So now there are 2 blogs. The initial blog is for planning the whole project, and the second blog covers half of my work.  I expect the final blog to cover the remaining half of my work.

2022-01-05 11:14 UTC, lijiarui requested changes

2022-01-05 11:14 UTC, lijiarui commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +{% include iframe.html src="https://youtu.be/OHKxFKlIaIU" %}
Please add slides for the blog as well.

2022-01-05 11:14 UTC, lijiarui commented on jekyll/_posts/2021-12-14-sales-assistant-mid-term-progress.md
> +{% include iframe.html src="https://youtu.be/i45SQ4CrsdE" %}
Please add slides for the blog as well.

2022-01-26 09:18 UTC, zhihuifanqiechaodan approved these changes, later dismissed

2022-02-09 14:31 UTC, KevinTung commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +{% include iframe.html src="https://youtu.be/OHKxFKlIaIU" %}
Pdf is added

2022-02-09 14:31 UTC, KevinTung commented on jekyll/_posts/2021-12-14-sales-assistant-mid-term-progress.md
> +{% include iframe.html src="https://youtu.be/i45SQ4CrsdE" %}
Pdf is added

2022-02-09 15:19 UTC, lijiarui requested changes
Please change a more attractive title for the blog.

2022-02-09 15:19 UTC, lijiarui commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +title: sales-assistant 项目规划
Change to a readable Wechaty blog title, such as: 基于Wechaty打在一个销售助理机器人 -- 项目规划

2022-02-09 15:19 UTC, lijiarui commented on jekyll/_posts/2021-12-14-sales-assistant-mid-term-progress.md
> +title: sales-assistant 项目中期进展
Change to a readable Wechaty blog title, such as: 基于Wechaty打在一个销售助理机器人 -- 项目中期进展

2022-02-09 15:23 UTC, KevinTung commented on jekyll/_posts/2021-11-11-sales-assistant-bot.md
> +title: sales-assistant 项目规划
modified to 基于Wechaty的销售助理机器人 -- 项目规划

2022-02-09 15:25 UTC, lijiarui approved these changes, later dismissed
LGTM

2022-02-09 15:25 UTC, KevinTung commented on jekyll/_posts/2021-12-14-sales-assistant-mid-term-progress.md
> +title: sales-assistant 项目中期进展
modified to 基于Wechaty的销售助理机器人 -- 项目中期进展

2022-02-09 16:51 UTC, qhduan approved these changes

2022-02-09 16:52 UTC, qhduan approved these changes
LGTM

2022-02-10 03:46 UTC, lijiarui approved these changes
LGTM

2022-02-10 04:23 UTC, qhduan approved these changes
LGTM

2022-02-12 00:09 UTC, zhihuifanqiechaodan approved these changes

2022-02-12 07:06 UTC, qhduan approved these changes
LGTM

2022-02-12 07:06 UTC, qhduan approved these changes
LGTM

2022-02-15 09:08 UTC, zhihuifanqiechaodan approved these changes

2022-02-18 05:28 UTC, KevinTung commented
@huan , @qhduan 可以幫我 approve 一下嗎？謝謝

2022-02-18 05:31 UTC, huan approved these changes
LGTM

2022-02-18 05:32 UTC, huan commented
Thank you very much for sharing this great use case, it's very valuable!

2022-02-18 05:33 UTC, KevinTung commented
> 

Really appreciate!

2022-02-18 05:35 UTC, KevinTung commented
@huan I expect that this blog will be merged by you after these 3 approvals?

2022-02-18 05:38 UTC, huan commented
Yes, you can expect that when this PR has been updated to the latest version of the main branch.

I have help you to updated it, so you can wait for the CI passed then this PR will be merged if there has no failure.

2022-02-18 05:49 UTC, merged