commit my mid term wechaty-puppet-walnut report
wechaty/docusaurus pull request #1442
Opened 2021-12-21 07:46 UTC by fabian4

2021-12-22 04:01 UTC, su-chang commented
作为期中博客，内容过于单薄，需要补充一些重点实现的内容，方便大家更加了解5G消息。

最好能展示下使用 wechaty 调用目前已完成工作内容的示例代码，以及能实现的效果。

2021-12-22 07:36 UTC, su-chang requested changes

2021-12-22 07:36 UTC, su-chang commented on jekyll/_posts/2021-12-21-mid-term-wechaty-puppet-walnut-report.md
> +- 已经实现的puppet的封装，支持简单消息、位置消息等多样信息格式。
可以针对这个展开描述下

2021-12-30 03:01 UTC, su-chang commented
如果能在构建细节中结合5G消息的特色重点描述下会更好，方便大家通过博客内容了解5G消息的细节。

目前的内容看起来更偏向如何封装puppet，与标题略有偏差。

2022-01-04 06:03 UTC, su-chang submitted a review, later dismissed

2022-01-04 08:00 UTC, fabian4 commented
@lijiarui @huan ping

2022-01-05 11:03 UTC, lijiarui requested changes

2022-01-05 11:03 UTC, lijiarui commented on jekyll/Gemfile
> +gem "webrick", "~> 1.7"
Why do you change this file in this PR?

2022-01-06 07:31 UTC, lijiarui requested changes
It seems you are adding a empty file: `scripts/jekyll-serve.sh` I don't think this file is related with this PR.

2022-01-09 10:35 UTC, fabian4 commented
problem fixed @lijiarui

2022-01-12 04:24 UTC, lijiarui approved these changes
Good job!
LGTM, Cheeers!

2022-01-12 04:30 UTC, su-chang approved these changes

2022-01-12 04:57 UTC, fabian4 commented
ping @huan

2022-01-12 06:49 UTC, huan approved these changes
LGTM

Thank you very much for the sharing!

2022-01-12 07:11 UTC, merged