add myself to website contributors
wechaty/docusaurus pull request #1470
Opened 2022-02-08 11:05 UTC by ericcug

add myself to website contributors

2022-02-09 03:30 UTC, lijiarui requested changes

2022-02-09 03:30 UTC, lijiarui commented on jekyll/_contributors/ericcug.md
> +---
Please add your contribution link and more introduce of yourself to your profile,  thanks!

2022-02-09 12:44 UTC, ericcug commented on jekyll/_contributors/ericcug.md
> +---
More information has been added.

2022-02-11 11:00 UTC, lijiarui approved these changes
LGTM

2022-02-11 11:00 UTC, merged