Workpro basic doc
wechaty/docusaurus pull request #1505
Opened 2022-12-23 17:18 UTC by hcfw007

basic doc for workpro

2022-12-23 17:50 UTC, windmemory commented on docusaurus/docs/puppet-services/wxwork.md
> +WxWork is deprecated and will not receive any updates. Please switch to our latest service: WorkPro.
Let's add a link to the WorkPro page here.

2022-12-26 02:46 UTC, windmemory approved these changes, later dismissed
LGTM

2022-12-26 11:00 UTC, lijiarui requested changes

2022-12-26 11:00 UTC, lijiarui commented on docusaurus/docs/puppet-services/tokens.md
> +- WorkPro: contact [here](https://work.weixin.qq.com/kfid/kfcbfceaec6e8e30afe)
It seems strange here... It should change to a direct contact information....

2022-12-26 11:00 UTC, lijiarui commented on docusaurus/docs/puppet-services/workpro.md
> +- Repo: <https://github.com/RPAChat/workpro-getting-started>
@windmemory  should we use wechaty official getting started or RPAChat repo?

2022-12-26 11:00 UTC, lijiarui commented on docusaurus/docs/puppet-services/workpro.md
> +](https://github.com/wechaty/wechaty/issues/2462)
It seems there is an extra new line

2022-12-26 11:00 UTC, lijiarui commented on docusaurus/docs/puppet-services/workpro.md
> +Check out blogs with the `workpro` tag at <https://wechaty.js.org/tags.html#workpro>
I suggest adding workpro blog here since we only have one workpro blog now and it looks confusing when we use workpro tag to get workpro blog.

2022-12-26 11:05 UTC, windmemory commented on docusaurus/docs/puppet-services/workpro.md
> +- Repo: <https://github.com/RPAChat/workpro-getting-started>
I think we don't actually need a github repository here, we could reuse the `puppet-service` or `puppet-supports` repository for WorkPro.

2022-12-26 11:05 UTC, hcfw007 commented on docusaurus/docs/puppet-services/tokens.md
> +- WorkPro: contact [here](https://work.weixin.qq.com/kfid/kfcbfceaec6e8e30afe)
I did not quite understand 'direct contact information'. It's not very appropriate to put QRCode here, so I use this contact link.

2022-12-26 11:06 UTC, hcfw007 commented on docusaurus/docs/puppet-services/workpro.md
> +- Repo: <https://github.com/RPAChat/workpro-getting-started>
In WxWork page we were using getting-started from juzibot.So I use RPAChat repo here.

2022-12-26 11:08 UTC, windmemory commented on docusaurus/docs/puppet-services/workpro.md
> +Check out blogs with the `workpro` tag at <https://wechaty.js.org/tags.html#workpro>
We only have one blog for now, but we might have more blogs in the future, so in my opinion, using search result page with WorkPro tag makes sense here.

2022-12-27 03:27 UTC, lijiarui approved these changes
LGTM！ Cheers！

2022-12-27 03:27 UTC, merged