Feat/new doc
wechaty/docusaurus pull request #1520
Opened 2023-05-17 11:29 UTC by hcfw007

2023-05-22 23:19 UTC, iamrajiv submitted a review, later dismissed

2023-05-22 23:23 UTC, su-chang submitted a review, later dismissed

2023-05-23 06:25 UTC, su-chang commented
@hcfw007 please resolve the conflicts, thanks.

2023-05-23 08:32 UTC, hcfw007 commented
> @hcfw007 please resolve the conflicts, thanks.

The conflicts will be resolved once the i18n pr is merged...

2023-06-02 06:46 UTC, huan commented
Thanks for refactoring the docs with the API!

I'm still thinking about we should keep the original directory structure (`/api/` instead of the `wechaty-api`) and add the `create-puppet` to another folder because the `/api/` is for the Wechaty SDK users, and the `create-puppet` is for the Wechaty SDK developers.

Is there any reason strong enough to rename the `api` to `wechaty-api`? If not, let's thinking about how to use the original `api` folder, and find another better place for the `create-puppet` folder.

Thanks!

2023-06-02 07:12 UTC, hcfw007 commented
I changed the directory structure from ```api``` to ```wechaty-api``` because I thought there could be other documents to be appended, e.g. ```grpc-api```, ```puppet-api```, for those who wish to contribute to other projects.

As we moved ```puppet-api``` to ```create-puppet``` now, maybe we can change the name back to ```api```, and find better names for people wish to contribute to other wecahty projects?

2023-06-02 08:16 UTC, huan commented
Thanks for the explanation!

I understand the reason you change the name.

Could you please rename it back to `API`, and let's create another folder named `Puppet API` to contain other docs?

For this structure, the `API` will contain all the Wechaty API for end users, and the `Puppet API` will be the related API for Puppet Developers.

2023-06-02 10:11 UTC, hcfw007 commented
@huan I have change the dir structure according to your suggestion, and translated one of the pages. Please check it out.

2023-06-02 10:13 UTC, huan commented on docusaurus/docs/api/contact-self.md
Why do we remove this doc?

2023-06-02 10:14 UTC, huan commented
@hcfw007 Please get two approvals from our contributors before I dive into this big PR; thanks!

2023-06-02 11:10 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
done

2023-06-02 11:36 UTC, hcfw007 commented
> @hcfw007 Please get two approvals from our contributors before I dive into this big PR; thanks!

@su-chang @iamrajiv @windmemory

2023-06-02 11:40 UTC, su-chang approved these changes, later dismissed

2023-06-02 16:15 UTC, huan commented on docusaurus/docs/api/contact-self.md
May I know what's the reason removed it before?

2023-06-04 03:34 UTC, windmemory submitted a review, later dismissed
LGTM

2023-06-04 14:58 UTC, iamrajiv approved these changes

2023-06-04 14:58 UTC, iamrajiv submitted a review, later dismissed

2023-06-04 19:04 UTC, huan commented
Can we resolve the conflicts first before approve a PR? Thanks!

2023-06-05 02:58 UTC, hcfw007 commented
> Can we resolve the conflicts first before approve a PR? Thanks!

The conflicts are resolved.

I'd like to speak to defend these riviews. This PR is marked ready and I ping them to review on Jun 2, 2023, 7:36 PM GMT+8, and the room-invitation PR was accpeted and merged on Jun 3, 2023, 12:19 AM GMT+8.

2023-06-05 05:50 UTC, windmemory submitted a review, later dismissed
LGTM

2023-06-05 07:54 UTC, huan requested changes
I have reviewed a file and found lots of problems.

Let's solve them first.

Thank you very much.

2023-06-05 07:54 UTC, huan commented on docusaurus/docs/api/contact-self.md
> +title: Contact-Self
Please use the class name `ContactSelf` instead of the file name.

2023-06-05 07:54 UTC, huan commented on docusaurus/docs/api/contact-self.md
> +sidebar_label: ' Contact-Self'
Use class name as well.

2023-06-05 07:54 UTC, huan commented on docusaurus/docs/api/contact-self.md
> +Contact-Self is a special kind of contact. It represents bot self. It has all methods and properties of a regular contact, and some more. Every method that returns a ```ContactInterface```, if the co
We should keep using the class name. 

May I know why you change to the folder name `Contact-Self`?

2023-06-05 07:54 UTC, huan commented on docusaurus/docs/api/contact-self.md
> +const contact = await bot.Contact.find({id: 'contactId-0' }) // contact0
The `find` is inherited from the `Contact` class.

Why do we introduce this code example in the `ContactSelf` extended class?

2023-06-05 07:54 UTC, huan commented on docusaurus/docs/api/contact-self.md
> +static async find (query : string | PUPPET.filters.Contact): Promise<undefined | ContactInterface>
`find` here is a method from the parent class

2023-06-05 07:54 UTC, huan commented on docusaurus/docs/api/contact-self.md
> -bot.on('login', async user => {
The code here is the proper documentation.

What's the reason we deleted them?

2023-06-05 08:14 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +const contact = await bot.Contact.find({id: 'contactId-0' }) // contact0
The ```find``` in ```ContactSelf``` is not just inhereited from ```Contact``` class. 

See https://github.com/wechaty/wechaty/blob/8bec2d5a66994d7c702c9f9c4fba3f5792273c87/src/user-modules/contact-self.ts#L57

2023-06-05 08:15 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +static async find (query : string | PUPPET.filters.Contact): Promise<undefined | ContactInterface>
ditto

2023-06-05 08:16 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> -bot.on('login', async user => {
Becuase in the new doc, this section is the code example for the static method find.

The ContactSelf part is complete rewroten, so I recommend to read the new doc directly, instead of reading the diff.

2023-06-05 08:38 UTC, huan commented on docusaurus/docs/api/contact-self.md
> +const contact = await bot.Contact.find({id: 'contactId-0' }) // contact0
Yes, I remember this because I think I wrote it.

However, the propose of its existence for it is to prevent the abuse of the `ContactSelf.find()` because it is meanling less: there will always be one `ContactSelf` instance for one Wechaty instance.

So it will be also meaning less to introduce this API in the docs.

The best practice of getting a `ContactSelf` instance is to monitor the `login` event and get it from the call back argument.

2023-06-05 08:51 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +title: Contact-Self
I'll change that, and also for roomInvitation. 

Instead of editing on the old doc, this doc is a fresh start fro scratch. So I did not changed it on puporse.

2023-06-05 08:51 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +sidebar_label: ' Contact-Self'
ditto

2023-06-05 08:51 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +Contact-Self is a special kind of contact. It represents bot self. It has all methods and properties of a regular contact, and some more. Every method that returns a ```ContactInterface```, if the co
ditto

2023-06-05 08:56 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +const contact = await bot.Contact.find({id: 'contactId-0' }) // contact0
It is indeed. So can we keep this introduction on static method ```find```, because it's there, and explain why it should not be used and we should get ```ContactSelf``` instance from ```login``` event listener?

2023-06-05 09:02 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +title: Contact-Self
In the old doc, ContactSelf was refrenced as one word ```ContactSelf```, and RoomInvitation was refrenced as two words ```Room Invitation```. Could you tell which one is prefered?

2023-06-05 10:52 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +Contact-Self is a special kind of contact. It represents bot self. It has all methods and properties of a regular contact, and some more. Every method that returns a ```ContactInterface```, if the co
done

2023-06-05 10:52 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +sidebar_label: ' Contact-Self'
done

2023-06-05 10:52 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +title: Contact-Self
done

2023-06-05 10:53 UTC, hcfw007 commented on docusaurus/docs/api/contact-self.md
> +const contact = await bot.Contact.find({id: 'contactId-0' }) // contact0
I have appended with the explaination above, please check it out.

2023-06-05 12:41 UTC, iamrajiv approved these changes

2023-06-07 03:12 UTC, windmemory approved these changes

2023-06-09 13:35 UTC, su-chang approved these changes

2023-06-14 06:44 UTC, huan requested changes
Can we split this huge PR into four parts?

1. The modified `docs/api/`
2. The added `docs/puppet-api`
3. the added `docs/i18n/`
4. other misc modifications

After that, I think I will be able to review it and we can fix them separately instead of this whole mess.

Thank you!

2023-06-14 06:44 UTC, huan commented on docusaurus/docs/references/overview.mdx
> +1. [API References](../references/overview.mdx)
Why did we change the link here?

2023-06-14 06:44 UTC, huan commented on docusaurus/docs/references/overview.mdx
> -import { Toc as ApiToc }  from '../api/overview.mdx'
Why did we remote those Toc here?

2023-06-14 06:44 UTC, huan commented on docusaurus/docs/wechaty.mdx
> +Learn more functions from [API Reference](./references/overview.mdx) and [How-to Guides](./howto/overview.mdx).
ditto

2023-06-14 06:44 UTC, huan commented on docusaurus/docs/api/overview.mdx
Why do we remove this file?

2023-06-14 06:44 UTC, huan commented on docusaurus/docs/api/wechaty.md
Why did we remove this file?

2023-06-14 21:02 UTC, iamrajiv approved these changes

2023-06-15 02:36 UTC, hcfw007 commented
> Can we split this huge PR into four parts?
> 
> 1. The modified `docs/api/`
> 2. The added `docs/puppet-api`
> 3. the added `docs/i18n/`
> 4. other misc modifications
> 
> After that, I think I will be able to review it and we can fix them separately instead of this whole mess.
> 
> Thank you!

OK

2023-08-10 11:11 UTC, closed without merging