wechaty-shows-on-geeks-party
wechaty/docusaurus pull request #179
Opened 2019-11-12 12:58 UTC by su-chang

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2019-11-12 17:29 UTC, lijiarui requested changes

2019-11-12 17:29 UTC, lijiarui commented on docs/_posts/2019-11-10-wechaty-shows-on-geeks-party.md
> +![图片1.png](https://i.loli.net/2019/11/12/Ko7uwXC1iLzdv5Y.png)
Please change as request:

1. Please upload the image here: https://github.com/Chatie/blog/tree/master/docs/assets/2019/jikemiaohui
Because we cannot promise this URL always exist in the future.

2. should name for the image instead of just `图片1`. This is a dirty name.

2019-11-15 03:08 UTC, su-chang commented
I will re-fit image size again, and make Travis CI green.

2019-12-20 06:12 UTC, lijiarui approved these changes

2019-12-20 06:12 UTC, merged