change sequence & add bilibili link
wechaty/docusaurus pull request #188
Opened 2019-12-23 18:38 UTC by lijiarui

2019-12-24 02:27 UTC, windmemory requested changes
I think it would be better to wrap english words with spaces.

2019-12-24 02:27 UTC, windmemory commented on docs/_posts/2019-12-20-microsoft-ai-global-training-camp-ends-in-beijing.md
> +本次活动由Microsoft MVP & DataFun & Plug and Play & Pre-Angel & 句子互动全程落地支持。
Let's put one space before `Microsoft MVP` and one space after `句子互动`.

2019-12-24 02:27 UTC, windmemory commented on docs/_posts/2019-12-20-microsoft-ai-global-training-camp-ends-in-beijing.md
> +微软最有价值专家Microsoft Most Valuable Professional（MVP）是微软公司授予第三方技术专业人士的一个全球奖项。27年来，世界各地的技术社区领导者，因在线上和线下的技术社区中分享专业知识和经验而获得此奖项。
Space before `Microsoft`

2020-03-19 11:01 UTC, huan approved these changes

2020-03-19 11:01 UTC, merged

2020-03-19 11:01 UTC, huan commented
Thanks for the update.