Wechaty meeting
wechaty/docusaurus pull request #21
Opened 2017-04-27 07:45 UTC by antonia0912

2017-04-27 13:16 UTC, lijiarui reviewed
Thanks for your great blog!

Please modify as I requested, thanks!

2017-04-27 13:16 UTC, lijiarui commented on _posts/2017-04-21-wechaty-meeting.md
> +**Jiarui LI**, full-stack developer and chatbot developer, also funder of  [OrangeInteraction](http://www.orangeinteraction.com/). Fascinated with Jazz, she set up a dancing community in her spare ti
OrangeInteraction link wrong, should be http://www.batorange.com/

2017-04-27 13:16 UTC, lijiarui commented on _posts/2017-04-21-wechaty-meeting.md
> +There were 7 guys came to the gathering (including me), 5 programmers, and one used to work for a technical community. We met at 7 pm and would have dinner together in a Chinese restaurant. We’d like
6 programmers instead of 5 programmers

2017-04-27 13:16 UTC, lijiarui commented on _posts/2017-04-21-wechaty-meeting.md
> +
need @zixia  introduction

2017-04-27 13:16 UTC, lijiarui commented on _posts/2017-04-21-wechaty-meeting.md
> +
加上 @zixia 的介绍

2017-04-27 13:16 UTC, lijiarui commented on _posts/2017-04-21-wechaty-meeting.md
> +
save images in this blog post into directory https://github.com/Chatie/blog/tree/master/download/2017
add add photo link like this:
```
![wechaty-metting-image]: /download/2017/wechaty-metting-image.jpg
```

2017-04-27 13:17 UTC, lijiarui requested changes
Please change as I requested, thanks

2017-04-27 13:20 UTC, lijiarui requested changes
Thanks for your great blog!

Please modify as I requested, thanks!

2017-04-28 04:04 UTC, zixia commented on _posts/2017-04-21-wechaty-meeting.md
> +
I'll add the photo and video later.

2017-04-28 04:06 UTC, huan requested changes
Thank you for writing this brief and clear blog for Chatie!

Please following the request changes of @lijiarui, and then I could merge it.

Cheers!

2017-04-28 05:40 UTC, lijiarui commented on _posts/2017-04-21-wechaty-meeting.md
> +
@zixia it seems strange, I have added video comment here...  Did you delete it..

2017-04-28 06:00 UTC, zixia commented on _posts/2017-04-21-wechaty-meeting.md
> +
no

2017-04-28 06:13 UTC, zixia commented
@antonia0912 Could you please also add Github Link to everyone's brief intro?

2017-04-28 18:18 UTC, zixia commented
Video code:

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/3eq8wJfCAWs" frameborder="0" allowfullscreen></iframe>
```

Photo url:
```
https://blog.chatie.io/download/2017/antonia0912-issue-4-seminar.jpg
```

![antonia-photo](https://blog.chatie.io/download/2017/antonia0912-issue-4-seminar.jpg)

2017-05-03 03:50 UTC, lijiarui commented
@zixia could you please change the group photo we discussed in the wechat group instead of this video screenshot... the screenshot is a little bit ugly....

2017-05-03 03:57 UTC, zixia commented
I do not feel it's ugly at all, and I want to keep it.

But if you like, you can put your favorite photo in the beginning of this blog, and move this photo down after the video.

2017-05-03 05:18 UTC, antonia0912 commented
@zixia @lijiarui 相应的做了一些修改  看看还有没有需要完善的地方

2017-05-03 05:45 UTC, huan approved these changes
It looks good for me. 

Please:

1. add the blog header(title/author/date/etc)
1. embed the photo & video before publishing.

Thanks!

2017-05-04 13:49 UTC, merged

2017-05-04 16:41 UTC, Samurais commented on _posts/2017-04-21-wechaty-meeting.md
> +**Hailiang WANG** is the leader of *Rockq Community* and a chatbot developer. He used to work in *IBM Innovation Center* and the *Development Labs*. Now he works for *Lingling English* and in charge
**Hailiang WANG** is Lead of *Rockq Community* and also a software developer. He used to work in *IBM China Innovation Center* and *IBM China Development Lab*. 

@antonia0912 , consider the above introductions, thanks.

2017-05-05 08:53 UTC, zixia commented on _posts/2017-04-21-wechaty-meeting.md
> +**Hailiang WANG** is the leader of *Rockq Community* and a chatbot developer. He used to work in *IBM Innovation Center* and the *Development Labs*. Now he works for *Lingling English* and in charge
Hi @Samurais , could you please send another PR to fix this by yourself?

Because this PR had already merged.

Thanks!