add blog
wechaty/docusaurus pull request #224
Opened 2020-04-15 02:32 UTC by GreyPlane

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/Chatie/blog#contribute-guideline)

2020-04-15 02:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=224) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=224) it.</sub>

2020-04-17 14:46 UTC, lijiarui commented
@GreyPlane Thanks for the post.

Please do the following things and then I can merge this blog:

- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

2020-04-22 08:13 UTC, lijiarui commented
@GreyPlane Thanks for your update, please add a teaser image for the blog at the header.

2020-05-14 03:32 UTC, lijiarui commented
ping @GreyPlane

2020-05-17 09:22 UTC, lijiarui commented on _posts/2020-04-15-nakano-bot-blog.md
> +
Please add a teaser for this blog, it can make this blog more beautiful, thanks!

2020-05-17 09:22 UTC, lijiarui requested changes
Please change as I request.

2020-05-17 09:23 UTC, lijiarui commented
Also, it would be nice if you can resolve the confilct@

2020-05-17 10:45 UTC, GreyPlane commented
> 
> 
> Also, it would be nice if you can resolve the confilct.

sry for take so long to reply, i'm pretty busy recently, i'll fix it as soon as possible

2020-05-31 17:05 UTC, lijiarui commented
ping @GreyPlane

2020-06-21 02:32 UTC, lijiarui commented
ping @GreyPlane 

Please let me know when will you fix this PR, or I will close this PR at the end of June.

2020-06-21 07:44 UTC, closed without merging