added a blog
wechaty/docusaurus pull request #231
Opened 2020-04-23 11:06 UTC by shuangjie

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/Chatie/blog#contribute-guideline)

2020-04-23 11:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=231) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=231) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=231) it.</sub>

2020-04-28 02:04 UTC, lijiarui commented
@shuangjie 
LGTM

Please add my wechat: ruirui_0914 I will invite you into Wechaty Contributor Room.

2020-04-29 18:31 UTC, shuangjie commented
@lijiarui sorry, is it ok now?

2020-05-06 10:32 UTC, lijiarui requested changes
Please change the content I request, thanks!

2020-05-06 10:32 UTC, lijiarui commented on _posts/2020-04-23-cps-of-wechat-bot-with-wechaty.md
> +  teaser: /assets/2020/cps-bot/qrcode.png
I guess this teaser is a wrong URL since I found your upload image is `qrcode.jpg` instead of `qrcode.png`

2020-05-09 03:11 UTC, lijiarui commented
ping @shuangjie

2020-05-12 09:55 UTC, shuangjie commented on _posts/2020-04-23-cps-of-wechat-bot-with-wechaty.md
> +  teaser: /assets/2020/cps-bot/qrcode.png
thanks, I'm done

2020-05-14 03:23 UTC, merged

2020-05-14 03:24 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and I will invite you into Wechaty Contributor Room
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/81889164-7747fa80-95d5-11ea-89a3-ea489439ca99.png)