Create 2020-04-30-wechaty-chat-room_manager.md
wechaty/docusaurus pull request #233
Opened 2020-04-30 02:28 UTC by tianyugeng

发表博客

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/Chatie/blog#contribute-guideline)

2020-04-30 02:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=233) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=233) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=233) it.</sub>

2020-05-06 14:36 UTC, lijiarui requested changes

2020-05-06 14:36 UTC, lijiarui commented on _posts/2020-04-30-wechaty-chat-room-manager.md
> +  teaser: /assets/images/bio-photo.png
Thanks for this blog!

Please teaser image for the blog, I found you add teaser here but cannot find the image, please add an image at `/assests/2020/room-manager/bio-photo.png`

2020-05-07 02:46 UTC, tianyugeng commented on _posts/2020-04-30-wechaty-chat-room-manager.md
> +  teaser: /assets/images/bio-photo.png
can i delete the teaser image if i do not want it?

2020-05-07 02:51 UTC, tianyugeng commented on _posts/2020-04-30-wechaty-chat-room-manager.md
> +  teaser: /assets/images/bio-photo.png
i mean ,let my blog has no teaser image.

2020-05-07 10:53 UTC, lijiarui commented on _posts/2020-04-30-wechaty-chat-room-manager.md
> +  teaser: /assets/images/bio-photo.png
I think you can find an image for this blog, then the blog may seem more beautiful.

2020-05-08 08:03 UTC, lijiarui requested changes
Please change the date as I request, thanks!

2020-05-08 08:03 UTC, lijiarui commented on _posts/2020-04-30-wechaty-chat-room-manager.md
> +date: '2020年4月30日'
should change to: `2020-4-30 09:00 +0800`

2020-05-09 02:35 UTC, merged

2020-05-09 02:59 UTC, lijiarui commented
Congratulations! :tada: :tada: :tada:

You become a wechaty contributor successfully!  :clap: :clap: :clap:

Please: 
- [ ] add my wechat: `ruirui_0914` and I will invite you into Wechaty Contributor Room
- [ ] join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/81462304-2f476300-91e4-11ea-917c-c9109f4d9c56.png)