Jesse web blog
wechaty/docusaurus pull request #234
Opened 2020-04-30 02:58 UTC by JesseWeb

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/Chatie/blog#contribute-guideline)

2020-04-30 02:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=234) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=234) it.</sub>

2020-04-30 03:29 UTC, JesseWeb commented
@huan what should I do for this check fail?

2020-04-30 03:40 UTC, JesseWeb commented
ci fail detail:
```
# image size should not more than 1MB
58
ok 2 should get image file list
59
not ok 3 ../assets/2020/promote-bot/banner.png exceed the max limit: width: 2208, size: 71267.
```

image Size:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/23567445/80669547-434ddf00-8ad7-11ea-83e5-82dc639f8c50.png">

as you can see, the image size is not out of max limit

2020-04-30 03:43 UTC, su-chang commented
> ../assets/2020/promote-bot/banner.png exceed the max limit: width: 2208, size: 71267. use "./scripts/fit-image.sh <FILE>" to adjust it fit.

Try adjust fit by script?

2020-04-30 03:47 UTC, JesseWeb commented
> > ../assets/2020/promote-bot/banner.png exceed the max limit: width: 2208, size: 71267. use "./scripts/fit-image.sh " to adjust it fit.
> 
> Try adjust fit by script?

where can I find this script in project?

2020-04-30 03:54 UTC, JesseWeb commented
> > > ../assets/2020/promote-bot/banner.png exceed the max limit: width: 2208, size: 71267. use "./scripts/fit-image.sh " to adjust it fit.
> > 
> > 
> > Try adjust fit by script?
> 
> where can I find this script in project?

never mind. I found it.

2020-05-06 10:13 UTC, lijiarui commented
@JesseWeb Thanks for this PR， please remove the unrelated files then I can merge this PR.

2020-05-06 10:28 UTC, lijiarui requested changes
too many unrelated files, it should be clean.

2020-05-06 12:51 UTC, JesseWeb commented
I’ll solve this tomorrow

2020-05-07 06:34 UTC, JesseWeb commented
@lijiarui those unrelated files are cleaned.

2020-05-07 10:49 UTC, lijiarui requested changes

2020-05-07 10:49 UTC, lijiarui commented on _posts/2020-04-30-wechat-promote-tool.md
> +感谢 [Wechaty](https://github.com/wechaty/wechaty) 开源项目及 JuziBot 公司提供的 token，为开发者带来极大便利！
You can add link to JuziBot to， something like this:
`[句子互动](https://www.juzibot.com/)`

Thanks!

2020-05-07 12:52 UTC, JesseWeb commented on _posts/2020-04-30-wechat-promote-tool.md
> +感谢 [Wechaty](https://github.com/wechaty/wechaty) 开源项目及 JuziBot 公司提供的 token，为开发者带来极大便利！
Yea no problem.

2020-05-08 01:06 UTC, JesseWeb commented
change request has done.

2020-05-08 01:51 UTC, lijiarui commented
Good job！

2020-05-08 01:52 UTC, lijiarui approved these changes

2020-05-08 01:52 UTC, merged

2020-05-08 01:56 UTC, lijiarui commented
Congratulations! You become a wechaty contributor successfully!  :clap: :clap: :clap:

Please: 
- [ ] add my wechat: `ruirui_0914` and I will invite you into Wechaty Contributor Room
- [ ] join wechaty org by clicking https://github.com/wechaty

2020-05-08 02:07 UTC, JesseWeb commented
my pleasure