Added a blog
wechaty/docusaurus pull request #245
Opened 2020-05-11 06:47 UTC by fish-ball

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-05-14 03:30 UTC, lijiarui requested changes
Thanks for the post.

Please change as I request, thank you！

2020-05-14 03:30 UTC, lijiarui commented on _posts/2020-05-11-wechaty-subscription-bot.md
> +  teaser: /assets/2020/2020-05-11-wechaty-subscription-bot.png
please create a new file `subscription-bot` and add this image to the file.

2020-05-14 03:30 UTC, lijiarui commented
Also, if you can resolve the conflict, it could be really nice !

2020-05-15 10:10 UTC, fish-ball commented on _posts/2020-05-11-wechaty-subscription-bot.md
> +  teaser: /assets/2020/2020-05-11-wechaty-subscription-bot.png
It's done, please have a review.

2020-05-15 12:08 UTC, lijiarui commented
@fish-ball Thanks for the update, but where is this file: `2020-05-11-wechaty-subscription-bot.png` ? Please commit this image and then I can merge this.

2020-05-31 17:05 UTC, lijiarui commented
ping @fish-ball

2020-06-05 02:57 UTC, su-chang commented
@fish-ball Could please finished this blog firstly? And then it will be merged.

2020-06-07 09:42 UTC, lijiarui requested changes

2020-06-07 09:42 UTC, lijiarui commented on _posts/2020-05-11-wechaty-subscription-bot.md
> +  teaser: /assets/2020/2020-05-11-wechaty-subscription-bot.png
Please create a new folder and put these images into the folder. eg ` /assets/2020/wechaty-subscription-bot/teaser.png`

2020-06-07 09:43 UTC, lijiarui commented
@fish-ball Please change as I request. Thanks!

2020-06-07 12:32 UTC, fish-ball commented
@lijiarui It's ok now, please check again. Sorry for troubling.

2020-06-07 14:52 UTC, lijiarui requested changes

2020-06-07 14:52 UTC, lijiarui commented on _posts/2020-05-11-wechaty-subscription-bot.md
> +  teaser: /assets/2020/wechaty-subscription-bot/teaser.png
Good job.

But where is the teaser image? It seems you delete this file...

2020-06-08 00:11 UTC, fish-ball commented on _posts/2020-05-11-wechaty-subscription-bot.md
> +  teaser: /assets/2020/wechaty-subscription-bot/teaser.png
I forgot to add the file before commit. It's done now.

2020-06-08 04:07 UTC, lijiarui approved these changes
Good job!

2020-06-08 04:07 UTC, merged

2020-06-08 04:08 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://github.com/wechaty/wechaty/wiki/Contributors), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/83991869-cab52a80-a980-11ea-8cb6-ffd3ec3f0fe5.png)