added a blog
wechaty/docusaurus pull request #250
Opened 2020-05-17 11:36 UTC by Kylin93CN

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-05-17 11:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=250) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=250) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=250) it.</sub>

2020-05-17 12:33 UTC, lijiarui requested changes
Please change as I request, thanks!

2020-05-17 12:33 UTC, lijiarui commented on _posts/2020-05-17-use-wechaty-manage-ur-customers.md
> +  - wechaty-puppet-macpro
Please add a teaser here to make the blog more beautiful.

2020-05-17 12:33 UTC, lijiarui commented
@Kylin93CN Thanks for your post, please sign the CLA and change as I request, then I can merge this PR.

2020-05-17 14:28 UTC, Kylin93CN commented on _posts/2020-05-17-use-wechaty-manage-ur-customers.md
> +  - wechaty-puppet-macpro
done.

2020-05-17 14:59 UTC, huan commented on _posts/2020-05-17-use-wechaty-manage-ur-customers.md
> +categories: XueMiEr-wx-bot
I can not understand what this category is.

2020-05-19 05:45 UTC, lijiarui commented on _posts/2020-05-17-use-wechaty-manage-ur-customers.md
> +  - wechaty-puppet-macpro
where is the teaser？

2020-05-19 05:46 UTC, lijiarui commented
@Kylin93CN Please add a teaser(image) for this blog.

2020-05-21 06:47 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ]  Join wechaty org by clicking https://github.com/wechaty

2020-05-21 06:48 UTC, lijiarui approved these changes

2020-05-21 06:48 UTC, merged