added a blog
wechaty/docusaurus pull request #258
Opened 2020-05-20 07:03 UTC by suruozhong

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-05-20 07:18 UTC, huan requested changes

2020-05-20 07:18 UTC, huan commented on package.json
> +{
Please remove the unrelated file.

2020-05-20 07:31 UTC, suruozhong commented on package.json
> +{
Deleted

2020-05-21 06:44 UTC, lijiarui commented on _posts/2020-05-20-wechaty-team-robot.md
> +tags:
Please add a teaser(image) here to make the blog more beauriful

2020-05-21 06:44 UTC, lijiarui requested changes
Please change as I request.

2020-05-23 03:39 UTC, suruozhong commented on _posts/2020-05-20-wechaty-team-robot.md
> +tags:
added

2020-05-23 09:48 UTC, lijiarui approved these changes

2020-05-23 09:50 UTC, lijiarui approved these changes

2020-05-23 09:51 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/82727585-f5b34380-9d1d-11ea-9848-1fe2677e4515.png)

2020-05-23 09:51 UTC, merged