add blog
wechaty/docusaurus pull request #266
Opened 2020-06-02 09:20 UTC by H3lloTom

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-06-02 12:15 UTC, lijiarui requested changes
Good job! Please change as I request and I would merge this PR.

2020-06-02 12:15 UTC, lijiarui commented on _posts/2020-06-02-wechat-bot.md
> +title: "wechat-bot"
Please add a more clear title for this blog, then others would like to click and read your blog.

2020-06-02 14:14 UTC, H3lloTom commented on _posts/2020-06-02-wechat-bot.md
> +title: "wechat-bot"
ok，glad to get your replay  (●'◡'●)

2020-06-04 03:51 UTC, lijiarui requested changes

2020-06-04 03:51 UTC, lijiarui commented on _posts/2020-06-02-wechat-bot.md
> +  teaser: /assets/2020/2020-06-02-wechat-bot.jpg
Please create a new folder under `/assets/2020` and put the image in the new folder. Thanks!

2020-06-04 04:54 UTC, H3lloTom commented on _posts/2020-06-02-wechat-bot.md
> +  teaser: /assets/2020/2020-06-02-wechat-bot.jpg
done~

2020-06-04 07:12 UTC, lijiarui commented
Good job！

2020-06-04 07:13 UTC, lijiarui approved these changes

2020-06-04 07:13 UTC, merged