Add Blog
wechaty/docusaurus pull request #275
Opened 2020-06-04 18:38 UTC by PXingwei

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-06-04 18:42 UTC, PXingwei commented
Thanks @lijiarui for reviewing my blog! I used the wrong username to commit the blog and have problems in signing CLA. I had to closed the previous pull request. I also created a new folder for the image. Thanks!

2020-06-05 02:51 UTC, lijiarui requested changes

2020-06-05 02:51 UTC, lijiarui commented on _posts/2020-06-04-group-wechat-bot.md
> +title: "微信群助手"
Please change a more clear title for this blog, then it may attract more readers.

2020-06-05 04:04 UTC, PXingwei commented on _posts/2020-06-04-group-wechat-bot.md
> +title: "微信群助手"
Thanks for pointing out!

2020-06-05 18:55 UTC, PXingwei commented
Hi @lijiarui, I have changed the title, are there other changes that I need to make?

2020-06-07 09:48 UTC, lijiarui approved these changes
Good job!

2020-06-07 09:52 UTC, lijiarui commented
Please resolve the conflict and then I can merge this PR.

2020-06-08 04:04 UTC, lijiarui commented
duplicate with #278

2020-06-08 04:04 UTC, closed without merging