add java wechaty
wechaty/docusaurus pull request #288
Opened 2020-06-15 15:50 UTC by diaozxin007

add java wechaty

2020-06-17 07:51 UTC, lijiarui requested changes
Thanks for the fantastic blog!

Please:

1. Change all of the images to local files in order to avoid 404 in the future.
2. It seems you didn't use  `assets/2020/2020-06-15-java-wechaty.png` in this blog.

Thanks!

2020-06-17 08:39 UTC, lijiarui requested changes

2020-06-17 08:39 UTC, lijiarui commented on _posts/2020-06-15-java-wechaty.md
> +   teaser: /assets/2020/2020-06-15-java-wechaty.png
Please create a new folder `java-wechaty` and put `2020-06-15-java-wechaty.png` into `java-wechaty`

2020-06-17 13:00 UTC, diaozxin007 commented on _posts/2020-06-15-java-wechaty.md
> +   teaser: /assets/2020/2020-06-15-java-wechaty.png
ok

2020-06-18 04:31 UTC, lijiarui approved these changes

2020-06-18 04:31 UTC, merged