add 07.05 multi-language-wechaty meeting-notes
wechaty/docusaurus pull request #321
Opened 2020-07-07 07:43 UTC by wj-Mcat

**2020.07.05 multi-language-wechaty Meeting Notes**

- [x] Add Blog Header, including title, author, date.

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
> I put the photos into `assets/2020/meeting-notes` dir, is it correct ?
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-07 10:01 UTC, lijiarui commented
@wj-Mcat Thanks for the fantastic blog!

Please make ci green first.

2020-07-07 16:58 UTC, huan approved these changes
LGTM

2020-07-07 16:59 UTC, huan commented
@wj-Mcat Thank you very much for organizing this great event and writing this memorable blog post, appreciate it!

2020-07-08 12:04 UTC, lijiarui requested changes
Please change as I request.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> + header:
No more blank here.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +   teaser: assets/2020/meeting-notes/07.05.head-picture.jpg
Please change the file name to `07-05-head-picture.jpg` Since the blog writing style is:


Keep all filenames & url as lowercase, and use - to connect words instead of space. e.g. 2017-10-06-wechat-pc-impactor instead of 2017-10-06-WeChat PC Impactor

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +![mock-is-required-for-wechaty](/assets/2020/meeting-notes/07.05.mock-server-can-test-more.png)
change the image name.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +![](/assets/2020/meeting-notes/07.05.hook-restful-api.png)
change the image name.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +![](/assets/2020/meeting-notes/07.05.puppet-mock-template.png)
change the image name.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +![](/assets/2020/meeting-notes/07.05.python-wechaty-web-functions.png)
change the image name.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +![](/assets/2020/meeting-notes/07.05.python-wechaty-web-asyncio.png)
change the image name.

2020-07-08 12:04 UTC, lijiarui commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +![](/assets/2020/meeting-notes/07.05.mocker.png)
change the image name.

2020-07-08 12:22 UTC, wj-Mcat commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> + header:
Yes, this configuration should not be preceded by blank.

2020-07-08 12:25 UTC, wj-Mcat commented on _posts/2020-07-05-multilanguage-meeting-notes.md
> +   teaser: assets/2020/meeting-notes/07.05.head-picture.jpg
Ok, I will change all file name style to `file-name.jpg`

2020-07-08 13:25 UTC, lijiarui requested changes

2020-07-08 13:25 UTC, lijiarui commented on package.json
> +  "version": "0.2.29",
Why you change package version?

2020-07-08 13:28 UTC, wj-Mcat commented on package.json
> +  "version": "0.2.29",
It seems that Git change it automatically.

2020-07-08 13:35 UTC, lijiarui commented on package.json
> +  "version": "0.2.29",
You should change it back， since one pr shouldn't commit unrelated files.

2020-07-08 13:58 UTC, wj-Mcat commented on package.json
> +  "version": "0.2.29",
I have changed it back.

2020-07-08 14:08 UTC, wj-Mcat commented
When I push the commits, it will automatically update the version.

2020-07-09 05:15 UTC, lijiarui commented
Good job!

2020-07-09 05:15 UTC, merged