工作日报管理机器人
wechaty/docusaurus pull request #331
Opened 2020-07-12 03:28 UTC by zzhoouxin

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-12 03:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=331) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=331) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=331) it.</sub>

2020-07-17 03:28 UTC, lijiarui requested changes

2020-07-17 03:28 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
Please remove disable markdown lint.

2020-07-17 03:41 UTC, zzhoouxin commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
successfully removed

2020-07-17 04:11 UTC, zzhoouxin commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
请问下-什么时候可以再次审核？谢谢了

2020-07-17 05:58 UTC, lijiarui requested changes

2020-07-17 05:58 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
It seems it still exist ....

2020-07-17 06:01 UTC, zzhoouxin commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
The error was not caused by him

2020-07-17 06:17 UTC, zzhoouxin commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
I have deleted it again thanks

2020-07-17 09:02 UTC, zzhoouxin commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
excuse me , will you still be reviewing today

2020-07-18 11:48 UTC, lijiarui requested changes

2020-07-18 11:48 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
Please make sure you remove this:

`<!-- markdownlint-disable -->`

2020-07-19 07:48 UTC, lijiarui approved these changes
Good job!

2020-07-19 07:54 UTC, lijiarui requested changes
Please fix the error to make CI green and then I will merge this PR.

2020-07-20 10:52 UTC, zzhoouxin commented
I have fixed the error

2020-07-20 10:58 UTC, zzhoouxin commented on _posts/2020-07-11-wechaty-daily.md
> +<!-- markdownlint-disable -->
I have fixed the error

2020-07-20 14:26 UTC, lijiarui requested changes

2020-07-20 14:26 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +  ![定时发送日报](https://upload-images.jianshu.io/upload_images/7078301-4af74bb5c0ea1991.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/340)
Please localize this image in case of a future 404 error.

2020-07-20 14:26 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +  ![image.png](https://upload-images.jianshu.io/upload_images/7078301-6b92349444b82c24.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/340)
Please localize this image in case of a future 404 error.

2020-07-20 14:26 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +![image.png](https://upload-images.jianshu.io/upload_images/7078301-b1b1b9855a417e80.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/340)
Please localize this image in case of a future 404 error.

2020-07-20 14:26 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +![image.png](https://upload-images.jianshu.io/upload_images/7078301-06e3a9ed05e322d6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/340)
Please localize this image in case of a future 404 error.

2020-07-20 14:26 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +  ![日常提醒](https://upload-images.jianshu.io/upload_images/7078301-f10068182c7ce0a0.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/330)
Please localize this image in case of a future 404 error.

2020-07-20 14:26 UTC, lijiarui commented on _posts/2020-07-11-wechaty-daily.md
> +![wiki基础页面结构](https://upload-images.jianshu.io/upload_images/7078301-14ae5594244e7afd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/340)
Please localize this image in case of a future 404 error.

2020-07-20 14:27 UTC, lijiarui commented
And also, please resolve the conflict.

2020-07-20 14:47 UTC, lijiarui commented
I mean localize the image, not delete the image :)

2020-07-21 03:00 UTC, zzhoouxin commented
:) sorry I submitted the code for the first time  ,the problem has now been solved

2020-07-21 04:56 UTC, lijiarui approved these changes
Good job!

2020-07-21 04:56 UTC, merged

2020-07-21 04:57 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty


![image](https://user-images.githubusercontent.com/6419514/88014484-a177e480-cb51-11ea-9a5c-c2b1189e132d.png)