added a blog
wechaty/docusaurus pull request #332
Opened 2020-07-12 07:44 UTC by sidny

post a blog for Support-Developers 

wxid: sidny00

2020-07-12 07:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=332) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=332) before we can accept your contribution.<br/><hr/>**yangfan_c** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=332) it.</sub>

2020-07-17 03:27 UTC, lijiarui requested changes

2020-07-17 03:27 UTC, lijiarui commented on _posts/2020-07-12-wechat-roommessage-bot.md
> +  - wechaty-puppet-padplus
Please add a teaser for this blog.

2020-07-17 03:29 UTC, lijiarui requested changes

2020-07-17 03:29 UTC, lijiarui commented on _posts/2020-07-12-wechat-roommessage-bot.md
> +<!-- markdownlint-disable -->
Please remove markdown link disable.

2020-07-20 04:42 UTC, sidny reviewed
1 remove markdown link disable   --- done 
2 add teaser --- done

2020-07-20 04:42 UTC, sidny commented on _posts/2020-07-12-wechat-roommessage-bot.md
> +  teaser: /assets/2020/wechat-roommessage-bot/teaser.png
add teaser

2020-07-20 04:42 UTC, sidny commented on _posts/2020-07-12-wechat-roommessage-bot.md
> +  - wechaty-puppet-padplus
done

2020-07-20 06:29 UTC, lijiarui requested changes
Good job, please add link for the blog and then I will merge this PR.

2020-07-20 06:29 UTC, lijiarui commented on _posts/2020-07-12-wechat-roommessage-bot.md
> +感谢句子互动提供的pad协议版token。
Please add link for wechaty and 句子互动：

- wechaty： https://wechaty.github.io/
- 句子互动： https://www.juzibot.com/

2020-07-20 14:23 UTC, lijiarui approved these changes
Good job！

2020-07-20 14:23 UTC, merged

2020-07-20 14:27 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/87949057-1c041e00-cad8-11ea-8588-e9441487233d.png)

2020-07-21 05:18 UTC, sidny commented
> Congratulations! 🎉 🎉 🎉
> 
> You become a wechaty contributor successfully! 👏 👏 👏
> 
> Please:
> 
> * [ ]   Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
> * [ ]  Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
> * [ ]   Join wechaty org by clicking https://github.com/wechaty
> 
> ![image](https://user-images.githubusercontent.com/6419514/87949057-1c041e00-cad8-11ea-8588-e9441487233d.png)

 Add my wechat: ruirui_0914 and send me this pr link   **--- done**
 Update your profile here: Contributor List   **---- done**
 Join wechaty org by clicking https://github.com/wechaty    **---- done**