微信转发机器人（wechaty-forwardBot）
wechaty/docusaurus pull request #333
Opened 2020-07-14 12:28 UTC by 22528850

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-14 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=333) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=333) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=333) it.</sub>

2020-07-17 03:22 UTC, lijiarui requested changes

2020-07-17 03:22 UTC, lijiarui commented on _posts/2020-07-15-wechaty-forwardbot.md
> +   teaser: https://avatars3.githubusercontent.com/u/56892264?s=460&u=b94cb5809dff0bc5766bc88acd3b57629817271f&v=4
Please localize this image in case a future 404 error.

2020-07-17 03:22 UTC, lijiarui commented on _posts/2020-07-15-wechaty-forwardbot.md
> +感谢WechatY团队提供微信机器人SDK 感谢句子互动提供的iPad协议版token
change `WechatY` to `Wechaty`

Also, you can add link for wechaty and juzibot:

wechaty: https://github.com/wechaty/wechaty
juzibot:https://www.juzibot.com/

2020-07-17 07:43 UTC, 22528850 commented on _posts/2020-07-15-wechaty-forwardbot.md
> +   teaser: https://avatars3.githubusercontent.com/u/56892264?s=460&u=b94cb5809dff0bc5766bc88acd3b57629817271f&v=4
Localized image resources completed

2020-07-17 07:44 UTC, 22528850 commented on _posts/2020-07-15-wechaty-forwardbot.md
> +感谢WechatY团队提供微信机器人SDK 感谢句子互动提供的iPad协议版token
WechatY has been modified to wechaty

2020-07-18 11:46 UTC, lijiarui requested changes

2020-07-18 11:46 UTC, lijiarui commented on _posts/2020-07-15-wechaty-forwardbot.md
> +<!-- markdownlint-disable -->
Please remove this： `<!-- markdownlint-disable -->`

2020-07-18 11:46 UTC, lijiarui commented on _posts/2020-07-15-wechaty-forwardbot.md
> +   teaser: /assets/2020/wechaty-forwardBot/header.jpg
Please follow the wechaty name rule, change `forwardBot` to `forward-bot` or  `forwardbot`

2020-07-18 12:29 UTC, 22528850 commented on _posts/2020-07-15-wechaty-forwardbot.md
> +<!-- markdownlint-disable -->
OK, deleted

2020-07-18 12:29 UTC, 22528850 commented on _posts/2020-07-15-wechaty-forwardbot.md
> +   teaser: /assets/2020/wechaty-forwardBot/header.jpg
OK, changed

2020-07-19 08:37 UTC, lijiarui requested changes
Please fix the error to make ci green. Then I will merge this PR.

2020-07-19 10:51 UTC, closed without merging