submit to wechaty-robot blog
wechaty/docusaurus pull request #334
Opened 2020-07-15 03:30 UTC by zoudingyi

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-15 03:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=334) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=334) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=334) it.</sub>

2020-07-17 03:18 UTC, lijiarui requested changes
Thanks for the blog.

1. Please change as I request
2. Please add more insight for this blog instead just code.
3. Please add your profile at author.yml

2020-07-17 03:18 UTC, lijiarui commented on _posts/2020-07-15-wechaty-robot.md
> +title: "微信机器人（wechaty robot）"
Please revise this title to make it more related to this blog. Since `微信机器人（wechaty robot）` can be any title for any wechaty blog.

2020-07-17 06:06 UTC, zoudingyi commented on _posts/2020-07-15-wechaty-robot.md
> +title: "微信机器人（wechaty robot）"
> Please revise this title to make it more related to this blog. Since `微信机器人（wechaty robot）` can be any title for any wechaty blog.

Thanks, I have corrected it.

2020-07-18 11:55 UTC, lijiarui requested changes

2020-07-18 11:55 UTC, lijiarui commented on _posts/2020-07-17-wechat-purchasing-robot.md
> +<!-- markdownlint-disable -->
Please remove this `<!-- markdownlint-disable -->`

2020-07-18 11:55 UTC, lijiarui commented on _posts/2020-07-17-wechat-purchasing-robot.md
> +非常感谢Wechaty团队提供微信机器人SDK，让开发者可以专注于业务代码。<br />感谢句子互动提供的pad协议版token。
Please add wechaty and juzibot link:

- wechaty:  https://wechaty.github.io/
- juzibot: https://www.juzibot.com

2020-07-18 11:55 UTC, lijiarui commented on _posts/2020-07-17-wechat-purchasing-robot.md
> +女朋友在做代购，加了很多微信好友和微信群，所以每天会有很多人前来咨询商品信息以及商品价格，因此想做一个管理机器人，用于自动回复消息、群管理以及自动添加好友，以及用户发送商品关键词能够自动回复相应商品信息。
Please add more `代购` related info in this blog. Since it can be more attractive.

2020-07-20 13:36 UTC, lijiarui requested changes
As an engineer, you should be more careful....

Or this is wasting both of us time....

2020-07-20 13:36 UTC, lijiarui commented on _posts/2020-07-20-wechat-purchasing-robot.md
> +![效果图](/assets/2020/wechaty-robot/chat.png)
It seems you change the file path.... This may cause a 404 error ....

2020-07-20 13:36 UTC, lijiarui commented on _posts/2020-07-20-wechat-purchasing-robot.md
> +   teaser: /assets/2020/wechat-purchasing-robot/header.jpg
Here should be 2 blanks... Instead of 3 blank...

2020-07-20 13:51 UTC, lijiarui commented
And please resolve the conflict, then I will be able to merge this PR.

2020-07-20 15:12 UTC, zoudingyi commented on _posts/2020-07-20-wechat-purchasing-robot.md
> +![效果图](/assets/2020/wechaty-robot/chat.png)
> It seems you change the file path.... This may cause a 404 error ....

 I'm very sorry about missing that.

2020-07-20 15:15 UTC, zoudingyi commented
> As an engineer, you should be more careful....
> 
> Or this is wasting both of us time....

I'm so sorry.

2020-07-21 03:49 UTC, zoudingyi commented
> And please resolve the conflict, then I will be able to merge this PR.

Sorry to disturb you during my busy schedule, I have resolved the conflict. Thank you very much for reviewing my blog.

2020-07-21 04:50 UTC, lijiarui approved these changes
Good job！

2020-07-21 04:51 UTC, merged

2020-07-21 04:54 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/88014339-4f36c380-cb51-11ea-9a45-f8843c06a03d.png)