added a blog
wechaty/docusaurus pull request #337
Opened 2020-07-19 09:55 UTC by FINCTIVE

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-19 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=337) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=337) it.</sub>

2020-07-19 11:11 UTC, lijiarui commented
Where is your blog file? I only find you change author.yml file.

2020-07-19 12:14 UTC, FINCTIVE commented
> Where is your blog file? I only find you change author.yml file.

Sorry, it's my second time to edit this, I forgot copy the blog file. :crying_cat_face:

2020-07-20 06:35 UTC, lijiarui requested changes

2020-07-20 06:35 UTC, lijiarui commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +   teaser: /assets/2020/go-wechaty/2020-06-29-go-wechaty.png
Where is this file?

2020-07-20 07:23 UTC, FINCTIVE commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +   teaser: /assets/2020/go-wechaty/2020-06-29-go-wechaty.png
> Where is this file?

It was uploaded.

https://github.com/wechaty/wechaty.github.io/blob/master/assets/2020/go-wechaty/2020-06-29-go-wechaty.png

I use the same image file in this post: https://wechaty.github.io/2020/09/18/go-wechaty/

2020-07-20 08:21 UTC, huan commented
Link to https://github.com/wechaty/summer-of-code/issues/9

2020-07-20 12:32 UTC, lijiarui commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +   teaser: /assets/2020/go-wechaty/2020-06-29-go-wechaty.png
Please put create a new file and put it in your separate folder, or it may make future 404 error.

2020-07-20 12:32 UTC, lijiarui commented
Also, you should solve the conflict, then I can merge this PR.

2020-07-20 16:17 UTC, FINCTIVE commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +   teaser: /assets/2020/go-wechaty/2020-06-29-go-wechaty.png
> Please put create a new file and put it in your separate folder, or it may make future 404 error.

OK, now I added a new file :smile:

2020-07-20 16:17 UTC, FINCTIVE commented
> Also, you should solve the conflict, then I can merge this PR.

Thanks for your patience! :+1:

2020-07-20 18:05 UTC, lijiarui requested changes

2020-07-20 18:05 UTC, lijiarui commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> + title: "暑期2020 [为 go-wechaty 设计实现插件体系] 计划书"
The indention here is wrong. Please refer other blog and fix this.

2020-07-21 04:58 UTC, lijiarui approved these changes
Good job!

2020-07-21 04:59 UTC, merged

2020-07-21 05:00 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/88014670-13502e00-cb52-11ea-9f7c-0d023a91c5f1.png)