Xzl blog
wechaty/docusaurus pull request #343
Opened 2020-07-19 14:52 UTC by MrZilinXiao

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-20 06:33 UTC, lijiarui requested changes

2020-07-20 06:33 UTC, lijiarui commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +
Please add a teaser for this blog.

2020-07-20 06:33 UTC, lijiarui commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +![image](https://upyun.mrxiao.net/img/wechaty-meme-bot.png)
Please localize the image in case of a future 404 error.

2020-07-20 11:48 UTC, MrZilinXiao commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +
Already done, sorry for the inconvenience.

2020-07-20 11:49 UTC, MrZilinXiao commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +![image](https://upyun.mrxiao.net/img/wechaty-meme-bot.png)
Already go localized, sorry for the inconvenience.

2020-07-20 12:25 UTC, lijiarui requested changes

2020-07-20 12:25 UTC, lijiarui commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> + author: MrZilinXiao
Here should be  `godkillerxiao`, or the system cannot recognize your profile.

2020-07-20 12:31 UTC, MrZilinXiao commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> + author: MrZilinXiao
Changed.

2020-07-20 15:22 UTC, lijiarui requested changes

2020-07-20 15:22 UTC, lijiarui commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +  teaser: /assets/2020/meme-bot/07-19-wechaty-meme-bot.png
There shouldn't have any blank here.

2020-07-20 15:23 UTC, lijiarui commented
And you should resolve the conflict.

2020-07-20 15:53 UTC, huan commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +  teaser: /assets/2020/meme-bot/07-19-wechaty-meme-bot.png
I guess you mean `indention`?

2020-07-20 18:05 UTC, lijiarui commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +  teaser: /assets/2020/meme-bot/07-19-wechaty-meme-bot.png
yes ：）

2020-07-20 22:16 UTC, MrZilinXiao commented
> And you should resolve the conflict.

Yep. Done!

2020-07-20 22:19 UTC, MrZilinXiao commented on _posts/2020-07-18-python-wechaty-meme-bot.md
> +  teaser: /assets/2020/meme-bot/07-19-wechaty-meme-bot.png
No more unnecessary indentions!

2020-07-22 13:15 UTC, lijiarui approved these changes
Good job！

2020-07-22 13:15 UTC, merged

2020-07-22 13:16 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/88180853-8fd13280-cc60-11ea-92c2-3cf348099495.png)

2020-07-23 07:02 UTC, MrZilinXiao commented
> Congratulations! 🎉 🎉 🎉
> 
> You become a wechaty contributor successfully! 👏 👏 👏
> 
> Please:
> 
> * [ ]   Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
> * [ ]  Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
> * [ ]   Join wechaty org by clicking https://github.com/wechaty
> 
> ![image](https://user-images.githubusercontent.com/6419514/88180853-8fd13280-cc60-11ea-92c2-3cf348099495.png)

Already finished the last two steps, while I am not invited to Contributor Room after sending you PR Link.