commit blog: 用 Wechaty 实现微信任务小助手
wechaty/docusaurus pull request #348
Opened 2020-07-20 03:07 UTC by darkli

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-20 03:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=348) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=348) before we can accept your contribution.<br/><hr/>**李云军** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=348) it.</sub>

2020-07-20 06:31 UTC, lijiarui requested changes
Good job, please change as I request and make ci green. Then I can merge this PR.

2020-07-20 06:31 UTC, lijiarui commented on _posts/2020-07-17-wechaty-assistant.md
> +<!-- markdownlint-disable -->
Please remove this: `<!-- markdownlint-disable -->`

2020-07-20 06:32 UTC, lijiarui commented
Also, please sign the CLA first.

2020-07-21 08:33 UTC, closed without merging

2020-07-21 08:33 UTC, darkli commented
提交blog的时候，用的身份不是darkli，无法做CLA，撤销这次PR，重新来一次