added a blog
wechaty/docusaurus pull request #371
Opened 2020-07-23 02:30 UTC by csjuXYZ

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-23 02:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=371) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=371) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=371) it.</sub>

2020-07-23 03:13 UTC, csju approved these changes
ok

2020-07-23 03:14 UTC, csju approved these changes
ok

2020-07-23 03:16 UTC, csju approved these changes

2020-07-23 12:51 UTC, lijiarui requested changes

2020-07-23 12:51 UTC, lijiarui commented on _posts/2020-07-23-wechaty-lottery.md
> +  teaser: ..\assets\2020\wechaty-lottery\lottery-header.jpg
Please remove  `..`

2020-07-23 12:51 UTC, lijiarui commented on _posts/2020-07-23-wechaty-lottery.md
> +- ![测试](..\assets\2020\wechaty-lottery\pic01.jpg)
Please remove `..`

2020-07-23 13:41 UTC, csjuXYZ commented on _posts/2020-07-23-wechaty-lottery.md
> +- ![测试](..\assets\2020\wechaty-lottery\pic01.jpg)
ok

2020-07-24 04:56 UTC, lijiarui approved these changes

2020-07-24 04:58 UTC, lijiarui commented
Please resolve the conflict, then I could able merge this PR.

2020-07-24 07:52 UTC, merged

2020-07-24 07:53 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty