Early bird
wechaty/docusaurus pull request #372
Opened 2020-07-23 08:11 UTC by lmaCode

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.

e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-23 09:07 UTC, lmaCode commented
Who can tell me what caused NPM build Test failure?

2020-07-23 09:14 UTC, csjuXYZ commented
> Who can tell me what caused NPM build Test failure?

MD文档有多余的空行或者空格,具体可以在details看出项错误的行数

2020-07-23 10:07 UTC, lijiarui commented
Please make CI green then I can review your PR.

2020-07-23 10:28 UTC, lmaCode commented
> Please make CI green then I can review your PR.

Done. Thank you all. @csjuXYZ @lijiarui

2020-07-23 12:53 UTC, lijiarui requested changes

2020-07-23 12:53 UTC, lijiarui commented on _posts/2020-07-23-early-bird-chatbot.md
> +[https://github.com/juzibot/Welcome/wiki/Support-Developers](https://github.com/juzibot/Welcome/wiki/Support-Developers)
change  to： https://github.com/juzibot/Welcome/wiki/Everything-about-Wechaty

2020-07-23 13:04 UTC, lmaCode commented on _posts/2020-07-23-early-bird-chatbot.md
> +[https://github.com/juzibot/Welcome/wiki/Support-Developers](https://github.com/juzibot/Welcome/wiki/Support-Developers)
Done. Please check it.

2020-07-24 04:53 UTC, lijiarui approved these changes
Good job

2020-07-24 04:53 UTC, merged

2020-07-24 04:54 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room
- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty

![image](https://user-images.githubusercontent.com/6419514/88361794-d338b780-cdac-11ea-8cf7-fafb64563d96.png)