Ainl per blog
wechaty/docusaurus pull request #379
Opened 2020-07-24 07:56 UTC by yinizhilian

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-10 13:35 UTC, lijiarui commented
Thanks for this blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-17 06:58 UTC, lijiarui commented
ping @yinizhilian

2020-08-17 11:21 UTC, lijiarui commented
@yinizhilian Please make CI green and then we can review you PR.

2020-08-18 06:54 UTC, yinizhilian commented
> @yinizhilian Please make CI green and then we can review you PR.

I made a mistake and wasted a lot of time yesterday，
but now It's ok ，thx.

2020-08-18 06:58 UTC, yinizhilian commented
@huan I made a mistake and wasted a lot of time yesterday，but now It's ok ，thx.

2020-08-20 09:27 UTC, lijiarui requested changes
Please change as I request, thanks!

2020-08-20 09:27 UTC, lijiarui commented on _data/authors.yml
> +      icon: "fab fa-fw fa-github"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-20 09:27 UTC, lijiarui commented on _developers/yinizhilian.md
> +
Please remove the useless row here.

2020-08-20 09:27 UTC, lijiarui commented on _developers/yinizhilian.md
> +
Please remove the useless row here.

2020-08-20 09:27 UTC, lijiarui commented on _developers/yinizhilian.md
> +site: <https://github.com/yinizhilian>
Please change to https://github.com/yinizhilian

2020-08-20 09:27 UTC, lijiarui commented on _developers/yinizhilian.md
> +avatar: <https://avatars1.githubusercontent.com/yinizhilian>
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-20 09:27 UTC, lijiarui commented on _developers/yinizhilian.md
> +
You should add your profile here, instead of the blog title here.

2020-08-20 09:27 UTC, lijiarui commented on _posts/2020-07-23-kuakua-wechaty.md
> +  teasser: /assets/2020/kuakua.png
Where is this profile？

2020-08-20 10:45 UTC, yinizhilian commented on _developers/yinizhilian.md
> +
I have removed the introduction

2020-08-20 10:46 UTC, yinizhilian commented on _posts/2020-07-23-kuakua-wechaty.md
> +  teasser: /assets/2020/kuakua.png
I have changed the image path

2020-08-20 12:15 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 12:15 UTC, lijiarui commented on _data/authors.yml
>        icon: "fas fa-fw fa-envelope-square"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-20 12:15 UTC, lijiarui commented on _developers/yinizhilian.md
> +avatar: /assets/2020/kuakua-wechaty/yinizhilian.png
This avatar should under `developers` file

2020-08-20 12:15 UTC, lijiarui commented on _developers/yinizhilian.md
> +Zhihu: <https://www.zhihu.com/people/wangjini521>
Please change to `https://www.zhihu.com/people/wangjini521` here

2020-08-20 12:15 UTC, lijiarui commented on _posts/2020-07-23-kuakua-wechaty.md
> +date: 2020-08-20 23:00 +0800
Please remove date here since we upgrade the blog.

2020-08-20 12:15 UTC, lijiarui commented on _posts/2020-07-23-kuakua-wechaty.md
> +header:
The image should change to:

```
image: /assets/2020/kuakua-wechaty/titleimage.png
```

2020-08-21 14:34 UTC, lijiarui requested changes
Please change as I request.

2020-08-21 14:34 UTC, lijiarui commented on .gitignore
> -new-gh-pages/
Please remove the useless commit here.

2020-08-30 16:46 UTC, lijiarui requested changes
Please change as I request.

2020-08-30 16:46 UTC, lijiarui commented on _data/authors.yml
>        icon: "fas fa-fw fa-envelope-square"
Please remove this file since this file is not useful anymore.

2020-08-30 16:46 UTC, lijiarui commented on _developers/yinizhilian.md
> +avatar: /_developers/yinizhilian.png
Please change this avator dir. 

The correct dir shoud be `/assets/developers/yourname/avatar.png`

2020-08-31 01:40 UTC, yinizhilian commented on _developers/yinizhilian.md
> +avatar: /_developers/yinizhilian.png
delete the authors.yml  and  modified the yinizhilian.md

2020-09-02 17:43 UTC, lijiarui requested changes
I mean you should remove the useless file from git commit, instead of remove the files from this repo. see : https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

Your commit trying to remove _data/author.yml is incorrect here.

2020-09-02 17:43 UTC, lijiarui commented on .gitignore
> -new-gh-pages/
I mean you should remove this file from git commit, see : https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

2020-10-03 08:55 UTC, lijiarui commented
ping @yinizhilian Please change as I request and then I would merge your blog.

2020-11-08 02:07 UTC, wj-Mcat requested changes
The path of `_developers/yinizhilian` is not correct.  You should move it to `/jeykll/`refer to : [develoers/archy](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_developers/archy.md) , please fix it as soon as possible. We will keep eyes on this pr these days.  Thanks a lot.

2020-12-05 02:56 UTC, merged

2020-12-05 03:32 UTC, huan commented
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/07/23/kuakua-wechaty>

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.