add a retarded-robot blog
wechaty/docusaurus pull request #382
Opened 2020-07-27 08:18 UTC by xajeyu

add a retarded-robot blog

2020-07-27 08:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=382) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=382) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=382) it.</sub>

2020-08-10 13:30 UTC, lijiarui commented
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-11 03:07 UTC, xajeyu commented
Already added, please review

2020-08-12 01:37 UTC, lijiarui requested changes

2020-08-12 01:37 UTC, lijiarui commented on _developers/xajeyu.md
> +avatar: https://avatars1.githubusercontent.com/u/26016496?s=460
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-12 01:37 UTC, lijiarui commented on _posts/2020-07-27-retarded-robot.md
> +author: xajeyu@gmail.com
`xajeyu@gmail.com` should be the same as markdown file name.

So you should change this to `xajeyu`

2020-08-12 01:54 UTC, xajeyu commented on _developers/xajeyu.md
> +avatar: https://avatars1.githubusercontent.com/u/26016496?s=460
I have finished

2020-08-12 01:54 UTC, xajeyu commented on _posts/2020-07-27-retarded-robot.md
> +author: xajeyu@gmail.com
I have finished

2020-08-12 03:00 UTC, lijiarui requested changes

2020-08-12 03:00 UTC, lijiarui commented on _data/authors.yml
> +  name        : "xajeyu"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-12 03:25 UTC, xajeyu commented
hi @lijiarui 

I have completed all changes, please check

Thanks

2020-08-12 17:06 UTC, merged

2020-08-12 17:06 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room