Java移植组件开发博客
wechaty/docusaurus pull request #383
Opened 2020-07-27 11:38 UTC by cunkoulaocai

添加java-wechaty开发计划博客

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-10 13:29 UTC, lijiarui commented
Please follow the blog rule:


Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

2020-08-17 07:00 UTC, lijiarui commented
ping @cunkoulaocai

2020-08-20 09:54 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 09:54 UTC, lijiarui commented on _posts/2020-07-27-java-wechaty-transplant.md
> +| title                     | author       | categories | image                                                        | tags         |
Please add blog as the template show.

2020-08-30 16:42 UTC, lijiarui commented
@cunkoulaocai I will close this PR if this PR has no reply at the end of September.

2020-08-31 03:18 UTC, cunkoulaocai commented
pong

2020-09-02 18:20 UTC, lijiarui commented
Could you change as I request as soon as possible? Since other soc contributors already posted their blog for a few weeks but you haven't posted even one blog!

2020-09-03 13:45 UTC, cunkoulaocai commented
I encounter some format problem,I will pull request again and close this pull request

2020-09-03 13:45 UTC, closed without merging