Rainbowbot blog
wechaty/docusaurus pull request #388
Opened 2020-07-28 09:15 UTC by CavonCheng

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-28 09:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=388) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=388) it.</sub>

2020-08-10 13:28 UTC, lijiarui commented
Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-10 15:16 UTC, CavonCheng commented
@lijiarui Thanks for your review, my profile has been committed.

2020-08-12 02:20 UTC, lijiarui requested changes
Good job！

Please change as I request.

2020-08-12 02:20 UTC, lijiarui commented on _data/authors.yml
> +CavonCheng:
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-12 02:20 UTC, lijiarui commented on _developers/CavonCheng.md
> +site: https://github.com/CavonCheng
You should change this to cavon-cheng, because our rule as follows:

>  Keep all filenames & url as lowercase, and use - to connect words instead of space. e.g. 2017-10-06-wechat-pc-impactor instead of 2017-10-06-WeChat PC Impactor

2020-08-12 02:20 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rainbowbot.md
> + author: CavonCheng
And here should be same as the markdown file name.

2020-08-12 09:14 UTC, CavonCheng commented on _posts/2020-07-28-wechaty-rainbowbot.md
> + author: CavonCheng
@lijiarui Thank you for reviewing. Do you mean that I should change "author: CavonCheng" to "author: 2020-07-28-wechaty-rainbowbot" here?  
I think "author: cavon-cheng" was what you want me to change to ,right?

2020-08-12 13:46 UTC, CavonCheng commented on _posts/2020-07-28-wechaty-rainbowbot.md
> + author: CavonCheng
@lijiarui  Finally I changed the title to "wechaty-rainbowbot ..." because I think this is more likely what you want me to do.

2020-08-12 13:49 UTC, CavonCheng commented
@lijiarui Thank you for the tips,I have fixed them. Please review again, thank you very much!

2020-08-12 16:42 UTC, lijiarui requested changes

2020-08-12 16:42 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rainbowbot.md
> + author: CavonCheng
yes, but you should change  `CavonCheng ` to `cavon-cheng`, it should be same as the markdown filename, or it cannot find your profile page correctly.

2020-08-13 14:33 UTC, CavonCheng commented on _posts/2020-07-28-wechaty-rainbowbot.md
> + author: CavonCheng
@lijiarui Oh,I see. It will be fixed soon!

2020-08-13 14:40 UTC, huan commented
@CavonCheng your profile filename on our website should be `CavonCheng.md` because your GitHub username is CavonCheng.

You should change all your usernames on our website to be exactly the same as your GitHub username. This requirement will make sure our blog posts can be connected to your developer profile and the GitHub correctly.

This requirement will be enforced in the future by checking in the CI scripts.

CC @lijiarui

2020-08-13 14:40 UTC, CavonCheng commented
@lijiarui Hi,I have fixed the author name in md file, please review it. Thank you very much!

2020-08-13 14:49 UTC, CavonCheng commented
@huan Haha, no problem,I will change it back right now.

2020-08-13 15:01 UTC, huan commented
@CavonCheng thanks for the understanding, and appreciate your patient! Our website is still under heavy refactoring, I hope we can start writing and then bring our CI script online soon.

2020-08-13 15:19 UTC, CavonCheng commented
@huan That`s great, hope the website refactoring going successfully. Now I have updated my code , waiting for your review.

2020-08-14 10:45 UTC, merged

2020-08-14 10:45 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

2020-08-15 08:37 UTC, CavonCheng commented
@lijiarui  Hi, I have added your wechat. Waiting for your invitation, thanks a lot!