Bikaiqiao blog
wechaty/docusaurus pull request #390
Opened 2020-07-28 10:43 UTC by bikaiqiao

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-07-28 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=390) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=390) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=390) it.</sub>

2020-08-10 13:27 UTC, lijiarui commented
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-17 06:51 UTC, lijiarui commented
ping @bikaiqiao Please change as I request.

2020-08-18 00:10 UTC, bikaiqiao commented
revise  complete

2020-08-20 09:30 UTC, lijiarui requested changes
Please change as I request, thanks!

2020-08-20 09:30 UTC, lijiarui commented on _data/authors.yml
> +  name       : "bikaiqiao"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-20 09:30 UTC, lijiarui commented on _developers/bikaiqiao.md
> +twitter: https://weibo.com/u/6987901535
It could be better your you could add more content in your profile, then other contributors could know you better!

2020-08-20 09:30 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rpa-kuaishou-plan.md
> +categories：project
Please add a soc tag and a image for the blog.

2020-08-20 14:35 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 14:35 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rpa-kuaishou-plan.md
> +  - kuaishou
Please add a soc tag here.

2020-08-21 12:55 UTC, huan commented on _posts/2020-08-20-wechaty-puppet-kuaishou-mid-term.md
> +<iframe src="//player.bilibili.com/player.html?aid=541809823&bvid=BV1ei4y1g7og&cid=226344965&page=1" width="560" height="315" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscre
I'd like to suggest that you can start using the new `iframe` segment feature publish from @univerone today!

2020-08-21 14:35 UTC, lijiarui requested changes

2020-08-21 14:35 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rpa-kuaishou-plan.md
> +  - kuaishou
ping

2020-08-21 15:12 UTC, lijiarui requested changes

2020-08-21 15:12 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rpa-kuaishou-plan.md
> +  - kuaishou
you cannot resolve this conversation since you didn't fix this.

2020-08-22 04:46 UTC, BikeJooe commented
I think I have fixed it

2020-08-22 07:16 UTC, lijiarui requested changes
You didn't fix all of my requests. Please change as I request.

2020-08-22 07:16 UTC, lijiarui commented on _posts/2020-07-28-wechaty-rpa-kuaishou-plan.md
> +  - kuaishou
No, you didn't add `soc` and `soc2020` tag here, as I requested before.

2020-08-22 07:16 UTC, lijiarui commented on _posts/2020-08-20-wechaty-puppet-kuaishou-mid-term.md
> +  - kuaishou
Please add `soc` and `soc2020` tag here.

2020-08-22 07:16 UTC, lijiarui commented on _posts/2020-08-20-wechaty-puppet-kuaishou-mid-term.md
> +image: /assets/2020/wechaty-puppet-kuaishou/wechaty-puppet-kuaishou-logo.jpeg
This image should separate with the other blog image. You cannot use one image in two blog.

2020-08-22 10:41 UTC, BikeJooe commented on _posts/2020-07-28-wechaty-rpa-kuaishou-plan.md
> +  - kuaishou
sorry,I will add it now

2020-08-22 11:22 UTC, BikeJooe commented on _posts/2020-08-20-wechaty-puppet-kuaishou-mid-term.md
> +  - kuaishou
I add it just now,plese check it

2020-08-22 11:54 UTC, lijiarui requested changes
Please change as I request.

2020-08-22 11:54 UTC, lijiarui commented on _posts/2020-08-20-wechaty-puppet-kuaishou-mid-term.md
> +image: /assets/2020/wechaty-puppet-kuaishou/wechaty-puppet-kuaishou-logo2.jpeg
Each blog should have its separate image folder to store a separate image.

So you should create a new folder called `wechaty-puppet-kuaishou-mid-term` for the image.

2020-08-22 14:14 UTC, BikeJooe commented on _posts/2020-08-20-wechaty-puppet-kuaishou-mid-term.md
> +image: /assets/2020/wechaty-puppet-kuaishou/wechaty-puppet-kuaishou-logo2.jpeg
ok,it's done

2020-08-23 07:29 UTC, lijiarui approved these changes
Good job

2020-08-23 07:30 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

![image](https://user-images.githubusercontent.com/6419514/90973562-bc28e900-e555-11ea-8175-6c8e2bd3d126.png)

2020-08-23 07:30 UTC, merged