wechaty-plugin-xyao [give bot ability to handle instruction distributed]
wechaty/docusaurus pull request #399
Opened 2020-08-01 06:53 UTC by watertao

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-01 06:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=399) it.</sub>

2020-08-10 13:27 UTC, lijiarui commented
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-10 14:37 UTC, watertao commented
@lijiarui Thanks for review, my profile has been committed.

2020-08-12 01:42 UTC, lijiarui requested changes
Good job!

Please change as I request.

2020-08-12 01:42 UTC, lijiarui commented on _posts/2020-08-01-wechaty-distribute-instruction-handler.md
> +![sample](../assets/2020/wechaty-plugin-xyao/interaction-sample.png)
no need to add `..`

2020-08-12 01:42 UTC, lijiarui commented on _posts/2020-08-01-wechaty-distribute-instruction-handler.md
> +![architecture](../assets/2020/wechaty-plugin-xyao/arc.png)
no need to add `..`

2020-08-12 04:11 UTC, watertao commented
@lijiarui image link has been corrected

2020-08-12 16:40 UTC, lijiarui requested changes

2020-08-12 16:40 UTC, lijiarui commented on _data/authors.yml
> +
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-13 02:26 UTC, watertao commented
fail to exclude authors.yml from this pr, so close it and recreate a new pull request

2020-08-13 02:26 UTC, closed without merging