add a blog
wechaty/docusaurus pull request #400
Opened 2020-08-02 10:16 UTC by wengcan

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-02 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=400) before we can accept your contribution.<br/><hr/>**wengcan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=400) it.</sub>

2020-08-10 13:24 UTC, lijiarui commented
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-10 13:25 UTC, lijiarui commented
Please sign the CLA first then I can review your blog!

Thanks!

2020-08-11 03:39 UTC, wengcan commented
> Please sign the CLA first then I can review your blog!
> 
> Thanks!

Hi @lijiarui 

I had already signed the CLA, please have a check.

Thanks

2020-08-12 01:43 UTC, lijiarui commented
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-13 05:16 UTC, wengcan commented
Hi @lijiarui ,
my profile file had been added in the _developers folder, please have a check.

2020-08-14 10:48 UTC, lijiarui requested changes
Please change as I request, thanks!

2020-08-14 10:48 UTC, lijiarui commented on _data/authors.yml
> +wengcan:
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-15 15:35 UTC, wengcan commented
> Please change as I request, thanks!

updated, thanks

2020-08-16 11:43 UTC, lijiarui commented
It looks good me. 

@Huan Please check this blog.

2020-08-16 15:47 UTC, huan requested changes
Thank you very much for sharing your idea to the community, it's very valuable!

Please follow my reviews so that we can improve the quality of this post.

Looking forward to seeing your new version, cheers!

2020-08-16 15:47 UTC, huan commented on _developers/wengcan.md
> +
Please introduce yourself to the community by adding your bio and related information in your profile, thanks!

2020-08-16 15:47 UTC, huan commented on _posts/2020-08-02-wechaty-stock-bot.md
> +git clone https://github.com/wengcan/stock-bot.git
Please add the `[Powered by Wechaty]` badge to your README.md.

You can find the badge in README from the Wechaty repo.

2020-08-16 15:47 UTC, huan commented on _posts/2020-08-02-wechaty-stock-bot.md
> +⭐ 分析群聊内容，实时回复当前行情
Cloud you please describe your feature with more details, so that the reader can follow your idea without any difficulty?

2020-08-20 02:40 UTC, wengcan commented
Hi @huan , please review my change, thx

2020-08-20 12:32 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

![image](https://user-images.githubusercontent.com/6419514/90770364-4427ac80-e324-11ea-9dc3-f957b4c5256f.png)

2020-08-20 12:32 UTC, merged