add Rae-OA-Wechaty blog
wechaty/docusaurus pull request #405
Opened 2020-08-03 14:46 UTC by NorthSeacoder

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-10 13:23 UTC, lijiarui requested changes
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-12 02:30 UTC, lijiarui requested changes
Please change as I request.

2020-08-12 02:30 UTC, lijiarui commented on _data/authors.yml
> +
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-12 02:30 UTC, lijiarui commented on _developers/NorthSeacoder.md
> +---
You should change this to cavon-cheng, because our rule as follows:

>  Keep all filenames & url as lowercase, and use - to connect words instead of space. e.g. 2017-10-06-wechat-pc-impactor instead of 2017-10-06-WeChat PC Impactor

2020-08-12 02:30 UTC, lijiarui commented on _posts/2020-07-28-rae-oa-wechaty.md
> +author: NorthSeacoder
And here should be same as the markdown file name.

2020-08-12 02:30 UTC, lijiarui commented on _developers/NorthSeacoder.md
> +avatar: https://avatars2.githubusercontent.com/u/30330837?s=460&u=1cd6e7c560308a159cf25295d652e375924ddf7e&v=4
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-12 10:06 UTC, NorthSeacoder commented
![image](https://user-images.githubusercontent.com/30330837/90003122-3344be80-dcc6-11ea-9b4a-fb225bb2ffb4.png)
![image](https://user-images.githubusercontent.com/30330837/90003276-6e46f200-dcc6-11ea-899c-9fca9aff8eff.png)
sth may be wrong...

2020-08-12 17:11 UTC, lijiarui commented
Sorry for mis push since the blog immigration.

Could you upload your local file to this PR again and then I will be able to review this again.

Sorry again for my mistake.

2020-08-14 00:16 UTC, NorthSeacoder reviewed
fix

2020-08-14 10:50 UTC, lijiarui reviewed
Thanks for re-commit!

Please change as I request and then I can merge this PR.

2020-08-14 10:50 UTC, lijiarui commented on _data/authors.yml
>        url: "hoc0415@foxmail.com"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-14 13:03 UTC, NorthSeacoder reviewed
fixed

2020-08-16 11:21 UTC, lijiarui requested changes

2020-08-16 11:21 UTC, lijiarui commented on _developers/north-sea-coder.md
> +
I suggest adding more information at the developer page, in order to help other developers know you better.

2020-08-16 11:21 UTC, lijiarui commented on _developers/north-sea-coder.md
> +avatar: /assets/2020/rae-oa-wechaty/github-avatars.jpg
You should put your avatar at `/assets/developers/XXX/avatar.jpg`

2020-08-17 00:44 UTC, NorthSeacoder reviewed
fixed

2020-08-17 06:44 UTC, lijiarui commented
It looks good to me.

Please check this blog to see whether we could merge or not. @huan

2020-08-17 06:54 UTC, NorthSeacoder commented
finally.....

2020-08-20 12:31 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

![image](https://user-images.githubusercontent.com/6419514/90770316-2a866500-e324-11ea-9960-b9f7a070051f.png)

2020-08-20 12:32 UTC, merged