added a blog (twitter2wechat)
wechaty/docusaurus pull request #406
Opened 2020-08-06 03:21 UTC by afterever

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ x ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "twitter2wechat"
author: Steve
date: "2020-08-06 10:59:00 +0800"
categories: project
tags:
  - wechaty
  - wechaty-puppet-padplus
  - twitter
image: /assets/2020/wechaty-twitter2wechat/wechaty-twitter2wechat-header.jpg
---
> Author: [afterever](https://github.com/afterever)
> Code: [twitter2wechat](https://github.com/afterever/twitter2wechat)
```

- [ x ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ x ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ x ] Add `` section to just show the abstract in blog homepage.
- [ x ] Add teaser image for the blog
- [ x ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-06 03:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=406) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=406) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=406) it.</sub>

2020-08-06 15:30 UTC, huan commented
Thanks for the sharing, it's a great blog post and very valuable for our Wechaty community!

2020-08-10 13:20 UTC, lijiarui commented
Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-10 13:22 UTC, lijiarui requested changes
Thanks for the blog!

Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-10 15:03 UTC, afterever commented
谢谢Jiarui和Huan的正面评价。我很乐意加入Wechaty Contributor群，与Wechaty的开发者们进行更深度的交流沟通。
如果你们在北美有业务拓展的话，我也很乐意出一份力。

2020-08-12 02:31 UTC, lijiarui requested changes
Good job!

Please change as I request.

2020-08-12 02:31 UTC, lijiarui commented on _data/authors.yml
> +
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-12 02:31 UTC, lijiarui commented on _posts/2020-08-06-wechaty-twitter2wechat.md
> +author: Steve
Here should be same as the markdown file name.

So here should be `steve`

2020-08-12 02:34 UTC, lijiarui requested changes

2020-08-12 02:34 UTC, lijiarui commented on _developers/steve.md
> +avatar: https://avatars1.githubusercontent.com/u/38563149?s=400&u=467bd61f9d073d0975c15f73cfd5ef2acec02335&v=4
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-12 02:49 UTC, afterever commented on _data/authors.yml
> +
removed, effectively rolled back

2020-08-12 02:51 UTC, afterever commented on _developers/steve.md
> +avatar: https://avatars1.githubusercontent.com/u/38563149?s=400&u=467bd61f9d073d0975c15f73cfd5ef2acec02335&v=4
saved here /assets/2020/wechaty-twitter2wechat/steve.png, together with the blog post.

(saw the \assets\developers, looks too official for me, please let me know if you need me put there)

2020-08-12 02:52 UTC, afterever commented on _posts/2020-08-06-wechaty-twitter2wechat.md
> +author: Steve
changed to little case

2020-08-12 02:57 UTC, lijiarui requested changes

2020-08-12 02:57 UTC, lijiarui commented on _developers/steve.md
> +avatar: /assets/2020/wechaty-twitter2wechat/steve.png
This should be /assets/developers/steve.png

2020-08-12 03:01 UTC, lijiarui requested changes

2020-08-12 03:01 UTC, lijiarui commented on _posts/2020-08-06-wechaty-twitter2wechat.md
> +[![Header Picture](https://github.com/afterever/Twitter2Wechat/blob/master/images/small_headerline_twitter2wechat.jpg)](https://github.com/afterever/Twitter2Wechat/blob/master/images/Headerline_twitt
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-12 03:01 UTC, lijiarui commented on _posts/2020-08-06-wechaty-twitter2wechat.md
> +[![Core Code](https://github.com/afterever/Twitter2Wechat/blob/master/images/core_code.jpg)](https://github.com/afterever/Twitter2Wechat/blob/master/images/core_code.jpg)
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-12 03:01 UTC, afterever commented on _developers/steve.md
> +avatar: /assets/2020/wechaty-twitter2wechat/steve.png
followed your and huan's example
saved to \assets\developers\steve\avatar.png

2020-08-12 03:13 UTC, afterever commented on _posts/2020-08-06-wechaty-twitter2wechat.md
> +[![Header Picture](https://github.com/afterever/Twitter2Wechat/blob/master/images/small_headerline_twitter2wechat.jpg)](https://github.com/afterever/Twitter2Wechat/blob/master/images/Headerline_twitt
localized, this picture was in the \asses\
fixed the URL in md

2020-08-12 03:17 UTC, afterever commented on _posts/2020-08-06-wechaty-twitter2wechat.md
> +[![Core Code](https://github.com/afterever/Twitter2Wechat/blob/master/images/core_code.jpg)](https://github.com/afterever/Twitter2Wechat/blob/master/images/core_code.jpg)
added this file into \assets\2020\wechaty-twitter2wechat and linked into the markdown

2020-08-12 03:18 UTC, afterever commented
much appreciated to point all the errors I made. 

now should all be fixed, thanks so much!

2020-08-12 03:18 UTC, afterever commented
much appreciated to point all the errors I made. 

now should all be fixed, thanks so much!

2020-08-12 16:27 UTC, merged

2020-08-12 16:29 UTC, lijiarui commented
Good job! 

Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

![image](https://user-images.githubusercontent.com/6419514/90041504-f398c980-dcfb-11ea-8e77-ed67eb5e8e14.png)