added a blog - when grafana meet wechaty
wechaty/docusaurus pull request #415
Opened 2020-08-11 11:10 UTC by techxel

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-11 11:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=415) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=415) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.github.io?pullRequest=415) it.</sub>

2020-08-12 02:52 UTC, lijiarui commented
Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

remove `author.yml`

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-12 15:47 UTC, lijiarui commented
Please resolve the conflict and change as I request

2020-08-12 15:48 UTC, lijiarui requested changes

2020-08-12 15:48 UTC, lijiarui commented on _data/authors.yml
> +
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-14 11:07 UTC, lijiarui requested changes

2020-08-14 11:07 UTC, lijiarui commented on _developers/magina.md
> +---
It could be better for you to add more information in your profile, it can make other developers know you better!

2020-08-16 11:51 UTC, lijiarui commented
Please sign the CLA firs then I can look into this PR.

2020-08-17 01:26 UTC, techxel commented
![image](https://user-images.githubusercontent.com/13285703/90349214-9ab69180-e06b-11ea-9b9b-1e7e17fb0e2b.png)

I have already signed, but I didn't whether something wrong about it?

2020-08-17 01:44 UTC, techxel commented
I think maybe this user which belongs yours also need sign

![image](https://user-images.githubusercontent.com/13285703/90349985-44971d80-e06e-11ea-82b6-c93f75eb3be8.png)

2020-08-17 04:05 UTC, lijiarui commented
You should check your username and your email. These two should be unified.

2020-08-17 05:54 UTC, techxel commented
I have signed before, at that time everything seems well, when TbhT came to merge, the sign started to be pending.

![image](https://user-images.githubusercontent.com/13285703/90361569-242c8a80-e091-11ea-9125-f40c75699674.png)

2020-08-17 05:57 UTC, techxel commented
It's obvious the user TbhT didn't sign

2020-08-17 06:56 UTC, lijiarui commented
If `TbhT` should sign, it means this commit is related to `TbhT`, but your PR should not related to other developer's commit.

Or you can create a new PR.

The precondition of our review is that everyone related to this PR has signed the CLA.

2020-08-17 07:39 UTC, huan commented
@TbhT Please sign the SLA under Wechaty org because you have synced the master commits to the branch from @techxel, which blocked this PR to pass the CLA check.

Thank you very much.

2020-08-17 12:09 UTC, TbhT commented
> @TbhT Please sign the SLA under Wechaty org because you have synced the master commits to the branch from @techxel, which blocked this PR to pass the CLA check.
> 
> Thank you very much.

DONE.

2020-08-17 12:25 UTC, lijiarui commented
As I requested before, please change as I request.

```
It could be better for you to add more information to your profile, it can make other developers know you better!
```

2020-08-17 13:17 UTC, techxel commented
> As I requested before, please change as I request.
> 
> ```
> It could be better for you to add more information to your profile, it can make other developers know you better!
> ```

I have already added before, I also find most of the authors weren't so detail as for me. I don't want to publish so much information on the Internet, just want to make some contributions to the project, don't want others to know me. you have rejected me several times, just for the personal information. I think it's not crucial for this project to force people doing something like this

2020-08-19 01:45 UTC, closed without merging

2020-08-21 15:38 UTC, huan commented
Hi @techxel !

I'm sorry to see that you canceled your PR due to the review process. You have almost finished all the steps: CLA is signed, CI is green, everything will be ok.

Our previous rejection is not because of your personal information, it's mainly because of the CLA and the CI staff, your developer profile is totally controlled by yourself, and please feel free to add more information to it or not.

So please feel free to create another PR or reopen this PR to submit your great post again, you will be always welcome to come back.

Have a great weekend!

2020-08-27 07:53 UTC, techxel commented
@huan  thanks, so good guy you are, and also fairly professional. I appreciated finding this project, and also want to participate in the python and go versions' development, but for some reason and I have my job. I hope this project will be better and better. I have persuaded my friend to buy your token, it's rewarding to pay for such a wonderful product. So I think this way is the best support for you and your partners.