Kxz blog
wechaty/docusaurus pull request #454
Opened 2020-08-14 13:29 UTC by kxz18

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
---
> Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

2020-08-14 13:46 UTC, kxz18 commented
I forgot to update from upstream, which caused the conflicts. I didn't edit the two files which brought up conflicts, so just keep the master branch version of these two files.

2020-08-16 11:24 UTC, lijiarui commented
Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

Remove `author.yml`

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

2020-08-16 12:50 UTC, lijiarui requested changes

2020-08-16 12:50 UTC, lijiarui commented on _developers/kxz18.md
>  avatar: /assets/developers/kxz18/avatar.png
Where is this file?

2020-08-16 12:50 UTC, lijiarui commented on _posts/2020-08-14-python-wechaty-groupchat-assistant-bot-poc.md
> + categories: project
Please add a soc tag here. e.g.:
```
tags:
  - soc
```

2020-08-16 12:50 UTC, lijiarui commented on _posts/2020-08-14-python-wechaty-groupchat-assistant-bot-poc.md
> +    teaser: /assets/2020/groupchat-assistant-bot/header.jpeg
Where is this file?

2020-08-16 13:00 UTC, kxz18 commented on _developers/kxz18.md
>  avatar: /assets/developers/kxz18/avatar.png
I found It's already in /assets/developers/kxz18/avatar.png when I pulled from upstream.

2020-08-16 13:14 UTC, kxz18 commented on _posts/2020-08-14-python-wechaty-groupchat-assistant-bot-poc.md
> + categories: project
In the new commit I have add the tags.

2020-08-16 13:15 UTC, kxz18 commented on _posts/2020-08-14-python-wechaty-groupchat-assistant-bot-poc.md
> +    teaser: /assets/2020/groupchat-assistant-bot/header.jpeg
This file was uploaded in last pull request (plan blog).

2020-08-16 13:52 UTC, lijiarui requested changes

2020-08-16 13:52 UTC, lijiarui commented on _posts/2020-08-14-python-wechaty-groupchat-assistant-bot-poc.md
> + image: /assets/2020/groupchat-assistant-bot/header.jpeg
Well, I think you should create a new file for this blog.

2020-08-16 14:27 UTC, kxz18 commented on _posts/2020-08-14-python-wechaty-groupchat-assistant-bot-poc.md
> + image: /assets/2020/groupchat-assistant-bot/header.jpeg
New file has been uploaded in latest commit.

2020-08-17 04:12 UTC, lijiarui approved these changes
Good job!

2020-08-17 06:45 UTC, lijiarui commented
@kxz18 Please make ci green first.

2020-08-17 07:16 UTC, lijiarui approved these changes
Good job！

2020-08-17 07:17 UTC, merged