Modify iframe
wechaty/docusaurus pull request #466
Opened 2020-08-17 09:23 UTC by univerone

Fixes issue #459  .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

add a new fragment `iframe.html`, which accept two parameters: the link of iframe and the ratio of height compared to width.you can use this fragment in post markdown file like

```
{% include iframe.html src="/assets/js/viewer-js/#/assets/2020/wechaty-words-per-day-plugin-mid-term/presentation.pdf" width="60%" %}
```

![Screenshot_2020-08-17 暑期2020  编写一个“每日一句”插件  POC 成果展示](https://user-images.githubusercontent.com/35693452/90380010-19ccb980-e0ae-11ea-955b-8cf3d2e366b3.png)

 If insert a bilibili video ,the recommended width ratio is 70%, while youtube ratio is 56.25%

2020-08-17 19:20 UTC, huan requested changes
Hi @univerone ,

I believe this is a great new feature to our blog system, thank you for your valuable PR!

I have some comments for this PR, let's improve it a little bit so that we will be able to merge it.

2020-08-17 19:20 UTC, huan commented on _includes/iframe.html
> +    padding-bottom:{{include.width}};
Cloud you please explain why you are using `include.width` as the `padding-bottom` at here?

2020-08-17 19:20 UTC, huan commented on _includes/iframe.html
> +    src="{{ include.src }}"
Does this mean the `include` variable will holds all the parameters?

Could you please provide a Jekyll document link about this feature, thank you very much.

2020-08-17 19:20 UTC, huan commented on _posts/2020-08-15-wechaty-words-per-day-plugin-mid-term.md
> +date: 2020-08-15 20:00
The `date` field is not necessary for all our posts.

It should be removed.

2020-08-17 19:20 UTC, huan commented on _posts/2020-08-15-wechaty-words-per-day-plugin-mid-term.md
> +{% include iframe.html src="//player.bilibili.com/player.html?aid=201701469&bvid=BV1ih411d75h&cid=224470522&page=1" width="70%" %}
This new `iframe` fragment is great, you are very smart to add this new feature to our blog system!

I have two comments for it:

1. As you have mentioned in your description:

> If insert a bilibili video, the recommended width ratio is 70%, while youtube ratio is 56.25%

Can we make this ratio value to be automatically set to the right default value when it has not been provided? Because that will make this feature more convenient for our writers. (and myself)

For example, if the src is a YouTube video, we can set it to 56.25%, and if it's a Bilibili, will be set to 70%

2. And also, I think we should find a better name to replace `width` because the `width` is always a pixel number or the ratio to the total width to the parent element. In our case here, it's a ratio to the height.

Anyway, good job!

2020-08-18 07:59 UTC, univerone commented on _includes/iframe.html
> +    src="{{ include.src }}"
Here is relevent document https://jekyllrb.com/docs/includes/ , I don't know if `include` is a variable, it seems like `{{ include.src }}` is used to get the value of  `src` parameter

2020-08-18 08:10 UTC, univerone commented on _includes/iframe.html
> +    padding-bottom:{{include.width}};
Actually, It's the relative height of compared to it's width. I'll change the name of this parameter. Here is [relevant  tutorial ](https://www.cnblogs.com/Wayou/p/css_keep_ratio_by_padding_bottom.html), I just quote the style of  lijiarui's post

2020-08-19 08:29 UTC, huan commented on _includes/iframe.html
> +    {% if include.type == "bilibili" %}
Could we keep the code DRY here?

I mean, how about let's save the ratio (70% or 56.25%) to a variable, then we will be able to write:

```
padding-bottom: {% ratio %};
```

2020-08-19 08:32 UTC, huan commented on _posts/2020-08-15-wechaty-words-per-day-plugin-mid-term.md
> +{% include iframe.html src="BV1ih411d75h" type="bilibili" %}
Could we be able to support just put the original embed code here?

I mean, it's complicated for the user to extract the `id` out from the original url.

I'd like to suggest that we can just put the whole URL as src, and let our program to extract the id out:

```
{% include iframe.html src="https:////player.bilibili.com/player.html?bvid=BV1ih411d75h" type="bilibili" %}
```

And to be better:

```diff
```
- {% include iframe.html src="https:////player.bilibili.com/player.html?bvid=BV1ih411d75h" type="bilibili" %}
+ {% include iframe.html src="https:////player.bilibili.com/player.html?bvid=BV1ih411d75h" %}
```

The above code should be cleaner because we can get to know what kind of that video is from the `src`.
```

2020-08-19 08:34 UTC, huan commented on _posts/2020-08-15-wechaty-words-per-day-plugin-mid-term.md
> +{% include iframe.html src="/assets/2020/wechaty-words-per-day-plugin-mid-term/presentation.pdf" type="pdf" %}
It would be great if we can support identify the `type` automatically because the src will contain that information?

2020-08-19 08:35 UTC, huan requested changes
Let's keep improving your PR, it will be a great tool for our future blog writers!

2020-08-19 08:37 UTC, huan commented
Great work, I believe this component(include segment) will be a great time saver!

2020-08-20 13:28 UTC, univerone commented on _includes/iframe.html
> +    {% if include.type == "bilibili" %}
That‘s good！

2020-08-20 13:29 UTC, univerone commented on _posts/2020-08-15-wechaty-words-per-day-plugin-mid-term.md
> +{% include iframe.html src="BV1ih411d75h" type="bilibili" %}
Sure, use original url is more convenient

2020-08-20 19:11 UTC, huan commented on _includes/iframe.html
> +<div style="
I'd like to suggest that we can have a `case/when` at the beginning to make the code easier to read and maintain in the future.

for example:

```
{% assign src = include.src %}
{% assign ratio = 56.25% %}

{% assign type = '... ' /* 'pdf', 'v.qq.com', 'youtube', 'bilibili', or other types which can be supported in the future */ %}

{% case type %}
  {% when ".pdf" %}
    {% assign src = '/assets/js/viewer-js/#' | append: include.src %}
  {% when "v.qq.com" %}
  {% when "youtube.com" %}
  {% when "bilibili.com" %}
    {% assign ratio = 70% %}
  {% else %}
{% endcase %}
```

2020-08-20 19:12 UTC, huan commented on _includes/iframe.html
> +    {% assign include.src = '/assets/js/viewer-js/#' | append: include.src %}
Move this code at the top of the file. (before `case/when`)

2020-08-20 19:13 UTC, huan requested changes
Great improvement!

Please follow my reviews and let's continue improving the code of the iframe segment!

2020-08-21 04:46 UTC, huan requested changes

2020-08-21 04:46 UTC, huan commented on _includes/iframe.html
> +{% assign src = include.src %}
The code that you have refactored is very beautiful!

Could you please add some comments on the top of this file, so that it can explain what your code is doing and why it design like this so that the future developer who wants to improve it will be easy to go?

I believe this PR will be able to be merged after you have added those docs.

Thank you very much for this great improvement!

2020-08-21 04:51 UTC, univerone commented on _includes/iframe.html
> +{% assign src = include.src %}
Sure! I'll use [liquid style comment](https://shopify.github.io/liquid/tags/comment/), and your comment is really valuable that I  can also benefit from this

2020-08-21 06:37 UTC, huan approved these changes
The comment is very clear, and the code I believe is clean enough for ready to be merged!

One more thing: please add your name as the author information in the comments!

After that, I'll merge this PR and let's enjoy your new `iframe` segment feature in our future posts!

2020-08-21 11:13 UTC, huan approved these changes
LGTM

2020-08-21 11:16 UTC, huan commented
@univerone Thank you very much for this great new feature, your iframe segment will help future writers save lots of time and prevent lots of mistakes too!

I believe this PR desires a blog post to publish this new feature so that we can make more contributors know how to use it. Would you like to write this blog to announce this powerful new feature released by you?

2020-08-21 11:16 UTC, merged

2020-08-21 11:25 UTC, univerone commented
> @univerone Thank you very much for this great new feature, your iframe segment will help future writers save lots of time and prevent lots of mistakes too!
> 
> I believe this PR desires a blog post to publish this new feature so that we can make more contributors know how to use it. Would you like to write this blog to announce this powerful new feature released by you?

I'd like to!

2020-08-21 11:29 UTC, huan commented
Awesome, great to know you like to write this blog post to announce the `iframe`, and I'm looking forward to reading your announcement blog post!