added a blog
wechaty/docusaurus pull request #469
Opened 2020-08-17 10:20 UTC by smwsk

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-17 11:42 UTC, lijiarui requested changes
Please change as I request.

2020-08-17 11:42 UTC, lijiarui commented on _data/authors.yml
> +  links:
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-17 11:42 UTC, lijiarui commented on _developers/smwsk.md
> +avatar: /assets/developers/smwsk/avatar.png
Where is this file?

2020-08-17 11:42 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-bot.md
> +image: /assets/2020/qijibot/qijibot.jpg
Where is this file?

2020-08-17 11:42 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-bot.md
> +<img src="../assets/2020/smwsk-java-wechaty-bot/results_1.jpg" width="300" alt="讲笑话-听歌"/>
should remove to `..`

2020-08-17 11:42 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-bot.md
> +<img src="../assets/2020/smwsk-java-wechaty-bot/results_2.jpg" width="300" alt="新闻-成语接龙"/>
should remove to `..`

2020-08-17 11:42 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-bot.md
> +<img src="../assets/2020/smwsk-java-wechaty-bot/results_3.jpg" width="300" alt="心理年龄测试"/>
should remove to `..`

2020-08-17 11:42 UTC, lijiarui commented on _developers/smwsk.md
> +JAVA 攻城狮
It would be better if you could add more profile, then other developers could know you better.

2020-08-17 12:27 UTC, smwsk commented on _developers/smwsk.md
> +JAVA 攻城狮
thank i will modifyit

2020-08-17 12:46 UTC, smwsk commented on _data/authors.yml
> +  links:
have removed

2020-08-17 12:47 UTC, smwsk commented on _developers/smwsk.md
> +avatar: /assets/developers/smwsk/avatar.png
has commit in https://github.com/smwsk/wechaty.js.org/blob/smwsk-blog/assets/developers/smwsk/avatar.jpg

2020-08-17 12:48 UTC, smwsk commented on _posts/2020-08-17-java-wechaty-bot.md
> +image: /assets/2020/qijibot/qijibot.jpg
has change it

2020-08-17 12:48 UTC, smwsk commented on _posts/2020-08-17-java-wechaty-bot.md
> +<img src="../assets/2020/smwsk-java-wechaty-bot/results_2.jpg" width="300" alt="新闻-成语接龙"/>
thank i have removed

2020-08-17 13:07 UTC, lijiarui requested changes
Please change as I request and make Github Action green.

2020-08-17 13:07 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-bot.md
> +title: "   SpringBoot 搭建wechaty智能聊天机器"
Please remove the useless blank here.

2020-08-18 02:51 UTC, smwsk commented on _data/authors.yml
> +  links:
hello, i has resolved all question, can i look it in blog site what time see it

2020-08-19 00:56 UTC, smwsk commented
> Please change as I request and make Github Action green.

i look my pull request has pass the test& build , and i look my action status is pass in the actions list, i have other question? please tell me, thank

2020-08-20 09:14 UTC, lijiarui approved these changes
It seems good to me, please review this PR and give more comments. @huan

2020-08-20 12:27 UTC, merged

2020-08-20 12:27 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room