Java wechaty transplant midpoc
wechaty/docusaurus pull request #472
Opened 2020-08-17 15:54 UTC by cunkoulaocai

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-20 09:32 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 09:32 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-transplant-midpoc.md
> +| title                     | date                   | author       | categories | image                                                        | tags         |
Please add the blog as the template show, and then I can review your blog.

2020-08-20 09:32 UTC, lijiarui commented on _data/authors.yml
> +  avatar      : "https://avatars3.githubusercontent.com/u/30389241?s=460&u=99b73e1a68a668a56e0a567ffa33bb8c2e99b4bb&v=4"
Please change this author.yml to a developer file.

2020-08-21 15:02 UTC, lijiarui requested changes
ping

2020-08-21 15:02 UTC, lijiarui commented on _data/authors.yml
> +  avatar      : "https://avatars3.githubusercontent.com/u/30389241?s=460&u=99b73e1a68a668a56e0a567ffa33bb8c2e99b4bb&v=4"
ping

2020-08-21 15:02 UTC, lijiarui commented on _posts/2020-08-17-java-wechaty-transplant-midpoc.md
> +| title                     | date                   | author       | categories | image                                                        | tags         |
ping

2020-08-30 16:34 UTC, lijiarui commented
ping @cunkoulaocai

2020-08-31 03:27 UTC, cunkoulaocai commented
pong

2020-09-02 18:22 UTC, lijiarui commented
Could you change as I request as soon as possible? Since other soc contributors already posted their blog for a few weeks but you haven't posted even one blog!

I will close the PR if this PR has no new commit at the end of September.

2020-09-03 13:20 UTC, cunkoulaocai commented
我这边为什么渲染不出对应的格式
![image](https://user-images.githubusercontent.com/30389241/92120061-2c275100-ee2b-11ea-817a-388fc168ff1e.png)
![image](https://user-images.githubusercontent.com/30389241/92120104-39dcd680-ee2b-11ea-897a-effc1d575ef3.png)
我格式应该是正确的了

2020-09-03 13:46 UTC, closed without merging