added a blog
wechaty/docusaurus pull request #473
Opened 2020-08-18 06:35 UTC by m4d3bug

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-18 06:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=473) it.</sub>

2020-08-20 09:20 UTC, lijiarui requested changes
Please change as I request, thanks!

2020-08-20 09:20 UTC, lijiarui commented on _data/authors.yml
> +  name        : "ZSC - College of Computing"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-20 09:20 UTC, lijiarui commented on _posts/2020-08-18-wechaty-for-new-student.md
> +author: techial1042
This should be same as the developers file name, so it should be `techinal` or you change the developer file name to `techial1042`

2020-08-20 09:20 UTC, lijiarui commented on _developers/techial.md
> +bio: "Welcome to join ZSC"
It would be better if you could add more content at your profile page, then other developers could know you better.

2020-08-20 09:20 UTC, lijiarui commented on _posts/2020-08-18-wechaty-for-new-student.md
> +image: /assets/2020/wechaty-bot/header.jpg
Where is this file?

2020-08-20 09:43 UTC, m4d3bug commented on _posts/2020-08-18-wechaty-for-new-student.md
> +author: techial1042
changed it. : - )

2020-08-20 09:43 UTC, m4d3bug commented on _developers/techial.md
> +bio: "Welcome to join ZSC"
Added the Github link.

2020-08-20 09:43 UTC, m4d3bug commented on _posts/2020-08-18-wechaty-for-new-student.md
> +image: /assets/2020/wechaty-bot/header.jpg
you mean the header.jpg ?

2020-08-20 10:07 UTC, lijiarui commented on _posts/2020-08-18-wechaty-for-new-student.md
> +image: /assets/2020/wechaty-bot/header.jpg
yes.

2020-08-20 10:07 UTC, lijiarui commented
Please make github action green and then I can review this PR.

2020-08-22 06:31 UTC, m4d3bug commented on _posts/2020-08-18-wechaty-for-new-student.md
> +image: /assets/2020/wechaty-bot/header.jpg
on here. 
```bash
# file assets/2020/wechat-bot/header.jpg
assets/2020/wechat-bot/header.jpg: JPEG image data, baseline, precision 8, 55x55, components 3
```

2020-08-22 07:27 UTC, lijiarui requested changes
Please change as I request.

2020-08-22 07:27 UTC, lijiarui commented on _data/authors.yml
> +techial:
You should not commit this file in this PR, since we won't use this file anymore.

2020-08-22 07:27 UTC, lijiarui commented on _developers/techial1042.md
> +avatar: /assets/developers/techial/avatar.jpg
I suggest you change `techial/avatar.jpg` to `techial1042/avatar.jpg` too, same as your file name.

2020-08-22 07:27 UTC, lijiarui commented on _posts/2020-08-18-wechaty-for-new-student.md
> +image: /assets/2020/wechaty-bot/header.jpg
You write `wechaty-bot` here, but the image is `wechat-bot`. You should be more careful.

2020-08-24 04:41 UTC, m4d3bug commented on _posts/2020-08-18-wechaty-for-new-student.md
> +image: /assets/2020/wechaty-bot/header.jpg
> You write `wechaty-bot` here, but the image is `wechat-bot`. You should be more careful.

you are right, I just changed the path again. Please check it.

2020-08-24 06:54 UTC, m4d3bug commented on _developers/techial1042.md
> +avatar: /assets/developers/techial/avatar.jpg
changed it, please check.

2020-08-24 08:41 UTC, m4d3bug commented on _data/authors.yml
> +techial:
> You should not commit this file in this PR, since we won't use this file anymore.

Just removed it.

2020-08-30 16:35 UTC, lijiarui approved these changes

2020-08-30 16:35 UTC, lijiarui commented on _data/authors.yml
>        icon: "fas fa-fw fa-envelope-square"
Please remove this file since we don't use this file anymore.

2020-08-30 16:36 UTC, lijiarui requested changes
Please change as I request.

2020-08-31 05:37 UTC, m4d3bug commented on _data/authors.yml
>        icon: "fas fa-fw fa-envelope-square"
> Please remove this file since we don't use this file anymore.

Thank you for the reply, I removed the authors.yml and push again.

2020-09-02 18:53 UTC, lijiarui requested changes
Please remove `authors.yml` from the commit, see: https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

2020-09-03 03:21 UTC, m4d3bug commented
> Please remove `authors.yml` from the commit, see: https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

Removed it, please check.

2020-09-06 08:39 UTC, lijiarui requested changes
Please change as I request.

2020-09-06 08:39 UTC, lijiarui commented on _data/authors.yml
> -  avatar      : "https://avatars2.githubusercontent.com/u/3895924?s=460&v=4"
I mean remove this commit instead of removing this file.

This file should not appear at `files changed` part.

2020-09-08 06:52 UTC, m4d3bug commented on _data/authors.yml
> -  avatar      : "https://avatars2.githubusercontent.com/u/3895924?s=460&v=4"
> I mean remove this commit instead of removing this file.
> 
> This file should not appear at `files changed` part.

@lijiarui We remove the commit again, please help recheck again.

2020-09-10 13:38 UTC, lijiarui commented
Good job!

Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

2020-09-10 13:38 UTC, merged