go-wechaty plugin poc (soc)
wechaty/docusaurus pull request #476
Opened 2020-08-19 12:26 UTC by FINCTIVE

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-20 09:09 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 09:09 UTC, lijiarui commented on _data/authors.yml
>        icon: "fas fa-fw fa-link"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-20 09:09 UTC, lijiarui commented on _posts/2020-08-19-go-wechaty-plugin-poc.md
> +author: FINCTIVE
It could be better if you add more your profile at `_developers/FINCTIVE.md`

2020-08-21 15:04 UTC, lijiarui requested changes
ping

2020-08-21 15:04 UTC, lijiarui commented on _data/authors.yml
>        icon: "fas fa-fw fa-link"
ping

2020-08-21 15:04 UTC, lijiarui commented on _posts/2020-08-19-go-wechaty-plugin-poc.md
> +author: FINCTIVE
ping

2020-08-21 15:04 UTC, lijiarui commented on _posts/2020-08-19-go-wechaty-plugin-poc.md
> +  - soc
Please add a `soc2020` tag as well.

2020-08-21 15:31 UTC, FINCTIVE commented on _data/authors.yml
>        icon: "fas fa-fw fa-link"
:smile: OK, I got it. I removed all the old content.

2020-08-21 15:47 UTC, FINCTIVE commented on _posts/2020-08-19-go-wechaty-plugin-poc.md
> +author: FINCTIVE
It's added.

2020-08-21 15:47 UTC, FINCTIVE commented on _posts/2020-08-19-go-wechaty-plugin-poc.md
> +  - soc
> Please add a `soc2020` tag as well.

Added 😄

2020-08-22 07:13 UTC, lijiarui requested changes
Please change as I request.

2020-08-22 07:13 UTC, lijiarui commented on _data/authors.yml
> -    - label: "GitHub"
You should not commit this file on this PR since we don't use `author.yml` anymore.

2020-08-22 07:13 UTC, lijiarui commented on _developers/finctive.md
>  avatar: /assets/developers/FINCTIVE/avatar.png
You should  change this to `finctive/avatar.png` because of @huan commit here: https://github.com/wechaty/wechaty.js.org/commit/ce0db0da9478e38453f8a774c512c0117167dddf

2020-08-22 07:13 UTC, lijiarui commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
>  image: /assets/2020/go-wechaty-plugin-soc/2020-07-21-go-wechaty.png
Where is this file?

2020-08-22 07:13 UTC, lijiarui commented on _posts/2020-08-19-go-wechaty-plugin-poc.md
> +author: FINCTIVE
should change to `finctive`, see  https://github.com/wechaty/wechaty.js.org/commit/ce0db0da9478e38453f8a774c512c0117167dddf

2020-08-22 15:32 UTC, FINCTIVE commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
>  image: /assets/2020/go-wechaty-plugin-soc/2020-07-21-go-wechaty.png
> Where is this file?

Hi, it was commited.

2020-08-23 07:23 UTC, lijiarui requested changes
Please change as I request.

2020-08-23 07:23 UTC, lijiarui commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +  - soc
Please add a `soc2020` tag for this blog.

2020-08-23 07:23 UTC, lijiarui commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
>  image: /assets/2020/go-wechaty-plugin-soc/2020-07-21-go-wechaty.png
You should upload a separate image for this blog, instead of using other blog's image.

2020-08-23 15:43 UTC, FINCTIVE commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +  - soc
> Please add a `soc2020` tag for this blog.

It's added now :smile:

2020-08-23 15:44 UTC, FINCTIVE commented on _posts/2020-07-19-go-wechaty-plugin-dev-plan.md
>  image: /assets/2020/go-wechaty-plugin-soc/2020-07-21-go-wechaty.png
> You should upload a separate image for this blog, instead of using other blog's image.

Hi, it's renamed. It is a separate image for this blog now.

2020-08-30 16:33 UTC, lijiarui commented
Good job！

Please resolve the conflict first and then I can review this blog.

2020-09-02 18:34 UTC, lijiarui requested changes
Please change as I request.

2020-09-02 18:34 UTC, lijiarui commented on jekyll/_posts/2020-07-19-go-wechaty-plugin-dev-plan.md
>    - soc2020
It seems this blog has two tags here...

2020-09-02 18:34 UTC, lijiarui commented on jekyll/_posts/2020-08-19-go-wechaty-plugin-poc.md
> +image: /assets/2020/go-wechaty-plugin-soc/2020-08-19-go-wechaty.png
Please create a new folder called `go-wechaty-plugin-midterm` and put this image there.

Since two blogs should have its separate image folder.

2020-09-06 08:34 UTC, lijiarui requested changes
Please change as I request.

2020-09-06 08:34 UTC, lijiarui commented on jekyll/_posts/2020-07-19-go-wechaty-plugin-dev-plan.md
> +  - go
Please add a `go-wechaty` tag here.

2020-09-06 08:34 UTC, lijiarui commented on jekyll/_posts/2020-08-19-go-wechaty-plugin-poc.md
> +  - go
Please add a `go-wechaty` tag here.

2020-09-10 13:48 UTC, lijiarui commented
Please resolve all the changes as I request.  I suggest you contact your mentor to help you to fix all of the problems.

If your mentor doesn't approve your PR, I won't review your PR anymore.

2020-09-11 03:38 UTC, FINCTIVE commented
Hi, mentors. @dingdayu @dchaofei Please review my blog post. Thank you!

@lijiarui Sorry for bothering you for a month. I apologize for my silly mistakes.

2020-09-16 04:25 UTC, dingdayu approved these changes
LGTM

2020-09-17 04:57 UTC, merged

2020-09-17 04:57 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room