add a blog
wechaty/docusaurus pull request #480
Opened 2020-08-20 07:49 UTC by Nebell

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-20 10:04 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 10:04 UTC, lijiarui commented on _data/authors.yml
> +  name        : "Tang Guangbin"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-08-20 10:04 UTC, lijiarui commented on _posts/2020-8-20-go-wechaty-github-action-optimization-mid-term.md
> +image: /assets/2020/go-wechaty-github-action-optimization/header.png
Where is this image?

2020-08-22 07:20 UTC, lijiarui commented
Please resolve the conflict first.

2020-08-23 07:20 UTC, lijiarui requested changes
Please change as I request.

2020-08-23 07:20 UTC, lijiarui commented on _developers/TangGuangbin.md
> +name: Tang Guangbin
You should change this file to tangguangbin, because our rule as follows:

>  Keep all filenames & url as lowercase, and use - to connect words instead of space. e.g. 2017-10-06-wechat-pc-impactor instead of 2017-10-06-WeChat PC Impactor

2020-08-23 07:20 UTC, lijiarui commented on _developers/TangGuangbin.md
> +avatar: /assets/developers/TangGuangbin/avatar.jpg
Please change folder name as our filename rule.

2020-08-30 07:06 UTC, Nebell commented
Please review.

2020-08-30 16:31 UTC, lijiarui requested changes
Please change as I request.

2020-08-30 16:31 UTC, lijiarui commented on _developers/tangguangbin.md
> +avatar: /assets/developers/TangGuangbin/avatar.jpg
You should change `TangGuangbin ` to `tang-guangbin ` to follow wechaty file name rules.

2020-08-30 16:31 UTC, lijiarui commented on _posts/2020-08-20-go-wechaty-github-action-optimization-mid-term.md
> +author: TangGuangbin
The author name should same as the author file, so you should change to `tangguangbin`

2020-08-30 16:31 UTC, lijiarui commented on _posts/2020-08-20-go-wechaty-github-action-optimization-mid-term.md
> +  - soc
Please add a `soc2020`  and `go-wechaty`tag here.

2020-08-31 00:45 UTC, Nebell commented on _developers/tangguangbin.md
> +avatar: /assets/developers/TangGuangbin/avatar.jpg
I change it to 'tangguangbin'.

2020-09-01 23:24 UTC, Nebell commented
Please review.

2020-09-02 18:41 UTC, lijiarui requested changes
Please change as I request.

Since @huan change the file at b5d981a8a218f684dfc92017e3aa1be1d18392ea

You should move all of the files under `jekyll`. For example:

move `_developers/tangguangbin.md` to `jekyll/_developers/tangguangbin.md`

2020-09-02 18:41 UTC, lijiarui commented on _posts/2020-08-20-go-wechaty-github-action-optimization-mid-term.md
> +  - go-wechaty
Please add a `soc` tag here.

2020-09-06 01:57 UTC, Nebell commented
Please review.

2020-09-06 08:13 UTC, lijiarui commented
Good job!

Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

2020-09-06 08:13 UTC, merged