added a blog
wechaty/docusaurus pull request #481
Opened 2020-08-20 08:54 UTC by przzl

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-20 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=481) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=481) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=481) it.</sub>

2020-08-20 09:41 UTC, lijiarui commented
Please make github action green first and then I can review this PR.

2020-08-20 11:23 UTC, przzl commented
> Please make github action green first and then I can review this PR.

is ok 。 any others？

2020-08-20 12:07 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 12:07 UTC, lijiarui commented on _data/authors.yml
> +  avatar     : "https://avatars.githubusercontent.com/u/52693821?s=460&v=4"
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

And please add a developer profile under the `_developers` folder.

2020-08-20 12:07 UTC, lijiarui commented on _posts/2020-08-20-wechaty-file-assistant-bot.md
> +
Please remove the useless row here and add blank as other blog show.

2020-08-20 12:07 UTC, lijiarui commented on 资产/2020年/file-assistant-bot
> +
What is this file?

2020-08-21 06:41 UTC, przzl commented on _data/authors.yml
> +  avatar     : "https://avatars.githubusercontent.com/u/52693821?s=460&v=4"
OK

2020-08-21 06:41 UTC, przzl commented on _posts/2020-08-20-wechaty-file-assistant-bot.md
> +
OK

2020-08-21 15:06 UTC, lijiarui requested changes
Please change as I request.

2020-08-21 15:06 UTC, lijiarui commented on 资产/2020年/file-assistant-bot
> +
You cannot resolve this conversation since you didn't remove this file.

2020-08-21 15:07 UTC, lijiarui requested changes
Please change as I request.

2020-08-22 08:15 UTC, przzl commented
> Please change as I request.

is ok

2020-08-22 09:21 UTC, lijiarui approved these changes
Good job

2020-08-22 09:21 UTC, merged

2020-08-22 09:22 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

![image](https://user-images.githubusercontent.com/6419514/90953214-12d1ec80-e49c-11ea-9475-e8abb7ed91a9.png)