Midterm blog
wechaty/docusaurus pull request #483
Opened 2020-08-20 10:05 UTC by Sapio-S

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-20 10:08 UTC, lijiarui requested changes
Please change as I request.

2020-08-20 10:08 UTC, lijiarui commented on _posts/2020-08-19-puppet-work-midterm.md
> +image: /assets/2020/work-puppet/pic.jpg
Where is this image?

2020-08-20 10:22 UTC, Sapio-S commented on _posts/2020-08-19-puppet-work-midterm.md
> +image: /assets/2020/work-puppet/pic.jpg
图片应该在前一个pull request里面（两个blog共用一张图）

2020-08-20 11:52 UTC, lijiarui commented on _posts/2020-08-19-puppet-work-midterm.md
> +image: /assets/2020/work-puppet/pic.jpg
Each blog should have it's separate image. Please upload a new image for this blog.

2020-08-20 15:02 UTC, Sapio-S commented on _posts/2020-08-19-puppet-work-midterm.md
> +image: /assets/2020/work-puppet/pic.jpg
好的，已经重新添加了图片。麻烦您了！

2020-08-21 15:09 UTC, lijiarui requested changes
Please change as I request and resolve the conflict, thanks!

2020-08-21 15:09 UTC, lijiarui commented on _posts/2020-08-19-puppet-work-midterm.md
> +  - Soc2020
Please add soc tag as well and change `Soc2020` to `soc2020`

2020-08-30 16:27 UTC, lijiarui commented
Please make CI green and resolve the conflict, and then I can review this blog.

2020-09-27 16:03 UTC, Sapio-S reviewed
抱歉我发现产生冲突的文件无法删除……请问有没有别的办法可以删除，还是只能重新提交一个pull request了呢？

2020-10-03 09:06 UTC, lijiarui commented
Yes, you can create a new one.

2020-10-03 09:35 UTC, lijiarui commented
@wj-Mcat  Please help @Sapio-S  posting his blog.

2020-10-04 02:09 UTC, wj-Mcat commented
Please close this issue and create new one.  If you have not completed this issue in next week, we will close this issue. Thanks for your attention.

2020-10-05 04:29 UTC, closed without merging