added a blog
wechaty/docusaurus pull request #487
Opened 2020-08-21 15:59 UTC by GilesWong

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [√ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [√ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ √] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ √] Add teaser image for the blog
- [ √] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-21 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=487) <br/>All committers have signed the CLA.

2020-08-21 17:13 UTC, GilesWong commented
@CLAassistant Hi, there! I have signed the CLA. Thanks!

2020-08-22 05:52 UTC, lijiarui requested changes
Please change as I request.

2020-08-22 05:52 UTC, lijiarui commented on _data/authors.yml
> +  bio         : "For a better me"
Please remove this file and create an `author.md` file under the `_developers` folder as other contributors did.

2020-08-22 05:52 UTC, lijiarui commented on _posts/2020-08-21-wechaty-xiaowang-learning-tool.md
> +image: https://avatars0.githubusercontent.com/u/13916856?s=60&v=4
You should localize this file in order to a future 404 error.

Since github image cannot be open at GFW, so you should localize github file too!

2020-08-22 06:32 UTC, GilesWong commented
@lijiarui Hi! I have changed my commit according to your request. Thank you.

2020-08-22 07:23 UTC, lijiarui requested changes
Please change as I request.

2020-08-22 07:23 UTC, lijiarui commented on _data/authors.yml
> -  links:
You should not commit `author.yml` on this PR.

2020-08-22 07:23 UTC, lijiarui commented on _posts/2020-08-21-wechaty-xiaowang-learning-tool.md
>  author: GilesWong
You should change this to `gileswong` because this should be the same as the developer file, or it cannot link the profile to the blog.

2020-08-22 08:02 UTC, GilesWong commented
@lijiarui I've checked out the original `_authors.yml` from master branch and it is not a changed file in this commit anymore.

2020-08-22 09:20 UTC, lijiarui requested changes

2020-08-22 09:20 UTC, lijiarui commented on _posts/2020-08-21-wechaty-xiaowang-learning-tool.md
> +image: /assets/developers/gileswong/avatar.png
You should add an image for this blog instead of just using your avatar.

2020-08-22 11:07 UTC, GilesWong commented
@lijiarui Teaser image added.

2020-08-22 11:55 UTC, lijiarui approved these changes
LGTM

2020-08-22 11:55 UTC, merged

2020-08-22 11:57 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

![image](https://user-images.githubusercontent.com/6419514/90955630-a6fa7e80-e4b1-11ea-8a20-b177f8986245.png)