Wangjunwei blog fix some bugs
wechaty/docusaurus pull request #490
Opened 2020-08-22 16:44 UTC by gavinwang23

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-22 17:17 UTC, gavinwang23 commented
Sorry,I found something went wrong in my blog,so I altered some files.please check and Merging it

2020-08-23 07:19 UTC, lijiarui requested changes
Please change as I request.

2020-08-23 07:19 UTC, lijiarui commented on _posts/2020-07-28-wechaty-puppet-douyin.md
>  image: /assets/2020/wechaty-puppet-douyin/wechaty-puppet-douyin-logo.jpg
Where is this file?

2020-08-23 10:36 UTC, gavinwang23 commented on _posts/2020-07-28-wechaty-puppet-douyin.md
>  image: /assets/2020/wechaty-puppet-douyin/wechaty-puppet-douyin-logo.jpg
It's already in master
![image](https://user-images.githubusercontent.com/48911723/90976422-82fd7280-e56f-11ea-8cc5-5755b6ea9bc1.png)

2020-08-23 10:43 UTC, gavinwang23 commented on _posts/2020-07-28-wechaty-puppet-douyin.md
>  image: /assets/2020/wechaty-puppet-douyin/wechaty-puppet-douyin-logo.jpg
Sorry, I didn’t check the article well before

2020-08-23 10:57 UTC, huan commented on _posts/2020-08-20-wechaty-puppet-douyin-mid-term.md
> +  <iframe width="560" height="315" src="https://www.youtube.com/embed/zDIPzGztn_E" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></if
I'd like to suggest that you can use the `iframe` new feature created from @univerone this week:

```html
{% include iframe.html src="https://www.youtube.com/embed/zDIPzGztn_E" %}
```

2020-08-23 11:22 UTC, lijiarui commented
Please resolve the conflict first.

2020-08-23 12:25 UTC, gavinwang23 commented on _posts/2020-08-20-wechaty-puppet-douyin-mid-term.md
> +  <iframe width="560" height="315" src="https://www.youtube.com/embed/zDIPzGztn_E" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></if
I saw that you have modified my blog, thank you very much, I have just modified the blog as your request

2020-08-23 12:27 UTC, gavinwang23 commented
I think everything is done😄

2020-08-23 12:29 UTC, gavinwang23 commented
Thanks for your help！

2020-08-30 16:26 UTC, lijiarui commented
You should resolve the conflict first and then I can look into your blog.

2020-09-01 13:49 UTC, closed without merging