added a blog
wechaty/docusaurus pull request #497
Opened 2020-08-26 15:28 UTC by ovarte

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-26 15:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=497) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=497) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=497) it.</sub>

2020-08-30 16:25 UTC, lijiarui requested changes
Please change as I request.

2020-08-30 16:25 UTC, lijiarui commented on _posts/2020-08-26-statistical-robot.md
> +image:
Please add a image for this blog.

2020-10-03 09:08 UTC, lijiarui commented
ping @ovarte

2020-11-08 02:12 UTC, wj-Mcat commented
ping @ovarte . If you have not fix this pr at next three days,  we will close it. Thanks a lot.

2020-12-05 06:21 UTC, huan commented
This is a Python Wechaty example! @wechaty/python

2020-12-14 09:15 UTC, huan commented
Close this PR due to no activities for more than 3 months.

2020-12-14 09:15 UTC, closed without merging