added a bolg
wechaty/docusaurus pull request #499
Opened 2020-08-28 05:37 UTC by Songbingjun

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-28 05:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=499) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=499) it.</sub>

2020-08-30 16:23 UTC, lijiarui commented
Please make  CI green and then I can look into your blog.

2020-08-31 01:03 UTC, Songbingjun commented
> Please make CI green and then I can look into your blog.

emm.. what's mean?

2020-08-31 02:53 UTC, Songbingjun commented
After the re submission, Ci was still not penalized
@lijiarui

2020-09-03 06:22 UTC, Songbingjun commented
我不知道怎么填加CI监测

2020-09-04 02:52 UTC, Songbingjun commented
@lijiarui 您好，我已经通过CI检测了，麻烦能通过审批一下吗

2020-09-06 08:28 UTC, lijiarui requested changes
Since we have the profile markdown file, so you should remove this introduction commit from authors.yml.

2020-09-08 01:41 UTC, Songbingjun commented
@lijiarui 您好，我已经通过CI检测了，麻烦能通过审批一下吗

2020-09-10 13:40 UTC, lijiarui requested changes
Please change as I request.

2020-09-10 13:40 UTC, lijiarui commented on jekyll/_posts/2020-08-28-wechaty-alert-padplus.md
> +author: songbingjun
Please change the author name to `wys0903`, it should the same as the profile name, or it will cause a 404 error.

2020-09-12 05:49 UTC, Songbingjun commented
如果还有什么问题，请都告诉我，谢谢！

2020-09-13 08:15 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

2020-09-13 08:16 UTC, merged