Add a Blog to deploy wechaty into aws
wechaty/docusaurus pull request #500
Opened 2020-08-28 12:08 UTC by Charles-Wu-Chen

First time to commit a blog and contribute to the project.  Let me know if there is any thing need to change .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

2020-08-28 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=500) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=500) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: code-challenge-reece<br/>:x: Charles-Wu-Chen<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=500) it.</sub>

2020-08-30 16:22 UTC, lijiarui commented
Please resolve the confilct and sign the CLA first.

2020-08-31 12:38 UTC, Charles-Wu-Chen commented
Hi,  have signed the CLA and resolved the conflict. Please have a review again.  Thanks

2020-09-02 18:47 UTC, lijiarui requested changes
Please change as I request.

Since @huan change the file at b5d981a8a218f684dfc92017e3aa1be1d18392ea

You should move all of the files under `jekyll`. For example:

move `_developers/charles-wu-chen.md.md` to `jekyll/_developers/charles-wu-chen.md.md`

2020-09-02 18:47 UTC, lijiarui commented on _posts/2020-08-28-deploy-wechaty-in-aws.md
> +author: Charles-Wu-Chen
You should change the author name to `charles-wu-chen` since it should the same as the profile file name, or it may cause a 404 error.

2020-09-03 03:14 UTC, Charles-Wu-Chen commented on _posts/2020-08-28-deploy-wechaty-in-aws.md
> +author: Charles-Wu-Chen
Hi @lijiarui  Thanks for the comments , fixed accordingly.

2020-09-06 08:15 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room

2020-09-06 08:15 UTC, merged