added a blog
wechaty/docusaurus pull request #509
Opened 2020-09-02 02:45 UTC by Songbingjun

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-09-02 05:40 UTC, Songbingjun commented
What should I do next? @lijiarui  @huan

2020-09-02 17:52 UTC, lijiarui requested changes
Please change as I request.

2020-09-02 17:52 UTC, lijiarui commented on _data/authors.yml
> +    - label: "Email"
You should add your profile at `_developers` file as other contributors did.

Btw, could you tell me where do you know you should add your profile at `author.yml`, it means we should update that file because it is outdated.

2020-09-02 17:52 UTC, lijiarui commented on _posts/2020-08-28-wechaty-alert-padplus.md
> +date: 2020-08-28 11:25:47
You should add an image for this blog.

2020-09-03 01:15 UTC, Songbingjun commented
> Please change as I request.

OK, I've finished the modification in pull requests #499 ，CI is still orange

2020-09-03 08:41 UTC, Songbingjun commented
CI监测没有自动运行，我不知道怎么让他运行 @lijiarui

2020-09-06 01:49 UTC, closed without merging