added a blog
wechaty/docusaurus pull request #514
Opened 2020-09-04 01:44 UTC by tomallv

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-09-04 01:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=514) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=514) before we can accept your contribution.<br/><hr/>**吕宁** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=514) it.</sub>

2020-09-06 08:26 UTC, lijiarui requested changes
Please change as I request.

2020-09-06 08:26 UTC, lijiarui commented on jekyll/_developers/tomallv.md
> +avatar: /assets/2020/issue-feedback-room-monitor/header.jpg
You should put your profile avatar under `/assets/developers/tomallv/avatar.png` instead of the 2020 folder.

2020-09-06 08:26 UTC, lijiarui commented on jekyll/_posts/2020-09-04-issue-feedback-room-monitor.md
> + ![1](/assets/2020/issue-feedback-room-monitor/qrcode-push.jpg)
It should be `png`  instead of `jpg` as you upload.

2020-09-07 01:51 UTC, tomallv commented on jekyll/_developers/tomallv.md
> +avatar: /assets/2020/issue-feedback-room-monitor/header.jpg
I have pushed the changing update followed by your request, please check again. thanks!

2020-09-07 01:52 UTC, tomallv commented on jekyll/_posts/2020-09-04-issue-feedback-room-monitor.md
> + ![1](/assets/2020/issue-feedback-room-monitor/qrcode-push.jpg)
I have pushed the changing update followed by your request, please check again. thanks!

2020-09-10 13:42 UTC, lijiarui requested changes
Please change as I request.

2020-09-10 13:42 UTC, lijiarui commented on jekyll/_developers/tomallv.md
> +avatar: /assets/2020/issue-feedback-room-monitor/header.jpg
No, you didn't. It still is `/assets/2020/issue-feedback-room-monitor/header.jpg`

2020-09-11 01:33 UTC, tomallv commented on jekyll/_developers/tomallv.md
> +avatar: /assets/2020/issue-feedback-room-monitor/header.jpg
sorry, this is my mistake, just re-push the update, please help to  check it again, Thanks!

2020-09-11 01:34 UTC, tomallv commented on jekyll/_posts/2020-09-04-issue-feedback-room-monitor.md
> + ![1](/assets/2020/issue-feedback-room-monitor/qrcode-push.jpg)
I re-push the correct update, please help to check it again, Thanks!

2020-09-13 08:21 UTC, lijiarui requested changes
Please change as I request.

2020-09-13 08:21 UTC, lijiarui commented on jekyll/_developers/tomallv.md
> +avatar: /assets/2020/issue-feedback-room-monitor/header.jpg
no you didn't. I mean in `jekyll/_developers/tomallv.md` file, the avatar profile is still `/assets/2020/issue-feedback-room-monitor/header.jpg`

2020-09-14 02:13 UTC, tomallv commented on jekyll/_developers/tomallv.md
> +avatar: /assets/2020/issue-feedback-room-monitor/header.jpg
Get your point, i forgot to update the 'jekyll/_developers/tomallv.md' in before. Now just re-push with the updating for this file, please check again, Thanks very much!

2020-09-14 02:24 UTC, lijiarui requested changes
Please change as I request.

2020-09-14 02:24 UTC, lijiarui commented on jekyll/_posts/2020-09-04-issue-feedback-room-monitor.md
> +image: /assets/developers/tomallv/avatar.png
You shouldn't use a developer avatar in the blog.

2020-09-14 06:28 UTC, tomallv commented on jekyll/_posts/2020-09-04-issue-feedback-room-monitor.md
> +image: /assets/developers/tomallv/avatar.png
OK, I have changed this in the blog, please check it, Thanks a lot!

2020-09-17 05:13 UTC, lijiarui requested changes
It seems the following 2 files are irrelated to this PR, please remove them:

1. package-lock.json
2. jekyll/assets/developers/tomallv/way.jpg

2020-09-17 06:54 UTC, tomallv commented
> It seems the following 2 files are irrelated to this PR, please remove them:
> 
> 1. package-lock.json
> 2. jekyll/assets/developers/tomallv/way.jpg

Done, please check again, Thanks a lot!

2020-09-17 08:58 UTC, lijiarui approved these changes

2020-09-17 08:58 UTC, merged

2020-09-17 08:58 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room