添加基于wechaty实现的基金小助手
wechaty/docusaurus pull request #516
Opened 2020-09-05 10:19 UTC by xla145

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "添加基于wechaty实现的基金小助手"
    author: xula
    avatar : "https://avatars3.githubusercontent.com/u/18521352?s=400&u=0cd7fac67d8159796fa99921939dabaea3f00643&v=4"
   date: 2020-09-05
    ---
    add blog
    ```
Here is the add files:
- 2020-09-05-fund-wechay-python-bot.md: https://github.com/wechaty/wechaty.github.io/blob/master/_post/2020-09-05-fund-wechay-python-bot.md
- picDir: https://github.com/wechaty/wechaty.github.io/blob/master/assets/2020/fund-wechay-python

update files:

- authors.yml: https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml

  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-09-05 10:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=516) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=516) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=516) it.</sub>

2020-09-06 03:51 UTC, xla145 commented
Please review

2020-09-06 08:10 UTC, lijiarui commented
Please sign the CLA first, and update your author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username.

2020-09-06 08:26 UTC, xla145 commented
Ok,thanks

2020-09-06 08:37 UTC, xla145 commented
I've added the developer information, please review

2020-09-13 07:22 UTC, lijiarui requested changes
Please change as I request.

2020-09-13 07:22 UTC, lijiarui commented on _data/authors.yml
> +  links:
Please remove this file since we change to developers markdown file.

2020-09-13 13:22 UTC, xla145 commented
I have fininshed removing authors file

2020-09-14 02:25 UTC, lijiarui commented
Please sign the CLA

2020-10-03 09:09 UTC, lijiarui commented
@xla145 Please sign the CLA first and then I can review your PR.

2020-11-08 02:17 UTC, wj-Mcat commented
ping @xla145  Please sign the CLA first and then I can review your PR. If you have not do it at next three days, we will close this pr. Thanks a lot.

2020-12-05 05:57 UTC, huan commented
Please sign the CLA by clicking the `[CLA | not signed yet]` button above, so that we can continue processing your PR.

2021-01-03 07:37 UTC, huan commented
Close this PR due to inactivity after 30 days.

2021-01-03 07:37 UTC, closed without merging