added a post
wechaty/docusaurus pull request #525
Opened 2020-09-14 06:46 UTC by garyboygo

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-09-14 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=525) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=525) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=525) it.</sub>

2020-09-17 04:59 UTC, lijiarui commented
Please make CI green then I can review this PR.

2020-09-22 05:20 UTC, garyboygo commented
@lijiarui Thanks for pointing that out for me! I already fix the test. Could you have me take a look at this PR when you have time?

2020-09-24 05:40 UTC, garyboygo commented
Hi @lijiarui, Could you help me take a quick look at my PR when you have time?

2020-09-24 06:18 UTC, lijiarui requested changes
Please change as I request.

2020-09-24 06:18 UTC, lijiarui commented on jekyll/_developers/garyboygo.md
> +avatar: /jekyll/assets/developers/garyboygo/avatar.jpg
Please change this to `/assets/developers/garyboygo/avatar.jpg`

And it seems you upload jepg, but you write jpg here.

2020-09-24 06:18 UTC, lijiarui commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +image: /jekyll/assets/2020/ads-filter-groupbot/ads-filter-groupbot.jpeg
Please change to `/assets/2020/ads-filter-groupbot/ads-filter-groupbot.jpeg`

2020-09-24 06:18 UTC, lijiarui commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +![avatar](/jekyll/assets/2020/ads-filter-groupbot/ads-filter-groupbot.jpeg)
Please change to `/assets/2020/ads-filter-groupbot/ads-filter-groupbot.jpeg`

2020-09-24 06:18 UTC, lijiarui commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +author: gary
Author name here should be same as the markdown file name. So you should change to `garyboygo` here.

2020-09-25 17:26 UTC, garyboygo commented on jekyll/_developers/garyboygo.md
> +avatar: /jekyll/assets/developers/garyboygo/avatar.jpg
Thanks for the suggestion!

2020-09-25 17:26 UTC, garyboygo commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +![avatar](/jekyll/assets/2020/ads-filter-groupbot/ads-filter-groupbot.jpeg)
Done!

2020-09-25 17:26 UTC, garyboygo commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +author: gary
Done!

2020-09-25 17:26 UTC, garyboygo commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +image: /jekyll/assets/2020/ads-filter-groupbot/ads-filter-groupbot.jpeg
Done!

2020-09-30 07:47 UTC, garyboygo commented
@lijiarui I already modified the code. Could you help me take a quick look at it?

2020-10-03 09:11 UTC, lijiarui requested changes

2020-10-03 09:11 UTC, lijiarui commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +- bot.js: 项目入口文件，实现了扫码微信，并注册监测广告的逻辑。
Where is bot.js?

2020-10-06 04:17 UTC, garyboygo commented on jekyll/_posts/2020-09-14-ads-filer-groupbot.md
> +- bot.js: 项目入口文件，实现了扫码微信，并注册监测广告的逻辑。
bot.js is the entry point of the WeChatGroupBot. You can find it in here(https://github.com/garyboygo/WeChatGroupBot). And the utility.js provides a collections of utility function to bot.js

2020-12-05 03:01 UTC, merged

2020-12-05 03:36 UTC, huan commented
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/09/14/ads-filer-groupbot>

> You've invited garyboygo to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.