added a blog
wechaty/docusaurus pull request #526
Opened 2020-09-14 15:12 UTC by chenj-freedom

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-09-14 15:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=526) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=526) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=526) it.</sub>

2020-09-15 01:04 UTC, chenj-freedom commented
1

2020-09-17 05:04 UTC, lijiarui requested changes
Please change as I request.

2020-09-17 05:04 UTC, lijiarui commented on jekyll/_developers/chenj-freedom.yml
> +name: chenj-freedom
You should change this file from `chej-freedom.yml` to `chej-freedom.md`

2020-09-17 05:04 UTC, lijiarui commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +这是一个商业公司（北京句子科技有限公司）开发的一套半开源半商业的库，基于web微信协议的库确实都开源了，但是基于上述腾讯的政策，web微信现在基本是都用不了了，所以web微信这套开源库，也就只能学学而已。但是他们还开发了一套基于pad微信协议的库，github地址：[https://github.com/wechaty/wechaty-puppet-padplus](https://github
Please change `北京句子科技有限公司` to `北京句子互动科技有限公司`

2020-09-17 05:04 UTC, lijiarui commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image](https://upload-images.jianshu.io/upload_images/24686309-5961452efa67c6f9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
Please localize this file in order to a future 404 error.

2020-09-17 05:04 UTC, lijiarui commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image.png](https://upload-images.jianshu.io/upload_images/24686309-08c59775ef5d4ae1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
Please localize this file in order to a future 404 error.

2020-09-18 02:24 UTC, chenj-freedom commented on jekyll/_developers/chenj-freedom.yml
> +name: chenj-freedom
fixed

2020-09-18 02:26 UTC, chenj-freedom commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +这是一个商业公司（北京句子科技有限公司）开发的一套半开源半商业的库，基于web微信协议的库确实都开源了，但是基于上述腾讯的政策，web微信现在基本是都用不了了，所以web微信这套开源库，也就只能学学而已。但是他们还开发了一套基于pad微信协议的库，github地址：[https://github.com/wechaty/wechaty-puppet-padplus](https://github
fixed

2020-09-18 02:37 UTC, chenj-freedom commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image](https://upload-images.jianshu.io/upload_images/24686309-5961452efa67c6f9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
fixed

2020-09-18 02:38 UTC, chenj-freedom commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image.png](https://upload-images.jianshu.io/upload_images/24686309-08c59775ef5d4ae1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
fixed

2020-09-24 06:22 UTC, lijiarui requested changes
Please change as I request.

2020-09-24 06:22 UTC, lijiarui commented on jekyll/_developers/chenj-freedom.md
> +avatar: /assets/developers/chenj-freedom/avatar.png
Where is this file?

2020-09-27 15:48 UTC, chenj-freedom commented on jekyll/_developers/chenj-freedom.md
> +avatar: /assets/developers/chenj-freedom/avatar.png
fixed

2020-10-03 09:13 UTC, lijiarui requested changes
Please change as I request.

2020-10-03 09:13 UTC, lijiarui commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image](jekyll/assets/2020/my-first-wechaty-bot/1.png)
Please change to `/assets/2020/my-first-wechaty-bot/1.png`

2020-10-03 09:13 UTC, lijiarui commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image.png](jekyll/assets/2020/my-first-wechaty-bot/3.png)
Please change to `/assets/2020/my-first-wechaty-bot/1.png`

2020-10-03 09:13 UTC, lijiarui commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image.png](jekyll/assets/2020/my-first-wechaty-bot/2.png)
Please change to `/assets/2020/my-first-wechaty-bot/2.png`

2020-10-07 03:22 UTC, chenj-freedom commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image](jekyll/assets/2020/my-first-wechaty-bot/1.png)
fixed

2020-10-07 03:23 UTC, chenj-freedom commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image.png](jekyll/assets/2020/my-first-wechaty-bot/2.png)
fixed

2020-10-07 03:23 UTC, chenj-freedom commented on jekyll/_posts/2020-09-14-my-first-wechaty-bot.md
> +![image.png](jekyll/assets/2020/my-first-wechaty-bot/3.png)
fixed

2020-11-13 05:53 UTC, chenj-freedom commented
不继续审核了吗？  一个月多的PR了

2020-11-13 06:00 UTC, huan commented
Refer to #582

2020-12-05 03:02 UTC, huan approved these changes
LGTM

2020-12-05 03:02 UTC, merged

2020-12-05 05:48 UTC, huan commented
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/09/14/my-first-wechaty-bot>

> You've invited chenj_freedom to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.