SoC final report blog
wechaty/docusaurus pull request #531
Opened 2020-09-26 06:10 UTC by kxz18

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-09-30 08:18 UTC, wj-Mcat requested changes
You have a great & fast blog. Waiting for your comment from mentor.

2020-10-03 08:46 UTC, lijiarui requested changes
Please change as I request:
- add tag for this blog
- add image for this blog as the blog link request.

2020-10-03 08:46 UTC, lijiarui commented on jekyll/_posts/2020-09-26-chassist-final.md
> +   - soc2020
Please add a `soc` tag here.

2020-10-03 08:46 UTC, lijiarui commented on jekyll/_posts/2020-09-26-chassist-final.md
> +<img src="/home/kxz/Documents/Study/MeMyself/Summer2020/blogs/final/images/logo.png" alt="logo" style="zoom: 33%;" />
Where is this image?

2020-10-03 08:46 UTC, lijiarui commented on jekyll/_posts/2020-09-26-chassist-final.md
> +![uml](/home/kxz/Documents/Study/MeMyself/Summer2020/blogs/final/images/uml.png)
Where is this image?

2020-10-03 09:36 UTC, lijiarui commented
@wj-Mcat  Please help @kxz18  posting his blog.

2020-10-04 01:48 UTC, wj-Mcat commented
> Please change as I request:
> 
> * add tag for this blog
> * add image for this blog as the blog link request.

Please add these two main features for this blog, thanks a lot. Waiting for your new commit.

2020-10-04 03:32 UTC, kxz18 commented
> > Please change as I request:
> > 
> > * add tag for this blog
> > * add image for this blog as the blog link request.
> 
> Please add these two main features for this blog, thanks a lot. Waiting for your new commit.

Both have been done in commits of yesterday.

2020-10-04 07:51 UTC, lijiarui approved these changes
Good job!

2020-10-04 07:51 UTC, merged