add 2017-10-28-ten-minutes-to-build-a-daily-paper-bot and some images
wechaty/docusaurus pull request #54
Opened 2017-10-28 02:11 UTC by leinue

2017-10-28 03:45 UTC, lijiarui reviewed
Cool! Thanks!

2017-10-28 03:45 UTC, lijiarui approved these changes

2017-10-28 03:47 UTC, lijiarui requested changes

2017-10-28 03:47 UTC, lijiarui commented on _posts/2017-10-28-ten-minutes-to-build-a-daily-paper-bot.md
> +
Could you add `<!--more-->` here? So we can see abstract from the blog homepage, or it will show all content on blog homepage

2017-10-28 05:42 UTC, huan requested changes
Please follow the reviews before we can merge it.

Thanks!

2017-10-28 05:42 UTC, zixia commented on _posts/2017-10-28-ten-minutes-to-build-a-daily-paper-bot.md
> +Finally, I like wechaty, thanks to all the oontributors of wechaty!
_oontributors_ -> Contributors

2017-10-29 02:19 UTC, huan approved these changes
Awesome, thank you very much!

2017-10-29 02:44 UTC, merged