Final blog wechat puppet
wechaty/docusaurus pull request #540
Opened 2020-09-30 14:09 UTC by Roxanne718

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-10-03 09:19 UTC, lijiarui requested changes
Please change as I request.

2020-10-03 09:19 UTC, lijiarui commented on jekyll/_posts/2020-09-28-puppet-work-final.md
> +	- live coding视频:{% include iframe.html src="https://work.weixin.qq.com/wework_admin/liveroom/v2/replay?ref=app&roomid=6877185498936770818" %}
Are you sure this is your live coding video?

2020-10-03 09:37 UTC, lijiarui commented
@wj-Mcat  Please help @Roxanne718  posting his blog.

2020-10-04 01:46 UTC, wj-Mcat commented on jekyll/_posts/2020-09-28-puppet-work-final.md
> +	- live coding视频:{% include iframe.html src="https://work.weixin.qq.com/wework_admin/liveroom/v2/replay?ref=app&roomid=6877185498936770818" %}
Please upload your live-coding video to bilibili/youtube/... video-stream website. Wating for your new commit.

2020-10-05 04:26 UTC, Sapio-S commented on jekyll/_posts/2020-09-28-puppet-work-final.md
> +	- live coding视频:{% include iframe.html src="https://work.weixin.qq.com/wework_admin/liveroom/v2/replay?ref=app&roomid=6877185498936770818" %}
这个是企业微信自带的直播功能得到的录屏，原本的链接跳转之后应该可以在企业微信登陆后观看。
上传到bilibili/youtube会比较麻烦，所以之前没传，如果必须上传的话可能还得需要一段时间（下载+转换格式+等待审核）。

2020-10-13 02:26 UTC, closed without merging