add hurely blog of wechat-wangke-bot
wechaty/docusaurus pull request #569
Opened 2020-10-16 06:09 UTC by hurely

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-11-11 02:32 UTC, wj-Mcat approved these changes
LGTM 🎉

2020-11-18 06:35 UTC, lijiarui requested changes
Please change as I request.

2020-11-18 06:35 UTC, lijiarui commented on jekyll/_posts/2020-10-15-wechaty-wangke-bot.md
> +  ![回复网课答案](https://kung-1252408270.cos.ap-chengdu.myqcloud.com/markdown/20201015105732.png)
Please localize this image in case of a future 404 error. You can put this here:  `2020/Wechaty-wangke-bot/`

2020-11-18 06:35 UTC, lijiarui commented on jekyll/_posts/2020-10-15-wechaty-wangke-bot.md
> +  ![接收小程序](https://kung-1252408270.cos.ap-chengdu.myqcloud.com/markdown/20201015112724.png)
Please localize this image in case of a future 404 error. You can put this here:  `2020/Wechaty-wangke-bot/`

2020-12-05 03:08 UTC, huan approved these changes
LGTM

2020-12-05 03:08 UTC, merged

2020-12-05 03:39 UTC, huan commented
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/10/15/wechaty-wangke-bot>

> You've invited kungggyoyoyo to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.