iyjian-我用wechaty做了一个积分红包机器人
wechaty/docusaurus pull request #57
Opened 2017-11-10 03:26 UTC by iyjian

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2017` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2017-11-12 11:04 UTC, lijiarui requested changes
Thanks for your blog! Could you help to fix these small change, then I will merge this.

2017-11-12 11:04 UTC, lijiarui commented on _posts/2017-11-08-red-pocket-wechaty-iyjian.md
> +  [3]: /download/2017/iyjian-5.jpg
I found you just have 3 images, could you change `iyjian-5.jpg` to `iyjian-3.jpg` for a better looking?
Thanks.

2017-11-12 11:04 UTC, lijiarui commented on _posts/2017-11-08-red-pocket-wechaty-iyjian.md
> +以上这么多废话是答应lijiarui小姐9月份写的，可是又要忙工作，又要忙这个娱乐项目，每天都是凌晨2，3点睡觉，6，7点起床，直到现在也如此，实在没有什么完整的时间，对于这种严重的拖延我深表歉意。
Could you help to add my GitHub link here? [lijiarui](github.com/lijiarui) Thanks!

2017-11-13 03:50 UTC, iyjian commented
done

2017-11-13 05:41 UTC, merged