add a blog (wxbot-admin)
wechaty/docusaurus pull request #579
Opened 2020-10-27 07:03 UTC by skyvow

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-10-27 07:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=579) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=579) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=579) it.</sub>

2020-11-02 05:09 UTC, skyvow commented
@huan @lijiarui Please help review it.

2020-11-02 06:05 UTC, huan commented
@skyvow thanks for your great blog post pull requests!

Please wait @lijiarui to review but she's quite busy those weeks.

Thank you very much for your patient.

2020-11-08 12:55 UTC, wj-Mcat requested changes
To better demonstrate your blog, please complete the following changes.

2020-11-08 12:55 UTC, wj-Mcat commented on jekyll/_posts/2020-10-27-wxbot-admin.md
> +> Code: [Github](https://github.com/wux-weapp/wxbot)
These will be the short description of blog, Please use a short description to display in a better way. refer to: [commandline-filter](https://github.com/wechaty/wechaty.js.org/blame/master/jekyll/_posts/2020-08-28-commandline-filter.md#L7) Thanks a lot.

2020-11-11 02:26 UTC, wj-Mcat approved these changes
LGTM

2020-11-18 05:02 UTC, skyvow commented
@wj-Mcat @lijiarui @huan 大佬们，啥时候能帮忙 merge 啊，token 过期都快一个月了，对开发者来说耐心都要没了，很难支持呀。。。

2020-11-18 06:27 UTC, lijiarui approved these changes
LGTM

2020-11-18 06:28 UTC, merged

2020-11-18 06:28 UTC, lijiarui commented
Congratulations! 🎉 🎉 🎉

You become a wechaty contributor successfully! 👏 👏 👏

Please:

- [ ] Update your profile here: [Contributor List](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0), then other contributors will know you better!
- [ ]  Join wechaty org by clicking https://github.com/wechaty
- [ ]  Add my wechat: ruirui_0914 and send me this pr link. I will invite you into Wechaty Contributor Room