added a blog
wechaty/docusaurus pull request #580
Opened 2020-10-30 21:37 UTC by Jasonlovesharon

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-11-08 08:48 UTC, wj-Mcat requested changes
There are some small changes that you should do, Please go ahead to make all things good, so that we can merge it. 🙈

2020-11-08 08:48 UTC, wj-Mcat commented on jekyll/_posts/2020-10-30-daily-message-and-chatbot.md
> +
Please remove this blank line, thanks a lot.

2020-11-08 08:48 UTC, wj-Mcat commented on jekyll/_posts/2020-10-30-daily-message-and-chatbot.md
> +## 前言
There should be only on blank line, please change it, thanks a lot.

2020-11-08 08:48 UTC, wj-Mcat commented on jekyll/_posts/2020-10-30-daily-message-and-chatbot.md
> +
I think that you have forgot the suffix of image file. Is that right ?

2020-11-08 08:48 UTC, wj-Mcat commented on jekyll/_posts/2020-10-30-daily-message-and-chatbot.md
> +到此已经实现了私人人助理和定时推送消息的功能（[项目地址](https://github.com/jasonlovesharon/my_bot)），由于对Typescript不熟，很多功能都是借鉴很多大神的轮子实现的，还是对Python熟悉点，下步准备用Python来实现以上功能，并进一步拓展更多有趣的功能。
Please add a new line at the end of the post, thanks a lot.

2020-11-09 18:07 UTC, huan commented on jekyll/_developers/jasonlovesharon.md
> +email: mailto:54027901@163.com
Remove `mailto:`

2020-11-09 18:18 UTC, Jasonlovesharon commented on jekyll/_developers/jasonlovesharon.md
> +email: mailto:54027901@163.com
Thanks for your check,I have fixed all ,please help review~~

2020-11-09 18:26 UTC, Jasonlovesharon commented on jekyll/_posts/2020-10-30-daily-message-and-chatbot.md
> +
yes,you are right,I have added, thank you..

2020-11-11 02:25 UTC, wj-Mcat requested changes
A small step can make it perfect.

2020-11-11 02:25 UTC, wj-Mcat commented on jekyll/_developers/jasonlovesharon.md
> +email:54027901@163.com
A small change: there should be a blank before your email address.  Please make another commit to make it perfect.

2020-11-11 05:07 UTC, Jasonlovesharon commented on jekyll/_developers/jasonlovesharon.md
> +email:54027901@163.com
got it,thanks a lot

2020-11-19 17:06 UTC, Jasonlovesharon commented
@huan @wj-Mcat @lijiarui ......

2020-11-22 16:03 UTC, huan commented
It's great to know that you want to use Python Wechaty to build your next bot!

2020-11-22 16:03 UTC, huan approved these changes
LGTM

2020-11-24 02:14 UTC, Jasonlovesharon commented
> It's great to know that you want to use Python Wechaty to build your next bot!
> 
> Link to Wechaty Contributors Nomination: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16)
yep,life is short,you need Python,lol... thanks a lot for your approval...

2020-12-05 03:10 UTC, huan approved these changes
LGTM

2020-12-05 03:11 UTC, merged

2020-12-05 03:43 UTC, huan commented
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/07/23/kuakua-wechaty>

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.