wechaty-electron blog
wechaty/docusaurus pull request #62
Opened 2017-11-26 04:55 UTC by GuoYingxu

wechaty-electron 如何让你的wechaty 变成客户端

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2017` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2017-11-26 08:30 UTC, lijiarui requested changes

2017-11-26 08:30 UTC, lijiarui commented on _posts/2017－11-26-wechaty-electron 如何让你的wechaty 变成客户端.md
> +去年的这个时候，我刚到现在的公司任职，发现同事正在用微信做转播，就是把几个微信群里有价值的发言同步到其他几个群里，同时还要存入数据库以便在论坛上也能看到相关讨论。当时同事用的是chrome插件的方式，那是第一次知道微信还可以这么玩。惊奇的同时我也发现了一个很严重的问题，就是插件跑一段时间，网页就卡死了，就得重启。 于是我在网上找不同的解决方案，github 真是一个神奇的地方，很快我就找到了好几
Could you please add `<!-- more -->` section here or anywhere you like to just show the abstract on blog homepage.

2017-11-26 08:35 UTC, lijiarui commented
Thanks for your pr!

Also， here are 2 suggestion:

1. Could you change the file-name from `2017－11-26-wechaty-electron 如何让你的wechaty 变成客户端.md` to something like `2017－11-26-wechaty-electron-making-your-wechaty-as-a-client-service.md`, because wechaty blog keeps all filenames & url as lowercase, and use - to connect words instead of space.

2. I suggest to add a image here to make the blog more attractive.

Thanks!

2017-11-27 03:32 UTC, lijiarui requested changes
I just to let others know how to run in this blog.

I just copy your readme here, can try the way you like, thanks!

2017-11-27 03:32 UTC, lijiarui commented on _posts/2017－11-26-wechaty-electron 如何让你的wechaty 变成客户端.md
> +
Also I suggest to add [wechaty-electron](https://github.com/GuoYingxu/wechaty/tree/wechaty-electron) quick start method here


1. Go to repo: https://github.com/GuoYingxu/wechaty/tree/wechaty-electron
2. Run the following command
```
  git checkout wechaty-electron
  npm install
  npm run dist
  npm start
```

2017-11-27 04:50 UTC, GuoYingxu commented on _posts/2017－11-26-wechaty-electron 如何让你的wechaty 变成客户端.md
> +
@lijiarui  今天弄一些图片。然后再录个小视频。晚上回去重新修改一遍。

2017-11-28 02:47 UTC, lijiarui requested changes
Thanks！ 

Will you add video to this blog as you said yesterday? If you just keep this version without video, I will merge when you add an image to your blog's title. Thanks!

See http://blog.chatie.io/

2017-11-28 02:47 UTC, lijiarui commented on _posts/2017-11-26-wechaty-electron-making-your-wechaty-as-a-client-service.md
> +
I suggest to add one of your image before `more` to make it more attracitve

2017-11-28 07:29 UTC, GuoYingxu commented
@lijiarui 我添加了几个图片，视频就算了

2017-11-29 13:23 UTC, closed without merging