dotnet-wechaty-getting-started 使用介绍
wechaty/docusaurus pull request #633
Opened 2020-12-26 15:49 UTC by Jesn

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [x] Add teaser image for the blog
- [ x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-12-26 16:20 UTC, Jesn reviewed
update

2020-12-26 16:33 UTC, Jesn reviewed
update

2020-12-26 16:45 UTC, Jesn reviewed
update

2020-12-28 02:51 UTC, huan requested changes
Thanks for submitting this great blog post for introducing .NET, it's our first .net post!

Please rename your profile filename in _developers as the same as your GitHub id in lowercase and follow my comments.

After you fixed them we will be able to merge this great post.

2020-12-28 02:51 UTC, huan commented on _post/2020-12-2-.NET Wechaty 使用介绍.md
> +author: Darren
Please use your GitHub username at here in lowercase because it will be used as your id for the post.

2020-12-28 02:51 UTC, huan commented on _post/2020-12-2-.NET Wechaty 使用介绍.md
> +  - C#
I'm not sure whether we can use . and # in tags, so I'd like to suggest to use csharp and dotnet at here

2020-12-28 05:52 UTC, Jesn commented on _post/2020-12-2-.NET Wechaty 使用介绍.md
> +author: Darren
@huan    updated

2020-12-29 14:58 UTC, huan approved these changes
LGTM

2020-12-29 14:58 UTC, merged

2020-12-29 14:59 UTC, huan commented
Thank you very much for writing this great .NET Wechaty blog post, it's very valuable!