Add article java-wechaty auto get news
wechaty/docusaurus pull request #636
Opened 2020-12-29 02:22 UTC by HarrisonQi

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2020-12-29 15:13 UTC, huan requested changes
It's so great to see a Java Wechaty blog post!

Please change your filename to lowercase then I believe it's ready to be merged!

2020-12-29 15:13 UTC, huan commented on jekyll/_posts/2020-12-28-auto-push-news.md
> +author: HarrisonQI
Please use `author: harrisonqi` here, and also rename `jekyll/_developers/HarrisonQI.md` to `jekyll/_developers/harrisonqi.md` because we are using all lowercase for our filenames.

2020-12-30 06:06 UTC, HarrisonQi commented on jekyll/_posts/2020-12-28-auto-push-news.md
> +author: HarrisonQI
Ok, please recheck

2020-12-30 06:06 UTC, HarrisonQi commented
> It's so great to see a Java Wechaty blog post!
> 
> Please change your filename to lowercase then I believe it's ready to be merged!

OK, please recheck

2021-01-01 03:38 UTC, huan approved these changes
LGTM

2021-01-01 03:38 UTC, merged

2021-01-01 03:42 UTC, huan commented
@HarrisonQi  Thank you very much for your sharing!

> You've invited 阿航 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

And we also have a WeChat room for contributors only which can discuss Wechaty at a deep level, you are welcome to join and if you are interested please contact @lijiarui to ask for an invitation.

2021-01-04 01:54 UTC, HarrisonQi commented
> @HarrisonQi  Thank you very much for your sharing!
> 
> > You've invited 阿航 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.
> 
> I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.
> 
> And we also have a WeChat room for contributors only which can discuss Wechaty at a deep level, you are welcome to join and if you are interested please contact @lijiarui to ask for an invitation.
> 
> Happy New Year!

Thank you very much!