wechaty-charbot
wechaty/docusaurus pull request #642
Opened 2021-01-12 01:07 UTC by zhoujian1028

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "基于WeChaty实现运维自动化交互及微信消息通知"
    author: zhoujian1028
    image: 
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/__your_github_username__.md> with your GitHub username in all lowercase. And please also remember to reference yourself with the Github username (in lowercase) in your blog post, so that we can have nice author information besides your blog after we published it!

  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

2021-01-12 01:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=642) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=642) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=642) it.</sub>

2021-01-12 02:56 UTC, huan requested changes

2021-01-12 02:56 UTC, huan commented on _post/2021-01-12-wechaty-charbot.md
> +## WeChaty
Please use `Wechaty` instead of WeChaty.

2021-01-13 02:53 UTC, zhoujian1028 commented on _post/2021-01-12-wechaty-charbot.md
> +## WeChaty
您好，还有什么问题吗，谢谢。

2021-01-21 08:08 UTC, zhoujian1028 commented
hi, all checks have passed, thx ! @huan

2021-01-26 00:50 UTC, closed without merging