Datagirls Chatbot
wechaty/docusaurus pull request #68
Opened 2018-01-08 17:47 UTC by bukaqiaqia

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2017` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2018-01-08 18:07 UTC, huan requested changes
@lijiarui This blog post is such a mess so please make sure it:

1. pass all your checklist and
1. ask for my review

2018-01-10 06:38 UTC, lijiarui commented
@bukaqiaqia Please pass all the checklist:

- [ ] Keep all filenames & url as lowercase, and use - to connect words instead of space. e.g. 2017-10-06-wechat-pc-impactor instead of 2017-10-06-WeChat PC Impactor.
- [ ] Embed the photo & video before publishing, save all external file to the blog /download/2017 directory. Please rename the image name istead of `1.jpg`, this will make confuse for other contributors.
- [ ] There are two similar image, one is `download/2017/14.jpg`, the other one is `download/2017/14_副本.jpg`。 Please make sure this error.

2018-01-10 15:50 UTC, lijiarui requested changes

2018-01-10 15:50 UTC, lijiarui commented on _posts/2018-01-09-all-you-need-to-know-about-chatbot.md
> +
Please change this :   `![1_](/download/2017/1.jpg)`
And all of the other picture should change like this.

Also, I suggest to move all images to `2018` folder like `2017` now, because this is a new year
Thanks!

2018-01-10 16:19 UTC, merged