Add a blog: 女生科技体验节，Wechaty杂货铺
wechaty/docusaurus pull request #72
Opened 2018-02-06 11:37 UTC by TingYinHelen

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2018-02-06 11:50 UTC, lijiarui requested changes
some small tips, thanks!

2018-02-06 11:50 UTC, lijiarui commented on _posts/2018-02-06-techie-festival-FAQ.md
> +不能用于公众号，公众号本身有自动回复的功能，可以直接调用公众号的接口，具体可以查看文档，使用Wechaty制作微信机器人只能用在个人微信号上。
加上下面的内容：

但是wechaty 有计划把公众号整合进来，详细讨论见 [issue1016](https://github.com/Chatie/wechaty/issues/1016)

2018-02-06 11:50 UTC, lijiarui commented on _posts/2018-02-06-techie-festival-FAQ.md
> +这里感谢我们的远程助教杉木和Fery提供的解决方案。
加上杉木和fery 的github地址：
`[杉木](https://github.com/binsee)` `[Fery](https://github.com/h4dex)`

2018-02-06 13:59 UTC, lijiarui commented
also, please change `2018-02-06-techie-festival-FAQ.md` to `2018-02-06-techie-festival-faq.md`

2018-02-08 03:42 UTC, TingYinHelen commented
I have already change the file name.

2018-02-08 06:47 UTC, merged

2018-02-08 06:47 UTC, lijiarui commented
Thanks！