[WIP] Added cloud images
wechaty/docusaurus pull request #756
Opened 2021-04-21 15:42 UTC by Soumi7

Updating getting started tutorial - Google Cloud section.

2021-04-22 02:14 UTC, huan requested changes
Thanks for helping us to continue improving the docs!

Please:

1.  Follow my review about the image alt text
1.  Rename all the image files under `docusaurus/static/img/docs/getting-started/` to a meaningful name, for example:
    ```diff
    - docusaurus/static/img/docs/getting-started/cloud_1.png
    + docusaurus/static/img/docs/getting-started/google-cloud-shell-homepage.png
    ```
1. use `-` in the filename instead of `_` to follow our website file naming conversion.

I believe this PR will be good to be merged after all the above modification has been done.

2021-04-22 02:14 UTC, huan commented on docusaurus/docs/getting-started/quick-start.mdx
> +![image](../../static/img/docs/getting-started/cloud_1.png)
Could you please use a meaningful text for the alt text, instead of a common name `image` at here?

For example: `Google Cloud Shell Homepage`

2021-04-22 02:14 UTC, huan commented on docusaurus/docs/getting-started/quick-start.mdx
> +![image](../../static/img/docs/getting-started/cloud_3.png)
Please use a meaningful name for all images as well.

2021-04-22 09:17 UTC, Soumi7 commented on docusaurus/docs/getting-started/quick-start.mdx
> +![image](../../static/img/docs/getting-started/cloud_3.png)
Yes, as the PR is a {WIP} work in progress, I am still doing it. 

The PR will be ready to merge when I remove the [WIP] status from the title. Thanks!

2021-04-22 09:23 UTC, Soumi7 commented on docusaurus/docs/getting-started/quick-start.mdx
> +![image](../../static/img/docs/getting-started/cloud_1.png)
Sure!

2021-04-22 09:23 UTC, Soumi7 commented on docusaurus/docs/getting-started/quick-start.mdx
> +![image](../../static/img/docs/getting-started/cloud_1.png)
Done.

2021-04-22 10:34 UTC, Soumi7 commented
### Final changes made.

The updated Google Cloud section of Getting Started webpage will look like this :

![Screenshot from 2021-04-22 15-57-58](https://user-images.githubusercontent.com/51290447/115700102-f87e4480-a383-11eb-954d-e8f55024010d.png)



![Screenshot from 2021-04-22 15-57-58](https://user-images.githubusercontent.com/51290447/115700200-121f8c00-a384-11eb-96b4-cf6809fc62bf.png)



![Screenshot from 2021-04-22 15-58-01](https://user-images.githubusercontent.com/51290447/115700210-1481e600-a384-11eb-9b0b-486721588523.png)



![Screenshot from 2021-04-22 15-58-04](https://user-images.githubusercontent.com/51290447/115700221-164ba980-a384-11eb-8ffe-b1d47c3ed586.png)



![Screenshot from 2021-04-22 15-58-09](https://user-images.githubusercontent.com/51290447/115700225-18156d00-a384-11eb-98f8-093374feb71e.png)



![Screenshot from 2021-04-22 15-58-16](https://user-images.githubusercontent.com/51290447/115700233-1a77c700-a384-11eb-869e-df74568864b4.png)



![Screenshot from 2021-04-22 15-58-58](https://user-images.githubusercontent.com/51290447/115700242-1c418a80-a384-11eb-8e01-08658a3f2f99.png)

2021-04-23 18:02 UTC, huan approved these changes
LGTM

2021-04-23 18:03 UTC, merged

2021-04-23 18:03 UTC, huan commented
Thank you very much for those great screen shots, I believe it will greatly improve the understanding for our readers!