新增博客：微信机器人-读经助手
wechaty/docusaurus pull request #800
Opened 2021-05-02 09:52 UTC by kkdev163

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-02 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=800) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=800) it.</sub>

2021-05-02 15:34 UTC, huan requested changes
Thank you very much for sharing your great experiences of creating your Wechaty chatbot!

Please fixing all the errors showing in the GitHub Actions, so that we can merge it after the CI turns green.

2021-05-05 03:35 UTC, kkdev163 commented
> Thank you very much for sharing your great experiences of creating your Wechaty chatbot!
> 
> Please fixing all the errors showing in the GitHub Actions, so that we can merge it after the CI turns green.

@huan  Thanks for your review. I have tried to fix all-knowing errors, please approving the CI  running again.

2021-05-05 04:34 UTC, huan requested changes

2021-05-05 04:34 UTC, huan commented on jekyll/_posts/2021-05-02-wechaty-bible-robot.md
> +categories: article
Please use the `project` as the category because this is an open-source project that you have shared.

2021-05-05 04:38 UTC, huan requested changes
Please make the CI green, thanks

2021-05-05 07:50 UTC, kkdev163 commented on jekyll/_posts/2021-05-02-wechaty-bible-robot.md
> +categories: article
Thanks for your reply, I have changed the category. 

But I haven't got your meaning of the folded name naming problem, can you give me more concrete advice on how to modify the naming. 

Thanks!

2021-05-05 12:50 UTC, huan requested changes
> not ok 33 "jekyll/_posts/2021-05-02-wechaty-bible-chatbot.md" has category "project": it's tags should contain one of "automotive,devops,ecommerce,ecosystem,education,entertainment,finance,game,healthcare,hospitality,insurance,media,other,productivity,real-estate,social,travel,utility" Learn more from Issue #710: Enforce blog posts with category "project" to contain one of the tags Url: https://github.com/wechaty/wechaty.js.org/issues/710

Please fix the above tags issue, then I believe the CI will turn green and this PR will be ready to be merged.

2021-05-06 10:10 UTC, kkdev163 commented
@huan Thanks for your patience. I believe the wechaty community will be health develop with your leading. 

Please approve the CI running again.

2021-05-06 10:19 UTC, huan approved these changes
LGTM

2021-05-06 10:22 UTC, merged

2021-05-06 10:23 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited KK to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

2021-10-10 00:52 UTC, kkdev163 commented
The invitation has expired,  may i receive a new invitation  @huan

2021-10-10 03:42 UTC, huan commented
Of course.

Will do, please try again and let me know the result.

2021-10-10 16:11 UTC, kkdev163 commented
> Of course.
> 
> Will do, please try again and let me know the result.

Thanks, I’m successfully join to the Wechaty Organization.