Create easy to learn tutorials for beginner users of Wechaty - blog post by jaya gupta
wechaty/docusaurus pull request #804
Opened 2021-05-03 12:21 UTC by jaya2320

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-03 12:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=804) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=804) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=804) it.</sub>

2021-05-03 20:28 UTC, huan requested changes

2021-05-03 20:28 UTC, huan commented on jekyll/_contributors/jaya2320.md
> +CTO of BotWave
I don't think you are the CTO of BotWave.

2021-05-03 20:28 UTC, huan commented on jekyll/_posts/2021-05-03-jaya_post.md
> +{% include iframe.html src="https://docs.google.com/document/d/1idLYEoqKcYoeID2jY-xufh3gRlDJhbmyy7MRhka38Q0/edit?usp=sharing" %}
Please write a blog post for introducing yourself, instead of just link another doc here.

P.S. I don't think our iframe.html supports google docs now.

2021-05-04 12:29 UTC, huan commented
Link to #817

2021-05-04 13:41 UTC, jaya2320 commented on jekyll/_posts/2021-05-03-jaya_post.md
> +{% include iframe.html src="https://docs.google.com/document/d/1idLYEoqKcYoeID2jY-xufh3gRlDJhbmyy7MRhka38Q0/edit?usp=sharing" %}
Sorry for the mistake

2021-05-04 13:46 UTC, jaya2320 commented on jekyll/_posts/2021-05-03-jaya_post.md
> +{% include iframe.html src="https://docs.google.com/document/d/1idLYEoqKcYoeID2jY-xufh3gRlDJhbmyy7MRhka38Q0/edit?usp=sharing" %}
Ok, I will. Sorry for the mistake.

2021-05-20 05:55 UTC, Rohitesh-Kumar-Jain commented
@jaya2320 are you still working on this PR?

2021-05-20 11:17 UTC, jaya2320 commented
No

On Thu, May 20, 2021, 11:25 AM Rohitesh Kumar Jain ***@***.***>
wrote:

> @jaya2320 <https://github.com/jaya2320> are you still working on this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/804#issuecomment-844723004>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONNRBWV2KARN756YDB4EN3TOSP57ANCNFSM44AXADDQ>
> .
>

2021-05-20 11:51 UTC, Rohitesh-Kumar-Jain commented
As the PR is still failing tests, I afraid that our only options are either we close this PR or you may push few commits to fix the tests : )

2021-05-20 12:28 UTC, jaya2320 commented
Ok, I will do that

On Thu, May 20, 2021, 5:21 PM Rohitesh Kumar Jain ***@***.***>
wrote:

> As the PR is still failing tests, I afraid that our only options are
> either we close this PR or you may push few commits to fix the tests : )
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/804#issuecomment-845024681>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONNRBTQRL5ECEEZNW6STNTTOTZUNANCNFSM44AXADDQ>
> .
>

2021-05-20 12:35 UTC, jaya2320 commented
Hey, I don't know why this is happening can you please help me out?

>
>>

2021-05-20 12:57 UTC, Rohitesh-Kumar-Jain commented
> Ok, I will do that

Yes, that's a really impressive attitude, and this was what I was expecting from you.

2021-05-20 13:01 UTC, Rohitesh-Kumar-Jain commented
First, run the test locally in your terminal, 
using 'npm install' and 'npm test'.

Then see why actually your tests are failing, you will get clear messages why your tests are failing. 
Follow those messages and make changes in your files, and then push it again.

2021-05-20 13:03 UTC, Rohitesh-Kumar-Jain commented
> Hey, I don't know why this is happening can you please help me out?
> […](#)
> >


jekyll/_posts/2021-05-03-jaya_post.md:142:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:142 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 13]
jekyll/_posts/2021-05-03-jaya_post.md:143:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:143 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 14]
jekyll/_posts/2021-05-03-jaya_post.md:144:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:144 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 15]
jekyll/_posts/2021-05-03-jaya_post.md:145:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:145 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 16]
jekyll/_posts/2021-05-03-jaya_post.md:146:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:146 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 17]
jekyll/_posts/2021-05-03-jaya_post.md:147:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:147 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 18]
jekyll/_posts/2021-05-03-jaya_post.md:148:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:148 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 19]
jekyll/_posts/2021-05-03-jaya_post.md:149:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:149 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 20]
jekyll/_posts/2021-05-03-jaya_post.md:150:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:150 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 21]
jekyll/_posts/2021-05-03-jaya_post.md:151:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:151 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 22]
jekyll/_posts/2021-05-03-jaya_post.md:152:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:152 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 23]
jekyll/_posts/2021-05-03-jaya_post.md:153:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:153 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 24]
jekyll/_posts/2021-05-03-jaya_post.md:154:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-03-jaya_post.md:154 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 25]
jekyll/_posts/2021-05-03-jaya_post.md:155 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 26]
jekyll/_posts/2021-05-03-jaya_post.md:156 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 27]
jekyll/_posts/2021-05-03-jaya_post.md:157 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 28]

These are the errors that you are getting, just read them and apply them and you will be good to go.

2021-05-20 13:10 UTC, Rohitesh-Kumar-Jain commented
Like in the line 142, you have a 1 trailing space, remove that error and you will have one less error.
In a similar way, you may proceed further.

I wish we could select everyone this year, but will say that you are still welcome to be part of the community, even if you wish you can even join our weekly meetings and participate in the discussion. 
Feel free to leave your thoughts in the PRs of other tech writers, feel free to give suggestions on the doc delivered by other writers.

2021-05-20 15:10 UTC, jaya2320 commented
Thank you for your response.

On Thu, May 20, 2021 at 6:41 PM Rohitesh Kumar Jain <
***@***.***> wrote:

> Like in the line 142, you have a 1 trailing space, remove that error and
> you will have one less error.
> In a similar way, you may proceed further.
>
> I wish we could select everyone this year, but will say that you are still
> welcome to be part of the community, even if you wish you can even join our
> weekly meetings and participate in the discussion.
> Feel free to leave your thoughts in the PRs of other tech writers, feel
> free to give suggestions on the doc delivered by other writers.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/804#issuecomment-845106703>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONNRBXLY62UDIS63RPWM2LTOUC7BANCNFSM44AXADDQ>
> .
>

2021-05-20 15:10 UTC, jaya2320 commented
Thank you for helping me out.

On Thu, May 20, 2021 at 6:41 PM Rohitesh Kumar Jain <
***@***.***> wrote:

> Like in the line 142, you have a 1 trailing space, remove that error and
> you will have one less error.
> In a similar way, you may proceed further.
>
> I wish we could select everyone this year, but will say that you are still
> welcome to be part of the community, even if you wish you can even join our
> weekly meetings and participate in the discussion.
> Feel free to leave your thoughts in the PRs of other tech writers, feel
> free to give suggestions on the doc delivered by other writers.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/804#issuecomment-845106703>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONNRBXLY62UDIS63RPWM2LTOUC7BANCNFSM44AXADDQ>
> .
>

2021-05-23 08:30 UTC, huan commented
Thanks to @Rohitesh-Kumar-Jain for helping @jaya2320 to make this PR green, appreciate it.

2021-05-23 08:30 UTC, merged

2021-05-23 08:31 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited Jaya Gupta to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!