Project Proposal by Abhishek Jaiswal
wechaty/docusaurus pull request #807
Opened 2021-05-03 17:12 UTC by abhishek-iiit

- Added Project Proposal by Abhishek Jaiswal

2021-05-03 20:26 UTC, huan requested changes
Thank you very much for adding your introduction blog post as a GSoD'21 technical writer!

Please make sure the CI turns green by fixing all the issues showed by the GitHub Actions so that we can continue reviewing this PR.

2021-05-04 12:29 UTC, huan commented
Link to #817

2021-05-05 04:46 UTC, huan requested changes

2021-05-05 04:46 UTC, huan commented on jekyll/_posts/2016-12-03-project-proposal-wechaty.md
> +title: Project Proposal for GSoD'21
Please add your name to the title:

`Abhishek Jaiswal: Project Proposal for GSoD'21`

2021-05-05 04:46 UTC, huan commented on jekyll/_posts/2016-12-03-project-proposal-wechaty.md
> +categories: article
Please change the categories from `article` to `proposal` so that we can use this category to show all proposals.

2021-05-05 05:25 UTC, abhishek-iiit commented on jekyll/_posts/2016-12-03-project-proposal-wechaty.md
> +categories: article
Thank you soo much for the feedback.Renamed the title and ghe category as per the instruction :)

2021-05-05 08:50 UTC, huan approved these changes
LGTM

2021-05-05 08:51 UTC, merged

2021-05-05 08:51 UTC, huan commented
Thank your very much for adding your proposal to our blog!