2021 GSoD Proposal: Simin Liao
wechaty/docusaurus pull request #819
Opened 2021-05-04 17:52 UTC by proudofsimin

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-04 17:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=819) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=819) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=819) it.</sub>

2021-05-04 19:19 UTC, huan commented
Link to #817

2021-05-04 19:26 UTC, huan requested changes
Thank you very much for submitting a blog post to the Wechaty blog.

Please make sure the CI turns green for your PR so that we can review and merge it!

2021-05-06 12:01 UTC, iamrajiv requested changes

2021-05-06 12:01 UTC, iamrajiv commented on jekyll/_posts/2021-05-04-gsod21-proposal.md
> +
@proudofsimin Please remove unnecessary line breaks and also add the image.

2021-05-09 19:04 UTC, huan requested changes
Please make sure the CI turns green before we can merge your great PR!

2021-05-11 17:23 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited Simin Liao to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

2021-05-11 17:51 UTC, huan reviewed
Please

2021-05-11 17:51 UTC, huan commented on jekyll/_posts/2021-05-04-gsod21-simin-proposal.md
> +title: Wechaty-Create easy to learn tutorials for beginner users of Wechaty
Please change the title to "volunteer" as well.

2021-05-11 17:51 UTC, huan commented on jekyll/_contributors/proudofsimin.md
> +
It would be great if you can copy/paste more information about yourself from the proposal to here because it would help other visitors to learn you more!

2021-05-12 01:32 UTC, huan commented
Hi Simin,

I have invited you to join our Wechaty GitHub Organization, please accept it by following the below message.

> You've invited Simin Liao to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

After joining our organization on GitHub, your Pull Requests will be able to run GitHub Actions automatically so that you can get a quick response about the CI result for your PR.

2021-05-12 06:44 UTC, huan approved these changes
LGTM

2021-05-12 06:44 UTC, merged

2021-05-12 06:45 UTC, huan commented
Thank you very much for creating your proposal blog post as well as the beautiful contributor profile page, welcome on boarding!