Create Chris GSOD2021
wechaty/docusaurus pull request #825
Opened 2021-05-05 10:10 UTC by chris-4444

Note: <Ongoing Progress>
________________________________________________
Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-05 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=825) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=825) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=825) it.</sub>

2021-05-05 12:56 UTC, huan requested changes
I'm looking forward to seeing your PR to be ready for reviewing!

2021-05-20 05:56 UTC, Rohitesh-Kumar-Jain commented
Hi @chris-4444 is the PR ready to be merged or you would like to push few more commits?

2021-05-20 07:02 UTC, chris-4444 commented
no more commits, since my new proposal was the joint proposal with joseph. ty @Rohitesh-Kumar-Jain

2021-05-26 08:15 UTC, Rohitesh-Kumar-Jain approved these changes
@huan PR is ready to get merged.

2021-05-26 08:15 UTC, Rohitesh-Kumar-Jain commented on Chris GSOD2021
> +---
LGTM

2021-07-10 09:56 UTC, lijiarui commented
Hi @shraddhavp As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-10 10:44 UTC, lijiarui approved these changes
Seems it's too simple..

2021-07-10 11:02 UTC, lijiarui requested changes
As profile request:

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Create your contributor profile (if you are a first time contributor)
- [ ] Add avatar for your contributor profile

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

2021-08-23 13:18 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 either work upon this, or close this : )

2021-09-07 17:15 UTC, huan commented
ping @chris-4444

2021-09-21 15:14 UTC, lijiarui commented
ping @chris-4444 

We will close this PR if there has no more commits send to it before the end of Sep.

2021-09-28 16:07 UTC, lijiarui commented
ping @chris-4444

I will close this PR tomorrow.

2021-09-29 05:38 UTC, chris-4444 commented
No worries, we can close this PR. I was creating my own proposal and then, came the [joint proposal](https://docs.google.com/document/d/1VxIByga8Lui6raoyrosfvjQ8zelpwk-1ci7uk8mZ57M/edit#heading=h.4ajz67fdcwye) after the Wechaty meeting, just before the final TW selection. Ty. 😎

2021-09-29 05:38 UTC, closed without merging