Ahmed Essam - GSoD'21
wechaty/docusaurus pull request #828
Opened 2021-05-05 13:37 UTC by Hanaffi

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-05 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=828) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=828) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=828) it.</sub>

2021-05-05 19:52 UTC, huan requested changes
Please follow my review and make suer the CI turns green, thanks!

2021-05-05 19:52 UTC, huan commented on jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md
> +categories: article
Please use `categories: proposal` instead of `article` for a better category.

2021-05-05 20:59 UTC, huan requested changes
Please make the CI green before we can merge your great PR, thanks!

2021-05-06 11:27 UTC, iamrajiv requested changes
@Hanaffi Please sign the CLA (Contributors License Agreement).

2021-05-06 16:43 UTC, Hanaffi commented
@huan Idk why it failed again :/

2021-05-06 17:09 UTC, huan requested changes
From <https://github.com/wechaty/wechaty.js.org/runs/2519437947> you can found the following error messages:

```
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:18:166 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:74 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:104:21 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:111 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:112 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:115:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:116:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:118 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:119 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:122:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:126:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:127:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:128:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:132:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:132:31 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:133:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:133:32 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:137:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:138:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:142:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:142:133 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:143:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:143:128 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:147:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:148:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:148:129 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:152:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:153:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:153:98 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:155:35 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:157:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:157:98 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:158:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:158:116 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:160:34 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:162:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:162:116 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:163:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:165:35 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:167:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:167:71 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:169:36 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:171:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:171:73 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md:173 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

You need to fix all of them in your files and then resubmit again to see what else our CI system will tell you.

Also you can run `npm test` in your local environment to run all the tests locally.

2021-05-12 17:47 UTC, iamrajiv requested changes
@Hanaffi Please fix these issues

![Screenshot 2021-05-12 at 11 16 15 PM](https://user-images.githubusercontent.com/42106787/118020759-18e46200-b378-11eb-83cf-9db01737ce2d.jpg)

2021-05-15 10:53 UTC, huan requested changes
Please follow the error message from CI and fix them before we can continue reviewing this PR, thanks!

2021-05-20 05:57 UTC, Rohitesh-Kumar-Jain commented
@Hanaffi  would you like to add some more commits to this PR?

2021-05-23 05:03 UTC, huan requested changes
Please make the CI green before we can continue reviewing it.

P.S. You can run `npm test` locally to make sure everything is ok before `git push`

2021-05-23 17:05 UTC, Hanaffi commented
@huan It should be working fine now. I tested it locally 💯

2021-05-23 19:22 UTC, Hanaffi commented
@huan Its following the naming convention but IDK why the test fails.
Can we merge it?

2021-05-23 23:43 UTC, iamrajiv requested changes

2021-05-23 23:43 UTC, iamrajiv commented on jekyll/_posts/2021-05-05-Ahmed-Essam-GSOD-Proposal.md
> +<div align="center">
@Hanaffi Please add Front Matter here. I would suggest you follow other posts in `jekyll/posts/`.

2021-05-24 16:55 UTC, huan requested changes
Please make sure the PR has passed all the CI tests and turns _green_. (you can run all tests locally by run `npm test`)

2021-05-24 18:49 UTC, Hanaffi commented
@huan  @Rohitesh-Kumar-Jain Can you check :/ ?

2021-05-25 13:56 UTC, Rohitesh-Kumar-Jain commented
> @huan @Rohitesh-Kumar-Jain Can you check :/ ?

Nice work, now you have just one test case failing.

the test which is failing is : 

# front matter key `author` should has a value exist in jekyll/_contributors/__VALUE__.md file
not ok 15 "jekyll/_posts/2021-05-05-gsod-2021-volunteering-proposal.md" author profile should exist at jekyll/_contributors/Ahmed Essam.md
  ---
    operator: fail
    at: Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/contributor-profile.spec.ts:40:9)
    stack: |-
      Error: "jekyll/_posts/2021-05-05-gsod-2021-volunteering-proposal.md" author profile should exist at jekyll/_contributors/Ahmed Essam.md
          at Test.assert [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/contributor-profile.spec.ts:40:9)
  ...


This means that you need to create your contributor profile first to write a blog post. Basically, just create your contributes profile [here](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) like other profiles.

2021-05-25 14:19 UTC, Hanaffi commented
@Rohitesh-Kumar-Jain Thank you :)
Can you check this: https://github.com/wechaty/wechaty.js.org/pull/895 ?

2021-05-26 11:18 UTC, Hanaffi commented
@huan @Rohitesh-Kumar-Jain Please consider this https://github.com/wechaty/wechaty.js.org/pull/898

2021-05-27 06:04 UTC, closed without merging