nbwsc's article
wechaty/docusaurus pull request #83
Opened 2018-05-07 16:04 UTC by nbwsc

Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 layout: post
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

2018-05-08 02:33 UTC, huan requested changes
Please fix the url dot bug, then I could be able to merge the new blog!

Thank you!

2018-05-08 02:33 UTC, zixia commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +* [littlecodersh/ItChat](https://github。com/littlecodersh/ItChat)|wxpy 就是基于此开发
github。com -> github.com

2018-05-08 02:33 UTC, zixia commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +接下去就是找找现成模块有没有能用的， 如果不够用， 就找找有没有开源， 改改代码。 实在不行也可以自己写， xposed 模块还是挺好写的。对了还有一个叫[VirtualXposed](https://github。com/android-hacker/VirtualXposed)的东西，修改微信 hook 的事情，这个足够了， 不需要 root。
github。com -> github.com

2018-05-08 02:33 UTC, zixia commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +* [HanSon/vbot](https://github。com/hanson/vbot)|基于 PHP7 的微信个人号机器人，通过实现匿名函数可以方便地实现各种自定义的功能 |[未使用]
github。com -> github.com

2018-05-08 02:33 UTC, zixia commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +* [sjdy521/Mojo-Weixin](https://github。com/sjdy521/Mojo-Weixin)|使用 Perl 语言编写的微信客户端框架，可通过插件提供基于 HTTP 协议的 api 接口供其他语言调用 |[未使用]
github。com -> github.com

2018-05-08 02:33 UTC, zixia commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +* [youfou/wxpy](https://github。com/youfou/wxpy) | 优秀的 api 包装和配套插件，微信机器人/优雅的微信个人号 API|[个人评价: 支持 python2/3 api 包装不错 文档写的满分 基于 itchat 开发，也开放了 itchat 的原始数据接口，自由度和封装美化兼顾 ]
github。com -> github.com

2018-05-08 02:33 UTC, zixia commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +> Author: [nbwsc](https://github。com/nbwsc)
github。com -> github.com

2018-05-08 02:58 UTC, nbwsc commented on _posts/2018-05-06-talk-about-wechat-robot.md
> +* [littlecodersh/ItChat](https://github。com/littlecodersh/ItChat)|wxpy 就是基于此开发
sorry, 全局替换的时候忘了这个了...

2018-05-08 03:27 UTC, zixia commented
You can just keep pushing new commits to your cloned repository, and then this PR will be updated automatically. :)

2018-05-08 13:48 UTC, merged

2021-01-02 11:39 UTC, huan commented
@nbwsc Thank you very much for your contribution!

> You've invited Wangshichao to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

And we also have a WeChat room for contributors only which can discuss Wechaty at a deep level, you are welcome to join and if you are interested please contact @lijiarui to ask for an invitation.

Cheers!