Submitting an application blog for GSoD 2021
wechaty/docusaurus pull request #840
Opened 2021-05-06 20:14 UTC by vasvi-sood

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-06 21:10 UTC, iamrajiv requested changes

2021-05-06 21:10 UTC, iamrajiv commented on jekyll/_posts/2021-05-06-vasvi-applicant-for-technical-writer-gsod.md
> +### Hi there👋, I'm Vasvi Sood a GSOD applicant
@vasvi-sood This should be the h2 heading because the first heading should be a top-level heading.

2021-05-06 21:10 UTC, iamrajiv commented on jekyll/_posts/2021-05-06-vasvi-applicant-for-technical-writer-gsod.md
> +
@vasvi-sood Remove this line break.

2021-05-07 05:23 UTC, vasvi-sood commented
My tests are still failing. Could you please guide me

2021-05-07 05:28 UTC, iamrajiv requested changes
@vasvi-sood Format like this

```markdown
---
title: GSoD Applicant (How-to guides)
author: https://github.com/vasvi-sood/
categories: Application blog
tags:
  - documentation
  - gsod
  - 2021
  - project
  - proposal

image: https://github.com/vasvi-sood/wechaty.js.org/blob/master/jekyll/assets/2021/06-Vasvi-applicant-for-technical-writer-gsod/my%20photo.png
---

Sophomore,NIT Hamirpur

## Hi there👋, I'm Vasvi Sood a GSOD applicant

I’m currently pursuing my Bachelor's in Electronics and Communication Engineering from National Institute Of Technology, Hamirpur.
I have applied for the position of Technical writer in Webchatty.
Let's connect:
<a href="https://www.linkedin.com/in/vasvi-sood-176610206/"><img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white"></a>
<a href="https://github.com/vasvi-sood"><img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white"></a>

## My Experience 😇

The Wechaty organization is very welcoming for the first time open source contributors. I faced no issues while making my first pull request to the GitHub repository.
The best part was the transparent and interactive the application process. The mentors were very supportive and offered information that was crucial for beginners like me.

## Why did I apply 🖋️

Comming from a technical background I am well aware about various technologies and developer tools .Story writing has always been my favorite hobby. For me, combining technology
with my writing abilities is a natural match.
I share Wechaty's vision of using simple and descriptive language in documentation to attract developers.
<a href ="https://docs.google.com/document/d/123CtDluY0zCi5c46se4wF1jJEWHf1lkm5TPrEzysfq0/edit?usp=sharing">My Proposal</a>
```

2021-05-07 06:10 UTC, Rohitesh-Kumar-Jain commented
> My tests are still failing. Could you please guide me

You may try running tests locally on your pc before pushing your changes on Github.

To run tests locally use ```npm test```

and after running the tests just fix issues that will be shown in your test log : )

2021-05-07 07:18 UTC, vasvi-sood commented
All tests have passed, kindly merge the pull request now.

2021-05-08 09:03 UTC, huan approved these changes
LGTM

2021-05-08 09:04 UTC, huan commented
Welcome on boarding!

2021-05-08 09:04 UTC, merged