Added GSoD 21 proposal blog : Shraddha and Soumi
wechaty/docusaurus pull request #846
Opened 2021-05-11 07:22 UTC by Soumi7

Added the combined proposal blog post for GSoD 21 project References section by @shraddhavp and @Soumi7 .

2021-05-11 13:27 UTC, huan requested changes

2021-05-11 13:27 UTC, huan commented on jekyll/_posts/2021-05-11-shraddhavp-soumi-combined-reference-proposal.md
> +<iframe width="1028" height="578" src="https://www.youtube.com/embed/82rFox9Vq14" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosc
Please use the following code to simplify your YouTube video embedding:

```html
{% include iframe.html src="https://www.youtube.com/embed/82rFox9Vq14" %}
```

See: https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/

@wechaty/writer

2021-05-11 14:03 UTC, shraddhavp commented
have added the changes as requested @huan

2021-05-11 16:26 UTC, huan approved these changes
LGTM

2021-05-11 16:26 UTC, merged

2021-05-11 16:26 UTC, huan commented
Thank you very much for submitting our first team proposal blog with your great presentation video!

2021-05-15 08:16 UTC, huan commented on jekyll/_posts/2021-05-11-shraddhavp-soumi-combined-reference-proposal.md
> +image: /assets/2021/05-shraddhavp-soumi-combined-reference-proposal/gsod_s.png
Could we please replace this teaser image with our beautiful first page in the presentation?

![image](https://user-images.githubusercontent.com/1361891/118353444-cafa7480-b598-11eb-884c-f52f55e6ee25.png)

2021-05-15 08:52 UTC, shraddhavp commented on jekyll/_posts/2021-05-11-shraddhavp-soumi-combined-reference-proposal.md
> +image: /assets/2021/05-shraddhavp-soumi-combined-reference-proposal/gsod_s.png
@huan you mean that image must be replaced with the below one ?
![firstpage](https://user-images.githubusercontent.com/42699578/118354508-00976180-b589-11eb-8f0d-9a0aab1dcf25.png)

2021-05-15 08:53 UTC, shraddhavp commented on jekyll/_posts/2021-05-11-shraddhavp-soumi-combined-reference-proposal.md
> +image: /assets/2021/05-shraddhavp-soumi-combined-reference-proposal/gsod_s.png
@huan  you mean that image must be replaced with the below one 
![Screenshot (154)](https://user-images.githubusercontent.com/42699578/118354540-1f95f380-b589-11eb-911b-c9df574d6c7e.png)

2021-05-15 08:58 UTC, huan commented on jekyll/_posts/2021-05-11-shraddhavp-soumi-combined-reference-proposal.md
> +image: /assets/2021/05-shraddhavp-soumi-combined-reference-proposal/gsod_s.png
The current version of our post will use `/assets/2021/05-shraddhavp-soumi-combined-reference-proposal/gsod_s.png` as the teaser image.

In our blog post list page and the blog post page, the teaser image will show as the following screenshots:

![image](https://user-images.githubusercontent.com/1361891/118354566-37c43d80-b59e-11eb-8631-499b44a0c596.png)

![image](https://user-images.githubusercontent.com/1361891/118354613-680bdc00-b59e-11eb-8809-114cec8b6362.png)

The above image is too general and can be improved by replacing it with a more meaningful image.

My suggestion is to replace the current teaser image with  a beautiful and meanful image from your slide, for example, the first page or the second page from the slide will all be good.

Please feel free to ask me if I explains not clear enough, thanks!

2021-05-15 08:59 UTC, shraddhavp commented on jekyll/_posts/2021-05-11-shraddhavp-soumi-combined-reference-proposal.md
> +image: /assets/2021/05-shraddhavp-soumi-combined-reference-proposal/gsod_s.png
ya sure @huan