GSoD'21 Volunteering Proposal
wechaty/docusaurus pull request #851
Opened 2021-05-12 16:17 UTC by Rohitesh-Kumar-Jain

I am adding the GSoD'21 volunteering proposal on behalf of myself and Simin.

2021-05-12 16:43 UTC, huan requested changes
Hi, it's great for having our volunteer team proposal blog post!

Could we please add the team presentation YouTube video in our blog post so that we can better explain our proposal to the community? Thanks!

2021-05-12 17:44 UTC, iamrajiv requested changes

2021-05-12 17:44 UTC, iamrajiv commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +* I’d like to prefer to be contacted primary by my email zixia@zixia.net, and the secondary channel on WeChat (ID: 918999).
```suggestion
* I’d like to prefer to be contacted primarily by my email zixia@zixia.net and the secondary channel on WeChat (ID: 918999).
```

2021-05-12 17:44 UTC, iamrajiv commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +Thanks for reading our post, Cheers!
```suggestion
Thanks for reading our post. Cheers!
```

Joining two independent clauses with a comma but no conjunction creates a run-on sentence.

2021-05-12 17:44 UTC, iamrajiv commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +7) Will create my own whatsapp bot using Wechaty and give feedback on the current state of documentation.
```suggestion
7) I Will create my own WhatsApp bot using Wechaty and give feedback on the current state of documentation.
```

2021-05-12 17:44 UTC, iamrajiv commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +* I will be in touch with the org via mailing list, Gitter and GitHub and you could find me through Gmail, WhatsApp, or WeChat (ID: siminmin1128).
```suggestion
* I will be in touch with the org via mailing list, Gitter, and GitHub, and you could find me through Gmail, WhatsApp, or WeChat (ID: siminmin1128).
```

2021-05-13 13:44 UTC, iamrajiv approved these changes

2021-05-13 15:30 UTC, huan requested changes
Could we please add the team presentation YouTube video in our blog post so that we can better explain our proposal to the community? Thanks!

2021-05-13 15:36 UTC, Rohitesh-Kumar-Jain commented
> Could we please add the team presentation YouTube video in our blog post so that we can better explain our proposal to the community? Thanks!

Yes, I and Simin are collaborating to make a YT video. 

I will request a review after committing the video, sorry for replying with only a thumbs-up emoji earlier 😅

2021-05-13 18:28 UTC, huan commented
That's alright. Looking forward to seeing the presentation with Simon and you!

2021-05-14 16:43 UTC, Rohitesh-Kumar-Jain commented
@huan We have added the team presentation YouTube video in our blog post. 

Special thanks to Simin for spending so much effort in creating the presentation and editing the video.

2021-05-15 06:54 UTC, huan approved these changes
LGTM

2021-05-15 06:55 UTC, merged

2021-05-15 06:58 UTC, huan commented
Thank you very much for the volunteer team proposal!

2021-05-15 08:02 UTC, huan commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +image: /assets/2021/05-gsod-2021-volunteering-proposal/gsod_s.png
Could we change this teaser image to the beautiful title page from our slide? Because that would make our blog post beautiful too!

![image](https://user-images.githubusercontent.com/1361891/118352957-e1073580-b596-11eb-9330-8a9435130708.png)

@proudofsimin @Rohitesh-Kumar-Jain

2021-05-15 08:50 UTC, Rohitesh-Kumar-Jain commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +image: /assets/2021/05-gsod-2021-volunteering-proposal/gsod_s.png
Sure, I will change this teaser image to this slide page in the next PR.

2021-05-15 09:21 UTC, Rohitesh-Kumar-Jain commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +image: /assets/2021/05-gsod-2021-volunteering-proposal/gsod_s.png
This image is exceeding the maximum limit of size, it's size is size: 1926439, and the limitation is size<=1048576, I need to either crop or reduce the quality of the image.

2021-05-15 10:58 UTC, huan commented on jekyll/_posts/2021-05-12-gsod-2021-volunteering-proposal.md
> +image: /assets/2021/05-gsod-2021-volunteering-proposal/gsod_s.png
Thank you very much for making the teaser image beautiful! 

I'd like to suggest that we should use the `.webp` for the default image format for all of our technical writers.