References API 1
wechaty/docusaurus pull request #865
Opened 2021-05-18 10:21 UTC by Soumi7

Added API references structure.

2021-05-18 10:40 UTC, Rohitesh-Kumar-Jain commented
I would like to suggest that, pls do add a screenshot of the documentation, after running it on your local server, like this https://github.com/wechaty/wechaty.js.org/pull/862

2021-05-18 10:47 UTC, Soumi7 commented
@Rohitesh-Kumar-Jain Sure

2021-05-20 06:02 UTC, Rohitesh-Kumar-Jain commented
@huan I believe we should add @proudofsimin to the Wechaty writer's team, she is probably missing from this team https://github.com/orgs/wechaty/teams/writers

2021-05-20 14:49 UTC, proudofsimin commented
Hi @Soumi7, 
I like your new structure that you fulfill the content. Can you also update your timeline as well? Thank you.
In addition, 
1. Please keep the words consistent and capitalize only the first word in the title. (ex. wechatyAPI -> WechatyAPI, classes -> Classes, Wechaty Options -> Wechaty options ...etc.) See [Capitalization](https://developers.google.com/style/capitalization) for more information.
2. Please keep the headings plural. (ex. Wechaty Event Function -> Wechaty event functions)

Thank you

2021-05-20 15:45 UTC, Soumi7 commented
I will update the timeline in the google doc. 

The headings are just placeholders. Will be updated once me and @shraddhavp start adding content to the pages. One this PR is pushed, she will pull the changes and start.

2021-05-20 16:21 UTC, proudofsimin commented
@Soumi7 Great! Thank you so much!

2021-05-21 12:44 UTC, abhishek-iiit reviewed
This is very helpful!!
Thank you @Soumi7 & @shraddhavp for this PR

2021-05-23 05:23 UTC, huan requested changes
My two cents:

1. Please make all file name to be lower-cased
2. Should we remove the `Wechaty` in the navigating menu so that the menu will be clear? Current version seems have too many `Wechaty` in the menu which I feel is unnecessary.

2021-05-24 06:34 UTC, Soumi7 commented
I have renamed the files to lowercase.

@shraddhavp  will be shifting the content of wechaty.md to other pages next. Hence I have let it remain as it is.

2021-05-26 10:59 UTC, shraddhavp commented
@huan can you please review the PR and check if it is ready to merge as? we have added the contents to the empty files ,but unless this PR is merged we will not be able to add those as CLI  will show docusaurus link failure

2021-05-27 06:10 UTC, Soumi7 commented
@wechaty/writers @huan  We need three reviews to be able to merge this PR. I request anyone from the volunteers to review it, so that we can merge it. We aren't able to proceed with this unless this PR is merged.

2021-05-28 12:52 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/api/wechaty-api/wechaty-api-overview.md
> +Main bot class, A Bot is a wechat client depends on which puppet you use.
I believe this sentence needs to be restated, something seems wrong with this statement. 

Maybe replace it with something like, ```that depends``` or ``` depending upon```

2021-05-28 13:08 UTC, Rohitesh-Kumar-Jain requested changes
I have seen a few grammatical errors.

I would like to suggest all tech writers to use a grammar and spell check software for assistance. [Grammarly](https://app.grammarly.com/) can assist you in this. But if you are looking for a completely free alternative, you can go for [Slick Write](https://www.slickwrite.com/#!home).

Also, Google docs also have some good spelling and grammar checking extensions.

Apart from correcting grammar and spelling mistakes, Grammarly also gives valuable suggestions to improve the writing and you can also get suggestions for better words.

I would be glad if you may take the assistance of some software next time.

Please don't take it as some sort of insult or scolding, I personally take their assistance all the time : )

2021-05-28 13:28 UTC, Rohitesh-Kumar-Jain commented
Also don't depend too much on them, at times they don't give the best advice. But if you will use them as the first line of checking, 95% of errors will be caught by them. And it will eventually help us reduce the number of review iterations in PRs.

2021-05-28 15:50 UTC, shraddhavp commented
@Rohitesh-Kumar-Jain , here @Soumi7  has just added  the structure for the api overview section, by adding empty files, next in the upcoming PR we will add the contents to these empty files

2021-05-28 16:08 UTC, shraddhavp commented
> I have seen a few grammatical errors.
> 
> I would like to suggest all tech writers to use a grammar and spell check software for assistance. [Grammarly](https://app.grammarly.com/) can assist you in this. But if you are looking for a completely free alternative, you can go for [Slick Write](https://www.slickwrite.com/#!home).
> 
> Also, Google docs have some good spelling and grammar checking extensions.
> 
> Apart from correcting grammar and spelling mistakes, Grammarly also gives valuable suggestions to improve the writing and you can also get suggestions for better words.
> 
> I would be glad if you may take the assistance of some software next time.
> 
> Please don't take it as some sort of insult or scolding, I personally take their assistance all the time : )

Yes when we will fill in the content we will check it

2021-05-28 16:11 UTC, Rohitesh-Kumar-Jain approved these changes
> Main bot class, A Bot is a wechat client depends on which puppet you use.

You added this line in this PR, so I though it will be best to remove errors in this PR only, but I am sorry I wan't aware that you are going to work on it in the next PR.

> I like your new structure that you fulfill the content.

As @proudofsimin approved the structure, and the changes suggested by Huan have been implemented I believe this PR is ready to be merged.

ping @huan

2021-05-30 06:21 UTC, proudofsimin approved these changes

2021-07-10 10:17 UTC, lijiarui commented
@Soumi7 and @shraddhavp  As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-12 14:24 UTC, Rohitesh-Kumar-Jain commented
@shraddhavp  We would be glad if you may once go through the PR, and either request for changes or approve the PR.

2021-07-17 05:28 UTC, Soumi7 commented
@shraddhavp  Could you review this?

2021-07-17 07:05 UTC, shraddhavp commented
LGTM

2021-07-17 07:09 UTC, shraddhavp approved these changes

2021-07-18 19:12 UTC, lijiarui requested changes
We should change all of md files to mdx here.

2021-07-19 14:20 UTC, shraddhavp commented
yes @lijiarui  mam have changed the files to mdx files

2021-07-29 15:44 UTC, lijiarui requested changes

2021-07-29 15:44 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/classes.mdx
> +
Please change path `wechaty-api` to `wechaty` Since it is Wechaty Class

2021-07-29 15:44 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/typedefs.mdx
> +---
Please change path `wechaty-api` to `wechaty` Since it is Wechaty Class

2021-07-29 15:44 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/wechaty-api-overview.mdx
> +---
Please change path `wechaty-api` to `wechaty` Since it is Wechaty Class

2021-07-29 15:44 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/wechaty-logonoff.mdx
> +title: Wechaty log on off
Please change path `wechaty-api` to `wechaty` Since it is Wechaty Class

2021-07-29 15:44 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/wechaty-logout.mdx
> +title: Wechaty logout
Please change path `wechaty-api` to `wechaty` Since it is Wechaty Class

2021-07-29 15:44 UTC, lijiarui commented on docusaurus/sidebars.ts
> +  label: 'wechaty-api',
Please change `wechaty-api` to `wechaty` Since it is Wechaty Class

2021-08-09 17:22 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-api/typedefs.mdx
> +---
Changed.

2021-08-16 10:07 UTC, Rohitesh-Kumar-Jain commented
@lijiarui I would be glad if we may prioritize this PR merge, as it is blocking the progress of this team

2021-08-23 03:13 UTC, Rohitesh-Kumar-Jain commented
@lijiarui this PR is blocking their progress, can we prioritize perfecting this PR : )

2021-08-23 04:24 UTC, shraddhavp commented
> @lijiarui this PR is blocking their progress, can we prioritize perfecting this PR : )

yes mam @lijiarui, please prioritize  this issue

2021-08-23 17:09 UTC, lijiarui requested changes
Pls remove the useless file, thanks!

2021-08-23 17:09 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/classes.mdx
> +
It feels a little bit strange that it still has this file. Maybe we should delete this file, since it is no longer useful

2021-08-23 17:09 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/typedefs.mdx
> +---
It feels a little bit strange that it still has this file. Maybe we should delete this file, since it is no longer useful

2021-08-23 17:09 UTC, lijiarui commented on docusaurus/docs/api/wechaty-api/wechaty-api-overview.mdx
> +---
It feels a little bit strange that it still has this file. Maybe we should delete this file, since it is no longer useful

2021-08-24 04:45 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-api/classes.mdx
> +
I should delete the classes.mdx file?

2021-08-24 04:49 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-api/classes.mdx
> +
Once this PR gets merged, @shraddhavp will be adding content to pages which look comparatively empty.

2021-08-24 04:50 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-api/classes.mdx
> +
Same for the rest of the files with less content. The content will be added once this PR is merged. This is just the file structure.

2021-08-24 04:52 UTC, Soumi7 commented
@lijiarui Do you mean we dont need the classes, typedefs and api-overview sections? I think we can let this structure be. Next Shraddha will be adding content to these pages

2021-08-25 18:24 UTC, lijiarui commented
@Rohitesh-Kumar-Jain How do you think about this?

Since this PR doesn't have any wechaty things, so you can decide to merge or not.

Actually, for me, I feel a little bit confuse about this part, since I don't know what content are you going to add for the doc.

My suggestion is PR for reference like the tutorials team did. Instead of updating all the contents and nav_bar at once, they update the contents and nav_bar of the corresponding chapter every time a small chapter is written.

Then we can clearly guide what to merge and what not to merge, and what name is the most appropriate one.

2021-08-26 02:59 UTC, Rohitesh-Kumar-Jain commented
> Actually, for me, I feel a little bit confuse about this part, since I don't know what content are you going to add for the doc.

This PR I believe was just intended to add the structure.

> My suggestion is PR for reference like the tutorials team did. Instead of updating all the contents and nav_bar at once, they update the contents and nav_bar of the corresponding chapter every time a small chapter is written.

Probably this PR was just intended to demonstrate the structure, but as it has gone through so many iterations, and I didn't ask them early to close this, so I am leaving upon @shraddhavp and @Soumi7 to decide what they wish to do.

So what I see, is that we have two options : 

1) Merge this PR and then merge other PRs.

2) Close this PR and then update already existing PRs to reflect changes.

2021-08-26 03:57 UTC, Soumi7 commented
@lijiarui Understood. I can remove the files whose content we are not sure about. Will do that and update this PR. Then it can be merged @Rohitesh-Kumar-Jain

2021-08-26 05:15 UTC, Soumi7 commented
> Pls remove the useless file, thanks!

I have removed the unnecessary files as suggested.

2021-08-26 13:37 UTC, lijiarui commented
@Rohitesh-Kumar-Jain  Feel free to merge this PR when you think it should be merged! Thanks!

2021-08-26 16:15 UTC, Rohitesh-Kumar-Jain commented
> @Rohitesh-Kumar-Jain Feel free to merge this PR when you think it should be merged! Thanks!

I need your approval to merge, because merging is blocked

2021-09-01 14:25 UTC, lijiarui approved these changes

2021-09-01 14:25 UTC, lijiarui commented
Hi @Rohitesh-Kumar-Jain  Sorry for approving late, you can merge when you think it is ready.

2021-09-02 06:37 UTC, Rohitesh-Kumar-Jain commented
@huan the requested changes have been approved

2021-09-07 14:09 UTC, shraddhavp commented
@huan  can you please approve the PR ,so that we can merge it

2021-09-07 17:18 UTC, huan requested changes
Dear all,

I saw a lot of conversations in this PR, but all the MDX files are still empty?

Is there a plan to fulfill those docs, so that we can start reviewing this PR?

Thank you very much.

2021-09-08 04:35 UTC, Rohitesh-Kumar-Jain commented
> I saw a lot of conversations in this PR, but all the MDX files are still empty?

This PR just aimed to add the structure, that's why files are still empty

2021-09-08 04:45 UTC, shraddhavp commented
closing the PR as the contents are updated in PR #913  and #916

2021-09-10 14:54 UTC, closed without merging