Overview of wechaty documentation
wechaty/docusaurus pull request #870
Opened 2021-05-19 11:46 UTC by nibble0101

# Improve the Introduction and Explanations project

| Section | Sub-section | Author |
| --- | --- | --- |
| Introduction | Overview | Joseph Mawa |

This the **Overview** sub-section of the **Introduction** section

2021-05-20 11:48 UTC, Rohitesh-Kumar-Jain commented
@proudofsimin

2021-05-21 15:22 UTC, proudofsimin reviewed
Hi @nibble0101, 

Overall this is a very great document! I left some comments below and also reference of Google style. Feel free to let me know if you have any question.

2021-05-21 15:22 UTC, proudofsimin commented on docusaurus/docs/overview.mdx
> +This is a learning oriented section which consists of both beginner and advanced tutorials. The beginner tutorials will take you by the hand and teach you how to build a Chatbot application from scra
> Note: If you are an absolute beginner, we recommend you to start with the [Introduction](https://wechaty.js.org/docs/) to familiarize yourself with Wechaty, Wechaty community and the Wechaty ecosystem.

This is a learning-oriented section which consists of two levels of tutorials:
- [Beginner tutorials](https://wechaty.js.org/docs/getting-started/)
- [Advanced tutorials](https://wechaty.js.org/docs/tutorials/docker)

### Beginner tutorials

The beginner tutorials will guide you how to build a Chatbot application from scratch through a series of steps. ...

### Advanced tutorials

...

(Ref: [Hyphens](https://developers.google.com/style/hyphens), [Notes](https://developers.google.com/style/notices))

2021-05-21 15:22 UTC, proudofsimin commented on docusaurus/docs/overview.mdx
> +The Reference Guide contains technical reference for Wechaty APIs and other aspects of Wechaty's machinery. It describes the various functionalities provided by Wechaty. You can always refer to this
> Prerequisite: You should have basic understanding of Wechaty and familiar with the key concepts in Wechaty and Chatbot application development in general.

The Reference guides contains technical reference for Wechaty APIs and other aspects of Wechaty's machinery. It describes the various functionalities provided by Wechaty. You can always refer to this section to learn more about classes, functions, modules and other aspects of Wechaty's machinery you come across.

(Reference: [Notes](https://developers.google.com/style/notices))

2021-05-23 06:09 UTC, huan commented
@proudofsimin Thank you very much for your comments to improve this PR, I believe they are very valuable.

We should strictly follow the [Documentation System](https://documentation.divio.com/) for our docs contributing,  @nibble0101 please follow the suggestions from @proudofsimin and make sure all our docs can be adaptered to the Documentation System, appreciate it!

2021-05-23 09:49 UTC, nibble0101 commented on docusaurus/docs/overview.mdx
> +This is a learning oriented section which consists of both beginner and advanced tutorials. The beginner tutorials will take you by the hand and teach you how to build a Chatbot application from scra
Thanks @proudofsimin for the review

2021-05-23 10:31 UTC, nibble0101 commented
I don't think CI is failing because the commit I made above.
![image](https://user-images.githubusercontent.com/52580190/119256800-1a5d2800-bbcb-11eb-8259-7376d00ffc20.png)

2021-05-23 16:35 UTC, huan commented
> I don't think CI is failing because of the commit I made above.

Yes, it's not related to this PR.

Sorry for that, I'm fixing it now.

2021-05-25 14:05 UTC, proudofsimin approved these changes
Hi @nibble0101, 

Wow I love it so much! Please correct just three minor typos. Thank you.

2021-05-25 14:05 UTC, proudofsimin commented on docusaurus/docs/overview.mdx
> +The Introduction section provides an in-depth introduction to Wechaty, Wechaty community and the Wechaty ecosystem. It has been tailored for both beginners and experienced Chatbot makers. This sectio
change period to colon at the end.

2021-05-25 14:05 UTC, proudofsimin commented on docusaurus/docs/overview.mdx
> +This is a learning oriented section which consists of two levels of tutorials:
add a hyphen for *learning-oriented*

2021-05-25 14:05 UTC, proudofsimin commented on docusaurus/docs/overview.mdx
> +The advanced tutorials require you to have atleast intermediate to advanced knowledge of Wechaty and chatbot development. If you are an experienced Wechaty developer, you can go ahead and explore the
*atleast* to *at least*

2021-05-28 09:11 UTC, Rohitesh-Kumar-Jain approved these changes
Great work guys, and thanks for fixing the typos 
ping @huan

2021-05-31 08:24 UTC, nibble0101 commented
Tag #872

2021-07-10 09:44 UTC, lijiarui commented
Please resolve the conflict first.

2021-07-12 13:18 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-14 05:35 UTC, chris-4444 approved these changes
LGTM.

2021-07-14 17:28 UTC, lijiarui requested changes
Thanks for updating!

I think the whole file looks good to me, but I suggest we add the link in the page, or file an issue to track this, then adding the issue in the future, or it may cause a dead link in the future.

Also, I file an issue #1089 and looking forward to put the content somewhere in the doc in the future.

2021-07-14 17:28 UTC, lijiarui commented on docusaurus/docs/overview.mdx
> +- [Introduction section](#placeholder)
It seems we already have all of these links, how about we add a link instead of `#placeholder` now?

2021-07-14 17:28 UTC, lijiarui commented on docusaurus/docs/overview.mdx
> +**[Beginner tutorials](tutorials/overview.md)**
Shall we change this to a more specific link or file an issue to track this, and adding this in the future?

2021-07-14 17:28 UTC, lijiarui commented on docusaurus/docs/overview.mdx
> +**[Advanced tutorials](tutorials/overview.md)**
Shall we change this to a more specific link or file an issue to track this, and adding this in the future?

2021-07-15 15:42 UTC, nibble0101 commented on docusaurus/docs/overview.mdx
> +- [Introduction section](#placeholder)
Added them. Check below.

2021-07-15 15:43 UTC, nibble0101 commented on docusaurus/docs/overview.mdx
> +**[Beginner tutorials](tutorials/overview.md)**
Add them.Check commit below

2021-07-15 15:44 UTC, nibble0101 commented on docusaurus/docs/overview.mdx
> +**[Advanced tutorials](tutorials/overview.md)**
I am tracking it in #1091

2021-07-16 19:35 UTC, lijiarui approved these changes
Thanks for the change!

2021-07-16 20:26 UTC, merged

2021-07-16 20:26 UTC, huan commented
Thank you very much for all efforts from everyone as a team, appreciate it!