Improve Introduction and Explanation sections project
wechaty/docusaurus pull request #871
Opened 2021-05-19 14:42 UTC by nibble0101

# Improve the Introduction and Explanations project

| Section | Sub-section | Author |
| --- | --- | --- |
| Introduction | What is Wechaty | Joseph Mawa |

This  **What is Wechaty** sub-section of the **Introduction** section

2021-05-22 08:40 UTC, proudofsimin requested changes
Overall your documentation is really great! I point out some minor corrections and hope we could make it better together!

2021-05-22 08:40 UTC, proudofsimin commented on docusaurus/docs/what-is-wechaty.md
> +A chatbot is a software application used to conduct an online chat conversation instead of direct contact with a human being. Wechaty is an [Open Source](https://opensource.com/resources/what-open-so
I love how you covered a lot of information in the introduction. But maybe next time, we could try to eliminate the use of subordinate clauses :) See [Reduce subordinate clauses](https://developers.google.com/tech-writing/one/short-sentences#reduce_subordinate_clauses_optional)

2021-05-22 08:40 UTC, proudofsimin commented on docusaurus/docs/what-is-wechaty.md
> +Wechaty supports a number of Instant Messaging platforms. You can build a chatbot using Wechaty for any of the following Instant Messaging platforms.
Please change the period at the end of the sentence to a colon. Thx!
(FYI [Lists](https://developers.google.com/style/lists))

2021-05-22 08:40 UTC, proudofsimin commented on docusaurus/docs/what-is-wechaty.md
> +The Wechaty community have developed [Software Development Kits](#placeholder) for most of the popular programming languages. You can build a Wechaty Chatbot in any of the programming languages liste
Please change the period at the end of the sentence to a colon. Thx!
(FYI [Lists](https://developers.google.com/style/lists))

2021-05-22 08:40 UTC, proudofsimin commented on docusaurus/docs/what-is-wechaty.md
> +- **Room management**: You can use it to create rooms, add and remove room members, manage topics, etc
Please see the use of *etc*. [Word list](https://developers.google.com/style/word-list#letter-e)
![image](https://user-images.githubusercontent.com/19759195/119219835-0dccc700-bb1a-11eb-9070-b0cc0584f603.png)

2021-05-22 08:40 UTC, proudofsimin commented on docusaurus/docs/what-is-wechaty.md
> +## Supported Programming Languages
Please capitalize only the first word in the title. See [Capitalization in titles and headings](https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings)

2021-05-22 08:40 UTC, proudofsimin commented on docusaurus/docs/what-is-wechaty.md
> +Our mission is to Make it easy for developers to build Chatbots using WeChaty
It seems that you accidentally capitalized *M* in *make it easy* and forgot the period at the end.

2021-05-23 06:33 UTC, huan commented
Thanks to @proudofsimin for your great review & suggestions of how to follow the Google Developer Documentation Style Guide!

It's very important for our docs to follow those guides because we must be consistent across all docs, especially we have many writers work together.

I'm thinking about whether we can find a linter (linting tool) for enforce those documentation styles, would love to add it to our CI system if there's any.

2021-05-23 14:38 UTC, iamrajiv commented
Hi @huan, I don't think there is a linter that follows the Google developer documentation style guide, but for programming languages, there are separate linters, but I don't think we need that.

So we have to make our linter according to the Google developer documentation style guide, but that would be very hard and can be considered a long process. So as of now, I would suggest making a separate markdown file that lists all the style guide to follow for Wechaty.

In addition to it, I want to add some miscellaneous points which can make the Wechaty workflow better:

- Adding linter to removed unnecessary indentations across all the docs file. There are so many files that have indentations like this (highlighted)

![Screenshot 2021-05-23 at 8 05 56 PM](https://user-images.githubusercontent.com/42106787/119264828-51026500-bc02-11eb-9a9f-c22c0c519c8a.jpg)

- Adding [Prettier](https://prettier.io) support for markdown files. Prettier is an opinionated code formatter. It removes all original styling and ensures that all outputted code conforms to a consistent style. (See this [blog post](https://archive.jlongster.com/A-Prettier-Formatter)).
- Adding spell check GitHub action.
- Adding GitHub action for translating Non-English issues content to English. For example, there are Non-English issues like [#161](https://github.com/wechaty/wechaty.js.org/issues/161). This action will convert that to English.

2021-05-25 14:33 UTC, proudofsimin commented
> Thanks to @proudofsimin for your great review & suggestions of how to follow the Google Developer Documentation Style Guide!
> 
> It's very important for our docs to follow those guides because we must be consistent across all docs, especially we have many writers work together.
> 
> I'm thinking about whether we can find a linter (linting tool) for enforce those documentation styles, would love to add it to our CI system if there's any.

Hi @huan, 

Very great suggestions! but unfortunately I didn't find it. 
Like Rajiv suggested, if we could import grammar or spelling check, that would be awesome.

2021-05-25 14:34 UTC, proudofsimin approved these changes
fantastic!

2021-05-28 09:16 UTC, Rohitesh-Kumar-Jain approved these changes
Looks good to me, great work

2021-06-01 05:26 UTC, Rohitesh-Kumar-Jain commented
ping @huan

2021-07-10 10:19 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-11 17:33 UTC, proudofsimin commented
> hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in #1045
> 
> This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

Hi @chris-4444 Wechaty committee requested review from teammates. Could you review/ sign off it and add a tag `ready to merge` after you finish? Thank you.

2021-07-12 10:24 UTC, chris-4444 requested changes
Updated @nibble0101 @proudofsimin @Rohitesh-Kumar-Jain.

2021-07-12 13:17 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-13 06:39 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 21:38 UTC, lijiarui requested changes

2021-07-18 21:38 UTC, lijiarui commented on docusaurus/docs/what-is-wechaty.md
> +Wechaty is maintained by [Huan](https://github.com/huan), [Rui](#placeholder) and a community of [Open Source Contributors](#placeholder). We are always looking for people to join the Wechaty communi
Here is the link:
```
[Rui](https://github.com/lijiarui)
[Open Source Commiters](https://github.com/wechaty/PMC#wechaty-committers)
[Open Source Contributors](https://wechaty.js.org/contributors/)
```

2021-07-19 18:25 UTC, nibble0101 commented on docusaurus/docs/what-is-wechaty.md
> +Wechaty is maintained by [Huan](https://github.com/huan), [Rui](#placeholder) and a community of [Open Source Contributors](#placeholder). We are always looking for people to join the Wechaty communi
Added the links

2021-07-29 15:03 UTC, lijiarui requested changes
I preview this doc but I found there are two `What is Wechaty here`
![image](https://user-images.githubusercontent.com/6419514/127516563-9931fb62-55bd-4a05-bfd5-b18d7371930c.png)

### 1. What is wechaty
![image](https://user-images.githubusercontent.com/6419514/127516181-8fb18f0b-d36b-44b2-9525-0a6159192ba3.png)


### 2. What is wechaty
![image](https://user-images.githubusercontent.com/6419514/127516438-38c678f7-2bb0-4bb8-80ae-e69ff86fee06.png)

2021-07-29 15:56 UTC, nibble0101 commented
> I preview this doc but I found there are two `What is Wechaty here`
> ![image](https://user-images.githubusercontent.com/6419514/127516563-9931fb62-55bd-4a05-bfd5-b18d7371930c.png)
> 
> ### 1. What is wechaty
> ![image](https://user-images.githubusercontent.com/6419514/127516181-8fb18f0b-d36b-44b2-9525-0a6159192ba3.png)
> 
> ### 2. What is wechaty
> ![image](https://user-images.githubusercontent.com/6419514/127516438-38c678f7-2bb0-4bb8-80ae-e69ff86fee06.png)

The first one is what we wrote and the second is what was originally in the docs. I think we can remove the second one.

2021-07-31 17:44 UTC, lijiarui commented
Hi @nibble0101 
> The first one is what we wrote and the second is what was originally in the docs. I think we can remove the second one.

I thinks instead of remove the origin part, you should merge them together, also remember to use mdx file here.

2021-08-03 13:25 UTC, nibble0101 commented
> Hi @nibble0101
> 
> > The first one is what we wrote and the second is what was originally in the docs. I think we can remove the second one.
> 
> I thinks instead of remove the origin part, you should merge them together, also remember to use mdx file here.

Well. I have merged the two files and changed it to `.mdx`

2021-08-23 16:16 UTC, lijiarui requested changes

2021-08-23 16:16 UTC, lijiarui commented on docusaurus/docs/wechaty.mdx
> +Wechaty is an [Open Source](https://opensource.com/resources/what-open-source) software application for building chatbots. It is a modern Conversational RPA SDK which Chatbot makers can use to create
Please add link (https://wechaty.js.org/docs/explainations/conversational) for Conversation

Please add link (http://wechaty.js.org/docs/explainations/rpa) for RPA

2021-08-23 16:16 UTC, lijiarui commented on docusaurus/docs/wechaty.mdx
> +You can use Wechaty to build a chatbot which automates conversations and interact with people through instant messaging platforms such as [Whatsapp](https://www.whatsapp.com/?lang=en), [Wechat](https
Please add [Wecom](https://work.weixin.qq.com/) as well

2021-09-03 07:33 UTC, nibble0101 commented on docusaurus/docs/wechaty.mdx
> +Wechaty is an [Open Source](https://opensource.com/resources/what-open-source) software application for building chatbots. It is a modern Conversational RPA SDK which Chatbot makers can use to create
Changed the text to hyperlinks.

2021-09-03 07:33 UTC, nibble0101 commented on docusaurus/docs/wechaty.mdx
> +You can use Wechaty to build a chatbot which automates conversations and interact with people through instant messaging platforms such as [Whatsapp](https://www.whatsapp.com/?lang=en), [Wechat](https
Added Wecom to the list

2021-09-06 14:37 UTC, huan approved these changes
LGTM

@nibble0101 Thank you very much for this great PR!

@proudofsimin @Rohitesh-Kumar-Jain @chris-4444  Thank you very much for the review comments and the approvals.

This PR has been in the queue for a long time, and it has already fulfilled the requirements to be merged with three approvements:

1. Approved by the teammate (+1)
2. Approved by the volunteer team (+2)

Could you please help yourself to merge this PR for the community?

And I'd like to encourage all of our technical writers to merge a PR for the community, whenever the PR has fulfilled the requirements, and you believe it's good to be merged.

Thank you very much!

2021-09-07 06:30 UTC, nibble0101 commented
@Rohitesh-Kumar-Jain  Can you merge this? I have failed to merge because either the base branch is protected or because I am the one who opened the PR. I am not exactly sure why.

2021-09-07 12:26 UTC, huan commented
I noticed that @lijiarui has required changes and it might be the blocker of merging this PR.

@nibble0101 Could you please resolve the change request from @lijiarui and ask her to approve this PR and try again to merge?

2021-09-07 12:33 UTC, nibble0101 commented
> I noticed that @lijiarui has required changes and it might be the blocker of merging this PR.
> 
> @nibble0101 Could you please resolve the change request from @lijiarui and ask her to approve this PR and try again to merge?

I have worked on the issues she raised and even requested another review from her.

2021-09-07 16:00 UTC, huan commented
ping @lijiarui

2021-09-07 17:38 UTC, lijiarui requested changes
Please change the IM name, then I will approve this PR. Thanks!

2021-09-07 17:38 UTC, lijiarui commented on docusaurus/docs/wechaty.mdx
> +You can use Wechaty to build a chatbot which automates conversations and interact with people through instant messaging platforms such as [Whatsapp](https://www.whatsapp.com/?lang=en), [Wechat](https
Whatsapp --> WhatsApp
Wechat --> WeChat
Wecom --> WeCom

2021-09-07 18:37 UTC, nibble0101 commented on docusaurus/docs/wechaty.mdx
> +You can use Wechaty to build a chatbot which automates conversations and interact with people through instant messaging platforms such as [Whatsapp](https://www.whatsapp.com/?lang=en), [Wechat](https
Changed

2021-09-09 03:16 UTC, lijiarui approved these changes

2021-09-09 11:45 UTC, merged