What can you do with Wechaty sub-section of Introduction section
wechaty/docusaurus pull request #873
Opened 2021-05-19 15:37 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
| Introduction | What can you do with Wechaty | Chris Estepa |

This  is **What can you do with Wechaty** sub-section of the **Introduction** section

2021-05-20 05:52 UTC, Rohitesh-Kumar-Jain reviewed
Pls go through the remarks added : )

2021-05-20 05:52 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +In this day and age, it is undeniable that chatbots are an essential part of every business and has become a part of our everyday lives. Aside from being a 24/7 digital support tool, chatbots can als
Hi, this seems a great introduction to chatbots. 

But I feel that if the title is what can you do with Wechaty, the first thing that comes to my mind is that you can make your own customised chatbot. You can add your code in it to make it according to your needs.

2021-05-20 05:52 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Wechaty always aims to be at the forefront of the chatbot revolution and by being the only chatbot in the world with the shortest code.
> Wechaty always aims to be at the forefront of the chatbot revolution

This part seems good. 

> and by being the only chatbot in the world with the shortest code.

I am not sure about this part, I feel that there are many other chatbot frameworks, and claiming 

>  by being the only chatbot in the world with the shortest code.

seems ambiguous to me.

I feel it's best that @huan lets us know with what vision he founded the org : )

2021-05-20 06:02 UTC, chris-4444 commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Wechaty always aims to be at the forefront of the chatbot revolution and by being the only chatbot in the world with the shortest code.
hi @Rohitesh-Kumar-Jain I would definitely edit this part. I'll go through it again. This is not yet done and would need improvement. thanks :)

2021-05-20 06:10 UTC, chris-4444 commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +In this day and age, it is undeniable that chatbots are an essential part of every business and has become a part of our everyday lives. Aside from being a 24/7 digital support tool, chatbots can als
~  ty for pointing that out. i'm still familiarizing myself with this. i'll edit this accordingly.

2021-05-22 09:01 UTC, proudofsimin commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +In this day and age, it is undeniable that chatbots are an essential part of every business and has become a part of our everyday lives. Aside from being a 24/7 digital support tool, chatbots can als
Yes, we are not writing a book or an essay. You only need to answer your titles directly.

2021-05-22 09:23 UTC, proudofsimin reviewed
I actually feels like you could talk more in each section. Maybe you could have a talk with @huan to fulfill your content?

2021-05-22 09:23 UTC, proudofsimin commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +
Don't put a list directly under the heading. Try paraphrase the heading and introduce the list.

2021-05-22 10:53 UTC, chris-4444 requested changes
@Rohitesh-Kumar-Jain @proudofsimin updated this.
@huan Can you give some more information  on the business problems that have been solved by using Wechaty so I can elaborate further? Thanks.

2021-05-23 06:53 UTC, huan commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Wechaty always aims to be at the forefront of the chatbot revolution and by being the only chatbot in the world with the shortest code.
@Rohitesh-Kumar-Jain thanks for looping me in!

About the vision of Wechaty, I have thought lots of version in the past, and I feel that our writer team can just go ahead and draft/discuss one for our community, and we can discuss based on that in the future.

@chris-4444 Thank you very much for your improvement, appreciate it!

2021-05-23 07:06 UTC, huan commented
> I actually feel like you could talk more in each section. Maybe you could have a talk with @huan to fulfill your content?

Thanks for looping me in! I agree that we need to learn more from the history / stories from Wechaty so that we can write better docs. Please feel free to ask me any questions when there's any need.

And we have lots of blog posts on our website (you can use Google Translate to read them @nibble0101 ) which I believe will help as well.

2021-05-23 07:09 UTC, huan commented
> @huan Can you give some more information on the business problems that have been solved by using Wechaty so I can elaborate further? Thanks.

No problem! I'd like to loop @lijiarui in this thread and I believe she can share lots of information on the business problems that have been solved by using Wechaty because her company business is building on top of Wechaty.

2021-05-23 08:17 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +
Yeah I agree with her

2021-05-23 16:25 UTC, lijiarui commented
@chris-4444 

### First, I would like to introduce [Juzibot](https://www.juzibot.com/): 

JuziBot is a startup that provides smart marketing and sales services for customers on WeChat and WeCom platforms, the company helps companies build secure and stable [Private Traffic](https://daxueconsulting.com/private-traffic-in-china/), as well as helps corporate clients with customer acquisition and sales conversion. JuziBot currently serves customers in education, consumer, healthcare, and a few other industries, some of the clients include Meituan Dianping, JingDong, L'Oréal, etc., and 80% of these existing customers have been acquired through word of mouth. JuziBot's products have been known to improve the sales experience for one million sales professionals on a daily basis. 

The company was accepted by the highly competitive Baidu AI accelerator in 2018, and it has also been invested by a number of leading VCs including PreAngel, Plug and Play, Y Combinator, TSVC, and Alpha Startups. JuziBot received the CCFA Retail Technology Rising Enterprise Award in 2018. In 2018 and 2019, respectively, the company won 1st place in both the task-based human-machine dialogue response naturalness and the chat-type human-machine dialogue assessment in the SMP Chinese Human-Machine Dialogue Technology Evaluation held by the Chinese Information Processing Society of China (CIPSC).

### Second, I would like to describe more about the problem

You can find our 2 minutes speech in [YC Demo Day](https://www.youtube.com/watch?v=ePKYaGGKsWw) show our business on top of Wechaty in 2019. (We changed our name from BotOrange to Juzibot, but all of the two brands belong to us.)

We are Intercom for WeChat, we help companies to acquire, engage and retain customers via WeChat. In China, WeChat IS the internet. Most Chinese people, they even never open a web browser, they only use WeChat.   But WeChat offers no tools for companies to manage their customers.  There is no Google Analytics, there is no salesforce, there is no intercom. There is nothing. But they need a tool.

We built a customer management tool for WeChat based on WeCom. It is very similar to Intercom. It provides a customer support ticket, includes a chatbot, and provides analytics to the business.

We give Chinese companies the ability to communicate with their customers where they live their life - on WeChat.

Here are two articles that show more about the business:

- [Intercom for WeChat, Why I create Juzibot](https://pre-angel.com/juzibot-why-is-jukebao/)
- [How can brands build private traffic to own their customer traffic](https://pre-angel.com/lijiarui-siyuliuliang/)
- [Juzibot provide chatbot and martech tools to help you get customer better based on WeChat](https://pre-angel.com/juzibot-36kr/)
- [What is Juzibot](https://rui.juzi.bot/thought/2019-1-19-what-is-botorange.html)
- [Microsoft MVP Blog: Six Lines Of Code. Two MVPs. One Chatbot.](https://wechaty.js.org/2020/11/10/six-lines-code-two-ai-mvps-one-chatbot/)

Hope it can help a lot, and feel free to contact me if you have more questions.

2021-05-23 16:46 UTC, huan commented
@lijiarui It's a great introduction to Juzi.BOT! It will be great if you can add the above content to https://pre-angel.com/portfolios/juzibot/ for the English version.

2021-05-26 09:58 UTC, chris-4444 requested changes
For checking.

2021-05-26 10:06 UTC, chris-4444 requested changes
updated.

2021-05-30 06:17 UTC, proudofsimin approved these changes
Well done!

2021-06-01 05:27 UTC, Rohitesh-Kumar-Jain approved these changes
ping @huan

2021-07-10 10:20 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-10 12:46 UTC, chris-4444 requested changes
@Rohitesh-Kumar-Jain @huan Changed is to seems to be, regarding the nation's internet.

2021-07-12 13:17 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-14 06:45 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 21:36 UTC, lijiarui requested changes

2021-07-18 21:36 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I think we should change this image here, because this logo has appear too much in the docs, we should change a more related image to this doc

2021-07-19 18:37 UTC, nibble0101 commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I have decided to remove. Like you said, looks like it serves no purpose there and we can't come up with another image to take its place.

2021-07-29 14:50 UTC, lijiarui requested changes

2021-07-29 14:50 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Thus, Huan decided to build Wechaty and landed its first set of [clients](https://github.com/nibble0101/wechaty-documentation-draft/blob/main/01-introduction/04-who-is-using-wechaty.md) in 2017. Wech
This link is a dead link here. And we should always use wechaty official repo in the docs.

2021-07-29 14:50 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Thus, Huan decided to build Wechaty and landed its first set of [clients](https://github.com/nibble0101/wechaty-documentation-draft/blob/main/01-introduction/04-who-is-using-wechaty.md) in 2017. Wech
`. Wechaty's chatbot can also function as a **_customer management tool_** that helps companies deal with some business challenges such as acquiring, engaging, and retaining customers. Wechaty is built as the _tireless bot_ that can work 24/7, can filter the most important messages, can highlight discussions that contain the **keywords** that users would want to search and follow, and can monitor chatbot and user actions seamlessly.` This is my company [JuziBot](www.juzibot.com) business.

Maybe you can change this to:

After that, Wechaty Co-creator Rui Li found this can help companies to build relationships with their customers. Then she created [JuziBot](www.juzibot.com), using Wechaty function as a **_customer management tool_** that helps companies deal with some business challenges such as acquiring, engaging, and retaining customers. Wechaty is built as the _tireless bot_ that can work 24/7, can filter the most important messages, can highlight discussions that contain the **keywords** that users would want to search and follow, and can monitor chatbot and user actions seamlessly.

2021-07-29 14:52 UTC, lijiarui commented
And I suggest adding some of the information https://github.com/wechaty/wechaty.js.org/pull/873#issuecomment-846589160 I wrote in the blog.

2021-08-03 07:42 UTC, nibble0101 commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Thus, Huan decided to build Wechaty and landed its first set of [clients](https://github.com/nibble0101/wechaty-documentation-draft/blob/main/01-introduction/04-who-is-using-wechaty.md) in 2017. Wech
Added suggested text.

2021-08-23 15:40 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Thus, Huan decided to build Wechaty and landed its first set of [clients](https://github.com/nibble0101/wechaty-documentation-draft/blob/main/01-introduction/04-who-is-using-wechaty.md) in 2017. Wech
It seems you didn't add as I suggest...

2021-08-23 16:12 UTC, lijiarui requested changes

2021-08-23 16:12 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Thus, Huan decided to build Wechaty and landed its first set of clients in 2017. After that, Wechaty Co-creator [Rui Li](https://github.com/lijiarui) found that Wechaty can help companies build relat
2017 --> 2016

2021-08-24 07:43 UTC, chris-4444 approved these changes
replaced 2017 with 2016.

2021-08-24 08:31 UTC, Rohitesh-Kumar-Jain approved these changes

2021-08-24 08:31 UTC, Rohitesh-Kumar-Jain commented
Pls resolve merge conflicts as well, so that we can proceed towards the merge

2021-09-03 09:54 UTC, nibble0101 commented
> Pls resolve merge conflicts as well, so that we can proceed towards the merge

Hi @Rohitesh-Kumar-Jain.  The merge conflicts have been fixed. Is there anything else?

2021-09-03 13:25 UTC, Rohitesh-Kumar-Jain commented
> > Pls resolve merge conflicts as well, so that we can proceed towards the merge
> 
> Hi @Rohitesh-Kumar-Jain. The merge conflicts have been fixed. Is there anything else?

No, you implemented the requested changes, so I think I am just waiting for @lijiarui approval for the merge

2021-09-07 17:24 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-07 17:51 UTC, lijiarui requested changes

2021-09-07 17:51 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Wechaty helps users implement their chatbots with straightforward business logic without the complexities of chatbot programming. As a developer, you will be able to create a chatbot that can run on
Wechat --> WeChat

2021-09-07 17:51 UTC, lijiarui commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Back in 2014, Wechaty creator [Huan Li](https://github.com/huan)'s daily life depended too much on Wechat, which was dubbed as China's famous messaging app that is capable of payment processing and o
Wechat --> WeChat

2021-09-07 18:47 UTC, nibble0101 commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Wechaty helps users implement their chatbots with straightforward business logic without the complexities of chatbot programming. As a developer, you will be able to create a chatbot that can run on
Changed

2021-09-07 18:47 UTC, nibble0101 commented on docusaurus/docs/what-can-you-do-with-wechaty.md
> +Back in 2014, Wechaty creator [Huan Li](https://github.com/huan)'s daily life depended too much on Wechat, which was dubbed as China's famous messaging app that is capable of payment processing and o
Changed

2021-09-09 03:17 UTC, lijiarui approved these changes

2021-09-09 05:20 UTC, merged