[Week 1][How to Guide] Updated readme for How to Guide
wechaty/docusaurus pull request #876
Opened 2021-05-20 09:42 UTC by vasvi-sood

### Week 1
- [x] Get familiar with the project
- [x] Finalized and submitted the team project proposal 
- [x] Removed the About bot section and added Deploy with Heroku & Deploy with Docker in How-to Guide
- [x] Add a README file to GitHub to help future contributors understand how to contribute to the How-to-guide page

![Screenshot from 2021-05-22 19-50-21](https://user-images.githubusercontent.com/69477761/119229784-20092e00-bb37-11eb-8b94-bfc85fe68c41.png)
![Screenshot from 2021-05-22 19-50-27](https://user-images.githubusercontent.com/69477761/119229785-213a5b00-bb37-11eb-9c04-03f9af4a98ee.png)
![Screenshot from 2021-05-22 19-50-34](https://user-images.githubusercontent.com/69477761/119229786-226b8800-bb37-11eb-8289-cf24cc10a566.png)
![Screenshot from 2021-05-22 19-50-40](https://user-images.githubusercontent.com/69477761/119229787-239cb500-bb37-11eb-8a0f-8ca333d9d3a9.png)
![Screenshot from 2021-05-22 19-50-48](https://user-images.githubusercontent.com/69477761/119229789-24cde200-bb37-11eb-99ba-5989a658813a.png)

2021-05-21 09:22 UTC, nibble0101 approved these changes
Thanks for adding this @vasvi-sood. This is very useful information.

2021-05-22 11:43 UTC, proudofsimin commented
Hi Vasvi, thank you for your effort! Can you change the bulleted points into numbers, since they are sequential lists. Thank you.

2021-05-22 15:14 UTC, Rohitesh-Kumar-Jain commented
> ![Screenshot from 2021-05-22 19-50-48](https://user-images.githubusercontent.com/69477761/119229789-24cde200-bb37-11eb-99ba-5989a658813a.png)


Thanks for adding screenshots in the description, it's good to add individual screenshots when you are modifying some part of the documentation, but if you are writing the documentation from scratch or modifying > 75% of the documentation I will prefer one single full-page screenshot. 

Another thing I feel is, we probably don't need too many images in the readme. I feel that images associated with git commit, and push are redundant, they probably won't help the reader much. What do you suggest @proudofsimin ? I will go with her views, as she is the one spearheading documentation style and structure : )

2021-05-23 06:07 UTC, vasvi-sood commented
> Hi Vasvi, thank you for your effort! Can you change the bulleted points into numbers, since they are sequential lists. Thank you.

@proudofsimin  Done

2021-05-23 06:23 UTC, proudofsimin commented
> ### Week 1
> * [x]  Get familiar with the project
> * [x]  Finalized and submitted the team project proposal
> * [x]  Removed the About bot section and added Deploy with Heroku & Deploy with Docker in How-to Guide
> * [x]  Add a README file to GitHub to help future contributors understand how to contribute to the How-to-guide page
> 
> ![Screenshot from 2021-05-22 19-50-21](https://user-images.githubusercontent.com/69477761/119229784-20092e00-bb37-11eb-8b94-bfc85fe68c41.png)
> ![Screenshot from 2021-05-22 19-50-27](https://user-images.githubusercontent.com/69477761/119229785-213a5b00-bb37-11eb-9c04-03f9af4a98ee.png)
> ![Screenshot from 2021-05-22 19-50-34](https://user-images.githubusercontent.com/69477761/119229786-226b8800-bb37-11eb-8289-cf24cc10a566.png)
> ![Screenshot from 2021-05-22 19-50-40](https://user-images.githubusercontent.com/69477761/119229787-239cb500-bb37-11eb-8a0f-8ca333d9d3a9.png)
> ![Screenshot from 2021-05-22 19-50-48](https://user-images.githubusercontent.com/69477761/119229789-24cde200-bb37-11eb-99ba-5989a658813a.png)

2021-05-23 07:25 UTC, huan requested changes
Thank you for the great improvement!

I have the following review comments:

1. The index file of the folder should be **overview.mdx** instead of ~~README.md~~ (just like all other folders under the docs/)
2. All images in the docs page should be put under a folder with the same name of the docs page. For example:
    -  If we have a docs page at `docs/howto/overview.mdx`
    - Then the image should be put under the folder `static/img/docs/howto/overview/`
3. Please keep all file names to be lowercase

2021-05-25 08:28 UTC, proudofsimin requested changes
It's great you changed the first part, but the second part is also a sequential list. Please change it as well. Thank you.

2021-05-25 08:28 UTC, proudofsimin commented on README.md
>  - Create new Pull Request
Please change this part to numbered list as well. Thank you :)

2021-05-25 13:59 UTC, Rohitesh-Kumar-Jain commented on README.md
>  - Create new Pull Request
Yeah numbered list will be better

2021-05-25 14:50 UTC, abhishek-iiit commented
Thank you @huan for your feedback,

For clear understanding, We do have both the part for our how-to guide section
1. For the index file, we do have the overview.mdx file that can be viewed on the website where we will have the short link to all the sections under how-to-guide.
2. For the readme.md that can be viewed from GitHub, we were planned to add how to contribute and run it locally to this file.

and we will surely be taking care of the format and the files that are to be kept under different sections.

2021-05-27 06:37 UTC, abhishek-iiit commented
I request @huan, @Rohitesh-Kumar-Jain & @proudofsimin to please have a look at the changes. and give us the feedback for the same :)

2021-05-27 09:06 UTC, vasvi-sood commented
@proudofsimin  @Rohitesh-Kumar-Jain all changes have been made. Kindly review the pull request and merge it.

2021-06-01 05:29 UTC, Rohitesh-Kumar-Jain approved these changes
Looks good for now, we will have a final review towards the end.
For now, I believe the PR is ready to get merged, well done.

2021-06-02 14:00 UTC, proudofsimin approved these changes

2021-06-14 11:16 UTC, Rohitesh-Kumar-Jain commented
this PR is the root cause of all the evil 🤦🏼 

I realized now that this PR is being pushed directly from the master branch of vavsi-sood. (This doesn't cause a problem if you are working on a solo project).

This is the PR from all the refactoring should start : )

Surprisingly I ignored it the first time I reviewed this, and @proudofsimin and @nibble0101 also approved this 😅 

I am not a git expert but that's what I believe is happening here.

So in short you need to close all the 4 PRs you have raised in the GSoD so far. 

You don't need to close them yourself actually, the below manoeuvre will automatically close PRs and reset everything.

## fix your current master branch

First of all, check out to your master branch, and then checkout to a new PR branch based on that.

```
git switch master
git switch -c new-branch
```

Then push the new branch to your fork and create a new PR based on that branch (the PR will be identical to this one with the exception of the branch). When you've done that, we can reset your master branch.

```
git switch master
git fetch upstream master # fetch upstream/master without merging into local master
git reset --hard upstream/master # reset local master to upstream/master's state
git push --force origin master # force-update your fork's master to reflect upstream
```

I hope I am doing right @huan and not being harsh on the How-to-guides team ?

2021-06-14 13:53 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit start from this PR, first make sure that your master branch is even with the upstream master. 

Remember this rule: `Your local master should be never ahead of upstream` your other branches can be ahead of upstream master.

2021-06-14 19:11 UTC, vasvi-sood commented
We will surely make the necesaary changes. And submit the work again in the next 2-3 days.

2021-07-04 05:34 UTC, closed without merging