fix search
wechaty/docusaurus pull request #877
Opened 2021-05-20 15:25 UTC by l3ob

fix https://github.com/wechaty/wechaty.js.org/issues/666

2021-05-20 15:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=877) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/wechaty.js.org?pullRequest=877) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/wechaty.js.org?pullRequest=877) it.</sub>

2021-05-20 15:37 UTC, l3ob commented
# 0x00
search result of jekyll posts cannot route correctly in docusaurus project
so change history.push(URL) to location.href=URL

script to copy docusaurus theme:
```
npx docusaurus swizzle @docusaurus/theme-search-algolia SearchBar --danger
```

# 0x01
remove some params to show all results

script to copy docusaurus theme:
```
npx docusaurus swizzle @docusaurus/theme-search-algolia SearchPage --danger
```

2021-05-23 16:39 UTC, huan requested changes
It's great to see this PR for fixing the search function of our site!

Could you please sign the CLA first, so that we can be able to merge this PR?

And also, I'd like to know what exactly diff did you make for this modification? Could you please submit a diff/patch so that we can better understand this problem, and be able to review it later?

Thank you very much!

2021-05-25 13:51 UTC, l3ob commented
@huan the CLA is signed, but I don't know why the status not changed yet.

![image](https://user-images.githubusercontent.com/3064691/119509283-1683fe00-bda3-11eb-9480-9f8adb140ed0.png)

2021-05-25 14:50 UTC, l3ob commented
> It's great to see this PR for fixing the search function of our site!
> 
> Could you please sign the CLA first, so that we can be able to merge this PR?
> 
> And also, I'd like to know what exactly diff did you make for this modification? Could you please submit a diff/patch so that we can better understand this problem, and be able to review it later?
> 
> Thank you very much!

https://github.com/l3ob/wechaty.js.org/commit/cbb6ef222fee818e3ff0d0ac9c9f4bfb8dd41b07

I start a branch here to better explain the change.

First, jekyll posts are not belongs to docusaurus project, so the default method using docusaurus router cannot find the posts. Redirect search result with href instead of router/push fix the problem.

Follow docusaurus docs to copy and edit the component:
https://docusaurus.io/docs/search#editing-the-algolia-search-component

Second, the search page show no results. I try to modify the algolia http request and removing facetFilters params could do the trick. Guess it's something with the algolia configuration. For now we can just comment the lines.

2021-05-26 12:07 UTC, huan commented
> @huan the CLA is signed, but I don't know why the status not changed yet.

According to the comment replied by the CLA bot, i3ob is OK but there have commits made by ❌ coderprepares.

2021-05-26 15:41 UTC, l3ob commented
> > @huan the CLA is signed, but I don't know why the status not changed yet.
> 
> According to the comment replied by the CLA bot, i3ob is OK but there have commits made by ❌ coderprepares.
> 
> You can pass the CLA check either by removing the commits from coderprepares or signing the CLA with coderprepares.

It's my another account. CLA sign is done. What else can I do?

2021-05-28 01:56 UTC, l3ob commented on docusaurus/src/theme/SearchBar/index.js
> +  return <Link href={hit.url}>{children}</Link>;
change `<Link to={hit.url}>` to `<Link href={hit.url}>`

2021-05-28 01:58 UTC, l3ob commented on docusaurus/src/theme/SearchBar/index.js
> +      location.href = itemUrl;
change `history.push(itemUrl);` to `location.href = itemUrl;`

2021-05-28 02:01 UTC, l3ob commented on docusaurus/src/theme/SearchPage/index.js
> +
remove certain search params

2021-05-28 02:02 UTC, l3ob commented on docusaurus/src/theme/SearchPage/index.js
> +    // );
remove certain search params

2021-05-28 02:18 UTC, closed without merging

2021-08-24 04:41 UTC, huan commented
Merge to #902