Updated the API overview.mdx
wechaty/docusaurus pull request #881
Opened 2021-05-22 12:19 UTC by shraddhavp

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-05-22 13:45 UTC, proudofsimin requested changes
Hi, I left some comments, please take a look and let me know if you have any question.
Besides, I don't understand why you are separate each topic to a level three heading and a bulleted point. Are you going to add some description later? If not, maybe we could combine them into one bulleted list together. 
- Typedefs
- Starting the bot
- Stopping the bot or logging off
- ...

2021-05-22 13:45 UTC, proudofsimin commented on docusaurus/docs/api/overview.mdx
> +This section will give you a complete detail of the role of the API,its interfacces,user classes and all other  high level features that Wechaty offers you.
I understand that you are trying speak in a friendly tone, but we should still keep it formal as the documentation represents Wechaty team. I feel like we could remove the word *for you* and the exclamation marks, so that the passage would not sound so conversational. See [Voice and tone](https://developers.google.com/style/tone) and [Exclamation points](https://developers.google.com/style/exclamation-points).

2021-05-22 13:45 UTC, proudofsimin commented on docusaurus/docs/api/overview.mdx
> +### Wechaty Class
Like I mentioned in the previous PR, please capitalize only the first letter of the heading. See [Capitalization](https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings).

2021-05-22 13:45 UTC, proudofsimin commented on docusaurus/docs/api/overview.mdx
> +### Wechaty Event Functions
changes to *Wechaty event functions*

2021-05-22 14:28 UTC, shraddhavp commented
ok Thanks @proudofsimin  will check it out

2021-05-22 16:36 UTC, iamrajiv requested changes

2021-05-22 16:36 UTC, iamrajiv commented on docusaurus/docs/api/overview.mdx
> +This section will give you a complete detail of the role of the API,its interfacces,user classes and all other  high level features that Wechaty offers you.
```suggestion
Wechaty defines a set of easy-to-use classes for you to implement your bot with ease.
Wechaty has a tiny API surface that makes it easier for you to implement the API to your bot. 
This section will give you complete detail of the role of the API, its interfaces, user classes, and all other high-level features that Wechaty offers you.
```

2021-05-23 07:41 UTC, huan requested changes
Thanks to @shraddhavp for the improvements!

Please follow the review from @proudofsimin so that this PR can meet our documentation styles.

2021-06-04 15:16 UTC, proudofsimin commented
Hi @shraddhavp,
Are you still taking care of this PR?

2021-06-04 16:00 UTC, shraddhavp commented
@proudofsimin  I am closing it

2021-06-05 04:45 UTC, closed without merging