Improve and update Vorpal bot steps
wechaty/docusaurus pull request #882
Opened 2021-05-22 14:35 UTC by sbis04

I have updated the [Using Vorpal with Wechaty](https://wechaty.js.org/docs/tutorials/using-vorpal-with-wechaty) page to add some better steps in the **Building the bot > Writing code for bot** section so that users can get a better understanding of the code. And, have also made some other small improvements.

2021-05-23 08:59 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +After scanning the generated QR code with the help of your app, the bot will start running on your device. Now, as it finds the specified commands inside the chat it will respond automatically to it.
seems good to me

2021-05-23 08:59 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +You have learnt to use Vorpal with Wechaty and built a Hacker News bot from scratch. Vorpal has a lot of extensions, you can find some of them [here](https://github.com/wechaty/wechaty-vorpal-contrib
not sure "from scratch" was required here, should we keep this?

2021-05-23 09:20 UTC, sbis04 commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +You have learnt to use Vorpal with Wechaty and built a Hacker News bot from scratch. Vorpal has a lot of extensions, you can find some of them [here](https://github.com/wechaty/wechaty-vorpal-contrib
Even I was not sure about it, I think we should remove it again.

2021-05-24 08:12 UTC, shwetalsoni approved these changes

2021-05-24 09:26 UTC, sbis04 commented
Tag: #891

2021-05-26 17:12 UTC, proudofsimin requested changes
Will we change the other part in the future? I'm actually hoping to add some sentences explaining what a Vorpal is.

2021-05-26 17:12 UTC, proudofsimin commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +Now, you have to define some functions that will help you to handle the different events returned by the Wechaty bot.
Do the functions mentioned below are only examples? I guess adding a note to tell our users that these are only examples, and provide a link to where they can find other functions would be helpful.

> Note:

2021-05-26 17:12 UTC, proudofsimin commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
How do you think if we add the functions to a bulleted list. Is it clearer? I feel like a bulleted list could separate functions and instructions. Otherwise instructions after function *onError* all seem like under it. Like

Now, you have to define some functions....
+ onScan
   Function used for generating...
   1.
   2.
+ onLogin
+ ...

You have completed defining...

2021-05-26 17:12 UTC, proudofsimin commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +You have completed defining all the functions required for handling various bot events. Now, initialize the Wechaty bot by providing a name:
Active voice is more favored. See [Active voice](https://developers.google.com/style/voice).

-> You have completed defining all the functions required for handling various bot events. Now, provide a name to initialize the Wechaty bot:

2021-05-27 02:49 UTC, sbis04 commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +Now, you have to define some functions that will help you to handle the different events returned by the Wechaty bot.
They are just self-defined functions for handling various bot actions which users can modify as they wish, that's why in the `onScan ` function section I have added points to describe the content of that function. And, the remaining functions contain just one line print statements.

2021-05-27 02:50 UTC, sbis04 commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
I have added the functions as bullets in the latest commit.

2021-05-27 02:51 UTC, sbis04 commented on docusaurus/docs/tutorials/using-vorpal-with-wechaty.md
> +You have completed defining all the functions required for handling various bot events. Now, initialize the Wechaty bot by providing a name:
I have changed it to _active voice_ in the latest commit.

2021-05-27 02:52 UTC, sbis04 commented
@proudofsimin I have added some information about Vorpal and improved the introduction of this tutorial page.

2021-06-01 05:23 UTC, Rohitesh-Kumar-Jain approved these changes
Looks good for now, we will have a final review of docs towards the end of the project.
For now, I feel it's probably ready to get merged.

ping @huan

2021-06-02 14:05 UTC, proudofsimin approved these changes
Great! Thank you!

2021-07-06 15:43 UTC, lijiarui requested changes
https://github.com/wechaty/wechaty.js.org/pull/882/files#diff-303abb05f025331bce4d51a11e7a6a4830b8fd26dac44d8cf197d2bc138418f7R84

We should not use any third-party repo in the tutorial. I thinks using https://github.com/wechaty/wechaty-vorpal-contrib is better.

2021-07-06 17:37 UTC, sbis04 commented
@lijiarui I have updated the GitHub repo links with the official [Wechaty Vorpal Contrib repo](https://github.com/wechaty/wechaty-vorpal-contrib).

2021-07-06 20:18 UTC, lijiarui requested changes
It seems to have some error in codesandbox, when I preview, it got the following error.

![image](https://user-images.githubusercontent.com/6419514/124661646-5a0d7400-deda-11eb-96c2-f2668ede4380.png)

2021-07-07 04:57 UTC, sbis04 commented
@lijiarui I tried out by running on localhost, for me it works fine:

![Screenshot 2021-07-07 at 10 22 46 AM](https://user-images.githubusercontent.com/43280874/124702168-93130c00-df0d-11eb-9061-6724e86f5153.png)

Can you please once try visiting [this link](https://codesandbox.io/embed/github/sbis04/vorpal-wechaty-hackernews/tree/main/?fontsize=12&hidenavigation=1&module=%2Fvorpal-bot.ts&theme=dark) if it is working here because this is the exactly CodeSandbox that I have embedded in the docs?

2021-07-07 18:13 UTC, lijiarui commented
> @lijiarui I tried out by running on localhost, for me it works fine:
> 
> ![Screenshot 2021-07-07 at 10 22 46 AM](https://user-images.githubusercontent.com/43280874/124702168-93130c00-df0d-11eb-9061-6724e86f5153.png)
> 
> Can you please once try visiting [this link](https://codesandbox.io/embed/github/sbis04/vorpal-wechaty-hackernews/tree/main/?fontsize=12&hidenavigation=1&module=%2Fvorpal-bot.ts&theme=dark) if it is working here because this is the exactly CodeSandbox that I have embedded in the docs?

Now it can works, although it still has some error, I think this is related to wechat4u, so I would ignore this.

![image](https://user-images.githubusercontent.com/6419514/124808885-15ddaa80-df92-11eb-9824-2c042dde521d.png)

2021-07-07 18:26 UTC, lijiarui commented
I think for this vorpal part, we still have 3 part need improvement, despite they already merged by @huan before:

### 1. We should use a tab to change Linux/Mac/Windows running the command

I wrote them in [PR 963](https://github.com/wechaty/wechaty.js.org/pull/963#discussion_r664773898)  and the issue is the same as this one.

### 2. We should use npm install instead of add package name in `package.json`

I wrote them in [PR 888](https://github.com/wechaty/wechaty.js.org/pull/888#discussion_r664740760)

###3. I don't think we should define scrips in this part because these scrips have no relation to vorpal plugin
![image](https://user-images.githubusercontent.com/6419514/124810361-ce581e00-df93-11eb-8e25-c70c1d56a65d.png)

2021-07-08 12:21 UTC, huan approved these changes

2021-07-08 16:08 UTC, sbis04 commented
@lijiarui I have made the required changes.

Btw, some of the previous CI builds of the merged commits have not passed, that's why this one is also failing.

2021-07-08 18:15 UTC, lijiarui approved these changes
LGTM!

2021-07-08 18:34 UTC, lijiarui commented
@sbis04 It seems have some sidebar issue for vorpal, pls make github action green.

2021-07-08 19:06 UTC, sbis04 commented
@lijiarui Have made the CI green.

2021-07-10 07:09 UTC, merged

2021-07-10 07:09 UTC, lijiarui commented
Good job！