Running locally (Ding Dong bot)
wechaty/docusaurus pull request #888
Opened 2021-05-23 17:23 UTC by shwetalsoni

* Improved tutorial for running ding dong bot locally
* code sandbox to be added

2021-05-24 17:36 UTC, shwetalsoni commented
Tag: #891

2021-05-25 14:01 UTC, Rohitesh-Kumar-Jain commented
Is the PR ready to be reviewd? You requested Review, but I believe you are still pushing new commits to the PR

2021-05-25 14:05 UTC, shwetalsoni commented
Now its done. You can review it now.

On Tue, 25 May 2021, 7:31 pm Rohitesh Kumar Jain, ***@***.***>
wrote:

> Is the PR ready to be reviewd? You requested Review, but I believe you are
> still pushing new commits to the PR
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/888#issuecomment-847896408>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANUJ3INXA6AXGKQZ35NKI3LTPOUUZANCNFSM45L44ORQ>
> .
>

2021-05-25 14:19 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/getting-started/hard-way.mdx
> +Just scan the generated QR code with Wechat/WhatsApp app and you are ready to go.
I am sure that you were able to run the Ding Dong bot yourself. 
But just to double-check I would like to ask have you successfully run this bot yourself ? 

I tried running this a week ago (without this documentation and I generated the QR code, but nothing happened on scanning it because I was probably doing something wrong.

2021-05-25 14:36 UTC, shwetalsoni commented
I don't know what error you are facing but i have tried it before also and
it worked well.

Well you can try it now, souvik has also checked it and it was working fine.

On Tue, 25 May 2021, 7:50 pm Rohitesh Kumar Jain, ***@***.***>
wrote:

> *@Rohitesh-Kumar-Jain* commented on this pull request.
> ------------------------------
>
> In docusaurus/docs/getting-started/hard-way.mdx
> <https://github.com/wechaty/wechaty.js.org/pull/888#discussion_r638834220>
> :
>
> >
> -<ShortestChatbots />
> +## Try out the bot
> +
> +You can try out Ding Dong Bot using this interactive CodeSandbox.
> +
> +Just scan the generated QR code with Wechat/WhatsApp app and you are ready to go.
>
> I am sure that you were able to run the Ding Dong bot yourself.
> But just to double-check I would like to ask have you successfully run
> this bot yourself ?
>
> I tried running this a week ago (without this documentation and I
> generated the QR code, but nothing happened on scanning it because I was
> probably doing something wrong.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/888#pullrequestreview-667891490>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANUJ3IICBT4T6FQCOXCTYNTTPOWZTANCNFSM45L44ORQ>
> .
>

2021-05-27 17:20 UTC, proudofsimin commented
I'm actually thinking if we should use the purpose for the *function as title instead of the function name. Because for the users when they are coding, they will look for what they need first, and then search for the function name. It is how human brains are processed. Since this is tutorial, telling them what they will learn is more efficient as function name itself is sometimes not self-explanatory. Function name as title is more like a library thing.

ex. 
#### Generate QR code for puppet specified

Add `onScan` to .......

But here it is in a very awkward position. How do you think is better? Thanks for raising this question. I also need to check more about how others document it.

2021-05-28 06:03 UTC, shwetalsoni commented
> I'm actually thinking if we should use the purpose for the _function_ as title instead of the function name. Because for the users when they are coding, they will look for what they need first, and then search for the function name. It is how human brains are processed. Since this is tutorial, telling them what they will learn is more efficient as function name itself is sometimes not self-explanatory. Function name as title is more like a library thing.
> 
> ex.
> 
> #### Generate QR code for puppet specified
> Add `onScan` to .......
> 
> But here it is in a very awkward position. How do you think is better? Thanks for raising this question. I also need to check more about how others document it.

Before starting with building the bot , I have added the purpose saying..

> Now we will write some functions which will be required for handling different events returned by bot.

Then starts different functions like `**onScan**`

And before writing the code for every function I have also specified what that function does in short. 

> This function will be required for generating QR code for puppet specified and Displays it on console.`

And after the code snippet, I have explained every function in detail like for `onScan` function.

![Screenshot from 2021-05-25 12-34-26](https://user-images.githubusercontent.com/57187745/119454059-b87cf980-bd55-11eb-8a1e-e4e652c60075.png)

2021-05-28 16:10 UTC, proudofsimin commented
Hi @shwetalsoni,
I'm sorry I didn't see the beginning. And thanks for checking the django documentation! I'm really happy to see that you are very organized when documenting.
One more reminder, I saw the word "we" in the quoted sentence. Please change it according to [Second person and first person](https://developers.google.com/style/person). Thank you. (but I guess this is out of scope for this PR, you could change it next time you correct the other part)

2021-05-28 16:12 UTC, proudofsimin approved these changes

2021-05-28 16:14 UTC, shwetalsoni commented
> Hi @shwetalsoni,
> I'm sorry I didn't see the beginning. And thanks for checking the django documentation! I'm really happy to see that you are very organized when documenting.
> One more reminder, I saw the word "we" in the quoted sentence. Please change it according to [Second person and first person](https://developers.google.com/style/person). Thank you. (but I guess this is out of scope for this PR, you could change it next time you correct the other part)

Sure, I'll do it :)

2021-05-28 17:47 UTC, sbis04 approved these changes

2021-06-01 05:30 UTC, Rohitesh-Kumar-Jain approved these changes
ping @huan

2021-06-09 15:12 UTC, lijiarui requested changes
I think it looks a little bit complex for just getting started. Maybe we can delete the part unrelated with wechaty.

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +2. Clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository
Please change this to http://github.com/wechaty/wechaty-getting-started

We should never use a third party repo in the docs.

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +with Wechat/WhatsApp app
It looks a little bit strange here when adding with  WeChat/WhatApp app

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +You can clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository by following the below command, and navigate to the directory:
Please use wechaty official repo

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +git clone https://github.com/shwetalsoni/ding-dong-bot
Please use wechaty official repo

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +* [wechaty-plugin-contrib](https://www.npmjs.com/package/wechaty-plugin-contrib): JavaScript function that returns a function which accepts a Wechaty instance
I don't think run a basic dingdong bot needs wechaty-plugin-contrib.

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +```
It seems installing too many puppet dependencies here. I suggest we delete them, because if you run a dingdong bot it doesn't need all puppet at the same time.

2021-06-09 15:12 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +### 4. Configure TypeScript
Why should we configure typescript if the developer just wants to run a ding dong bot...

Maybe this is unrelated to wechaty..

2021-06-09 15:46 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +### 4. Configure TypeScript
Configure typescript is under **Building the bot**, which allows the user to build the bot from scratch after he has got an idea of running it by cloning the getting-started repo and it requires configuring typescript.

2021-06-09 15:48 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +```
I think it's better if we install all the puppets so that the user can use any.

2021-06-09 16:22 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +2. Clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository
Fixed

2021-06-09 16:22 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +with Wechat/WhatsApp app
Fixed

2021-06-09 16:23 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +You can clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository by following the below command, and navigate to the directory:
Fixed

2021-06-09 16:23 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +git clone https://github.com/shwetalsoni/ding-dong-bot
Fixed

2021-06-09 16:23 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +* [wechaty-plugin-contrib](https://www.npmjs.com/package/wechaty-plugin-contrib): JavaScript function that returns a function which accepts a Wechaty instance
Removed `wechaty-plugin-contrib`

2021-07-06 17:08 UTC, lijiarui requested changes
After I running this locally, here is the suggestion:

### 1. change the file name

If our title is `Running locally`,how about we change the title to `getting-started/running-locally.mdx`

### 2. Fix CodeSandbox error

![image](https://user-images.githubusercontent.com/6419514/124640605-376e6180-dec0-11eb-8981-e94c342ad405.png)

I run this locally and found error here, I think you should fix this error fist.

2021-07-06 17:28 UTC, lijiarui requested changes
Please change as I request.

2021-07-06 17:28 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +}
We should change adding dependencies way from adding to package.json to using `npm install`

maybe change something like this:

```shell
npm install wechaty
```

If you want to show qr-code at the terminal, you can add this:

```shell
npm install qrcode- terminal
```

We may not use `dotenv` here because this is not the requisite package when using wechaty

2021-07-06 17:28 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +```
We should change adding dependencies way from adding to package.json to using npm install

may change something like this:

You can install wechaty-puppet as you like when using wechaty:
1. If young want to use whatsapp,you can install wechaty-puppet-whatsapp
```shell
npm install wechaty-puppet-whatsapp
```

2. If you want to use wechat, you can install wechaty-puppet-wechat
```shell
npm install wechaty-puppet-wechat
```

3. If you want to use wecom, you can install wechaty-puppet-wxwork
```shell
npm install wechaty-puppet-wxwork
```

You can find more puppet information here: https://wechaty.js.org/docs/puppet-providers/

2021-07-06 17:28 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +    "wechaty-puppet-whatsapp": "0.2.3"
We can delete this pakcage.json part, since it is not necessary for users.

2021-07-06 17:28 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +```
Reomve `npm install` here, because we already use npm install XXX before

2021-07-06 17:28 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +You have to define the script for running the bot. Add the following to your `package.json` file:
This is an enhancement feature, I'd rather to remove this from the tutorial. If you strongly want to add it here, maybe you can tell the reader about this.

We can change this something like this:

If you want to run it more conveniently, you can add some script in package.json.

2021-07-06 17:36 UTC, lijiarui commented
I think you can refer to this PR when telling people how to use wechaty: https://github.com/wechaty/wechaty.js.org/pull/905

2021-07-07 11:37 UTC, shwetalsoni commented
@lijiarui I have applied all the requested changes except the code sandbox. I have attached screenshots for clearance. 
@sbis04 Can you please help me with code sandbox error. I tried but couldn't fix it.

2021-07-07 11:37 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +You have to define the script for running the bot. Add the following to your `package.json` file:
fixed

2021-07-07 11:38 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +```
removed

2021-07-07 11:38 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +    "wechaty-puppet-whatsapp": "0.2.3"
deleted `package.json`

2021-07-07 16:21 UTC, lijiarui requested changes
Good job! 

One more tips to fix.

2021-07-07 16:21 UTC, lijiarui commented on docusaurus/docs/getting-started/running-locally.mdx
> +```
Please remove npm install npx here, because node has npx itself.

2021-07-07 16:23 UTC, lijiarui commented
> @lijiarui I have applied all the requested changes except the code sandbox. I have attached screenshots for clearance.
> @sbis04 Can you please help me with code sandbox error. I tried but couldn't fix it.

@sbis04 you can click here: https://codesandbox.io/s/github/wechaty/wechaty-getting-started/tree/master/examples/third-parties/codesandbox?hidenavigation=1&module=%2Fding-dong-bot.ts&theme=dark and will found error as well. Pls help @shwetalsoni fix this.

2021-07-07 16:34 UTC, shwetalsoni commented
@lijiarui I have applied the above requested change.

2021-07-07 18:34 UTC, lijiarui commented
Good job, I think you can file a new issue about the sandbox problem, and I will approve this PR.

2021-07-07 18:34 UTC, lijiarui approved these changes

2021-07-07 18:36 UTC, shwetalsoni commented
> Good job, I think you can file a new issue about the sandbox problem, and I will approve this PR.

Do you mean to create an issue under `Issues`?

2021-07-08 08:24 UTC, shwetalsoni commented
@lijiarui I have created issue #1032 for keeping the record of all the features that need to be added later mentioning all the respective PR's.

2021-07-08 12:22 UTC, huan approved these changes

2021-07-08 15:10 UTC, merged