Getting started overview
wechaty/docusaurus pull request #897
Opened 2021-05-26 06:37 UTC by shwetalsoni

## Updated the getting started overview

![Screenshot from 2021-05-26 12-00-02](https://user-images.githubusercontent.com/57187745/119613540-d19bae00-be1a-11eb-98ba-ec3ce59ab4c2.png)

2021-05-27 03:11 UTC, sbis04 commented
Tag: #891

2021-05-29 10:45 UTC, proudofsimin commented
Hi I don't quite understand, I saw you only screenshot a small part of it but in *Files change* I saw many places updated. Can you tell us what they are and where should we review? Thank you.

2021-05-29 10:53 UTC, shwetalsoni commented
> Hi I don't quite understand, I saw you only screenshot a small part of it but in _Files change_ I saw many places updated. Can you tell us what they are and where should we review? Thank you.

Hii @proudofsimin for this PR only overview.mdx is required to be reviewed.

2021-05-29 16:26 UTC, proudofsimin commented
Hi @shwetalsoni,
How do you think if we modify the passage to something like this:
(I still feel it's a bit jumping between the first and second sentences, but I haven't thought of a better way to connect them.)


If you are a total beginner to Wechaty, start from this section.

You can run Wechaty on the following platforms:

- Cloud IDE
- Gitpod
- Local machine

Wechaty is a powerful software (maybe *software* is not the best word here). You will learn the following fundamental features of Wechaty in the getting-started tutorials:

- Turn your WeChat/ WhatsApp account to a chatbot with few lines of code.
- Communicate with your users for you through Wechaty Conversational RPA technology.
- Work out of the box on Line, Mac, and Windows.
- Support all puppets like Web, Pad, Windows, and Mac.
- Reply with a dong message when you receive a ding message.

2021-06-01 04:27 UTC, sbis04 approved these changes

2021-06-01 05:45 UTC, Rohitesh-Kumar-Jain reviewed
pls, first address @proudofsimin's so that we can continue reviewing this PR : )

2021-06-03 09:45 UTC, Rohitesh-Kumar-Jain commented
> pls, first address @proudofsimin's so that we can continue reviewing this PR : )
> 
> @Rohitesh-Kumar-Jain , I would do the rest of changes with a new PR. If I do them now it will cause merge conflicts and those would be difficult to resolve. So @sbis04 had suggested me to do the changes with a new PR to prevent any merge conflicts.

I believe it's not a good practice to reply to someone by editing in one's own comment 😅 
Okay so let's merge this for now, and pls implement the changes suggested by Simin in the next PR.

2021-06-03 11:30 UTC, shwetalsoni commented
> > pls, first address @proudofsimin's so that we can continue reviewing this PR : )
> > @Rohitesh-Kumar-Jain , I would do the rest of changes with a new PR. If I do them now it will cause merge conflicts and those would be difficult to resolve. So @sbis04 had suggested me to do the changes with a new PR to prevent any merge conflicts.
> 
> I believe it's not a good practice to reply to someone by editing in one's own comment 
> Okay so let's merge this for now, and pls implement the changes suggested by Simin in the next PR.

So sorry @Rohitesh-Kumar-Jain. I had to select quote reply but by mistake I edited it.

2021-06-04 15:13 UTC, proudofsimin requested changes
Hi @shwetalsoni, 
Have you changed the content?

2021-06-04 15:18 UTC, shwetalsoni commented
> Hi @shwetalsoni,
> Have you changed the content?

Hii @proudofsimin 
I will change make the changes with a new PR once this is merged. If I do it now it will cause merge conflicts.

2021-06-07 15:48 UTC, proudofsimin approved these changes

2021-06-09 13:13 UTC, lijiarui requested changes
I suggest using wechaty official repo in the doc and explain the official code instead a third-party repo.

2021-06-09 13:13 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +2. Clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository
We should always use wechaty official repo instead of third-party repo, making it more easy to maintain.

I think maybe you can choose or any files in wechaty-getting-started:
- https://github.com/wechaty/wechaty-getting-started  
- https://github.com/wechaty/wechaty-getting-started/tree/master/examples 
- https://github.com/wechaty/wechaty-getting-started/tree/master/examples/basic

2021-06-09 13:13 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +4. Run the bot
Also, maybe we keep `1.` as markdown standard is a better way.

2021-06-09 13:13 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +You can clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository by following the below command, and navigate to the directory:
Please change this to https://github.com/wechaty/wechaty-getting-started  
We should never use third party repo because it would be hard to maintain.

2021-06-09 13:13 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +git clone https://github.com/shwetalsoni/ding-dong-bot
change to https://github.com/wechaty/wechaty-getting-started

2021-06-09 13:13 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +cd ding-dong-bot
maybe change to `cd examples`

2021-06-09 13:13 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +with Wechat/WhatsApp app
It seems strange you add this before `
&gt; Installation guide for `Node.js` in other platforms can be found [here](https://nodejs.org/en/download/package-manager/).<br class="Apple-interchange-newline">`

because https://github.com/wechaty/wechaty.js.org/pull/897/files?short_path=6421205#diff-0777a84ed127f4e07da56f66a237e9e3eb98167a2ff8952cf0a8c0adee85feeaR56 here is telling developers how to install NodeJS

2021-06-09 14:35 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +with Wechat/WhatsApp app
Hii @lijiarui. I will make the changes with a new PR. Actually when I created branches for different PR's I forgot to switch to master and so PR no. 903 contains the changes made by me in other branches too. So if I make changes now, it would cause merge conflicts which would be difficult to resolve. So will that be fine?
I will definitely do all these changes once these PR's are merged.

2021-06-09 14:58 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +with Wechat/WhatsApp app
I think this PR cannot be merged if it is not correct, we have never merge a wrong PR and wait for a new PR to fix this.

I believe you can resolve the conflict after learning more about GitHub.

2021-06-09 15:12 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +with Wechat/WhatsApp app
ok I will do

2021-06-09 16:18 UTC, shwetalsoni commented
@lijiarui The changes that you have requested here are all for `hard-way.mdx`. In my previous PR [#888 ](https://github.com/wechaty/wechaty.js.org/pull/888/) I have updated these already and pushed. This file is shown here because by mistake while working on `getting-started page` I created the new branch without going back to master. So the changes made by me in my last PR are also shown here.

2021-06-09 16:25 UTC, shwetalsoni commented
> Hi @shwetalsoni,
> How do you think if we modify the passage to something like this:
> (I still feel it's a bit jumping between the first and second sentences, but I haven't thought of a better way to connect them.)
> 
> If you are a total beginner to Wechaty, start from this section.
> 
> You can run Wechaty on the following platforms:
> 
> * Cloud IDE
> * Gitpod
> * Local machine
> 
> Wechaty is a powerful software (maybe _software_ is not the best word here). You will learn the following fundamental features of Wechaty in the getting-started tutorials:
> 
> * Turn your WeChat/ WhatsApp account to a chatbot with few lines of code.
> * Communicate with your users for you through Wechaty Conversational RPA technology.
> * Work out of the box on Line, Mac, and Windows.
> * Support all puppets like Web, Pad, Windows, and Mac.
> * Reply with a dong message when you receive a ding message.
> 
> Seems fine to me. If you say so, I will update it

Hii @proudofsimin I have made the suggested changes.

2021-06-09 16:26 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +2. Clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository
Changed to `https://github.com/wechaty/wechaty-getting-started`

2021-06-09 16:26 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +You can clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository by following the below command, and navigate to the directory:
Fixed

2021-06-09 16:26 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +git clone https://github.com/shwetalsoni/ding-dong-bot
Fixed

2021-06-09 16:27 UTC, shwetalsoni commented on docusaurus/docs/getting-started/hard-way.mdx
> +cd ding-dong-bot
Changed to `wechaty-getting-started`

2021-06-10 12:00 UTC, shwetalsoni commented
I have created a new PR #935 for this. So, should I close this PR now?

2021-06-11 12:46 UTC, lijiarui commented
If this PR is duplicate with the other one, I suggest you close one of them. ：）

2021-06-13 06:05 UTC, closed without merging