NEW - Ahmed Essam  - GSOD
wechaty/docusaurus pull request #898
Opened 2021-05-26 11:17 UTC by Hanaffi

I made new PR for all files better than last approach

2021-05-26 11:19 UTC, Hanaffi commented
@huan @Rohitesh-Kumar-Jain

2021-05-26 14:19 UTC, Rohitesh-Kumar-Jain commented
> @huan @Rohitesh-Kumar-Jain

We still have this error : 

```
# all asset files should be put into folder `/assets/YYYY/MM-slug-...-slug/` (slugs should be the same as the post)
not ok 13 "/assets/2021/05-gsod-2021-volunteering-proposal/gsod_s.webp" from "jekyll/_posts/2021-05-05-ahmed-essam-gsod-2021-volunteering-proposal.md" should be save to "assets/2021/05-ahmed-essam-gsod-2021-volunteering-proposal/"
  ---
    operator: fail
    at: Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/asset-file-location.spec.ts:58:11)
    stack: |-
      Error: "/assets/2021/05-gsod-2021-volunteering-proposal/gsod_s.webp" from "jekyll/_posts/2021-05-05-ahmed-essam-gsod-2021-volunteering-proposal.md" should be save to "assets/2021/05-ahmed-essam-gsod-2021-volunteering-proposal/"
          at Test.assert [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/runner/work/wechaty.js.org/wechaty.js.org/node_modules/tape/lib/test.js:80:32)
          at Test.<anonymous> (/home/runner/work/wechaty.js.org/wechaty.js.org/tests/jekyll/asset-file-location.spec.ts:58:11)
  ...
```

Just fix this and we are good to go

2021-05-26 16:47 UTC, Hanaffi commented
@Rohitesh-Kumar-Jain  Last check :( ?

2021-05-27 03:05 UTC, Rohitesh-Kumar-Jain commented
> @Rohitesh-Kumar-Jain Last check :( ?

don't worry, I can check more : )

2021-05-27 04:09 UTC, Rohitesh-Kumar-Jain approved these changes
Congratulations CI turned green 🎉 🥳

2021-05-28 09:50 UTC, Rohitesh-Kumar-Jain commented
ping @huan

2021-05-28 11:41 UTC, Hanaffi commented
@huan  Hey Huan, Can you merge? Its finally green :)

2021-06-08 18:04 UTC, Hanaffi commented
@huan Can you merge please?

2021-06-09 12:24 UTC, lijiarui requested changes

2021-06-09 12:24 UTC, lijiarui commented on jekyll/_posts/2021-05-05-ahmed-essam-gsod-2021-volunteering-proposal.md
> +image: /assets/2021/05-ahmed-essam-gsod-2021-volunteering-proposal/gsod_s.webp
Please follow our file name rule:
> Create a markdown file in jekyll/_posts folder. The file name should follow the format YYYY-MM-DD-your-blog-slug.md. For example 2016-12-03-welcome-to-wechaty.md

Please change `gsod_s.webp` to `gsod-s.webp`

2021-07-10 10:20 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-10 10:21 UTC, lijiarui commented
Hi @Hanaffi , Since the `.webp` format has lots of advantages and the [safari has supported it last year](https://www.macrumors.com/2020/06/22/webp-safari-14/) which means all the modern browsers will be able to compatible with it.

@huan has just added a new unit test for enforcing the image format: the CI will not be passed if we are using other image formats than the perfect .webp.

Please make CI green to adjust the new rule, see https://github.com/wechaty/wechaty.js.org/issues/1035

2021-08-23 13:20 UTC, Rohitesh-Kumar-Jain commented
Hi @Hanaffi , would you like to push more commits to turning the CI green?

2021-09-07 17:28 UTC, huan requested changes
Please check the CI and make sure it turns green before we can continue reviewing this PR, thanks!

See: https://github.com/wechaty/wechaty.js.org/pull/898/checks?check_run_id=3035429136#step:8:65

2021-09-21 15:14 UTC, lijiarui commented
ping @Hanaffi

2021-09-28 16:12 UTC, lijiarui commented
ping @Hanaffi

2021-10-10 09:13 UTC, Rohitesh-Kumar-Jain commented
@Hanaffi feel free to reopen the PR, and push more commits to it :)

2021-10-10 09:13 UTC, closed without merging