Wechaty getting started  sub-section of the Introduction section
wechaty/docusaurus pull request #899
Opened 2021-05-26 11:22 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
| Introduction | Wechaty getting started | Joseph Mawa |

This  is **Getting started with Wechaty** sub-section of the **Introduction** section

![image](https://user-images.githubusercontent.com/52580190/119651383-a078a900-be2d-11eb-83c4-a658823c85a1.png)
![image](https://user-images.githubusercontent.com/52580190/119651475-ba19f080-be2d-11eb-84bf-58c25c6dd598.png)
![image](https://user-images.githubusercontent.com/52580190/119651572-d322a180-be2d-11eb-8c4e-3ca5b6a6994a.png)

2021-05-28 09:35 UTC, Rohitesh-Kumar-Jain commented
The documentation patch looks good to me, I would like to appreciate you for attaching appropriate links in the documentation. Great Work !

2021-05-28 15:04 UTC, nibble0101 commented
> The documentation patch looks good to me, I would like to appreciate you for attaching appropriate links in the documentation. Great Work !

Thanks for the review

2021-05-29 13:20 UTC, proudofsimin approved these changes
It looks great. Maybe next time we could try to eliminate the frequency of using "You" to start a sentence. It sounds a bit commanding.
FYI: [self-editing](https://developers.google.com/tech-writing/two/editing)

2021-05-29 14:19 UTC, Rohitesh-Kumar-Jain reviewed
It looks good to me, do let me know when you think the PR is ready to get merged : )

2021-05-31 08:01 UTC, nibble0101 commented
@proudofsimin  :100: Okay then we shall limit the use of `you` at the beginning of a sentence in the subsequent iterations of the docs.

@Rohitesh-Kumar-Jain  We are ready for merging. We have links that are not pointing to the exact location because the doc. is still evolving. At the moment we are using placeholders. We shall start replacing them in the  next iterations when the entire doc. is 60 - 80 %  finished.

2021-06-01 05:47 UTC, Rohitesh-Kumar-Jain approved these changes
PR ready to be merged
ping @huan

2021-06-09 13:16 UTC, lijiarui requested changes
Maybe we should change `docusaurus/docs/getting-started-with-wechaty.md` to `docusaurus/docs/getting-started-with-wechaty.mdx`

2021-07-10 10:22 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-11 17:41 UTC, proudofsimin commented
> hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in #1045
> 
> This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

Hi @chris-4444 could you review and add the tag `ready to merge` afterwards? Thank you.

2021-07-12 13:16 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-12 17:31 UTC, lijiarui commented
hi @chris-4444 , as @Rohitesh-Kumar-Jain said, I will remove `ready to merge` tag, when it got enough approval, feel free to add it again.

2021-07-13 15:19 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 21:34 UTC, lijiarui requested changes

2021-07-18 21:34 UTC, lijiarui commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +We have set up a Wechaty [getting-started repository](https://github.com/wechaty/wechaty-getting-started) to help you start writing code in a couple of minutes. The Wechaty [getting-started repositor
I think we already have ding-dong bot link here: https://github.com/wechaty/wechaty-getting-started/blob/master/examples/ding-dong-bot.js

2021-07-18 21:34 UTC, lijiarui commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +We have set up a Wechaty [getting-started repository](https://github.com/wechaty/wechaty-getting-started) to help you start writing code in a couple of minutes. The Wechaty [getting-started repositor
I think we should add IDE link here because it seems doesn't depends on any other PR.

2021-07-18 21:34 UTC, lijiarui commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +We have made it very easy to start writing Wechaty code in any of the supported programming languages. You need a few lines of code to turn your WeChat or Whatsapp account into a chatbot. Your chatbo
turn your WeChat or Whatsapp account into a chatbot --> change to `turn your IM (such as [WeChat](https://www.wechat.com/), [Whatsapp](https://www.whatsapp.com/), [Wecom](https://work.weixin.qq.com/), [Lark](https://www.larksuite.com/zh_cn/), etc)account into a chatbot.`

2021-07-19 19:32 UTC, nibble0101 commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +We have set up a Wechaty [getting-started repository](https://github.com/wechaty/wechaty-getting-started) to help you start writing code in a couple of minutes. The Wechaty [getting-started repositor
Added

2021-07-19 19:37 UTC, nibble0101 commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +We have made it very easy to start writing Wechaty code in any of the supported programming languages. You need a few lines of code to turn your WeChat or Whatsapp account into a chatbot. Your chatbo
Added

2021-07-29 14:40 UTC, lijiarui requested changes

2021-07-29 14:40 UTC, lijiarui commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +title: Getting started with Wechaty
I think we should change to `Getting started` because all of the docs is talking about Wechaty.

2021-07-29 14:40 UTC, lijiarui commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
We should change this image to a more related image instead of a general logo here.

2021-07-30 17:17 UTC, nibble0101 commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +title: Getting started with Wechaty
Changed

2021-07-30 17:23 UTC, nibble0101 commented on docusaurus/docs/getting-started-with-wechaty.mdx
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I can't think of any image at the moment. Instead removed it.

2021-07-31 17:38 UTC, lijiarui approved these changes
LGTM

2021-08-02 10:04 UTC, Rohitesh-Kumar-Jain commented
@nibble0101 this branch has some conflicts, pls resolve them so that we can merge this, @proudofsimin I would be glad if you may take care of merging PRs in the future : )

2021-08-02 10:40 UTC, nibble0101 commented
> @nibble0101 this branch has some conflicts, pls resolve them so that we can merge this, @proudofsimin I would be glad if you may take care of merging PRs in the future : )

@Rohitesh-Kumar-Jain  I think it is fine now.

2021-08-02 16:00 UTC, merged