Who is using wechaty subsection of the introduction section
wechaty/docusaurus pull request #900
Opened 2021-05-26 18:54 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
| Introduction | Who is using wechaty |  Chris Estepa, Joseph Mawa |

This  is **Who is using wechaty** sub-section of the **Introduction** section

![image](https://user-images.githubusercontent.com/52580190/119715279-7beff180-be6c-11eb-880a-3ac5988ee4ed.png)
![image](https://user-images.githubusercontent.com/52580190/119715410-a5108200-be6c-11eb-8d93-0654e8521106.png)
![image](https://user-images.githubusercontent.com/52580190/119715641-e43ed300-be6c-11eb-9e4b-b6a566f63fbc.png)

2021-05-27 15:48 UTC, iamrajiv requested changes

2021-05-27 15:48 UTC, iamrajiv commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are still not sure whether Wechaty can solve your problem or challenge, take a look at [what you can do with Wechaty](#link) section. Wechaty is evolving very fast. New Wechaty [puppets](#link
```suggestion
If you are still unsure whether Wechaty can solve your problem or challenge, take a look at [what you can do with Wechaty](#link) section. Wechaty is evolving very fast. Our dedicated community of developers is adding new Wechaty [puppets](#link-to-puppets) and [plugins](#link-to-plugins). Feel free to ask. We shall be happy to help you.
```

2021-05-27 15:48 UTC, iamrajiv commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are interested in using Wechaty, you are welcome to join our [community](#link) of users and developers. We are an inclusive and welcoming community.
```suggestion
If you are interested in using Wechaty, you are welcome to join our [community](#link) of users and developers. We are an inclusive and welcoming community.

```

2021-05-27 15:48 UTC, iamrajiv commented on docusaurus/docs/who-is-using-wechaty.md
> +- [Meituan](https://www.meituan.com/) - is a group-discount website which sells vouchers from merchants for deals and generates most of its revenue from mobile application services.
```suggestion
- [Meituan](https://www.meituan.com/) - is a group-discount website that sells vouchers from merchants for deals and generates most of its revenue from mobile application services.
```

This fixes the pronoun problem.

2021-05-27 15:48 UTC, iamrajiv commented on docusaurus/docs/who-is-using-wechaty.md
> +- [Plug And Play](https://www.plugandplaytechcenter.com/) - is the world's largest early stage investor, accelerator, and corporate innovation platform
```suggestion
- [Plug And Play](https://www.plugandplaytechcenter.com/) - is the world's largest early-stage investor, accelerator, and corporate innovation platform
```

2021-05-27 17:08 UTC, iamrajiv approved these changes

2021-05-30 07:15 UTC, proudofsimin commented
Hi @nibble0101,
I guess this part also includes a bit of marketing purpose. Imagine yourself as a user who is a foreigner and has never used Wechaty before. When you are considering if you would like to import this software to your company, seeing that most of the users are Chinese companies, how do you feel? Although your introduction is correct, but it makes Wechaty seems a bit local.  As far as I know, those companies have many users outside China. Do you think if it's better that we focus them on the international part than where they are based? For example like L'Oréal is from France but you would describe it as "world's leading FMCG". 
This is my opinions. How do you think? And @huan I'm not sure if this is how you like the customers to be described or if they have specific official introduction.

2021-05-30 08:57 UTC, chris-4444 commented
@huan Can you please confirm what L'Oréal branch is using Wechaty just to be sure? Is it L'Oréal China?
@proudofsimin Would it be okay if we put L'Oréal China there once it was confirmed? Or, would you like us to remove the company descriptions? All are Chinese companies except for Plug and Play, which is an international company.

2021-05-31 07:51 UTC, nibble0101 commented
> Hi @nibble0101,
> I guess this part also includes a bit of marketing purpose. Imagine yourself as a user who is a foreigner and has never used Wechaty before. When you are considering if you would like to import this software to your company, seeing that most of the users are Chinese companies, how do you feel? Although your introduction is correct, but it makes Wechaty seems a bit local. As far as I know, those companies have many users outside China. Do you think if it's better that we focus them on the international part than where they are based? For example like L'Oréal is from France but you would describe it as "world's leading FMCG".
> This is my opinions. How do you think? And @huan I'm not sure if this is how you like the customers to be described or if they have specific official introduction.

Thanks @proudofsimin  for the invaluable feedback. Definitely if I were a businessman seeking to start using Wechaty in my business, I would have a lot more confidence in Wechaty if its users are companies that have a global footprint. We can add more information about  each company's  reach (customer base) outside China to give a lot more confidence to potential users, especially those from outside China.  Perhaps @huan  will have to furnish us with a list of other companies outside China that have used or are using Wechaty if they exist so that we have a mix of both China based companies and those outside China.

2021-05-31 08:05 UTC, proudofsimin commented
> > Hi @nibble0101,
> > I guess this part also includes a bit of marketing purpose. Imagine yourself as a user who is a foreigner and has never used Wechaty before. When you are considering if you would like to import this software to your company, seeing that most of the users are Chinese companies, how do you feel? Although your introduction is correct, but it makes Wechaty seems a bit local. As far as I know, those companies have many users outside China. Do you think if it's better that we focus them on the international part than where they are based? For example like L'Oréal is from France but you would describe it as "world's leading FMCG".
> > This is my opinions. How do you think? And @huan I'm not sure if this is how you like the customers to be described or if they have specific official introduction.
> 
> Thanks @proudofsimin for the invaluable feedback. Definitely if I were a businessman seeking to start using Wechaty in my business, I would have a lot more confidence in Wechaty if its users are companies that have a global footprint. We can add more information about each company's reach (customer base) outside China to give a lot more confidence to potential users, especially those from outside China. Perhaps @huan will have to furnish us with a list of other companies outside China that have used or are using Wechaty if they exist so that we have a mix of both China based companies and those outside China.

I know those companies are very large and I actually meant that to focus those companies on the international part. For example like Tencent, we could describe it as "a ~Chinese~ multinational technology...". How do you think?

2021-05-31 08:09 UTC, nibble0101 commented
> > > Hi @nibble0101,
> > > I guess this part also includes a bit of marketing purpose. Imagine yourself as a user who is a foreigner and has never used Wechaty before. When you are considering if you would like to import this software to your company, seeing that most of the users are Chinese companies, how do you feel? Although your introduction is correct, but it makes Wechaty seems a bit local. As far as I know, those companies have many users outside China. Do you think if it's better that we focus them on the international part than where they are based? For example like L'Oréal is from France but you would describe it as "world's leading FMCG".
> > > This is my opinions. How do you think? And @huan I'm not sure if this is how you like the customers to be described or if they have specific official introduction.
> > 
> > 
> > Thanks @proudofsimin for the invaluable feedback. Definitely if I were a businessman seeking to start using Wechaty in my business, I would have a lot more confidence in Wechaty if its users are companies that have a global footprint. We can add more information about each company's reach (customer base) outside China to give a lot more confidence to potential users, especially those from outside China. Perhaps @huan will have to furnish us with a list of other companies outside China that have used or are using Wechaty if they exist so that we have a mix of both China based companies and those outside China.
> 
> I know those companies are very large and I actually meant that to focus those companies on the international part. For example like Tencent, we could describe it as "a ~Chinese~ multinational technology...". How do you think?

That is fine with me. We can do the same for other companies that have footprint outside China as well. What do you think @chris-4444?

2021-05-31 08:12 UTC, proudofsimin commented
> @huan Can you please confirm what L'Oréal branch is using Wechaty just to be sure? Is it L'Oréal China?
> @proudofsimin Would it be okay if we put L'Oréal China there once it was confirmed? Or, would you like us to remove the company descriptions? All are Chinese companies except for Plug and Play, which is an international company.

@chris-4444 Wechat, baidu, and those companies are very large in China and have branches all over the world, so maybe we could focus on the international part of them. What I mentioned about L'Oréal means that although L'Oréal is based in France, you would describe it as a world's leading FMCG instead of a French leading FMCG. Do you feel it is better? This is just my point of view. If you feel the original version is better, you could keep it.

2021-05-31 08:39 UTC, chris-4444 requested changes
@nibble0101 yep sure. 👍🏽 @proudofsimin yeah you're right.  updated it and now, there's a global feel to it compared before. we'll update again if needed. :)

2021-06-04 15:34 UTC, proudofsimin commented
> @nibble0101 yep sure. 👍🏽 @proudofsimin yeah you're right. updated it and now, there's a global feel to it compared before. we'll update again if needed. :)

Hi @chris-4444,
Thanks I saw your commit, but did you check the rest Chinese companies (other than Tencent)? Do they have branches/ market share abroad? 
BTW, I just found out that Wechat is actually owned by Tencent, like WhatsApp to Facebook. You might need to mention it.

Thank you :)

2021-06-07 04:13 UTC, chris-4444 commented
@proudofsimin Updated Tencent description. I noticed that Baidu has a branch in US but didn't mention it. Re the market share, I don't know how to compute in case we need to put it. For the rest of the companies, it is only Tencent and Wechat that are related. :) Should I mention the other locations of the companies then? Tia for the advice.

2021-06-09 03:38 UTC, Rohitesh-Kumar-Jain approved these changes
Looks good to me : )

> Should I mention the other locations of the companies then? Tia for the advice.
@proudofsimin 

Feel free to add ready-to-merge label as soon as Simin approves these changes

2021-06-09 13:21 UTC, lijiarui commented
How about we put this to the `Introduction--> community` part instead of putting it just under the `introduction` part?

2021-06-09 13:22 UTC, lijiarui reviewed
How about we put this to the `Introduction--> community` part instead of putting it just under the `introduction` part?

2021-06-12 13:39 UTC, proudofsimin approved these changes
Approved for the document content. Regarding the location, I'm fine with either of them. Thank you.

2021-07-02 11:19 UTC, nibble0101 commented
> How about we put this to the `Introduction--> community` part instead of putting it just under the `introduction` part?

Hi @lijiarui Thanks for the review and sorry for the late reply. Actually it was intentional that we placed that section under Introduction. Just like we mentioned in our proposal, one of our goals is to avoid having documents  nested two or more levels deep especially in the sections we are working on. One of the reasons is to help anyone who is new to easily access the information they are looking for. One example is when  we were writing the GSoD proposals, I had to always use the search bar to locate the Wechaty GSOD proposal because the information is hidden in Introduction -> Community -> Google season of docs. Such nesting makes it difficult to locate specific information in the documentation.

We are also proposing the removal of the community section from the documentation. We don't see any valid reason why it should be in the docs.  The documentation in our opinion looks huge because of all the information we believe should not be there in the first place e.g. community, showcase etc. Even when you check most  of the popular open source projects I have listed below, their community section is not part of the documentation. It is a separate menu item on the website. Doing that will keep the doc clean with only the necessary information so that locating what you need becomes easy. You can check the following docs to see what I am talking about.
- [react native doc](https://reactnative.dev/)
- [electron doc](https://www.electronjs.org/docs)
- [react doc](https://reactjs.org/)
- [docusaurus doc](https://docusaurus.io/)

Since the PRs here are not being merged, we have deployed a clone of  wechaty.js.org containing the Introduction and Explanation section. You can check it out [here](https://wechaty-js-org.netlify.app/docs/). That is how we would love those two sections to be; short and precise with only the necessary information. However if you still want the community section to be part of the docs, we shall add it and include who is using Wechaty section in it.

2021-07-10 12:03 UTC, lijiarui commented
> @huan Can you please confirm what L'Oréal branch is using Wechaty just to be sure? Is it L'Oréal China?
> @proudofsimin Would it be okay if we put L'Oréal China there once it was confirmed? Or, would you like us to remove the company descriptions? All are Chinese companies except for Plug and Play, which is an international company.

Hi @chris-4444 , L'Oréal is [Juzi.bot](https://pre-angel.com/portfolios/juzibot/)  customer, my company [Juzi.bot](https://pre-angel.com/portfolios/juzibot/) build on top of Wechaty, we provide SaaS solutions to large enterprises. It is L'Oréal, so I think it is suitable putting L'Oréal on wechaty list.

2021-07-12 11:51 UTC, chris-4444 commented
LGTM.

2021-07-12 11:52 UTC, chris-4444 approved these changes
LGTM.

2021-07-12 12:48 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 and @nibble0101 would you like to push any more commits to this PR?

@nibble0101 approve this PR when you feel it's ready to be merged

2021-07-12 12:52 UTC, nibble0101 commented
> @chris-4444 and @nibble0101 would you like to push any more commits to this PR?
> 
> @nibble0101 approve this PR when you feel it's ready to be merged

I authored all the PRs. I don't think I will be able to approve any of them. Since @chris-4444  has approved it, then we are good.

2021-07-12 13:03 UTC, Rohitesh-Kumar-Jain commented
> > @chris-4444 and @nibble0101 would you like to push any more commits to this PR?
> > @nibble0101 approve this PR when you feel it's ready to be merged
> 
> I authored all the PRs. I don't think I will be able to approve any of them. Since @chris-4444 has approved it, then we are good. LGTM

thanks for letting me know this : )

2021-07-12 17:09 UTC, lijiarui requested changes
I have some suggestion about this part, how do you think of this?

2021-07-12 17:09 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +
How do you think of we add this part here： [Voice of Developers](https://github.com/wechaty/wechaty#yum-voice-of-developers)

2021-07-12 17:09 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +- [Wechat](https://www.wechat.com/en/) - is China's top free messaging and calling app that serves as a mobile internet
Hi @nibble0101 How do you think we change the company introduction to the company logo?  Maybe people don't care what company introduction here.

2021-07-12 17:09 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +
We have two images introducing wechaty contributors and developers at [wechaty introduction slide](https://docs.google.com/presentation/d/1eRNrKnCpdnsmplTwtZzmtGZgrPoNCmOnitmHKVc6iVU/edit#slide=id.g476e76b184_1_58), do you think it is suitable adding them here?

And I think maybe we can add the following users:
- Google，Tencent , ByteDance engineers and entrepreneurs

![image](https://user-images.githubusercontent.com/6419514/125327463-b6a6de00-e375-11eb-816a-df2a8893355e.png)

![image](https://user-images.githubusercontent.com/6419514/125327487-beff1900-e375-11eb-820e-f5b4e8774c0d.png)

2021-07-12 17:09 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are interested in using Wechaty, you are welcome to join our [community](#link) of users and developers. We are an inclusive and welcoming community.
I think we should change [community](#link) to `[community](https://gitter.im/wechaty/wechaty)`

2021-07-12 17:09 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are still not sure whether Wechaty can solve your problem or challenge, take a look at [what you can do with Wechaty](#link) section. Wechaty is evolving very fast. New Wechaty [puppets](#link
It seems we lack several links here, how about file a issue to track this, and added in the future?

2021-07-13 13:32 UTC, chris-4444 requested changes
@nibble0101 Updated If you are interested in using Wechaty links, last paragraph. Is this okay?

2021-07-13 13:59 UTC, nibble0101 commented
Hi @lijiarui Thanks for the suggestions. I will look into what you have suggested in the coming days. I think they will make excellent additions to that sub-section. About the links, we shall add those links which point to other sections in the docs after most of the PRs have been merged because they are being worked on by other teams to avoid failing CI. We are tracking them.

@chris-4444  We still have to add some of images suggested by @lijiarui. I am removing the ready to merge tag

2021-07-14 17:32 UTC, lijiarui commented
Thanks for your work! Great to know that you are tracking for the links!

2021-07-15 07:59 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are still not sure whether Wechaty can solve your problem or challenge, take a look at [what you can do with Wechaty](#link) section. Wechaty is evolving very fast. New Wechaty [puppets](#link
Issue #1091 is now tracking the missing the links

2021-07-23 13:22 UTC, chris-4444 requested changes
@nibble0101 Added the company logos.  @lijiarui  Would it be okay if we retain the company descriptions because there might be some users who would like to know what these companies do? Even if most clients are from Asia, Wechaty's audience is all over the world so they might want to know these? 😉

2021-07-23 15:38 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +
Added.

2021-07-23 16:05 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +
Added

2021-07-23 16:07 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are still not sure whether Wechaty can solve your problem or challenge, take a look at [what you can do with Wechaty](#link) section. Wechaty is evolving very fast. New Wechaty [puppets](#link
Added. Only one missing link awaiting new sections which are yet to be merged.

2021-07-23 16:08 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are interested in using Wechaty, you are welcome to join our [community](#link) of users and developers. We are an inclusive and welcoming community.
Added

2021-07-26 01:33 UTC, chris-4444 approved these changes
LGTM.

2021-07-26 12:29 UTC, Rohitesh-Kumar-Jain commented
This PR has conflicts but version conflicts can be resolved after @lijiarui again review this

2021-07-29 13:57 UTC, lijiarui requested changes

2021-07-29 13:57 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Maybe we should change a more related image here or remove it. Wechaty logo is too general for this part.

2021-07-29 13:57 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are interested in using Wechaty, you are welcome to join our [community](https://gitter.im/wechaty/wechaty) of users and [developers](https://github.com/wechaty/wechaty#yum-voice-of-developers
Please change developer link to https://wechaty.js.org/contributors/

2021-07-30 17:32 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Removed Wechaty logo.

2021-07-30 17:38 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +If you are interested in using Wechaty, you are welcome to join our [community](https://gitter.im/wechaty/wechaty) of users and [developers](https://github.com/wechaty/wechaty#yum-voice-of-developers
Change link URL.

2021-07-31 17:35 UTC, lijiarui requested changes

2021-07-31 17:35 UTC, lijiarui commented on docusaurus/docs/who-is-using-wechaty.md
> +  ![Wechaty users](../static/img/docs/wechaty-users.webp)
Here is the Wechaty user instead of companies, so I suggest putting them on the `Users of Wechaty` part.

2021-08-03 11:58 UTC, nibble0101 commented on docusaurus/docs/who-is-using-wechaty.md
> +  ![Wechaty users](../static/img/docs/wechaty-users.webp)
Added to Users of Wechaty section.

2021-08-23 13:56 UTC, lijiarui approved these changes
LGTM

2021-08-23 16:29 UTC, Rohitesh-Kumar-Jain commented
@nibble0101 pls  resolve the conflict, and then ping for merge

2021-08-23 18:17 UTC, nibble0101 commented
> @nibble0101 pls resolve the conflict, and then ping for merge

@Rohitesh-Kumar-Jain  I think we are good.

2021-08-24 06:45 UTC, merged