[Week 2] How-to-guide Overview
wechaty/docusaurus pull request #901
Opened 2021-05-27 10:47 UTC by abhishek-iiit

Added Different heading in the overview section of how-to-guide
![Screenshot from 2021-05-27 10-58-47](https://user-images.githubusercontent.com/69477761/119813308-bc9c4900-bf06-11eb-889a-d1a7a8e2ad73.png)
![Screenshot from 2021-05-27 10-59-00](https://user-images.githubusercontent.com/69477761/119813311-bdcd7600-bf06-11eb-8f7b-9eddbe71ce73.png)

2021-05-31 09:31 UTC, proudofsimin reviewed
I'm a bit confused. If this part is at the very beginning of overview, please includes the prerequisite telling users they need some basic knowledge and direct them to the correct page if they are new to wechaty. 
If this part is not at the beginning, then omit my comment. Thank you.

2021-05-31 09:31 UTC, proudofsimin commented on docusaurus/docs/howto/overview.mdx
> +How-to guides are recipes and they guide you through the steps involved in addressing key problems and use-cases.
How-to guides are like recipes when you are cooking. Equipped with basic knowledge about Wechaty, you can find key problems and use-cases here. If you are a total beginner, go to [Wechaty getting started](https://wechaty.js.org/docs/getting-started/) first.

2021-06-03 17:23 UTC, abhishek-iiit commented on docusaurus/docs/howto/overview.mdx
> +How-to guides are recipes and they guide you through the steps involved in addressing key problems and use-cases.
Thanks @proudofsimin for your helpful feedback :) Please review for the same and have us ready for merge.

2021-06-04 15:37 UTC, proudofsimin approved these changes
Thank you :)

2021-06-04 17:03 UTC, Rohitesh-Kumar-Jain approved these changes
ping for merge @huan

2021-06-09 13:28 UTC, lijiarui requested changes
Please change as I request.

2021-06-09 13:28 UTC, lijiarui commented on README.md
> +1. Fork this repository
Fork this repository: https://github.com/wechaty/wechaty.js.org

2021-06-09 13:28 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +- [Deploy in Whatsapp](#)
We can add:

- Deploy in WeCom
- Deploy in Gitter
- Deploy in Lark
- Deploy in WeChat Official Account
- Deploy in Dingding

2021-06-12 12:12 UTC, abhishek-iiit commented on docusaurus/docs/howto/overview.mdx
> +- [Deploy in Whatsapp](#)
Thanks a lot for the feedback ,have added the same as suggested :)

2021-06-12 12:13 UTC, abhishek-iiit commented on README.md
> +1. Fork this repository
added the same as suggested :)

2021-06-16 15:42 UTC, closed without merging