Tutorial overview
wechaty/docusaurus pull request #903
Opened 2021-05-28 08:17 UTC by shwetalsoni

Updated tutorial overview by adding different tutorials available and also explaining which tutorial is convenient for which type of user.

* Classified tutorials into three categories

     * Building your first chatbot with wechaty
     
     * Advanced tutorials (Using plugins, library, and framework with wechaty)
     
     * Explore more bots (Adding more features to your bot)
     
![Screenshot from 2021-05-28 13-45-06](https://user-images.githubusercontent.com/57187745/119952799-ff1f5d80-bfba-11eb-9c56-669aa5ddd182.png)

![Screenshot from 2021-05-28 13-45-21](https://user-images.githubusercontent.com/57187745/119952808-00e92100-bfbb-11eb-8288-29ed4d88cdb6.png)

2021-05-28 08:17 UTC, shwetalsoni commented
Tag: #891

2021-06-01 04:15 UTC, sbis04 commented
@shwetalsoni I think you are creating the new branches for PRs from your last changed branch. Same for this PR as well: #897, both of these contain changes of #888 

If you are doing this and in case you need to do changes to the previous branch, assume you pushed some new commits to the previous PR. Now when the previous PR gets merged and a part of those changes are in a new PR also, so this may create some merge conflicts which would be time taking to solve.

Instead of doing that, next time the better way would be to:

1. Switch to the master branch of this repo using:

```sh
git checkout master
```

2. To make sure your fork is updated to the master of the original repo:

```sh
git remote add upstream https://github.com/wechaty/wechaty.js.org.git
git fetch upstream
```

3. Now, create the branch from the master:

```sh
git branch name-of-branch
git checkout name-of-branch
```

2021-06-01 04:26 UTC, sbis04 approved these changes
In order to prevent any merge conflicts, I think it would be better to not make any changes to the previous two PRs (#888, #897), and if it is required to make any suggested changes in previous PRs it would be better to create a new PR to do those after these three are merged.

2021-06-01 08:13 UTC, shwetalsoni commented
> In order to prevent any merge conflicts, I think it would be better to not make any changes to the previous two PRs (#888, #897), and if it is required to make any suggested changes in previous PRs it would be better to create a new PR to do those after these three are merged.

Thanks @sbis04 for addressing this. Once this PR is merged I would do the rest changes by creating new PR

2021-06-01 14:42 UTC, proudofsimin approved these changes
Your instruction is pretty clear. I like it, but please correct some minor typos. Thanks!

2021-06-01 14:42 UTC, proudofsimin commented on docusaurus/docs/tutorials/overview.md
> +For better understanding we have classified the bots under three categories taking you from building basic to proffesional bots.
correct typo: professional

2021-06-01 14:42 UTC, proudofsimin commented on docusaurus/docs/tutorials/overview.md
> +- [World's Shortest Chatbot](examples/basic/the-worlds-shortest-chatbot-code-in-6-lines.md): The very first wechaty example showcasing how easy it is to get started.
please remove the period at the end.

2021-06-02 05:18 UTC, shwetalsoni commented on docusaurus/docs/tutorials/overview.md
> +- [World's Shortest Chatbot](examples/basic/the-worlds-shortest-chatbot-code-in-6-lines.md): The very first wechaty example showcasing how easy it is to get started.
Didn't get this one @proudofsimin

2021-06-06 04:47 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/tutorials/overview.md
> +- [World's Shortest Chatbot](examples/basic/the-worlds-shortest-chatbot-code-in-6-lines.md): The very first wechaty example showcasing how easy it is to get started.
A period (in America) is a full stop (.). It is a punctuation mark (.) at the end of a sentence.

2021-06-06 04:50 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/tutorials/overview.md
> +For better understanding we have classified the bots under three categories taking you from building basic to proffesional bots.
Pls take assistance from some grammar and spell checker to avoid this kind of mistakes (first line of defence against typos), and finally proofread once to avoid these mistakes.

2021-06-06 07:01 UTC, shwetalsoni commented on docusaurus/docs/tutorials/overview.md
> +For better understanding we have classified the bots under three categories taking you from building basic to proffesional bots.
> Pls take assistance from some grammar and spell checker to avoid this kind of mistakes (first line of defence against typos), and finally proofread once to avoid these mistakes.

Thanks @Rohitesh-Kumar-Jain. I would keep that in mind

2021-06-06 07:50 UTC, shwetalsoni commented on docusaurus/docs/tutorials/overview.md
> +- [World's Shortest Chatbot](examples/basic/the-worlds-shortest-chatbot-code-in-6-lines.md): The very first wechaty example showcasing how easy it is to get started.
@proudofsimin and @Rohitesh-Kumar-Jain I have done the suggested changes

2021-06-06 09:09 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for rectifying the errors : )

2021-06-09 13:32 UTC, lijiarui requested changes
We should always use wechaty official repo.

2021-06-09 13:32 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +2. Clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository
We should not use a third party repo here.

2021-06-09 13:32 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +You can clone the [Ding Dong Bot](https://github.com/shwetalsoni/ding-dong-bot) repository by following the below command, and navigate to the directory:
Should change back to https://github.com/wechaty/wechaty-getting-started

2021-06-09 13:32 UTC, lijiarui commented on docusaurus/docs/getting-started/hard-way.mdx
> +git clone https://github.com/shwetalsoni/ding-dong-bot
please change back to https://github.com/wechaty/wechaty-getting-started

2021-06-09 16:30 UTC, shwetalsoni commented
@lijiarui I have fixed all these in #888. This PR contains the changes of the previous two PR's because of creating the new branch from the previous branch.  That's why it is also shown here

2021-06-10 02:58 UTC, Rohitesh-Kumar-Jain commented
> @lijiarui I have fixed all these in #888. This PR contains the changes of the previous two PR's because of creating the new branch from the previous branch. That's why it is also shown here

I am not sure if you know how to work on two different features:

```
git switch -c feature1
```
Do your work on feature 1

```
git switch master

git switch -c feature2
```
Do your work on feature 2

Feel free to ask any doubt regarding git workflow : )

But @shwetalsoni thanks for adding a clean screenshot, it really helps in reviewing especially if 30+ commits are being pushed. 

Another thing, pls do a local testing before pushing here. Local tests are actually fast, and helps to avoid unnecessary commits.
You can also squeeze commits for a better commit history.

Your document quality is good but you are making meals of your PRs 😅 

Another thing I would like to say is to focus on delivering deliverables according to your timeline and don't worry about making a commit each and every day.

2021-06-10 07:01 UTC, shwetalsoni commented
> > @lijiarui I have fixed all these in #888. This PR contains the changes of the previous two PR's because of creating the new branch from the previous branch. That's why it is also shown here
> 
> I am not sure if you know how to work on two different features:
> 
> ```
> git switch -c feature1
> ```
> 
> Do your work on feature 1
> 
> ```
> git switch master
> 
> git switch -c feature2
> ```
> 
> Do your work on feature 2
> 
> Feel free to ask any doubt regarding git workflow : )
> 
> But @shwetalsoni thanks for adding a clean screenshot, it really helps in reviewing especially if 30+ commits are being pushed.
> 
> Another thing, pls do a local testing before pushing here. Local tests are actually fast, and helps to avoid unnecessary commits.
> You can also squeeze commits for a better commit history.
> 
> Your document quality is good but you are making meals of your PRs 
> 
> Another thing I would like to say is to focus on delivering deliverables according to your timeline and don't worry about making a commit each and every day.

Thanks @Rohitesh-Kumar-Jain for briefing me about git workflow :)
I'll definitely follow this. Also, these bunch of PR's are because of package.json version problem, everytime I was trying to push, it was doing some pre-commit due to which I was unable to push. Later I resolved it and hence my next PR #923 had a clean commit history.
And yes I'm strictly following my timeline.

2021-06-10 07:12 UTC, Rohitesh-Kumar-Jain commented
> And yes I'm strictly following my timeline.

there's no fixed frequency for you to make a commit, just be with the timeline. 
Ik you must have forgotten to switch back to master before creating the feature2 branch, it happens but you should also quickly cover up for that.

2021-06-10 07:17 UTC, shwetalsoni commented
> > And yes I'm strictly following my timeline.
> 
> there's no fixed frequency for you to make a commit, just be with the timeline.
> Ik you must have forgotten to switch back to master before creating the feature2 branch, it happens but you should also quickly cover up for that.

Before I could know about this I had already created two new branches and also pushed them, then I had no idea how to fix that and souvik suggested me to make the new changes with new PR. Can you please tell me what could have been done to fix this.

Thanks :)

2021-06-10 08:04 UTC, lijiarui commented
@Rohitesh-Kumar-Jain 

> 
> I am not sure if you know how to work on two different features:
> 
> git switch -c feature1
> Do your work on feature 1
> 
> git switch master
> 
> git switch -c feature2
> Do your work on feature 2

I know this workflow, so that's why each PR should only contain the related files instead of containing other PR.

I suggest remove committing `docusaurus/docs/getting-started/hard-way.mdx` if this file is unrelated to this PR, thus will make it clear to review.

2021-06-10 08:07 UTC, Rohitesh-Kumar-Jain commented
> I know this workflow, so that's why each PR should only contain the related files instead of containing other PR.

I was suggesting this to @shwetalsoni, not to you 😅

2021-06-10 08:09 UTC, Rohitesh-Kumar-Jain commented
> I am not sure if you know how to work on two different features:

I meant this for @shwetalsoni, that's why I quoted her reply.

2021-06-10 08:11 UTC, shwetalsoni commented
> > I know this workflow, so that's why each PR should only contain the related files instead of containing other PR.
> 
> I was suggesting this to @shwetalsoni, not to you



Hii @Rohitesh-Kumar-Jain can you please tell me how can I remove unrelated files from this PR.

2021-06-10 08:13 UTC, lijiarui commented
@Rohitesh-Kumar-Jain Cool, then pls help @shwetalsoni to clean the commit.

Also, I suggest removing the `ready to merge` tag, only when @shwetalsoni has clean the commit, then adding this tag to the issue, will make it more clear when we trying to merge PR.

How do you think about this?

2021-06-10 08:16 UTC, shwetalsoni commented
@Rohitesh-Kumar-Jain what if I revert the other files unrelated to this PR to their state as in the master branch and then commit. Will this be okay or if there's any other way ?

2021-06-10 08:34 UTC, Rohitesh-Kumar-Jain commented
> Hii @Rohitesh-Kumar-Jain can you please tell me how can I remove unrelated files from this PR.

Probably not the best way but the easiest way is to simply raise another PR and close this one (link this one to that PR)

Start by: 

```
git switch master # switch to master branch
git fetch upstream master # fetch upstream/master without merging into local master
git reset --hard upstream/master # reset local master to upstream/master's state
git push --force origin master # force-update your fork's master to reflect upstream
git switch -c new-branch-name
```
make your changes that should have been in this PR, raise a new PR link this one and close this PR.

2021-06-10 10:32 UTC, shwetalsoni commented
> > Hii @Rohitesh-Kumar-Jain can you please tell me how can I remove unrelated files from this PR.
> 
> Probably not the best way but the easiest way is to simply raise another PR and close this one (link this one to that PR)
> 
> Start by:
> 
> ```
> git switch master # switch to master branch
> git fetch upstream master # fetch upstream/master without merging into local master
> git reset --hard upstream/master # reset local master to upstream/master's state
> git push --force origin master # force-update your fork's master to reflect upstream
> git switch -c new-branch-name
> ```
> 
> make your changes that should have been in this PR, raise a new PR link this one and close this PR.

Ok, I'll do this but due it won't affect already created branches right?

2021-06-10 11:04 UTC, Rohitesh-Kumar-Jain commented
> Ok, I'll do this but due it won't affect already created branches right?

Actually 

```
git fetch upstream master # fetch upstream/master without merging into local master
git reset --hard upstream/master # reset local master to upstream/master's state
git push --force origin master # force-update your fork's master to reflect upstream
```
These commands will sync your master branch to upstream master branch

The commands you need are just ...
```
git switch master # switch to master branch
git switch -c new-branch-name
```
I don't think these two will affect your existing branches

2021-06-10 11:09 UTC, shwetalsoni commented
> > Ok, I'll do this but due it won't affect already created branches right?
> 
> Actually
> 
> ```
> git fetch upstream master # fetch upstream/master without merging into local master
> git reset --hard upstream/master # reset local master to upstream/master's state
> git push --force origin master # force-update your fork's master to reflect upstream
> ```
> 
> These commands will sync your master branch to upstream master branch
> 
> The commands you need are just ...
> 
> ```
> git switch master # switch to master branch
> git switch -c new-branch-name
> ```
> 
> I don't think these two will affect your existing branches

ok, Thanks @Rohitesh-Kumar-Jain :)

2021-06-10 11:37 UTC, shwetalsoni commented
I have created a new PR for tutorial overview #934. @Rohitesh-Kumar-Jain should I close this one?

2021-06-13 06:13 UTC, closed without merging