Main concepts in Wechaty
wechaty/docusaurus pull request #904
Opened 2021-05-28 14:58 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
| Introduction | Main concepts in Wechaty |  Chris Estepa, Joseph Mawa |

This  is **Main concepts in Wechaty** sub-section of the **Introduction** section

![image](https://user-images.githubusercontent.com/52580190/120003099-1885d100-bfde-11eb-91b7-ae3d856201e2.png)
![image](https://user-images.githubusercontent.com/52580190/120003183-2b98a100-bfde-11eb-9ae1-1d3e710bad27.png)
![image](https://user-images.githubusercontent.com/52580190/120003271-43702500-bfde-11eb-81bd-0be16e2de4a5.png)

2021-05-28 16:00 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  These are bots which are designed for interacting with humans in voice or text-based conversation. Chatbots simulate human conversation by responding to certain phrases or words with programmed res
not sure but to me ```that are``` seems better than ```which are```, what do you think?

2021-05-28 16:02 UTC, Rohitesh-Kumar-Jain approved these changes
Great work @nibble0101 and @chris-4444, I approve these changes.

2021-05-31 07:20 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  These are bots which are designed for interacting with humans in voice or text-based conversation. Chatbots simulate human conversation by responding to certain phrases or words with programmed res
Thanks for the review. I have changed it to `that`.

2021-06-02 12:45 UTC, proudofsimin reviewed
I actually feel the word terminology or glossary might be better than "concepts". How do you think?

2021-06-02 12:45 UTC, proudofsimin commented on docusaurus/docs/main-concepts-in-wechaty.md
> +This section covers the main Wechaty concepts you need to be familiar with to understand the other sections of the documentation. The other sections of the documentation assume you are familiar with
This section explain the main concepts in Wechaty. If you are new to communication software and its applications (?), start from this glossary to familiarize yourself with the terminology.

2021-06-03 08:08 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +This section covers the main Wechaty concepts you need to be familiar with to understand the other sections of the documentation. The other sections of the documentation assume you are familiar with
Added suggested changes in the commit below.

2021-06-04 15:40 UTC, proudofsimin approved these changes
Thank you :)

2021-07-10 10:23 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-11 17:44 UTC, proudofsimin commented
> hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in #1045
> 
> This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

Hi @chris-4444, Could you review and add the tag `ready to merge` afterwards? Thank you.

2021-07-12 13:15 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-12 17:28 UTC, lijiarui commented
> @chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

Hi @chris-4444 , as @Rohitesh-Kumar-Jain said, I will remove the `ready to merge tag`, after it got enough approval, feel free to add it again.

2021-07-14 10:55 UTC, chris-4444 approved these changes
LGTM.

2021-07-14 18:06 UTC, lijiarui requested changes

2021-07-14 18:06 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  Wechaty puppet provider refers to [RPA](#placeholder-link) module used for connecting Wechaty API to the corresponding Instant Messaging platform bot account. Each supported Instant Messaging syste
How about we change `Instant Messaging platform` to `Instant Messaging platform(such as WeChat, Whatsapp, and TikTok)`

We can also add some examples here:

For example, the Wechaty Puppet Provider who is supporting WeChat is named [wechaty-puppet-wechat](https://github.com/wechaty/wechaty-puppet-wechat), supporting Whatsapp is named [wechaty-puppet-whatsapp](https://github.com/wechaty/wechaty-puppet-whatsapp), and supporting Lark is named [wechaty-puppet-lark](https://github.com/wechaty/wechaty-puppet-lark).

2021-07-14 18:06 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +
We should add `puppet service` concept here:

```
**puppet service**

Wechaty Puppet Service is gRPC for Wechaty Puppet Provider.

For example, we can cloudify the Wechaty Puppet Provider wechaty-puppet-padlocal to a Wechaty Puppet Service by running our Wechaty Puppet Service Token Gateway.
```

2021-07-14 18:06 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  Puppet service providers refer to Wechaty developers who have developed puppets for the different Instant Messaging systems.
Maybe we should change to `  Puppet service providers refer to Wechaty developers who provide puppets cloud service for the different Instant Messaging systems.`

@huan I'm not very sure about this, how do you think of this?

2021-07-14 18:06 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  Wechaty Puppet is a standard for maintaining compatibility between Instant Messaging(IM) systems. Wechaty Puppet defines the universal Instant Messaging interface for compatibility between Wechaty
@huan It seems @nibble0101 combines the two concepts `Wechaty Puppet` and `Wechaty Puppet Abstract` as you mentioned in [Introducing Wechaty Puppet Service (Providers)](https://wechaty.js.org/2021/01/14/wechaty-puppet-service/). I feel combine them makes it more clear to understand, and I support combining them together.

What's your suggestion? Do you think we should remove the `wechaty puppet abstract` concept in the blog or add this concept here?

2021-07-14 18:06 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +- **Wechaty service token**
Please change this to `Wechaty Puppet Service Token`

2021-07-14 18:06 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  This is a unique key for authorizing Wechaty puppet service access. This token is issued by Puppet service providers.
I thinks it should change to 

```
This is a unique key for authorizing the service from Wechaty Puppet Service Provider access. This token is issued by Puppet service providers.

```

2021-07-21 11:17 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  Wechaty puppet provider refers to [RPA](#placeholder-link) module used for connecting Wechaty API to the corresponding Instant Messaging platform bot account. Each supported Instant Messaging syste
Added.

2021-07-21 11:22 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +
Added

2021-07-21 11:25 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  Puppet service providers refer to Wechaty developers who have developed puppets for the different Instant Messaging systems.
Added

2021-07-21 11:30 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +- **Wechaty service token**
Added

2021-07-21 11:33 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +  This is a unique key for authorizing Wechaty puppet service access. This token is issued by Puppet service providers.
Added

2021-07-29 13:52 UTC, lijiarui requested changes
Just one more tips then I will merge this PR!

2021-07-29 13:52 UTC, lijiarui commented on docusaurus/docs/main-concepts-in-wechaty.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I feel we may move this image or change a more related image here.

2021-07-30 16:40 UTC, nibble0101 commented on docusaurus/docs/main-concepts-in-wechaty.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Removed the logo.

2021-07-31 17:30 UTC, lijiarui approved these changes
LGTM

2021-08-02 10:01 UTC, merged