[Howto guides] Install wechaty
wechaty/docusaurus pull request #906
Opened 2021-05-29 09:30 UTC by vasvi-sood

The starter.md file contains a step by step guide on how to run the wechaty bot with the most famous messaging apps- Wechat and Whatsaap

2021-06-02 14:31 UTC, proudofsimin commented
I saw quite a lot of files but did not see the starter.md. Could you screenshot where we should review? Thank you.

2021-06-05 06:29 UTC, abhishek-iiit reviewed
Please review for the same

2021-06-05 11:39 UTC, Rohitesh-Kumar-Jain commented
> Could you screenshot where we should review? Thank you.

Yes pls add screenshots, ask for help if you need help in adding screenshots of the preview : )

2021-06-06 11:37 UTC, vasvi-sood commented
> > Could you screenshot where we should review? Thank you.
> 
> Yes pls add screenshots, ask for help if you need help in adding screenshots of the preview : )

![Screenshot ](https://user-images.githubusercontent.com/76619050/120922902-68088300-c6e9-11eb-94b1-ccf0cc29f03f.png)
This is the starter.md file. This can be reviewed at  docusaurus/docs/howto/starter.md.

2021-06-09 03:42 UTC, Rohitesh-Kumar-Jain commented
Hey @vasvi-sood and @abhishek-iiit, I would be glad if you may keep your commit history clean next time you raise a PR.

By clean commit history and a good screenshot, I mean something like this : #928 

Consider squashing commits, and try keeping the commit history easy to review.

2021-06-09 03:50 UTC, Rohitesh-Kumar-Jain commented
This PR neither have screenshot(s) nor clean commit history making it hard to review 😅 

I am confused, from where should I start reviewing 51 commits ?

2021-06-11 06:55 UTC, vasvi-sood commented
We'll add a related screenshot. We had some issue in pushing the branch to GitHub due to an error in package.json file. We had to make various commits for that. We'll take care of it from next time.

2021-06-11 07:11 UTC, vasvi-sood commented
![Screenshot from 2021-06-11 12-39-31](https://user-images.githubusercontent.com/76619050/121645885-57258c00-cab2-11eb-8bc8-9e0e7a26a7df.png)
![Screenshot from 2021-06-11 12-39-55](https://user-images.githubusercontent.com/76619050/121645899-5ab91300-cab2-11eb-8dfa-aad59fcc9fc7.png)
![Screenshot from 2021-06-11 12-40-17](https://user-images.githubusercontent.com/76619050/121645910-5db40380-cab2-11eb-97b5-62514248a289.png)

2021-06-11 07:12 UTC, vasvi-sood commented
This is how the starter.md file looks. Kindly review it @proudofsimin  and @Rohitesh-Kumar-Jain

2021-06-12 14:16 UTC, proudofsimin reviewed
Hi @vasvi-sood thank you for your work, but I am quite confused that I remembered last time we said that we will remove the section of "create the bot" since we have the installation section in tutorials. Why are we doing it again?

2021-06-12 14:16 UTC, proudofsimin commented on docusaurus/docs/howto/starter.md
> +title: 'Getting started with the bot on Wechat or Whatsaap'
correct the typo: whatsapp

2021-06-12 14:16 UTC, proudofsimin commented on docusaurus/docs/howto/starter.md
> +This will be a step by step guide on how to run the bot on most popular messaging apps, Whatsapp and Wechat:
How do you think if we change to:
In this section, you will learn how to run the bot on the popular messaging apps, including WhatsApp and Wechat.

2021-06-12 14:16 UTC, proudofsimin commented on docusaurus/docs/howto/starter.md
> +If you do not wish to run the bot locally, you can also use use Gitpod  or Google Cloud Shell. The steps can be found [here](../getting-started/quick-start)
please remove the duplicated *use*

2021-06-12 16:07 UTC, Rohitesh-Kumar-Jain commented on README.md
> +### How to Run Locally
Is this section finally in the documentation?

2021-06-12 16:25 UTC, Rohitesh-Kumar-Jain commented
Hi, 

I followed these steps but in the end maybe I am doing something wrong, I am unable to get ```dong``` for a ```ding```

2021-06-12 16:26 UTC, Rohitesh-Kumar-Jain commented
What is to be done after scanning the code

2021-06-13 07:25 UTC, vasvi-sood commented
You need to scan the code with whatsapp web, then ask a friend to send you a ding message. Please ensure ding is lowercase.

2021-06-13 09:07 UTC, Rohitesh-Kumar-Jain commented
> You need to scan the code with whatsapp web

Do I need to keep WhatsApp web open while scanning on the phone?

2021-06-14 08:45 UTC, Rohitesh-Kumar-Jain requested changes
Improper PR, pls see my comments on #940 

How to guides team your documentation quality is good but your team is having some serious issues with PRs and git 😕

2021-06-14 08:57 UTC, Rohitesh-Kumar-Jain commented
Try to fix the issues yourself first, and if you aren't able to fix these issues I will demonstrate how to work on two features simultaneously at the next meeting which will be nothing but the implementation of these steps https://gist.github.com/Rohitesh-Kumar-Jain/54e9f93bb6fad32ea2385016d1e2858d

One way to fix this error is :  

1) Switch to master

`git switch master`

2) make a new branch for this PR

`git switch -c branch-name`

3) copy paste work related to this PR (related to only this PR).

4) commit changes from that branch 

5) push changes 

` git push origin branch-name`

6) make a new PR, and close this one with reference to this one

7) congrats one PR solved 

8) now, switch to master

`git switch master`

repeat steps 1-8 for other faulty PRs (all of your PRs are faulty 😅)

Don't wait for mentors to close PRs, close yourself : )

PRs like this are unacceptable and are going to cause merge conflict as improperly rebased.

2021-06-14 10:21 UTC, abhishek-iiit commented
Hello @Rohitesh-Kumar-Jain, I did exactly the same way, as you suggested here as well as in your previous comment. But, all the commits that were one in the master branch show too in the created branch. PR #939 and #940 are done exactly in the same manner.

2021-06-14 10:56 UTC, Rohitesh-Kumar-Jain commented
>  But, all the commits that were one in the master branch show too in the created branch.

You aren't supposed to commit anything to the master branch, always remember never to commit directly or change anything in your master branch. You just need to keep your master branch in sync with the upstream that's it.

No where in my comments I mentioned you to make commits in your master branch.

2021-06-14 11:00 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit pls first backup all your documentation, I am having a fear that you might lose all your progress while making changes.

I see your master is 41 commits ahead the upstream, that needs to be corrected first.

2021-06-14 11:03 UTC, Rohitesh-Kumar-Jain commented
I am saying again backup all of your progress in some files first, before doing his manovuer 

## fix your current master branch

First of all, checkout to your master branch, and then checkout to a new PR branch based on that.

```
git switch master
git switch -c new-branch
```

Then push the new branch to your fork and create a new PR based on that branch (the PR will be identical to this one with the exception of the branch). When you've done that, we can reset your master branch.

```
git switch master
git fetch upstream master # fetch upstream/master without merging into local master
git reset --hard upstream/master # reset local master to upstream/master's state
git push --force origin master # force-update your fork's master to reflect upstream
```

2021-06-14 11:04 UTC, Rohitesh-Kumar-Jain commented
@huan and @lijiarui 

What do you think should be done in this situation ?

2021-06-14 17:50 UTC, abhishek-iiit commented
> @abhishek-iiit pls the first backup all your documentation, I am having a fear that you might lose all your progress while making changes.
Took the backup of the documentation. Thank you, for the help. Now, will make PR with suggested changes :)

2021-06-14 19:07 UTC, vasvi-sood commented
> Hi @vasvi-sood thank you for your work, but I am quite confused that I remembered last time we said that we will remove the section of "create the bot" since we have the installation section in tutorials. Why are we doing it again?

We thought that instaling wechaty meant the six line code to get started with wechaty. We wanted to create a guide for using wechaty with Whatsapp and Wechat separately because those are the most popular messaging apps. So it helps if developers find a separate section for that.

2021-06-14 19:08 UTC, vasvi-sood commented
> > You need to scan the code with whatsapp web
> 
> Do I need to keep WhatsApp web open while scanning on the phone?

No, you don't need to. Can you please share the error you are getting.

2021-06-14 19:10 UTC, vasvi-sood commented on docusaurus/docs/howto/starter.md
> +This will be a step by step guide on how to run the bot on most popular messaging apps, Whatsapp and Wechat:
> In this section, you will learn how to run the bot on the popular messaging apps, including WhatsApp and Wechat.
That would be better. I'll do the necessary changes

2021-06-15 02:52 UTC, Rohitesh-Kumar-Jain commented
> No, you don't need to. Can you please share the error you are getting.

I am not getting any error, after I scan the QR code, even my phone gets registered, but where to go from there? 

I got on 'dong's for 'ding's send to my phone

2021-06-15 02:59 UTC, Rohitesh-Kumar-Jain commented
I will suggest you to first focus on your existing PRs, correct them.
And don't forget to backup your work. (I am having a fear that you might lose your work while trying to fix git issues, and that will be a disaster, so pls the first backup and save everything you have documented so far, and then feel free to refactor your PRs)

2021-06-15 18:37 UTC, lijiarui commented
> @huan and @lijiarui

> What do you think should be done in this situation ?

@Rohitesh-Kumar-Jain It seems this PR commit too many files unrelated to this PR. It @vasvi-sood found it's hard to use git to correct them, a better way maybe close this PR, create a new branch and create a new PR.

2021-06-16 03:25 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood and @abhishek-iiit I have a really simple idea to fix your issues if you are finding git way hard to fix issues.

@abhishek-iiit create a fresh fork (don't delete this fork, as this fork anyways belongs to @vasvi-sood).

And then just follow the instructions I gave you to work on more than 1 features, and raise new PRS, and we will close these PRs.

2021-06-16 03:36 UTC, abhishek-iiit commented
Thank you for your guidance and support, we have done the same way to fork the project(doesn't delete the previous one) and will open PR with the new forked repo.

2021-06-24 12:25 UTC, shraddhavp commented
@abhishek-iiit  and @vasvi-sood  thanks for the PR it is actually helpful for installing Wechaty locally ,one thing I would like to suggest is ,as all the installation steps   mentioned are easy for Linux users but Windows users place difficulty to run some of the commands like sudo etc., can you please add a section for Windows user too? as it would be even more widely reachable

2021-06-24 17:30 UTC, proudofsimin commented
> @abhishek-iiit and @vasvi-sood thanks for the PR it is actually helpful for installing Wechaty locally ,one thing I would like to suggest is ,as all the installation steps mentioned are easy for Linux users but Windows users place difficulty to run some of the commands like sudo etc., can you please add a section for Windows user too? as it would be even more widely reachable

Hi @shraddhavp, 
Thank you for your great suggestion. This PR is accidentally overlap with #905 from the tutorial team, so it's preferred if you could notify in there.

2021-07-14 05:05 UTC, closed without merging