References - Puppet Services
wechaty/docusaurus pull request #907
Opened 2021-05-29 15:36 UTC by Soumi7

# References - Puppet Services

This PR will cover all updates in the puppet services subsection of references.

Related Issues :

#890

This is WIP (Work in progress). I Will request reviews once I am done with all my changes.

2021-06-01 06:54 UTC, Soumi7 commented
Screenshots :

![Screenshot from 2021-06-01 12-22-23](https://user-images.githubusercontent.com/51290447/120279465-18cee680-c2d4-11eb-92a7-2a1a4b70df69.png)

![Screenshot from 2021-06-01 12-23-30](https://user-images.githubusercontent.com/51290447/120279588-4025b380-c2d4-11eb-9ea2-0650d47a6dbe.png)

![Screenshot from 2021-06-01 12-23-39](https://user-images.githubusercontent.com/51290447/120279601-43b93a80-c2d4-11eb-89c8-163286d72ac7.png)

![Screenshot from 2021-06-01 12-18-33](https://user-images.githubusercontent.com/51290447/120279635-4d42a280-c2d4-11eb-90c9-e17dddb8f1c1.png)

2021-06-02 15:36 UTC, proudofsimin commented
It seems to me that you only screenshot part of the content. Could you screenshot all of them? and why don't we divided them into four PRs. It seems a lot of work!

2021-06-03 05:38 UTC, Soumi7 commented
@proudofsimin I have screenshotted the part I have made changes to. Let me know if you need ss of the parts which arent changed.

As the PRs are not getting merged regularly or weekly, and as they are interdependent, creating too many PRs will cause issues and slow down work. Hence I am making one PR and pushing commits to it.

@Rohitesh-Kumar-Jain @shraddhavp Can you also review please?

2021-06-03 05:48 UTC, Soumi7 commented
Screenshots in order :

![Screenshot from 2021-06-03 11-13-07](https://user-images.githubusercontent.com/51290447/120593401-11871480-c45d-11eb-8734-953a7677b144.png)

![Screenshot from 2021-06-03 11-13-20](https://user-images.githubusercontent.com/51290447/120593410-164bc880-c45d-11eb-99fa-6e2d0cb478e1.png)

![Screenshot from 2021-06-03 11-13-24](https://user-images.githubusercontent.com/51290447/120593423-1ba91300-c45d-11eb-8b96-828df12c17c8.png)

![Screenshot from 2021-06-03 11-13-28](https://user-images.githubusercontent.com/51290447/120593432-219ef400-c45d-11eb-8d55-72c81c7f380a.png)

![Screenshot from 2021-06-03 11-13-33](https://user-images.githubusercontent.com/51290447/120593443-25cb1180-c45d-11eb-81de-770984473bd1.png)

![Screenshot from 2021-06-03 11-13-37](https://user-images.githubusercontent.com/51290447/120593455-2a8fc580-c45d-11eb-97c1-931b3d70258e.png)

![Screenshot from 2021-06-03 11-13-41](https://user-images.githubusercontent.com/51290447/120593464-2fed1000-c45d-11eb-9274-3a8c84f77df1.png)

![Screenshot from 2021-06-03 11-13-47](https://user-images.githubusercontent.com/51290447/120593474-34192d80-c45d-11eb-91f2-7c8ce978c163.png)

![Screenshot from 2021-06-03 11-13-51](https://user-images.githubusercontent.com/51290447/120593510-4004ef80-c45d-11eb-9b9b-d9374fae139e.png)


![Screenshot from 2021-06-03 11-13-58](https://user-images.githubusercontent.com/51290447/120593522-44310d00-c45d-11eb-9e7f-2103fc1daca2.png)


![Screenshot from 2021-06-03 11-14-02](https://user-images.githubusercontent.com/51290447/120593537-485d2a80-c45d-11eb-8a45-f8e523967055.png)

![Screenshot from 2021-06-03 11-14-07](https://user-images.githubusercontent.com/51290447/120593554-4e530b80-c45d-11eb-9503-ab94a023f4d4.png)


![Screenshot from 2021-06-03 11-14-14](https://user-images.githubusercontent.com/51290447/120593566-5317bf80-c45d-11eb-9a86-af886683e030.png)

![Screenshot from 2021-06-03 11-14-17](https://user-images.githubusercontent.com/51290447/120593578-5743dd00-c45d-11eb-8148-870334b4f652.png)

![Screenshot from 2021-06-03 11-14-19](https://user-images.githubusercontent.com/51290447/120593590-5ad76400-c45d-11eb-95d8-7c253b5a91ad.png)

![Screenshot from 2021-06-03 11-14-22](https://user-images.githubusercontent.com/51290447/120593604-5dd25480-c45d-11eb-9d8a-a2bc09675c03.png)

![Screenshot from 2021-06-03 11-14-25](https://user-images.githubusercontent.com/51290447/120593619-61fe7200-c45d-11eb-8106-0afe60ca3bf0.png)

![Screenshot from 2021-06-03 11-14-31](https://user-images.githubusercontent.com/51290447/120593639-675bbc80-c45d-11eb-8b93-d7a39dab06c7.png)

![Screenshot from 2021-06-03 11-14-34](https://user-images.githubusercontent.com/51290447/120593651-6b87da00-c45d-11eb-9fc8-14aafbb36930.png)


![Screenshot from 2021-06-03 11-14-39](https://user-images.githubusercontent.com/51290447/120593682-793d5f80-c45d-11eb-99c2-8dfbb458b253.png)

2021-06-03 06:47 UTC, shraddhavp commented
@Soumi7  it looks fine to me

2021-06-13 09:05 UTC, proudofsimin requested changes
Please let me know if you have any question.

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/padlocal.md
Can you add one or two sentences to describe these two info? A list always needs an introduction.

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/padlocal.md
>  👉🏻 [pad-local.com](http://pad-local.com/) 👈🏻, get **FREE** trail token for **7** days.
Please replace the hand icon with a clear written instruction. (Like "go to ...)

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/padlocal.md
> +A preliminary study of Python-wechaty & wechaty-puppet-padlocal
I don't understand what is this sentence for?

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/padlocal.md
> +2. Newly registered Wechat account will not be able to log in- Fixed at 2021-03-10
If they are fixed, I guess we could remove them.

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/wxwork.md
> +```wechaty-puppet-wxwork``` is a **WeCom**(original WeChat Work) solution. Currently it supports following features:
[the] following features

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/wxwork.md
> +- Room events(join, leave, topic)
Add a space before the parenthesis.

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/wxwork.md
> +1. Change company of the account will cause unknown bug to wxwork [wechaty/puppet-services#100](https://github.com/wechaty/puppet-services/issues/100#issuecomment-803709545)
* Change company of the account will cause unknown bug to wxwork. See [wechaty/puppet-services#100](https://github.com/wechaty/puppet-services/issues/100#issuecomment-803709545).

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/wxwork.md
> +- Service Level Agreement (SLA): To-be-added
remove the draft.

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/wxwork.md
>  Read blogs with the `wxwork` tag at <https://wechaty.js.org/tags.html#wxwork>
~Read~ [Check out]

2021-06-13 09:05 UTC, proudofsimin commented on docusaurus/docs/puppet-services/overview.mdx
> +There can be several reasons for which you may need a ready-to-use Wechaty Puppet Service. Some of them can be :
Though it takes time, but I think you can do better on this part.

2021-07-12 14:23 UTC, Rohitesh-Kumar-Jain requested changes
As we have added a new test for forcing .webp as the image format, pls refactor all the images from .png to .webp

2021-07-14 16:32 UTC, proudofsimin commented
Hi @Soumi7, are you still taking care of this PR?

2021-07-15 08:21 UTC, Soumi7 commented
Yes, I will update starting 17 July.

On Wed, Jul 14, 2021 at 10:03 PM Simin Liao ***@***.***>
wrote:

> Hi @Soumi7 <https://github.com/Soumi7>, are you still taking care of this
> PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wechaty/wechaty.js.org/pull/907#issuecomment-880039476>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMHKCT2GET3K6CRCEXRK253TXW333ANCNFSM45YM5GCA>
> .
>

2021-07-15 16:47 UTC, Rohitesh-Kumar-Jain commented
> Yes, I will update starting 17 July.

You need to make a comeback soon, you have just raised 2 PRs in which you have pushed only 400 lines of documentation so far.

2021-07-17 07:01 UTC, Soumi7 commented on docusaurus/docs/puppet-services/padlocal.md
>  👉🏻 [pad-local.com](http://pad-local.com/) 👈🏻, get **FREE** trail token for **7** days.
Done

2021-07-17 07:02 UTC, Soumi7 commented on docusaurus/docs/puppet-services/padlocal.md
> +2. Newly registered Wechat account will not be able to log in- Fixed at 2021-03-10
Removed.

2021-07-17 07:02 UTC, Soumi7 commented on docusaurus/docs/puppet-services/wxwork.md
> +```wechaty-puppet-wxwork``` is a **WeCom**(original WeChat Work) solution. Currently it supports following features:
Changed.

2021-07-17 07:03 UTC, Soumi7 commented on docusaurus/docs/puppet-services/wxwork.md
> +- Room events(join, leave, topic)
Done.

2021-07-17 07:03 UTC, Soumi7 commented on docusaurus/docs/puppet-services/padlocal.md
> +A preliminary study of Python-wechaty & wechaty-puppet-padlocal
Removed.

2021-07-17 07:03 UTC, shraddhavp commented
this looks fine to me @Soumi7

2021-07-17 07:03 UTC, Soumi7 commented on docusaurus/docs/puppet-services/wxwork.md
> +1. Change company of the account will cause unknown bug to wxwork [wechaty/puppet-services#100](https://github.com/wechaty/puppet-services/issues/100#issuecomment-803709545)
Changed.

2021-07-17 07:03 UTC, Soumi7 commented on docusaurus/docs/puppet-services/wxwork.md
>  Read blogs with the `wxwork` tag at <https://wechaty.js.org/tags.html#wxwork>
Changed.

2021-07-17 07:04 UTC, Soumi7 commented on docusaurus/docs/puppet-services/overview.mdx
> +There can be several reasons for which you may need a ready-to-use Wechaty Puppet Service. Some of them can be :
Sure, have updated it. Thanks

2021-07-17 07:32 UTC, Soumi7 commented
@proudofsimin I have made changes as you suggested. Let me know if this is fine.

2021-07-23 16:29 UTC, proudofsimin commented on docusaurus/docs/puppet-services/faq.md
> +To be written.
What is it? Are you doing to do it later? Or please remove it to prevent our draft to go public.

2021-07-23 16:48 UTC, iamrajiv requested changes

2021-07-23 16:48 UTC, iamrajiv commented on docusaurus/docs/puppet-services/padlocal.md
> +- PC (Mac is used in this article)
I think the article link is missed.

2021-07-24 09:35 UTC, Soumi7 commented on docusaurus/docs/puppet-services/padlocal.md
> +- PC (Mac is used in this article)
I think referring to this page(instructions). I can replace it by "used here".

2021-07-24 09:38 UTC, Soumi7 commented on docusaurus/docs/puppet-services/padlocal.md
> +- PC (Mac is used in this article)
Ref : https://wechaty.js.org/2021/03/08/python-wechaty-and-wechaty-puppet-padlocal/

2021-07-24 09:39 UTC, Soumi7 commented on docusaurus/docs/puppet-services/faq.md
> +To be written.
Have changed it.

2021-09-07 17:43 UTC, huan requested changes
Thanks for the improvements!

Please follow my review, and also change all the image files to the directory name as same as the docs path as the following diff shows:

```diff
- docusaurus/static/img/docs/references/padlocal/qrcode.webp
+ docusaurus/static/img/docs/puppet-services/padlocal/qrcode.webp
```

2021-09-07 17:43 UTC, huan commented on docusaurus/docs/puppet-services/compatibility.md
> +title: 'Puppet Service Compatibility- Chinese'
When we have made an English version of our docs, we can just overwrite the Chinese version.

Please remove the `Chinese` in the title, and use the English version in this file.

2021-09-07 17:43 UTC, huan commented on docusaurus/docs/puppet-services/compatibility-english.md
> +sidebar_label:'Puppet Service: 'English'
We do not need this `compatibility-english.md` file. 

Overwrite the `compatibility.md` instead.

2021-09-08 04:47 UTC, shraddhavp commented
@Soumi7  please resolve the conflicts,then we are good to merge it

2021-09-09 07:05 UTC, shraddhavp requested changes
@Soumi7  please resolve the conflicts ,i see there is one file causing conflict

2021-09-09 11:18 UTC, huan commented
This is a HUGE PR, and it's very hard to review.

Could we split it into several small ones? It would be very appreciated if we can.

Thank you very much.

2021-09-09 12:24 UTC, Soumi7 commented
I can do that but it would require a lot of work. Almost everyone has already reviewed this PR.

2021-09-10 06:59 UTC, huan commented
> Almost everyone has already reviewed this PR.

Yes, you are correct that lots of us have reviewed the PR, but the PR still gets zero approval from the team, which I believe it's caused the high complexity of the PR.

2021-09-14 06:05 UTC, closed without merging

2021-09-18 08:55 UTC, Soumi7 commented
Hi Huan,

In most PRs, they require review from you on behalf of "wechaty/editors".
Without your review, it says :

"Merging blocked, code owner review required."

This happens even after three approvals from writers and volunteers.

That is why we need your review as well on the PRs as the setting is made
like that.


Please let me know if there is a workaround as well.

On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:

> Dear References Team,
>
> Appreciate the summary of all your Pull Requests to our docs site, it's a
> great job!
>
> As I said before:
>
> Form my option, the best way to process Pull Request should be to review,
>> request changes, approve and merge by the community because we trust you,
>> who are our GSoD'21 tech writers, are professional enough to make the final
>> merge decision based on the team effort.
>
>
> Please follow my suggestion as below:
>
> many trivial PRs, like small changes, corrections, blog posts, and PRs not
>> involving a review of their technical correctness, any technical writers
>> who have the write permission should merge these PRs after (+3) if they
>> believe it's ready to go, so that community can focus on important PRs, and
>> avoid stacking of PRs.
>
>
> Learn more from my issue: GSoD Project PR merge workflow #1257
> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>
> Please feel free to let me know if you have any questions, thank you very
> much!
>
> Best,
> *Huan* (李卓桓)
> ------------------------------
>
> *Linkedin <https://linkedin.com/in/zixia> | GitHub
> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
> <https://blog.zixia.net/>*
> Carpe Diem - If not us, who? if not now, when?
>
>
> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
> ***@***.***> wrote:
>
>> Hi Huan,
>> There are some PR from the references team, that need your review can you
>> please review the PRs listed below, then later we can work on creating our
>> last blog and video . Thanks in advance.
>>
>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>
>> --
> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6 lines of
> code.
>
> Talk to the community by joining our Gitter network
> https://gitter.im/wechaty/wechaty if you aren't already a member.
>
> - Website: https://wechaty.js.org
> - GitHub: https://github.com/wechaty
> ---
> You received this message because you are subscribed to the Google Groups
> "Wechaty" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to ***@***.***
> To view this discussion on the web visit
> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
> .
>

2021-09-18 09:04 UTC, Soumi7 commented
Hi Soumi,

Thanks for letting me know about this problem, I have thought that we have
no issues with the merging workflow because there's no one letting me know
that.

I have just removed the requirements for the review from @wechaty/editors
for our `docusaurus/*` PRs, please try again and let me know if it works
for you now.

Best,
*Huan* (李卓桓)
------------------------------

*Linkedin <https://linkedin.com/in/zixia> | GitHub
<https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
<https://blog.zixia.net/>*
Carpe Diem - If not us, who? if not now, when?


On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***> wrote:

> Hi Huan,
>
> In most PRs, they require review from you on behalf of "wechaty/editors".
> Without your review, it says :
>
> "Merging blocked, code owner review required."
>
> This happens even after three approvals from writers and volunteers.
>
> That is why we need your review as well on the PRs as the setting is made
> like that.
>
>
> Please let me know if there is a workaround as well.
>
> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>
>> Dear References Team,
>>
>> Appreciate the summary of all your Pull Requests to our docs site, it's a
>> great job!
>>
>> As I said before:
>>
>> Form my option, the best way to process Pull Request should be to review,
>>> request changes, approve and merge by the community because we trust you,
>>> who are our GSoD'21 tech writers, are professional enough to make the final
>>> merge decision based on the team effort.
>>
>>
>> Please follow my suggestion as below:
>>
>> many trivial PRs, like small changes, corrections, blog posts, and PRs
>>> not involving a review of their technical correctness, any technical
>>> writers who have the write permission should merge these PRs after (+3) if
>>> they believe it's ready to go, so that community can focus on important
>>> PRs, and avoid stacking of PRs.
>>
>>
>> Learn more from my issue: GSoD Project PR merge workflow #1257
>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>
>> Please feel free to let me know if you have any questions, thank you very
>> much!
>>
>> Best,
>> *Huan* (李卓桓)
>> ------------------------------
>>
>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>> <https://blog.zixia.net/>*
>> Carpe Diem - If not us, who? if not now, when?
>>
>>
>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>> ***@***.***> wrote:
>>
>>> Hi Huan,
>>> There are some PR from the references team, that need your review can
>>> you please review the PRs listed below, then later we can work on creating
>>> our last blog and video . Thanks in advance.
>>>
>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>
>>> --
>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6 lines
>> of code.
>>
>> Talk to the community by joining our Gitter network
>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>
>> - Website: https://wechaty.js.org
>> - GitHub: https://github.com/wechaty
>> ---
>> You received this message because you are subscribed to the Google Groups
>> "Wechaty" group.
>> To unsubscribe from this group and stop receiving emails from it, send an
>> email to ***@***.***
>> To view this discussion on the web visit
>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>> .
>>
>

2021-09-18 09:19 UTC, Soumi7 commented
Hi Huan,

Yes, now I am able to merge the PRs.

Thanks,
Soumi.

On Sat, Sep 18, 2021 at 2:34 PM Huan (李卓桓) ***@***.***> wrote:

> Hi Soumi,
>
> Thanks for letting me know about this problem, I have thought that we have
> no issues with the merging workflow because there's no one letting me know
> that.
>
> I have just removed the requirements for the review from @wechaty/editors
> for our `docusaurus/*` PRs, please try again and let me know if it works
> for you now.
>
> Best,
> *Huan* (李卓桓)
> ------------------------------
>
> *Linkedin <https://linkedin.com/in/zixia> | GitHub
> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
> <https://blog.zixia.net/>*
> Carpe Diem - If not us, who? if not now, when?
>
>
> On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***> wrote:
>
>> Hi Huan,
>>
>> In most PRs, they require review from you on behalf of "wechaty/editors".
>> Without your review, it says :
>>
>> "Merging blocked, code owner review required."
>>
>> This happens even after three approvals from writers and volunteers.
>>
>> That is why we need your review as well on the PRs as the setting is made
>> like that.
>>
>>
>> Please let me know if there is a workaround as well.
>>
>> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>>
>>> Dear References Team,
>>>
>>> Appreciate the summary of all your Pull Requests to our docs site, it's
>>> a great job!
>>>
>>> As I said before:
>>>
>>> Form my option, the best way to process Pull Request should be to
>>>> review, request changes, approve and merge by the community because we
>>>> trust you, who are our GSoD'21 tech writers, are professional enough to
>>>> make the final merge decision based on the team effort.
>>>
>>>
>>> Please follow my suggestion as below:
>>>
>>> many trivial PRs, like small changes, corrections, blog posts, and PRs
>>>> not involving a review of their technical correctness, any technical
>>>> writers who have the write permission should merge these PRs after (+3) if
>>>> they believe it's ready to go, so that community can focus on important
>>>> PRs, and avoid stacking of PRs.
>>>
>>>
>>> Learn more from my issue: GSoD Project PR merge workflow #1257
>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>
>>> Please feel free to let me know if you have any questions, thank you
>>> very much!
>>>
>>> Best,
>>> *Huan* (李卓桓)
>>> ------------------------------
>>>
>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>> <https://blog.zixia.net/>*
>>> Carpe Diem - If not us, who? if not now, when?
>>>
>>>
>>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>>> ***@***.***> wrote:
>>>
>>>> Hi Huan,
>>>> There are some PR from the references team, that need your review can
>>>> you please review the PRs listed below, then later we can work on creating
>>>> our last blog and video . Thanks in advance.
>>>>
>>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>>
>>>> --
>>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6 lines
>>> of code.
>>>
>>> Talk to the community by joining our Gitter network
>>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>>
>>> - Website: https://wechaty.js.org
>>> - GitHub: https://github.com/wechaty
>>> ---
>>> You received this message because you are subscribed to the Google
>>> Groups "Wechaty" group.
>>> To unsubscribe from this group and stop receiving emails from it, send
>>> an email to ***@***.***
>>> To view this discussion on the web visit
>>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>>> .
>>>
>>

2021-09-18 09:33 UTC, Soumi7 commented
Glad to know that!

Please help yourself to merge those PRs by following GSoD Project PR merge
workflow #1257 <https://github.com/wechaty/wechaty.js.org/issues/1257>

Cheers!

Best,
*Huan* (李卓桓)
------------------------------

*Linkedin <https://linkedin.com/in/zixia> | GitHub
<https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
<https://blog.zixia.net/>*
Carpe Diem - If not us, who? if not now, when?


On Sat, Sep 18, 2021 at 5:19 PM Soumi7 ***@***.***> wrote:

> Hi Huan,
>
> Yes, now I am able to merge the PRs.
>
> Thanks,
> Soumi.
>
> On Sat, Sep 18, 2021 at 2:34 PM Huan (李卓桓) ***@***.***> wrote:
>
>> Hi Soumi,
>>
>> Thanks for letting me know about this problem, I have thought that we
>> have no issues with the merging workflow because there's no one letting me
>> know that.
>>
>> I have just removed the requirements for the review from @wechaty/editors
>> for our `docusaurus/*` PRs, please try again and let me know if it works
>> for you now.
>>
>> Best,
>> *Huan* (李卓桓)
>> ------------------------------
>>
>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>> <https://blog.zixia.net/>*
>> Carpe Diem - If not us, who? if not now, when?
>>
>>
>> On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***> wrote:
>>
>>> Hi Huan,
>>>
>>> In most PRs, they require review from you on behalf of
>>> "wechaty/editors". Without your review, it says :
>>>
>>> "Merging blocked, code owner review required."
>>>
>>> This happens even after three approvals from writers and volunteers.
>>>
>>> That is why we need your review as well on the PRs as the setting is
>>> made like that.
>>>
>>>
>>> Please let me know if there is a workaround as well.
>>>
>>> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>>>
>>>> Dear References Team,
>>>>
>>>> Appreciate the summary of all your Pull Requests to our docs site, it's
>>>> a great job!
>>>>
>>>> As I said before:
>>>>
>>>> Form my option, the best way to process Pull Request should be to
>>>>> review, request changes, approve and merge by the community because we
>>>>> trust you, who are our GSoD'21 tech writers, are professional enough to
>>>>> make the final merge decision based on the team effort.
>>>>
>>>>
>>>> Please follow my suggestion as below:
>>>>
>>>> many trivial PRs, like small changes, corrections, blog posts, and PRs
>>>>> not involving a review of their technical correctness, any technical
>>>>> writers who have the write permission should merge these PRs after (+3) if
>>>>> they believe it's ready to go, so that community can focus on important
>>>>> PRs, and avoid stacking of PRs.
>>>>
>>>>
>>>> Learn more from my issue: GSoD Project PR merge workflow #1257
>>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>>
>>>> Please feel free to let me know if you have any questions, thank you
>>>> very much!
>>>>
>>>> Best,
>>>> *Huan* (李卓桓)
>>>> ------------------------------
>>>>
>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>> <https://blog.zixia.net/>*
>>>> Carpe Diem - If not us, who? if not now, when?
>>>>
>>>>
>>>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>>>> ***@***.***> wrote:
>>>>
>>>>> Hi Huan,
>>>>> There are some PR from the references team, that need your review can
>>>>> you please review the PRs listed below, then later we can work on creating
>>>>> our last blog and video . Thanks in advance.
>>>>>
>>>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>>>
>>>>> --
>>>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6 lines
>>>> of code.
>>>>
>>>> Talk to the community by joining our Gitter network
>>>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>>>
>>>> - Website: https://wechaty.js.org
>>>> - GitHub: https://github.com/wechaty
>>>> ---
>>>> You received this message because you are subscribed to the Google
>>>> Groups "Wechaty" group.
>>>> To unsubscribe from this group and stop receiving emails from it, send
>>>> an email to ***@***.***
>>>> To view this discussion on the web visit
>>>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>>>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>>>> .
>>>>
>>>

2021-09-18 10:21 UTC, Soumi7 commented
Hi Huan,

One more point I wanted to add here :

The reviewer who requests changes on a PR also has to approve the PR after
the requested changes are made.

Otherwise, it cannot be merged even though other people approve it.

For example, this PR : Puppet services overview by Soumi7 · Pull Request
#1277 · wechaty/wechaty.js.org (github.com)
<https://github.com/wechaty/wechaty.js.org/pull/1277>

Even though it has three approvals, it cannot be merged until you approve
it, as the changes were requested by you.

Thanks,
Soumi.


On Sat, Sep 18, 2021 at 3:03 PM Huan (李卓桓) ***@***.***> wrote:

> Glad to know that!
>
> Please help yourself to merge those PRs by following GSoD Project PR
> merge workflow #1257
> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>
> Cheers!
>
> Best,
> *Huan* (李卓桓)
> ------------------------------
>
> *Linkedin <https://linkedin.com/in/zixia> | GitHub
> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
> <https://blog.zixia.net/>*
> Carpe Diem - If not us, who? if not now, when?
>
>
> On Sat, Sep 18, 2021 at 5:19 PM Soumi7 ***@***.***> wrote:
>
>> Hi Huan,
>>
>> Yes, now I am able to merge the PRs.
>>
>> Thanks,
>> Soumi.
>>
>> On Sat, Sep 18, 2021 at 2:34 PM Huan (李卓桓) ***@***.***> wrote:
>>
>>> Hi Soumi,
>>>
>>> Thanks for letting me know about this problem, I have thought that we
>>> have no issues with the merging workflow because there's no one letting me
>>> know that.
>>>
>>> I have just removed the requirements for the review
>>> from @wechaty/editors for our `docusaurus/*` PRs, please try again and let
>>> me know if it works for you now.
>>>
>>> Best,
>>> *Huan* (李卓桓)
>>> ------------------------------
>>>
>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>> <https://blog.zixia.net/>*
>>> Carpe Diem - If not us, who? if not now, when?
>>>
>>>
>>> On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***> wrote:
>>>
>>>> Hi Huan,
>>>>
>>>> In most PRs, they require review from you on behalf of
>>>> "wechaty/editors". Without your review, it says :
>>>>
>>>> "Merging blocked, code owner review required."
>>>>
>>>> This happens even after three approvals from writers and volunteers.
>>>>
>>>> That is why we need your review as well on the PRs as the setting is
>>>> made like that.
>>>>
>>>>
>>>> Please let me know if there is a workaround as well.
>>>>
>>>> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>>>>
>>>>> Dear References Team,
>>>>>
>>>>> Appreciate the summary of all your Pull Requests to our docs site,
>>>>> it's a great job!
>>>>>
>>>>> As I said before:
>>>>>
>>>>> Form my option, the best way to process Pull Request should be to
>>>>>> review, request changes, approve and merge by the community because we
>>>>>> trust you, who are our GSoD'21 tech writers, are professional enough to
>>>>>> make the final merge decision based on the team effort.
>>>>>
>>>>>
>>>>> Please follow my suggestion as below:
>>>>>
>>>>> many trivial PRs, like small changes, corrections, blog posts, and PRs
>>>>>> not involving a review of their technical correctness, any technical
>>>>>> writers who have the write permission should merge these PRs after (+3) if
>>>>>> they believe it's ready to go, so that community can focus on important
>>>>>> PRs, and avoid stacking of PRs.
>>>>>
>>>>>
>>>>> Learn more from my issue: GSoD Project PR merge workflow #1257
>>>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>>>
>>>>> Please feel free to let me know if you have any questions, thank you
>>>>> very much!
>>>>>
>>>>> Best,
>>>>> *Huan* (李卓桓)
>>>>> ------------------------------
>>>>>
>>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>>> <https://blog.zixia.net/>*
>>>>> Carpe Diem - If not us, who? if not now, when?
>>>>>
>>>>>
>>>>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>>>>> ***@***.***> wrote:
>>>>>
>>>>>> Hi Huan,
>>>>>> There are some PR from the references team, that need your review can
>>>>>> you please review the PRs listed below, then later we can work on creating
>>>>>> our last blog and video . Thanks in advance.
>>>>>>
>>>>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>>>>
>>>>>> --
>>>>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6
>>>>> lines of code.
>>>>>
>>>>> Talk to the community by joining our Gitter network
>>>>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>>>>
>>>>> - Website: https://wechaty.js.org
>>>>> - GitHub: https://github.com/wechaty
>>>>> ---
>>>>> You received this message because you are subscribed to the Google
>>>>> Groups "Wechaty" group.
>>>>> To unsubscribe from this group and stop receiving emails from it, send
>>>>> an email to ***@***.***
>>>>> To view this discussion on the web visit
>>>>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>>>>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>>>>> .
>>>>>
>>>>

2021-09-18 10:31 UTC, Soumi7 commented
Of course. Please ping the reviewer when your PR has been updated as
required.

I have just approved the #1277 with a modification requirement.

Thanks.

Best,
*Huan* (李卓桓)
------------------------------

*Linkedin <https://linkedin.com/in/zixia> | GitHub
<https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
<https://blog.zixia.net/>*
Carpe Diem - If not us, who? if not now, when?


On Sat, Sep 18, 2021 at 6:21 PM Soumi7 ***@***.***> wrote:

> Hi Huan,
>
> One more point I wanted to add here :
>
> The reviewer who requests changes on a PR also has to approve the PR after
> the requested changes are made.
>
> Otherwise, it cannot be merged even though other people approve it.
>
> For example, this PR : Puppet services overview by Soumi7 · Pull Request
> #1277 · wechaty/wechaty.js.org (github.com)
> <https://github.com/wechaty/wechaty.js.org/pull/1277>
>
> Even though it has three approvals, it cannot be merged until you approve
> it, as the changes were requested by you.
>
> Thanks,
> Soumi.
>
>
> On Sat, Sep 18, 2021 at 3:03 PM Huan (李卓桓) ***@***.***> wrote:
>
>> Glad to know that!
>>
>> Please help yourself to merge those PRs by following GSoD Project PR
>> merge workflow #1257
>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>
>> Cheers!
>>
>> Best,
>> *Huan* (李卓桓)
>> ------------------------------
>>
>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>> <https://blog.zixia.net/>*
>> Carpe Diem - If not us, who? if not now, when?
>>
>>
>> On Sat, Sep 18, 2021 at 5:19 PM Soumi7 ***@***.***> wrote:
>>
>>> Hi Huan,
>>>
>>> Yes, now I am able to merge the PRs.
>>>
>>> Thanks,
>>> Soumi.
>>>
>>> On Sat, Sep 18, 2021 at 2:34 PM Huan (李卓桓) ***@***.***> wrote:
>>>
>>>> Hi Soumi,
>>>>
>>>> Thanks for letting me know about this problem, I have thought that we
>>>> have no issues with the merging workflow because there's no one letting me
>>>> know that.
>>>>
>>>> I have just removed the requirements for the review
>>>> from @wechaty/editors for our `docusaurus/*` PRs, please try again and let
>>>> me know if it works for you now.
>>>>
>>>> Best,
>>>> *Huan* (李卓桓)
>>>> ------------------------------
>>>>
>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>> <https://blog.zixia.net/>*
>>>> Carpe Diem - If not us, who? if not now, when?
>>>>
>>>>
>>>> On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***>
>>>> wrote:
>>>>
>>>>> Hi Huan,
>>>>>
>>>>> In most PRs, they require review from you on behalf of
>>>>> "wechaty/editors". Without your review, it says :
>>>>>
>>>>> "Merging blocked, code owner review required."
>>>>>
>>>>> This happens even after three approvals from writers and volunteers.
>>>>>
>>>>> That is why we need your review as well on the PRs as the setting is
>>>>> made like that.
>>>>>
>>>>>
>>>>> Please let me know if there is a workaround as well.
>>>>>
>>>>> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>>>>>
>>>>>> Dear References Team,
>>>>>>
>>>>>> Appreciate the summary of all your Pull Requests to our docs site,
>>>>>> it's a great job!
>>>>>>
>>>>>> As I said before:
>>>>>>
>>>>>> Form my option, the best way to process Pull Request should be to
>>>>>>> review, request changes, approve and merge by the community because we
>>>>>>> trust you, who are our GSoD'21 tech writers, are professional enough to
>>>>>>> make the final merge decision based on the team effort.
>>>>>>
>>>>>>
>>>>>> Please follow my suggestion as below:
>>>>>>
>>>>>> many trivial PRs, like small changes, corrections, blog posts, and
>>>>>>> PRs not involving a review of their technical correctness, any technical
>>>>>>> writers who have the write permission should merge these PRs after (+3) if
>>>>>>> they believe it's ready to go, so that community can focus on important
>>>>>>> PRs, and avoid stacking of PRs.
>>>>>>
>>>>>>
>>>>>> Learn more from my issue: GSoD Project PR merge workflow #1257
>>>>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>>>>
>>>>>> Please feel free to let me know if you have any questions, thank you
>>>>>> very much!
>>>>>>
>>>>>> Best,
>>>>>> *Huan* (李卓桓)
>>>>>> ------------------------------
>>>>>>
>>>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>>>> <https://blog.zixia.net/>*
>>>>>> Carpe Diem - If not us, who? if not now, when?
>>>>>>
>>>>>>
>>>>>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>>>>>> ***@***.***> wrote:
>>>>>>
>>>>>>> Hi Huan,
>>>>>>> There are some PR from the references team, that need your review
>>>>>>> can you please review the PRs listed below, then later we can work on
>>>>>>> creating our last blog and video . Thanks in advance.
>>>>>>>
>>>>>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>>>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>>>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>>>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>>>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>>>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>>>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>>>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>>>>>
>>>>>>> --
>>>>>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6
>>>>>> lines of code.
>>>>>>
>>>>>> Talk to the community by joining our Gitter network
>>>>>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>>>>>
>>>>>> - Website: https://wechaty.js.org
>>>>>> - GitHub: https://github.com/wechaty
>>>>>> ---
>>>>>> You received this message because you are subscribed to the Google
>>>>>> Groups "Wechaty" group.
>>>>>> To unsubscribe from this group and stop receiving emails from it,
>>>>>> send an email to ***@***.***
>>>>>> To view this discussion on the web visit
>>>>>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>>>>>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>>>>>> .
>>>>>>
>>>>>

2021-09-18 10:39 UTC, Soumi7 commented
Great, thanks!

On Sat, Sep 18, 2021 at 4:01 PM Huan (李卓桓) ***@***.***> wrote:

> Of course. Please ping the reviewer when your PR has been updated as
> required.
>
> I have just approved the #1277 with a modification requirement.
>
> Thanks.
>
> Best,
> *Huan* (李卓桓)
> ------------------------------
>
> *Linkedin <https://linkedin.com/in/zixia> | GitHub
> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
> <https://blog.zixia.net/>*
> Carpe Diem - If not us, who? if not now, when?
>
>
> On Sat, Sep 18, 2021 at 6:21 PM Soumi7 ***@***.***> wrote:
>
>> Hi Huan,
>>
>> One more point I wanted to add here :
>>
>> The reviewer who requests changes on a PR also has to approve the PR
>> after the requested changes are made.
>>
>> Otherwise, it cannot be merged even though other people approve it.
>>
>> For example, this PR : Puppet services overview by Soumi7 · Pull Request
>> #1277 · wechaty/wechaty.js.org (github.com)
>> <https://github.com/wechaty/wechaty.js.org/pull/1277>
>>
>> Even though it has three approvals, it cannot be merged until you approve
>> it, as the changes were requested by you.
>>
>> Thanks,
>> Soumi.
>>
>>
>> On Sat, Sep 18, 2021 at 3:03 PM Huan (李卓桓) ***@***.***> wrote:
>>
>>> Glad to know that!
>>>
>>> Please help yourself to merge those PRs by following GSoD Project PR
>>> merge workflow #1257
>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>
>>> Cheers!
>>>
>>> Best,
>>> *Huan* (李卓桓)
>>> ------------------------------
>>>
>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>> <https://blog.zixia.net/>*
>>> Carpe Diem - If not us, who? if not now, when?
>>>
>>>
>>> On Sat, Sep 18, 2021 at 5:19 PM Soumi7 ***@***.***> wrote:
>>>
>>>> Hi Huan,
>>>>
>>>> Yes, now I am able to merge the PRs.
>>>>
>>>> Thanks,
>>>> Soumi.
>>>>
>>>> On Sat, Sep 18, 2021 at 2:34 PM Huan (李卓桓) ***@***.***> wrote:
>>>>
>>>>> Hi Soumi,
>>>>>
>>>>> Thanks for letting me know about this problem, I have thought that we
>>>>> have no issues with the merging workflow because there's no one letting me
>>>>> know that.
>>>>>
>>>>> I have just removed the requirements for the review
>>>>> from @wechaty/editors for our `docusaurus/*` PRs, please try again and let
>>>>> me know if it works for you now.
>>>>>
>>>>> Best,
>>>>> *Huan* (李卓桓)
>>>>> ------------------------------
>>>>>
>>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>>> <https://blog.zixia.net/>*
>>>>> Carpe Diem - If not us, who? if not now, when?
>>>>>
>>>>>
>>>>> On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***>
>>>>> wrote:
>>>>>
>>>>>> Hi Huan,
>>>>>>
>>>>>> In most PRs, they require review from you on behalf of
>>>>>> "wechaty/editors". Without your review, it says :
>>>>>>
>>>>>> "Merging blocked, code owner review required."
>>>>>>
>>>>>> This happens even after three approvals from writers and volunteers.
>>>>>>
>>>>>> That is why we need your review as well on the PRs as the setting is
>>>>>> made like that.
>>>>>>
>>>>>>
>>>>>> Please let me know if there is a workaround as well.
>>>>>>
>>>>>> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>>>>>>
>>>>>>> Dear References Team,
>>>>>>>
>>>>>>> Appreciate the summary of all your Pull Requests to our docs site,
>>>>>>> it's a great job!
>>>>>>>
>>>>>>> As I said before:
>>>>>>>
>>>>>>> Form my option, the best way to process Pull Request should be to
>>>>>>>> review, request changes, approve and merge by the community because we
>>>>>>>> trust you, who are our GSoD'21 tech writers, are professional enough to
>>>>>>>> make the final merge decision based on the team effort.
>>>>>>>
>>>>>>>
>>>>>>> Please follow my suggestion as below:
>>>>>>>
>>>>>>> many trivial PRs, like small changes, corrections, blog posts, and
>>>>>>>> PRs not involving a review of their technical correctness, any technical
>>>>>>>> writers who have the write permission should merge these PRs after (+3) if
>>>>>>>> they believe it's ready to go, so that community can focus on important
>>>>>>>> PRs, and avoid stacking of PRs.
>>>>>>>
>>>>>>>
>>>>>>> Learn more from my issue: GSoD Project PR merge workflow #1257
>>>>>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>>>>>
>>>>>>> Please feel free to let me know if you have any questions, thank you
>>>>>>> very much!
>>>>>>>
>>>>>>> Best,
>>>>>>> *Huan* (李卓桓)
>>>>>>> ------------------------------
>>>>>>>
>>>>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>>>>> <https://blog.zixia.net/>*
>>>>>>> Carpe Diem - If not us, who? if not now, when?
>>>>>>>
>>>>>>>
>>>>>>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>>>>>>> ***@***.***> wrote:
>>>>>>>
>>>>>>>> Hi Huan,
>>>>>>>> There are some PR from the references team, that need your review
>>>>>>>> can you please review the PRs listed below, then later we can work on
>>>>>>>> creating our last blog and video . Thanks in advance.
>>>>>>>>
>>>>>>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>>>>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>>>>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>>>>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>>>>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>>>>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>>>>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>>>>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>>>>>>
>>>>>>>> --
>>>>>>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6
>>>>>>> lines of code.
>>>>>>>
>>>>>>> Talk to the community by joining our Gitter network
>>>>>>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>>>>>>
>>>>>>> - Website: https://wechaty.js.org
>>>>>>> - GitHub: https://github.com/wechaty
>>>>>>> ---
>>>>>>> You received this message because you are subscribed to the Google
>>>>>>> Groups "Wechaty" group.
>>>>>>> To unsubscribe from this group and stop receiving emails from it,
>>>>>>> send an email to ***@***.***
>>>>>>> To view this discussion on the web visit
>>>>>>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>>>>>>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>>>>>>> .
>>>>>>>
>>>>>>

2021-09-18 10:50 UTC, Soumi7 commented
You are welcome!

Best,
*Huan* (李卓桓)
------------------------------

*Linkedin <https://linkedin.com/in/zixia> | GitHub
<https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
<https://blog.zixia.net/>*
Carpe Diem - If not us, who? if not now, when?


On Sat, Sep 18, 2021 at 6:39 PM Soumi7 ***@***.***> wrote:

> Great, thanks!
>
> On Sat, Sep 18, 2021 at 4:01 PM Huan (李卓桓) ***@***.***> wrote:
>
>> Of course. Please ping the reviewer when your PR has been updated as
>> required.
>>
>> I have just approved the #1277 with a modification requirement.
>>
>> Thanks.
>>
>> Best,
>> *Huan* (李卓桓)
>> ------------------------------
>>
>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>> <https://blog.zixia.net/>*
>> Carpe Diem - If not us, who? if not now, when?
>>
>>
>> On Sat, Sep 18, 2021 at 6:21 PM Soumi7 ***@***.***> wrote:
>>
>>> Hi Huan,
>>>
>>> One more point I wanted to add here :
>>>
>>> The reviewer who requests changes on a PR also has to approve the PR
>>> after the requested changes are made.
>>>
>>> Otherwise, it cannot be merged even though other people approve it.
>>>
>>> For example, this PR : Puppet services overview by Soumi7 · Pull
>>> Request #1277 · wechaty/wechaty.js.org (github.com)
>>> <https://github.com/wechaty/wechaty.js.org/pull/1277>
>>>
>>> Even though it has three approvals, it cannot be merged until you
>>> approve it, as the changes were requested by you.
>>>
>>> Thanks,
>>> Soumi.
>>>
>>>
>>> On Sat, Sep 18, 2021 at 3:03 PM Huan (李卓桓) ***@***.***> wrote:
>>>
>>>> Glad to know that!
>>>>
>>>> Please help yourself to merge those PRs by following GSoD Project PR
>>>> merge workflow #1257
>>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>>
>>>> Cheers!
>>>>
>>>> Best,
>>>> *Huan* (李卓桓)
>>>> ------------------------------
>>>>
>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>> <https://blog.zixia.net/>*
>>>> Carpe Diem - If not us, who? if not now, when?
>>>>
>>>>
>>>> On Sat, Sep 18, 2021 at 5:19 PM Soumi7 ***@***.***>
>>>> wrote:
>>>>
>>>>> Hi Huan,
>>>>>
>>>>> Yes, now I am able to merge the PRs.
>>>>>
>>>>> Thanks,
>>>>> Soumi.
>>>>>
>>>>> On Sat, Sep 18, 2021 at 2:34 PM Huan (李卓桓) ***@***.***> wrote:
>>>>>
>>>>>> Hi Soumi,
>>>>>>
>>>>>> Thanks for letting me know about this problem, I have thought that we
>>>>>> have no issues with the merging workflow because there's no one letting me
>>>>>> know that.
>>>>>>
>>>>>> I have just removed the requirements for the review
>>>>>> from @wechaty/editors for our `docusaurus/*` PRs, please try again and let
>>>>>> me know if it works for you now.
>>>>>>
>>>>>> Best,
>>>>>> *Huan* (李卓桓)
>>>>>> ------------------------------
>>>>>>
>>>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>>>> <https://blog.zixia.net/>*
>>>>>> Carpe Diem - If not us, who? if not now, when?
>>>>>>
>>>>>>
>>>>>> On Sat, Sep 18, 2021 at 4:55 PM Soumi7 ***@***.***>
>>>>>> wrote:
>>>>>>
>>>>>>> Hi Huan,
>>>>>>>
>>>>>>> In most PRs, they require review from you on behalf of
>>>>>>> "wechaty/editors". Without your review, it says :
>>>>>>>
>>>>>>> "Merging blocked, code owner review required."
>>>>>>>
>>>>>>> This happens even after three approvals from writers and volunteers.
>>>>>>>
>>>>>>> That is why we need your review as well on the PRs as the setting is
>>>>>>> made like that.
>>>>>>>
>>>>>>>
>>>>>>> Please let me know if there is a workaround as well.
>>>>>>>
>>>>>>> On Sat, Sep 18, 2021 at 2:19 PM Huan (李卓桓) ***@***.***> wrote:
>>>>>>>
>>>>>>>> Dear References Team,
>>>>>>>>
>>>>>>>> Appreciate the summary of all your Pull Requests to our docs site,
>>>>>>>> it's a great job!
>>>>>>>>
>>>>>>>> As I said before:
>>>>>>>>
>>>>>>>> Form my option, the best way to process Pull Request should be to
>>>>>>>>> review, request changes, approve and merge by the community because we
>>>>>>>>> trust you, who are our GSoD'21 tech writers, are professional enough to
>>>>>>>>> make the final merge decision based on the team effort.
>>>>>>>>
>>>>>>>>
>>>>>>>> Please follow my suggestion as below:
>>>>>>>>
>>>>>>>> many trivial PRs, like small changes, corrections, blog posts, and
>>>>>>>>> PRs not involving a review of their technical correctness, any technical
>>>>>>>>> writers who have the write permission should merge these PRs after (+3) if
>>>>>>>>> they believe it's ready to go, so that community can focus on important
>>>>>>>>> PRs, and avoid stacking of PRs.
>>>>>>>>
>>>>>>>>
>>>>>>>> Learn more from my issue: GSoD Project PR merge workflow #1257
>>>>>>>> <https://github.com/wechaty/wechaty.js.org/issues/1257>
>>>>>>>>
>>>>>>>> Please feel free to let me know if you have any questions, thank
>>>>>>>> you very much!
>>>>>>>>
>>>>>>>> Best,
>>>>>>>> *Huan* (李卓桓)
>>>>>>>> ------------------------------
>>>>>>>>
>>>>>>>> *Linkedin <https://linkedin.com/in/zixia> | GitHub
>>>>>>>> <https://github.com/huan> | Twitter <https://twitter.com/huan_us> | Blog
>>>>>>>> <https://blog.zixia.net/>*
>>>>>>>> Carpe Diem - If not us, who? if not now, when?
>>>>>>>>
>>>>>>>>
>>>>>>>> On Sat, Sep 18, 2021 at 12:28 PM 1JS16CS094 _Shraddha prasad <
>>>>>>>> ***@***.***> wrote:
>>>>>>>>
>>>>>>>>> Hi Huan,
>>>>>>>>> There are some PR from the references team, that need your review
>>>>>>>>> can you please review the PRs listed below, then later we can work on
>>>>>>>>> creating our last blog and video . Thanks in advance.
>>>>>>>>>
>>>>>>>>>    1. https://github.com/wechaty/wechaty.js.org/pull/1294
>>>>>>>>>    2. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>>>>    3. https://github.com/wechaty/wechaty.js.org/pull/1290
>>>>>>>>>    4. https://github.com/wechaty/wechaty.js.org/pull/1286
>>>>>>>>>    5. https://github.com/wechaty/wechaty.js.org/pull/1285
>>>>>>>>>    6. https://github.com/wechaty/wechaty.js.org/pull/1284
>>>>>>>>>    7. https://github.com/wechaty/wechaty.js.org/pull/1283
>>>>>>>>>    8. https://github.com/wechaty/wechaty.js.org/pull/1278
>>>>>>>>>    9. https://github.com/wechaty/wechaty.js.org/pull/1277
>>>>>>>>>    10. https://github.com/wechaty/wechaty.js.org/pull/1273
>>>>>>>>>
>>>>>>>>> --
>>>>>>>> Conversational RPA SDK for building WeChat/Whatsapp chatbots in 6
>>>>>>>> lines of code.
>>>>>>>>
>>>>>>>> Talk to the community by joining our Gitter network
>>>>>>>> https://gitter.im/wechaty/wechaty if you aren't already a member.
>>>>>>>>
>>>>>>>> - Website: https://wechaty.js.org
>>>>>>>> - GitHub: https://github.com/wechaty
>>>>>>>> ---
>>>>>>>> You received this message because you are subscribed to the Google
>>>>>>>> Groups "Wechaty" group.
>>>>>>>> To unsubscribe from this group and stop receiving emails from it,
>>>>>>>> send an email to ***@***.***
>>>>>>>> To view this discussion on the web visit
>>>>>>>> https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com
>>>>>>>> <https://groups.google.com/d/msgid/wechaty/CAE5_cz0wgUyVzLEJj2zWJ2eBLHGTgjwUkLK4y5oJJT%3D2yOjhwg%40mail.gmail.com?utm_medium=email&utm_source=footer>
>>>>>>>> .
>>>>>>>>
>>>>>>>