Overview subsection of the explanation section
wechaty/docusaurus pull request #915
Opened 2021-06-01 08:44 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Overview of the explanation section |  Chris Estepa |

This  is **Overview** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/120294064-7f510600-c2ce-11eb-809f-80c26526b21b.png)
![image](https://user-images.githubusercontent.com/52580190/120294146-968ff380-c2ce-11eb-8f3a-a0ccf1798c0a.png)
![image](https://user-images.githubusercontent.com/52580190/120294225-aad3f080-c2ce-11eb-893e-4d0a27ff10c5.png)

2021-06-02 09:31 UTC, Rohitesh-Kumar-Jain approved these changes
Great work @nibble0101 and @chris-4444 : )

2021-06-03 16:19 UTC, proudofsimin approved these changes
Thank you!

2021-07-10 10:24 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-12 13:13 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-13 14:12 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 19:09 UTC, lijiarui requested changes
It seems explanation overview is talking about chatbot not Wechaty.

I think we should add more Wechaty part instead of chatbot part.

2021-07-18 19:09 UTC, lijiarui commented on docusaurus/docs/explainations/overview.mdx
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I feel like the wechaty logo appears too much in the doc, how about we change a more related image to the explanation part if you think we need add image here.

2021-07-18 19:09 UTC, lijiarui commented on docusaurus/docs/explainations/overview.mdx
> +
I'm not sure if we need to add a life cycle here. 

If you are saying wechaty lifecycle, it is necessary, but if you are saying chatbot lifecycle, it is not that related to wechaty doc.

2021-07-21 12:36 UTC, nibble0101 commented on docusaurus/docs/explainations/overview.mdx
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Removed logo

2021-07-21 12:37 UTC, nibble0101 commented on docusaurus/docs/explainations/overview.mdx
> +
Can you clarify on this? Should we remove it from the explanation section completely?

2021-07-22 14:05 UTC, chris-4444 commented
@lijiarui  May I know what do you mean by adding more about the Wechaty part? Is it pertaining to Wechaty as an organization itself? If yes, it's already covered in [**What is Wechaty**](https://github.com/wechaty/wechaty.js.org/pull/871) and [**What can you do with Wechaty**.](https://github.com/wechaty/wechaty.js.org/pull/873) In any case that the information we've provided is lacking, would it be okay if you explain it to us in more detail? Kindly advise so that we can revise. Thanks a lot!  😉

2021-07-29 13:49 UTC, lijiarui commented
@chris-4444 

> May I know what do you mean by adding more about the Wechaty part

May I know where is this comment related to this PR?

2021-08-06 04:28 UTC, chris-4444 commented
@lijiarui Yep, I'm referring to your comment above re PR 915.  We already have covered some things about Wechaty (e.g., [**What is Wechaty**](https://github.com/wechaty/wechaty.js.org/pull/871) and [**What can you do with Wechaty**.](https://github.com/wechaty/wechaty.js.org/pull/873).   The ones reflected in the Explanation overview are based on the topics reflected in Explanations before as well. In case we miss something, please let us know.  😉

![image](https://user-images.githubusercontent.com/82779784/128455503-6e40abf7-ae26-4568-aa1f-f912e475d4a7.png)


> @chris-4444
> 
> > May I know what do you mean by adding more about the Wechaty part
> 
> May I know where is this comment related to this PR?



> @lijiarui May I know what do you mean by adding more about the Wechaty part? Is it pertaining to Wechaty as an organization itself? If yes, it's already covered in [**What is Wechaty**](https://github.com/wechaty/wechaty.js.org/pull/871) and [**What can you do with Wechaty**.](https://github.com/wechaty/wechaty.js.org/pull/873) In any case that the information we've provided is lacking, would it be okay if you explain it to us in more detail? Kindly advise so that we can revise. Thanks a lot! 😉

2021-08-23 16:19 UTC, lijiarui requested changes

2021-08-23 16:19 UTC, lijiarui commented on docusaurus/docs/explainations/overview.mdx
> +
If we cannot explain this, I think we should remove this.

2021-08-23 16:21 UTC, lijiarui commented
Hi, @chris-4444  I feel a little bit confused about you asking me what should add for this part.

I think if we don't have more to talk, then we should not add the explanation here.

2021-09-07 17:53 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-09 11:14 UTC, chris-4444 approved these changes

2021-09-09 11:36 UTC, chris-4444 commented
@lijiarui @huan kindly merge because merging is disabled for me and @nibble0101. thanks.

2021-09-09 11:41 UTC, huan commented
@chris-4444 The reason that you can not merge this PR is that @lijiarui has a "change request" on it.

Please contact @lijiarui and get the approval from her, then this PR will be good to go.

2021-09-09 11:50 UTC, chris-4444 commented
@lijiarui i have updated the post accordingly. kindly approve. thanks.

2021-09-10 06:46 UTC, huan commented
ping @lijiarui

2021-09-14 09:46 UTC, lijiarui requested changes
This part looks a little bit strange, some of the explanation parts is shown while the other part isn't shown. Could you tell us the reason why you design like this?

2021-09-14 09:46 UTC, lijiarui commented on docusaurus/docs/explanations/overview.mdx
> +title: Overview of Explanation section
![image](https://user-images.githubusercontent.com/6419514/133234877-9f0d2e55-c5d7-45c7-b4c0-492d16edf337.png)

It seems the title is too long here, I suggest changing to `Overview` as the other part wrote.

Also, I think we should change `explanation` to `Explanation` as the other part wrote, using the uppercase letter.

2021-09-14 12:34 UTC, chris-4444 approved these changes
Shortened the SDK title as requested.

2021-09-15 14:52 UTC, lijiarui requested changes

2021-09-15 14:52 UTC, lijiarui commented on docusaurus/docs/explanations/overview.mdx
> +## SDK, RPA, and Conversational Interfaces
change `SDK, RPA, and Conversational Interfaces` to `SDK & CUI`, and we need link for this.

2021-09-15 14:52 UTC, lijiarui commented on docusaurus/docs/explanations/overview.mdx
> +## [Life cycle](lifecycle.md)
cycle --> Cycle

2021-09-15 17:44 UTC, nibble0101 commented on docusaurus/docs/explanations/overview.mdx
> +## SDK, RPA, and Conversational Interfaces
@lijiarui  This link can't be added  until #930 has been merged.

2021-09-15 18:18 UTC, nibble0101 commented on docusaurus/docs/explanations/overview.mdx
> +## SDK, RPA, and Conversational Interfaces
Changed to `SDK & CUI` and added place holder link.

2021-09-15 18:43 UTC, nibble0101 commented on docusaurus/docs/explanations/overview.mdx
> +## [Life cycle](lifecycle.md)
Capitalized cycle.

2021-09-16 03:20 UTC, Rohitesh-Kumar-Jain approved these changes
Changes requested by Rui have been implemented 👍🏼

2021-09-18 18:56 UTC, lijiarui approved these changes
LGTM

2021-09-21 04:53 UTC, merged