Added the wechaty-message references section
wechaty/docusaurus pull request #916
Opened 2021-06-01 12:02 UTC by shraddhavp

This  PR links to #890

2021-06-02 05:17 UTC, shraddhavp commented
@Rohitesh-Kumar-Jain  and @proudofsimin  please have a look at it and please let me know if any changes

2021-06-03 17:19 UTC, proudofsimin requested changes
I don't see the need to use bulleted points to describe each method. How do you think if we change to a paragraph? I found two examples for your reference: [Chrome API](https://developer.chrome.com/docs/extensions/mv3/declare_permissions/), [JavaScript specials](https://javascript.info/javascript-specials).

2021-06-04 04:52 UTC, shraddhavp commented
> I don't see the need to use bulleted points to describe each method. How do you think if we change to a paragraph? I found two examples for your reference: [Chrome API](https://developer.chrome.com/docs/extensions/mv3/declare_permissions/), [JavaScript specials](https://javascript.info/javascript-specials).

Ok @proudofsimin  will change it as suggested

2021-06-04 05:41 UTC, shraddhavp commented
> I don't see the need to use bulleted points to describe each method. How do you think if we change to a paragraph? I found two examples for your reference: [Chrome API](https://developer.chrome.com/docs/extensions/mv3/declare_permissions/), [JavaScript specials](https://javascript.info/javascript-specials).

@proudofsimin  had tried that too, but as Wechaty has used usage examples for each method hence have added the bullets. but will try to see if there are some other way to make it beautiful

2021-06-04 06:27 UTC, Soumi7 commented
@shraddhavp can you add the screenshots?

2021-06-06 07:43 UTC, shraddhavp commented
![Screenshot (166)](https://user-images.githubusercontent.com/42699578/120916745-ed2f7000-c6c8-11eb-93d6-add998407c1e.png)
![Screenshot (167)](https://user-images.githubusercontent.com/42699578/120916752-f1f42400-c6c8-11eb-89e4-264cd3a379c8.png)
![Screenshot (168)](https://user-images.githubusercontent.com/42699578/120916754-f28cba80-c6c8-11eb-90ab-682b562e08e5.png)
![Screenshot (169)](https://user-images.githubusercontent.com/42699578/120916755-f28cba80-c6c8-11eb-9c3e-cccf1b360fc6.png)
![Screenshot (170)](https://user-images.githubusercontent.com/42699578/120916756-f3255100-c6c8-11eb-97cd-0280a85e9a01.png)
![Screenshot (171)](https://user-images.githubusercontent.com/42699578/120916758-f3255100-c6c8-11eb-8fbc-fad0a4c8d3f4.png)
![Screenshot (172)](https://user-images.githubusercontent.com/42699578/120916759-f3bde780-c6c8-11eb-86df-6a2ff512cc63.png)

2021-06-13 16:44 UTC, proudofsimin requested changes
Hi @shraddhavp,
It's quite hard to read if the syntax in a list is not paralleled. I changed two of them for your reference. In addition, If the list only contains one bulleted point, just simply remove the bulleted point and turn it to a complete sentence. Thank you. You can do it!

2021-06-13 16:44 UTC, proudofsimin commented on docusaurus/docs/api/wechaty-message.md
> +* This is an instance method of class `Message`
By using ```message.from```, you will receive the sender name from the message. If the method could not find the sender, it will return  `null`. See the following example of instance method of class `Message`:

2021-06-13 16:44 UTC, proudofsimin commented on docusaurus/docs/api/wechaty-message.md
> +* Gets the text content of the recalled message
By using `message.toRecalled`, you will get the text content of the recalled message.
Here is an example:

2021-06-13 16:44 UTC, proudofsimin commented on docusaurus/docs/api/wechaty-message.md
> +      description        : '身份管家',
Since this is a English version, it's better to remove the Chinese words though it won't affect reading.
(FYI about the Chinese: 
title: I'm using *Authing* to authenticate my identity. Come and try.
description: Identity auditor)

2021-06-14 11:27 UTC, Rohitesh-Kumar-Jain approved these changes
PR is properly based, good in scope

2021-06-20 06:00 UTC, shraddhavp commented
@proudofsimin  please have a look at the New change done to the PR as suggested ,and let me know about new suggestions or changes Thanks

2021-06-20 09:32 UTC, proudofsimin approved these changes
This is great. Don't forget to add a space between two sentences. Thanks.

2021-07-10 10:24 UTC, lijiarui commented
hi @shraddhavp  As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-12 14:14 UTC, Rohitesh-Kumar-Jain commented
@Soumi7 We would be glad if you may once go through the PR, and either request for changes or approve the PR.

2021-07-17 05:39 UTC, Soumi7 requested changes
Rest LGTM

2021-07-17 05:39 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-message.md
> +The method returns the text content of the message.
This method returns the text context for the message.

2021-07-17 05:39 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-message.md
> +By using `message.say` you can reply a Text, Contact Card, Media File or Link message to the sender.The method takes in 5 types of parameter ,the more details is given below :
This method takes in 5 types of parameters, ~the~ more details are given below.

2021-07-17 05:39 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-message.md
> +The method gets the type of the  wechat message.The different method type supported are listed below:
This method gets the type of the wechat message. The different method types supported are listed below:

2021-07-17 05:39 UTC, Soumi7 commented on docusaurus/docs/api/wechaty-message.md
> +The method checks if a message is a self mention.It returns `true` for self mention messages.Here is an example:
The -> this and spaces after fullstops.

2021-09-07 17:55 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 06:33 UTC, shraddhavp commented
@Soumi7  please review ,have done the changes requested

2021-09-09 05:35 UTC, Soumi7 approved these changes
LGTM.

2021-09-11 05:48 UTC, shraddhavp commented
have opened a new PR #1281  instead of this due to conflicts

2021-09-11 10:45 UTC, merged