[GSoD 2021] Documented Wechaty OpenAPI section
wechaty/docusaurus pull request #917
Opened 2021-06-01 22:54 UTC by iamrajiv

Related: #1012

![Screenshot 2021-06-02 at 4 17 20 AM](https://user-images.githubusercontent.com/42106787/120399792-570ee900-c35a-11eb-997e-7210ccbd578a.jpg)
![Screenshot 2021-06-02 at 4 17 36 AM](https://user-images.githubusercontent.com/42106787/120399795-59714300-c35a-11eb-9c10-c7c8549457e3.jpg)

2021-06-01 23:12 UTC, iamrajiv commented
@huan @Rohitesh-Kumar-Jain @proudofsimin Please take a look.

2021-06-02 03:18 UTC, Rohitesh-Kumar-Jain commented
@iamrajiv great start 🎉 

I am curious about one thing, how do you decide what image format to pick ? like you have pushed 2 images, one in .jpeg and other .png, and I remember some time back you were advocating the use of .webp all over the Wechaty 😅

Huan also advised me to use .webp in one of my PRs.

2021-06-02 04:02 UTC, iamrajiv commented
Sorry for the inconvenience, @Rohitesh-Kumar-Jain. I forget to change the format of the images. I have converted all the images into WEBP format.

2021-06-04 15:05 UTC, proudofsimin reviewed
Hi, just a minor notice. Can you change the introductory sentences for lists to complete sentences? See [Introductory sentences for lists](https://developers.google.com/style/lists#introductory-sentences-for-lists).

2021-06-05 04:34 UTC, iamrajiv commented
Hi, @proudofsimin I have converted introductory sentences for lists to complete sentences please take a look.

2021-06-06 04:34 UTC, Rohitesh-Kumar-Jain approved these changes
Looks good to me : )

2021-06-13 16:55 UTC, proudofsimin approved these changes
Hi @iamrajiv, 
Approved since it's a minor problem, but I was asking to change this sentence
> An OpenAPI file allows you to describe your entire API, including:

into a complete sentence, instead of those in the bulleted points. Sorry for confusing.

2021-06-17 22:07 UTC, iamrajiv commented
Hi, @proudofsimin I have broken the bullets pinto into a single sentence please review.

2021-06-17 22:08 UTC, iamrajiv commented
Hi, @proudofsimin I have broken the bullet points into a single sentence please review.

2021-06-19 17:42 UTC, proudofsimin commented
Hi @iamrajiv, 
I am sorry I didn't say it clear. The bulleted list is very great, just the introductory sentence needs to be complete.

![image](https://user-images.githubusercontent.com/19759195/122651012-adf12c80-d168-11eb-9527-b9e9aec8fe36.png)

2021-07-12 15:40 UTC, lijiarui commented
@iamrajiv Please make CI green then I will review this PR.

@Rohitesh-Kumar-Jain Please notice that only when CI is green, then you can put it in [merging list](https://github.com/wechaty/wechaty.js.org/issues/1056) Thanks!

2021-07-12 23:47 UTC, iamrajiv commented
@lijiarui I have resized that image now CI is passing can you take a look.

2021-07-14 18:28 UTC, lijiarui requested changes
As we talked #956

I feel we should add the main content from https://github.com/wechaty/openapi

Developers care more about FEATURES, INSTALL, USAGE,KNOWN ISSUES and ARCHITECTURE than about swagger and openapi general introduction.

2021-07-14 22:53 UTC, iamrajiv commented
@lijiarui Added the things that you suggested.

2021-07-16 19:45 UTC, lijiarui requested changes
Hi @iamrajiv 

Please change fix the dead link issue, thanks!

2021-07-16 19:45 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +
`http://github.com/wechaty/openapi/blob/master/CONTRIBUTING.md` this link is a dead link, please check for this.

2021-07-16 19:57 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +
@lijiarui Yeah this file is not added yet but I created PR for this https://github.com/wechaty/openapi/pull/16 so after merge it will work fine.

2021-07-18 17:21 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +
I think wechaty should have only one contributing file, it should be: http://wechaty.js.org/docs/contributing/

And thanks for your reminder, I think we should merge https://github.com/wechaty/openapi/pull/16  and https://github.com/wechaty/wechaty/blob/master/CONTRIBUTING.md to http://wechaty.js.org/docs/contributing/ together, and all of the start contributing link is the unified link: http://wechaty.js.org/docs/contributing/

So please change this link to http://wechaty.js.org/docs/contributing/ first.

2021-07-18 18:53 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +
@lijiarui Yeah this sounds good. I have updated the contributing link. Can you take a look?

2021-07-25 18:57 UTC, lijiarui requested changes

2021-07-25 18:57 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +> [View Wechaty OpenAPI Specification on SwaggerHub](https://app.swaggerhub.com/apis/zixia/WechatyPuppet/)
How about we add screenshot like wehcaty openAPI did here: https://github.com/wechaty/openapi#screenshot

2021-07-25 18:57 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +    width="400"
maybe we can change the width to a larger one.

It looks a little bit small here.
![image](https://user-images.githubusercontent.com/6419514/126910155-adf60282-447d-4db3-b10c-43412bef01a0.png)

2021-07-25 18:57 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +git clone git@github.com:wechaty/openapi-wechaty-getting-started.git
We seem don't have this repo yet, please make sure to use an existing repo or code. Or you may just write code here.

2021-07-25 21:01 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +> [View Wechaty OpenAPI Specification on SwaggerHub](https://app.swaggerhub.com/apis/zixia/WechatyPuppet/)
@lijiarui Yeah I had already added `<img src="../../../static/img/docs/openapi/2.webp" />` in line 158.

2021-07-25 21:02 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +    width="400"
@lijiarui yeah I have updated the image size.

2021-07-25 21:03 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +git clone git@github.com:wechaty/openapi-wechaty-getting-started.git
@lijiarui thanks for pointing out as of now I have removed the link in the future If a repo is created I will update the docs and add the repo link.

2021-07-25 21:03 UTC, iamrajiv commented
@lijiarui Done with all requested changes can you take a look I think it's good to go.

2021-07-31 17:06 UTC, lijiarui requested changes

2021-07-31 17:06 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +title: Wechaty OpenAPI
I think it would be better to change to `OpenAPI Wechaty` like other Polyglot showed.

2021-07-31 17:06 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +git clone git@github.com:wechaty/openapi-wechaty-getting-started.git
It seems you haven't remove the link yet.

2021-07-31 17:06 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +<img src="../../../static/img/docs/openapi/2.webp" />
It seems this image is deformed, could you help to make it proportional?

2021-07-31 20:47 UTC, iamrajiv commented
@lijiarui Requested changes done can u check once

2021-08-14 10:23 UTC, iamrajiv commented
@lijiarui Requested changes done can u check once

2021-09-05 16:56 UTC, iamrajiv commented
@lijiarui Please review the changes. It's pending for a long time and merge conflict is happening it's very hard to resolve the merge conflict again and again :sweat_smile:.

2021-09-07 18:03 UTC, huan requested changes
Thanks for the improvements!

Please follow my comments, as well as the below diff shows:

```diff
- docusaurus/static/img/docs/openapi/1.webp 
+ docusaurus/static/img/docs/polyglot/openapi/some-meaning.webp 
```

2021-09-07 18:03 UTC, huan commented on docusaurus/docs/getting-started/overview.mdx
> -slug: /getting-started/
If I'm remembering right, this docs file path is the most important "getting started" tutorial URL at https://wechaty.js.org/docs/getting-started/

Replace this file with `/polyglot/openapi` is not the right decision I believe.

2021-09-07 18:03 UTC, huan commented on docusaurus/docs/polyglot/openapi/overview.md
> -slug: /polyglot/openapi/
Why do you remove this file?

This file I believe is the correct point for the openapi docs.

2021-09-09 22:19 UTC, iamrajiv commented on docusaurus/docs/getting-started/overview.mdx
> -slug: /getting-started/
@huan oh yeah updated the requested changes.

2021-09-09 22:20 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.md
> -slug: /polyglot/openapi/
@huan I did not delete like I renamed `overview.md` file with `overview.mdx` because I want to render js code to highlight some keyword so added highlight code in it.

2021-09-10 06:06 UTC, huan commented on docusaurus/docs/getting-started/overview.mdx
> +<img src="../../../static/img/docs/openapi/openapi-logo.webp" />
Please use Markdown instead of HTML because the docusaurus build system can check markdown files.

2021-09-10 06:11 UTC, huan requested changes
Please move the image files location:

```diff
- docusaurus/static/img/docs/openapi/openapi-logo.webp 
+ docusaurus/static/img/docs/polyglot/openapi/openapi-logo.webp 
```

2021-09-10 06:11 UTC, huan requested changes
Please remove all unrelated changes to the file `docusaurus/docs/getting-started/overview.mdx` because this is not right I believe.

2021-09-10 15:40 UTC, iamrajiv commented
@huan requested changes done, please review.

2021-09-10 17:31 UTC, huan requested changes

2021-09-10 17:31 UTC, huan commented on docusaurus/docs/getting-started/overview.mdx
> +sidebar_label: Wechaty OpenAPI
I can not understand why this PR changes the `docs/getting-started/overview.mdx` to **OpenAPI**?

This doc should be our main getting started overview docs and should not be used as other docs.

2021-09-10 22:47 UTC, iamrajiv commented on docusaurus/docs/getting-started/overview.mdx
> +sidebar_label: Wechaty OpenAPI
@huan sorry for the inconvenience by mistake I duplicated the open API docs in getting started now I have reverted it.

2021-09-11 03:49 UTC, huan approved these changes
LGTM

It will be great if you can add a link of your swagger blog post link to this doc.

I hope we can be careful to not destroy the existing doc by mistake in the future, because I have see several cases in our pull request.

Thank you very much!

2021-09-11 07:04 UTC, iamrajiv commented
@huan added the swagger blog link.

2021-09-11 17:02 UTC, shraddhavp approved these changes
LGTM

2021-09-16 08:07 UTC, iamrajiv commented
@lijiarui Requested changes done can you approve.

2021-09-17 07:30 UTC, iamrajiv commented
@Rohitesh-Kumar-Jain This is good to be merged.

2021-09-20 00:57 UTC, iamrajiv commented
@lijiarui Can you approve the changes?

2021-09-21 15:55 UTC, lijiarui requested changes
Generally, it seems good to me, just two small tips.

2021-09-21 15:55 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.md
> -slug: /polyglot/openapi/
I think it is better to use mdx file and we wish all of the docs can use mdx instead of md. If you can change to mdx file, it would be better!

2021-09-21 15:55 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.md
> +Wechaty has a community of very helpful contributors on different platforms you can join to get help from. Before joining any of the communities, we recommend that you read our Code of conduct]o that
I think this is a typo: `conduct]o `

2021-09-22 20:25 UTC, iamrajiv commented
@lijiarui Done with the requested changes can you check once.

2021-09-23 06:23 UTC, Rohitesh-Kumar-Jain commented
@iamrajiv pls resolve the merge conflict so that we can proceed with the merge

2021-09-23 08:27 UTC, iamrajiv commented
@Rohitesh-Kumar-Jain Done.

2021-09-27 12:58 UTC, lijiarui requested changes

2021-09-27 12:58 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +import ProviderBadges from '../puppet-providers/transclusions/badges.mdx';
Why do you change this part? If it is the format reason, I think the old version format is better.

2021-09-27 12:58 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +title: Wechaty OpenAPI
It seems you didn't change as I requested. And, sidebar_label should change back to OpenAPI as other Polyglot showed.

2021-09-27 12:58 UTC, lijiarui commented on docusaurus/docs/polyglot/transclusions/polyglot-table.mdx
> +| --------------------------------------- | ----------------------------------------------------------- | ---------------------------------------------------------------------------------------------
Why do you change this file? It seems you only change the blank format...

2021-09-27 13:42 UTC, iamrajiv commented on docusaurus/docs/polyglot/transclusions/polyglot-table.mdx
> +| --------------------------------------- | ----------------------------------------------------------- | ---------------------------------------------------------------------------------------------
@lijiarui no-no like I change the like `overview.md` to `overview.mdx` in this file rest indentations I removed.

2021-09-27 13:53 UTC, iamrajiv commented on docusaurus/docs/getting-started/overview.mdx
> +import ProviderBadges from '../puppet-providers/transclusions/badges.mdx';
@lijiarui nothing changes I just update the `overview.md` file to `overview.mdx` file because we have rename the file so we have to update the links other than that mdx file is formatted to prettier so extra `;` is added which is fine.

2021-09-28 16:49 UTC, lijiarui requested changes, later dismissed

2021-09-28 16:49 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +import ProviderBadges from '../puppet-providers/transclusions/badges.mdx';
I don't think we don't need to add `;` here if it doesn't affect the function.

2021-09-28 16:49 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.mdx
> +title: Wechaty OpenAPI
ping

2021-09-28 16:49 UTC, lijiarui commented on docusaurus/docs/polyglot/transclusions/polyglot-table.mdx
> +| --------------------------------------- | ----------------------------------------------------------- | ---------------------------------------------------------------------------------------------
You just change openAPI part right? Why other languages seems to be changed? Please only change the related part of yours.

2021-09-29 09:01 UTC, iamrajiv commented
Hi, @lijiarui thanks for the feedback I have done with the changes cane you review once.

2021-10-03 14:58 UTC, iamrajiv commented
Hi, @lijiarui thanks for the feedback I have done with the changes cane you review once.

2021-10-15 09:08 UTC, merged