Wechaty chatbot development lifecycle
wechaty/docusaurus pull request #918
Opened 2021-06-03 07:45 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Wechaty chatbot development lifecycle |  Joseph Mawa |

This  is **Wechaty chatbot development lifecycle** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/120606850-4ba1e780-c458-11eb-8981-88758314eb9f.png)
![image](https://user-images.githubusercontent.com/52580190/120606984-696f4c80-c458-11eb-941e-36069429f9af.png)
![image](https://user-images.githubusercontent.com/52580190/120607067-8146d080-c458-11eb-8863-0080b11ac8e0.png)
![image](https://user-images.githubusercontent.com/52580190/120607145-9459a080-c458-11eb-86b9-6aa7d5b9feab.png)
![image](https://user-images.githubusercontent.com/52580190/120607248-adfae800-c458-11eb-9f99-0290302c34a2.png)
![image](https://user-images.githubusercontent.com/52580190/120607323-bf43f480-c458-11eb-8161-4d21c62c9722.png)

2021-06-04 16:45 UTC, proudofsimin approved these changes
You did a great job! Thank you.

2021-06-04 16:58 UTC, Rohitesh-Kumar-Jain approved these changes
@huan ping for merge

2021-06-09 13:45 UTC, lijiarui requested changes
Request to add a diagram

2021-06-09 13:45 UTC, lijiarui commented on docusaurus/docs/explainations/lifecycle.md
> +<!-- Insert the lifecycle diagram here -->
How about draw a lifecycle diagram here?

2021-06-09 14:13 UTC, nibble0101 commented on docusaurus/docs/explainations/lifecycle.md
> +<!-- Insert the lifecycle diagram here -->
@lijiarui  Yes. I left that comment intentionally. We have taken note of it as part of our todo when we start polishing the different sections we are working on. Our goal is to get all the content in place and start adding illustrations after that.

2021-06-09 14:51 UTC, lijiarui commented on docusaurus/docs/explainations/lifecycle.md
> +<!-- Insert the lifecycle diagram here -->
Got it, thanks.

2021-07-10 10:25 UTC, lijiarui commented
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-12 13:13 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-15 07:16 UTC, chris-4444 requested changes
@nibble0101 I don't know if this is okay with you, at least for now we have a chatbot lifecycle image as requested by @lijiarui. Feel free to change this as required. 😉
@Rohitesh-Kumar-Jain @proudofsimin I'll wait what Joseph says since I suck at graphics. 😵
![Wechaty_Chatbot_Development_Lifecycle](https://user-images.githubusercontent.com/82779784/125745677-c937aa6c-ad03-4df4-a6d0-77eafc12ad0f.png)

2021-07-15 07:35 UTC, nibble0101 commented
> @nibble0101 I don't know if this is okay with you, at least for now we have a chatbot lifecycle image as requested by @lijiarui. Feel free to change this as required. 
> @Rohitesh-Kumar-Jain @proudofsimin I'll wait what Joseph says since I suck at graphics. 
> ![Wechaty_Chatbot_Development_Lifecycle](https://user-images.githubusercontent.com/82779784/125745677-c937aa6c-ad03-4df4-a6d0-77eafc12ad0f.png)

Thanks. The diagram is supposed to capture all the steps described. What tool did you use to generate that?

2021-07-15 17:32 UTC, Rohitesh-Kumar-Jain reviewed
Ig some phases are missing like promoting the bot, bot architecture, bot script writing.

Thanks for taking so much effort in creating a beautiful animation, I was expecting a simple flow chart, but this is so amazing.

2021-07-22 13:11 UTC, chris-4444 requested changes
@nibble0101 Updated the diagram.

2021-07-23 06:15 UTC, nibble0101 commented on docusaurus/docs/explainations/lifecycle.md
> +<!-- Insert the lifecycle diagram here -->
Added life cycle diagram

2021-07-23 06:18 UTC, nibble0101 commented
@chris-4444  Thanks for the diagram. This is what it looks like.
![image](https://user-images.githubusercontent.com/52580190/126744125-8874b818-4287-423c-b4ba-389e6609f882.png)

2021-07-23 06:46 UTC, chris-4444 approved these changes
LGTM.

2021-08-23 16:34 UTC, lijiarui requested changes

2021-08-23 16:34 UTC, lijiarui commented on docusaurus/docs/explainations/lifecycle.md
> +title: Wechaty Chatbot development lifecycle
Should change back to Life Cycle.

Since this is wechaty doc, we don't need to add more wechaty in the docs.

2021-08-23 16:34 UTC, lijiarui commented on docusaurus/docs/explainations/lifecycle.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Please remove this image, since it is a little meaningless when we put the wechaty logo here.

2021-08-23 16:34 UTC, lijiarui commented on docusaurus/docs/explainations/lifecycle.md
> +Wechaty is an exciting SDK for developing chatbots for popular Instant Messaging systems such as Wechat, Whatsapp, and Gitter. It provides developers with the unique capability of building chatbots t
such as Wechat, Whatsapp, and Gitter ---> such as WeChat, WeCom, WhatsApp, and Gitter.

2021-08-23 16:34 UTC, lijiarui commented on docusaurus/docs/explainations/lifecycle.md
> +- **Articulate business requirements**
I think:

1. the following explanation isn't matched the lifecycle diagram.
2. It seems unrelated to Wechaty

We should add more wechaty related lif cycle things here.

2021-09-03 10:23 UTC, nibble0101 commented on docusaurus/docs/explainations/lifecycle.md
> +title: Wechaty Chatbot development lifecycle
Changed it back to Life cycle

2021-09-03 10:24 UTC, nibble0101 commented on docusaurus/docs/explainations/lifecycle.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Removed image

2021-09-03 10:25 UTC, nibble0101 commented on docusaurus/docs/explainations/lifecycle.md
> +Wechaty is an exciting SDK for developing chatbots for popular Instant Messaging systems such as Wechat, Whatsapp, and Gitter. It provides developers with the unique capability of building chatbots t
Added Wecom

2021-09-03 11:22 UTC, nibble0101 commented on docusaurus/docs/explainations/lifecycle.md
> +- **Articulate business requirements**
> I think:
> 
> 1. the following explanation isn't matched the lifecycle diagram.
> 2. It seems unrelated to Wechaty
> 
> We should add more wechaty related lif cycle things here.

Hi @lijiarui 


I don't think I understand what it is exactly you want me to include in this section. We are following the [Divio documenation system](https://documentation.divio.com) which spells out that one of  the goals of the Explanation section  is  to deepen the readers knowledge of a topic. 

Wechaty is SDK for building chatbots. Chatbots are the end product of using Wechaty SDK. Are you suggesting knowledge of Chatbot development  life cycle wouldn't be useful to someone who is building chatbot using Wechaty?  Or it doesn't deepen the knowledge or understanding of someone using Wechaty? Or Are you saying Wechaty chatbots have different  lifecycle than what we described  above? If so, what are the lifecycle stages one should go through when building a chatbot  using Wechaty? Or by "wechaty related lif cycle things", you want us  to describe the stages the Wechaty codebase went through from conception of the project idea up to today?

 If you could enlighten me on the above questions and clarify on what you mean by "wechaty related lif cycle things" , I will be more than happy to work on them. Otherwise the one sentence response in your review doesn't tell me anything about what exactly you want me to include here.  Our intention of including this section is to discuss Chatbot development lifecycle in general  to broaden the reader's  knowledge (by reader I am referring to someone who wants to learn how to use Wechaty to build chatbot) and help them understand more about chatbot development.

Sorry for the late response.  I have been quite busy in the last one month.

2021-09-03 14:33 UTC, closed without merging

2021-09-03 14:35 UTC, nibble0101 commented
As per [per this comment](https://github.com/wechaty/wechaty.js.org/pull/915#discussion_r694119318), it seems people are not interested in seeing Chatbot lifecycle in the docs, therefore I have decided to close this PR.