Added  Wechaty token section
wechaty/docusaurus pull request #919
Opened 2021-06-03 13:31 UTC by shraddhavp

This PR is for the Wechaty token section, this links #890

2021-06-03 14:31 UTC, shraddhavp commented
@huan  @Rohitesh-Kumar-Jain  and @proudofsimin please check out the PR

2021-06-05 16:51 UTC, proudofsimin requested changes
I'm feeling like you've gone too far in this part. Hold on, and don't give instructions in reference. The most important things in reference are easy to search and include the information as much as possible, so the word like "example" should not appear as you are supposed to provide everything like an encyclopedia. I found a good [example](https://developers.google.com/vault/reference/rest) for your reference. I think you may consider reconstruct this part a little bit. Please let me know if you have any question.

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +Wechaty Puppet Service Token Gateway is a gateway for converting the Wechaty Puppet Provider to a Wechaty Puppet Service.This can be done by setting up different environment variables
add a space between two sentences and a period at the end of the second sentence.

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +Here 👇 is an example for setting up Wechaty Puppet service to one of the Wechaty Puppet Provider Padlocal
I don't quite understand this part. By example you mean the following four variables (WECHATY_PUPPET, WECHATY_TOKEN...)? And I could see you are trying to create a casual atmosphere, but I felt the icon makes this document a bit unprofessional. I would recommend to remove it.

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +## WECHATY_PUPPET
If these four are the examples mentioned in the previous sentence, they should be one level lower.

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +This environment variable is used for defining the Wechaty Puppet Provider NPM name and its parameters
Don't forget the period at the end.

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +The after running the above commands lot of  output log messages can be seen in the terminal.
I don't understand this sentence.

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +The running of the Wechaty Puppet Service can be checked by using the command given below:
Use the command given below to check the running of the Wechaty Puppet Service.
(Active voice is preferred)

2021-06-05 16:51 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +**Replace ${WECHATY_TOKEN} to your real token in the above configuration*
Are you trying to make it **bold** ?

2021-06-05 17:29 UTC, shraddhavp commented
> I'm feeling like you've gone too far in this part. Hold on, and don't give instructions in reference. The most important things in reference are easy to search and include the information as much as possible, so the word like "example" should not appear as you are supposed to provide everything like an encyclopedia. I found a good [example](https://developers.google.com/vault/reference/rest) for your reference. I think you may consider reconstruct this part a little bit. Please let me know if you have any question.

ok will do the changes @proudofsimin ,thanks

2021-06-06 07:37 UTC, shraddhavp commented
@proudofsimin  have done the changes please check now,let me know if any further changes

2021-06-13 17:09 UTC, proudofsimin approved these changes
Thank you! The updated version is impressive :)

2021-06-13 17:09 UTC, proudofsimin commented on docusaurus/docs/specs/specs-token.md
> +After the docker image has been created use a docker command  to start the Wechaty Puppet Service Token Gateway with the below configuration:
After the docker image has been created [,] use a docker command  to start the Wechaty Puppet Service Token Gateway with the below configuration:

(Don't forget the comma)

2021-06-14 11:25 UTC, Rohitesh-Kumar-Jain approved these changes
I am approving for PR quality 

Perfect PR : clean commit history, properly based, PR good in scope.

2021-07-10 10:25 UTC, lijiarui commented
hi @shraddhavp  As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-12 14:14 UTC, Rohitesh-Kumar-Jain commented
@Soumi7 We would be glad if you may once go through the PR, and either request for changes or approve the PR.

2021-07-17 05:43 UTC, Soumi7 approved these changes
LGTM

2021-07-17 06:06 UTC, Rohitesh-Kumar-Jain commented
> LGTM

Welcome back, glad to hear again from you 🎉

2021-07-17 07:07 UTC, Soumi7 commented
> > LGTM
> 
> Welcome back, glad to hear again from you tada

Haha Thanks! Great to be back!

2021-09-07 18:08 UTC, huan approved these changes
Thanks for adding this!

Please change the file name to `specs/gateway.mdx` as other files are.

After being renamed, I believe this PR will be ready to be merged.

2021-09-07 18:09 UTC, huan commented on docusaurus/docs/specs/specs-token.md
> +  -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT” \
Please add `-e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER`

See: https://github.com/wechaty/wechaty-puppet-service/issues/160

2021-09-08 06:16 UTC, merged