Running ding dong bot on gitpod
wechaty/docusaurus pull request #923
Opened 2021-06-05 10:03 UTC by shwetalsoni

Added tutorial for **Running on Gitpod**

Below is the structure that I have followed:

* Create an account on Gitpod if a new user
* Creating workspace
* Scanning the QR code
* Connecting the bot with specified puppet
* Testing the bot

![Screenshot from 2021-06-05 15-22-27](https://user-images.githubusercontent.com/57187745/120887901-22798680-c613-11eb-8437-4ea65ce1bd24.png)
![Screenshot from 2021-06-05 15-22-52](https://user-images.githubusercontent.com/57187745/120887912-2efddf00-c613-11eb-8214-f747b9e00ae1.png)
![Screenshot from 2021-06-05 15-23-07](https://user-images.githubusercontent.com/57187745/120887914-302f0c00-c613-11eb-912c-fd3113ec92cd.png)
![Screenshot from 2021-06-05 15-23-20](https://user-images.githubusercontent.com/57187745/120887916-30c7a280-c613-11eb-946b-c668d03063fe.png)

2021-06-05 10:12 UTC, shwetalsoni commented
Tag: #891

2021-06-08 13:54 UTC, proudofsimin approved these changes
Great but please correct some typos.

2021-06-08 13:54 UTC, proudofsimin commented on docusaurus/docs/getting-started/running-on-gitpod.md
> +If you are total begginer to wechaty this tutorial will guide you how to run the [Ding Dong bot](https://github.com/wechaty/wechaty-getting-started/blob/master/examples/ding-dong-bot.ts) from the [We
If you are total ~begginer~ [beginner] to ~w~ [W] echaty [,]  this tutorial will guide you...

2021-06-08 13:54 UTC, proudofsimin commented on docusaurus/docs/getting-started/running-on-gitpod.md
> +Follow the steps below to get started.
Add a colon after *to get started*.

2021-06-08 13:54 UTC, proudofsimin commented on docusaurus/docs/getting-started/running-on-gitpod.md
> +1. After logging in with your github account you have to create a workspace by clicking on **New Workspace** button.
After logging in with your github account [,] you have to create a workspace by clicking on **New Workspace** button.

2021-06-08 16:58 UTC, shwetalsoni commented
@proudofsimin I have made the suggested changes.

2021-06-14 11:24 UTC, Rohitesh-Kumar-Jain approved these changes
Perfect PR : clean commit history, properly based, relevant screenshots, PR good in scope.

2021-07-06 18:49 UTC, lijiarui requested changes
Please change as I request, thanks!

2021-07-06 18:49 UTC, lijiarui commented on docusaurus/docs/getting-started/running-on-gitpod.md
> +If you are total beginner to wechaty this tutorial will guide you how to run the [Ding Dong bot](https://github.com/wechaty/wechaty-getting-started/blob/master/examples/ding-dong-bot.ts) from the [We
How about we add Gitpod link here, change to：

[Gitpod](https://gitpod.io/#https://github.com/wechaty/wechaty-getting-started)

2021-07-07 08:41 UTC, shwetalsoni commented
@lijiarui I have made the requested change.

2021-07-07 16:30 UTC, lijiarui approved these changes
Good job!

2021-07-08 12:40 UTC, huan approved these changes

2021-07-08 15:15 UTC, lijiarui commented
@shwetalsoni Please resolve this conflict and then I will merge this PR.

2021-07-08 17:25 UTC, merged