Rendered openapi/CHANGELOG.md file in the History section of OpenAPI docs
wechaty/docusaurus pull request #924
Opened 2021-06-05 12:28 UTC by iamrajiv

![Screenshot 2021-06-05 at 5 57 23 PM](https://user-images.githubusercontent.com/42106787/120891700-8a39cc80-c627-11eb-8c94-778294cfedeb.jpg)

2021-06-05 12:41 UTC, iamrajiv commented
Hi, @huan @Rohitesh-Kumar-Jain @proudofsimin I have made a PR [#11](https://github.com/wechaty/openapi/pull/11) in [wechaty/openapi](https://github.com/wechaty/openapi) repository which will add `CHANGELOG.md` file. So, as of now, the History section output will not load because PR [#11](https://github.com/wechaty/openapi/pull/11) is not yet merged if it gets merged then the section will load fine.

2021-06-10 15:07 UTC, proudofsimin commented
Hi @iamrajiv,
Thank you for taking care of the version update history. Do you think if it's better to change the layout to this:

## History

This table shows a history of recent updates to the _openAPI_.

| Date | Change|
|------|--------|
|...       |...          |

2021-06-10 15:41 UTC, iamrajiv commented
Hi, @proudofsimin. Unfortunately, we can't change the layout of the History section like that because it is rendered in real-time from [wechaty/openapi](https://github.com/wechaty/openapi). The layout will always look like this https://github.com/wechaty/wechaty/blob/master/CHANGELOG.md.

2021-06-10 16:09 UTC, proudofsimin commented
Hi @iamrajiv, 
Then please remove me from the reviewer if the document structure is unable to change. Thank you.

2021-07-21 03:45 UTC, Rohitesh-Kumar-Jain approved these changes, later dismissed
I am not the best person to review this, but it looks fine to me : )

2021-09-07 18:16 UTC, huan approved these changes
LGTM.

The `zero-md` looks great, this module gives me a reason to put `CHANGELOG.md` in our repos!

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-10 03:07 UTC, huan commented on .gitignore
> +jekyll/_posts/2020-12-31-osschat-a-bridge-to-the-apache-way-in-china.md
Why do we add this post to `.gitignore`?

2021-09-10 03:12 UTC, huan requested changes
~~outdated~~

2021-09-10 03:13 UTC, huan commented on docusaurus/tsconfig.json
> +    "es2016",
How about using `es2020`? :)

2021-09-10 03:13 UTC, huan approved these changes, later dismissed
LGTM

Thanks for the update!

2021-09-16 04:50 UTC, shraddhavp submitted a review, later dismissed

2021-09-18 17:57 UTC, lijiarui submitted a review, later dismissed
LGTM

2021-10-03 15:02 UTC, iamrajiv commented
@huan Tests are failing it's saying `HTMLElement is not defined` I tried a lot to fix it but was not able to get it can you help, please. Btw I think it's not relevant we can ignore the tests.

2021-10-04 05:11 UTC, huan commented
We need to fix this before merge because if this PR can not pass the CI, then it will block the whole repo to be published after it has been merged.

2022-03-24 03:04 UTC, huan approved these changes
LGTM

2022-03-30 12:12 UTC, merged

2022-03-30 12:12 UTC, huan commented
Thank you very much for the improvements!