Software Development Kit subsection of the Explanations section
wechaty/docusaurus pull request #930
Opened 2021-06-08 09:49 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Software Development Kit  |  Chris Estepa |

This  is **Software Development Kit** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/121163613-9d32e380-c857-11eb-91ef-9d70da406521.png)
![image](https://user-images.githubusercontent.com/52580190/121163747-b6d42b00-c857-11eb-9d2d-32e74760d056.png)
![image](https://user-images.githubusercontent.com/52580190/121163865-cf444580-c857-11eb-82f0-745d0ff8bd70.png)

2021-06-12 09:02 UTC, proudofsimin approved these changes
Thank you

2021-06-14 11:22 UTC, Rohitesh-Kumar-Jain approved these changes
Perfect PR : clean commit history, properly based, relevant screenshots, PR good in scope.

2021-07-12 13:13 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-13 15:26 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 19:05 UTC, lijiarui requested changes

2021-07-18 19:05 UTC, lijiarui commented on docusaurus/docs/explainations/software-development-kit.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Maybe we change to SDK image better than wechaty logo here.

2021-07-18 19:05 UTC, lijiarui commented on docusaurus/docs/explainations/software-development-kit.md
> +title: Software Development Kit
The title is `Software Development Kit` but you talk about `Software Development Kit` as well as `conversational UI and AI`, `RPA`, etc, so I think you should either change the title or change the content here.

2021-08-23 13:48 UTC, lijiarui requested changes
ping @nibble0101

2021-08-23 13:48 UTC, lijiarui commented on docusaurus/docs/explainations/software-development-kit.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
ping @nibble0101

2021-09-03 14:20 UTC, nibble0101 commented on docusaurus/docs/explainations/software-development-kit.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Remove the image

2021-09-03 14:21 UTC, nibble0101 commented on docusaurus/docs/explainations/software-development-kit.md
> +title: Software Development Kit
Removed content not related to SDK

2021-09-03 14:25 UTC, nibble0101 commented
@chris-4444  I have removed all the other sub-sections except the one talking about SDK. Would you mind reading through again to see if it is still okay?

2021-09-06 12:09 UTC, chris-4444 approved these changes
@nibble0101 @lijiarui Updated the title to match the contents.

2021-09-07 18:21 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-14 09:40 UTC, lijiarui requested changes
![image](https://user-images.githubusercontent.com/6419514/133234042-4de9caca-96d6-4eda-bf86-9694a08717ff.png)

It looks strange here since the title is tooooooo long.

And we already have a explanation here: http://wechaty.js.org/docs/explanations/rpa

I suggest we merge them together or just delete this part.

2021-09-14 12:02 UTC, chris-4444 approved these changes
@lijiarui I have shortened the title. Let us retain this section as it was previously a section in the old Wechaty site and is also important. We just have it put in one section to make it look more organized. The sidebar would also be updated and would look somehow like this: 
![image](https://user-images.githubusercontent.com/82779784/133253760-0d22e5fc-9e4d-47ce-98cc-9dda5831ff77.png)

2021-09-14 13:46 UTC, chris-4444 approved these changes
Removed RPA.

2021-09-15 14:48 UTC, lijiarui requested changes

2021-09-15 14:48 UTC, lijiarui commented on docusaurus/docs/explanations/software-development-kit.md
> +title: SDK and Conversational Interfaces
I suggest changing to `SDK & CUI`

2021-09-15 14:48 UTC, lijiarui commented on docusaurus/sidebars.ts
> +    'explanations/software-development-kit',
change `software-development-kit` to `sdk-cui`, making it more unified.

2021-09-15 17:31 UTC, nibble0101 commented on docusaurus/docs/explanations/software-development-kit.md
> +title: SDK and Conversational Interfaces
Changed title to SDK & CUI

2021-09-15 17:31 UTC, nibble0101 commented on docusaurus/sidebars.ts
> +    'explanations/software-development-kit',
Changed file name to sdk-cui,

2021-09-16 03:24 UTC, Rohitesh-Kumar-Jain approved these changes
Requested changes have been implemented

2021-09-18 18:57 UTC, lijiarui approved these changes
LGTM

2021-09-21 04:38 UTC, merged