Updated tutorial overview as per suggestion with a new PR
wechaty/docusaurus pull request #934
Opened 2021-06-10 11:34 UTC by shwetalsoni

Updated tutorial overview by adding different tutorials available and also explaining which tutorial is convenient for which type of user.

* Classified tutorials into three categories

     * Building your first chatbot with wechaty
     
     * Advanced tutorials (Using plugins, library, and framework with wechaty)
     
     * Explore more bots (Adding more features to your bot)

![Screenshot from 2021-06-10 17-00-26](https://user-images.githubusercontent.com/57187745/121518113-bd0c0800-ca0d-11eb-9871-fc2479a47877.png)
![Screenshot from 2021-06-10 17-00-51](https://user-images.githubusercontent.com/57187745/121518152-c85f3380-ca0d-11eb-9ca2-87262cf18789.png)
![Screenshot from 2021-06-10 17-01-06](https://user-images.githubusercontent.com/57187745/121518160-c9906080-ca0d-11eb-8220-fcfbcc6db040.png)

2021-06-10 11:35 UTC, shwetalsoni commented
This PR is renewed PR for #903

2021-06-10 11:51 UTC, shwetalsoni commented
Tag #891

2021-06-12 03:53 UTC, sbis04 commented on docusaurus/docs/tutorials/overview.md
> +- [Cloud IDE](getting-started/quick-start.mdx)
While referring to the pages, using **Google Cloud Shell** instead of **Cloud IDE** would be better.

2021-06-13 10:00 UTC, proudofsimin approved these changes
Thank you

2021-06-14 11:21 UTC, Rohitesh-Kumar-Jain approved these changes
Perfect PR : clean commit history, properly based, relevant screenshots, PR good in scope.

2021-06-15 05:12 UTC, sbis04 approved these changes

2021-07-06 18:57 UTC, lijiarui requested changes
Pls change as I request, thanks!

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +- [Gitpod](getting-started/quick-start.mdx)
I think we should add an anchor here, maybe getting-started/quick-start#gitpod is better.

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +- [Google Cloud Shell](getting-started/quick-start.mdx)
I think we should add an anchor here, maybe getting-started/quick-start#google-cloud-shell

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +If you are a total begginer then we recommend using **Gitpod**.
I thinks we can add link for Gitpod here.

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +Once you get basic idea of ding-dong bot, you can try out building it from scratch by following our [Running Locally](getting-started/hard-way.mdx) tutorial.
I think we should change hard-way to `running-locally` when #888 changed as I request.

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +## Advanced Tutorials (Using plugins, library and framework with wechaty)
I think we should just use `Using plugins with wechaty` since `Vorpal` and `Redux` is plugin too.

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +
I think we  should remove blank lines here.

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +
I think we  should remove blank lines here.

2021-07-06 18:57 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +
I think we  should remove blank lines here.

2021-07-07 08:16 UTC, shwetalsoni commented on docusaurus/docs/tutorials/overview.md
> +- [Gitpod](getting-started/quick-start.mdx)
Yeah I will be updating the link here to `getting-started/quick-start/gitpod.md` once the PR #922 is merged. In this PR souvik has created a new structure for `getting started` section. Therefore under `Quick Start` there will be separate lpages for **Gitpod** and **Google Cloud Shell**.

2021-07-07 08:17 UTC, shwetalsoni commented on docusaurus/docs/tutorials/overview.md
> +- [Google Cloud Shell](getting-started/quick-start.mdx)
same for this one too.
`getting-started/quick-start/google-cloud-shell.md`

2021-07-07 08:18 UTC, shwetalsoni commented on docusaurus/docs/tutorials/overview.md
> +Once you get basic idea of ding-dong bot, you can try out building it from scratch by following our [Running Locally](getting-started/hard-way.mdx) tutorial.
Yeah I'll do this once #888 is merged

2021-07-07 08:35 UTC, shwetalsoni commented
@lijiarui I have made the suggested changes.

2021-07-07 16:35 UTC, lijiarui requested changes
After you file issues for the pending questions, I will approve this PR.

2021-07-07 16:35 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +- [Gitpod](getting-started/quick-start.mdx)
Then how about we file a new issue for this comment, and I will ignore this part at this PR.

2021-07-07 16:35 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +- [Google Cloud Shell](getting-started/quick-start.mdx)
Then how about we file a new issue for this comment, and I will ignore this part at this PR.

2021-07-07 16:35 UTC, lijiarui commented on docusaurus/docs/tutorials/overview.md
> +Once you get basic idea of ding-dong bot, you can try out building it from scratch by following our [Running Locally](getting-started/hard-way.mdx) tutorial.
Then how about we file a new issue for this comment, and I will ignore this part at this PR.

2021-07-07 17:14 UTC, shwetalsoni commented
> Thanks for the fixing!
> 
> After you file issues for the pending questions, I will approve this PR.

Sorry, I didn't get you.
Do you mean to create an issue mentioning the changes to be done later?

2021-07-07 18:56 UTC, lijiarui commented
> > Thanks for the fixing!
> > After you file issues for the pending questions, I will approve this PR.
> 
> Sorry, I didn't get you.
> Do you mean to create an issue mentioning the changes to be done later?

Yes, you are right. You can create an issue and relate it to this PR. We can merge this PR first and then fix the issue later by creating a new PR.

2021-07-08 08:25 UTC, shwetalsoni commented
@lijiarui I have created issue #1032 for keeping the record of all the features that need to be added later mentioning all the respective PR's.

2021-07-08 11:58 UTC, lijiarui approved these changes
Good job！

2021-07-08 12:39 UTC, huan approved these changes

2021-07-08 15:15 UTC, merged