Getting started overview
wechaty/docusaurus pull request #935
Opened 2021-06-10 11:57 UTC by shwetalsoni

![Screenshot from 2021-06-10 17-26-28](https://user-images.githubusercontent.com/57187745/121520926-1e81a600-ca11-11eb-9cbc-a63d60e4d3df.png)
![Screenshot from 2021-06-10 17-26-47](https://user-images.githubusercontent.com/57187745/121520936-204b6980-ca11-11eb-9a5f-9d87abfeb5f6.png)

2021-06-10 11:58 UTC, shwetalsoni commented
This PR is renewed PR for #897.

2021-06-10 12:01 UTC, shwetalsoni commented
Tag #891

2021-06-12 03:50 UTC, sbis04 commented on docusaurus/docs/getting-started/overview.mdx
> +* [Cloud IDE](getting-started/quick-start.mdx)
I have one little suggestion here, it would be nice to use **Google Cloud Shell** here instead of **Cloud IDE** as in the other pages of the docs we are referring it by this name.

2021-06-12 12:00 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/getting-started/overview.mdx
> +* [Cloud IDE](getting-started/quick-start.mdx)
yes seems legit

2021-06-12 12:03 UTC, Rohitesh-Kumar-Jain commented
@shwetalsoni thanks for renewing the PR, PR looks good to me, Souvik suggested a valid point, pls do consider that.

2021-06-13 14:10 UTC, proudofsimin requested changes
Please let me know if you have any question.

2021-06-13 14:10 UTC, proudofsimin commented on docusaurus/docs/getting-started/overview.mdx
> +* It replies with a `dong` message when it recieves a `ding` message.
Please align the sentences structure under the list. For example:
* Turn a WeChat/Whatsapp account into a chatbot, a.k.a [Conversational User Interface](https://en.wikipedia.org/wiki/Conversational_user_interface) Automation Software, with just a few lines of code.
* Represent the user with the power of Wechaty Conversational RPA technology.
* Work out of the box on **Linux**, **Mac** and **Windows**.
* Support all [puppets](../puppet-services) like Web, Pad, Windows and Mac.
* Reply with a `dong` message when it recieves a `ding` message.

(Or you could rewrite the sentences yourself)

2021-06-13 14:36 UTC, shwetalsoni commented on docusaurus/docs/getting-started/overview.mdx
> +* It replies with a `dong` message when it recieves a `ding` message.
I have made the changes @proudofsimin

2021-06-13 14:59 UTC, proudofsimin commented on docusaurus/docs/getting-started/overview.mdx
> +* It replies with a `dong` message when it recieves a `ding` message.
Hi @shwetalsoni, 
Thank you for your prompt reply, but these sentences should all start from a verb and omit the subject. How do you think if we change the second one to "Use the chatbot to communicate or do anything on behalf of you."

2021-06-14 05:59 UTC, shwetalsoni commented on docusaurus/docs/getting-started/overview.mdx
> +* It replies with a `dong` message when it recieves a `ding` message.
Changed to **Use the chatbot to communicate or do anything on behalf of you.**

2021-06-14 11:20 UTC, Rohitesh-Kumar-Jain approved these changes
Perfect PR : clean commit history, properly based, relevant screenshots, PR good in scope.

2021-06-14 15:38 UTC, proudofsimin approved these changes
Thank you :)

2021-06-15 05:11 UTC, sbis04 approved these changes

2021-07-06 19:02 UTC, lijiarui requested changes
Pls change as I request, thanks!

2021-07-06 19:02 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +* [Gitpod](getting-started/quick-start.mdx)
I thinks we should add an anchor for Google Cloud Shell and Gitpod link.

2021-07-06 19:02 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +* [Gitpod](getting-started/quick-start.mdx)
I thinks we should add an anchor for Google Cloud Shell and Gitpod link.

2021-07-06 19:02 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +* [Locally on your machine](getting-started/hard-way.mdx)
I think we should change `hard-way` to `running-locally` after #888 changed as I requested.

2021-07-06 19:02 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +
We should remove blank lines here.

2021-07-06 19:02 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +* Supports all [puppets](../puppet-services) like Web, Pad, Windows and Mac.
`like Web, Pad, Windows and Mac.` --> `like Wechat, WhatsApp, WeCom, Lark and so on`

2021-07-07 07:19 UTC, shwetalsoni commented on docusaurus/docs/getting-started/overview.mdx
> +* [Locally on your machine](getting-started/hard-way.mdx)
Yeah sure, I'll change the file name to `running-locally` but here it can only be changed once #888 is merged

2021-07-07 07:21 UTC, shwetalsoni commented on docusaurus/docs/getting-started/overview.mdx
> +* [Gitpod](getting-started/quick-start.mdx)
Actually, I think providing the link to pages is better because a user needs to follow some steps to run ding-dong bot on gitpod and google cloud shell. Going directly to gitpod/google cloud shell link without knowing how to operate it will be inconvenient for the user.

2021-07-07 07:48 UTC, shwetalsoni commented on docusaurus/docs/getting-started/overview.mdx
> +* Supports all [puppets](../puppet-services) like Web, Pad, Windows and Mac.
changed to *like Wechat, WhatsApp, WeCom, Lark and so on*

2021-07-07 09:29 UTC, shwetalsoni commented
Hii @Rohitesh-Kumar-Jain , 
I need some help with git. I did `git pull` inside my `new-getting-started` branch and now the changes of others are also shown in my PR.  I tried doing `git revert` to undo those but couldn't solve it. Can you please tell me how can i fix this.

2021-07-08 18:32 UTC, lijiarui commented
@shwetalsoni You should change `hard-way` to `running-locally`, or the CI will keep red.

2021-07-09 08:30 UTC, shwetalsoni commented
@lijiarui I have turned the CI green.

2021-07-10 07:33 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +* [Gitpod](getting-started/quick-start.mdx)
@shwetalsoni sure, could you file an issue illustrate this then we can tracking for this. Then I will approve this PR.

2021-07-10 07:34 UTC, lijiarui approved these changes
LGTM.

Looking forward to your new issue for tracking!

2021-07-10 07:49 UTC, shwetalsoni commented on docusaurus/docs/getting-started/overview.mdx
> +* [Gitpod](getting-started/quick-start.mdx)
sure @lijiarui , I have updated the status of this PR [here](https://github.com/wechaty/wechaty.js.org/issues/1032)

2021-07-10 07:50 UTC, shwetalsoni commented
@lijiarui I have mentioned this PR here in this issue #1032

2021-07-10 08:06 UTC, lijiarui reviewed
I found you delete the following files, which is unrelated to this PR:
- jekyll/_contributors/simplepad.md
- jekyll/_posts/2021-06-17-puppet-simplepad-hello.md
- jekyll/assets/2021/06-puppet-simplepad-hello/logo.png
- jekyll/assets/2021/06-puppet-simplepad-hello/process.png
- jekyll/assets/contributors/simplepad/avatar.png

2021-07-10 08:08 UTC, lijiarui requested changes
@shwetalsoni  I found you delete the following files, which is unrelated to this PR, and it is a problem:
- jekyll/_contributors/simplepad.md
- jekyll/_posts/2021-06-17-puppet-simplepad-hello.md
- jekyll/assets/2021/06-puppet-simplepad-hello/logo.png
- jekyll/assets/2021/06-puppet-simplepad-hello/process.png
- jekyll/assets/contributors/simplepad/avatar.png

Please recover these files. Please notice that each PR should not change other files

2021-07-10 09:23 UTC, lijiarui commented
@shwetalsoni Also, please make CI green to match the new rules, see: https://github.com/wechaty/wechaty.js.org/issues/1035

2021-07-10 10:06 UTC, shwetalsoni commented
@lijiarui I have restored the files and also added images in webp format.

2021-07-10 11:36 UTC, lijiarui requested changes
Good job, after I look deep into the introduction, I think maybe we can modify more about the introduction, pls change as I request, thanks!

2021-07-10 11:36 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +Wechaty is a powerful software. You will learn the following fundamental features of Wechaty in the getting-started tutorials:
Maybe we should change to the following saying instead of saying `software`, unify with [Official Repo](https://github.com/wechaty/wechaty#hearts-connecting-chatbots)：

```
Wechaty is a RPA (Robotic Process Automation) SDK for Chatbot Makers which can help you create a bot in 6 lines of [JavaScript](https://GitHub.com/Wechaty/wechaty), [Python](https://GitHub.com/Wechaty/python-wechaty/), [Go](https://GitHub.com/Wechaty/go-wechaty/), and [Java](https://GitHub.com/Wechaty/java-wechaty/), with cross-platform support including [Linux, Windows, MacOS](https://github.com/wechaty/wechaty/actions?query=workflow%3ANPM), and [Docker](https://github.com/wechaty/wechaty/actions?query=workflow%3ADocker).
```

2021-07-10 11:36 UTC, lijiarui commented on docusaurus/docs/getting-started/overview.mdx
> +- Turn a WeChat/Whatsapp account into a chatbot, a.k.a Conversational User Interface Automation Software, with just a few lines of code.
Maybe we should add more IM introduction here:

```
Turn different instant messaging (IM) systems (such as WeChat, Wecom，Whatsapp, Lark，Gitter, and TikTok) account into chatbot.

```

2021-07-10 12:02 UTC, lijiarui approved these changes
Good job! Thanks for the contribution!

2021-07-10 12:10 UTC, huan approved these changes

2021-07-10 12:10 UTC, merged