Wechaty Chatbot testing subsection of Explanation section
wechaty/docusaurus pull request #936
Opened 2021-06-11 13:40 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Wechaty chatbot testing |  Joseph Mawa |

This  is **Wechaty chatbot testing** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/121694857-302b8200-cad3-11eb-9986-5a3c8923e724.png)
![image](https://user-images.githubusercontent.com/52580190/121694966-49ccc980-cad3-11eb-9a1d-5d80b868b713.png)
![image](https://user-images.githubusercontent.com/52580190/121695081-65d06b00-cad3-11eb-9895-46914f90e91a.png)
![image](https://user-images.githubusercontent.com/52580190/121695177-7bde2b80-cad3-11eb-96db-84e44b17002c.png)
![image](https://user-images.githubusercontent.com/52580190/121695257-90222880-cad3-11eb-97d0-0edccb919fc9.png)
![image](https://user-images.githubusercontent.com/52580190/121695366-ac25ca00-cad3-11eb-8369-683415ef09a5.png)

2021-06-13 14:47 UTC, proudofsimin approved these changes
Similar feedback again. Please introduce a list with a complete sentence, instead of a partial one that's completed by the list items. See [Introductory sentences for lists](https://developers.google.com/style/lists#introductory-sentences-for-lists).
(But since this is a minor problem, I'll still approve it.)

2021-06-13 14:59 UTC, Rohitesh-Kumar-Jain approved these changes
Perfect PR :  clean commit history, properly based, relevant screenshots, PR good in scope.

2021-07-12 13:12 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-16 16:51 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 19:02 UTC, lijiarui requested changes
I feel a lit bit confuse about this part.

At first, I thought it maybe wechaty testing, but when I dig into it, it seems trying to say chatbot testing, which is unrelated with wechaty. 

@nibble0101 Could you tell me which part reference chatbot testing concept?

Thanks!

2021-07-18 19:02 UTC, lijiarui commented on docusaurus/docs/explainations/chatbot-testing.md
> +title: Wechaty Chatbot testing
We should change to `Testing` here.

2021-07-25 19:15 UTC, lijiarui commented on docusaurus/docs/explainations/chatbot-testing.md
> +title: Wechaty Chatbot testing
@chris-4444 @nibble0101 Please change as I request.

Also, I think the file name should change to `testing.md` too.

2021-07-29 13:44 UTC, lijiarui commented
I'm not quite sure whether this is really related to wechaty. How do you think of this? @huan

2021-07-29 14:04 UTC, huan commented
Chatbot testing is very important for a production environment and enterprise usage.

Wechaty has a testing framework named [wechaty-puppet-mock](https://github.com/wechaty/wechaty-puppet-mock) and a more specific module [wechaty-mocker](https://github.com/wechaty/wechaty-mocker) to help Wechaty developers to do better unit testing for their chatbots.

A conversational testing example can be found at [math_master unit tests](https://github.com/wechaty/wechaty-vorpal-contrib/blob/master/src/contrib/math_master/math_master.spec.ts), I believe we should add that information to this page.

For the other part of this docs page, like the chatbottesting.com etc., I feel they are OK to be there, but should be minor information.

The major information in this page should be how to use **wechaty-puppet-mock** and the **wechaty-mocker**

2021-07-29 14:20 UTC, lijiarui commented
Yeah, I just remember we have this:
- https://github.com/wechaty/puppet-services/wiki
- https://github.com/wechaty/PMC/issues/31

2021-08-02 19:02 UTC, nibble0101 commented on docusaurus/docs/explainations/chatbot-testing.md
> +title: Wechaty Chatbot testing
Changed as requested

2021-08-06 16:13 UTC, lijiarui requested changes
> For the other part of this docs page, like the chatbottesting.com, etc., I feel they are OK to be there but should be minor information.

I feel that there is too much talking about other testing tools, which is actually unrelated to wechaty testing.

2021-08-06 16:13 UTC, lijiarui commented on docusaurus/docs/explainations/testing.md
> +You can read the [unit tests](https://github.com/wechaty/wechaty-vorpal-contrib/blob/master/src/contrib/math_master/math_master.spec.ts) for math_master bot for a full example illustrating the use of
We can add link https://github.com/wechaty/wechaty-vorpal-contrib/tree/master/src/contrib/math_master for math_master bot here.

2021-08-23 13:45 UTC, lijiarui approved these changes
LGTM

2021-08-23 16:41 UTC, merged