How to guide overview
wechaty/docusaurus pull request #947
Opened 2021-06-16 06:40 UTC by abhishek-iiit

## Added Overview Section
![Screenshot from 2021-06-16 12-07-10](https://user-images.githubusercontent.com/69477761/122169877-8f0a4600-ce9b-11eb-98d3-51d69d4af0cc.png)
![Screenshot from 2021-06-16 12-07-18](https://user-images.githubusercontent.com/69477761/122169881-90d40980-ce9b-11eb-9dd1-31914b6ff51d.png)

2021-06-16 08:08 UTC, Rohitesh-Kumar-Jain approved these changes
Perfect PR, pls link to the PR that will be closed if we merge this.

2021-06-16 14:42 UTC, proudofsimin approved these changes
approved as already reviewed in #901.

2021-07-10 10:27 UTC, lijiarui commented
Hi @abhishek-iiit , As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-12 14:31 UTC, Rohitesh-Kumar-Jain commented
@Soumi7 We would be glad if you may once go through the PR, and either request for changes or approve the PR.

2021-07-14 05:23 UTC, vasvi-sood approved these changes
This PR looks Great!

2021-07-29 15:39 UTC, lijiarui requested changes

2021-07-29 15:39 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
I think we should change the title from ` Wechaty How-to guides overview` to `Overview`, change sidebar_label from `How-to Guides: Overview` to `Overview`

2021-07-29 17:31 UTC, abhishek-iiit commented on docusaurus/docs/howto/overview.mdx
Thankyou, changes made as suggested :)

2021-08-23 17:00 UTC, lijiarui requested changes, later dismissed

2021-08-23 17:00 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +<!-- These are some use cases and code snippets to get you started with Redux in a real app. They assume you understand the topics in [basic](#b) and [advanced](#a) tutorials. They are more advanced
It seems you comment on this part and it wouldn't be shown in the docs.

2021-08-23 17:00 UTC, lijiarui commented on docusaurus/docs/howto/overview.mdx
> +<!-- ## Using Puppets with Wechaty (How to switch between puppets) -->
It seems you make them as docs comment here, and it cannot be shown in the docs.

I think this part should be shown in the docs.

2021-08-24 06:36 UTC, abhishek-iiit commented on docusaurus/docs/howto/overview.mdx
> +<!-- These are some use cases and code snippets to get you started with Redux in a real app. They assume you understand the topics in [basic](#b) and [advanced](#a) tutorials. They are more advanced
Yes, the line 11 and the line 9 explains the same process. So, made to comment out the later part :)

2021-09-07 18:24 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 04:49 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit pls remove the merge conflicts

2021-09-09 08:58 UTC, merged