Add DevOps sub-section of the explanation section
wechaty/docusaurus pull request #949
Opened 2021-06-17 06:40 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Wechaty DevOps tools |  Joseph Mawa |

This  is **Wechaty DevOps tools** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/122344561-9ab74480-cf4f-11eb-8f75-38a6e78dc628.png)
![image](https://user-images.githubusercontent.com/52580190/122344639-ad317e00-cf4f-11eb-9159-730539a07467.png)
![image](https://user-images.githubusercontent.com/52580190/122344727-c5090200-cf4f-11eb-9bb1-39f7149a7b8c.png)
![image](https://user-images.githubusercontent.com/52580190/122344812-da7e2c00-cf4f-11eb-8b49-5eeae3046995.png)
![image](https://user-images.githubusercontent.com/52580190/122344882-f08bec80-cf4f-11eb-84ba-6c3d51b63af1.png)

2021-06-18 14:48 UTC, proudofsimin approved these changes
It seems that each letter of npm is low case. Please change *NPM* to *npm*. Thank you.

2021-07-12 13:12 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-12 13:12 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-18 10:02 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 this PR is awaiting your review : )

2021-07-21 12:53 UTC, chris-4444 approved these changes
LGTM.

2021-07-29 14:59 UTC, lijiarui requested changes
It would be better if @huan has some Wechaty Github Action docs or reference link, then we can add more to DevOps tools part.

2021-07-29 14:59 UTC, lijiarui commented on docusaurus/docs/explainations/devops-tools.md
> +title: Wechaty DevOps tools
We should change this to `DevOps Tools` Since we don't need to emphasize too much wechaty in wechaty docs.

2021-07-29 14:59 UTC, lijiarui commented on docusaurus/docs/explainations/devops-tools.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
We should change a more related image here.

2021-07-29 15:03 UTC, huan commented
I'd like to add the following two blog post links to this doc page:

1. https://wechaty.js.org/2019/06/12/chatie-devops-toolset/
2. https://wechaty.js.org/2020/06/20/wonderful-wechaty-devops-tools/

Thanks!

2021-08-02 11:18 UTC, nibble0101 commented on docusaurus/docs/explainations/devops-tools.md
> +title: Wechaty DevOps tools
Changed to `DevOps Tools`.

2021-08-02 11:18 UTC, nibble0101 commented on docusaurus/docs/explainations/devops-tools.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Removed image

2021-08-23 16:28 UTC, lijiarui commented
I think it would be better if you can merge these two blogs in the docs, then the docs can be easy to read. (At least add the blog image in the docs.)

https://wechaty.js.org/2019/06/12/chatie-devops-toolset/
https://wechaty.js.org/2020/06/20/wonderful-wechaty-devops-tools/

2021-08-23 16:29 UTC, lijiarui requested changes
I think it would be better if you can merge these two blogs in the docs, then the docs can be easy to read. (At least add the blog image in the docs.)

https://wechaty.js.org/2019/06/12/chatie-devops-toolset/
https://wechaty.js.org/2020/06/20/wonderful-wechaty-devops-tools/

2021-09-06 14:44 UTC, nibble0101 commented
> I think it would be better if you can merge these two blogs in the docs, then the docs can be easy to read. (At least add the blog image in the docs.)
> 
> https://wechaty.js.org/2019/06/12/chatie-devops-toolset/
> https://wechaty.js.org/2020/06/20/wonderful-wechaty-devops-tools/

@lijiarui  I have merged the two blog posts and added the images.

2021-09-07 18:25 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-11 14:51 UTC, huan reviewed
Please move `docusaurus/static/img/docs/devops-tools/*` to `docusaurus/static/img/docs/explanations/devops-tools/`, to make the image folder more structure.

2021-09-14 03:40 UTC, lijiarui requested changes

2021-09-14 03:40 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +This npm package is a wrapper for the [git-scripts](https://www.npmjs.com/package/git-scripts) package. It provides githooks integration for chatie projects. In addition to the features that come wit
Please change to https://github.com/chatie/git-scripts

2021-09-14 03:43 UTC, lijiarui requested changes
Please change image folder from devops-tools to  devops-toolset

2021-09-14 03:43 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +title: DevOps tools
DevOps tools --DevOps Toolset

2021-09-14 03:43 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-devops-toolset.webp)
DevOps tools --DevOps Toolset

2021-09-14 03:43 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-semver.webp)
DevOps tools --DevOps Toolset

2021-09-14 03:43 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-git-scripts.webp)
DevOps tools --DevOps Toolset

2021-09-14 03:43 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-eslint-config.webp)
DevOps tools --DevOps Toolset

2021-09-14 03:43 UTC, lijiarui commented on docusaurus/sidebars.ts
> +    'explanations/devops-tools',
devops-tools --> devops-toolset

2021-09-14 15:39 UTC, nibble0101 commented on docusaurus/docs/explanations/devops-tools.md
> +This npm package is a wrapper for the [git-scripts](https://www.npmjs.com/package/git-scripts) package. It provides githooks integration for chatie projects. In addition to the features that come wit
Changed URL.

2021-09-14 15:40 UTC, nibble0101 commented on docusaurus/docs/explanations/devops-tools.md
> +title: DevOps tools
Renamed title.

2021-09-14 15:40 UTC, nibble0101 commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-devops-toolset.webp)
Changed alternative text.

2021-09-14 15:40 UTC, nibble0101 commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-semver.webp)
Changed alternative text.

2021-09-14 15:41 UTC, nibble0101 commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-git-scripts.webp)
Changed alternative text.

2021-09-14 15:41 UTC, nibble0101 commented on docusaurus/docs/explanations/devops-tools.md
> +![Devops tools](../../static/img/docs/explanations/devops-tools/chatie-eslint-config.webp)
Changed alternative text.

2021-09-14 15:42 UTC, nibble0101 commented on docusaurus/sidebars.ts
> +    'explanations/devops-tools',
Changed

2021-09-15 15:03 UTC, lijiarui commented on docusaurus/docs/explanations/devops-tools.md
> +This npm package is a wrapper for the [git-scripts](https://www.npmjs.com/package/git-scripts) package. It provides githooks integration for chatie projects. In addition to the features that come wit
No, you didn't change the URL. 

Please change `https://github.com/nkzawa/git-scripts` to `https://github.com/chatie/git-scripts`

2021-09-15 15:04 UTC, lijiarui requested changes

2021-09-15 15:04 UTC, lijiarui commented on docusaurus/docs/explanations/devops-toolset.md
> +This npm package is a wrapper for the [git-scripts](https://github.com/chatie/git-scripts) package. It provides githooks integration for chatie projects. In addition to the features that come with gi
No, you didn't change the URL. 

Please change `https://github.com/nkzawa/git-scripts` to `https://github.com/chatie/git-scripts`

2021-09-16 03:25 UTC, Rohitesh-Kumar-Jain approved these changes
link has been updated

2021-09-21 10:52 UTC, lijiarui approved these changes
LGTM! Cheers!

2021-09-22 04:39 UTC, merged