Add Troubleshooting sub-section of the Explanation section
wechaty/docusaurus pull request #950
Opened 2021-06-17 07:16 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Troubleshooting  |  Chris Estepa |

This  is **Troubleshooting** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/122349253-bf61eb00-cf54-11eb-8ecf-555d86ee6418.png)
![image](https://user-images.githubusercontent.com/52580190/122349348-d7d20580-cf54-11eb-89bc-4227908f3c6f.png)
![image](https://user-images.githubusercontent.com/52580190/122349467-f59f6a80-cf54-11eb-8f53-09a02b6318c2.png)

2021-06-18 15:46 UTC, proudofsimin requested changes
Hi Chris,
I know currently we need more information to enrich the content. @huan and @lijiarui please let Chris know if there's anything she could add. In addition, Could you categorize the questions in case we get more questions in the future? Or if it's hard to categorize at this time, at least we could separate the questions to *customer side* and *developer side*. How do you think?

2021-07-12 13:10 UTC, Rohitesh-Kumar-Jain approved these changes
I have given my feedback on their tracking issue about this page.

2021-07-12 13:11 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 and @nibble0101 pls address Simin's comments so that we can merge the PR in the best way the community thinks is right.

2021-07-13 12:01 UTC, chris-4444 commented
@nibble0101 @Rohitesh-Kumar-Jain @proudofsimin I have sent this in in our group mail. This is the info I got from Rajiv and Abishek and will add if needed. Yep Simin, I will categorize just like what you have suggested.

2021-07-14 16:24 UTC, proudofsimin commented
Hi @chris-4444, 
Since we don't have many questions now it seems ok to just list down all of them instead of putting them into different categories, but in the future it would be hard for our users to search for what they need. For a healthy document it's better if we set up the foundation at the very beginning. Thank you.

2021-07-15 13:22 UTC, nibble0101 commented
Hi @iamrajiv 
I understand you have ever encountered the issue described in the screenshot below. The solution I provide here works on my end. Could you test whether it will work on your end too. Thanks.

![image](https://user-images.githubusercontent.com/52580190/125794118-61c10fd3-ca87-4026-92f5-5d478b95b7cc.png)
![image](https://user-images.githubusercontent.com/52580190/125794240-d666dcf8-e7ea-4ea5-ad2d-1233456bd8ac.png)
![image](https://user-images.githubusercontent.com/52580190/125794408-19aaee3a-95a2-46e5-acf5-1572c7b9f9ed.png)

2021-07-15 16:41 UTC, proudofsimin approved these changes
This is great. Thank you:)

2021-07-16 07:00 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 18:13 UTC, lijiarui commented
@nibble0101 Please make Github action green then I will review this PR.

2021-07-18 20:29 UTC, nibble0101 commented
You can review now @lijiarui

2021-07-25 19:18 UTC, lijiarui requested changes

2021-07-25 19:18 UTC, lijiarui commented on docusaurus/docs/explainations/troubleshooting.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I think we should change a more related image here, since this logo has appeared too much in the doc.

2021-07-25 19:18 UTC, lijiarui commented on docusaurus/docs/explainations/troubleshooting.md
> +```
How about we change to `mdx` file and use a tab like this: http://wechaty.js.org/docs/getting-started/running-locally#4-run-the-bot

2021-07-30 16:27 UTC, nibble0101 commented on docusaurus/docs/explainations/troubleshooting.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Removed the logo instead.

2021-07-30 16:29 UTC, nibble0101 commented on docusaurus/docs/explainations/troubleshooting.md
> +```
Changed as requested

2021-07-31 17:26 UTC, lijiarui commented
LGTM.

But I'm not quite sure about the difference between the troubleshooting part and the FAQ part.

@huan  How do you think about this?

2021-07-31 17:27 UTC, lijiarui approved these changes

2021-08-02 09:14 UTC, merged