zhang704
wechaty/docusaurus pull request #954
Opened 2021-06-17 10:26 UTC by zhang704

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-06-17 10:46 UTC, huan requested changes
Thank you very much for sharing your experience with the community!

This post is good, please follow my reviews.

2021-06-17 10:46 UTC, huan commented on jekyll/_posts/2021-06-17-wxrobot-backend-management.md
> +[![Powered by Wechaty](https://img.shields.io/badge/Powered%20By-Wechaty-green.svg)](https://github.com/chatie/wechaty)
```diff
- https://github.com/chatie/wechaty
+ https://github.com/wechaty/wechaty
```

2021-06-17 10:46 UTC, huan commented on jekyll/_posts/2021-06-17-wxrobot-backend-management.md
> +- 感谢 [Wechaty](https://wechaty.github.io/) 团队提供微信机器人 `SDK`，让开发者可以专注于业务代码。
```diff
- https://wechaty.github.io
+ https://wechaty.js.org
```

2021-06-17 10:46 UTC, huan commented on jekyll/_posts/2021-06-17-wxrobot-backend-management.md
> +原来2017年之后注册的微信号都无法登录网页版微信，而2017年之前注册得微信账号也有很大几率登录不上，找朋友试了也都不行。
This situation has changed since https://wechaty.js.org/2021/04/13/wechaty-uos-web/ had been published.

Please take a look.

2021-06-18 01:54 UTC, zhang704 commented
@huan please review

2021-06-18 09:02 UTC, zhang704 commented
@huan Excuse me, if you are free, please review the PR, thx.

2021-06-18 09:34 UTC, huan requested changes
Please fix the errors that CI reported and push again.

P.S. you can run the test locally by running `npm test` before push.

2021-06-18 10:31 UTC, zhang704 commented
@huan thx, I have solved it all

2021-06-18 11:44 UTC, huan commented
Let's check it by running GitHub Actions.

2021-06-18 14:06 UTC, zhang704 commented
@huan oh, checks passed, Really gratifying.

2021-06-18 16:39 UTC, huan approved these changes
LGTM

2021-06-18 16:39 UTC, merged

2021-06-18 17:44 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited zhang704 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!