Added OpenAPI learning resources
wechaty/docusaurus pull request #956
Opened 2021-06-17 12:55 UTC by iamrajiv

2021-06-19 10:16 UTC, proudofsimin requested changes
Hi Rajiv,
Can you explain how you organize the sequence of these resources? It seems just random materials putting together, and most of them are from the same website. If you are only providing some relevant information about OpenAPI, the resources are better to cover different aspects (or from different organizations). On the other hand, if you are guiding readers what an OpenAPI is (as I saw you put the tutorials in), maybe you could consider re-organize the topics a little bit (from basic to advanced). Also a short description of your purpose of this page is required at the beginning.
Btw, please remove the link to each topic. You don't need to link them twice.

2021-06-19 12:38 UTC, iamrajiv commented
Hi, @proudofsimin thank you for the review and suggestion. I have structured the learning resources section and removed the duplicate links. I have provided learning resources according to Wechaty user requirements and which are not covered in PR [#917](https://github.com/wechaty/wechaty.js.org/pull/917). I have added these learning resources at the end because that will be more suitable since after the merge of PR [#917](https://github.com/wechaty/wechaty.js.org/pull/917) other things will be added in front of the document that covers basic and general learning about OpenAPI. If a user wants to learn more I have added the relevant links in additional resources they can go through it.

2021-06-20 10:13 UTC, proudofsimin approved these changes

2021-07-12 14:43 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-12 17:22 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.md
> +
> It seems just random materials putting together, and most of them are from the same website. If you are only providing some relevant information about OpenAPI, the resources are better to cover different aspects (or from different organizations). On the other hand, if you are guiding readers what an OpenAPI is (as I saw you put the tutorials in), maybe you could consider reconstruct the topics a little bit (from basic to advanced). Also a short description of your purpose of this page is required at the beginning.

I agree with @proudofsimin 

I think we may more information from README in [wechaty openapi official repo](https://github.com/wechaty/openapi), content in README is more relative to wechaty docs.

We can have some learning resources, but I don't think in a wechaty openai introduction page, 2/3 of the content is introducing resources, it looks a bit overwhelming.

2021-07-13 00:12 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.md
> +
@lijiarui I have removed unnecessary resources and added only relevant resources about OpenAPI.

2021-07-13 03:54 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.md
> +
Hi @iamrajiv Thanks for removing unnecessary resources,  I think we may add more information from README in [wechaty openapi official repo](https://github.com/wechaty/openapi), content in README is more relative to wechaty docs.

2021-07-13 08:38 UTC, iamrajiv commented on docusaurus/docs/polyglot/openapi/overview.md
> +
@lijiarui Yeah I made a separate PR for that https://github.com/wechaty/openapi/pull/18. This PR is an addition to https://github.com/wechaty/wechaty.js.org/pull/917 so that people can get an overview on the website too about learning resources of OpenAPI.

2021-07-14 18:08 UTC, lijiarui commented on docusaurus/docs/polyglot/openapi/overview.md
> +
great! I think it lgtm.

2021-07-14 18:08 UTC, lijiarui approved these changes

2021-07-15 21:09 UTC, merged

2021-07-15 21:10 UTC, huan commented
Thank you very much for adding resources to the open API docs!