Update Wechaty Plugin Overview page under Tutorials
wechaty/docusaurus pull request #957
Opened 2021-06-17 17:29 UTC by sbis04

I have updated the "**Using Plugin with Wechaty**" section under **Tutorials**. The page is now divided into some sub-sections containing the following:

<img width="296" alt="Sub-menu" src="https://user-images.githubusercontent.com/43280874/122444881-9f671180-cfbe-11eb-826d-1339b291fc92.png">

This PR contains the updated sub-menu and the contents of the **Overview** page. The plugin tutorials will be included in the rest of the pages in future PRs.

The Overview page looks like this:

![Plugin Overview page](https://user-images.githubusercontent.com/43280874/122445481-39c75500-cfbf-11eb-89e0-fbc1d213e969.png)

Tag: #891

2021-06-19 14:45 UTC, proudofsimin reviewed
Hi @sbis04, 
Have you contacted the reference team to add the plugin section? Thank you.

2021-06-19 14:45 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +title: Event Logger Plugin
Please only capitalize only the first letter of the sentence, except for technical terms.

2021-06-19 14:45 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/message-awaiter.md
> +title: Message Awaiter Plugin
Please only capitalize only the first letter of the sentence.

2021-06-19 14:45 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +title: QR Code Terminal Plugin
Please only capitalize only the first letter of the sentence, except for technical terms.

2021-06-20 10:58 UTC, sbis04 commented
@proudofsimin I have fixed the title capitalizations.

Yes, I have contacted the references team, and they have confirmed that they will add the plugins section under References.

2021-06-21 16:12 UTC, proudofsimin approved these changes

2021-07-06 17:55 UTC, lijiarui requested changes
Pls change as I request.

2021-07-06 17:55 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/overview.md
> +The first Wechaty Plugin system was design by our core team developer [@gcaufy](https://github.com/gcaufy), you can get more information about it [here](https://github.com/wechaty/wechaty/pull/1946).
pls change `core team developer` to `Wechaty Commiter`

2021-07-06 17:55 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/overview.md
> +1. [**Wechaty Xyao**](https://github.com/watertao/wechaty-plugin-xyao) by [@watertao](https://github.com/watertao) - Wechaty Xyao Plugin gives bot ability to execute instruction with distributed brai
Pls sync this with: https://github.com/wechaty/wechaty-plugin-contrib#wechaty-plugin-directory

We have a new plugin: `Wechaty-fanli by @Leo_chen - help you quickly access the rebate robot about taobao`

2021-07-06 18:01 UTC, lijiarui reviewed
If we can add a video talk page of the plugin part, it would be more clear for developers.

2021-07-06 18:01 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/overview.md
> +
We can also add plugin launch talk vedio here:

[plugin launch talk vedio](https://www.youtube.com/watch?v=tfGZXoe_aA4)

Also, I have a suggestion: how about we add a new page showing this video? You can refer the description of the video:

```
Wechaty插件开源月活动，微信群222人，Webinar在线56人。腾讯微信小程序框架开源项目 Wepy作者，Wechaty插件架构师Gcaufy介绍了插件的设计理念、开发历程；Wechaty Puppet Donut/Padplus作者高原介绍了插件的商业化落地展望，Wechaty Plugin开发者王墨炱为大家Live Coding了基于插件的Wechaty开发。 ​​​​

议程：5月30日（周六）下午

14:00 - 14:05 Wechaty 社区团队 「插件开源月」活动开幕及议程介绍
14:05 - 14:25 Wechaty 作者 李卓桓 Wechaty项目和社区生态介绍
14:25 - 14:55 Wechaty Plugin 设计师，腾讯微信小程序框架开源项目Wepy 作者 Gcaufy 插件系统开发历程及应用

14:55 - 15:00 休息

15:00 - 15:30 Wechaty Puppet Donut/Padplus 作者 高原 Wechaty 插件的商业化落地展望
15:30 - 16:00 Wechaty Plugin开发者 王墨炱 基于插件的Wechaty开发

- https://github.com/wechaty
- https://mp.weixin.qq.com/s/8ISuUUGO1r...

```

2021-07-07 05:41 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/overview.md
> +1. [**Wechaty Xyao**](https://github.com/watertao/wechaty-plugin-xyao) by [@watertao](https://github.com/watertao) - Wechaty Xyao Plugin gives bot ability to execute instruction with distributed brai
Updated it

2021-07-07 05:43 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/overview.md
> +
I think keeping the video on this overview page would keep to docs concise and easy to navigate. I'll do update this page with the video.

2021-07-07 05:45 UTC, sbis04 commented
@lijiarui I have added the video along with the agenda. The updated page looks like this now:

![Plugin Overview page](https://user-images.githubusercontent.com/43280874/124706227-8cd45e00-df14-11eb-96f9-63fc3d84c11c.png)

2021-07-07 18:52 UTC, lijiarui requested changes
Thanks for the improvement, after fix these two issues, I will approve this PR.

2021-07-07 18:52 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/overview.mdx
> +* [NPM package of Wechaty Plugin Contrib](https://www.npmjs.com/package/wechaty-plugin-contrib)
We can add one more link here:

`[Why we build Wechaty Plugin Contrib](https://mp.weixin.qq.com/s/8ISuUUGO1rZMYOJmpRpKUQ)`

2021-07-07 18:52 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/overview.mdx
> +- [15:30](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=930s) Wechaty Plugin开发者 王墨炱 基于插件的Wechaty开发
How about we translate this into English.

```
- [14:00](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=840s) Wechaty Community Team, "Plugin Open Source Month" event opening and agenda introduction
- [14:05](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=845s) Wechaty Creator [Huan](https://github.com/huan) ,Introduction and community ecology of Wechaty
- [14:25](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=865s) Wechaty Plugin Designer，Creator of [Wepy](https://github.com/tencent/wepy)(Wepy is Tencent mini-app opensource framework) [Gcaufy](https://github.com/Gcaufy), Development process and application of plugin system
- [14:55](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=895s) TeaBreak
- [15:00](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=900s) Wechaty Puppet Creator, Co-Founder of Juzi.Bot [Yuan Gao](https://github.com/windmemory),  Prospects for the commercialization of Wechaty plugins
- [15:30](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=930s) Wechaty Plugin Contributor [JesseWeb](https://github.com/JesseWeb), How to build with Wechaty Plugin
```

2021-07-08 16:57 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/overview.mdx
> +* [NPM package of Wechaty Plugin Contrib](https://www.npmjs.com/package/wechaty-plugin-contrib)
Have added the link

2021-07-08 16:58 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/overview.mdx
> +- [15:30](https://www.youtube.com/watch?v=tfGZXoe_aA4&t=930s) Wechaty Plugin开发者 王墨炱 基于插件的Wechaty开发
Thanks for providing the English translations! Have updated it.

2021-07-08 16:59 UTC, sbis04 commented
@lijiarui I have made the suggested changes.

2021-07-08 18:10 UTC, merged