Customise bot
wechaty/docusaurus pull request #958
Opened 2021-06-17 19:58 UTC by abhishek-iiit

## Add events and customise a bot
![Screenshot from 2021-06-18 00-59-11](https://user-images.githubusercontent.com/69477761/122462799-a7c94780-cfd2-11eb-8b9f-12c2bee49a6f.png)
![Screenshot from 2021-06-18 00-59-27](https://user-images.githubusercontent.com/69477761/122462804-a9930b00-cfd2-11eb-887e-fdb8b29259f8.png)
![Screenshot from 2021-06-18 00-59-38](https://user-images.githubusercontent.com/69477761/122462813-aac43800-cfd2-11eb-99af-4da02ec1922c.png)
![Screenshot from 2021-06-18 00-59-53](https://user-images.githubusercontent.com/69477761/122462818-abf56500-cfd2-11eb-9534-f6eed778392f.png)
![Screenshot from 2021-06-18 01-00-04](https://user-images.githubusercontent.com/69477761/122462824-ad269200-cfd2-11eb-9d57-1b1a337ff1bb.png)
![Screenshot from 2021-06-18 01-00-15](https://user-images.githubusercontent.com/69477761/122462832-adbf2880-cfd2-11eb-8c6f-b101edf14953.png)
![Screenshot from 2021-06-18 01-00-24](https://user-images.githubusercontent.com/69477761/122462833-aef05580-cfd2-11eb-9911-dd91dd65486a.png)
![Screenshot from 2021-06-18 01-00-32](https://user-images.githubusercontent.com/69477761/122462838-b0218280-cfd2-11eb-8958-d121b993bdca.png)
![Screenshot from 2021-06-18 01-00-42](https://user-images.githubusercontent.com/69477761/122462841-b152af80-cfd2-11eb-9870-a34da1d42376.png)
![Screenshot from 2021-06-18 01-00-50](https://user-images.githubusercontent.com/69477761/122462845-b1eb4600-cfd2-11eb-93a5-752459999209.png)

2021-06-19 17:17 UTC, proudofsimin requested changes
1. Please correct all the typos and add colons/ commas you forgot (I didn't point out all of them).
2. Please remove the *TODO* in each event and replace them with short introductions of the events' functions. Like what you did in the `scan` event is great. (but don't forget the `` tag and a period at the end.)

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +For simplicity, this tutorial will guide you to create a bot in javascript but but you can choose between various programming languages available.
Before starting this guide, make sure you are already familiar with the ding dong bot. If not, go to __. In this section, you will learn how to add various events to a bot. Events are functions that define the operations a bot can perform. Some common events include `login`, `logout`, `onMessage`. The guide will demonstrate in JavaScript, but you can choose between various programming languages available.

- Put the prerequisite at the very beginning, so if the users are not equipped with the knowledge, they could leave first.
- And why are you separate the three sentences to three paragraphs?

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +<li>In the termial write the following command</li>
In the terminal, type the following command:

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +<li>In the terminal install the necesary dependencies</li>
In the terminal[,] install the necesary dependencies

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +<li> For whatsapp:</li>
please use their official name: WhatsApp

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +<li>For wechat</li>
WeChat

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +But before that we need to add events to the bot. For following along the tutorial use the javascript code from the polyglot.
Remove this sentence and add a step in between: Add events to the bot. See the following examples.

2021-06-19 17:17 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +### `Scan` Event
`scan` is an event. lower case, please.

2021-06-19 17:45 UTC, abhishek-iiit commented on docusaurus/docs/howto/event.md
> +For simplicity, this tutorial will guide you to create a bot in javascript but but you can choose between various programming languages available.
Thanks a lot, Simin for the suggested changes, we will get improvement done.
We broke into paragraphs so as to keep it as short as possible (not to look like a lengthy one).

2021-06-19 17:53 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +For simplicity, this tutorial will guide you to create a bot in javascript but but you can choose between various programming languages available.
I'm sorry my bad. I forgot it. Could you please point out where to review next time for me ? Many thanks. Then just correct the typos and this PR is done.

2021-06-19 18:11 UTC, abhishek-iiit commented on docusaurus/docs/howto/event.md
> +For simplicity, this tutorial will guide you to create a bot in javascript but but you can choose between various programming languages available.
Thank you, Simin! I Will surely try to comment on the changes I did from the next PR :)

2021-06-21 16:06 UTC, proudofsimin commented on docusaurus/docs/howto/event.md
> +For simplicity, this tutorial will guide you to create a bot in javascript but but you can choose between various programming languages available.
> Before starting this guide, make sure you are already familiar with the ding dong bot. If not, go to __. In this section, you will learn how to add various events to a bot. Events are functions that define the operations a bot can perform. Some common events include `login`, `logout`, `onMessage`. The guide will demonstrate in JavaScript, but you can choose between various programming languages available.

Ah I'm so sad. I even rewrote it for you, but why didn't you change it ?

2021-06-21 16:55 UTC, abhishek-iiit commented on docusaurus/docs/howto/event.md
> +For simplicity, this tutorial will guide you to create a bot in javascript but but you can choose between various programming languages available.
So sorry, I misinterpreted the message, so as to change the typo only. Will change it tonight as soon as possible .

2021-06-22 16:47 UTC, proudofsimin approved these changes
Thank you :)

2021-07-05 14:52 UTC, abhishek-iiit commented
@Rohitesh-Kumar-Jain I request you to please review this PR :)

2021-07-12 14:28 UTC, Rohitesh-Kumar-Jain approved these changes
LGTM

2021-07-12 14:30 UTC, Rohitesh-Kumar-Jain commented
@vasvi-sood  We would be glad if you may once go through the PR, and either request for changes or approve the PR.

team-mates needs to approve each other's PRs to get them merged.

2021-07-14 05:21 UTC, vasvi-sood requested changes
Make the changes before it can be merged.

2021-07-14 05:21 UTC, vasvi-sood commented on docusaurus/docs/howto/event.md
> +### `scan` Event
Add the description of the events.

2021-07-21 14:08 UTC, vasvi-sood commented
@Rohitesh-Kumar-Jain and @proudofsimin all changes have been made. Kindly review it and add the ready to merge label.

2021-07-21 18:06 UTC, vasvi-sood approved these changes

2021-07-22 18:26 UTC, abhishek-iiit commented
Thankyou Vasvi for putting up the changes :)

2021-09-07 18:28 UTC, huan approved these changes
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

2021-09-08 04:52 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit resolve conflicts and then merge

2021-09-08 19:14 UTC, abhishek-iiit commented
> @abhishek-iiit resolve conflicts and then merge

@Rohitesh-Kumar-Jain resolved conflict issue :)

2021-09-10 06:24 UTC, abhishek-iiit commented
> @abhishek-iiit resolve conflicts and then merge

Conflict resolved and merging now :)

2021-09-10 06:25 UTC, merged