Add tutorial for EventLogger plugin
wechaty/docusaurus pull request #963
Opened 2021-06-18 15:15 UTC by sbis04

I have added the tutorial for the `EventLogger` plugin. The page contents are as follows:

![EventLogger plugin](https://user-images.githubusercontent.com/43280874/122582358-b3217f00-d075-11eb-9fdb-f6d4b9b906d7.png)

Tag #891

2021-06-20 09:10 UTC, proudofsimin approved these changes
Hi, 
This is great. Please just change the v-ing in steps to present tense. Thank you.

2021-06-20 09:10 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +### 4. Writing code for bot
Write

2021-06-20 09:10 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +### 5. Running the bot
Run

2021-06-20 09:10 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +### 2. Integrating the plugin
Integrate

2021-06-20 10:55 UTC, sbis04 commented
@proudofsimin I have changed the -ing(s) in steps to present tense and fixed the title capitalizations.

2021-06-25 03:16 UTC, sbis04 commented
Hi @proudofsimin @Rohitesh-Kumar-Jain in the previous meeting we were confused where to keep the simple bot, so that we can use it to show how to add the plugins.

I and @shwetalsoni discussed about this, and we decided to keep the simple bot inside **Examples > Basic > Starter Bot**. And, we will show how to add the plugins using this bot.

<img width="278" alt="Sidebar examples basic" src="https://user-images.githubusercontent.com/43280874/123363755-cc07c400-d590-11eb-8fed-10927178a540.png">

The updated **Event Logger plugin** page looks like this:

![Event Logger plugin](https://user-images.githubusercontent.com/43280874/123364200-a7601c00-d591-11eb-86dd-4567c2dee31c.png)

2021-06-27 16:21 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +
Hi, do you think if it's better if we add a step one telling our user to create a simple bot first? Anyway it is still a step they need to do first.

1. Create a starter bot

Follow the instructions in [Starter bot] to create the the foundation.

2. Install dependency
...

2021-06-27 16:23 UTC, proudofsimin reviewed
I love your new organization so much. This is so good!

2021-06-28 00:48 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +
Yes, I have added step one for telling the users to create a starter bot

2021-07-06 18:09 UTC, lijiarui requested changes
Pls change as I request, thanks!

2021-07-06 18:09 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
I thinks we should add link for `**Starter Bot*` page and then users can refer that part if he don't know how to build a starter bot.

2021-07-06 18:09 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +#### Linux/macOS
I think we should unify the style here, @shwetalsoni did a good job, it looks like this：

![image](https://user-images.githubusercontent.com/6419514/124647062-0d20a200-dec8-11eb-863c-8cff0c1fd114.png)

You can use code like this:

```markdown
<Tabs
  groupId="operating-systems"
  defaultValue="linux"
  values={[
    { label: 'Linux',   value: 'linux', },
    { label: 'macOS',   value: 'mac', },
    { label: 'Windows', value: 'windows', },
  ]
}>

<TabItem value="linux">

```

2021-07-06 18:09 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +
Add video link reference here: https://www.youtube.com/watch?v=tfGZXoe_aA4

2021-07-07 05:49 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/event-logger.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
Yes, I'll add the link. Currently, the **Starter Bot** page isn't there on the docs, we have it further down on our proposal timeline. Once, the page is ready we will also update the link here.

2021-07-08 17:46 UTC, lijiarui commented
ping @sbis04

2021-07-08 18:17 UTC, lijiarui commented
Pls resolve the conflict, then I will approve this PR.

2021-07-08 19:05 UTC, sbis04 commented
@lijiarui Have made the CI green.

2021-07-10 07:15 UTC, lijiarui approved these changes
LGTM

2021-07-10 09:22 UTC, lijiarui commented
@sbis04 Please make CI green to match the new rules, see: https://github.com/wechaty/wechaty.js.org/issues/1035

2021-07-10 10:48 UTC, sbis04 commented
@lijiarui I have converted the image to `.webp` format and made the CI green.

2021-07-10 12:12 UTC, huan approved these changes

2021-07-10 12:13 UTC, merged