Manage contact
wechaty/docusaurus pull request #964
Opened 2021-06-20 10:37 UTC by abhishek-iiit

Added Explanation and Contact details
- [x] added basics details 
- [x] added explanations to used function
- [ ] add more examples
![Screenshot from 2021-06-20 16-05-33](https://user-images.githubusercontent.com/69477761/122670800-6fe41f00-d1e1-11eb-93e6-334a76bf3a69.png)
![Screenshot from 2021-06-20 16-05-45](https://user-images.githubusercontent.com/69477761/122670802-707cb580-d1e1-11eb-9a31-60f66e97a79b.png)

2021-06-22 16:24 UTC, proudofsimin requested changes
I would say that this is a great document for reference, but not suitable for how-to guides. In how-to guides, our users are expected to see step by step guides with clear instructions. However, in this topic, I saw you gave some code snippets and listed out some functions with instructions. Although the code snippets might be quite self-explanatory maybe, in how-to guides we shall take the active role to explain, instead of just providing information to the users.

2021-06-27 11:55 UTC, abhishek-iiit commented
Please @proudofsimin review my changes as suggested. Thankyou :)

2021-06-29 16:24 UTC, proudofsimin approved these changes
Approved with the document format. You're doing great! But again, be careful of the typos and don't forget the space between two sentences.

2021-06-29 16:24 UTC, proudofsimin commented on docusaurus/docs/howto/contact.md
> +The steps outlined here mainly focuses on working with Javascript, but user are free to switch between any languages.All wechaty contacts are encapsulated as a Contact.
The steps outlined here mainly focuse~s~ on working with Javascript,...

> any languages.All wechaty
Add a space between the two sentence.

2021-06-29 16:24 UTC, proudofsimin commented on docusaurus/docs/howto/contact.md
> +The below function needs a basic scipt that can help run the bot. The basic script starts by importing the code from [Github/Contact-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc17
typo: scipt.

The functions below require a basic script to help run the bot. Import the codes from [Github/Contact-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/contact-bot.ts) for the basic script, and integrate the codes below.

2021-07-02 08:47 UTC, abhishek-iiit commented
Changes done as suggested :)

2021-07-05 14:54 UTC, abhishek-iiit commented
I request you to please this PR @Rohitesh-Kumar-Jain :)

2021-07-11 12:56 UTC, Rohitesh-Kumar-Jain reviewed
I have seen a lot of agreement violations in your documentation, not just this documentation I see violations, but in your other documents, I have seen this. So just to avoid this in the future pls go through this, to get a better idea of what I am talking about. 
https://academicanswers.waldenu.edu/faq/73188

2021-07-11 13:57 UTC, abhishek-iiit commented
Sorry, for the inconvenience. Will reviews this as well as all other PR after going through the link you provided.

2021-07-14 05:19 UTC, vasvi-sood reviewed
This PR Looks good to me.

2021-08-12 05:51 UTC, vasvi-sood approved these changes

2021-09-07 18:30 UTC, huan requested changes, later dismissed

2021-09-07 18:30 UTC, huan commented on docusaurus/docs/howto/contact.mdx
> +const { Contact } = require('wechaty')
Please always use ESM (import... from...) instead of CommonJS.

2021-09-13 08:44 UTC, Rohitesh-Kumar-Jain commented
pls work upon merging the PRs faster @abhishek-iiit

2021-09-16 21:07 UTC, abhishek-iiit commented on docusaurus/docs/howto/contact.mdx
> +const { Contact } = require('wechaty')
changes done as suggested :)

2021-09-16 21:19 UTC, abhishek-iiit commented
@huan @Rohitesh-Kumar-Jain  I request to look for the approval, so that we can continue towards merging this PR

2021-09-17 05:20 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing the suggested changes : )

2021-09-18 18:06 UTC, lijiarui requested changes
Hi @abhishek-iiit 

I found this doc is referred to as an outdated example code, we should not use 2018 code in https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/contact-bot.ts

Please change all of the related code to the new one:  
https://github.com/wechaty/wechaty-getting-started/blob/main/examples/basic/contact-bot.js

2021-09-18 18:06 UTC, lijiarui commented on docusaurus/docs/howto/contact.mdx
> +Use the guide to help you integrate additional functions to an existing project which is present at [Github/Contact-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe5335154
https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/contact-bot.ts is an outdated file, which is committed in 2018. We should update to the latest version: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/basic/contact-bot.js

2021-09-18 18:06 UTC, lijiarui commented on docusaurus/docs/howto/contact.mdx
> +* Your system must have [Node.js](https://nodejs.org/en/download/package-manager/) installed (version >= 12).
`(version >= 12).` should change to `(version >= 16).` Since wechaty has force updated to Node 16.

2021-09-18 18:06 UTC, lijiarui commented on docusaurus/docs/howto/contact.mdx
> +The functions below require a basic script to help run the bot. Import the codes from [Github/Contact-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/co
https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/contact-bot.ts is an outdated file, which is committed in 2018. We should update to the latest version: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/basic/contact-bot.js

2021-09-18 18:06 UTC, lijiarui commented on docusaurus/docs/howto/contact.mdx
> +* [Wechaty Bot Example](https://github.com/wechaty/wechaty/tree/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples).
Please change to https://github.com/wechaty/wechaty-getting-started/tree/main/examples

2021-09-21 10:34 UTC, abhishek-iiit commented on docusaurus/docs/howto/contact.mdx
> +Use the guide to help you integrate additional functions to an existing project which is present at [Github/Contact-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe5335154
thankyou @lijiarui, changes done as suggested :)

2021-09-21 16:16 UTC, lijiarui approved these changes
LGTM！ Cheers!

2021-09-21 19:37 UTC, abhishek-iiit commented
Merging PR with no conflicts and 4 approvals :)

2021-09-21 19:37 UTC, merged