Updated the Wechaty Puppet Service
wechaty/docusaurus pull request #965
Opened 2021-06-20 12:34 UTC by shraddhavp

this PR links #890

2021-06-21 11:39 UTC, shraddhavp commented
@proudofsimin  and @Rohitesh-Kumar-Jain  please have look at the PR  and please do let me know your feedback

2021-06-22 16:41 UTC, proudofsimin commented
Can you provide the screenshot? I saw you made quite a lot of changes so it's a bit hard to preview. Thank you.

2021-06-24 05:39 UTC, shraddhavp commented
> Can you provide the screenshot? I saw you made quite a lot of changes so it's a bit hard to preview. Thank you.

yes will do so

2021-06-24 05:41 UTC, shraddhavp commented
![Screenshot (2)](https://user-images.githubusercontent.com/42699578/123208513-dc5e6700-d4dc-11eb-8da8-91ba71210de2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/42699578/123208516-df595780-d4dc-11eb-8d71-49693c3e1ba4.png)
![Screenshot (4)](https://user-images.githubusercontent.com/42699578/123208523-e2ecde80-d4dc-11eb-9efc-bf7bf6f038da.png)

2021-06-24 05:43 UTC, shraddhavp commented
![Screenshot (2)](https://user-images.githubusercontent.com/42699578/123208700-352dff80-d4dd-11eb-8ae3-e27255e89f38.png)
![Screenshot (4)](https://user-images.githubusercontent.com/42699578/123208716-39f2b380-d4dd-11eb-9f56-4ed0fe921e23.png)
![Screenshot (3)](https://user-images.githubusercontent.com/42699578/123208719-39f2b380-d4dd-11eb-8300-2ba3e64ea693.png)

2021-06-24 05:44 UTC, shraddhavp commented
@proudofsimin  please have a look at the screenshots added

2021-06-24 05:46 UTC, shraddhavp commented
![Screenshot (4)](https://user-images.githubusercontent.com/42699578/123208916-8211d600-d4dd-11eb-917f-d971b6735154.png)
![Screenshot (2)](https://user-images.githubusercontent.com/42699578/123208941-8d650180-d4dd-11eb-9339-65c14315aca1.png)
![Screenshot (3)](https://user-images.githubusercontent.com/42699578/123208960-90f88880-d4dd-11eb-8b78-29c0139e6838.png)

2021-06-24 05:46 UTC, shraddhavp commented
![Screenshot (4)](https://user-images.githubusercontent.com/42699578/123209008-a66db280-d4dd-11eb-8a66-141d56abc994.png)
![Screenshot (3)](https://user-images.githubusercontent.com/42699578/123209035-acfc2a00-d4dd-11eb-81e6-eb01d54a8798.png)
![Screenshot (2)](https://user-images.githubusercontent.com/42699578/123209044-af5e8400-d4dd-11eb-8bca-a0e1577eef1b.png)

2021-06-27 14:55 UTC, Rohitesh-Kumar-Jain approved these changes
proofread

2021-06-27 16:00 UTC, proudofsimin approved these changes
I could see you really improve a lot!! You are so great! You did very great in the first part and with only some minor improvement in the second part, so I still approve it. Thank you.

2021-06-27 16:00 UTC, proudofsimin commented on docusaurus/docs/specs/service.md
> +[source code](https://github.com/wechaty/wechaty/blob/7e97620e2a92841227a6ae355efa615c5af95b32/src/io.ts#L236)
. See the [source code](https://github.com/wechaty/wechaty/blob/7e97620e2a92841227a6ae355efa615c5af95b32/src/io.ts#L236).

2021-06-27 16:00 UTC, proudofsimin commented on docusaurus/docs/specs/service.md
> +2. When a puppet service discovery query has been sent to `api.chatie.io` like `https://api.chatie.io/v0/hosties/puppet_rock_token` has been visited, the `api.chatie.io` will send a JSONRPC to you vi
See the [source code](https://github.com/wechaty/wechaty/blob/7e97620e2a92841227a6ae355efa615c5af95b32/src/io.ts#L363).

2021-06-27 16:00 UTC, proudofsimin commented on docusaurus/docs/specs/service.md
> +3. You can learn more about the registration protocol via this discussion: [Support rock puppet service provider. #98](https://github.com/wechaty/wechaty-puppet-service/issues/98)
You said two steps so please don't use more than number two, and move this sentence after the picture.
So it's like below:

The following is a pictorial representation that describes the process above.

[picture]

You can learn more about the registration protocol via [#98 Support rock puppet service provider](https://github.com/wechaty/wechaty-puppet-service/issues/98).

2021-07-10 10:32 UTC, lijiarui commented
Hi @shraddhavp As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-10 10:54 UTC, shraddhavp commented
> Hi @shraddhavp As GSoD Project PR Review Rules in #1045
> 
> This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

yes @lijiarui  mam sure,thanks

2021-07-12 14:13 UTC, Rohitesh-Kumar-Jain commented
@Soumi7 We would be glad if you may once go through the PR, and either request for changes or approve the PR.

2021-07-17 05:50 UTC, Soumi7 approved these changes
LGTM

2021-07-29 15:57 UTC, lijiarui requested changes

2021-07-29 15:57 UTC, lijiarui commented on docusaurus/docs/specs/service.md
> -Through the above steps, you can publish a token with any existing wechaty puppets.
I think we should add `Through the above steps, you can publish a token with any existing wechaty puppets.` this back to the doc.

2021-09-07 18:35 UTC, huan requested changes
Please follow my reviews, thank you very much!

2021-09-07 18:35 UTC, huan commented on docusaurus/docs/specs/service.md
> +[![Sequence Diagram](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgV2VjaGF0eSBQdXBwZXQgU2VydmVyLT4-K2FwaS5jaGF0aWUuaW86IFNlbmRzIGEgd2Vic29ja2V0IGNvbm5lY3Rpb24gd2l0aCBIdHRwIGF1dGhvcm
Could you please save this image to local so that we will not use an external link?

2021-09-07 18:35 UTC, huan commented on docusaurus/docs/specs/service.md
> -
Please keep those sentences about `2. Register the Token with Protocol` and `Registration Process Discussion` because they are important.

2021-09-07 18:35 UTC, huan commented on docusaurus/docs/specs/service.md
>      {"ip":"1.2.3.4","port":1234}
Our protocol changed.

Please change `ip` to `host`.

```diff
-     {"ip":"1.2.3.4","port":1234}
+     {"host":"1.2.3.4","port":1234}
```

2021-09-08 04:05 UTC, shraddhavp commented on docusaurus/docs/specs/service.md
> +[![Sequence Diagram](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgV2VjaGF0eSBQdXBwZXQgU2VydmVyLT4-K2FwaS5jaGF0aWUuaW86IFNlbmRzIGEgd2Vic29ja2V0IGNvbm5lY3Rpb24gd2l0aCBIdHRwIGF1dGhvcm
yes will do so

2021-09-10 13:39 UTC, shraddhavp commented on docusaurus/docs/specs/service.md
> +[![Sequence Diagram](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgV2VjaGF0eSBQdXBwZXQgU2VydmVyLT4-K2FwaS5jaGF0aWUuaW86IFNlbmRzIGEgd2Vic29ja2V0IGNvbm5lY3Rpb24gd2l0aCBIdHRwIGF1dGhvcm
done

2021-09-10 13:40 UTC, shraddhavp commented on docusaurus/docs/specs/service.md
>      {"ip":"1.2.3.4","port":1234}
@huan done

2021-09-10 13:43 UTC, shraddhavp commented on docusaurus/docs/specs/service.md
> -Through the above steps, you can publish a token with any existing wechaty puppets.
@lijiarui  done

2021-09-10 13:55 UTC, shraddhavp commented on docusaurus/docs/specs/service.md
> -
done

2021-09-10 15:36 UTC, huan approved these changes
Thanks for following my reviews, appreciate the improvements!

2021-09-11 07:24 UTC, lijiarui approved these changes
LGTM

2021-09-11 09:51 UTC, merged