added tutorial for qr-code-terminal plugin
wechaty/docusaurus pull request #969
Opened 2021-06-23 08:27 UTC by shwetalsoni

Added tutorial for `QR code terminal plugin`. 

![Screenshot from 2021-06-23 13-53-24](https://user-images.githubusercontent.com/57187745/123063100-bf695b80-d42a-11eb-9cbe-ca8d2cf64c75.png)
![Screenshot from 2021-06-23 13-53-47](https://user-images.githubusercontent.com/57187745/123063107-c1331f00-d42a-11eb-941f-07527b901711.png)
![Screenshot from 2021-06-23 13-54-00](https://user-images.githubusercontent.com/57187745/123063109-c1cbb580-d42a-11eb-8ff7-4cc7dde0eb96.png)
![Screenshot from 2021-06-23 13-54-15](https://user-images.githubusercontent.com/57187745/123063112-c2644c00-d42a-11eb-81e8-7e08e38f28cf.png)

2021-06-23 08:29 UTC, shwetalsoni commented
Tag #891

2021-06-23 14:47 UTC, proudofsimin requested changes
Hi, could you explain more about this plugin at the beginning? Is it the users (developers) or customers will scan the QR code? What will the developers receive when someone scan the QR code? And what will it show on phone after scanning the QR code?

2021-06-23 14:47 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +## 2. Integrating the plugin
remove the v-ing form. Use imperative sentence.

2021-06-23 14:47 UTC, proudofsimin commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +## 3. Running the bot
remove the v-ing form. Use imperative sentence.

2021-06-23 15:11 UTC, shwetalsoni commented
> Hi, could you explain more about this plugin at the beginning? Is it the users (developers) or customers will scan the QR code? What will the developers receive when someone scan the QR code? And what will it show on phone after scanning the QR code?

Hii simin,
Actually this plugin is just for demonstrating that how a user can use this plugin in their bot. So, now on scanning this qr code it wont do anything.

I think for better explanation I can provide a conclusion at end reffering to ding dong bot because there we have used this plugin. On scanning that qr code users can connect to whatsapp and wechat.

What do you think or is their any better way to do this ?

2021-06-24 17:48 UTC, proudofsimin reviewed
Hi @shraddhavp,

Let me clear up. So in here, you use the plugin to generate a QR code first, and then you are required to use the events (are they called events?) to define the function for it. Am I right? I agree with your suggestion that mentioning a real example really helps me/user to clear it up. Thank you.

2021-06-27 08:16 UTC, shwetalsoni commented
Hii @proudofsimin
 I have changed ing(s) to imperative form. 
I have also added conclusion section at end describing about the application of `QR code terminal` plugin. 
I have updated the screenshots for better understanding.
Thank you :)

2021-06-27 08:19 UTC, shwetalsoni commented
> Hi @shraddhavp,
> 
> Let me clear up. So in here, you use the plugin to generate a QR code first, and then you are required to use the events (are they called events?) to define the function for it. Am I right? I agree with your suggestion that mentioning a real example really helps me/user to clear it up. Thank you.

yeah, you get it right. I have made the changes now. You can review it. 
Btw it's not @shraddhavp :sweat_smile:

2021-06-29 15:51 UTC, proudofsimin commented
> Hii @proudofsimin
> I have changed ing(s) to imperative form.
> I have also added conclusion section at end describing about the application of `QR code terminal` plugin.
> I have updated the screenshots for better understanding.
> Thank you :)

Thanks for the modification and adding the starter bot. Could you put the "create the starter bot" in step one like #963 ? Thank you.

P.s. sorry for linking the wrong name...

2021-06-29 15:53 UTC, proudofsimin approved these changes
Since it's only minor modification left, approve first.

2021-06-30 07:13 UTC, shwetalsoni commented
> > Hii @proudofsimin
> > I have changed ing(s) to imperative form.
> > I have also added conclusion section at end describing about the application of `QR code terminal` plugin.
> > I have updated the screenshots for better understanding.
> > Thank you :)
> 
> Thanks for the modification and adding the starter bot. Could you put the "create the starter bot" in step one like #963 ? Thank you.
> 
> P.s. sorry for linking the wrong name...

I have added this step

2021-07-06 19:07 UTC, lijiarui requested changes
Pls change as I request.

2021-07-06 19:07 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
I think we should add a starter bot link here for **Starter Bot**

2021-07-06 19:07 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +#### Linux/macOS
I think we should unify the style here, you did a good job at #888 , it looks like this：

![image](https://user-images.githubusercontent.com/6419514/124647062-0d20a200-dec8-11eb-863c-8cff0c1fd114.png)

You can use code like this:

```markdown
<Tabs
  groupId="operating-systems"
  defaultValue="linux"
  values={[
    { label: 'Linux',   value: 'linux', },
    { label: 'macOS',   value: 'mac', },
    { label: 'Windows', value: 'windows', },
  ]
}>

<TabItem value="linux">

```

2021-07-06 19:07 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +
Add video link reference here: https://www.youtube.com/watch?v=tfGZXoe_aA4

2021-07-06 19:07 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +
Pls remove blank lines here.

2021-07-07 06:33 UTC, shwetalsoni commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
Yeah, I will add the link here. Started Bot will be under `examples/basic/`. We have this section in the upcoming weeks in our proposal. So once the starter bot is added and merged we can provide the link here.

For now, I'm thinking to link the `examples/basic` only. Will that be fine?

2021-07-07 07:10 UTC, shwetalsoni commented
@lijiarui I have made the suggested changes except for the starter bot link which I'll add later when the starter bot is created and merged.

2021-07-07 17:10 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/qr-code-terminal.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
I think you could file a new issue for this. Once you create a new issue, I will ignore this part.

2021-07-07 17:13 UTC, lijiarui commented
Good job! After you file a new issue for [this](https://github.com/wechaty/wechaty.js.org/pull/969#discussion_r665081568), I will approve this PR.

2021-07-08 08:25 UTC, shwetalsoni commented
@lijiarui I have created issue #1032 for keeping the record of all the features that need to be added later mentioning all the respective PR's.

2021-07-08 11:59 UTC, lijiarui approved these changes
Good job！ Appoved

2021-07-08 12:32 UTC, huan approved these changes

2021-07-08 15:16 UTC, merged