updated the puppet.md file
wechaty/docusaurus pull request #972
Opened 2021-06-24 14:59 UTC by shraddhavp

this PR links to #890

2021-06-25 14:04 UTC, proudofsimin commented
Please don't forget to attach screen shots. Thank you

2021-06-25 14:31 UTC, shraddhavp commented
> Please don't forget to attach screen shots. Thank you

yes @proudofsimin adding it soon

2021-06-25 14:33 UTC, shraddhavp commented
![Screenshot (5)](https://user-images.githubusercontent.com/42699578/123440268-38fe7680-d5f0-11eb-9254-3befe3e4aded.png)
![Screenshot (6)](https://user-images.githubusercontent.com/42699578/123440285-3c91fd80-d5f0-11eb-8262-29c03807e67e.png)
![Screenshot (7)](https://user-images.githubusercontent.com/42699578/123440299-40258480-d5f0-11eb-95f0-3330200d1825.png)
![Screenshot (8)](https://user-images.githubusercontent.com/42699578/123440311-43207500-d5f0-11eb-9db9-f234a9a02101.png)
![Screenshot (9)](https://user-images.githubusercontent.com/42699578/123440333-49165600-d5f0-11eb-8d1d-76a8587f2238.png)
![Screenshot (16)](https://user-images.githubusercontent.com/42699578/123440346-4d427380-d5f0-11eb-8178-7f84e41633ff.png)

2021-06-27 14:53 UTC, Rohitesh-Kumar-Jain approved these changes

2021-07-06 15:00 UTC, proudofsimin approved these changes
Hi, sorry I missed this PR.
The structure is good, just that I guess link the URL to the file name is better. See [Link text](https://developers.google.com/style/link-text). (instead of: See [this page](https://developers.google.com/style/link-text) or See https://developers.google.com/style/link-text.)

2021-07-12 14:13 UTC, Rohitesh-Kumar-Jain commented
@Soumi7 We would be glad if you may once go through the PR, and either request for changes or approve the PR.

2021-07-15 17:40 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing the changes

2021-07-17 06:02 UTC, Soumi7 requested changes

2021-07-17 06:02 UTC, Soumi7 commented on docusaurus/docs/specs/puppet.md
> +| PuppetMock      | A mock function to connect WeChat, not a real implement, for testing other connectors to connect with Wechaty. This is used for further to connect other solutions, such as iPad, X
not a real ```implementation```. 

This is used ```to``` further connect

windows client ```.```

2021-07-17 06:02 UTC, Soumi7 commented on docusaurus/docs/specs/puppet.md
> +Currently neither of the Donut, WXWork, Rock, PadLocal have support to this stateless feature, nor the Wechaty system is ready for it.
have support ```for``` this stateless feature

2021-07-17 06:02 UTC, Soumi7 commented on docusaurus/docs/specs/puppet.md
> +3. Then the `ready-ed` event is generated.The ievent is just before the `ready` event.
is this supposed to be ```ievent```?

2021-07-17 06:02 UTC, Soumi7 commented on docusaurus/docs/specs/puppet.md
> +1. The Webhook get called by the Tencent Server.
gets

2021-07-17 07:26 UTC, shraddhavp commented
@Soumi7  thanks for the changes have updated it

2021-07-17 07:36 UTC, Soumi7 approved these changes
LGTM

2021-09-07 18:36 UTC, huan commented on docusaurus/docs/specs/puppet.md
> -## What is Wechaty Puppet
Please keep this paragraph

2021-09-07 18:37 UTC, huan requested changes
Thanks for the improvement!

Please follow my reviews.

2021-09-07 18:37 UTC, huan commented on docusaurus/docs/specs/puppet.md
> -## Wechaty Puppet Message Processing Flow
Please keep those sentences

2021-09-07 18:37 UTC, huan commented on docusaurus/docs/specs/puppet.md
> +[![Flowchart](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFdlYmhvb2spIC0tPnxNZXNzYWdlRXZlbnR8IEIoT2ZmaWNpYWxBY2NvdW50KVxuICAgIEIgLS0-fE1lc3NhZ2VFdmVudHwgQyhQdXBwcGV0T0EpXG4gICAgQyAtLT58T
Please use a local image file instead of an external link to prevent the future 404 errors.

2021-09-09 16:13 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> -## What is Wechaty Puppet
yes @huan  have kept it just added more links 
![Screenshot (27)](https://user-images.githubusercontent.com/42699578/132723158-c0188b4e-79d1-4d94-8e8b-4095d2a27ff4.png)

2021-09-09 16:14 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> +[![Flowchart](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFdlYmhvb2spIC0tPnxNZXNzYWdlRXZlbnR8IEIoT2ZmaWNpYWxBY2NvdW50KVxuICAgIEIgLS0-fE1lc3NhZ2VFdmVudHwgQyhQdXBwcGV0T0EpXG4gICAgQyAtLT58T
yes will do so

2021-09-09 16:24 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> -## Wechaty Puppet Message Processing Flow
ok

2021-09-10 02:55 UTC, huan requested changes
Thank you very much for following my reviews.

I have another two comments, this PR should LGTM after reserving them. (refining them will be appreciated)

2021-09-10 02:55 UTC, huan commented on docusaurus/docs/specs/puppet.md
> -<https://github.com/wechaty/wechaty-puppet-official-account/blob/381ffb820fcc63e4b89a99c433b696e790e06b7a/src/official-account/webhook.ts#L247-L252>
Please keep 195 - 212

2021-09-10 02:55 UTC, huan commented on docusaurus/docs/specs/puppet.md
> -1. the payload of the `dong` event might contains a `data` key with the value exactly match the `data` when calling the `ding()` method.
Please keep 230 - 249, and refining them will be appreciated.

2021-09-10 12:23 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> -<https://github.com/wechaty/wechaty-puppet-official-account/blob/381ffb820fcc63e4b89a99c433b696e790e06b7a/src/official-account/webhook.ts#L247-L252>
@huan done

2021-09-10 12:58 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> -<https://github.com/wechaty/wechaty-puppet-official-account/blob/381ffb820fcc63e4b89a99c433b696e790e06b7a/src/official-account/webhook.ts#L247-L252>
done

2021-09-10 12:58 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> -1. the payload of the `dong` event might contains a `data` key with the value exactly match the `data` when calling the `ding()` method.
@huan  done

2021-09-11 15:58 UTC, huan approved these changes
Thank you very much for following my reviews. There are lots of useful information in this doc and it will be very important when we are implementing a new puppet provider.

This PR will be good after you followed my last change request.

Appreciate all the efforts!

2021-09-11 15:58 UTC, huan commented on docusaurus/docs/specs/puppet.md
> -## NPM Publication
Please keep 142 - 147

2021-09-11 16:56 UTC, shraddhavp commented on docusaurus/docs/specs/puppet.md
> -## NPM Publication
yes @huan it is already present but instead of "NPM Publication"  I have renamed it as "Important Tips" and it is present at the end of this PR 
![Screenshot (28)](https://user-images.githubusercontent.com/42699578/132955405-75a74465-585f-402a-ae91-07ebb179000c.png)
doc

2021-09-12 04:33 UTC, merged