update 2021 soc kick-off meeting
wechaty/docusaurus pull request #973
Opened 2021-06-24 17:54 UTC by ninetailskim

Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2021-06-25 03:53 UTC, huan requested changes
Dear @ninetailskim,

Thank you very much for your great work of publishing this valuable meeting blog post, what you had written is awesome!

I have suggested a few changes and add some comments, please follow them and feel free to let me know if you have any questions.

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +title: "Wechaty Summer of Code 2021 Kickoff Meeting"
Please change `Wechaty Summer of Code 2021` to `Wechaty Open Source Promotion Plan 2021` because the official project name of 暑期2021 is OSPP.

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +image: /assets/2021/06-wechaty-soc-kick-off-meeting/group-photo.png
I'd like to suggest that we use the `.webp` format for our photos because it will greatly reduce the size of the file.

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +> 作者: [ninetailskim](https://github.com/ninetailskim/)
We can use the Wechaty contributor profile instead of GitHub because it will show all your blog posts and introductions from the community. For example, yours is at https://wechaty.js.org/contributors/ninetailskim/

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +### 开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 <https://github.com/wechaty/summer-of-wechaty/issues/78>
Could you please re-order all the projects, so that they can be listed by ascending order of the issue numbers? (from small to big)

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- 导师：李卓桓 Wechaty creator，Python Wechaty maintainer，Tencent TVP of Chatbot （zixia@zixia.net）；吴京京 Python Wechaty creator，Wechaty committer （wjmcater@gmail.com）
Please help me to move 京京 to be the first mentor. I'll be the second mentor to co-mentor this project.

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- 导师：李卓桓 Creator of Wechaty，Tencent TVP of Chatbot （zixia@zixia.net）；李佳芮 Wechaty co-creator，Founder & CEO of Juzi.BOT （rui@chatie.io）
Please help me to move 佳芮 to be the first mentor. I'll be the co-mentor for this project.

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +<div class="video-container" style="
Please use `{% include iframe.html src="https://www.youtube.com/watch?v= ZcVRxXA5OWc" %}` to embed your video. All our videos should be upload to YouTube and use this way to embed into our blog posts.

Do not use HTML code directly to make the work to be simple and get an auto-layout CSS setting.

See: https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- **Plan Blog**：学生开发者们会在**6.30号**前以博客形式在[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)进行分享，内容包括：排期规划、对应项目Repo、联系方式等，同时也作为每周进展在例行更新中同步。除blog之外，学生还应另外提供投影片以及视频演讲内容。
I remember there has some discussion about the deadline date about the 6.30. Do we need to postpone the date 1 or 2 weeks later?

Please review the discussion and let's update this deadline to better fit the students' needs.

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- **POC Blog**：学生开发者们会在**8.30号**前以博客形式在[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)进行分享，内容包括：完成的项目核心攻关、后续需要的支持和新的开发排期，同时也作为每周进展在例行更新中同步。除blog之外，学生还应另外提供投影片以及视频演讲内容。
This address is outdated: `[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)`

Please use this correct one: 

```md
[wechaty/wechaty.js.org](https://github.com/wechaty/wechaty.js.org)
```

2021-06-25 03:53 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +
Could you please add the agenda details to the YouTube video description, as well as in this blog post, like the following [one](https://www.youtube.com/watch?v=hTkM_XPpFfU&list=PL8hd9KDTdarDXf_Rxtr8meKhxtgcXMInh)?

```md
- [0:01:41](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=101s) 1. Introducing the Meeting Agenda
- [0:03:08](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=188s) 2. Self-introduction: Huan
- [0:06:15](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=375s) 3. Self-introduction: Rui
- [0:09:15](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=555s) 4. Self-introducing: Technical Writers
- [0:24:53](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=1493s) 5. Introducing Wechaty
- [0:29:37](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=1777s) 6. Introducing GSoD Project List
- [0:41:46](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=2506s) 7. Introducing Received Proposals
- [0:44:41](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=2681s) 8. Primary Project: Tutorial
- [0:45:33](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=2733s) 8.1 Tutorial Proposal from Souvik Biswas
- [0:49:24](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=2964s) 8.2 Tutorial Proposal from Shwetal Soni
- [1:00:19](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=3619s) 9. Landing Page Proposal from Sajen Sarvajith K
- [1:12:00](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=4320s) 10. Introduction & Explanation Proposal from Mukosa Joseph Mawa
- [1:23:44](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=5024s) 11.1. How-to Guides Proposal from Vasvi Sood
- [1:27:38](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=5258s) 11.2. How-to Guides Proposal from Abhishek Jaiswal
- [1:33:05](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=5585s) 12. References Proposal from Shraddha Vasant Prasad
- [1:41:00](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=6060s) 13. Volunteer Project
- [1:43:00](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=6060s) 13.1 Volunteer Proposal from Rohitesh Jain
- [1:45:42](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=6342s) 13.2 Volunteer Proposal from Vicky Liao
- [1:57:49](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=7069s) 14. Budget Plan for Stipends
- [2:05:28](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=7528s) 15. Webmaster Tools
- [2:06:33](https://www.youtube.com/watch?v=hTkM_XPpFfU&t=7593s) 16. Q&A
```

2021-06-25 06:10 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- **POC Blog**：学生开发者们会在**8.30号**前以博客形式在[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)进行分享，内容包括：完成的项目核心攻关、后续需要的支持和新的开发排期，同时也作为每周进展在例行更新中同步。除blog之外，学生还应另外提供投影片以及视频演讲内容。
Done! I will update when all problems fixed.

2021-06-25 06:16 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- **Plan Blog**：学生开发者们会在**6.30号**前以博客形式在[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)进行分享，内容包括：排期规划、对应项目Repo、联系方式等，同时也作为每周进展在例行更新中同步。除blog之外，学生还应另外提供投影片以及视频演讲内容。
I don't remember that and i couldn't find the discussion in meeting note, I will check it later~

2021-06-25 06:16 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +title: "Wechaty Summer of Code 2021 Kickoff Meeting"
Done! I will update after all problems fixed.

2021-06-25 06:16 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +> 作者: [ninetailskim](https://github.com/ninetailskim/)
Done! I will update after all problems fixed.

2021-06-25 06:16 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +image: /assets/2021/06-wechaty-soc-kick-off-meeting/group-photo.png
Done! I will update after all problems fixed.

2021-06-25 06:17 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +### 开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 <https://github.com/wechaty/summer-of-wechaty/issues/78>
Done! I will update after all problems fixed.

2021-06-25 06:19 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +### 开发基于 Wechaty 实现微俱乐部会员&活动管理的微信小程序 <https://github.com/wechaty/summer-of-wechaty/issues/78>
I ordered those projects by the order in the poster, I will re-order them.

2021-06-25 06:19 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- 导师：李卓桓 Wechaty creator，Python Wechaty maintainer，Tencent TVP of Chatbot （zixia@zixia.net）；吴京京 Python Wechaty creator，Wechaty committer （wjmcater@gmail.com）
Done! I will update after all problems fixed.

2021-06-25 06:19 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- 导师：李卓桓 Creator of Wechaty，Tencent TVP of Chatbot （zixia@zixia.net）；李佳芮 Wechaty co-creator，Founder & CEO of Juzi.BOT （rui@chatie.io）
Done! I will update after all problems fixed.

2021-06-25 09:21 UTC, chinggg commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- **Plan Blog**：学生开发者们会在**6.30号**前以博客形式在[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)进行分享，内容包括：排期规划、对应项目Repo、联系方式等，同时也作为每周进展在例行更新中同步。除blog之外，学生还应另外提供投影片以及视频演讲内容。
We talked about it in the SoW Wechat group after the meeting, wjj suggest 7.4 to be the deadline, which is a Sunday. But some students will have exams until 7.25.

2021-06-25 17:36 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +- **Plan Blog**：学生开发者们会在**6.30号**前以博客形式在[wechaty.github.io](https://github.com/wechaty/wechaty.github.io)进行分享，内容包括：排期规划、对应项目Repo、联系方式等，同时也作为每周进展在例行更新中同步。除blog之外，学生还应另外提供投影片以及视频演讲内容。
OK, I will fix it.

2021-06-25 17:44 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +
i add those details to the youtube description. but i don't know where to put those in blog.

2021-06-26 03:49 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +
Thanks for adding those details to the YouTube description!

YouTube has a feature that can help us to [add chapters to the video progress bar](https://support.google.com/youtube/answer/9884579?hl=en), please read the link and make our list of the timestamps and titles enable chapters in the progress bar correctly.

Thank you very much!

2021-06-26 03:51 UTC, huan requested changes

2021-06-26 03:51 UTC, huan commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +
For the question about where to put those in our blog, I feel it can be put under the YouTube embedded section. Please pick a place where you believe it is best for the readers, thanks!

2021-06-26 04:21 UTC, xilou31 commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +{% include iframe.html src="https://www.https://www.youtube.com/watch?v=ZcVRxXA5OWc" %}
The url for "SoC破冰会会议纪实" is wrong, the correct url should be "www.https://www.youtube.com/watch?v=ZcVRxXA5OWc"

2021-06-26 04:23 UTC, xilou31 requested changes

2021-06-26 04:23 UTC, xilou31 commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +{% include iframe.html src="https://www.https://www.youtube.com/watch?v=ZcVRxXA5OWc" %}
The url for "SoC破冰会会议纪实" is wrong, the correct url should be "https://www.youtube.com/watch?v=ZcVRxXA5OWc"

2021-06-26 06:24 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +
> Thanks for adding those details to the YouTube description!
> 
> YouTube has a feature that can help us to [add chapters to the video progress bar](https://support.google.com/youtube/answer/9884579?hl=en), please read the link and make our list of the timestamps and titles enable chapters in the progress bar correctly.
> 
> Thank you very much!

Done!

2021-06-26 06:25 UTC, ninetailskim commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +{% include iframe.html src="https://www.https://www.youtube.com/watch?v=ZcVRxXA5OWc" %}
Thank You, I will fix it~

2021-06-26 06:48 UTC, lyleshaw approved these changes

2021-06-26 10:35 UTC, xilou31 approved these changes
LGTM。

2021-06-26 12:15 UTC, chinggg approved these changes

2021-06-26 12:15 UTC, chinggg commented on jekyll/_posts/2021-06-24-wechaty-soc-kick-off-meeting.md
> +“开源软件供应链点亮计划-暑期2021”（以下简称 暑期2021）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动。旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。活动联合各大开源社区，针对重要开源软件的开发与维护提供项目，并向全球高校学生开放报名。
`「」` may be better than `“”`, but the latter is still OK since we do not have a rigid grammer rule.

2021-06-27 14:53 UTC, huan approved these changes
LGTM

2021-06-27 14:54 UTC, huan commented
Thanks to @ninetailskim for publishing this great blog post for our OSPP meeting minutes and uploading the YouTube video for the community!

2021-06-27 14:55 UTC, merged