Architecture subsection of Explanation section
wechaty/docusaurus pull request #977
Opened 2021-06-25 09:12 UTC by nibble0101

# Improve the Introduction and Explanation sections project

| Section | Sub-section | Technical Writer |
| --- | --- | --- |
|Explanations | Architecture  |  Joseph Mawa |

This  is **Architecture** sub-section of the **Explanations** section

![image](https://user-images.githubusercontent.com/52580190/123399938-e1d7b200-d5ad-11eb-9693-68c7b6d03c47.png)
![image](https://user-images.githubusercontent.com/52580190/123400008-f7e57280-d5ad-11eb-8c5b-e220ff593fb7.png)
![image](https://user-images.githubusercontent.com/52580190/123400216-2fecb580-d5ae-11eb-9971-fcf960088dc9.png)
![image](https://user-images.githubusercontent.com/52580190/123400298-45fa7600-d5ae-11eb-816a-3e43ce538536.png)
![image](https://user-images.githubusercontent.com/52580190/123400367-5c083680-d5ae-11eb-9494-5d89acadcd8e.png)
![image](https://user-images.githubusercontent.com/52580190/123400476-79d59b80-d5ae-11eb-80bc-92a8816c897b.png)

2021-06-25 14:45 UTC, proudofsimin approved these changes

2021-06-27 14:49 UTC, Rohitesh-Kumar-Jain approved these changes
Great work, I proofread this, not a single typo

2021-07-12 13:09 UTC, Rohitesh-Kumar-Jain commented
@chris-4444 I would like you to once go through the PR, and approve when you think it's ready to get merged.

2021-07-14 07:58 UTC, chris-4444 approved these changes
LGTM.

2021-07-18 18:56 UTC, lijiarui requested changes

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +title: Wechaty chatbot architecture
Please change back to `Architecture`, because:

1. All of here is Wechaty, no Wechaty chatbot concept
2. Since this is Wechaty doc, we don't need to add Wechaty here again.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
I think we should use an architecture image better than a wechaty logo here, so I suggest change it back.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> -The following diagram shows out that we can reuse almost everything in TypeScript, and what we need to do is only the block located at the top right of the diagram: `Wechaty (Polyglot)`.
I think we should add this part back because this is explaining the architecture image.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  +-------------------------------------------------------+
Please change this back, because we draw like that mean `typescript` is the main language, and other language is translating typescript

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  |                Wechaty Puppet Abstract                |
Please change this back to `Wechaty Puppet Service` because here is wechaty service.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +    +--------------------+  gRPC  +---------------------+
Please change back to `wechaty_grpc`

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  |                 Wechaty Puppet Abstract               |
Please add `(wechaty-puppet)` back. And change Wechaty Puppet Abstract to Wechaty Puppet

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
>    +--------------------------+ +--------------------------+
I think you left 2 blanks for `wechaty-puppet-wechat` here.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> -> Chart made by [AsciiFlow](http://asciiflow.com/)
I think we can keep this reference back.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  With Wechaty, you can build chatbots for Instant Messaging systems such as [Wechat and Whatsapp among others](#placeholder-link). They constitute the front-end interface your clients will interact
What is required is just switching the service token --> What is required is just switching the service token and environment variable `WECHATY_PUPPET`.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  <!-- Not very sure about the correctness of this explanation. Need clarification from a core Wechaty contributor -->
As we talked here: https://github.com/wechaty/wechaty.js.org/pull/904/files#r669839258

We can use Wechaty Puppet instead of Wechaty Puppet Abstract here, and change the explanation to the following you write in #904 :

```
Wechaty Puppet is a standard for maintaining compatibility between Instant Messaging(IM) systems. Wechaty Puppet defines the universal Instant Messaging interface for compatibility between Wechaty API and variants of IM systems.
```

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  In the Wechaty ecosystem, different Instant Messaging systems require different plugins for compatibility with the Wechaty API. These plugins are referred to as Wechaty Puppet Providers. The Wechat
I think we should change as follows:

```
Wechaty puppet provider refers to [RPA](#placeholder-link) module used for connecting Wechaty API to the corresponding Instant Messaging platform bot account. Each supported Instant Messaging system has its own Puppet provider. See [Puppet Providers](#placeholder-link) section for a complete list of puppet providers.

For example, the Wechaty Puppet Provider who is supporting WeChat is named [wechaty-puppet-wechat](https://github.com/wechaty/wechaty-puppet-wechat), supporting Whatsapp is named [wechaty-puppet-whatsapp](https://github.com/wechaty/wechaty-puppet-whatsapp), and supporting Lark is named [wechaty-puppet-lark](https://github.com/wechaty/wechaty-puppet-lark).
```

Because:
1.  We should not use `plugin` word in wehcaty puppet provider, since it will mix developer with wechaty plugin, we use this here: http://wechaty.js.org/docs/using-plugin-with-wechaty/overview which is totally different with wechaty
2. Wechaty Puppet Provider named following `wechaty-puppet-anyword`, you can use any word here instead of just use INSTANT_MESSAGING_PLATFORM, for example, these 3 puppets: wechaty-puppet-padlocal, wechaty-puppet-donut and wechaty-puppet-wechat all work for WeChat but they are using 3 different names.

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  Using Wechaty puppet as a service saves you from dealing with setup, downtime, and maintenance overheads. What you need is an access TOKEN and it just works out of the box. Most puppet services off
Please change `Wechaty chatbot architecture` to `Wechaty architecture`

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  Using Wechaty puppet as a service saves you from dealing with setup, downtime, and maintenance overheads. What you need is an access TOKEN and it just works out of the box. Most puppet services off
I like the explanation you talked about here about Wechaty Puppet Service, it's very clear and easy to understand than what we trying to explain before. Could you help to combine the following explanation together:

```
Wechaty Puppet Service is gRPC for Wechaty Puppet Provider.

For example, we can cloudify the Wechaty Puppet Provider wechaty-puppet-padlocal to a Wechaty Puppet Service by running our Wechaty Puppet Service Token Gateway.
```

2021-07-18 18:56 UTC, lijiarui commented on docusaurus/docs/explainations/architecture.md
> +  Initially, Wechaty was built using TypeScript. Support for other languages such as Python, Go, Java, PHP, .NET, and Scala was later introduced in 2020 so that chatbot makers can build chatbots in t
Could you add this concept to https://github.com/wechaty/wechaty.js.org/pull/904 as well? I like this explanation here!

2021-07-21 14:15 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +title: Wechaty chatbot architecture
Reverted back to Architecture

2021-07-21 14:19 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +![Wechaty: Conversational RPA SDK for Chatbot Makers](/img/wechaty-logo.svg)
Added Architecture image

2021-07-21 14:24 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> -The following diagram shows out that we can reuse almost everything in TypeScript, and what we need to do is only the block located at the top right of the diagram: `Wechaty (Polyglot)`.
Added the paragraph of text.

2021-07-21 14:25 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  |                Wechaty Puppet Abstract                |
Reverted to the original chart.

2021-07-21 14:26 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  +-------------------------------------------------------+
Reverted back to original chart.

2021-07-21 14:27 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +    +--------------------+  gRPC  +---------------------+
Reverted to the original chart

2021-07-21 14:30 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  |                 Wechaty Puppet Abstract               |
Reverted to original chart and made necessary changes.

2021-07-21 14:31 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
>    +--------------------------+ +--------------------------+
Reverted to the original chart

2021-07-21 14:32 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  With Wechaty, you can build chatbots for Instant Messaging systems such as [Wechat and Whatsapp among others](#placeholder-link). They constitute the front-end interface your clients will interact
Fixed

2021-07-21 14:33 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> -> Chart made by [AsciiFlow](http://asciiflow.com/)
Fixed

2021-07-21 14:35 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  <!-- Not very sure about the correctness of this explanation. Need clarification from a core Wechaty contributor -->
Fixed

2021-07-21 14:39 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  In the Wechaty ecosystem, different Instant Messaging systems require different plugins for compatibility with the Wechaty API. These plugins are referred to as Wechaty Puppet Providers. The Wechat
Fixed

2021-07-21 14:41 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  Using Wechaty puppet as a service saves you from dealing with setup, downtime, and maintenance overheads. What you need is an access TOKEN and it just works out of the box. Most puppet services off
Fixed

2021-07-21 14:44 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  Using Wechaty puppet as a service saves you from dealing with setup, downtime, and maintenance overheads. What you need is an access TOKEN and it just works out of the box. Most puppet services off
Replaced explanation with requested one.

2021-07-21 14:58 UTC, nibble0101 commented on docusaurus/docs/explainations/architecture.md
> +  Initially, Wechaty was built using TypeScript. Support for other languages such as Python, Go, Java, PHP, .NET, and Scala was later introduced in 2020 so that chatbot makers can build chatbots in t
Added to #904

2021-07-25 19:12 UTC, lijiarui approved these changes
LGTM

2021-07-29 13:57 UTC, huan approved these changes
LGTM 

@Rohitesh-Kumar-Jain Would you like to merge this PR on behalf of the community? As we discussed before: whenever a PR has been approved by all the team writers and the volunteers, and it has been passed the CI tests, then you can feel free to merge it when you feel comfortable, or request changes to the org admin.

2021-07-30 12:55 UTC, merged