blog for xiaoli
wechaty/docusaurus pull request #98
Opened 2018-08-11 21:08 UTC by judaschrist

RT

2018-08-12 15:21 UTC, lijiarui requested changes

2018-08-12 15:21 UTC, lijiarui commented on _posts/2018-08-05-wechaty-xiaoli.md
> +                "title": "微信群里的赌场",
`微信群里的赌场`  Maybe we can change to another example? ：）

2018-08-13 02:48 UTC, merged

2018-08-13 02:48 UTC, lijiarui commented
Thanks!

2018-08-13 03:08 UTC, judaschrist commented
@lijiarui changed the example as requested