[How to guides] Dealing with messages
wechaty/docusaurus pull request #980
Opened 2021-06-25 20:43 UTC by vasvi-sood

![dealingMessages](https://user-images.githubusercontent.com/76619050/123483241-0bcbbb80-d624-11eb-8062-197b8fec3b5a.png)
![dealingMessage2](https://user-images.githubusercontent.com/76619050/123483252-0d957f00-d624-11eb-9074-f2b827dd04b4.png)
![dealingMessages3](https://user-images.githubusercontent.com/76619050/123483262-0ff7d900-d624-11eb-8cfb-338799b41fb6.png)

2021-06-26 14:39 UTC, proudofsimin requested changes
Beside the comments below, I was expected to see instructions/ steps instead of only code snippets without any explanation.

2021-06-26 14:39 UTC, proudofsimin commented on docusaurus/docs/howto/message.md
> +Mention messages are sent automatically by the bot if the message recieved as a parameter by the onMessage belongs to a room. The bot can mention(@) others.
Could you rewrite this sentence? There are so many conjunctions inside and should better be divided. It's a bit difficult to read.
Please note:
* Put the purpose or condition clauses at the beginning.
* `onMessage`

2021-06-26 14:39 UTC, proudofsimin commented on docusaurus/docs/howto/message.md
> +Self messages are sent automatically by the bot if the message recieved as a parameter by the onMessage  function has also been sent by the bot itself.
same as above. Please rewrite this sentence.

2021-06-30 06:42 UTC, vasvi-sood commented on docusaurus/docs/howto/message.md
> +Mention messages are sent automatically by the bot if the message recieved as a parameter by the onMessage belongs to a room. The bot can mention(@) others.
Okay, I will do the necessary changes.

2021-06-30 06:50 UTC, vasvi-sood commented
> Beside the comments below, I was expected to see instructions/ steps instead of only code snippets without any explanation.

Do you want me to write the prerequisites (installing dependencies, creating a bot.js file)? Basically this  code snippet is just a simple function that gives me the following result:
![dealingMessage2](https://user-images.githubusercontent.com/76619050/123914523-1d52f180-d99d-11eb-8e5d-06bcc562a4d6.png)

2021-06-30 07:21 UTC, vasvi-sood commented on docusaurus/docs/howto/message.md
> +Mention messages are sent automatically by the bot if the message recieved as a parameter by the onMessage belongs to a room. The bot can mention(@) others.
Done, Kindly review it now

2021-06-30 17:41 UTC, proudofsimin commented
> > Beside the comments below, I was expected to see instructions/ steps instead of only code snippets without any explanation.
> 
> Do you want me to write the prerequisites (installing dependencies, creating a bot.js file)? Basically this code snippet is just a simple function that gives me the following result:
> ![dealingMessage2](https://user-images.githubusercontent.com/76619050/123914523-1d52f180-d99d-11eb-8e5d-06bcc562a4d6.png)

You could either do like how tutorial team does (#985) or like [JavaScript](https://javascript.info/date). Basically I would suggest you to add some sentences to explain the code snippets. Please let me know how you think is better? Thank you.

2021-07-04 05:25 UTC, vasvi-sood commented
> > > Beside the comments below, I was expected to see instructions/ steps instead of only code snippets without any explanation.
> > 
> > 
> > Do you want me to write the prerequisites (installing dependencies, creating a bot.js file)? Basically this code snippet is just a simple function that gives me the following result:
> > ![dealingMessage2](https://user-images.githubusercontent.com/76619050/123914523-1d52f180-d99d-11eb-8e5d-06bcc562a4d6.png)
> 
> You could either do like how tutorial team does (#985) or like [JavaScript](https://javascript.info/date). Basically I would suggest you to add some sentences to explain the code snippets. Please let me know how you think is better? Thank you.

I think following the pattern that the tutorials team is following will be more intuitive. I wll do it that way.

2021-07-04 08:47 UTC, proudofsimin commented
> > > > Beside the comments below, I was expected to see instructions/ steps instead of only code snippets without any explanation.
> > > 
> > > 
> > > Do you want me to write the prerequisites (installing dependencies, creating a bot.js file)? Basically this code snippet is just a simple function that gives me the following result:
> > > ![dealingMessage2](https://user-images.githubusercontent.com/76619050/123914523-1d52f180-d99d-11eb-8e5d-06bcc562a4d6.png)
> > 
> > 
> > You could either do like how tutorial team does (#985) or like [JavaScript](https://javascript.info/date). Basically I would suggest you to add some sentences to explain the code snippets. Please let me know how you think is better? Thank you.
> 
> I think following the pattern that the tutorials team is following will be more intuitive. I wll do it that way.

or you could see how @abhishek-iiit did, he figured out quite a good way. #981

2021-07-06 15:34 UTC, proudofsimin reviewed
I'm not sure did you make any change?
Maybe you could explain what the routines are or where we could find the explanation(ex. .mentionList()).

2021-07-11 12:47 UTC, Rohitesh-Kumar-Jain requested changes
Correct the spelling of Received at all places.

2021-07-14 05:04 UTC, vasvi-sood commented
> I'm not sure did you make any change?
> Maybe you could explain what the routines are or where we could find the explanation(ex. .mentionList()).

I have not made all the required changes. I'll do that soon.

2021-07-21 14:33 UTC, vasvi-sood commented
@proudofsimin  and @Rohitesh-Kumar-Jain  I have made all the necessary changes. Kindly review the same.

2021-07-22 09:10 UTC, abhishek-iiit approved these changes
Changes as suggest in #1011, else LGTM :)

2021-08-01 09:16 UTC, proudofsimin approved these changes

2021-09-07 18:40 UTC, huan requested changes
Thanks for the improvements.

Please follow my reviews.

2021-09-07 18:40 UTC, huan commented on docusaurus/docs/howto/message.md
>  const { Message } = require('wechaty')
`import { Message } from 'wechaty'`

2021-09-07 18:40 UTC, huan commented on docusaurus/docs/howto/message.md
> +   console.log(contact);
Please keep the code clean and with a formatted indents.

2021-09-13 17:24 UTC, vasvi-sood commented on docusaurus/docs/howto/message.md
> +   console.log(contact);
All changes made as suggested. Kindly review it @huan  and @Rohitesh-Kumar-Jain

2021-09-15 03:35 UTC, Rohitesh-Kumar-Jain commented on docusaurus/docs/howto/message.md
> +   console.log(contact);
Yes this one seems to be resolved, but I don't see the upper one being resolved.

2021-09-17 17:18 UTC, vasvi-sood commented on docusaurus/docs/howto/message.md
> +   console.log(contact);
I forget to do that. Changed require to import in the new commit. Kindly review it @Rohitesh-Kumar-Jain

2021-09-18 18:19 UTC, lijiarui requested changes
@abhishek-iiit I think since you are using an outdated example, please change all of the content to the latest example: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/friend-bot.js

2021-09-18 18:19 UTC, lijiarui commented on docusaurus/docs/howto/message.md
> +* Your system must have [Node.js](https://nodejs.org/en/download/package-manager/) installed (version >= 12).
Please change 12 to 16, since the latest wechaty can only run when node version is over 16

2021-09-18 18:19 UTC, lijiarui commented on docusaurus/docs/howto/message.md
> +The below function needs a basic script that can help run the bot. The basic script starts by importing the code from [Github/Friend-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc17
Please change https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/friend-bot.ts to the latest version, since this code is written in 2018.

The latest example link is: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/friend-bot.js

2021-09-24 17:43 UTC, vasvi-sood commented on docusaurus/docs/howto/message.md
> +The below function needs a basic script that can help run the bot. The basic script starts by importing the code from [Github/Friend-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc17
changes made as suggested @lijiarui  @huan  and @Rohitesh-Kumar-Jain

2021-09-27 09:09 UTC, Rohitesh-Kumar-Jain approved these changes
Thanks for implementing the suggested changes : )

2021-09-27 12:13 UTC, lijiarui commented
Hi @vasvi-sood  Please resolve the conflict first.

2021-10-02 07:50 UTC, vasvi-sood commented
> Hi @vasvi-sood Please resolve the conflict first.

done

2021-10-16 16:17 UTC, Rohitesh-Kumar-Jain commented
ping @huan and @lijiarui

2021-10-16 19:20 UTC, huan approved these changes
LGTM

2021-10-17 12:48 UTC, lijiarui requested changes

2021-10-17 12:48 UTC, lijiarui commented on docusaurus/docs/howto/message.md
> +* You need to have at least a minimal application ready to work, follow one of our [Example/Friend-Bot](https://wechaty.js.org/docs/examples/advanced/friend-bot/).
I think the best example is the ding-dong bot: https://github.com/wechaty/getting-started/blob/main/examples/ding-dong-bot.js

2021-10-17 12:48 UTC, lijiarui commented on docusaurus/docs/howto/message.md
> +See [Running our first ding-dong bot](https://wechaty.js.org/docs/getting-started/quick-start).
I'm not sure this link is the correct link, please contact the tutorial team to get a proper link.

2021-10-17 12:48 UTC, lijiarui commented on docusaurus/docs/howto/message.md
> +The below function needs a basic script that can help run the bot. The basic script starts by importing the code from [Github/Friend-Bot](https://github.com/wechaty/wechaty-getting-started/blob/main/
I think the best example is the ding-dong bot instead of friend-bot: https://github.com/wechaty/getting-started/blob/main/examples/ding-dong-bot.js

2021-10-17 12:48 UTC, lijiarui commented on docusaurus/docs/howto/message.md
>  ## Mention
I think we should add more message types before mention the part, it is more important for developers. eg: text message, image message, URL link message, mini-program message, contact- card message, and so on.

2021-11-03 11:22 UTC, Rohitesh-Kumar-Jain commented
@abhishek-iiit pls resolve conflicts first :)

2021-11-14 03:59 UTC, shraddhavp approved these changes
LGTM

2021-11-17 03:40 UTC, shraddhavp commented
@lijiarui

2022-03-30 12:09 UTC, huan commented
@lijiarui You have blocked this PR for months. I'll merge it in favor of

- #1501

2022-03-30 12:09 UTC, merged