Friend request
wechaty/docusaurus pull request #981
Opened 2021-06-27 11:43 UTC by abhishek-iiit

## Send and accept friend requests
![Screenshot from 2021-06-27 16-58-52](https://user-images.githubusercontent.com/69477761/123543148-d54c8880-d76a-11eb-87ff-7fd47ff2f73a.png)
![Screenshot from 2021-06-27 16-59-03](https://user-images.githubusercontent.com/69477761/123543149-d67db580-d76a-11eb-805e-48b44398df2a.png)
![Screenshot from 2021-06-27 16-59-28](https://user-images.githubusercontent.com/69477761/123543150-d7aee280-d76a-11eb-9853-d359f66f77b7.png)

2021-06-27 14:46 UTC, Rohitesh-Kumar-Jain approved these changes
it seems like you have got comfortable with git, quickly learned version control 🎉

2021-06-27 15:19 UTC, abhishek-iiit commented
Thank you for always being there @Rohitesh-Kumar-Jain 😃

2021-06-29 16:51 UTC, proudofsimin commented
not sure if you're waiting but please give me one more day for this PR. Thanks.

2021-06-30 17:23 UTC, proudofsimin reviewed
For this and your previous PR, originally I was expected to see you introduce a bit about the code snippets. You revision is very great, but it would be better if you could explain a bit more about the codes (although they are quite self-explanatory). You could see a great example in [JavaScript](https://javascript.info/date). I would like to hear your opinion and how you think could make this document better. Please feel free to contact me through email or other. Thank you.

2021-06-30 17:23 UTC, proudofsimin commented on docusaurus/docs/howto/friendship.md
> +Sending and accepting friend requests can easily be done using wechaty onfriendship function. This guide help you Send request, Receive request(in friend event), Confirmation friendship(friend event)
This guide [will] help you send friend request, receive request (in friend event), and confirm friendship (friend event) in a room.

2021-06-30 17:23 UTC, proudofsimin commented on docusaurus/docs/howto/friendship.md
> +Trying to expand the network can help you extend the employment opportunities and professional resources. If you have questions like "How can I friend someone on IM platform?" then you need this sect
This introduction is a bit weird in here. The first sentence is more suitable in an essay but it's tolerable. For the second sentence, I would prefer direct description of the function. It would feel more formal. How do you think?

2021-07-04 08:19 UTC, proudofsimin approved these changes

2021-07-10 10:27 UTC, lijiarui commented
Hi @abhishek-iiit , As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

2021-07-10 10:28 UTC, lijiarui commented
Since the `.webp` format has lots of advantages and the [safari has supported it last year](https://www.macrumors.com/2020/06/22/webp-safari-14/) which means all the modern browsers will be able to compatible with it.

@huan has just added a new unit test for enforcing the image format: the CI will not be passed if we are using other image formats than the perfect .webp.

Please make CI green to adjust the new rule, see https://github.com/wechaty/wechaty.js.org/issues/1035

2021-07-14 05:17 UTC, vasvi-sood requested changes
Please change the Image format, because the tests are failing.

2021-07-21 14:43 UTC, vasvi-sood commented on docusaurus/docs/howto/friendship.md
> +The below function needs a basic scipt that can help run the bot. The basic script starts by importing the code from [Github/Friend-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172
correct the spelling of `script`.

2021-08-12 05:55 UTC, vasvi-sood approved these changes

2021-09-07 18:41 UTC, huan requested changes
Please use ESM syntax.

Then I believe this PR will be ready to be merged.

2021-09-07 18:41 UTC, huan commented on docusaurus/docs/howto/friendship.mdx
> +const { Friendship } = require('wechaty')
Please use ESM syntax.

2021-09-16 20:40 UTC, abhishek-iiit commented on docusaurus/docs/howto/friendship.mdx
> +const { Friendship } = require('wechaty')
changes made as suggested :)

2021-09-16 20:43 UTC, abhishek-iiit commented
@huan I request to look for the approval, so that we can continue towards merging this PR

2021-09-18 18:23 UTC, lijiarui requested changes
@abhishek-iiit I think since you are using an outdated example, please change all of the content to the latest example: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/friend-bot.js

2021-09-18 18:23 UTC, lijiarui commented on docusaurus/docs/howto/friendship.mdx
> +* Your system must have [Node.js](https://nodejs.org/en/download/package-manager/) installed (version >= 12).
Please change 12 to 16

2021-09-18 18:23 UTC, lijiarui commented on docusaurus/docs/howto/friendship.mdx
> +Use the guide to help you integrate additional functions to an existing project which is present at [Github/Friend-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540
Please change https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/friend-bot.ts to the latest version, since this code is written in 2018.

The latest example link is: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/friend-bot.js

2021-09-18 18:23 UTC, lijiarui commented on docusaurus/docs/howto/friendship.mdx
> +The below function needs a basic script that can help run the bot. The basic script starts by importing the code from [Github/Friend-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc17
Please change https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc172a744b2fbe53351540e/examples/friend-bot.ts to the latest version, since this code is written in 2018.

The latest example link is: https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/friend-bot.js

2021-09-21 19:53 UTC, abhishek-iiit commented
@huan @lijiarui I request to look for the approval, so that we can continue towards merging this PR

2021-09-21 19:54 UTC, abhishek-iiit commented on docusaurus/docs/howto/friendship.mdx
> +The below function needs a basic script that can help run the bot. The basic script starts by importing the code from [Github/Friend-Bot](https://github.com/wechaty/wechaty/blob/1523c5e02be46ebe2cc17
changes done as suggested :)

2021-10-17 12:55 UTC, lijiarui submitted a review, later dismissed

2021-10-17 12:55 UTC, lijiarui commented on docusaurus/docs/howto/friendship.mdx
> +Use the guide to help you integrate additional functions to an existing project which is present at [Github/Friend-Bot](https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/
I think the best practice is to add a ding-dong example here, instead of add a contact-bot example.

2021-10-17 12:55 UTC, lijiarui commented on docusaurus/docs/howto/friendship.mdx
> +* You need to have at least a minimal application ready to work, follow one of our [Example/Friend-Bot](https://wechaty.js.org/docs/examples/advanced/friend-bot/).
I think the best practice is to add a ding-dong example here, instead of adding a friend bot example: https://github.com/wechaty/getting-started/blob/main/examples/ding-dong-bot.js

2021-10-17 12:55 UTC, lijiarui commented on docusaurus/docs/howto/friendship.mdx
> +See [Running our first ding-dong bot](https://wechaty.js.org/docs/getting-started/quick-start).
I'm not sure this link is the correct link, please contact the tutorial team to get a proper link.

2021-11-14 03:57 UTC, shraddhavp approved these changes
LGTM

2021-11-19 15:33 UTC, huan approved these changes
LGTM

2021-11-20 04:55 UTC, merged