Add tutorial for Heartbeat plugin
wechaty/docusaurus pull request #985
Opened 2021-06-28 11:52 UTC by sbis04

I have added the tutorial for the `Heartbeat` plugin. The page contents are as follows:

![Heartbeat plugin](https://user-images.githubusercontent.com/43280874/123632016-0d200280-d835-11eb-869e-d9b702a85cbf.png)

Tag #891

2021-06-29 16:43 UTC, proudofsimin approved these changes
You are so great as always!

2021-07-06 18:45 UTC, lijiarui requested changes
Pls change as I request, thanks!

2021-07-06 18:45 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
I thinks we should add link for **Starter Bot* page and then users can refer that part if he don't know how to build a starter bot.

2021-07-06 18:45 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +* `emoji`: Define under `heartbeat`, the emoji to send (default: **爱心**)
change  `default: **爱心**` to `[爱心] - Heartbeat emoji`

2021-07-06 18:45 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +For using with **WhatsApp** you can set the contact in the following format:
If you try to introduce WhatsApp here, then I suggest you introduce Wechat and WeCom here.

2021-07-06 18:45 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +    contact: 'cotact_num@c.us', // contact who will receive the emoji
I suggest this using default contact `filehelper` 

`filehelper` is suitable for Wechat puppet, `cotact_num@c.us` is suitable for Whatsapp puppet.

2021-07-06 18:45 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +#### Linux/macOS
I think we should unify the style here, @shwetalsoni did a good job, it looks like this：

![image](https://user-images.githubusercontent.com/6419514/124647062-0d20a200-dec8-11eb-863c-8cff0c1fd114.png)

You can use code like this:

```markdown
<Tabs
  groupId="operating-systems"
  defaultValue="linux"
  values={[
    { label: 'Linux',   value: 'linux', },
    { label: 'macOS',   value: 'mac', },
    { label: 'Windows', value: 'windows', },
  ]
}>

<TabItem value="linux">

```

2021-07-06 18:45 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +
Add video link reference here: https://www.youtube.com/watch?v=tfGZXoe_aA4

2021-07-08 17:46 UTC, lijiarui commented
ping @sbis04

2021-07-08 18:18 UTC, lijiarui commented
Pls resolve the conflict @sbis04

2021-07-08 18:40 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +    contact: 'cotact_num@c.us', // contact who will receive the emoji
@sbis04 It still show as `cotact_num@c.us` here, I think we should change to `filehelper`

2021-07-08 19:05 UTC, sbis04 commented
@lijiarui Have made the CI green.

2021-07-08 20:07 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +
Have added the video link

2021-07-08 20:07 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +#### Linux/macOS
Have added the tabs

2021-07-08 20:07 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +    contact: 'cotact_num@c.us', // contact who will receive the emoji
Have updated it now

2021-07-08 20:07 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +For using with **WhatsApp** you can set the contact in the following format:
As I have updated with `filehelper`, I have removed the reference to WhatsApp.

2021-07-08 20:07 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +* `emoji`: Define under `heartbeat`, the emoji to send (default: **爱心**)
Have updated it.

2021-07-08 20:07 UTC, sbis04 commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
Yes, I'll add the link. Currently, the **Starter Bot** page isn't there on the docs, we have it further down on our proposal timeline. Once, the page is ready we will also update the link here.

2021-07-09 00:49 UTC, sbis04 commented
@lijiarui I have made the suggested changes

2021-07-10 07:25 UTC, lijiarui commented on docusaurus/docs/using-plugin-with-wechaty/heartbeat.md
> +Follow the instructions on the **Starter Bot** page to create the foundation of a Wechaty bot.
@sbis04 Could you file a new issue for this and we can trace this later, then I will ignore this part.

2021-07-10 07:26 UTC, lijiarui approved these changes
LGTM.

And also looking forward for you to file a new issue for the pending part.

2021-07-10 09:23 UTC, lijiarui commented
@sbis04 Please make CI green to match the new rules, see: https://github.com/wechaty/wechaty.js.org/issues/1035

2021-07-10 10:53 UTC, sbis04 commented
@lijiarui I have converted the image to `.webp` format and made the CI green.

2021-07-10 12:15 UTC, huan approved these changes

2021-07-10 12:15 UTC, merged