Using Redux with Wechaty overview
wechaty/docusaurus pull request #989
Opened 2021-06-30 08:28 UTC by shwetalsoni

I have added **Using Redux with Wechaty** under Tutorials. The page is divided into some subsections as shown below:

![Screenshot from 2021-06-30 13-47-03](https://user-images.githubusercontent.com/57187745/123927487-855c0480-d9aa-11eb-863f-ba924f6ffbaa.png)

The PR contains the updated submenu and **Overview** page. In later PR's we''ll include tutorials for respective subsections.

The overview page looks like this:

![Screenshot from 2021-06-30 13-46-30](https://user-images.githubusercontent.com/57187745/123927746-c81ddc80-d9aa-11eb-86a9-01544bf70704.png)
![Screenshot from 2021-06-30 13-46-44](https://user-images.githubusercontent.com/57187745/123927748-c94f0980-d9aa-11eb-871d-61a0e395162e.png)

2021-07-01 17:18 UTC, proudofsimin approved these changes
Just correct some minor mistakes and this is good :)

2021-07-01 17:18 UTC, proudofsimin commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +Using redux with wechaty wraps Wechaty with Redux Actions &amp; Reducers for Easy State Management.
[W]echaty

2021-07-01 17:18 UTC, proudofsimin commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +- Makes it easier to test, maintain and debug the code
Use imperative sentence in the bulleted list, so please remove the s in makes.

2021-07-01 17:18 UTC, proudofsimin commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +The tutorial for **Vannila Redux with Wechaty Redux Plugin** is available [here](using-redux-with-wechaty/vannila-redux.md)
You forgot the period at the end.

2021-07-01 17:18 UTC, proudofsimin commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +The tutorial for **Ducks Proposal Style for Wechaty Redux Plugin** is available [here](using-redux-with-wechaty/ducks-proposal.md)
The period at the end.

2021-07-02 05:49 UTC, shwetalsoni commented
@proudofsimin I have made the suggested changes.

2021-07-04 08:30 UTC, shwetalsoni commented
Tag #891

2021-07-06 19:13 UTC, lijiarui requested changes
Pls change as I request.

2021-07-06 19:13 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +
Pls remove blank lines here.

2021-07-06 19:13 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +> Image Credit: [Alamy](https://www.alamy.com/cute-duck-and-little-ducks-over-white-background-colorful-design-vector-illustration-image185379753.html)
Where is the image? I think you may forget to upload the image here.

2021-07-06 19:13 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +
Pls remove blank line here.

2021-07-07 06:12 UTC, shwetalsoni commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +> Image Credit: [Alamy](https://www.alamy.com/cute-duck-and-little-ducks-over-white-background-colorful-design-vector-illustration-image185379753.html)
The image of **Ducks** is used above.  This is just the credit. Here I guess we have to provide only the link of the image used.

2021-07-07 06:18 UTC, shwetalsoni commented
@lijiarui I have made the requested changes

2021-07-07 17:08 UTC, lijiarui requested changes
Please fix image issue here.

2021-07-07 17:08 UTC, lijiarui commented on docusaurus/docs/using-redux-with-wechaty/overview.md
> +> Image Credit: [Alamy](https://www.alamy.com/cute-duck-and-little-ducks-over-white-background-colorful-design-vector-illustration-image185379753.html)
No, you didn't.

Here is the review of your PR
![image](https://user-images.githubusercontent.com/6419514/124800961-d8c0ea80-df88-11eb-939a-194484103c77.png)

If you open this image https://www.alamy.com/cute-duck-and-little-ducks-over-white-background-colorful-design-vector-illustration-image185379753.html , you could find this image, but it didn't showed in the doc.

![image](https://user-images.githubusercontent.com/6419514/124801040-f3935f00-df88-11eb-9e41-a12184721467.png)

2021-07-07 17:21 UTC, shwetalsoni commented
> Please fix image issue here.

Actually, this image credit section was originally there on the page. So while updating it, I got confused with the image of ducks used above. I thought it was referring to that one. 

I think this image doesn't make sense here. Should I remove it?

2021-07-07 18:59 UTC, lijiarui commented
> I think this image doesn't make sense here. Should I remove it?



> > Please fix image issue here.
> 
> Actually, this image credit section was originally there on the page. So while updating it, I got confused with the image of ducks used above. I thought it was referring to that one.
> 
> I think this image doesn't make sense here. Should I remove it?

I agree with you, remove the credit is a better solution.

2021-07-08 07:48 UTC, shwetalsoni commented
@lijiarui I have removed the image credit.

2021-07-08 12:07 UTC, lijiarui approved these changes
LGTM

2021-07-08 12:29 UTC, huan approved these changes

2021-07-08 15:19 UTC, lijiarui commented
@shwetalsoni Please resolve the conflict and then I will merge this PR.

2021-07-08 18:09 UTC, merged